<?php 
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
     $frm = $this->frm;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<title><?php echo $this->tr->translate("RECEIVECHEQE")?></title>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RECEIVECHEQE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id=='' || branch_id<=0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>');
						dijit.byId('branch_id').focus();
						return false;
					}
					paymentId = dijit.byId('paymentId').get('value');
					if(paymentId=='' || paymentId<=0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_PAYMENT_NO');?>');
						dijit.byId('paymentId').focus();
						return false;
					}
					
					loadingBlock();
					return true;
	  			 }else {
					return false;
	   			}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("branch_id");?>
		                </div>
		             </div>
					
					<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("RECEIVED_CHEQUE_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="issueId" />
							<?php echo $frm->getElement("paymentId");?>
		                </div>
		             </div>  
					
					 <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("WITHDRAW_DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("withdrawDate");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("noteWithdraw");?>
		                </div>
		             </div>
					  <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("statusWithdraw");?>
		                </div>
		             </div>
				</div>
				<div class="col-md-8 col-sm-8 col-xs-12">
					<div id="request-info"></div>
				 </div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE_CLOSE");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="submit" value="save_close" id="save_new" name="save_new" label="<?php echo $tr->translate("SAVENEW");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
    </div>
</div>
<style>
div#request-info .form-group {
	display: block;
	font-size: 12px;
	background: #fdfbbd;
	border: solid 2px #dc0303;
	border-radius: 5px;
}
div#request-info .form-group ul li span.lbl-tt {
	color: #02014a;
}
span.red {
	color: #f00;
	font-weight: bold;
}
div#request-info .form-group ul {
    margin: 0;
    padding: 0px 5px;
}
div#request-info .form-group ul li {
	display: inline-block;
	width: 47%;
	vertical-align: top;
}
</style>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
    dojo.require("dijit.form.Textarea");
    dojo.require("dijit.form.NumberTextBox");
    dojo.require("dijit.form.DateTextBox");
	
	currentProjectId ='<?php echo empty($this->row['projectId'])?0:$this->row['projectId']; ?>';
	currentIssueId ='<?php echo empty($this->row['id'])?0:$this->row['id']; ?>';
	
	var issueIdStore  = getDataStorefromJSON('id','name', null );
    require(["dojo/ready"], function(ready){
		ready(function(){
			<?php if(!empty($this->row['projectId'])){?>
			dijit.byId('branch_id').set('value', currentProjectId);
			<?php } ?>
			
			onChageFunctionByBranch();
		});

		new dijit.form.FilteringSelect({
			store: issueIdStore,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,		           
			name: "issueId",
			placeHolder:'<?php echo $tr->translate('PAYMENT_NO');?>',
			id: "issueId",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				getIssueInfo();
			}
		}, "issueId");
	 
	 });
	 
	 function onChageFunctionByBranch(){
		 getAllIssue();
	 }
	
	var urlGetAllPayment = '<?php echo $this->url(array('module'=>'invpayment','controller'=>'issuecheque','action'=>'getallissuecheque')); ?>';
	function getAllIssue(){
		dijit.byId('issueId').reset();
		issueIdStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('issueId').set('store', issueIdStore);
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id<=0){
			branch_id = 0;
		}
		dojo.xhrPost({
			url:urlGetAllPayment,	
			content:{ 
				'branch_id':branch_id,
			},		    
			handleAs:"json",
			load: function(data) {
				issueIdStore  = getDataStorefromJSON('id','name', data);		
				dijit.byId('issueId').set('store', issueIdStore);
				<?php if(!empty($this->reqResult['projectId'])){?>
				dijit.byId('issueId').set('value', currentIssueId);
				<?php } ?>
				
			},
			error: function(err) {
			}
		});
	}
	var urlGetIssueInfo = '<?php echo $this->url(array('module'=>'invpayment','controller'=>'issuecheque','action'=>'getissueinfo')); ?>';
	function getIssueInfo(){
		
		dijit.byId('paymentId').set('value',0);
		issueId = dijit.byId('issueId').get('value');
		if(issueId=='' || issueId==0){
			dojo.byId("request-info").innerHTML = '';
			return false;
		}
		
		dojo.xhrPost({
			url: urlGetIssueInfo,
			content:{
				'issueId':issueId
				},
			handleAs:"json",
			load: function(data) {
				if(data!=''){
					dijit.byId('paymentId').set('value', data.paymentId);
				}
				getPaymentInfo();
			},
			error: function(err) {
			}
		});
	}
	var urlGetPaymentInfo = '<?php echo $this->url(array('module'=>'invpayment','controller'=>'payment','action'=>'getpaymentinfo')); ?>';
	function getPaymentInfo(){

		paymentId = dijit.byId('paymentId').get('value');
		if(paymentId=='' || paymentId==0){
			dojo.byId("request-info").innerHTML = '';
			return false;
		}
		dojo.xhrPost({
			url: urlGetPaymentInfo,
			content:{
				'paymentId':paymentId
				},
			handleAs:"json",
			load: function(data) {
				var string='';
				if(data!=''){
				string+='<div class="form-group" style=" padding: 10px; ">';
					string+='<span class="note_score"><i class="fa fa-file-text-o" aria-hidden="true"></i> <?php echo $tr->translate("PAYMENT_INFO");?></span>';
					string+='<ul>';
						string+='<li><span class="lbl-tt"><?php echo $tr->translate("INVOICE_NO");?></span>: <span class="red">'+data.invoiceNoList+'</span></li>';
						string+='<li><span class="lbl-tt"><?php echo $tr->translate("PAYMENT_METHOD");?></span>: <span class="red">'+data.paymentMethodTitle+'</span></li>';
						
						string+='<li><span class="lbl-tt"><?php echo $tr->translate("SUPPLIER_INVOICE");?></span>: <span class="red">'+data.supplierInvoiceNoList+'</span></li>';
						string+='<li><span class="lbl-tt"><?php echo $tr->translate("BANK");?></span>: <span class="red">'+data.bankName+'</span></li>';
						
						string+='<li><span class="lbl-tt"><?php echo $tr->translate("PAYMENT_DATE");?></span>: <span class="red">'+data.paymentDateDMY+'</span></li>';
						string+='<li><span class="lbl-tt"><?php echo $tr->translate("ACCOUNT_AND_CHEQUE_NO");?></span>: <span class="red">'+data.accNameAndChequeNo+'</span></li>';
					string+='</ul>';
				string+='</div>';
				
				
				}
				dojo.byId("request-info").innerHTML = string;
			},
			error: function(err) {
			}
		});
	}
</script>