<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD_SUPPLIER'));
?>	
<?php  $techer= $this->frm_co;?>
<script>
	dojo.require("dijit/form/DateTextBox");
	dojo.require("dijit.form.ValidationTextBox");
</script>
<div class="card">
	<div class="card-content collapse show">
		<form  id='add_techer' action="<?php echo $this->url(array('module'=>'group','controller'=>'supplier','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					dijit.byId('save_new').set('disabled',true);
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_SUPPLIER');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('SUPPLIER_INFO')?> </p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $techer->getElement('branch_id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CODE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $techer->getElement('supplier_code'); echo $techer->getElement('id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SUPPLIER_NAME");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $techer->getElement('name');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	             </div>
	             <div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-phone-alt" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('CONTACT_INFO')?> </p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $techer->getElement('tel');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("EMAIL");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $techer->getElement('email');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ADDRESS");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $techer->getElement('address');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $techer->getElement('note');?>
											<input type="hidden" id="page" name="page" value="<?php echo $this->page?>" />
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	             </div>
	        </div>
	        <div class="clearfix"></div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" id="save_new" value="save_new" name="save_new" label="<?php echo $tr->translate("SAVE");?>" dojoType="dijit.form.Button" />
	    		</div>
	    	</div>
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.ready(function(){
	$(window).keydown(function(event){
		if(event.keyCode == 13) {
		  event.preventDefault();
		  return false;
		}
	  });
});
var url_staffcode = '<?php echo $this->url(array('module'=>'group','controller'=>'supplier','action'=>'getstaffcode')); ?>';
function getStaffCode(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('supplier_code').attr('value','');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_staffcode,	
		content:{ 
		    'branch_id':branch_id,
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('supplier_code').attr('value',data);
		},
		error: function(err) {
		}
	});
}
</script>