<?php 
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
     $frm = $this->frm;	
	 $db = new Po_Model_DbTable_DbDirectPO();
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<title><?php echo $this->tr->translate("COPY_DIRECT_PURCHASING")?></title>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-copy" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('DIRECT_PURCHASING');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id=='' || branch_id<=0){
						infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>');
						dijit.byId('branch_id').focus();
						return false;
					}
					
					supplierId = dijit.byId('supplierId').get('value');
					if(supplierId=='' || supplierId<=0){
						infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_SUPPLIER');?>');
						dijit.byId('supplierId').focus();
						return false;
					}
					var rowId = $('#identity').val();
					if(rowId==''){ 
						infoMessageAlert("<?php echo $tr->translate("PLEASE_ADD_RECORD");?>");
						return false;
					}
					loadingBlock();
					return true;
	  			 }else {
					return false;
	   			}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-open-file" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("PURCHASING_INFO");?></p>
										</div> 
									</div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH_NAME");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_id");?>
											<?php echo $frm->getElement("id");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUPPLIER");?> </label>
										<div class="col-md-4 col-sm-4 col-xs-12">
											<?php echo $frm->getElement("supplierId");?>
										</div>
										<div class="col-md-3 col-sm-3 col-xs-12">
											<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("GET_DATA");?>" onclick="getRefreshData();" />
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PO_NO");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("purchaseNo");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DATE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("date");?>
										</div>
									 </div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-info " aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("OTHER_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PURCHASING_PURPOSE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("purpose");?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("note");?>
										</div>
									</div>
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="form-group" style="background: #d8e0e2;padding: 5px 15px;margin: 0;border: solid 1px #697996;border-radius: 2px;margin-top: 10px;">
						<label style=" margin: 0; line-height: 30px; " class="control-label bold col-md-2 col-sm-2 col-xs-12"><?php echo $tr->translate("CATEGORY");?> </label>
						 <div class="col-md-3 col-sm-3 col-xs-12">
								<?php echo $frm->getElement("categoryId");?>
						</div>
						<label style=" margin: 0; line-height: 30px; text-align: center;" class="control-label bold col-md-1 col-sm-1 col-xs-12"><?php echo $tr->translate("PRODUCT");?> </label>
						<div class="col-md-3 col-sm-3 col-xs-12">
							<input id="productId" />
						</div>
						
					</div>

					<div class="card-box">
						<ul class="nav  md-pills pills-primary nav-tab" role="tablist">
							<li class="nav-item active">
								<a class="nav-link " data-toggle="tab" href="#panel21" role="tab">
									<i class="fa fa-tasks ml-2"></i>
								 <?php echo $tr->translate("PRODUCT");?></a>
							</li>
							<li class="nav-item">
								<a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
								<i class="fa fa fa-calendar ml-2"></i> <?php echo $tr->translate("SCHEDULE");?>
								</a>
							</li>
						</ul>
					</div>
					<div class="tab-content vertical">
						<div class="tab-pane fade in active" id="panel21" role="tabpanel">
								<table class="collape responsiveTable tbPOItems"  >
									<thead>
										<tr id="head-title" class="head-td" align="center">
											<th scope="col" rowspan="2"><?php echo $tr->translate("DEL");?></th>
											<th scope="col" rowspan="2"><?php echo $tr->translate("N_O");?></th>
											
											<th scope="col" colspan="4" ><?php echo $tr->translate("PRODUCT_INFO");?></th>
											<th scope="col" colspan="2" ><?php echo $tr->translate("DISCOUNT_INFO");?></th>
											
										</tr>
										<tr  class="head-td" align="center">
											<th scope="col" width="20%"><?php echo $tr->translate("PRODUCT_NAME");?></th>
											<th scope="col" class="currentQty"><?php echo $tr->translate("STOCK_REMAIN");?></th>
											<th scope="col" width="10%"><?php echo $tr->translate("QTY");?></th>
											<th scope="col" width="20%"><?php echo $tr->translate("UNIT_PRICE");?></th>
											
											<th scope="col" width="10%"><?php echo $tr->translate("DISCOUNT_PERCENT");?></th>
											<th scope="col" width="10%"><?php echo $tr->translate("DISCOUNT")." ".$tr->translate("CURRENCY_SIGN");?></th>
										</tr>
									</thead>
									<tbody id="table_row">
									</tbody>
								</table>
								
								<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
								<div class="form-group" style="margin-bottom: 0;">
									<label class="control-label bold col-md-7 col-sm-7 col-xs-12" style="text-align:right;"><?php echo $tr->translate("TOTAL")." ".$tr->translate("CURRENCY_SIGN");?> </label>
									<div class="col-md-5 col-sm-5 col-xs-12">
										<?php echo $frm->getElement("total");?>
									</div>
								</div>

						</div>

						<div class="tab-pane fade in " id="panel22" role="tabpanel">
								<table class="collape responsiveTable" >
									<thead>
										<tr id="head-title" class="head-td" align="center">
											<th scope="col"><?php echo $tr->translate("N_O");?></th>
											<th scope="col" width="40%"><?php echo $tr->translate("PRODUCT_NAME");?></th>
											<th scope="col" width="40%"><?php echo $tr->translate("DATE_ENTRY");?></th>	
										</tr>
									</thead>
									<tbody id="table_product_schedule">
									</tbody>
								</table>
								<input type="hidden" name="identity_product_schedule" id="identity_product_schedule" dojoType="dijit.form.TextBox" value="" >
								
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE");?>" dojoType="dijit.form.Button" />
					
               	</div>
             </div>
		</form>
    </div>
</div>
<?php if (!empty($this->rowdetail)) foreach ($this->rowdetail as $key=> $rs){?>
	<div id="proCode<?php echo $key?>" style="display: none;"><?php echo $rs['proCode'];?></div>
	<div id="productName<?php echo $key?>" style="display: none;"><?php echo $rs['proName'];?></div>
	<div id="measureTitle<?php echo $key?>" style="display: none;"><?php echo $rs['measureTitle'];?></div>
	<div id="itemsNote<?php echo $key?>" style="display: none;"><?php echo $rs['note'];?></div>
<?php } ?>

<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
    dojo.require("dijit.form.Textarea");
    dojo.require("dijit.form.NumberTextBox");
    dojo.require("dijit.form.DateTextBox");

	
	var productStore  = getDataStorefromJSON('id','name', null );
    require(["dojo/ready"], function(ready){
		ready(function(){
			onChageFunctionByBranch();
			dijit.byId("branch_id").set("readOnly",true);
			initailize();
		});

		new dijit.form.FilteringSelect({
			store: productStore,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,		           
			name: "productId",
			placeHolder:'<?php echo $tr->translate('PRODUCT_NAME');?>',
			id: "productId",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				addRowProductPO();
			}
		}, "productId");
	 });
    
	function onChageFunctionByBranch(){
		
		
		getAllProduct();
		getPurchaseNoByBranch();
	
	}
	var urlGetRequestNo = '<?php echo $this->url(array('module'=>'po','controller'=>'index','action'=>'getpurchaseno')); ?>';
	function getPurchaseNoByBranch(){
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id<=0){
			return false;
		}
		dateRequest = dijit.byId('date').get('value');
		if(dateRequest==''){
			infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_DATE');?>');
			dijit.byId('date').focus();
			return false;
		}
			var a = new Date(dateRequest);
			mm = a.getMonth()+1;
			var dd = a.getDate();
			 if(dd<10){
				 dd = "0"+dd;
			}
			//month = returnMOnth(mm);
			month=mm;
			if(mm<10){
				 month = "0"+mm;
			}
			
			var y = a.getFullYear();
			var dateRequest = dd +'-'+month+'-'+y ;
	
		dojo.xhrPost({
			url:urlGetRequestNo,	
			content:{ 
				'branch_id':branch_id,'dateRequest':dateRequest
			},		    
			handleAs:"json",
			load: function(data) {
				dijit.byId('purchaseNo').set('value', data);
			},
			error: function(err) {
			}
		});
	} 	
	
	var urlGetAllProduct = '<?php echo $this->url(array('module'=>'requesting','controller'=>'request','action'=>'getallproduct')); ?>';
	function getAllProduct(){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id<=0){
			branch_id = 0;
		}
		categoryId = dijit.byId('categoryId').get('value');
		if(categoryId=='' || categoryId==0){
			categoryId=0;
		}
		
		
		var urlGetAllProduct = '<?php echo $this->url(array('module'=>'requesting','controller'=>'request','action'=>'getallproduct')); ?>';
		objectContentFilter = {'branch_id':branch_id,'categoryId':categoryId};
		getAllProductStoreFunction(urlGetAllProduct,objectContentFilter);
		
	}

	function addNewSupplier(){
		supplierId = dijit.byId('supplierId').get('value');
		if(supplierId==-1){
			window.open('<?php echo $this->baseUrl();?>/po/supplier/add?isAddSupplier=1');
			dijit.byId('supplierId').reset();
		}
	}

	var urlGetAllSuppilyer = '<?php echo $this->url(array('module'=>'po','controller'=>'supplier','action'=>'getallsupplier')); ?>';
	function getRefreshData(){
			
		dojo.xhrPost({
			url:urlGetAllSuppilyer,	
			handleAs:"json",
			load: function(data) {
				supplierStore  = getDataStorefromJSON('id','name', data);	
			    dijit.byId('supplierId').set('store',supplierStore);
				
				
			},
			error: function(err){
			}
		});
		
	}
	
	var col= 0; var no=0;
	var title = 0;
	var urlGetProductInfo = '<?php echo $this->url(array('module'=>'requesting','controller'=>'request','action'=>'productinfo')); ?>';
	function addRowProductPO(){
		
		template='';
		temp = "";
		
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id<=0){
			infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>');
			dijit.byId('branch_id').focus();
			return false;
		}

		productId = dijit.byId('productId').get('value');
		productLabel = dijit.byId('productId').attr('displayedValue');
		if(productId=='' || productId<=0){
			//infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_PRODUCT');?>');
			dijit.byId('productId').reset();
			dijit.byId('productId').focus();
			return false;
		}
		
		var iden = $("#identity").val();
		var arrays = iden.split(',');
		 if(arrays!=""){
			 for(var i=0;i< arrays.length;i++) {
				 readychoose = dijit.byId('proId'+arrays[i]).get('value');
				 if(readychoose==productId){
					 infoMessageAlert("<?php echo $tr->translate("Choosen ready")?> "+productLabel);
					 dijit.byId('productId').reset();
					 return false;
				 }
			}
		}
		col++;no++;
		
		
		dojo.xhrPost({
			url:urlGetProductInfo,	
			content:{ 
				'branch_id':branch_id,'productId':productId
			},		    
			handleAs:"json",
			load: function(data) {
				var lastUnitPrice = data.latestUnitPrice;	
				var subTotalRow = lastUnitPrice;
				
				template+='<td rowspan="2" class="numberRecord infoCol" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD");?>" class="removeRow" onclick="deleteRecord('+col+');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span></td>';
				template+='<td rowspan="2" align="center" class="numberRecord infoCol" data-label="<?php echo $tr->translate("N_O");?>">'+no+'</td>';
				template+='<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" class="productName infoCol" >'+data.proCode+'<br />'+data.proName+'<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="proId'+col+'" name="proId'+col+'" value="'+data.id+'" type="text"  ></td>';	
				template+='<td data-label="<?php echo $tr->translate("STOCK_REMAIN");?>" class="currentQty infoCol"  width="5%">'+data.currentQty+' ('+data.measureTitle+')</td>';	
				template+='<td data-label="<?php echo $tr->translate("QTY");?>" ><input required dojoType="dijit.form.NumberTextBox" class="fullside" data-dojo-props="constraints:{min:0.01},rangeMessage:'+"'<?php echo $tr->translate("MINIMUM_VALUE_IS_ZEROONE");?>'"+'" onKeyup="calculateTotal('+col+');" id="qty'+col+'" name="qty'+col+'" placeholder="'+'<?php echo $tr->translate("QTY");?>" value="1" type="text"  ></td>';	
				template+='<td data-label="<?php echo $tr->translate("UNIT_PRICE");?>"><input required dojoType="dijit.form.NumberTextBox" class="fullside" data-dojo-props="constraints:{min:0.01},rangeMessage:'+"'<?php echo $tr->translate("MINIMUM_VALUE_IS_ZEROONE");?>'"+'" onKeyup="calculateTotal('+col+');" id="unitPrice'+col+'" name="unitPrice'+col+'" placeholder="'+'<?php echo $tr->translate("UNIT_PRICE");?> " value="'+lastUnitPrice+'" type="text"  ></td>';	
				
				
				template+='<td data-label="<?php echo $tr->translate("DISCOUNT_PERCENT");?>">';	
				template+='<input dojoType="dijit.form.NumberTextBox" class="fullside" data-dojo-props="constraints:{min:0,max:100},rangeMessage:'+"'<?php echo $tr->translate("MAX_VALUE_IS");?> 100'"+'"  onKeyup="calculateTotal('+col+');" id="discountPercent'+col+'" name="discountPercent'+col+'" placeholder="'+'<?php echo $tr->translate("DISCOUNT_PERCENT");?> " value="0" type="text"  >';	
				template+='</td>';	
				template+='<td data-label="<?php echo $tr->translate("DISCOUNT");?>">';	
					template+='<input dojoType="dijit.form.NumberTextBox" class="fullside"  onKeyup="calculateTotal('+col+');" id="discountAmount'+col+'" name="discountAmount'+col+'" placeholder="'+'<?php echo $tr->translate("DISCOUNT")." ".$tr->translate("CURRENCY_SIGN");?> " value="0" type="text"  >';	
					template+='<input dojoType="dijit.form.TextBox" class="fullside"   id="totalDiscount'+col+'" name="totalDiscount'+col+'"  value="0" type="hidden"  >';	
				template+='</td>';
				
		
				templateii='';
				templateii+='<td colspan="4" class="infoCol" data-label="<?php echo $tr->translate("NOTE");?>"><input dojoType="dijit.form.TextBox" class="fullside" id="note'+col+'" name="note'+col+'" placeholder="'+'<?php echo $tr->translate("NOTE");?> " value="" type="text"  ></td>';	
				templateii+='<td colspan="4" class="red bold" data-label="<?php echo $tr->translate("SUB_TOTAL");?>"><input readOnly dojoType="dijit.form.NumberTextBox" class="fullside"   id="subTotal'+col+'" name="subTotal'+col+'" placeholder="'+'<?php echo $tr->translate("SUB_TOTAL");?> " value="'+subTotalRow+'" type="text"  ></td>';	
			
			
				tmp='<tr class="rowData" id="row'+col+'">';
				tmp+="</tr>";
				tmp+='<tr class="rowData" id="rowii'+col+'">';
				tmp+="</tr>";
				
				dojo.query("#table_row").append(tmp);
				if($("#identity").val()!="") {
					var identity = $("#identity").val();
					$("#identity").val(identity+','+col);
				} else {$("#identity").val(col);}
				dojo.html.set(dojo.byId("row"+col),template , {
					 parseContent: true,
				});
				
				dojo.html.set(dojo.byId("rowii"+col),templateii , {
					 parseContent: true,
				});
				
				dijit.byId('productId').reset();
				netTotal();
				addRowProductSchetdule(data.proName, data.id);
			},
			error: function(err) {
			}
		});
	}
	
	function calculateTotal(index){
		unitPrice = dijit.byId('unitPrice'+index).get('value');
		unitPrice=isNaN(unitPrice)?0:unitPrice;
		
		discountAmount = dijit.byId('discountAmount'+index).get('value');
		discountAmount=isNaN(discountAmount)?0:discountAmount;
		
		discountPercent = dijit.byId('discountPercent'+index).get('value');
		discountPercent=isNaN(discountPercent)?0:discountPercent;
		if(discountPercent>100){
			discountPercent=100;
		}
		
		qty = dijit.byId('qty'+index).get('value');
		qty=isNaN(qty)?0:qty;
		
		var subtotal=0;
		subtotal = (qty*unitPrice);
		
		discountPercentAmt = parseFloat(subtotal*discountPercent/100);
		subtotal = subtotal-discountPercentAmt;
		if(discountAmount>subtotal){
			dijit.byId('subTotal'+index).set('value',0);
			dijit.byId('discountAmount'+index).set('value',subtotal);
			infoMessageAlert("<?php echo $tr->translate("DISCOUNT_CAN_NOT_BIGER_THAN_TOTAL")?>"+" "+subtotal);
			netTotal();
			return false;
		}
		subtotal=subtotal-discountAmount;
		totalDiscount = (discountAmount+discountPercentAmt).toFixed(3);
		dijit.byId('totalDiscount'+index).set('value',totalDiscount);
		
		dijit.byId('subTotal'+index).set('value',subtotal);
		netTotal();
	}
	function netTotal(){
		var netTotal=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		if(rowId==''){
			infoMessageAlert("<?php echo $tr->translate('PLEASE_SELECT_PRODUCT');?>");
			dijit.byId("productId").focus();
			dijit.byId('total').attr('value',netTotal.toFixed(3));
			return false;
		}
		for(var n = 0; n < rowIDArray.length; n++) {
			netTotal += dijit.byId('subTotal'+rowIDArray[n]).get('value');
		}
		dijit.byId('total').attr('value',netTotal.toFixed(3));
	}
	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
		dojo.query("#rowii"+index).remove();
		netTotal();
		deleteProductSceduleRow(index);
	}
	
	function initailize() {
		<?php if (!empty($this->rowdetail)) foreach ($this->rowdetail as $key=> $rs){?>
		col++;no++;
		template='';
		temp = "";
		
		var proCodeString = $( '#proCode'+'<?php echo $key;?>').html();
		var productNameString = $( '#productName'+'<?php echo $key;?>').html();
		var measureTitleString = $( '#measureTitle'+'<?php echo $key;?>').html();
		var itemsNoteString = $( '#itemsNote'+'<?php echo $key;?>').html();
		
		template+='<td rowspan="2" class="numberRecord infoCol" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD");?>" class="removeRow" onclick="deleteRecord('+col+');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span></td>';
		template+='<td rowspan="2" align="center" class="numberRecord infoCol" data-label="<?php echo $tr->translate("N_O");?>">'+no+'<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="detailId'+col+'" name="detailId'+col+'" value="<?php echo $rs['id'];?>" type="text"  ></td>';
		template+='<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" class="productName infoCol" >'+proCodeString+'<br />'+productNameString+'<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="proId'+col+'" name="proId'+col+'" value="<?php echo $rs['proId'];?>" type="text"  ></td>';	
		template+='<td data-label="<?php echo $tr->translate("STOCK_REMAIN");?>" class="currentQty infoCol"  ><?php echo $rs['currentQty'];?> ('+measureTitleString+')</td>';	
		template+='<td data-label="<?php echo $tr->translate("QTY");?>"><input required data-dojo-props="constraints:{min:0.01},rangeMessage:'+"'<?php echo $tr->translate("MINIMUM_VALUE_IS_ZEROONE");?>'"+'" dojoType="dijit.form.NumberTextBox" class="fullside"  onKeyup="calculateTotal('+col+');" id="qty'+col+'" name="qty'+col+'" placeholder="'+'<?php echo $tr->translate("QTY");?>" value="<?php echo $rs['qty'];?>" type="text"  ></td>';	
		template+='<td data-label="<?php echo $tr->translate("UNIT_PRICE");?>"><input required data-dojo-props="constraints:{min:0.01},rangeMessage:'+"'<?php echo $tr->translate("MINIMUM_VALUE_IS_ZEROONE");?>'"+'" dojoType="dijit.form.NumberTextBox" class="fullside"  onKeyup="calculateTotal('+col+');" id="unitPrice'+col+'" name="unitPrice'+col+'" placeholder="'+'<?php echo $tr->translate("UNIT_PRICE");?> " value="<?php echo $rs['unitPrice'];?>" type="text"  ></td>';	
		
		template+='<td data-label="<?php echo $tr->translate("DISCOUNT_PERCENT");?>">';	
		template+='<input dojoType="dijit.form.NumberTextBox" class="fullside" data-dojo-props="constraints:{min:0,max:100},rangeMessage:'+"'<?php echo $tr->translate("MAX_VALUE_IS");?> 100'"+'"  onKeyup="calculateTotal('+col+');" id="discountPercent'+col+'" name="discountPercent'+col+'" placeholder="'+'<?php echo $tr->translate("DISCOUNT_PERCENT");?> " value="<?php echo $rs['discountPercent'];?>" type="text"  >';	
		template+='</td>';	
		template+='<td data-label="<?php echo $tr->translate("DISCOUNT");?>">';	
			template+='<input dojoType="dijit.form.NumberTextBox" class="fullside"  onKeyup="calculateTotal('+col+');" id="discountAmount'+col+'" name="discountAmount'+col+'" placeholder="'+'<?php echo $tr->translate("DISCOUNT")." ".$tr->translate("CURRENCY_SIGN");?> " value="<?php echo $rs['discountAmount'];?>" type="text"  >';	
			template+='<input dojoType="dijit.form.TextBox" class="fullside"   id="totalDiscount'+col+'" name="totalDiscount'+col+'"  value="<?php echo $rs['totalDiscount'];?>" type="hidden"  >';	
		template+='</td>';
				
		templateii='';
		templateii+='<td colspan="4" class="infoCol" data-label="<?php echo $tr->translate("NOTE");?>"><input dojoType="dijit.form.TextBox" class="fullside" id="note'+col+'" name="note'+col+'" placeholder="'+'<?php echo $tr->translate("NOTE");?> " value="'+itemsNoteString+'" type="text"  ></td>';	
		templateii+='<td colspan="4" class="red bold" data-label="<?php echo $tr->translate("SUB_TOTAL");?>"><input readOnly dojoType="dijit.form.NumberTextBox" class="fullside"  id="subTotal'+col+'" name="subTotal'+col+'" placeholder="'+'<?php echo $tr->translate("SUB_TOTAL");?> " value="<?php echo $rs['subTotal'];?>" type="text"  ></td>';	
			
			
		tmp='<tr class="rowData" id="row'+col+'">';
		tmp+="</tr>";
		tmp+='<tr class="rowData" id="rowii'+col+'">';
		tmp+="</tr>";
		
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
		
		dojo.html.set(dojo.byId("rowii"+col),templateii , {
			 parseContent: true,
		});
		
		<?php }?>
		initailizeScheduleProduct()

	}

	var col_sub= 0; 
	function productSchedule(pro_id, col){
		template='';
		temp = "";
	
		var iden = $("#identity_schedule"+col).val();
		var arrays = iden.split(',')
		col_sub++;
				template+='<td class="numberRecord" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD");?>" class="removeRow" onclick="deleteScheduleRecord('+col_sub+', '+col+');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span></td>';
				template+='<td data-label="<?php echo $tr->translate("DATE_ENTRY");?>"><input required dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'+"'dd/MM/yyyy'"+'}" id="schedule_date'+col+'_'+col_sub+'" name="schedule_date'+col+'_'+col_sub+'" placeholder="'+'<?php echo $tr->translate("DATE_ENTRY");?> " value="now" type="text"  ></td>';	
				template+='<td data-label="<?php echo $tr->translate("NOTE");?>" ><input  type="text" name="schedule_note'+col+'_'+col_sub+'" id="schedule_note'+col+'_'+col_sub+'" dojoType="dijit.form.TextBox" class="fullside" placeholder="'+'<?php echo $tr->translate("NOTE");?> " value=""  ></td>';	
				tmp='<tr class="rowData" id="row_pro'+col_sub+'">';
				tmp+="</tr>";

				dojo.query("#schedule_row"+col).append(tmp);
				if($("#identity_schedule"+col).val()!="") {
					var identity = $("#identity_schedule"+col).val();
					$("#identity_schedule"+col).val(identity+','+col_sub);
				} else {$("#identity_schedule"+col).val(col_sub);}
				dojo.html.set(dojo.byId("row_pro"+col_sub),template , {
					 parseContent: true,
				});	
	}

    function initailizeScheduleProduct() {
		
		<?php if (!empty($this->rowdetail)) foreach ($this->rowdetail as $rs){?>
		
		col1++;no1++;
		template='';
		temp = "";
		template+='<td align="center" class="numberRecord" data-label="<?php echo $tr->translate("N_O");?>">'+no1+'<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="pro_scheduleId'+col1+'" name="pro_scheduleId'+col1+'" value="<?php echo $rs['id'];?>" type="text"  ></td>';
		template+='<td width="30%" align="center" data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" class="productName" ><?php echo $rs['proName'];?><input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="pro_id'+col1+'" name="pro_id'+col1+'" value="<?php echo $rs['proId'];?>" type="text"  ></td>';	
		template+='<td width="50%" align="left"  data-label="<?php echo $tr->translate("SCHEDULE");?>"> <table> <tbody id="schedule_row'+col1+'"> </tbody> </table> <input type="hidden" name="identity_schedule'+col1+'" id="identity_schedule'+col1+'" dojoType="dijit.form.TextBox" value="" ><input  type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-sort-by-attributes" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("ADD_SCHEDULE");?>" onClick=" productSchedule('+<?php echo $rs['proId'];?>+', '+col1+') "></td>';
		
		tmp='<tr class="rowData" id="row_schedule'+col1+'">';
		tmp+="</tr>";
		dojo.query("#table_product_schedule").append(tmp);
		if($("#identity_product_schedule").val()!="") {
			var identity = $("#identity_product_schedule").val();
			$("#identity_product_schedule").val(identity+','+col1);
		} else {$("#identity_product_schedule").val(col1);}
		dojo.html.set(dojo.byId("row_schedule"+col1),template , {
		     parseContent: true,
		});

		<?php
		$row = $db->getPOScheduleDetailById($rs['purchaseId'] , $rs['proId']);  
		if(!empty($row)) foreach($row as $rr){  ?>
	
			template='';
			temp = "";
			col_sub++;
			template+='<td class="numberRecord" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD");?>" class="removeRow" onclick="deleteScheduleRecord('+col_sub+', '+col1+');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span><input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="scheduleId'+col1+'_'+col_sub+'" name="scheduleId'+col1+'_'+col_sub+'" value="<?php echo $rr['id'];?>" ></td>';
			template+='<td data-label="<?php echo $tr->translate("DATE_ENTRY");?>"><input required dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'+"'dd/MM/yyyy'"+'}" id="schedule_date'+col1+'_'+col_sub+'" name="schedule_date'+col1+'_'+col_sub+'" placeholder="'+'<?php echo $tr->translate("DATE_ENTRY");?> " value="<?php echo $rr['schedule']; ?>" type="text"  ></td>';	
			template+='<td data-label="<?php echo $tr->translate("NOTE");?>" ><input  type="text" name="schedule_note'+col1+'_'+col_sub+'" id="schedule_note'+col1+'_'+col_sub+'" dojoType="dijit.form.TextBox" class="fullside" placeholder="'+'<?php echo $tr->translate("NOTE");?> " value="<?php echo $rr['note']; ?>"  ></td>';	
			tmp='<tr class="rowData" id="row_pro'+col_sub+'">';
			tmp+="</tr>";

			dojo.query("#schedule_row"+col1).append(tmp);
			if($("#identity_schedule"+col1).val()!="") {
				var identity = $("#identity_schedule"+col1).val();
					$("#identity_schedule"+col1).val(identity+','+col_sub);
				} else {$("#identity_schedule"+col1).val(col_sub);}
				dojo.html.set(dojo.byId("row_pro"+col_sub),template , {
					 parseContent: true,
			});	
		
		<?php }  
		}?>	
		
	}



	var col1= 0; var no1=0;
	var title1 = 0;
	function addRowProductSchetdule(pro_name, pro_id){
		
		template='';
		temp = "";
		var iden = $("#identity_product_schedule").val();
		var arrays = iden.split(',');
		col1++;no1++;
				
				template+='<td align="center" class="numberRecord" data-label="<?php echo $tr->translate("N_O");?>">'+no1+'</td>';
				template+='<td width="30%" align="center" data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" class="productName" >'+pro_name+'<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="pro_id'+col1+'" name="pro_id'+col1+'" value="'+pro_id+'" type="text"  ></td>';
				template+='<td width="50%" align="left"  data-label="<?php echo $tr->translate("SCHEDULE");?>"> <table> <tbody id="schedule_row'+col1+'"> </tbody> </table> <input type="hidden" name="identity_schedule'+col1+'" id="identity_schedule'+col1+'" dojoType="dijit.form.TextBox" value="" ><input  type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-sort-by-attributes" dojoType="dijit.form.Button"  label="<?php echo $tr->translate("ADD_SCHEDULE");?>" onClick=" productSchedule('+pro_id+', '+col1+') "></td>';	
				tmp='<tr class="rowData" id="row_schedule'+col1+'">';
				tmp+="</tr>";
				dojo.query("#table_product_schedule").append(tmp);
				if($("#identity_product_schedule").val()!="") {
					var identity = $("#identity_product_schedule").val();
					$("#identity_product_schedule").val(identity+','+col1);
				} else {$("#identity_product_schedule").val(col1);}
				dojo.html.set(dojo.byId("row_schedule"+col1),template , {
					 parseContent: true,
				});	
				productSchedule(pro_id, col1);
	}

	function deleteProductSceduleRow(index){
		var identity = $('#identity_product_schedule').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity_product_schedule').val(strings);
		dojo.query("#row_schedule"+index).remove();

	}

	function deleteScheduleRecord(index, col) {

		var identity = $('#identity_schedule'+col).val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity_schedule'+col).val(strings);
		dojo.query("#row_pro"+index).remove();
	
	}

</script>