<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('LAND_BLOG'));
?>	
<?php  $property= $this->frm_land_blog;?>
<script>
	dojo.require("dijit/form/DateTextBox");
	dojo.require("dijit/form/NumberTextBox");
	dojo.ready(function(){
		//getStaffCode();
		});
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
            <div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-map-marker" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('LAND_BLOG');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form  id='add_techer' action="<?php echo $this->url(array('module'=>'property','controller'=>'blog','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				/*if(dijit.byId('province').get('value')==''){
					alert('Province required');
					return false;
			    }*/
				return true;
			} else {
				return false;
			}
			</script>

		    <div class="card-box">
	    		<div class="col-md-6 col-sm-6 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TITLE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php  echo $property->getElement('title_kh');?>
	                   </div>
	                </div>	
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php  echo $property->getElement('note');?>
	                   </div>
	                </div>	
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php  echo $property->getElement('status');?>
	                   </div>
	                </div>	
	                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
						<input type="hidden" name="exchangefrom" value="2" />
									<input type="reset" value="សំអាត" label="សំអាត"dojoType="dijit.form.Button"/>
									<input type="submit" value="save_close" name="save_close" label="រក្សាទុក+បិត" dojoType="dijit.form.Button"
									iconClass="dijitEditorIcon dijitEditorIconSave" /> 
	    			</div>
	             </div>
	         </div>
         </form>
	</div>
</div>
