<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("LAND_BLOG"));
$frm = $this->frm_property_type;
$url_delete =$this->url(array('module'=>'property','controller'=>'blog','action'=>'delete'));
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'property','controller'=>'blog','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			   <table width="50%">
			   	<tr>
				   <td ><?php echo $frm->getElement("adv_search");?></td>
				   <td ><?php echo $frm->getElement('status_search');?></td>
				   <td><input type="submit" value="search" name="search" label="Search" dojoType="dijit.form.Button" 
													iconClass="dijitIconSearch" />
					</td>
					<td><input type="submit" value="show_all" onClick="resetForm();" label="<?php echo $tr->translate('SHOW_ALL');?>" id="show_all" dojoType="dijit.form.Button" name="show_all" />	</td>
				</tr>
			   </table>
			</form>
		</div>
		<div class="card-box">
		<?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dijit.Dialog");
function  resetForm(){
	var datenow = '<?php echo date("Y-m-d");?>';
	dijit.byId('adv_search').attr('value','');
	dijit.byId('status_search').set('value','-1');
}
var recordid='';
function deleteRecord(url){
	 id = recordid;
	 window.location.href = url+'/id/'+id;
}

function setValue(index){
	var recorddelete = $('input[name=copy]:checked').val();
	dijit.byId('recorddelete').attr('value',recorddelete);
}
function showDeleteForm(id){
	if(id==''){
		alert("No record selected for delete.");
		dijit.byId('deleteForm').hide();
	}else{
		dijit.byId('deleteForm').show();
		recordid = id;
	}
}
function closeForm(){
	dijit.byId('deleteForm').hide();
}
</script>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?'"  id="deleteForm" style="width:350px;" >
		<div style=" text-align: center;">
			<h4>តើអ្នកពិតជាលុបទិន្នន័យនេះមែនទេ?</h4>
			<button onclick="deleteRecord('<?php echo $url_delete;?>')" iconclass="dijitIconDelete" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("DELETE");?></button>
			<button onclick="closeForm();" dojoType="dijit.form.Button" showLabel="true" type="button"><?php echo $tr->translate("CANCEL");?></button>
		</div>
	</div>
</div>