<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD'));
	$frm = $this->frmBudget;

?>	
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add' action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					budgetType = dijit.byId('budgetType').get('value');
					if(budgetType<1){
						alert('<?php echo $tr->translate('SELECT_BUDGET_TYPE');?>');
						dijit.byId('budgetType').focus();
						return false;
					}

					return true;
				}else{
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-bars" aria-hidden="true"></i> <i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD');?></h4>

	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
		    <div class="col-md-12">
	        	<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" >
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="button" dojoType="dijit.form.Button" onclick="getRefreshData();" label="Get Data" iconClass="dijitEditorIcon dijitEditorIconUndo" /> 
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BUDGET_TYPE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('budgetType');?>
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PARENT_BUDGET_ITEM");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('parent_id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BUDGET_TYPE_TITLE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('budgetTitle');?>
	                   </div>
	                </div>
	            </div>
	        </div>
			<div class="clearfix"></div>
			  <div class="card-box">
               	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input type="reset" value="CLEAR" tabindex="2" label="<?php echo $tr->translate('CLEAR');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
						 	iconClass="dijitIconClear" /> 
						<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
							iconClass="dijitEditorIcon dijitEditorIconSave" /> 
					</div>
    			</div>
	    	</div>
		</form>
	</div>
</div>
<script type="text/javascript">
	function addNewBudgetItem(){
		budgetType = dijit.byId('budgetType').get('value');
		if(budgetType==-1){
			window.open('<?php echo $this->url(array('module'=>'budget','controller'=>'type','action'=>'add'))?>');
		}
	}
	function getRefreshData(){
	
	}
	dojo.require("dijit.form.Textarea");
</script>