<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT'));
	$frm = $this->frmBudget;

?>	
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add' action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					budgetType = dijit.byId('budgetType').get('value');
					if(budgetType<1){
						infoMessageAlert('<?php echo $tr->translate('SELECT_BUDGET_TYPE');?>');
						dijit.byId('budgetType').focus();
						return false;
					}

					return true;
				}else{
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-bars" aria-hidden="true"></i> <i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT');?></h4>

	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
		    <div class="col-md-12">
	        	<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-bars" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("BUDGET_ITEM");?></p>
										</div> 
									</div>
									
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BUDGET_TYPE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<div class="col-md-6 col-sm-6 col-xs-12">
												<?php echo $frm->getElement('budgetType');?>
											</div>
											<div class="col-md-6 col-sm-6 col-xs-12">
												<input type="button" class="button-class button-primary"  iconClass="glyphicon glyphicon-refresh" dojoType="dijit.form.Button" onclick="getRefreshData();" label="<?php echo $tr->translate("GET_DATA");?>" /> 
											</div>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PARENT_BUDGET_ITEM");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('budgetItem');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BUDGET_ITEM_TITLE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('budgetTitle');?>
											<?php echo $frm->getElement('id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('status');?>
									   </div>
									</div>
									
									<div class="clearfix"></div>
									<div class="card-box">
										<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
											<input type="reset" class="button-class button-danger" iconClass="glyphicon glyphicon-repeat" value="CLEAR" tabindex="2" label="<?php echo $tr->translate('CLEAR');?>" id="save_close" dojoType="dijit.form.Button" name="save_close" /> 
											<input type="submit"  class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk"  value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new" /> 
										</div>
									</div>
									
								</div>
							</div>
						</div>
					</div>
	            </div>
	        </div>
			
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");

	function getBudgetItem(){
		budgetType = dijit.byId('budgetType').get('value');
		if(budgetType==-1){
			window.open('<?php echo $this->baseUrl();?>/budget/type/add?isAddBudgetType=1');
		}else if(budgetType>0){
			urlGetBudgetItem = '<?php echo $this->url(array('module'=>'budget','controller'=>'item','action'=>'get-allbudgetitem'));?>';
			contentData = {'budgetType':budgetType};
			getAllBudgetItem(urlGetBudgetItem,contentData);
		}
	}
	function getRefreshData(){
		urlGetBudgetType ='<?php echo $this->url(array('module'=>'budget','controller'=>'type','action'=>'getbudgettype'))?>';
		getAllBudgetType(urlGetBudgetType);
	}
	dojo.require("dijit.form.Textarea");
</script>