<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('TERMCONDICTION')); 
?>
<?php  $frm = $this->frm_term;?>
<script>
dojo.require("dijit.form.Textarea");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
					<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('TERMCONDICTION');?></h4>
				</div>
				<div class="col-sm-4 text-right">
				</div>
			</div>
		</div>
		<form action="<?php echo $this->url(array('module'=>'other','controller'=>'term','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-file-text" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("TERMCONDICTION");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-12 col-sm-12 col-xs-12" ><?php echo $tr->translate("CONDICTION_STEP");?>
									   </label>
									   <div class="col-md-12 col-sm-12 col-xs-12">
											<textarea class="fullside"  dojoType="dijit.form.Textarea" class="fullside" style="width:100%;min-height:60px;max-height:300px; "   tabindex="" class="fullside" id="con_step" name="con_step"><?php echo $this->term['con_step'];?></textarea>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-12 col-sm-12 col-xs-12" ><?php echo $tr->translate("CONDICTION_INSTALLMENT");?>
									   </label>
									   <div class="col-md-12 col-sm-12 col-xs-12">
											<textarea dojoType="dijit.form.Textarea" class="fullside" style="width:100%;min-height:60px;max-height:300px; " tabindex="" class="fullside" id="con_khmer" name="con_khmer"><?php echo $this->term['con_khmer'];?></textarea>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-12 col-sm-12 col-xs-12" ><?php echo $tr->translate("CONDICTION_PAYOFF");?>
									   </label>
									   <div class="col-md-12 col-sm-12 col-xs-12">
											<textarea class="fullside"  dojoType="dijit.form.Textarea" class="fullside" style="width:100%;min-height:60px;max-height:300px; "   tabindex="" class="fullside" id="con_payoff" name="con_payoff"><?php echo $this->term['con_payoff'];?></textarea>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="card-box">
					<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
						<input type="reset" class="button-class button-danger" iconClass="glyphicon glyphicon-repeat" value="សំអាត" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" />
						<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_close" name="save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" dojoType="dijit.form.Button"  />
					</div>
				</div>	
			</div>
		</form>
		
	</div>
</div>