<?php	
	$frm = $this->frm;
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();

	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_PAYMENT_COMBINE"));
	$montFomat="d-M-Y";
?>
<style>
.fullside50{ width:48%;}
.agreement{
	border: 1px solid #92b0ea;
    background: #cbdcff;
    font-weight: bold;
    text-align: center;}
.blog-left-content {
    min-height: 250px;
    border: 1px solid #eee;
    margin: 0 !important;
    padding: 10px !important;
    background: #f9f7f7;
}
.hiddenControl{
	  display:none;
  }
  tr.trHeadTile th {
		background: #085d94;
		padding: 5px;
		text-align: center;
		color: #fff;
	}
	tr.regurlar {
		background: #eee;
	}
	td.preFooterTotal {
		background: #085d94;
		color: #fff;
	}
	
	label.price {
		font-size: 14px;
		color: red;
		font-weight: bold;
	}
	tfoot tr td {
		padding: 5px 0;
	}
	
	ul.introduction {
		list-style: none;
		padding-left: 15px;
		font-size: 12px;
		line-height: 18px;
	}
</style>
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
	<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
	<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
		  			
           			branchId = dijit.byId('branchId').get('value');
            		if (branchId=='' || branchId==-1){
						infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH")?>!');
						dijit.byId('branchId').focus();
						return false;
					}
					
					clientId = dijit.byId('clientId').get('value');
            		if (clientId=='' || clientId==-1){
						infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_CLIENT")?>!');
						dijit.byId('clientId').focus();
						return false;
					}
					
					loadingBlock();
					dijit.byId('saveclose').set('disabled',true);	
					dijit.byId('savenew').set('disabled',true);
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_PAYMENT_COMBINE');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	
	       <div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-tasks" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("CUSTOMER_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branchId');?>
											<?php echo $frm->getElement('id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("Customers");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="clientId" />
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('note');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					
				</div>
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-money" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("PAYMENT_INFORMATION");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DATE_PAYMENT");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('datePayment');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PAYMENT_METHOD");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('paymentMethod');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BANK");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('bankId');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NUMBER_CODE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('cheque');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("totalAllPaid");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('totalAllPaid');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
					
				</div>
				
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="form-group" style="background: #d8e0e2;padding: 5px 15px;margin: 0;border: solid 1px #697996;border-radius: 2px;margin-top: 10px;">
										<strong><?php echo $tr->translate("NOTE");?>:</strong>
										<br />
										<ul class="introduction">
											<li>
												1. សម្រាប់ការទូទាត់ប្រាក់ច្រើនការលក់បញ្ចូលគ្នា គឺតម្រូវអោយធ្វើការ <strong>Tick</strong> ទៅលើការលក់ខាងក្រោម ដើម្បីអាចធ្វើការចុះការទូទាត់បាន។
											</li>
											<li>
												2. សម្រាប់ការទូទាត់លើការលក់ដែល <strong>មានតារាងបង់ប្រាក់រួចរាល់</strong> តម្រូវអោយទទួលប្រាក់តាមគោលការណ៍ដែលបានកំណត់ប៉ុណ្ណោះ។
											</li>
											<li>
												3. សម្រាប់ការទូទាត់លើការលក់ដែល <strong>មិនទាន់មានតារាងបង់ប្រាក់ឬគោលការណ៍បង់ប្រាក់</strong> គឺអាចកែប្រែទឹកប្រាក់ត្រូវទទួលបាន។
											</li>
											<li>
												4. គោការណ៍ <strong>ផាកពិន័យ</strong> ឬ  <strong>ទឹកប្រាក់បន្ថែម</strong> មិនត្រូវបានអនុវត្តក្នុង ជម្រើសទទួលប្រាក់នេះឡើយ។
											</li>
										</ul>
									</div>
									
									
									
								</div>
							</div>
						</div>
					</div>
					
				</div>
				
			</div>
			<div class="card-box">
	          		 <div class="col-md-12 col-sm-12 col-xs-12">
	          		 	
		             	<div class="form-group">
		          			<table  class="collape responsiveTable">
								<thead>
									<tr id="head-title" class="head-td" align="right">
										<th scope="col">
										<div class="custom-control custom-checkbox ">
												<input type="checkbox" class="custom-control-input checkbox"  name="checkAll" id="checkAll" value="all" OnChange="CheckAllTotal(0);" >
												<label class="custom-control-label" for="checkAll">
												</label>
											</div>
										</th>
										<th scope="col"><?php echo $tr->translate("NUM");?></th>
										<th scope="col" style=" min-width: 105px;"><?php echo $tr->translate("PROPERTY_CODE");?></th>
										<th scope="col" ><?php echo $tr->translate("DATE_PAYMENT");?></th>
										<th scope="col" ><?php echo $tr->translate("PRICE_SOLD");?></th>
										<th scope="col" ><?php echo $tr->translate("OS_AMOUNT");?></th>
										<th scope="col" ><?php echo $tr->translate("INTEREST");?></th>
										<th scope="col" ><?php echo $tr->translate("TOTAL_AMOUNT");?></th>
										<th scope="col" ><?php echo $tr->translate("BALANCE");?></th>
									</tr>
								</thead>
								<tbody id="tableRecord">
									<?php if(!empty($this->rowDetail)) foreach($this->rowDetail as $key=>$row){
										
										$datePay = new DateTime($row["date_payment"]);
										$datePayment =  $datePay->format($montFomat);
										?>
										<tr>
											<td scope="col"></td>
											<td scope="col"><?php echo ($key+1);?></td>
											<td scope="col"><?php echo $row["landAddress"];?></td>
											<td scope="col"><?php echo $datePayment;?></td>
											<td scope="col" align="center"><label class="price">$ <?php echo number_format($row["priceSold"],2);?></label></td>
											<td scope="col" align="center"><?php echo number_format($row["total_principal_permonthpaid"],2);?></td>
											<td scope="col" align="center"><?php echo number_format($row["total_interest_permonthpaid"],2);?></td>
											<td scope="col" align="center"><?php echo number_format($row["recieve_amount"],2);?></td>
											<td scope="col" align="center"><?php echo number_format($row["priceSold"]-$row["allpaid_before"],2);?></td>
										</tr>
									<?php }?>
								<tbody>
								<tfoot>
									<tr>
										<td colspan="5"></td>
										<td >
											<?php echo $frm->getElement('totalPrinciple');?>
										</td>
										<td >
											<?php echo $frm->getElement('totalInterest');?>
										</td>
										<td >
											<?php echo $frm->getElement('totalPayment');?>
										</td>
										<td >
											<?php echo $frm->getElement('totalBalance');?>
										</td>
									</tr>
								<tfoot>
							</table>
							<input type="hidden" id="identity" name="identity" />
							<input type="hidden" name="old_identity" id="old_identity"  value="" >
						 </div>
	          		</div>
	          </div>
	         <div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" label="<?php echo $tr->translate("SAVE");?>" id='saveclose' name='saveclose' value='saveclose' dojoType="dijit.form.Button" />
				</div>
    		</div>
		</form>
	</div>
</div>
<script type="text/javascript">	
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var contractNameStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
require(["dojo/ready"], function(ready){
	 ready(function(){
		 dijit.byId("branchId").set("readOnly",true);
		 <?php if(!empty($this->row["paymentMethod"])){?>
			dijit.byId('paymentMethod').set('value', "<?php echo $this->row["paymentMethod"]; ?>");
		<?php }?>
		 enablePayment();
		 filterClient();
	  });
	new dijit.form.FilteringSelect({
	store: client_store,//dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: false,
	queryExpr: "*${0}*",	           
	name: "clientId",
	id: "clientId",
	searchAttr: "name",
	required:true,
	readOnly:true,
	class: 'fullside',
	onChange: function() {
		
		
		}
	}, "clientId");

});					           

function enablePayment(){
	paymentMethod = dijit.byId('paymentMethod').get('value');
	dijit.byId("cheque").set("readOnly",false);
	dijit.byId("cheque").attr("value",'');
	if(paymentMethod==1){
		dijit.byId("cheque").attr("value",'N/A');
		dijit.byId("cheque").set("readOnly",true);
	}
	<?php if(!empty($this->row["cheque"])){?>
		dijit.byId('cheque').set('value', "<?php echo $this->row["cheque"]; ?>");
	<?php }?>
	<?php if(!empty($this->row["bankId"])){?>
		dijit.byId('bankId').set('value', "<?php echo $this->row["bankId"]; ?>");
	<?php }?>
	
}


function filterClient(){
	branchId = dijit.byId('branchId').get('value');	
	
	getAllClientByBranch(branchId);
}

var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branchId){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branchId
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('clientId').set('store', client_store);
			<?php if(!empty($this->row["clientId"])){?>
			dijit.byId('clientId').set('value', "<?php echo $this->row["clientId"]; ?>");
			<?php }?>
		},
		error: function(err) {
		}
	});
}

function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = dijit.byId('branchId').get('value');
	if(branch_id==""){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img class="view" style="height:80px; max-width: 100%;" src="<?php echo $this->baseUrl()."/images/projects/"?>'+arr.logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;

			document.getElementById('ft_branch_title_lb').innerHTML = arr.footer_title;
			document.getElementById('ft_website_lb').innerHTML = arr.office_website;
			document.getElementById('ft_email_client_lb').innerHTML = arr.office_email;
			document.getElementById('ft_address_lb').innerHTML = arr.office_address;
			document.getElementById('ft_phone_lb').innerHTML = arr.office_tel;
		},
		error: function(e) {
		}
	});
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}

function returnMOnth(monthnum){
	var month = new Array();
	month[1] = "Jan";
	month[2] = "Feb";
	month[3] = "Mar";
	month[4] = "Apr";
	month[5] = "May";
	month[6] = "Jun";
	month[7] = "Jul";
	month[8] = "Aug";
	month[9] = "Sep";
	month[10] = "Oct";
	month[11] = "Nov";
	month[12] = "Dec";
	return month[monthnum];
}

	
</script>