<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$dbGB = new Application_Model_DbTable_DbGlobal();

	$montFomat=DATE_FORMAT_FOR_PHP;

	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
	
	$branch_title = $tr->translate("BRAND_TITLE");
	
	$dbGBstock = new Application_Model_DbTable_DbGlobalStock();
	$arrStep = array(
			'keyIndex'=>1,//Purchase By Request
			'typeKeyIndex'=>1,
		);
	$purchaseType = $dbGBstock->purchasingTypeKey($arrStep);
	
	$titleReport = $tr->translate("RPT_UNCLOSING_PAYMENT");
?>
<title><?php echo $titleReport;?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div class="reportblog">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i> <?php echo $tr->translate('RPT_UNCLOSING_PAYMENT');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<form method="post">
			<div class="card-box">
		    	<div class="form-group">
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("adv_search");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("branch_id");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("start_date");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("end_date");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("statusAcc");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("closingStatus");?>
					</label>
					
					
				</div>
				<div class="form-group">
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("supplierId");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("paymentMethod");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("bankId");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12" >
						<?php echo $frm->getElement("btn_search");?>
					</label>
					
				</div>
				
			</div>
		</form>
		<div style="width:100%; margin:0 auto;">
		<div style="min-height:22cm; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
			</style>
	<form id="list" name="list" action="<?php echo $this->url(array('module'=>'report','controller'=>'stockmg','action'=>'unclosingpayment')); ?>" dojoType="dijit.form.Form" method="post">
		<script type="dojo/method" event="onSubmit" >			
					id_selected = dijit.byId('id_selected').get('value');
					if(id_selected==''){
						alert('No record to close !!! ');
						return false;
					}
					return true;
			</script>
			<div id="divPrint">
				<style type="text/css">
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table { page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					td.rightText{
						text-align: right;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					tr.style.void td {
						background: #fff6f6;
					}
					
					table.totalBottom{
						line-height: 25px; 
						font-size:11px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.totalBottom tr td{
						padding:2px;
						line-height: 14px;
					}
					table.totalBottom tr.rowHead td {
						padding: 4px 0;
						font-weight: 600;
					}
					tr.rowHead td.mainCol {
						width: 15%;
						border-bottom: solid 2px #000;
						border-top: solid 2px #000;
						padding: 2px 0;
					}
					td.blankCol {
						width: 2%;
					}
					td.sideCol {
						width: 10%;
					}
					td.valueData {
					}
					td.valueData.totalVal {
						font-weight: 600;
					}
				</style>
				<table width="100%">
					<tr>
				    	<td align="center" valign="top">
				        	<div class="divFooter">
					        	<?php echo $this->headerReport;?>
				            </div>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				            <table class="content-data" width="100%" border="1"  cellspacing="0" cellpadding="0">
					                <thead>
					                <tr class="hide" style="border:1px solid #000;">
					                	<td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
					                </tr>
					                <tr  class="style" align="center" >
					                    <td scope="col" rowspan="2" class="center">
											<input type="checkBox" onclick="checkAll('<?php echo count($this->row);?>');" name="checkall" id="checkall" />
											<input type="hidden" name="id_selected" id="id_selected" dojoType="dijit.form.TextBox" />
										</td>
					                    <td scope="col" rowspan="2" class="center"><?php echo $tr->translate("NUM");?></td>
										<td scope="col" colspan="4" class="center"><?php echo $tr->translate("PAYMENT_INFO");?></td>    
					                    <td scope="col" colspan="4" class="center"><?php echo $tr->translate("AMOUNT_INFO");?></td>    
					                   
									    <td scope="col" colspan="2" class="center"><?php echo $tr->translate("INVOICE_INFO");?></td>
					                    <td scope="col" colspan="4" class="center"><?php echo $tr->translate("OTHER");?></td>    
					                 
					                </tr>
					                <tr class="style" align="center">
					                	<td scope="col" style="padding:1px;"><?php echo $tr->translate("BRANCH_NAME");?></td>                   
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("PO_NO");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("DATE");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("SUPPLIER");?></td>
										
										<td scope="col" style="padding:1px;"><?php echo $tr->translate("PAYMENT_METHOD");?></td>
										<td scope="col" style="padding:1px;"><?php echo $tr->translate("BANK");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("ACCOUNT_AND_CHEQUE_NO");?></td>	                    
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("PAID")." ".$tr->translate("CURRENCY_SIGN");?></td>
										
										<td scope="col" style="padding:1px;"><?php echo $tr->translate("INVOICE_NO");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("SUPPLIER_INVOICE");?></td>
										
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("NOTE");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("STATUS");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("BY");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("CLOSING");?></td>
					                </tr>
					            </thead>
				                <?php 
				                	$totalCash = 0;
									$totalCheque = 0;
									$totalBank = 0;
									
									$voidCash = 0;
									$voidCheque = 0;
									$voidBank = 0;
									
									$noCash = 0;
									$noCheque = 0;
									$noBank = 0;
									
				                	$gTotal=0;
				                	$totalVoid=0;
				                	$i=1;
				                ?>
				                <?php 
				                if(!empty($this->row)) foreach ($this->row as $index => $rs){
									$class="";
									if($rs["status"]==0){
										$class="void";
										$totalVoid =$totalVoid+1;
										if($rs["paymentMethod"]==1){
											$voidCash =$voidCash+1;
										}elseif($rs["paymentMethod"]==2){
											$voidBank =$voidBank+1;
										}elseif($rs["paymentMethod"]==3){
											$voidCheque =$voidCheque+1;
										}
									}else{
										if($rs["paymentMethod"]==1){
											$totalCash =$totalCash+$rs["totalAmount"];
											$noCash =$noCash+1;
										}elseif($rs["paymentMethod"]==2){
											$totalBank =$totalBank+$rs["totalAmount"];
											$noBank =$noBank+1;
										}elseif($rs["paymentMethod"]==3){
											$totalCheque =$totalCheque+$rs["totalAmount"];
											$noCheque =$noCheque+1;
										}
										$gTotal =$gTotal+$rs["totalAmount"];
									}
								?>
				                <tr class=" style <?php echo $class;?>" style="font-family: 'Khmer OS Content'; white-space:nowrap; ">
				               		<td style="text-align: center;">
										<input style="height: 15px;margin-top: 5px;" type="checkBox" onClick="checked_id(<?php echo $index+1;?>)" name="check_box<?php echo $index+1;?>" id="check_box<?php echo $index+1;?>" />
							            <input type="hidden" id="id_<?php echo $index+1;?>" name="id_<?php echo $index+1;?>" value="<?php echo $rs['id'];?>" dojoType="dijit.form.TextBox" />
									</td>
				               		<td data-label="<?php echo $tr->translate("NUM");?>" style="text-align: center;"><?php echo $i++; ?></td>
				               		<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"><?php echo $rs["branch_name"];?></td>
				               		<td data-label="<?php echo $tr->translate("PO_NO");?>" class="centerText redBold"><?php echo $rs["paymentNo"];?></td>      
									<td data-label="<?php echo $tr->translate("DATE");?>" class="centerText"><?php echo date($montFomat,strtotime($rs["paymentDate"]));?></td>
									<td data-label="<?php echo $tr->translate("SUPPLIER");?>"><?php echo $rs["supplierName"];?></td>
									
									
									<td data-label="<?php echo $tr->translate("PAYMENT_METHOD");?>"><?php echo $rs["paymentMethodTitle"];?></td>
									<td data-label="<?php echo $tr->translate("BANK");?>"><?php echo $rs["bankName"];?></td>
									<td data-label="<?php echo $tr->translate("ACCOUNT_AND_CHEQUE_NO");?>"><?php echo $rs["accNameAndChequeNo"];?></td>
									<td data-label="<?php echo $tr->translate("PAID");?>" class="rightText"><?php echo number_format($rs["totalAmount"],2);?></td>
									
									<td data-label="<?php echo $tr->translate("INVOICE_NO");?>"><span style="max-width: 160px;min-width: 100px;display: block;white-space: pre-line;line-height: 14px;overflow-wrap: break-word;padding: 1px;font-size: 9px;" ><?php echo $rs["invoiceNoList"];?></span></td>
									<td data-label="<?php echo $tr->translate("SUPPLIER_INVOICE");?>"><span style="max-width: 160px;min-width: 100px;display: block;white-space: pre-line;line-height: 14px;overflow-wrap: break-word;padding: 1px;font-size: 9px;" ><?php echo $rs["supplierInvoiceNoList"];?></span></td>
									
									<td data-label="<?php echo $tr->translate("NOTE");?>"><span style="max-width: 160px;min-width: 100px;display: block;white-space: pre-line;line-height: 14px;overflow-wrap: break-word;padding: 1px;font-size: 9px;" ><?php echo $rs["note"];?></span></td>
									<td data-label="<?php echo $tr->translate("STATUS");?>" class="centerText"><?php echo empty($rs["statusTitle"])?"-":$rs["statusTitle"];?></td>
									<td data-label="<?php echo $tr->translate("BY");?>" class="centerText"><?php echo $rs["byUser"];?></td>
									<td data-label="<?php echo $tr->translate("CLOSING");?>" class="centerText"><?php echo $rs["isClosedTitle"];?></td>
								</tr>
				                <?php }?>
				               
				            </table>
							<br />
				            <table class="totalBottom" style="width:100%;">
								
								<tr class="rowHead">
									<td class="sideCol"></td>
									<td class="mainCol centerText"><?php echo $tr->translate("CASH");?></td>
									<td class="blankCol">&nbsp;</td>
									<td class="mainCol centerText"><?php echo $tr->translate("PAYWITH_BANK");?></td>
									<td class="blankCol">&nbsp;</td>
									<td class="mainCol centerText"><?php echo $tr->translate("CHEQUE");?></td>
									<td class="blankCol">&nbsp;</td>
									<td class="mainCol centerText"><?php echo $tr->translate("TOTAL");?></td>
									<td class="sideCol"></td>
								</tr>
								<tr>
									<td class="rightText"><?php echo $tr->translate("CURRENCY_SIGN");?></td>
									<td class="valueData centerText"><?php echo number_format($totalCash,2);?></td>
									<td></td>
									<td class="valueData centerText"><?php echo number_format($totalBank,2);?></td>
									<td></td>
									<td class="valueData centerText"><?php echo number_format($totalCheque,2);?></td>
									<td></td>
									<td class="valueData totalVal centerText"><?php echo number_format($gTotal,2);?></td>
								</tr>
								<tr>
									<td class="rightText"><?php echo $tr->translate("AMT_RECORD");?></td>
									<td class="valueData centerText"><?php echo sprintf('%02d',$noCash);?></td>
									<td></td>
									<td class="valueData centerText"><?php echo sprintf('%02d',$noBank);?></td>
									<td></td>
									<td class="valueData centerText"><?php echo sprintf('%02d',$noCheque);?></td>
									<td></td>
									<td class="valueData totalVal centerText"><?php echo sprintf('%02d',count($this->row));?></td>
								</tr>
								<tr>
									<td class="rightText"><?php echo $tr->translate("AMT_VOID_RECORD");?></td>
									<td class="valueData centerText"><?php echo sprintf('%02d',$voidCash);?></td>
									<td></td>
									<td class="valueData centerText"><?php echo sprintf('%02d',$voidBank);?></td>
									<td></td>
									<td class="valueData centerText"><?php echo sprintf('%02d',$voidCheque);?></td>
									<td></td>
									<td class="valueData totalVal centerText"><?php echo sprintf('%02d',$totalVoid);?></td>
								</tr>
				            </table>
							<br />
						    <?php echo $this->footerReport;?>
				    	</td>
				    </tr>
				</table>
				<table width="100%">
					<tr>
						<td align="center">
							<br><button class="button-class button-primary" iconclass="glyphicon glyphicon-remove-circle" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("UNCLOSING");?></button>
						</td>
					</tr>	
				</table>
			</div>
	</form>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	require(["dojo/ready"], function(ready){
		ready(function(){
			 
			 getBranchInfo();
			 
			 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			 document.getElementById('reportTitle').innerHTML = '<?php echo $titleReport;?>';
			 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date(DATE_FORMAT_FOR_PHP); }else{ echo date(DATE_FORMAT_FOR_PHP,strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date(DATE_FORMAT_FOR_PHP,strtotime($this->search['end_date'])); }?>';
		
			<?php if( $this->search['closingStatus']>-1 ){?>
				dijit.byId('closingStatus').set('value','<?php echo $this->search['closingStatus']; ?>');
			<?php  } ?>
		});
		
	});

function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}


function checkAll(array_length){
		dijit.byId('id_selected').attr('value','');
		if(dojo.byId('checkall').checked){
			for(var j=1;j<=array_length;j++){
				$('#check_box'+j).each(function() { 
					this.checked = true;  
				});
				checked_id(j);
			}
		}else{
			for(var j=1;j<=array_length;j++){
				$("#check_box"+j).removeAttr("checked");
				checked_id(j);
			}
		}
	}

	function checked_id(index){
		row_id = index;//dijit.byId('id_'+index).get('value');
		if(dojo.byId('check_box'+index).checked){
			if($("#id_selected").val()!="") {
				var identity = $("#id_selected").val();
				$("#id_selected").val(identity+','+row_id);
			}else{
				$("#id_selected").val(row_id);
			}
		}else{
			var identity = $('#id_selected').val();
			var arrays = identity.split(',');
			for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == row_id) arrays.splice(i,1);
			}
			var strings = arrays.join(',');
			$('#id_selected').val(strings);
		}
	}
</script>