<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$dbGB = new Application_Model_DbTable_DbGlobal();

	$montFomat=DATE_FORMAT_FOR_PHP;
	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
	
	$branch_title = $tr->translate("BRAND_TITLE");
	$titleReport = $tr->translate('RPT_REQUEST_PRODUCT_SUMMARY');
	
	$requestLetter = $this->baseUrl()."/report/stockmg/request-letter/id/";
	$requestInfor = $this->baseUrl()."/report/stockmg/request-info/id/";
	$purchaseLetter = $this->baseUrl()."/report/stockmg/purchase-letter/id/";
	$urlDnLetter = $this->baseUrl()."/report/stockreport/rpt-receivestockdetail/id/";
	
?>
<title><?php echo $titleReport;?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div class="reportblog">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $titleReport;?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<form method="post">
			<div class="card-box">
		    	<div class="form-group"> 
					<label class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</label>

				</div>
				<div class="form-group">
					<label class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("requestStatusCheck");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary" iconClass="glyphicon glyphicon-search"dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</label>
					
				</div>
				
			</div>
		</form>
		<div style="width:100%; margin:0 auto;">
		<div style="min-height:22cm; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
			</style>
			<div id="divPrint">
				<style type="text/css">
					table,
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					
					table.content-data { page-break-inside:auto }
					table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:8px;
					}
					table.content-data thead tr.style,
					table.content-data  tr td.styleTitle {
					   line-height: 25px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:11px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
					table.content-data  tr td.styleTitle,
					table tr td{
						padding:0 5px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					td.centerRight{
						text-align: right;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					.boldText {
						font-weight: 600;
					}
					.greenClass {
						color: #017236;
					}
					tr.style.rejected {
						background: #ffe5e5;
					}
					a.colorInherit {
						color: inherit;
						text-decoration:none;
					}
				</style>
				<table width="100%">
					<tr>
				    	<td align="center" valign="top">
				        	<div class="divFooter">
					        	<?php echo $this->headerReport;?>
				            </div>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				            <table class="content-data" width="100%" border="1"  cellspacing="0" cellpadding="0">
					                <thead>
					                <tr class="hide" style="border:1px solid #000;">
					                	<td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
					                </tr>
					                <tr class="style" align="center" >
					                    <td scope="col"  rowspan="2" class="center"><?php echo $tr->translate("NUM");?></td>
										<td scope="col"  colspan="3" class="center"><?php echo $tr->translate("REQUEST_INFO");?></td>
					                    <td scope="col"  colspan="8" class="center"><?php echo $tr->translate("PRODUCT_INFO");?></td>    
					                       
					                    <td scope="col"  colspan="2" class="center"><?php echo $tr->translate("PURCHASING_AND_DN_INFO");?></td>    
					                   
								   </tr>
					                <tr class="style" align="center">
					                   
										<td scope="col"  style="padding:1px;"><?php echo $tr->translate("BRANCH_NAME");?></td>
										<td scope="col"  style="padding:1px;"><?php echo $tr->translate("REQUEST_NO");?></td>
					                    <td scope="col"  style="padding:1px;"><?php echo $tr->translate("DATE");?></td>
										
										<td scope="col"  style="padding:1px;"><?php echo $tr->translate("QTY_REQUEST");?></td>
					                    <td scope="col"  style="padding:1px;"><?php echo $tr->translate("QTY_APPROVED");?></td>
					                    <td scope="col"  style="padding:1px;"><?php echo $tr->translate("QTY_PO");?></td>
					                    <td scope="col"  style="padding:1px;"><?php echo $tr->translate("QTY_RECEIVE");?></td>
					                    <td scope="col"  style="padding:1px;"><?php echo $tr->translate("QTY_REMAIN");?></td>
										<td scope="col"  style="padding:1px;"><?php echo $tr->translate("UNIT_PRICE");?></td>
										<td scope="col"  style="padding:1px;"><?php echo $tr->translate("TOTAL")." ".$tr->translate("CURRENCY_SIGN");?></td>
										<td scope="col"  style="padding:1px;"><?php echo $tr->translate("IN_STOCK");?></td>
										
										
					                   
					                   
										
					                    <td scope="col"  style="padding:1px;"><?php echo $tr->translate("PO_NO");?></td>
										 <td scope="col"  style="padding:1px;"><?php echo $tr->translate("DN_NO");?></td>
					                 
					                   
					                </tr>
					            </thead>
				                
				                <?php 
								$projectId="";
								
								$i=1;
								$productId="";
								$productNo=0;
								
								$itemsTotalRequest=0;
								$itemsTotalApproved=0;
								$itemsTotalPrice=0;
								$itemsTotalQtyPO=0;
								$itemsTotalQtyRececive=0;
								$itemsTotalQtRemain=0;
								
								$rowRequestId=0;
								
								
								$GTotalRequest=0;
								$GTotalApproved=0;
								$GTotalPrice=0;
								$GTotalQtyPO=0;
								$GTotalQtyRececive=0;
								$GTotalQtyRemain=0;
				                if(!empty($this->row)) foreach ($this->row as $index => $rs){
									
								?>
								<?php if($productId!=$rs["proId"]){ $productNo++;?>
								
									<?php if($index>0){?>
										<tr class="style " style="white-space:nowrap; ">
											<td colspan="4"></td>
											<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalRequest,2);?></td>
											<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalApproved,2);?></td>
											<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalQtyPO,2);?></td>
											<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalQtyRececive,2);?></td>
											<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalQtRemain,2);?></td>
											<td class="styleTitle centerRight boldText" colspan="2"><?php echo number_format($itemsTotalPrice,2);?></td>
										</tr>
									<?php 
										$$itemsTotalRequest =0; 
										$itemsTotalApproved =0; 
										$itemsTotalPrice =0; 
										$itemsTotalQtyPO=0;
										$itemsTotalQtyRececive=0;
										$itemsTotalQtRemain=0;
									}?>
									
									  <tr class="style " style="white-space:nowrap; ">
										<td colspan="15" class="styleTitle">
											<strong><?php echo $productNo.".) ".$rs["proCode"]." - ".$rs["proName"];?></strong>
										</td>
									  </tr>
								<?php }?>
								
								<?php 
									$rowTotalPrice = $rs["qtyReceive"]*$rs["unitPrice"];
									$itemsTotalPrice = $itemsTotalPrice+$rowTotalPrice;
									
									
									
									
									$itemsTotalQtyPO = $itemsTotalQtyPO+$rs["qtyPO"];
									$itemsTotalQtyRececive = $itemsTotalQtyRececive+$rs["qtyReceive"];
									
									$qtyRemain = $rs["qtyApproved"]-$rs["qtyReceive"];
									if($rs["qtyPO"]>0){
										$qtyRemain = $rs["qtyPO"]-$rs["qtyReceive"];
									}
									
									$qtyRemainForCal = $qtyRemain;
									$completed="";
									if( ($rs["isCompletedReceive"]>0) OR ($qtyRemain==0) ){
										$completed = "greenClass";
										$qtyRemain="បានទទួលគ្រប់";
										$qtyRemainForCal=0;
									}
									
									
									
									$classRow="";
									
									$qtyRequest = $rs["qtyRequest"];
									$qtyRequestForCal = $qtyRequest;
									
									$qtyApproved=$rs["qtyAdjust"];
									$qtyApprovedForCal=$qtyApproved;
									
									$qtyPO=$rs["qtyPO"];
									$qtyReceive=$rs["qtyReceive"];
									$unitPrice=$rs["unitPrice"];
									$rowTotalPrice = number_format($rowTotalPrice,2);
									
									if($rs["checkingStatus"]==2){
										$classRow="rejected";
										$qtyApproved="SD: Recjected (Full)";
										$qtyPO="-";
										$qtyReceive="-";
										$unitPrice="-";
										$rowTotalPrice="-";
										$qtyRemain="-";
									}else if($rs["pCheckingStatus"]==2){
										$classRow="rejected";
										$qtyApproved="PO: Recjected (Full)";
										$qtyPO="-";
										$qtyReceive="-";
										$unitPrice="-";
										$rowTotalPrice="-";
										$qtyRemain="-";
									}else if($rs["approveStatus"]==2){
										$classRow="rejected";
										$qtyApproved="Boss: Recjected (Full)";
										$qtyPO="-";
										$qtyReceive="-";
										$unitPrice="-";
										$rowTotalPrice="-";
										$qtyRemain="-";
									}else if($rs["adjustStatus"]==2){
										$classRow="rejected";
										$qtyApproved="SD: Recjected";
										$qtyPO="-";
										$qtyReceive="-";
										$unitPrice="-";
										$rowTotalPrice="-";
										$qtyRemain="-";
									}else if($rs["verifyStatus"]==2){
										$classRow="rejected";
										$qtyApproved="PO: Recjected";
										$qtyPO="-";
										$qtyReceive="-";
										$unitPrice="-";
										$rowTotalPrice="-";
										$qtyRemain="-";
									}else if($rs["approvedStatus"]==2){
										$classRow="rejected";
										$qtyApproved="Boss: Recjected";
										$qtyPO="-";
										$qtyReceive="-";
										$unitPrice="-";
										$rowTotalPrice="-";
										$qtyRemain="-";
									}else if($rs["approvedStatus"]==1){
										$qtyApproved=$rs["qtyApproved"];
										$qtyApprovedForCal=$rs["qtyApproved"];
									}
									
									if( ($productId == $rs["proId"]) AND ($rowRequestId == $rs["requestId"]) ){
										$qtyApproved="-";
										$qtyRequest="-";
										
										$qtyApprovedForCal=0;
										$qtyRequestForCal=0;
									}
									$currentQty = $rs["currentQty"];
									
									$itemsTotalRequest = $itemsTotalRequest+$qtyRequestForCal;
									$itemsTotalApproved = $itemsTotalApproved+$qtyApprovedForCal;
									$itemsTotalQtRemain = $itemsTotalQtRemain+$qtyRemainForCal;
									
									$GTotalRequest = $GTotalRequest+$qtyRequestForCal;
									$GTotalApproved = $GTotalApproved+$qtyApprovedForCal;
									$GTotalPrice = $GTotalPrice+$rowTotalPrice;
									$GTotalQtyPO = $GTotalQtyPO+$rs["qtyPO"];
									$GTotalQtyRececive = $GTotalQtyRececive+$rs["qtyReceive"];
									$GTotalQtyRemain = $GTotalQtyRemain+$qtyRemainForCal;
									
									$rowRequestId =$rs["requestId"];
									$productId=$rs["proId"];
									
									
								?>
				                <tr oncontextmenu="setrowdata(<?php echo $rs['requestId'];?>);return false;" class="context-menu-one style <?php echo $classRow;?> " style="white-space:nowrap; ">
				               		<td data-label="<?php echo $tr->translate("NUM");?>"  style="text-align: center;"><?php echo $i++; ?></td>
				               		
									<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"><?php echo $rs["branch_name"];?></td>
									<td data-label="<?php echo $tr->translate("REQUEST_NO");?>"  class="redBold"><a class="colorInherit" title="<?php echo $tr->translate("REQUEST_INFO")." - ".$rs["requestNo"];?>" target="_blank" href="<?php echo $requestInfor."".$rs['requestId']; ?>"><?php echo $rs["requestNo"];?></a></td>                 		
				               		<td data-label="<?php echo $tr->translate("DATE");?>" ><?php echo date($montFomat,strtotime($rs["requestDate"]));?></td>
				               	
								
									<td data-label="<?php echo $tr->translate("QTY_REQUEST");?>"  class="centerText"><?php echo $qtyRequest;?></td>
									<td data-label="<?php echo $tr->translate("QTY_APPROVED");?>"  class="centerText boldText"><?php echo $qtyApproved;?></td>
									<td data-label="<?php echo $tr->translate("QTY_PO");?>"  class="centerText boldText"><?php echo $qtyPO;?></td>
									<td data-label="<?php echo $tr->translate("QTY_RECEIVE");?>"  class="centerText boldText"><?php echo $qtyReceive;?></td>
									<td data-label="<?php echo $tr->translate("QTY_REMAIN");?>"  class="centerText boldText <?php echo $completed; ?>"><?php echo $qtyRemain;?></td>
									<td data-label="<?php echo $tr->translate("UNIT_PRICE");?>"  class="centerText"><?php echo $unitPrice;?></td>
									<td data-label="<?php echo $tr->translate("TOTAL")." ".$tr->translate("CURRENCY_SIGN");?>"  class="centerText"><?php echo $rowTotalPrice;?></td>
									<td data-label="<?php echo $tr->translate("IN_STOCK");?>"  class="centerText boldText greenClass"><?php echo $currentQty;?></td>
									
				               	
									
									
									<td data-label="<?php echo $tr->translate("PO_NO");?>"  class="centerText"><a class="colorInherit" title="<?php echo $tr->translate("PURCHASE_LETTER")." - ".$rs["purchaseNo"];?>" target="_blank" href="<?php echo $purchaseLetter.$rs['poId']; ?>"><?php echo $rs["purchaseNo"];?></a></td>
									
									<td data-label="<?php echo $tr->translate("DN_NO");?>"  class="centerText"><?php echo $rs["dnNumber"];?></td>
									
								</tr>
								
				                <?php }?>
				               <tr class="style " style="white-space:nowrap; ">
									<td colspan="4" style="border-bottom: none;border-left: solid 1px #fff;" ></td>
									<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalRequest,2);?></td>
									<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalApproved,2);?></td>
									<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalQtyPO,2);?></td>
									<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalQtyRececive,2);?></td>
									<td class="styleTitle centerRight boldText"><?php echo number_format($itemsTotalQtRemain,2);?></td>
									<td class="styleTitle centerRight boldText" colspan="2"><?php echo number_format($itemsTotalPrice,2);?></td>
									<td colspan="3" style="border-bottom: none;border-right: solid 1px #fff;" ></td>
								</tr>
								<tr class="style " style="white-space:nowrap; ">
									<td colspan="4" style=" border-top: none; border-bottom: none;border-left: solid 1px #fff;"></td>
									<td class="styleTitle centerRight boldText"><?php echo $tr->translate("QTY_TOTAL_REQUEST");?></td>
									<td class="styleTitle centerRight boldText"><?php echo $tr->translate("QTY_TOTAL_APPROVED");?></td>
									<td class="styleTitle centerRight boldText"><?php echo $tr->translate("QTY_TOTAL_PO");?></td>
									<td class="styleTitle centerRight boldText"><?php echo $tr->translate("QTY_TOTAL_RECEIVED");?></td>
									<td class="styleTitle centerRight boldText"><?php echo $tr->translate("QTY_TOTAL_REMAIN");?></td>
									<td colspan="2" class="styleTitle centerRight boldText"><?php echo $tr->translate("TOTAL")." ".$tr->translate("CURRENCY_SIGN");?></td>
									<td colspan="3" style=" border-top: none; border-bottom: none;border-right: solid 1px #fff;"></td>
								</tr>
								<tr class="style " style="white-space:nowrap; ">
									<td colspan="4" style="border-top: none; border-bottom: solid 1px #fff; border-left: solid 1px #fff;" ></td>
									<td class="centerRight boldText"><?php echo $GTotalRequest;?></td>
									<td class="centerRight boldText"><?php echo $GTotalApproved;?></td>
									<td class="centerRight boldText"><?php echo $GTotalQtyPO;?></td>
									<td class="centerRight boldText"><?php echo $GTotalQtyRececive;?></td>
									<td class="centerRight boldText"><?php echo $GTotalQtyRemain;?></td>
									<td colspan="2" class="centerRight boldText"><?php echo number_format($GTotalPrice,2);?></td>
									<td colspan="3" style="border-top: none; border-bottom: solid 1px #fff; border-right: solid 1px #fff;"></td>
								</tr>
				            </table>
							<br />
				              <?php echo $this->footerReport;?>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	require(["dojo/ready"], function(ready){
		ready(function(){
			 
			 getBranchInfo();
			 
			 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			 document.getElementById('reportTitle').innerHTML = '<?php echo $titleReport;?>';
			 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date(DATE_FORMAT_FOR_PHP); }else{ echo date(DATE_FORMAT_FOR_PHP,strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date(DATE_FORMAT_FOR_PHP,strtotime($this->search['end_date'])); }?>';
		});
		
	});

function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}



var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="requestLetter"){
				url='<?php echo $requestLetter;?>';
			}else if(key=="requestInfor"){
				url='<?php echo $requestInfor;?>';
			}
			gotoAction();
		},
		items: {
			"requestLetter": {name: "<?php echo $tr->translate("REQUEST_LETTER");?>", icon: "fa-file-text", accesskey: "c"},
			"requestInfor": {name: "<?php echo $tr->translate("REQUEST_INFO_DETAIL");?>", icon: "fa-file-text"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>