<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;

	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
	$dbs  = new Report_Model_DbTable_DbStockReports();
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_BUGET_PLAN");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_BUGET_PLAN');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<form name="frm_rptstaff" action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("adv_search");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('branch_id');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<select class="fullside" id="monthlytype" name="monthlytype" dojoType="dijit.form.FilteringSelect">
					<option value="1" <?php if ($this->search['monthlytype']==1){ echo 'selected=selected';}?>><?php  echo $tr->translate("MONTH");?></option>
					<option value="2" <?php if ($this->search['monthlytype']==2){ echo 'selected=selected';}?>><?php  echo $tr->translate("YEAR");?></option>
				</select>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('start_date');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('end_date');?>
        	</div>
        	
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        </div>        
	 </form> 
	<div style="min-height:22cm; margin:0 auto;">
	   	<div id="divPrint">
	    	 	<style>
					.style{
						line-height: 20px;font-size: 14px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
						}
						th{padding: 2px;}
						.hide{visibility: hidden;}
							@media print {
							  div.divFooter {
							    position: fixed;
							    top: 0;
							  	width: 100%;
							  	height: 100px;
							  	bottom:0px;
								margin:0;
							 }
						.hide{visibility: visible; height: 110px;}
					}
					td.verites-col {
					    text-align: center;
					    white-space: nowrap;
					    g-origin: 50% 50%;
					    -webkit-transform: rotate(270deg);
					    -moz-transform: rotate(270deg);
					    -ms-transform: rotate(270deg);
					    -o-transform: rotate(270deg);
					    transform: rotate(270deg);
					}
					tr.hover td.verites-col span.verites,
					td.verites-col span.verites {
					    margin: 0 -100%;
					    display: inline-block;
					}
					tr.hover td.verites-col span.verites:before,
					td.verites-col span.verites:before {
					    content: '';
					    width: 0;
					    padding-top: 110%;
					    display: inline-block;
					    vertical-align: middle;
					}
					.bgRow{background:#fafafa;}
					.fontWeight{font-weight: bold;}
					.blogSummary{
						background:#0199ca;font-size: 14px;
						color:#ebfaff;font-weight: bolder;
						padding:5px;text-align: center;
						margin-top:5px;
						box-shadow:rgb(5 110 145) 1.95px 1.95px 2.6px;
						font-family:'khmer os battambang';
						float: right;
						margin-left:5px;
				
					}
					#exportExcel{
						font-family:'khmer os battambang';
					}
					@page{
						size: landscape;
						margin-left:0.2cm;
						margin-right:0.2cm;
					}
					</style>
				<div class="divFooter">
		        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;">
		            	<tr>
			                <td width="30%"><img src="<?php echo $logo;?>" style="height:85px; max-width: 100%;"></td>
			                <td width="40%" valign="top">
			                	<h2 style="white-space:nowrap;font-weight:normal; text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $branch_title;?></h2>
			               		<h2 style="font-weight:normal; text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_BUGET_PLAN");?></h2>
			                	<h2 style="font-weight:normal; text-align:center; font-size:13px; font-family:'Times New Roman','Khmer OS Muol Light';">
			                	<?php if ($this->search['monthlytype']==1){?>
			                		<?php if(!empty($this->search['start_date'])){ echo date("M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("M-Y",strtotime($this->search['end_date']));}?>
			                	<?php }else{?>
			                		<?php if(!empty($this->search['start_date'])){ echo date("Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("Y",strtotime($this->search['end_date']));}?>
			                	<?php }?>
			                	</h2>
			                </td>
		                	<td width="30%"></td>
		             	</tr> 
		            </table>
		        </div>
		        <?php if ($this->search['monthlytype']==1){?>
	            	<table class="content-data" id="exportExcel" width="100%" style="border-collapse:collapse; line-height: 24px; font-size: 12px;" >  
					    	<thead>
					    		<tr class="hide" style="border:1px solid #000;">
						             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						        </tr>
						    	<tr class="style" align="center" style="color:#ebfaff;background:#0199ca;text-align: center;table-layout : fixed; white-space:nowrap;line-height: 14px; line-height: 24px; font-size:14px; padding:5px 0px; " >
									<td scope="col" >&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
								    <td scope="col" >&nbsp;
								    	ឈ្មោះមុខ ចំណាយ<br />
								    	Budget Item
								    </td>
								    <?php if (!empty($this->search['start_date'])){
								    	$startmonth= date("Y-m-01",strtotime($this->search['start_date']));
								    	$endmonth= date("Y-m-01",strtotime($this->search['end_date']));
								    	for ($i=0; date("Y-m-01",strtotime("$startmonth+$i month"))<= date("Y-m-01",strtotime($endmonth)); $i++){
								    ?>
								    <td scope="col"  class="verites-col">&nbsp;<span class="verites"><strong><?php echo date("M-Y",strtotime(" $startmonth+$i month"));?></strong></span>&nbsp;</td>
								   <?php }
								    }?>
								    <td scope="col" >&nbsp;<?php echo $tr->translate("TOTAL_EXPENSE");?>&nbsp;</td>
								    <td scope="col" >&nbsp;<?php echo $tr->translate("BUDGET_AMOUNT");?>&nbsp;</td>
								    <td scope="col" >&nbsp;<?php echo $tr->translate("REMAIN");?>&nbsp;</td>
								</tr>
							</thead>
							<tbody>
								<?php 
									$total_expense= 0;
									$total_allexpense = 0;
									$total_remain = 0;
									$total_allbudget= 0;
									$totalAllREmain=0;
									$rowExpensebyComlumn = array();
									
								if (!empty($this->rsBudgets)) foreach ($this->rsBudgets as $key=> $budget){ ?>
								<tr class="fontWeight <?php if($key%2==0)echo'bgRow';?>">
									<td data-label="ល.រ​ /N.o" align="center">&nbsp;<?php echo $key+1?>&nbsp;</td>
									<td data-label="ឈ្មោះមុខ ចំណាយ">&nbsp;<?php echo $budget['budgetTitle']?>&nbsp;</td>
									 <?php if (!empty($this->search['start_date'])){
								    	$startmonth= date("Y-m-01",strtotime($this->search['start_date']));
								    	$endmonth= date("Y-m-01",strtotime($this->search['end_date']));
								    	for ($i=0; date("Y-m-01",strtotime("$startmonth+$i month"))<= date("Y-m-01",strtotime($endmonth)); $i++){
								    		
								    ?>
								    <td data-label="<?php echo date("M-Y",strtotime("$startmonth+$i month"));?>" align="center" style="white-space: nowrap;">
								    	<span class="">
								    	&nbsp;
								    	<?php 
									    	$param = array(
									    			'monthlytype'=>$this->search['monthlytype'],
									    			'budgetItemId'=>$budget['id'],
									    			'projectId'=>$budget['projectId'],
									    			'date'=>date("Y-m",strtotime(" $startmonth+$i month"))
									    	);
									    		$totalBudget = $dbs->getExpensByMonth($param,$budget['projectId'], date("Y-m",strtotime(" $startmonth+$i month")));
									     		if ($totalBudget>0){	echo "$ ".number_format($totalBudget,2);}else { echo "-";};
										     	
									     	$total_expense = $total_expense+$totalBudget;
									     	$total_allexpense = $total_allexpense+$totalBudget;
									     	
											if($key==0){
								     			$rowExpensebyComlumn[$i]=$totalBudget;
							    			}else{
							    				$rowExpensebyComlumn[$i]=$rowExpensebyComlumn[$i]+$totalBudget;
							    			}

								     	?>&nbsp;
								     	</span>
								     </td>
								   <?php }
									 }
									 	$total_allbudget = $total_allbudget+$budget['totalBudget'];
									 	$total_remain = $budget['totalBudget'] - $total_expense;
									 ?>
								    <td data-label="ចំណាយសរុប" align="center" style="white-space: nowrap;">&nbsp;<strong><?php echo "$ ".number_format($total_expense,2);$total_expense=0;?></strong>&nbsp;</td>
								    <td data-label="គ្រោងចំណាយ " align="center" style="white-space: nowrap;">&nbsp;<strong><?php echo "$ ".number_format($budget['totalBudget'],2);?></strong>&nbsp;</td>
								    <td data-label="ប្រាក់នៅសល់ " align="center" style="white-space: nowrap;">&nbsp;<strong style="color: red;"><?php if ($total_remain<0){ echo "$ (".number_format(abs($total_remain),2).")"; }else{ echo "$ ".number_format($total_remain,2);}?></strong>&nbsp;</td>
								</tr>
								<?php }
								if(!empty($rowExpensebyComlumn)){
								?>
								<tr align="center" style="border:1px solid #fff;border-top: 2px dashed #b9bbdd;">
									<td data-label="ចំណាយសរុប"><strong>ចំណាយសរុប</strong></td>
									<?php foreach($rowExpensebyComlumn as $key=>$result){?>
										<td valign="top">$<?php echo number_format($result,2);?></td>
									<?php }?>
									<td ></td>
									<td ></td>
									<td ></td>
								</tr>
								<?php }?>
							  </tbody>
					    	</table>
					    	<div  class="col-md-6 col-sm-6 col-xs-12"></div>
					    	<div  class="col-md-6 col-sm-6 col-xs-12">
					    		<div  class="col-md-4 col-sm-4 col-xs-12">
						    		<div class="blogSummary">
										<div>បានចំណាយសរុប</div>
										<small>Total Budget Paid</small><br />
										<?php echo "$ ".number_format($total_allexpense,2);?>
									</div>
								</div>
								<div  class="col-md-4 col-sm-4 col-xs-12">
									<div class="blogSummary">
										<div>សរុបគ្រោងចំណាយ </div>
										<small>Total Budget Plan</small><br />
										<?php echo "$ ".number_format($total_allbudget,2);?>
									</div>
								</div>
								<div  class="col-md-4 col-sm-4 col-xs-12">
									<div class="blogSummary">
										<div>សរុបនៅសល់ </div>
										<small>Total Budget Balance</small><br />
										<?php $totalAllREmain = $total_allbudget-$total_allexpense; ?>
										<?php
										if ($totalAllREmain<0){ echo "$ (".number_format(abs($totalAllREmain),2).")"; }else{ echo "$ ".number_format($totalAllREmain,2);}?>
									</div>
								</div>
					    	</div>
	            <?php }else{?>
	            	<table id="exportExcel" width="100%" style="border-collapse:collapse; line-height: 24px; font-size: 14px;" >  
					    	<thead>
					    		<tr class="hide" style="border:1px solid #000;">
						             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						        </tr>
						        <tr class="style" align="center" style="color:#ebfaff;background:#0199ca;text-align: center;table-layout : fixed; white-space:nowrap;line-height: 14px; line-height: 24px; font-size:14px; padding:5px 0px; " >
									<td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
								    <td>&nbsp;
								    	ឈ្មោះមុខ ចំណាយ<br />
								    	Budget Item</td>
								    <?php if (!empty($this->search['start_date'])){
								    	$startmonth= date("Y-m-01",strtotime($this->search['start_date']));
								    	$endmonth= date("Y-m-01",strtotime($this->search['end_date']));
								    	for ($i=0; date("Y-m-01",strtotime("$startmonth+$i year"))<= date("Y-m-01",strtotime($endmonth)); $i++){
								    ?>
								    <td class="verites-col">&nbsp;<span class="verites">&nbsp;&nbsp;&nbsp;<strong><?php echo date("Y",strtotime(" $startmonth+$i year"));?></strong>&nbsp;&nbsp;&nbsp;</span>&nbsp;</td>
								   <?php }
								    }?>
								    <td>&nbsp;<?php echo $tr->translate("TOTAL_EXPENSE");?>&nbsp;</td>
								    <td >&nbsp;<?php echo $tr->translate("BUDGET_AMOUNT");?>&nbsp;</td>
								    <td>&nbsp;<?php echo $tr->translate("REMAIN");?>&nbsp;</td>
								</tr>
							</thead>
							<tbody>
								<?php 
									$total_expense= 0;
									$total_allexpense = 0;
									$total_remain = 0;
									$total_allbudget= 0;
									$totalAllREmain=0;
									$rowExpensebyComlumn = array();
								if (!empty($this->rsBudgets)) foreach ($this->rsBudgets as $key=> $budget){ ?>
								<tr class="fontWeight <?php if($key%2==0)echo'bgRow';?>">
									<td align="center">&nbsp;<?php echo $key+1?>&nbsp;</td>
									<td style="white-space: nowrap;">&nbsp;<?php echo $budget['budgetTitle']?>&nbsp;</td>
									 <?php if (!empty($this->search['start_date'])){
								    	$startmonth= date("Y-m-01",strtotime($this->search['start_date']));
								    	$endmonth= date("Y-m-01",strtotime($this->search['end_date']));
								    	
								    	
								    		for ($i=0; date("Y-m-01",strtotime("$startmonth+$i year"))<= date("Y-m-01",strtotime($endmonth)); $i++){
								    ?>
								    <td  align="center" style="white-space: nowrap;">
								    	<span >
								    	&nbsp;
								    	<?php 
								    	$param = array(
								    			'monthlytype'=>$this->search['monthlytype'],
								    			'budgetItemId'=>$budget['id'],
								    			'projectId'=>$budget['projectId'],
								    			'date'=>date("Y-m",strtotime(" $startmonth+$i year"))
								    		);
								    	$totalBudget = $dbs->getExpensByMonth($param,$budget['projectId'], date("Y",strtotime(" $startmonth+$i year")),$this->search['monthlytype']);
								     	if ($totalBudget>0){	echo "$ ".number_format($totalBudget,2);}else { echo "-";};
								     	if($key==0){
								     		$rowExpensebyComlumn[$i]=$totalBudget;
								     	}else{
								     		$rowExpensebyComlumn[$i]=$rowExpensebyComlumn[$i]+$totalBudget;
								     	}
								     	
								     	$total_expense = $total_expense+$totalBudget;
								     	$total_allexpense = $total_allexpense+$totalBudget;
								     	?>&nbsp;
								     	</span>
								     </td>
								   <?php }
									 }
										 $total_allbudget = $total_allbudget+$budget['totalBudget'];
										 $total_remain = $budget['totalBudget'] - $total_expense;
									 ?>
								    <td align="center" style="white-space: nowrap;">&nbsp;<strong><?php echo "$ ".number_format($total_expense,2);$total_expense=0;?></strong>&nbsp;</td>
								    <td align="center" style="white-space: nowrap;">&nbsp;<strong><?php echo "$ ".number_format($budget['totalBudget'],2);?></strong>&nbsp;</td>
								    <td align="center" style="white-space: nowrap;">&nbsp;<strong style="color: red;"><?php if ($total_remain<0){ echo "$ (".number_format(abs($total_remain),2).")"; }else{ echo "$ ".number_format($total_remain,2);}?></strong>&nbsp;</td>
								</tr>
								<?php }
								if(!empty($rowExpensebyComlumn)){
								?>
									<tr align="center" style="border:1px solid #fff;border-top: 2px dashed #b9bbdd;">
										<td></td>
										<td></td>
										<?php foreach($rowExpensebyComlumn as $key=>$result){?>
											<td valign="top">$<?php echo number_format($result,2);?></td>
										<?php }?>
										<td></td>
										<td></td>
										<td></td>
									</tr>
								<?php }?>
							</tbody>
					    </table>
					    <div class="card-box">
						    <div  class="col-md-6 col-sm-6 col-xs-12"></div>
						    <div  class="col-md-6 col-sm-6 col-xs-12">
					    		<div  class="col-md-4 col-sm-4 col-xs-12">
						    		<div class="blogSummary">
										<div>បានចំណាយសរុប</div>
										<small>Total Budget Paid</small><br />
										<?php echo "$ ".number_format($total_allexpense,2);?>
									</div>
								</div>
								<div  class="col-md-4 col-sm-4 col-xs-12">
									<div class="blogSummary">
										<div>សរុបគ្រោងចំណាយ </div>
										<small>Total Budget Plan</small><br />
										<?php echo "$ ".number_format($total_allbudget,2);?>
									</div>
								</div>
								<div  class="col-md-4 col-sm-4 col-xs-12">
									<div class="blogSummary">
										<div>សរុបនៅសល់ </div>
										<small>Total Budget Balance</small><br />
										<?php $totalAllREmain = $total_allbudget-$total_allexpense; ?>
										<?php
										if ($totalAllREmain<0){ echo "$ (".number_format(abs($totalAllREmain),2).")"; }else{ echo "$ ".number_format($totalAllREmain,2);}?>
									</div>
								</div>
					    	</div>
					    </div>
	            <?php }?>
			</div>
	</div>
</div>