<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("INVOICE_PAYMENT_HISTORY")); 
	echo $this->headTitle();
	
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	$dbparmeter = new Report_Model_DbTable_DbParamater();
?>
<div class="reportblog">
	<div class="card-box">
		<div class="col-sm-12 border-botom">
			<div class="col-sm-8 pd-0">
				<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i> <?php echo $tr->translate('INVOICE_PAYMENT_HISTORY');?></h4>
			</div>
			<div class="col-sm-4 text-right">
			</div>
		</div>
	</div>
	<div class="card-box">
		<div id="divPrint">
			<style>
				table.tableTop tr td,span {
					font-size:12px ;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table.tableTop tr td span.project-name{
					font-size:12px ;
					font-family:"Times New Roman","Khmer OS Muol Light";
				}
				table tr td{
					padding:0 2px;
					line-height: 14px;
				}
				table.content-data{
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:13px;
				}
				table.content-data thead tr.style {
				   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #c1d0f3;
					font-weight:600;
				}
				table.content-data  tr.regurlar {
					background: #eee;
				}
				tr.void {
					background: #ffe5e5 !important;
				}
				table.content-data tr td{
					padding:5px 3px; 
					border:none;
					vertical-align:middle;
				}
				table.content-data tr.headRow td{
					border:solid 1px #000;
					padding:10px 2px; 
					vertical-align:middle;
				}
				.content-data tr.headRow td span {
					display: block;
					line-height: 14px;
				}
				.content-data tr.headRow td small {
					display: block;
					line-height: 12px;
					font-size: 10px;
				}

				table.requestInfo {
					width: 100%;
					margin-top: 10px;
				}
				table.requestInfo tr td {
					vertical-align: top;
				}
				table.requestInfo span.lbTitle {
					line-height: 14px;
					float: left;
					vertical-align: top;
					min-width: 20%;
				}
				table.requestInfo span.lbTitle small {
					display: block;
					font-style: italic;
					font-weight: 200;
					line-height: 10px;
				}
				table.requestInfo tr td span {
					line-height: 14px;
					vertical-align: top;
					min-width: 75%;
				}
				span.bold {
					font-weight: 600;
				}
				span.redColor {
					color: #ff0000;
				}
				tr.style.rejected {
					background: #ffcece;
				}
				tr.rowFooter td span {
					font-weight: 600;
					font-size: 12px;
				}
				tr.rowFooter td span.gtotalVal {
					color: #000000;
					display: block;
					width: 100%;
					border-bottom: dashed 1px #959595;
					text-align: right;
				}
				span.gtotalVal.mainTotal {
					font-size: 14px;
				}
				
			</style>
				
			<table class="tableTop" width="100%" >
				<tr>
					<td width="30%" id="projectlogo">
						<br />
						<img style="height:85px; max-width: 100%;" src="">
					</td>
					<td width="40%" valign="top" style=" padding-bottom: 40px;">
					</td>
					<td width="30%" align="right" style="vertical-align:top; position:relative;">
						<span class="project-name" id="projectName">(<?php echo $this->row["branch_name"];?>)</span>
						<?php echo $this->printByFormat;?>
					</td>
				</tr> 
				<tr>
					<td colspan="3" align="center" style="position:relative;" >
						<span style='font-family: "Times New Roman","Khmer OS Muol Light"; display: block;line-height: 16px;' ><?php echo "ប្រវិត្តិការទូទាត់វិក័្កយប័ត្រ";?></span>
						<span style='font-family: "Times New Roman","Khmer OS Muol Light";display: block;line-height: 16px;text-transform: uppercase;font-weight: 600;' ><?php echo "Invoice Payment History";?></span>
						
						
					</td>
				</tr>
				<tr>
					<td colspan="3" style="position:relative;" >
						<?php 
							$void=0;
							if($this->row["status"]==0){
								$void=1;
							}
						?>
						<?php if($void==1){?>
						<div style="opacity: 0.7;position: absolute;display: block;background-size: 80%;z-index: 12;font-size: 40px;color: #f00;transform: rotate(-50deg);border: solid 5px #f00;padding: 26px;top: 110px;left:40%;" ><?php echo $tr->translate("VOID");?></div>
						<?php }?>
						<table class="requestInfo">
							<tr>
								<td width="40%">
									<span class="lbTitle">
										អ្នកផ្គត់ផ្គង់ : 
										<small>Supplier : </small>
									</span>
									<span><?php echo $this->row["supplierName"];?></span>
								</td>
								<td width="30%">
									<span class="lbTitle">
										លេខបញ្ជាទិញ : 
										<small>Purchase N<sup>o</sup> : </small>
									</span>
									<span class="bold redColor" ><?php echo $this->row["purchaseNo"];?></span>
								</td>
								<td width="40%">
									<span class="lbTitle">
									លេខវិក័្កយប័ត្រ : 
										<small>Invoice N<sup>o</sup> : </small>
									</span>
									<span class="bold redColor" ><?php echo $this->row["invoiceNo"];?></span>
								</td>
								
							</tr>
							<tr>
								
								<td>
									<span class="lbTitle">
										ឈ្មោះទំនាក់ទំនង : 
										<small>Contact Name : </small>
									</span>
									<span><?php echo $this->row["contactName"];?></span></td>
								<td >
									<span class="lbTitle">
										កាលបរិច្ឆេទបញ្ជាទិញ : 
										<small>Purchase Date : </small>
									</span>
									<span class="bold"><?php echo date(DATE_FORMAT_FOR_PHP,strtotime($this->row["purchaseDate"]));?></span>
								</td>
								<td >
									<span class="lbTitle">
										កាលបរិច្ឆេទទទួល : 
										<small>Received Date : </small>
									</span>
									<span class="bold"><?php echo date(DATE_FORMAT_FOR_PHP,strtotime($this->row["receiveIvDate"]));?></span>
								</td>
							</tr>
							<tr>
								
								<td>
									<span class="lbTitle">
										លេខទូរសព្ទ : 
										<small>Tel : </small>
									</span>
									<span><?php echo $this->row["supplierTel"];?></span></td>
								<td >
									<?php if(!empty($this->row["requestId"])){?>
									<span class="lbTitle">
										លេខសំណើ : 
										<small>Request N<sup>o</sup> : </small>
									</span>
									<span class="bold redColor" ><?php echo $this->row["requestNo"];?></span>
									<?php }else{?>
									&nbsp;
									<?php }?>
									
								</td>
								<td >
									<span class="lbTitle">
										លេខវិក័្កយប័ត្រ(ក្រៅ) : 
										<small>Supplier Invoice N<sup>o</sup> : </small>
									</span>
									<span class="bold redColor" ><?php echo $this->row["supplierInvoiceNo"];?></span>
								</td>
							</tr>
							<tr>
								
								<td rowspan="2">
									<span class="lbTitle">
										អាសយដ្ឋាន : 
										<small>Address : </small>
									</span>
									<span><?php echo $this->row["address"];?></span></td>
								<td >
									
										<?php if(!empty($this->row["requestId"])){?>
										<span class="lbTitle">
											កាលបរិច្ឆេទស្នើ : 
											<small>Request Date : </small>
										</span>
										<span class="bold"><?php echo date(DATE_FORMAT_FOR_PHP,strtotime($this->row["requestDate"]));?></span>
										<?php }?>
								</td>
								<td >
									<span class="lbTitle">
										កាលបរិច្ឆេទក្នុងវិក័្កយប័ត្រ : 
										<small>Invoice Date : </small>
									</span>
									<span class="bold"><?php echo date(DATE_FORMAT_FOR_PHP,strtotime($this->row["invoiceDate"]));?></span>
								</td>
							</tr>
							<tr>
								<td>
								</td>
								<td>
										<?php if(!empty($this->row["requestName"])){?>
										<span class="lbTitle">
											ស្នើដោយ : 
											<small>Request By : </small>
										</span>
										<span><?php echo $this->row["requestName"];?></span>
										<?php }?>
								</td>
								<td>
								</td>
							</tr>
							
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3" >
						<table class="content-data" width="100%" border="1"  cellspacing="0" cellpadding="0">
							<thead>
								<tr class="style headRow" align="center" >
									<td class="center">
										<span>ល.រ</span>
										<small>N<sup>o</sup></small>
									</td>
									<td class="center" style="width:200px;">
										<span>លេខការទូទាត់</span>
										<small>Payment N<sup>o</sup></small>
									</td>
									<td class="center">
										<span>កាលបរិច្ឆេទ</span>
										<small>Payment Date</small>
									</td>
									<td class="center">
										<span>វិធីសាស្រ្តទូទាត់</span>
										<small>Payment Method</small>
									</td>
									<td class="center">
										<span>ធនាគារ</span>
										<small>Bank</small>
									</td>
									<td class="center">
										<span>លេខ និង ឈ្មោះគណនី</span>
										<small>Bank Account Name / Number</small>
									</td>
									<td class="center">
										<span>ទឹកប្រាក់បានទូរទាត់ (USD)</span>
										<small>Payment Amount</small>
									</td>
									<td class="center">
										<span>ស្ថានភាព</span>
										<small>Payment Status</small>
									</td>
								</tr>
							</thead>
							 <?php 
							 $i=0;
							 $minimumRow=15;
							 $gTotal=0;
				                if(!empty($this->rowdetail)) foreach ($this->rowdetail as $index => $rs){ $i++;
								$classRowBg = "odd";
								if(($i%2)==0){
								$classRowBg = "regurlar";
								}
								$gTotal=$gTotal+$rs["paymentAmount"];
								$paymentStatus=$rs["paymentStatus"];
								$classVoid="";
								if(!empty($rs["statusTitle"])){
									$paymentStatus=$rs["statusTitle"];
									$classVoid=" void";
								}
							?>
							<tr class="style <?php echo $classRowBg; echo $classVoid;?>" style=" white-space:nowrap;">
				               	<td style="text-align: center;"><?php echo $i; ?></td>
								<td>
									<?php echo $rs["paymentNo"];?>
								</td>
								<td align="center"><?php echo date(DATE_FORMAT_FOR_PHP,strtotime($rs["paymentDate"]));?></td>
								<td ><?php echo $rs["paymentMethodTitle"];?></td>
								<td ><?php echo empty($rs["bankName"])?"N/A":$rs["bankName"];?></td>
								<td ><?php echo $rs["accNameAndChequeNo"];?></td>
								<td align="right"><?php echo number_format($rs["paymentAmount"],2);?></td>
								<td ><?php echo $paymentStatus;?></td>
							</tr>
							<?php } ?>
							<?php for ($i = $i; $i <= $minimumRow; $i++) { ?>
							<tr class="style <?php //echo $classRow; ?>" style=" white-space:nowrap;">
								<td style="border:none;" colspan="7">&nbsp;</td>
							</tr>
							<?php } ?>
						</table>
						
					</td>
				</tr>
				<tr>
					<td colspan="3" >
						<br />
						<table style="width:45%; float: left;" border="1"  cellspacing="0" cellpadding="0">
							<?php if(!empty($this->DNList)){?>
							<tr>
								<td style="vertical-align: top;padding: 2px 5px;height: 80px; line-height: 16px;">
									<span style="font-weight: 600; display: block;text-decoration: underline;">ព៏ត៌មានការដឹញ្ជូន / Delivery Information ៖</span>
									<span style="font-weight: 600; display: block; font-size:11px;"><?php echo $this->DNList['DNNumberList'];?><span>
								</td>
							</tr>
							<tr>
								<td style="height:10px; border:none;border-right: solid 1px #fff;border-left: solid 1px #fff;">
								</td>
							</tr>
							<?php } ?>
							<tr>
								<td style="vertical-align: top;padding: 2px 5px;height: 80px; line-height: 16px;">
									<span style="font-weight: 600; display: block;text-decoration: underline;">សម្គាល់ / Note ៖</span>
									<span style="display: block; font-size:11px;"><?php echo $this->row["note"];?><span>
								</td>
							</tr>
						</table>
						<table style="width: 55%;">
							<tr class="rowFooter" style=" white-space:nowrap;">
								<td style="width:70%; text-align:right;" ><span>សរុប / Total (USD):</span></td>
								<td style="border:none; " ><span class="gtotalVal"><?php echo number_format($gTotal,2);?></span></td>
							</tr>
							<?php if(!empty($this->rowdetailServicce)) foreach ($this->rowdetailServicce as $index => $rs){ $gTotal=$gTotal+$rs["totalReceive"];?>
							<tr class="rowFooter" style=" white-space:nowrap;">
								<td style="width:70%; text-align:right;" ><span><?php echo $rs["proName"]." (USD)";?> :</span></td>
								<td style="border:none; " ><span class="gtotalVal"><?php echo number_format($rs["totalReceive"],2);?></span></td>
							</tr>
							<?php } ?>
							<tr class="rowFooter" style=" white-space:nowrap;">
								<td style="width:70%; text-align:right;" ><span>សរុបរួម / Grand Total (USD):</span></td>
								<td style="border:none; " ><span class="gtotalVal mainTotal"><?php echo number_format($gTotal,2);?></span></td>
							</tr>
						</table>
						<div class="clearfix" style="clear: both !important;"></div>
						<table width="100%" cellspacing="0" cellpadding="0" style="margin-top:10px;" >
							<tr>
								<td style="width:25%; vertical-align: top;line-height: 16px; text-align:center;">
									<span style="font-weight: 600; display: block;">អ្នកផ្គត់ផ្គង់ / Supplier </span>
								</td>
								<td style="width:25%; vertical-align: top;line-height: 16px; text-align:center;">
									<span style="font-weight: 600; display: block;"><?php //echo $tr->translate("CHECKING_BY");?> </span>
								</td>
								<td style="width:25%; vertical-align: top;line-height: 16px; text-align:center;">
									<span style="font-weight: 600; display: block;"><?php //echo $tr->translate("PCHECKING_BY");?> </span>
								</td>
								<td style="width:25%; vertical-align: top;line-height: 16px; text-align:center;">
									<span style="font-weight: 600; display: block;">អ្នកតំណាងក្រុមហ៊ុន / Company Represent</span>
								</td>
							</tr>
							<tr>
								<td colspan="3" style="height:80px;" >
									&nbsp;
								</td>
							</tr>
							<tr>
								<td style="text-align:center;">
									<span style="font-weight: 600; display: block; line-height: 16px;"><?php echo $this->row["supplierName"];?></span>
								</td>
								<td style="text-align:center;">
									
								</td>
								<td style="text-align:center;">
									
								</td>
								<td style="text-align:center;">
									<span style="font-weight: 600; display: block; line-height: 16px;"><?php echo $this->row["byUser"];?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<script>
require(["dojo/ready"], function(ready){
	ready(function(){
		 getBranchInfo();
	});
});
		
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->row['projectId'])?0:$this->row['projectId'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:65px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			document.getElementById('projectName').innerHTML = 'គម្រោង៖ '+arr.project_name;
		},
		error: function(e) {
		}
	});
}
</script>
