<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$dbGB = new Application_Model_DbTable_DbGlobal();

	$montFomat=DATE_FORMAT_FOR_PHP;
	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
	
	$branch_title = $tr->translate("BRAND_TITLE");
	
	$dbGBstock = new Application_Model_DbTable_DbGlobalStock();
	$arrStep = array(
			'keyIndex'=>1,//Purchase By Request
			'typeKeyIndex'=>1,
		);
	//$purchaseType = $dbGBstock->purchasingTypeKey($arrStep);
	
	$expenseLetter = $this->baseUrl()."/report/stockmg/expense-letter/id/";

?>
<title><?php echo $tr->translate("RPT_EXPENSE");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div class="reportblog">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i> <?php echo $tr->translate('RPT_EXPENSE');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<form method="post">
			<div class="card-box">
		    	<div class="form-group">
					<label class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("branch_id");?>
					</label>
					<label  class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("paymentMethod");?>
					</label>
					<label  class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("bankId");?>
					</label>
					
					<label class="col-md-2 col-sm-2 col-xs-12">
						<input id="budgetItem" />
					</label>
				</div>
				<div class="form-group">
					<label class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("start_date");?>
					</label>
					<label class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("end_date");?>
					</label>	
					<label  class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("btn_search");?>
					</label>
				</div>
				
			</div>
		</form>
		<div style="width:100%; margin:0 auto;">
		<div style="min-height:22cm; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
			</style>
			<div id="divPrint">
				<style type="text/css">
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table { page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					td.rightText{
						text-align: right;
					}
					.redBold {
						font-weight: 600;
						color: #f80000;
					}
					tr.style.void td {
						background: #fff6f6;
					}
					
					table.totalBottom{
						line-height: 25px; 
						font-size:11px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.totalBottom tr td{
						padding:2px;
						line-height: 14px;
					}
					table.totalBottom tr.rowHead td {
						padding: 4px 0;
						font-weight: 600;
					}
					tr.rowHead td.mainCol {
						width: 15%;
						border-bottom: solid 2px #000;
						border-top: solid 2px #000;
						padding: 2px 0;
					}
					td.blankCol {
						width: 2%;
					}
					td.sideCol {
						width: 10%;
					}
					td.valueData {
					}
					td.valueData.totalVal {
						font-weight: 600;
					}
				</style>
				<table width="100%">
					<tr>
				    	<td align="center" valign="top">
				        	<div class="divFooter">
					        	<?php echo $this->headerReport;?>
				            </div>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				            <table class="content-data" width="100%" border="1"  cellspacing="0" cellpadding="0">
					            <thead>
					                <tr class="hide" style="border:1px solid #000;">
					                	<td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
					                </tr>
					                <tr class="style" align="center" >
					                    <td scope="col" rowspan="2" class="center"><?php echo $tr->translate("NUM");?></td>
										<td scope="col" colspan="5" class="center"><?php echo $tr->translate("EXPENSE_INFO");?></td>    
					                    <td scope="col" colspan="4" class="center"><?php echo $tr->translate("AMOUNT_INFO");?></td>    
					                    <td scope="col" colspan="2" class="center"><?php echo $tr->translate("INVOICE_INFO");?></td>    
					                    <td scope="col" colspan="2" class="center"><?php echo $tr->translate("OTHER");?></td>    
					                 
					                </tr>
					                <tr class="style" align="center">
					                	<td scope="col" style="padding:1px;"><?php echo $tr->translate("BRANCH_NAME");?></td>                   
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("EXPENSE_TITLE");?></td>
										<td scope="col" style="padding:1px;"><?php echo $tr->translate("BUDGET_ITEM");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("DATE");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("RECEIVER");?></td>
										
										<td scope="col" style="padding:1px;"><?php echo $tr->translate("PAYMENT_METHOD");?></td>
										<td scope="col" style="padding:1px;"><?php echo $tr->translate("BANK");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("ACCOUNT_AND_CHEQUE_NO");?></td>	                    
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("TOTAL_EXPENSE")." ".$tr->translate("CURRENCY_SIGN");?></td>
										
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("INVOICE_NO");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("SUPPLIER_INVOICE");?></td>
										
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("NOTE");?></td>
					                    <td scope="col" style="padding:1px;"><?php echo $tr->translate("BY");?></td>
					                </tr>
					            </thead>
				                <?php 
				                	$totalCash = 0;
									$totalCheque = 0;
									$totalBank = 0;
				                	$gTotal=0;
				                	$i=1;
				                ?>
				                <?php 
				                if(!empty($this->row)) foreach ($this->row as $index => $rs){
									$class="";
									if($rs["status"]==1){
										if($rs["paymentMethod"]==1){
											$totalCash =$totalCash+$rs["totalAmount"];
										}elseif($rs["paymentMethod"]==2){
											$totalBank =$totalBank+$rs["totalAmount"];
										}elseif($rs["paymentMethod"]==3){
											$totalCheque =$totalCheque+$rs["totalAmount"];
										}
										$gTotal =$gTotal+$rs["totalAmount"];
									}
								?>
				                <tr oncontextmenu="setrowdata(<?php echo $rs['id'];?>);return false;" class=" context-menu-one style <?php echo $class;?>" style="font-family: 'Khmer OS Content'; white-space:nowrap; ">
				               		<td data-label="<?php echo $tr->translate("NUM");?>" style="text-align: center;"><?php echo $i++; ?></td>
				               		<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>" ><?php echo $rs["projectName"];?></td>
				               		<td data-label="<?php echo $tr->translate("EXPSENSE_TITLE");?>" ><?php echo $rs["expenseTitle"];?></td> 
									<td data-label="<?php echo $tr->translate("BUDGET_ITEM");?>" ><?php echo $rs["budgetItem"];?></td>        
									<td data-label="<?php echo $tr->translate("DATE");?>"  class="centerText"><?php echo date($montFomat,strtotime($rs["paymentDate"]));?></td>
									<td data-label="<?php echo $tr->translate("RECEIVER");?>" ><?php echo $rs["receiver"];?></td>
									
									
									<td data-label="<?php echo $tr->translate("PAYMENT_METHOD");?>" ><?php echo $rs["paymentMethodTitle"];?></td>
									<td data-label="<?php echo $tr->translate("BANK");?>" ><?php echo empty($rs["bankName"])?"N/A":$rs["bankName"];?></td>
									<td data-label="<?php echo $tr->translate("ACCOUNT_AND_CHEQUE_NO");?>" ><?php echo $rs["accNameAndChequeNo"];?></td>
									<td data-label="<?php echo $tr->translate("PAID");?>"  class="rightText"><?php echo number_format($rs["totalAmount"],3);?></td>
									
									<td data-label="<?php echo $tr->translate("INVOICE_NO");?>"  class="centerText redBold"> <?php echo $rs["paymentNo"];?></span></td>
									<td data-label="<?php echo $tr->translate("SUPPLIER_INVOICE");?>" ><?php echo $rs["externalInvoice"];?></span></td>
									
									<td data-label="<?php echo $tr->translate("NOTE");?>" ><?php echo $rs["note"];?></span></td>
									<td data-label="<?php echo $tr->translate("BY");?>"  class="centerText"><?php echo $rs["byUser"];?></td>
								</tr>
				                <?php }?>
				              
								
				            </table>
							<br />
				            <table class="totalBottom" style="width:100%;">
								
								<tr class="rowHead">
									<td class="sideCol"></td>
									<td class="mainCol centerText"><?php echo $tr->translate("CASH");?></td>
									<td class="blankCol">&nbsp;</td>
									<td class="mainCol centerText"><?php echo $tr->translate("PAYWITH_BANK");?></td>
									<td class="blankCol">&nbsp;</td>
									<td class="mainCol centerText"><?php echo $tr->translate("CHEQUE");?></td>
									<td class="blankCol">&nbsp;</td>
									<td class="mainCol centerText"><?php echo $tr->translate("TOTAL");?></td>
									<td class="sideCol"></td>
								</tr>
								<tr>
									<td class="rightText"><?php echo $tr->translate("CURRENCY_SIGN");?></td>
									<td class="valueData centerText"><?php echo number_format($totalCash,3);?></td>
									<td></td>
									<td class="valueData centerText"><?php echo number_format($totalBank,3);?></td>
									<td></td>
									<td class="valueData centerText"><?php echo number_format($totalCheque,3);?></td>
									<td></td>
									<td class="valueData totalVal centerText"><?php echo number_format($gTotal,3);?></td>
								</tr>
				            </table>
							
							
							<br />
						    <?php echo $this->footerReport;?>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	dojo.require("dijit.form.DateTextBox");
	var budgetItemStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->budgetItem));?> );
	var budgetTypeStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->budgetType));?> );
	require(["dojo/ready"], function(ready){
		ready(function(){

				
				new dijit.form.FilteringSelect({
					store: budgetItemStore,
					autoComplete: false,
					queryExpr: "*${0}*",                       
					id: "budgetItem",
					name: "budgetItem",  
					class: 'fullside',  
			
					required:false,
					placeHolder:"<?php echo $tr->translate("SELECT_BUDGET_ITEM");?>", 
				}, "budgetItem");
			 
			 getBranchInfo();
			 
			 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			 document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("RPT_EXPENSE");?>';
			 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date(DATE_FORMAT_FOR_PHP); }else{ echo date(DATE_FORMAT_FOR_PHP,strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date(DATE_FORMAT_FOR_PHP,strtotime($this->search['end_date'])); }?>';
		});
		
	});

function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="expenseLetter"){
				url='<?php echo $expenseLetter;?>';
			}
			gotoAction();
		},
		items: {
			"expenseLetter": {name: "<?php echo $tr->translate("EXPENSE_LETTER");?>", icon: "fa-file-text", accesskey: "c"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>