<?php	
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$this->headTitle($tr->translate('PLONG_STEP'));
	echo $this->headTitle();
?>
<style>
.fullside50{ width:48%;}
.hover:hover{background: #eee !important;}
</style>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				identity= $("#identity").val();
				if(identity=='' || identity==null){
					infoMessageAlert("<?php echo $tr->translate("PLEASE_SELECT");?>");
					dijit.byId("loan_number").focus();
					return false;
				}

				process_status = dijit.byId('process_status').get('value');
            	if (process_status==0){
					infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_PROCCESSING");?>');
					dijit.byId('process_status').focus();
					return false;
				}
				
				loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('PLONG_STEP');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-tasks" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INFO_INDILOAN");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branch_id')?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_CODE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id='loan_number' />
											<input type="hidden" name="identity" id="identity"  value="" >
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-indent-left" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("PROCESS_INFO");?></p>
										</div> 
									</div>		
									
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DATE");?>:
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('date')?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROCCESSING");?>:
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('process_status')?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("GIVE_BY");?>:
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('give_by')?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("RECEIVE_BY");?>:
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('receive_by')?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	    		</div>
	    		<div class="col-md-8 col-sm-8 col-xs-12">
	    			<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-tasks" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INFO_INDILOAN");?></p>
										</div> 
									</div>
									<br />
									<div  id="showrecord"></div>
									<div id='data_table_loan_haspay' name='data_table_loan_haspay' style="white-space: nowrap;"></div>
								</div>
							</div>
						</div>
					</div>
	    		</div>
	    	</div>
	    	<div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" class="button-class button-danger" iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("SAVE")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button" />
    			</div>
    		</div>
		</form>
	</div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dijit/form/Textarea"]);
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var sale_store  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	 ready(function(){
	  });
	new dijit.form.FilteringSelect({
		store: sale_store,
		required: false,		           
		name: "loan_number",
		id: "loan_number",
		autoComplete: false,
		queryExpr: "*${0}*",      
		searchAttr: "name",
		class: 'fullside',
		onChange: function(){
			checkSaleInPlongStep();
			
	    }
		}, "loan_number");
	 
});
var url_checksale = '<?php echo $this->url(array('module'=>'issue','controller'=>'plongstep','action'=>'checksale')); ?>';
function checkSaleInPlongStep(){
	loan_number = dijit.byId('loan_number').get('value');
	if(loan_number=='' || loan_number=='-1'){
		infoMessageAlert('Please Select Sale Property');
		dijit.byId('loan_number').focus();
		return false;
	}
	dojo.xhrPost({
		url: url_checksale,	
		content:{ 
		    'sale_id':loan_number,
		},		    
		handleAs:"json",
		load: function(data) {
			if(data==1){
				infoMessageAlert('<?php echo $tr->translate("SALE_ALREADY_ON_PLONG_STEP"); ?>');
			}else{
				addRow();
			}
		},
		error: function(err) {
			
		}
	});
}

function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	getAllSaleNumber(branch_id);
}
function setBranchID(){}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		infoMessageAlert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
		},
		error: function(err) {
			
		}
	});
}

var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getInfoByLoanNumber(index){
	loan_id = dijit.byId('loan_number').get('value');
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'sale_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('customer_id'+index).set('value', data.client_id);
			dijit.byId('property_id'+index).attr('value', data.house_id);
			
		},
		error: function(err) {
			infoMessageAlert(err);
		}
	});
}
var sale_number_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getsalenumber = "<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-sale-number')); ?>";
function getAllSaleNumber(branch_id){//used
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value'),
		    'is_issueplong':1
		},		    
		handleAs:"json",
		load: function(data) {
			sale_number_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('loan_number').set('store',sale_number_store); 
		},
		error: function(err) {
			
		}
	});
}

col=0;no=0;
title=0;
temp='';
function addRow(){
	loan_number=dijit.byId("loan_number").get("value");
	if(loan_number=='' || loan_number==-1){
		return false;
	}
	var iden = $("#identity").val();
	var arrays = iden.split(',');
	 if(arrays!=""){
		 for(var i=0;i< arrays.length;i++){
			 readychoose = dijit.byId('sale_id'+arrays[i]).get('value');
			 if(readychoose==loan_number){
				 infoMessageAlert("<?php echo $tr->translate("Choosen ready")?>");
				 return false;
			 }
		}
	}
		
	temp='';
	col++;no++;
	template='';
	if(title!=1){    
		tmp='<table id="table_row" class="collape responsiveTable">';
		tmp+='<tr id="head-title" class="head-td" align="center"></tr>';
		tmp+='</table>';
		dojo.query("#showrecord").append(tmp);
		
		temp+='<th scope="col" width="47px"><?php echo $tr->translate("DEL");?></th>';
		temp+='<th scope="col" width="2%"><?php echo $tr->translate("NUM");?></th>';
		temp+='<th scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></th>';
		temp+='<th scope="col"><?php echo $tr->translate("NOTE");?></th>';
		
		dojo.query("#head-title").append(temp);
		title=1;
	}else{
	}
		sale_label = dijit.byId("loan_number").attr("displayedValue");
		sale_id = dijit.byId("loan_number").get("value");
		template+='<td data-label="<?php echo $tr->translate("DEL");?>" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD");?>" class="removeRow" onclick="deleteRecord('+col+');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span><input class="fullside" value="" type="hidden" data-dojo-type="dijit.form.TextBox" id="customer_id'+col+'" name="customer_id'+col+'" /></td>';
		template+='<td data-label="<?php echo $tr->translate("NUM");?>"  align="center">'+no+'</td>';
		template+='<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" style="white-space: nowrap"><input class="fullside" value="'+sale_id+'" type="hidden" data-dojo-type="dijit.form.TextBox" id="sale_id'+col+'" name="sale_id'+col+'" />'+sale_label+'<input class="fullside" value="" type="hidden" data-dojo-type="dijit.form.TextBox" id="property_id'+col+'" name="property_id'+col+'" /></td>';	
		template+='<td data-label="<?php echo $tr->translate("NOTE");?>"><input class="fullside" type="text" name="note'+col+'" id="note'+col+'" dojoType="dijit.form.TextBox" /></td>';
	tmp='<tr class="rowData hover" id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	getInfoByLoanNumber(col);
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}
</script>