<?php	
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$this->headTitle($tr->translate('PLONG_STEP'));
	echo $this->headTitle();
?>
<style>
.fullside50{ width:48%;}
.hover:hover{background: #eee !important;}
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				loadingBlock();
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('PLONG_STEP');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-map" aria-hidden="true"></i> <?php echo $tr->translate("INFO_INDILOAN");?> 
	                   </label>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('branch_id')?>
	                    	<?php echo $frm->getElement('customer_id')?>
	                    	<?php echo $frm->getElement('property_id')?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_CODE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id='loan_number' />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?>:
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('note')?>
	                   </div>
	                </div>
	    		</div>
	    		<div class="col-md-8 col-sm-8 col-xs-12">
	    			<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-list" aria-hidden="true"></i> <?php echo $tr->translate("PROCESS_HISTORY");?> 
	                   </label>
	                </div>
	                <?php if (!empty($this->rsdetail)){?>
	                <div class="form-group">
	                	<table class="history-record" >
	                		<thead>
	                			<tr>
	                				<th><?php echo $tr->translate("NUM");?></th>
	                				<th><?php echo $tr->translate("DATE");?></th>
	                				<th><?php echo $tr->translate("PROCCESSING");?></th>
	                				<th><?php echo $tr->translate("GIVE_BY");?></th>
	                				<th><?php echo $tr->translate("RECEIVE_BY");?></th>
	                				<th>&nbsp;</th>
	                			</tr>
	                		</thead>
	                		<tbody>
	                		<?php foreach ($this->rsdetail as $key => $record){?>
	                			<tr>
	                				<td align="center">&nbsp;<?php echo $key+1;?>&nbsp;</td>
	                				<td align="center">&nbsp;<?php echo date("d/M/Y",strtotime($record['date']))?>&nbsp;</td>
	                				<td align="center">&nbsp;<?php echo $record['processing'];?>&nbsp;</td>
	                				<td align="center">&nbsp;<?php echo $record['give_by']?>&nbsp;</td>
	                				<td align="center">&nbsp;<?php echo $record['receive_by'];?>&nbsp;</td>
	                				<td align="center">&nbsp;
	                					<?php 
	                					$url="#";
	                					$url = $this->baseUrl()."/loan/plongstep/stepup/id/".$this->rs['id']."?record=".$record['id'];
										?>
	                					<a class="btn btn-primary btn-xs" target="_blank" title="<?php echo $tr->translate("Update Or Edit Result");?>" href="<?php echo $url;?>">
	                					<i class="fa fa-edit" aria-hidden="true"></i>
	                					</a>&nbsp;
	                				</td>
	                			</tr>
	                			<?php }?>
	                		</tbody>
	                	</table>
	                </div>
	                <?php }?>
	    		</div>
	    	</div>
	    	<div class="col-md-4 col-sm-4 col-xs-12">
	    	</div>
	    	<div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" label="<?php echo $tr->translate("SAVE")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
    			</div>
    		</div>
		</form>
	</div>
</div>
<style>
table.history-record {
    width: 100%;
    font-size: 12px;
}
table.history-record thead tr th {
    text-align: center;
    padding: 5px 2px;
    background: #e0eafb;
    border-bottom: solid 1px #afadad;
}
table.history-record tbody tr {
    border-bottom: solid 1px #e8e8e8;
}
table.history-record tbody tr td {
    padding: 5px;
	vertical-align: top;
}
</style>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dijit/form/Textarea"]);
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var sale_store  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	
	new dijit.form.FilteringSelect({
		store: sale_store,
		required: false,	
		readOnly: true,	           
		name: "loan_number",
		id: "loan_number",
		autoComplete: false,
		queryExpr: "*${0}*",      
		searchAttr: "name",
		class: 'fullside',
		onChange: function(){
			getInfoByLoanNumber();
	    }
		}, "loan_number");

	 ready(function(){
		 filterClient()
	  });
	 
});


function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	getAllSaleNumber(branch_id);
}

function setBranchID(){}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
		},
		error: function(err) {
			
		}
	});
}

var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getInfoByLoanNumber(){
	loan_id = dijit.byId('loan_number').get('value');
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'sale_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('customer_id').set('value', data.client_id);
			dijit.byId('property_id').set('value', data.house_id);
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
var oldbranhc_id = '<?php echo $this->rs['branch_id']?>'
var sale_number_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getsalenumber = "<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-sale-number')); ?>";
function getAllSaleNumber(branch_id){//used
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value'),
		    'is_issueplong':1
		},		    
		handleAs:"json",
		load: function(data) {
			sale_number_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('loan_number').set('store',sale_number_store); 
		    if(oldbranhc_id==dijit.byId('branch_id').get('value')){
		    dijit.byId('loan_number').set('value','<?php echo $this->rs['sale_id']?>'); 
		    }
		},
		error: function(err) {
			
		}
	});
}

</script>