<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ISSUE_HOUSE'));
	$frm = $this->frm_loan;
?>
 <div class="card">
	<div class="card-content collapse show">
		<form id="add_cancel" action="<?php echo $this->url(array('module'=>'issue','controller'=>'index','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					dijit.byId('savenew').set('disabled',true);
    				return true;
   				}else {
    				return false;
   				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ISSUE_HOUSE');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-inbox" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("ISSUE_HOUSE");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?>  :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branch_id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_CODE")?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="sale_no" />
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PAYMENT_TYPE")?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('payment_id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><strong><?php echo $tr->translate("ELECTRIC_START");?></strong> :</label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('electric_start');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><strong><?php echo $tr->translate("WATER_START");?></strong> :</label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('water_start');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CONTACT_CONSTRUCTION");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('contact_contruction');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('note');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("RECEIVED_DATE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('issue_date');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('status');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	             </div>
	             <div class="col-md-6 col-sm-6 col-xs-12">
	             </div>
	         </div>
	         <div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" name="savenew" id="savenew" value="<?php echo $tr->translate('GO_EDIT')?>" label="<?php echo $tr->translate('GO_EDIT')?>" id="submitButton" dojoType="dijit.form.Button" />
    			</div>
    		</div>
		</form>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.NumberTextBox");

var sale_no_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var plongtype_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->layouttype));?> );
dojo.ready(function(){
	try{
		new dijit.form.FilteringSelect({
			store: sale_no_store,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: true,		           
			name: "sale_no",
			id: "sale_no",
			searchAttr: "name",
			class: 'fullside',
				onChange: function() {
				}
			}, "sale_no");

		getSaleClie();
		}catch(e){
		}
});
var	url_getSaleClien = '<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'get-saleclie'));?>';
function getSaleClie(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==0){
		return false;
	}
	dojo.xhrPost({
		url:url_getSaleClien,	
		content:{ 
			'branch_id': branch_id,'sale_id':'',
		},
		handleAs:"json",
		load: function(data) {	
			sale_no_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('sale_no').set('store', sale_no_store);
		    dijit.byId('sale_no').attr('value','<?php echo $this->rs['sale_id'];?>');
		},
		error: function(err) {
		}
	});
}
</script>