<!DOCTYPE html>
<html lang="en">
<?php $tr=Application_Form_FrmLanguages::getCurrentlanguage();
?>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/images/icon.ico" type="image/x-icon"/>
    <title><?php echo $tr->translate("Sale Dash")?> </title>

    <!-- Bootstrap -->
    <link href="<?php echo $this->baseUrl();?>/admin/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="<?php echo $this->baseUrl();?>/admin/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <!-- NProgress -->
    <link href="<?php echo $this->baseUrl();?>/admin/vendors/nprogress/nprogress.css" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="<?php echo $this->baseUrl();?>/admin/build/css/custom.min.css" rel="stylesheet">
    
     <script src="<?php echo $this->baseUrl()."/contextMenu/1.11.3/"?>jquery.min.js"></script>
    <link href="<?php echo $this->baseUrl()."/admin/"?>/select2/css/select2.min.css" rel="stylesheet">
	 <script src="<?php echo $this->baseUrl()."/admin/"?>/select2/js/select2.js"></script>   
	 <script src="<?php echo $this->baseUrl()?>/admin/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
	<style>
		/* Select 2 */
		.select2-container .select2-selection--single {
		  border: 1px solid #E3E3E3 !important;
		  height: 38px !important; }
		  .select2-container .select2-selection--single .select2-selection__rendered {
		    line-height: 30px !important;
		    padding-left: 12px !important; }
		  .select2-container .select2-selection--single .select2-selection__arrow {
		    height: 34px;
		    width: 34px;
		    right: 3px; }
		    .select2-container .select2-selection--single .select2-selection__arrow b {
		      border-color: #999 transparent transparent transparent;
		      border-width: 6px 6px 0 6px; }
		
		.select2-container--open .select2-selection--single .select2-selection__arrow b {
		  border-color: transparent transparent #999 transparent !important;
		  border-width: 0 6px 6px 6px !important; }
		
		.select2-container--default .select2-results__option--highlighted[aria-selected] {
		  background-color: #000000; }
		
		.select2-results__option {
		  padding: 6px 12px; }
		
		.select2-dropdown {
		  border: 1px solid #e3e3e3 !important;
		  padding-top: 5px;
		  box-shadow: 0 2px 2px rgba(0, 0, 0, 0.15); }
		
		.select2-search input {
		  border: 1px solid #e3e3e3 !important; }
		
		.select2-container .select2-selection--multiple {
		  min-height: 38px !important;
		  border: 1px solid #e3e3e3 !important; }
		  .select2-container .select2-selection--multiple .select2-selection__rendered {
		    padding: 2px 10px; }
		  .select2-container .select2-selection--multiple .select2-search__field {
		    margin-top: 7px;
		    border: 0 !important; }
		  .select2-container .select2-selection--multiple .select2-selection__choice {
		    background-color: #f5f5f5;
		    border: 1px solid #e3e3e3;
		    border-radius: 1px;
		    padding: 0 7px; }
		span.select2.select2-container.select2-container--default {
		    width: 100% !important;
		}
.login {
    background: #fff;
}
		.header-top {
		    background: #02014a;
		    color: #fff;
		    padding: 10px 0;
		    min-height: 10%;
		    border-bottom: solid 4px #0077c5;
		}
		.system-title {
		    font-size: 18px;
		    font-family: 'Khmer MEF2';
		    line-height: 30px;
		}
		.imgage-content.text-center {
		    padding: 45px 0;
		}
		.searc-blog-main {
		    padding: 0;
		    margin-top: 13px;
		    background: #fff;
		    min-height: 630px;
			border-left: solid 1px #eee;
   			box-shadow: -1px 16px 13px #e4e4e4;
		}
.property-detail .contetn-data span i {
    font-size: 15px;
}
	</style>
  </head>

  <body class="login">
    <div>
      <div class="header-top">
    			<div class="col-md-3 col-sm-3 col-xs-12">
    				<img src="<?php echo $this->baseUrl();?>/images/cam-app-logo.png" style="max-height:45px;margin: 0;padding-left: 10px;">
    			</div>
    			<div class="col-md-6 col-sm-6 col-xs-12">
    				<div class="system-title text-center">
    				<?php echo $this->data["system_name"];?><br />
					Installment Management System
					</div>
    			</div>
    			<div class="col-md-3 col-sm-3 col-xs-12">
    			</div>
    			<div class="clearfix"></div>
    		</div>
	 		<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
	  			<div class="imgage-content text-center">
    				<img src="<?php echo $this->baseUrl()."/images/loan-animationold.png"?>" style="width: 300px;">
    			</div>
    			 <div class="text-center">
                  <h1></h1>
                  <div style="height: 200px;"></div>
                  <p>&copy រក្សាសិទ្ធិគ្រប់យ៉ាង 
                  	<a title="<?php echo $this->data['power_by']?>" class="copyright" href="http://<?php echo $this->data['companywebsite']?>" target="_blank">
								<strong><?php echo $this->data['power_by']?></strong></a>
					<br />
					<?php echo $this->data['branch-tel'];	?>
				</p>
                </div>
	 		 </div>
	  		<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 " style="background: #fff;">
	  			<div class="card-box searc-blog-main">
					<form id="list" name="list" action="" dojoType="dijit.form.Form" method="GET">
		          		<div class="x_panel searc-blog">
		          			<div class="x_title">
						    	<h2><i class="fa fa-search"></i> <?php echo $tr->translate("Finding Sale")?></h2>
								<span class="pull-right">
								</span>
								<div class="clearfix"></div>
							</div>
							<div class="x_content search">
								<?php $frm = $this->frm_degree;?>
								<div class="form-control">
									<div class="search-list col-lg-2 col-md-2 col-sm-12 col-xs-12">
										<input value="<?php echo $this->search['advance_search'];?>" style="width: 100%;height: 38px;" placeholder="<?php echo $tr->translate("SEARCH");?> " type="text" id="advance_search" name="advance_search" class="form-control" style="width: 100%;">
									</div>
									<div class="search-list col-lg-2 col-md-2 col-sm-12 col-xs-12">
										<select class="select2" id="branch_id" name="branch_id" onChange="getAllPropertyBranch();">
											 <option value="0"><?php echo $tr->translate("SELECT_BRANCH");?></option>
											<?php if (!empty($this->allbranch)) foreach ($this->allbranch as $br){?>
									        <option value="<?php echo $br['br_id'];?>" <?php if ($this->search['branch_id']==$br['br_id']){ echo 'selected="selected"';}?>><?php echo $br['project_name'];?></option>
									        <?php }?>
									       
									    </select>
									</div>
									<div class="search-list col-lg-2 col-md-2 col-sm-12 col-xs-12">
										<select data-placeholder="<?php echo $tr->translate('SELECT_PROPERTY')?>" class="select2" id="land_id" name="land_id">
									    </select>
									</div>
									<div class="search-list col-lg-2 col-md-2 col-sm-12 col-xs-12">
										<select class="select2" id="pro_type" name="pro_type">
											<option value="0"><?php echo $tr->translate("SELECT_PROPERTY");?></option>
											<?php if ($this->pro_type) foreach ($this->pro_type as $rs){?>
									        <option value="<?php echo $rs['id'];?>" <?php if ($this->search['pro_type']==$rs['id']){ echo 'selected="selected"';}?>><?php echo $rs['name'];?></option>
									        <?php }?>
									    </select>
									</div>
									
									<div class="search-list col-lg-2 col-md-2 col-sm-12 col-xs-12">
										<select class="select2" id="customer" name="customer">
											<option value="0"><?php echo $tr->translate("CHOOSE_CUSTOEMR");?></option>
											<?php if ($this->client) foreach ($this->client as $rs){?>
									        <option value="<?php echo $rs['id'];?>" <?php if ($this->search['customer']==$rs['id']){ echo 'selected="selected"';}?>><?php echo $rs['name'];?></option>
									        <?php }?>
									    </select>
									</div>
									<div class="search-list col-lg-2 col-md-2 col-sm-12 col-xs-12">
										<button name="search" type="submit" class="btn btn-success"><?php echo $tr->translate("SEARCH");?></button>
									</div>
									<div class="clearfix"></div>
								</div>
								<div class="form-control" style="border:none;">
								<div class="pull-right restult-count">
									<span><?php echo $tr->translate("TOTAL_RESULT")?> <strong id="total_result"><?php echo count($this->rs)?></strong> </span><br />
								</div>
							</div>
							</div>
						</div>
					</form>
					<div class="x_content result">
						<?php if (!empty($this->rs)){?>
    								<?php foreach ($this->rs as $key => $sale){?>
    								<div class="property-detail text-center col-lg-3 col-md-3 col-sm-12 col-xs-12">
				          				<div title="<?php echo $sale['house_no']." ".$sale['property_type'];?>" class="contetn-data">
					          				<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
					          					<span><i class="fa fa-map"></i></span>
					          				</div>
					          				<div class="col-lg-9 col-md-9 col-sm-12 col-xs-12">
					          				 <span style="text-align: left;width: 70%;display: inline-block;"><?php echo $sale['property_type']?></span>
					          				 <ul class="nav navbar-right panel_toolbox stusearch" style=" width: 30%; min-width: 20%;    margin-top: -10px;">
						                      <li class="dropdown">
						                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
						                       		 <ul class="dropdown-menu" role="menu">
						                        		 <li>
							                          		<a href="<?php echo $this->baseUrl()."/default/index/detailview/id/".$sale['id'];?>"><i class="fa fa-print"></i> <?php echo $tr->translate('PRINT');?></a>
							                          	</li>
							                         </ul>
							                       </li>
							                  </ul>
		                          
					          				</div>
					          				<div class="clearfix"></div>
					          				<br />
					          				<span class="pro-street"><?php echo $sale['house_no']?></span>
					          				
					          				<span class="pro-price"><?php echo $sale['client_name']?></span>
					          				<span class="pro-project"><a href="javascript:;" target="_blank"><?php echo $sale['branch_name']?></a></span>
				          				</div>
				          			</div>
    								<?php }?>
    					<?php }?>
					</div>
				</div>
	  </div>
      
    </div>
    
 
 	<script>
        $(document).ready(function() { 
         
        	$(".select2").select2();
        	getAllPropertyBranch();
         });

        var oldbranch ='<?php echo $this->search['branch_id'];?>';
        var url_getland ='<?php echo $this->url(array('module'=>'home','controller'=>'index','action'=>'getallland')); ?>';  
        function getAllPropertyBranch(){
        	branch_id = $("#branch_id").val();
        	if(branch_id<=0){
        		$('#land_id').empty().append("");
           		$('#land_id').select2();
          		 return false;
        	}
        	$.ajax({
                url: url_getland,
                type: "post",
                data: {'branch_id':branch_id,'action':1},
                success: function(data){
                	val = $.parseJSON(data);
               	 $('#land_id').empty().append(val);
                	if(branch_id==oldbranch){
                    	<?php if (!empty($this->search['land_id'])){?>
                		$("#land_id").val('<?php echo $this->search['land_id'];?>');
                		<?php }?>
               	 	}
                 $('#land_id').select2();
                
        		},
        		error: function(err) {
        			//alert(err);
        		}
        	});
        } 
    </script>  
  </body>
</html>
