<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_expense;
?>
<title><?php echo $tr->translate('EDITEXPENSE');?></title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
 </script>
 
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
               		branch_id = dijit.byId('branch_id').get('value');
			   		if(branch_id=='' || branch_id==0){
						dijit.byId('branch_id').focus();
						return false;
					}
			   		loadingBlock();
			   		return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDITEXPENSE');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PROJECT_INFO");?> 
	                   </label>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('branch_id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RECEIPT_NO");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('invoice');?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INVOICE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('other_invoice');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('Date');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EXPENSE_TITLE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('title');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CATEGORY");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="income_category" />
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("AMOUNT_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SUPPLIER");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('supplier_id');?>
	                    	</div>
	                    	 <div class="col-md-3 col-sm-3 col-xs-12">
	                   		  	<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getSupplier()"/>
	                   		 </div>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_EXPENSE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('total_amount');?>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_TYPE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('payment_type');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CHEQUE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('cheque');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CHEQUE_ISSUER");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('cheque_issuer');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('Description');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('Stutas');?>
	                   </div>
	                </div>
	            </div>
	        </div>
	        
	        <div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
             		<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button"  iconClass="dijitIconClear"/>
					<input type="submit" label="<?php echo $tr->translate("GO_EDIT");?>" name='saveclose' value='saveclose' dojoType="dijit.form.Button"
					 iconClass="dijitIconDelete"/>
					<input type="button" label="<?php echo $tr->translate("SAVEPRINT")?>" name='print' value=''print'' dojoType="dijit.form.Button"
					 iconClass="dijitIconNewTask" onClick="printSave('');displayNone();" />
    			</div>
    		</div>
    		
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("CHEQUE_ISSUER")?>'"  id="frm_cheque" >
		<form id="form_cheque"​ dojoType="dijit.form.Form" >
			<table style="margin: 0 auto; width: 100%;" cellspacing="7">
				<tr>
					<td>
						<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="addchequename" name="addchequename" value="" type="text">
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button" id="save_cheque" value="Save" label="<?php echo $tr->translate('GO_SAVE');?>" dojoType="dijit.form.Button"
							iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewCheque();"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_category" data-dojo-props="title:'<?php echo $tr->translate("ADD_CATEGORY")?>'" >
		<form style="width:100%;" id='frm_category' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<div class="card-box">
	    		<div class="col-md-12 col-sm-12 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PARENT");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="parent_id" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EXPENSE_TITLE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" required="true"  class="fullside" id="cate_name" name="cate_name" value="" type="text">
	                   </div>
	                </div>
	         	</div>
	         </div>
	         <div class="card-box">
             	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
					<input type="button" value="ចាកចេញ" label="<?php echo $tr->translate("CANCEL");?>" id="close" name="close" dojoType="dijit.form.Button" 
						​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
						<input type="button" value="save" label="<?php echo $tr->translate("GO_SAVE");?>" id="save" name="save" dojoType="dijit.form.Button" 
						 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addCategory();"/>
    			</div>
    		</div>
		</form>
	</div>
</div>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dojo.html");
function displayNone(){
	document.getElementById('divPrint1').style.display="none";
}
var parent_id_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var supplierStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
require(["dojo/ready"], function(ready){
	ready(function(){
		getallCustomer();
		getParentbytype();
	  });
	  
	new dijit.form.FilteringSelect({
		name: "supplier_id",
		id: "supplier_id",
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			Addsupplier()
	    }
	}, "supplier_id");


	new dijit.form.FilteringSelect({
		name: "cheque_issuer",
		id: "cheque_issuer",
		autoComplete: false,
		required: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupIssuer();
	    }
	}, "cheque_issuer");

	new dijit.form.FilteringSelect({
		store: parent_id_store,
		autoComplete: false,
		queryExpr: "*${0}*",
		required: false,		           
		name: "parent_id",
		id: "parent_id",
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
	    }
	}, "parent_id");
});
var chequeStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->cheque_issue));?> );
function addNewCheque(){
	if(dijit.byId('form_cheque').validate()){
		var Itemmake = {					
				id: dijit.byId('addchequename').get('value'),
			    name: dijit.byId('addchequename').get('value')
		};		

		addDataToSelectbox(dijit.byId('cheque_issuer'),chequeStore , Itemmake, dijit.byId('addchequename').get('value'));
		
		//addDataToSelectbox(dijit.byId('cheque_issuer'), StreetStore, Itemmake, dijit.byId('addchequename').get('value'));	
		//dijit.byId('cheque_issuer').attr('value',dijit.byId('addchequename').get('value'));
		dijit.byId('form_cheque').reset();
		dijit.byId('frm_cheque').hide();
		dijit.byId('save_cheque').set('disabled',true);
	}
}
function popupIssuer(){
	cheque_issuer = dijit.byId('cheque_issuer').get('value');
	if(cheque_issuer==-1){
		dijit.byId('save_cheque').set('disabled',false);
		dijit.byId('frm_cheque').show();
	}
}
function enablePayment(){
	payment_method = dijit.byId('payment_type').get('value');
	dijit.byId("cheque").set("readOnly",false);
	dijit.byId("cheque").attr("value",'');
	dijit.byId("cheque_issuer").set("readOnly",false);
	if(payment_method==1){
		dijit.byId("cheque").attr("value",'N/A');
		dijit.byId("cheque").set("readOnly",true);

		dijit.byId("cheque_issuer").set("value",'');
		dijit.byId("cheque_issuer").set("readOnly",true);
	}
}
function Addsupplier(){
	supplier_id = dijit.byId('supplier_id').get('value');
	if(supplier_id==-1){
		window.open('<?php echo $this->baseUrl()."/group/supplier/add?page=popup";?>');
	}
}
var url_supplier = '<?php echo $this->url(array('module'=>'incexp','controller'=>'expense','action'=>'getsupplier')); ?>';
function getSupplier(){
	loadingBlock();
	branch_id = dijit.byId('branch_id').get('value');
	dojo.xhrPost({
		url: url_supplier,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			supplierStore  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('supplier_id').set('store', supplierStore);
		    HideloadingBlock();
		},
		error: function(err) {
		}
	});
}
dojo.ready(function(){
	dijit.byId('income_category').attr('value',<?php echo $this->row['category_id'];?>);
});


var income_category_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->all_category));?> );

new dijit.form.FilteringSelect({
	store: income_category_store,
	autoComplete: false,
	queryExpr: "*${0}*",                 
    id: "income_category",
    name: "income_category",  
    class: 'fullside',  
    placeHolder:"<?php echo $tr->translate('SELECT_CATEGORY');?>", 
    onChange: function() {          
	   	fa_job = dijit.byId('income_category').get('value');
	    if(fa_job==-1){
	   	 dijit.byId("popup_category").show();
	    }
    } 
}, "income_category");


function getallCustomer(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==""){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img class="view" style="height:80px; max-width: 100%;" src="<?php echo $this->baseUrl()."/images/projects/"?>'+arr.logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;
			//document.getElementById('projectlogo1').innerHTML = imagesUrl;
		},
		error: function(e) {
		}
	});
}
function getInvoiceNo(condition){
	
}

function printSave(new_invoice_no){
	dojo.byId("lb_invoice").innerHTML = dijit.byId("invoice").attr('displayedValue');
	//dojo.byId("lb_invoice1").innerHTML = dijit.byId("invoice").attr('displayedValue');
	supplier_id = dijit.byId("supplier_id").attr("value");
	supplier_lable="";
	if(supplier_id>0){
		supplier_lable = dijit.byId("supplier_id").attr('displayedValue');
	}
	dojo.byId("lb_supplier").innerHTML = supplier_lable;
	//dojo.byId("lb_supplier1").innerHTML = supplier_lable;
	dojo.byId("lb_branch").innerHTML = dijit.byId("branch_id").attr('displayedValue');
	dojo.byId("lb_income_category").innerHTML = dijit.byId("income_category").attr('displayedValue');
	dojo.byId("lb_income_title").innerHTML = dijit.byId("title").get('value');
	dojo.byId("lb_total_amount").innerHTML =currencyFormat(dijit.byId("total_amount").get('value'));
	dojo.byId("lb_date").innerHTML = dijit.byId("Date").attr('displayedValue');
	dojo.byId("lb_description").innerHTML = dijit.byId("Description").attr('displayedValue');
	dojo.byId("lb_cheque").innerHTML = dijit.byId("cheque").attr('displayedValue');

	//dojo.byId("lb_branch1").innerHTML = dijit.byId("branch_id").attr('displayedValue');
	//dojo.byId("lb_income_category1").innerHTML = dijit.byId("income_category").attr('displayedValue');
	//dojo.byId("lb_income_title1").innerHTML = dijit.byId("title").get('value');
	//dojo.byId("lb_total_amount1").innerHTML = currencyFormat(dijit.byId("total_amount").get('value'));
	//dojo.byId("lb_date1").innerHTML = dijit.byId("Date").attr('displayedValue');
	//dojo.byId("lb_description1").innerHTML = dijit.byId("Description").attr('displayedValue');
	//dojo.byId("lb_cheque1").innerHTML = dijit.byId("cheque").attr('displayedValue');
	dijit.byId("print_expense").show();
}

function currencyFormat(num) {
    return "$ " + num.toFixed(2).replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,")
}

function doPrint() {
	dojo.byId("printblog2").innerHTML = dojo.byId('divPrint').innerHTML;
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML <?php if($this->data['showreceipt']>1){ ?>+ dojo.byId('divPrint1').innerHTML<?php }?>;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    loadingBlock();
    printSubmit();
    hideDialog();
}
function printSubmit(){
	 $('#frm_add_tran').submit();
}
var url_add_category = '<?php echo $this->url(array("module"=>"incexp","controller"=>"expense","action"=>"add-category")); ?>';
function addCategory(){
	if(dijit.byId('frm_category').validate()){
		dijit.byId('save').set('disabled',true);
		dojo.xhrPost({
			url:url_add_category,
			form: dojo.byId("frm_category"),
			handleAs:"json",
			load: function(data) {
				//var Itemmake = { 
		    		//id: data,
			       // name: dijit.byId('cate_name').get('value')
			   // };
		 		//addDataToSelectbox(dijit.byId('income_category'), income_category_store, Itemmake, data);

		 		resetStoreCategory(data);
		 		
			    dijit.byId('frm_category').reset();
			    dijit.byId("popup_category").hide();
			    dijit.byId('save').set('disabled',false);
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
var url_getland = '<?php echo $this->url(array('module'=>'incexp','controller'=>'income','action'=>'getparentbyid')); ?>';
function getParentbytype(){
	account_type = 13
	dijit.byId('parent_id').reset();
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'type':account_type
		},		    
		handleAs:"json",
		load: function(data) {
			acc_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('parent_id').set('store', acc_store);
		},
		error: function(err) {
		}
	});
}
var url_getland = '<?php echo $this->url(array('module'=>'incexp','controller'=>'income','action'=>'getparentbyid')); ?>';
function resetStoreCategory(keyValue){
	account_type = 13
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'type':account_type,'with_add_new':1
		},		    
		handleAs:"json",
		load: function(data) {
			income_category_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('income_category').set('store', income_category_store);
		    dijit.byId('income_category').set('value', keyValue);
		},
		error: function(err) {
		}
	});
}
</script>


<div class="dijitHidden" style="width: 23cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:22cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="print_expense" >
		<div id="divPrint" style="width: 100% !important; height: 13cm ; padding: 0px; margin: 0px;">
			<style>
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:16px 'Khmer OS Battambang';border: 1px solid #000; height: 30px; width: 100%;margin-right:5px; display: block;
						line-height: 28px;
					    text-align: center;
						}
				.print tr td{
					padding:2px 2px; 
				}
				
				.khmerbold{font:16px 'Khmer OS Battambang';}
			   .khmer{font:14px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;}
			   .noted{
					white-space: pre-wrap;     
					word-wrap: break-word;      
					word-break: break-all;
					white-space: pre;
					font:12px 'Khmer OS Battambang';
					border: 1px solid #000;
                    line-height:20px;font-weight: normal !important;
                }
				label{margin-bottom: 0px !important}
			</style>	
			<table width="100%" style="white-space: nowrap;font-size:16px;margin-top: 10px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer OS Muol Light';white-space:nowrap;">
							<tr>
								<td id="projectlogo" width="25%">
									<img style="height:75px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font: 18px 'Khmer OS Muol Light';" valign="top" align="center"><u><span style=" font-family: Arial Black,'Khmer OS Muol Light';">បង្កាន់ដៃចំណាយ</span></u>
									<div style="line-height:10px;"><strong style="font-size: 18px;font-weight:bold">PAYMENT VOUCHER</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table  width="100%" style="white-space: nowrap;font-size:14px;margin-top:-5px;" class="print" cellspacing="3px"  cellpadding="0">
				<tr style="white-space: nowrap;">
					<td width="15%" class="one khmerbold">គម្រោង</td>
                    <td width="35%" ><strong><label id="lb_branch" class="value"></label></strong></td>
				    <td width="15%" class="one khmerbold">&nbsp;&nbsp;&nbsp;វិក័យប័ត្រលេខ</td>
                    <td width="35%" ><strong><label id="lb_invoice" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">អ្នកផ្គត់ផ្គង់</td>
                    <td ><strong><label id="lb_supplier" class="value"></label></strong></td>
                    <td class="one khmerbold">&nbsp;&nbsp;&nbsp;ថ្ងៃចំណាយ</td>
				    <td ><strong><label id="lb_date" class="value"></label></strong></td>
				</tr>
				<tr>
					<td class="one khmerbold">ប្រភេទចំណាយ</td>
					<td ><strong><label id="lb_income_category" class="value"></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;សែក</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_cheque" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">ពណ៌នាចំនាយ</td>
				    <td><strong><label id="lb_income_title" class="value"></label></strong></td>
				    <td class="one khmerbold" rowspan="2">&nbsp;&nbsp;&nbsp;សម្គាល់</td>
				    <td colspan="1" align="left" rowspan="2" style="border: 1px solid #000 !important;" class="noted"><label style="text-align: left; " id="lb_description" ></label></td>
				</tr>
				<tr>
					<td class="one khmerbold">ចំណាយសរុប</td>
					<td><strong><label id="lb_total_amount" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td class="khmerbold" style="line-height: 14px;"colspan="2"  align="center" >&nbsp;&nbsp;<span style=" font-family: Arial Black;font-family:'Khmer OS Muol Light';">
				    	<?php echo $this->data['customer_sign'];?></span></td>
				    <td colspan="2" class="khmerbold" style="line-height: 14px;" align="center" ><span style=" font-family: Arial Black;font-family:'Khmer OS Muol Light';">
				    	<?php echo $this->data['teller_sign'];?></span></td>
				</tr>
				<tr style="white-space: nowrap;" height="100px;">
					<td class="one khmerbold" colspan="2" align="center" valign="bottom">
					</td>
				    <td class="one khmerbold" colspan="2" align="center" valign="bottom">&nbsp;
				  		<h4  style="font-weight:normal; padding-right: 5px ! important;margin-bottom: -10px  !important;">
			              <?php 
			              $session_user=new Zend_Session_Namespace(SYSTEM_SES);
					      $last_name=$session_user->last_name;
					      $username = $session_user->first_name;
					      ?>
					    </h4>  
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="4" valign="top" >
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="4" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
					</td>
				</tr>
				<tr style="line-height: 20px;font-size: 10px;">
					<td colspan="6" >
						<?php echo $this->footer;?>
					</td>
				</tr>
			</table>
		</div>
		<table>
			<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
			<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
				type="button" onclick="doPrint();">បោះពុម្ភ/Print</button>
		</table>
		<div id="divPrint1" style="width: 21cm !important; height: 12cm ; padding: 0px; margin: 0px;">
			<?php if($this->data['showreceipt']>1){?>
				<div style="border:2px dashed #000; vertical-align: middle;margin:20px 0px 40px 0px"></div>
			<?php }?>
			<div id="printblog2"></div>
		</div>
	</div>
</div>
