<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("STAFF"));
$frm = $this->frm_co;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'co','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			   <table width="100%" >
			   	<tr>
				   <td><?php echo $frm->getElement("adv_search");?></td>
				   <td><?php echo $frm->getElement("branch_id");?></td>
				   <td><?php echo $frm->getElement('status_search');?></td>
				   <td><?php echo $frm->getElement("btn_search");?></td>
				</tr>
			   </table>
			    <?php echo $this->list;?>
			</form>
		</div>
		<div class="card-box">
		</div>
	</div>
</div>
