<?php	
	$frm = $this->frm;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<title><?php echo $tr->translate("RENT_REFUND");?></title>
<style>
.fullside50{ width:48%;}
.agreement{
	border: 1px solid #92b0ea;
    background: #cbdcff;
    font-weight: bold;
    text-align: center;}
   textarea{font-size:10px;}
.not-display {
    display: none !important;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
           			 branch_id = dijit.byId('branch_id').get('value');
           			 if (branch_id=='' || branch_id==-1){
						infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>!');
						dijit.byId('branch_id').focus();
						return false;
					}
					rent_id = dijit.byId('rent_id').get('value');
					if (rent_id=='' || rent_id==-1){
						infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_RENT");?>!');
						dijit.byId('rent_id').focus();
						return false;
					}
					total_amount = dijit.byId('total_amount').get('value');
					if (total_amount<=0){
						infoMessageAlert('<?php echo $tr->translate("TOTAL_AMOUNT_MUST_BE_BIGER_THAN_ZERO");?>!');
						dijit.byId('total_amount').focus();
						return false;
					}
              		loadingBlock();
			  	 return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RENT_REFUND');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
		    <div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("RENT_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?>  :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branch_id');?>
											<?php echo $frm->getElement('customer_id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("RENT_NO");?>  :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="rent_id" />
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("REFUND_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("REFUND_DATE");?>  :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('refund_date');?>
									   </div>
									</div>
								   <div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PAYMENT_TYPE");?>  :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('payment_method');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NUMBER");?>  :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('cheque');?>
									   </div>
									</div>
								   <div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CHEQUE_ISSUER");?>:
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('cheque_issuer');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("REFUND_AMOUNT");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('total_amount');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('note');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
	            </div>
	        </div>
	        <div class="clearfix"></div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="reset" class="button-class button-danger" iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" label="<?php echo $tr->translate("SAVE_CLOSE")?>" id='saveclose' value='saveclose' dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("SAVENEW")?>" id='savenew' value='savenew' dojoType="dijit.form.Button" />
				</div>
			</div>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("CHEQUE_ISSUER")?>'"  id="frm_cheque" >
		<form id="form_cheque"​ dojoType="dijit.form.Form" >
			<table style="margin: 0 auto; width: 100%;" cellspacing="7">
				<tr>
					<td>
						<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="addchequename" name="addchequename" value="" type="text">
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button" id="save_cheque" value="Save" label="<?php echo $tr->translate('GO_SAVE');?>" dojoType="dijit.form.Button"
							iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewCheque();"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
<script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
</script>
<script type="text/javascript">	
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");
dojo.require("dojo.html");
var rent_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

require(["dojo/ready"], function(ready){
	 ready(function(){
		 //getAllRentNumber();
		 enablePayment();
	  });
	new dijit.form.FilteringSelect({
			store: rent_store,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,		           
			name: "rent_id",
			id: "rent_id",
			searchAttr: "name",
			class: 'fullside',
			required:true,
			onChange: function() {
				rent_id = dijit.byId('rent_id').get('value');
				if(rent_id==-1 || rent_id ==""){
				}else{
					getRentInfo();
				}
		}
	}, "rent_id");
	new dijit.form.FilteringSelect({
		name: "cheque_issuer",
		id: "cheque_issuer",
		autoComplete: false,
		required: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupIssuer();
	    }
	}, "cheque_issuer");
});
function enablePayment(){
	payment_method = dijit.byId('payment_method').get('value');
	dijit.byId("cheque").set("readOnly",false);
	dijit.byId("cheque").attr("value",'');
	dijit.byId("cheque_issuer").set("readOnly",false);
	if(payment_method==1){
		dijit.byId("cheque").attr("value",'N/A');
		dijit.byId("cheque").set("readOnly",true);
		dijit.byId('cheque_issuer').reset();
		dijit.byId("cheque_issuer").set("readOnly",true);
	}
}
function popupIssuer(){
	cheque_issuer = dijit.byId('cheque_issuer').get('value');
	if(cheque_issuer==-1){
		dijit.byId('save_cheque').set('disabled',false);
		dijit.byId('frm_cheque').show();
	}
}
var chequeStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->cheque_issue));?> );
function addNewCheque(){
	if(dijit.byId('form_cheque').validate()){
		var Itemmake = {					
			id: dijit.byId('addchequename').get('value'),
		    name: dijit.byId('addchequename').get('value')
		};		
		addDataToSelectbox(dijit.byId('cheque_issuer'),chequeStore , Itemmake, dijit.byId('addchequename').get('value'));
		dijit.byId('form_cheque').reset();
		dijit.byId('frm_cheque').hide();
		dijit.byId('save_cheque').set('disabled',true);
	}
}
var url_getsalenumber = "<?php echo $this->url(array('module'=>'rent','controller'=>'payment','action'=>'get-sale-number')); ?>";
function getAllRentNumber(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('rent_id').reset();
	if(branch_id== 0 || branch_id==-1){
		var rent_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
		rent_store  = getDataStorefromJSON('id','name', data);
	    dijit.byId('rent_id').set('store',rent_store); 
		return false;
	}
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':branch_id,'is_completed':1
		},		    
		handleAs:"json",
		load: function(data) {
			rent_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('rent_id').set('store',rent_store); 
		},
		error:  function(response, ioArgs) {
		}
	});
}
var url_rentinfo = "<?php echo $this->url(array('module'=>'rent','controller'=>'deposit','action'=>'getrentinfo')); ?>";
function getRentInfo(){
	rent_id = dijit.byId('rent_id').get('value');
	if(branch_id== 0 || branch_id==-1){
		return false;
	}
	dojo.xhrPost({
		url: url_rentinfo,	
		content:{ 
		    'rent_id':rent_id
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('total_amount').attr('value',data.depositRent);
			dijit.byId('customer_id').attr('value',data.client_id);
		},
		error:  function(response, ioArgs) {
		}
	});
}

</script>