<?php	
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$install_month = $this->data['install_by'];
	$autocalcualte = $this->data['autocalcualte_period'];
?>
<title><?php echo $tr->translate("SALE_PROPERTY");?></title>
<style>
.fullside50{ width:48%;}
.agreement{
	border: 1px solid #92b0ea;
    background: #cbdcff;
    font-weight: bold;
    text-align: center;}
.blog-left-content {
    min-height: 250px;
    border: 1px solid #eee;
    margin: 0 !important;
    padding: 10px !important;
    background: #f9f7f7;
}
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
	<script src="<?php echo $baseurl;?>/js/help.js"></script>
	<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
   </script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
		  			schedule_opt = dijit.byId('schedule_opt').get('value');
		 			 for_installamount= dijit.byId('for_installamount').get('value');
         			var rowId = $('#identity').val();
          
					schedule_opt = dijit.byId("schedule_opt").get("value");
					remain_balance = dijit.byId("remain_balance").get("value");
					if(schedule_opt==6 || schedule_opt==5){ 
						identity = $("#identity").val(); 
						if(identity==''){ 
							alert("សូមបញ្ចូលប្រាក់ដែលអតិថិជននឹងត្រូវបង់!");
							addRow(); return false;
						}
						if(remain_balance!=0){
							alert("ការរៀបចំតារាងត្រូវបង់មិនទាន់គ្រប់ចំនួនទេ។សូមត្រួតពិនិត្យម្តងទៀត !");	
							return false;
						}
					}
					if(for_installamount>0 && schedule_opt==6 ){
						alert("សូមបញ្ចូលប្រាក់ដែលត្រូវបង់ក្នុងតារាងខាងក្រោម អោយគ្រប់ចំនួន នៃតម្លៃ ដី/ផ្ទះ!");
						document.getElementById('table_row').style.background='#ff8a8a';
						return false;
					}
           			branch_id = dijit.byId('branch_id').get('value');
            		if (branch_id=='' || branch_id==-1){
						alert('Please Select Branch!');
						dijit.byId('branch_id').focus();
						return false;
					}
					client = dijit.byId('member').get('value');
					if (client=='' || client==-1){
						alert('Please Select Client Name !');
						dijit.byId('member').focus();
						return false;
					}
					rs = checkValidateDate();
					if(rs==false){
           			   return false;			
          			  }
          		  payment_id =dijit.byId("schedule_opt").get("value");
         		   paid_amount =dijit.byId("deposit").get("value");
					if(schedule_opt==2){//បង់ផ្តាច់
						  sold_price = dijit.byId("sold_price").get("value");
  				 		 deposit = dijit.byId("deposit").get("value");
				 		 if(sold_price!=deposit){
							alert("បង់ផ្តាច់ តម្លៃលក់ ត្រូវស្មើរ នឹងប្រាក់ដែលត្រូវទទួល!");
							dijit.byId("deposit").focus();
							return false;
						  }
					}

					dijit.byId('saveclose').set('disabled',true);	
					dijit.byId('savenew').set('disabled',true);
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SALE_PROPERTY');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("INFO_INDILOAN");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('branch_id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SALE_NO");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('sale_code');?>
	                   </div>
	                </div>
	                
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="member" /><input dojoType="dijit.form.TextBox" class="fullside" id="joint_with" name="joint_with"  type="hidden"><!-- ពេលបោះពុម្ពចេញអ្នកទិញជាមួយ -->
							<input type="hidden" name="identity_land" id="identity_land"  value="" >
							<input type="hidden" name="land_label" id="land_label" dojoType="dijit.form.TextBox" value="" >
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CLIENT_NUM");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		 <div class="col-md-7 col-sm-7 col-xs-12">
	                   		 	<input id="customer_code" /><input type="hidden" name="identity" id="identity"  value="" >
	                   		 </div>
	                   		  <div class="col-md-3 col-sm-3 col-xs-12">
	                   		  	<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="filterClient();"/>
	                   		 </div>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-map-marker" aria-hidden="true"></i> <?php echo $tr->translate("PROPERTY_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROPERTY_TYPE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('property_type');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROPERTY_CODE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		 <div class="col-md-6 col-sm-6 col-xs-12">
	                   		 	<?php echo $frm->getElement('typesale');?>
	                   		 </div>
	                   		  <div class="col-md-6 col-sm-6 col-xs-12">
	                   		  	<input id="land_code" /><input dojoType="dijit.form.TextBox"  id="propertype" name="propertype" type="hidden">
	                   		 </div>
	                   </div>
	                 </div>
                   <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PRICE_BEFORE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('total_sold');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Discount");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('discount_percent');?><?php echo $frm->getElement('discount');?>
	                   </div>
	                </div>
	                <!-- 
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php //echo $tr->translate("OTHER_FEE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php //echo $frm->getElement('other_fee');?>
	                   </div>
	                </div> -->
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SOLD_PRICE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('sold_price');?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12" style="background:#fff;border:1px solid #aac4e6;font-size: 13px;color:#284db7;padding:2px;clear: both;height: auto;min-height: 60px;">
	                    	<label id="land_information" style="max-width:100%;"></label>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("INSTALLMENT_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_TYPE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<div class="col-md-6 col-sm-6 col-xs-12">
	                    	<?php echo $frm->getElement('schedule_opt');?>
	                    	</div>
	                    	<div class="col-md-6 col-sm-6 col-xs-12">
	                    		<select class="fullside" dojoType="dijit.form.FilteringSelect" name="install_type" id="install_type">
									<option value="1"><?php echo $tr->translate("FIXED_PAYMENT");?></option>
									<option value="2"><?php echo $tr->translate("DECLINE");?></option>
								</select>
	                    	</div>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_FORINTALLMENT");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input readonly type="text" class="fullside" dojoType="dijit.form.TextBox" name="for_installamount" id="for_installamount"  value="" >
								<input type="hidden" class="fullside" dojoType="dijit.form.TextBox" name="total_installamount" id="total_installamount"  value="" >
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name">
	                   <lable id='lbl_period'><?php echo $tr->translate("TERM_BORROW");?></lable><lable id='lbl_year'><?php echo $tr->translate("YEAR");?></lable> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('period');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_FORINTALLMENT");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input style="color:red" readonly="readonly" type="text" class="fullside" dojoType="dijit.form.NumberTextBox" name="remain_balance" id="remain_balance"  value="" >
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_RATE");?>/<?php echo $tr->translate("YEAR");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('interest_rate');?>
	                   </div>
	                </div>
						
	                <div class="form-group">
	                   <label id="lbl_payment" class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('fixed_payment');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label id="lbl_release" class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LOAN_RELEASE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('release_date');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FIRST_PAYMENT");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('first_payment');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label id="lbl_dateline" class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LIFE_LOAN");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('date_line');?>
	                   </div>
	                </div>
	                  <div class="form-group">
	                   <label id="lbl_dateline" class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name">
	                   		<?php echo $tr->translate("paid_receivehouse");?> :
	                   </label>
	                   <div class="col-md-4 col-sm-4 col-xs-12">
	                   		<?php echo $frm->getElement('paid_receivehouse');?>
	                   </div>
	                   <div class="col-md-3 col-sm-3 col-xs-12">
	                   		<?php echo $frm->getElement('delay_day');?>
	                   </div>
	                </div>
	             </div>
	             
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-user" aria-hidden="true"></i> <?php echo $tr->translate("SALE_AGENT_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CO_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="staff_id" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMISSION_EXPECTED");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('full_commission');?>
	                   </div>
	                </div>
	                <!-- <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php //echo $tr->translate("COMISSION");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php //echo $frm->getElement('commission');?>
	                   </div>
	                </div> -->
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate("AGREEMENT");?> 
	                   </label>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE_BUY");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('date_buy');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("AGREEMENT_DATE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('agreement_date');?>
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BUILD_PERIOD");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('amount_build');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BUILD_START");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('start_building');?>
	                   </div>
	                </div>
	            </div>
	           	
	        </div>
	        <div class="card-box">
	    		
	             <div class="col-md-8 col-sm-8 col-xs-12">
					<div class="form-group blog-left-title">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold m-0" for="first-name"><i class="fa fa-calendar" aria-hidden="true"></i> <?php echo $tr->translate("SCHEDULE_INSTALLMENT");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                	 <div class="col-md-12 col-sm-12 col-xs-12 blog-left-content">
	                	 	<div  id="showrecord"></div>
							<input type="button" label="<?php echo $tr->translate('ADD_INSTALLMENT');?>" dojoType="dijit.form.Button" 
					 		iconClass="dijitIconEditProperty" onclick="addRow();" />
	                	 </div>
	                </div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-money" aria-hidden="true"></i> <?php echo $tr->translate("PAYMENT_INFORMATION");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DAY_PAYMENT");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input constraints="{datePattern:'dd/MM/yyyy'}" type="text" class="fullside" dojoType="dijit.form.DateTextBox" name="paid_date" id="paid_date"  value="<?php echo date("Y-m-d");?>" >
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_RECEIPT");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('receipt');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Paid");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('deposit');?>
	                    	<input dojoType="dijit.form.TextBox" class="fullside" id="total_interest" name="total_interest" value="0" type="hidden">	
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Balance");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('balance');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('note');?>
	                   </div>
	                </div>
	            </div>
	         </div>
	         <div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" label="<?php echo $tr->translate("CLEAR");?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
					<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" id='saveclose' name='saveclose' value='saveclose' dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
					<input type="submit" label="<?php echo $tr->translate("SAVENEW");?>" id='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
					<input type="button" onclick="addPreviewLoan();displayNone();" label="<?php echo $tr->translate("PREVIEW");?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
	
    			</div>
    		</div>
		</form>
	</div>
</div>

<div class="dijitHidden">
	<style>
	.print tr td{
		padding:5px 2px; 
	}
	</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់'" id="lbl_schedule" style="width: 25cm !important;">
		<div id="rpt_print" class="print" style="text-align: center;">
			<input style="text-align: center;" type="button" onclick="printSave('','');" label="<?php echo $tr->translate("បោះពុម្ភបង្កាន់ដៃ");?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
			<div id="t_amountmoneytype" name="t_amountmoneytype">
			</div>
		</div>
	</div>
</div>
<div class="dijitHidden" style="width:24cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:23cm !important;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="terms" >
		<div id="divPrint" style="height: 13cm ; padding: 0px; margin: 0px;font-family:'Khmer OS Battambang';">
			<style>
				.label{ font-size: 22px;}
				.value{ font:14px 'Khmer OS Battambang';border: 1px solid #000; height: 26px; padding: 0 2px;width: 100%;margin-right:5px; display: block;
						line-height: 25px;
					    text-align: center;
				}
				.print tr td{
					padding:1px 2px; 
				}
			   .khmer{font:14px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;}
			   .noted{
				    white-space: pre-wrap;     
					word-wrap: break-word;      
					word-break: break-all;
					white-space: pre;
					font:12px 'Khmer OS Battambang';
					border: 1px solid #000;
                    line-height:20px;font-weight: normal !important;
				}
				label{margin-bottom: 0px !important}
			</style>	
			<table width="100%" style="backgroud:red;white-space: nowrap;font-size:14px; padding:0px;margin-top: -15px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td id="projectlogo" width="35%">
									<img style="height:75px; max-width: 100%;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>			
								<td width="30%" style="font:16px 'Kh Muol';" valign="top" align="center"><u><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃទទួលប្រាក់</strong></u>
									<div style="line-height:10px;"><strong style="font-size: 16px;">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="35%"></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table style="backgroud:red;width:100%;white-space: nowrap;font-size:14px;padding:-10px 10px 0px 5px; margin-top: -38px;font-family: 'Khmer OS Battambang';" class="print" cellspacing="0px"  cellpadding="0" >
				<tr style="white-space: nowrap;font-size: 14px;margin-top: -15px;" >
				    <td colspan="5"></td>
					<td align="right"><strong>
						<div style=" display: none;"><?php echo $this->rs['project_name'];?></div>
						<label id="lb_receipt" ></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td style="display: none;">លេខកូដលក់</td>
				    <td style="display: none;"><strong><label class="value"><?php echo $this->rs['sale_number'];?></label></strong></td>
				    <td>គម្រោង</td>
				    <td><strong><strong><label id="lbl_project" class="value">3</label></strong></td>
					<td>&nbsp;&nbsp;ប្រាក់ដើមត្រូវបង់</td>
                    <td><strong><label id="lb_amount" class="value"></label></strong></td>
					<td>&nbsp;បង់លើកទី</td>
					<td><strong><label id="lbl_paidtimes" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td>ឈ្មោះ​អតិថិជន </td>
				    <td><strong><label id="lb_customer" class="value"></label></strong></td>
					<td>&nbsp;&nbsp; ប្រាក់ការ</td>
                    <td><strong><label id="lb_interest" class="value">0.00</label></strong></td>
					<td>&nbsp; ប្រាក់ពិន័យ</td>
					<td><strong><label id="lb_penalty" class="value">0.00</label></strong></td>
                </tr>
				<tr style="white-space: nowrap;">
					<td><?php echo $tr->translate("PROPERTY_CODE");?></td>
                    <td><strong><label id="lb_hourseno" class="value"></label></strong></td>
				   <td>&nbsp;&nbsp;ប្រាក់បង់បន្ថែម</td>
					<td colspan="3"><strong><label id="lb_extrapayment" class="value">0.00</label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td width="10%"><?php echo $tr->translate("HOUSE_PRICE");?></td>
				    <td width="40%"><strong><label id="lb_saleprice" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;ប្រាក់ត្រូវបង់</td>
                    <td colspan="3"><strong><label id="lbl_totalpayment" class="value"></label></strong></td>
				</tr>
				<tr>
					<td>ប្រាក់បានបង់សរុប</td>
					<td valign="top">
						<table width="100%" cellpadding="0" cellspacing="0">
							<tr>
								<td width="33.5%" style="white-space: nowrap;"><label style="margin-left: -4px;" id="lbl_total_paid1" class="value"></label></td>
								<td width="33%" style="white-space: nowrap;">ប្រាក់នៅសល់</td>
								<td width="33.5%"><label style="white-space: nowrap;margin-right: -4px;" class="value" id="lbl_balance"></label></td>
							</tr>
						</table>
					</td>
					<td>&nbsp;&nbsp;ប្រាក់ទទួលបាន</td>
				    <td colspan="3"><strong><label  class="value" style="font-weight:700; font-family: Arial,Helvetica,sans-serif;" id="lbl_total_receive"></label></strong></td>
				</tr>
				<tr style="">
					<td rowspan="2">សម្គាល់</td>
				    <td rowspan="2" class="noted" valign="top"><label id="lb_noted"></label></td>
					<td>&nbsp;&nbsp;ថ្ងៃត្រូវបង់</td>
				    <td><strong><label id="lb_buydate1" class="value"></label></strong></td>
					<td>&nbsp;ថ្ងៃទទួល</td>
					<td><strong><label id="lbl_paid_date1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td>&nbsp;បង់ជា</td>
					<td><strong><label id="lbl_paymenttype" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;លេខ</td>
					<td><strong><label id="lb_cheque1" class="value">N/A</label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td colspan="6" valign="top">
						<table width="100%" border="0" style="font-size:14px;line-height: 18px;">
							<tr>
								<td width="30%">&nbsp;
									<?php echo $this->data['account_sign'];?>
								</td>
								<td align="center" width="40%">
									<?php echo $this->data['customer_sign'];?>
								</td>
								<td align="center" width="30%">
									<?php echo $this->data['teller_sign'];?>
								</td>
							</tr>
							<tr height="75px">
								<td colspan="3">&nbsp;
								</td>
							</tr>
							<tr>
								<td width="30%">&nbsp;</td>
								<td align="center" width="40%">
									<label id="lbl_customer" ></label>
								</td>
								<td align="center" width="30%">
								<?php 
								   $session_user=new Zend_Session_Namespace('authinstall');
								   $last_name=$session_user->last_name;
								   $username = $session_user->first_name;
								   echo $last_name." ".$username;
								?>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr style="font-size: 11px;">
						<td colspan="6" valign="top">
							<table width="100%" border="0" style="margin-top:-5px">
								<tr>
									<td width="10%"><span style="text-decoration:underline;font-size: 12px; margin-top: -5px;">សម្គាល់ ៖</span></td>
									<td colspan="5">
										<p style="font-size: 11px;margin:-5px 0px -5px 0px !important;padding:0 !important; margin"><?php echo $this->data['comment'];?></p>
										<span style="white-space: pre-line;font-size: 11px;margin-top: -5px;"><?php echo $this->data['comment1'];?></span>
									</td>
								</tr>
							</table>
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)"></td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" >
						<?php echo $this->footer;?>
					</td>
				</tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
			type="button" onclick="doPrint();">បោះពុម្ភ/Print</button>
		<div id="divPrint1" style="width: 21cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<?php if($this->data['showreceipt']>1){?>
				<div style="border:2px dashed <?php echo $this->data['border_receiptcolor'];?>; vertical-align: middle;margin:20px 0px 40px 0px"></div>
			<?php }?>
			<div id="printblog2"></div>
		</div>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("INTEREST_RATE")?>'"  id="frm_interest" >
		<form id="form_interestrate" dojoType="dijit.form.Form">
			<table style="margin: 0 auto; width: 100%;" cellspacing="7">
				<tr>
					<td>
						<input dojoType="dijit.form.NumberTextBox" required="true" class="fullside" id="interest_ratenew" name="interest_ratenew" value="" type="text">
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button" value="Save" label="<?php echo $tr->translate('GO_SAVE');?>" dojoType="dijit.form.Button"
							iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addinterest();"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script type="text/javascript">	
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");
var interestStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rs_interest));?> );
function addinterest(){
	if(dijit.byId('form_interestrate').validate()){
		var Itemmake = {					
				id: dijit.byId('interest_ratenew').get('value'),
			    name: dijit.byId('interest_ratenew').get('value')
		};		
		addDataToSelectbox(dijit.byId('interest_rate'), interestStore, Itemmake, dijit.byId('interest_ratenew').get('value'));	
		dijit.byId('interest_rate').attr('value',dijit.byId('interest_ratenew').get('value'));
		dijit.byId('frm_interest').reset();
		dijit.byId('frm_interest').hide();
	}
}						           
var staff_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->co_name));?> );
new dijit.form.FilteringSelect({
	store: staff_store,
	autoComplete: false,
	queryExpr: "*${0}*",                       
    id: "staff_id",
    name: "staff_id",  
    class: 'fullside',  
    required:false,
    placeHolder:"Selected Agent", 
    onChange: function() {        
    	branch_id = dijit.byId('branch_id').get('value');
    	staff_id = dijit.byId('staff_id').get('value');
    	if(branch_id==0){
    		if(staff_id==-1){
    			alert('Please select branch');
    			dijit.byId('branch_id').focus();
    			return false;
        	}
    	}else{
		    if(staff_id==-1){
		    	dijit.byId('branch_id_pop').attr('value',branch_id);
		   		dijit.byId("popup_staff").show();
		    }
    	}
    } 
}, "staff_id");
function displayNone(){
	document.getElementById('divPrint1').style.display="none";
}
function resetSale(){
	dijit.byId('land_label').attr("value",'');
	$('#identity_land').val('');
	dojo.byId('land_information').innerHTML ="";
	dijit.byId('total_sold').attr("value",0);
	dijit.byId('sold_price').attr("value",0);
	land_id = dijit.byId("land_code").get("value");
	if(land_id!='' && land_id>0){
		getlandinfo();
	}
}
function checkScheduleOption(){
    interest_rate = dijit.byId("interest_rate").get("value");
  	if(interest_rate==-1){
  		dijit.byId('frm_interest').show();
  		return false;
	}
	dijit.byId("install_type").set("readOnly",true);
	dijit.byId('first_payment').set("readOnly",false);
	dijit.byId('period').set("readOnly",false);
	dijit.byId('interest_rate').set("readOnly",false);
	dijit.byId('release_date').set("readOnly",false);
	dijit.byId('date_line').set("readOnly",true);
	dijit.byId('paid_receivehouse').set("readOnly",false);
	
	method_id = dijit.byId('schedule_opt').get('value');
	amount_principal = dijit.byId('balance').get('value');	
	debt_amount = dijit.byId('period').get('value')*<?php echo $install_month;?>;
	dojo.byId('lbl_dateline').innerHTML="<?php echo $tr->translate("LIFE_LOAN");?>";
	
	if(method_id==3 || method_id==6){
		debt_amount = dijit.byId('period').get('value');
	}
	dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TERM_BORROW");?>";
	dojo.byId('lbl_year').innerHTML="<?php echo ($install_month==12)?$tr->translate("YEAR"):$tr->translate("MONTH");?>";

	dojo.query("#table_row").append('');
	dijit.byId("total_installamount").attr("value",0);
	$('#identity').val('');
	dojo.query("#showrecord").append('');
	title=0;
	no=0;
	
	if(method_id==4){
		dijit.byId("install_type").set("readOnly",false);
		calCulateFixedPeriod();	
		}else {
			dijit.byId('fixed_payment').attr('value',0);
			dijit.byId('fixed_payment').set("readOnly",true);
		if(method_id==1){//booking
			dijit.byId('paid_receivehouse').set("readOnly",true);
			dojo.byId('lbl_dateline').innerHTML="<?php echo $tr->translate("DATE_MAKE_AGREEEMNT");?>";
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('date_line').set("readOnly",false);
			dijit.byId('period').set("readOnly",true);
			dijit.byId('period').attr("value",0);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('interest_rate').set("readOnly",true);
		}else if(method_id==2){//payoff
			dijit.byId('paid_receivehouse').set("readOnly",true);
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('period').set("readOnly",true);
			amount_principal = dijit.byId("sold_price").get("value");
			dijit.byId('deposit').attr("value",amount_principal);
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			dijit.byId('date_line').attr("value",'<?php echo date("Y-m-d");?>');
		}else if(method_id==3){//times
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT");?>";
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE");?>";
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH");?>';
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			amount_principal=dijit.byId('sold_price').get('value');
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(0);
			if(debt_amount!=0){
				dijit.byId('fixed_payment').attr("value",total_collect);
			}
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('remain_balance').attr("value",0);
		}else if(method_id==5){//times
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH");?>';
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			if(dijit.byId('interest_rate').get('value')==0 ){
				dijit.byId('interest_rate').attr("value",0);
			}
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('period').set("readOnly",false);
		}
		else if(method_id==6){//times			
			if(dijit.byId('period').get('value')==12){
				//dijit.byId('period').attr('value',0);
			}
			$('#identity').val('');
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT");?>";
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH");?>';
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE");?>";
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(2);
			if(isNaN(total_collect)){
				total_collect=0;
			}
			dijit.byId('fixed_payment').attr("value",total_collect);
			if(dijit.byId('interest_rate').get('value')==0){
			dijit.byId('interest_rate').attr("value",0);}
			dijit.byId('interest_rate').set("readOnly",true);
		}
	}
}
function calCulateFixedPeriod(){
	var total_paid_install = dijit.byId('total_installamount').get('value');
	if(total_paid_install == 0){
		amount_principal = dijit.byId('sold_price').get('value');
	}else{
		amount_principal = dijit.byId('sold_price').get('value')-dijit.byId('total_installamount').get('value');
	}	
	dijit.byId('remain_balance').attr('value',amount_principal);
	
	dijit.byId('fixed_payment').set('readOnly',false);
	dojo.byId('lbl_payment').innerHTML="<?php echo $tr->translate("AMOUNT_GRAICE_PARIOD");?>";
	debt_term=30;
	collect_term = 1;
	collect_amount = 1;
	collect_term=30;
	debt_amount = dijit.byId('period').get('value')*<?php echo $install_month;?>;
	
	term = (debt_term*debt_amount)/(collect_term*collect_amount);
	interest_rate=dijit.byId('interest_rate').get('value')/<?php echo 12; //$install_month;?>/(100);//(100/30day)
	if(interest_rate==0){
		amount_payment = parseFloat(amount_principal/debt_amount);
		if(amount_payment=='Infinity' || amount_payment=='NaN'){amount_payment=0;}
	}else{
		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		//amount_payment = amount_payment.toFixed(0);
		if(isNaN(amount_payment)){amount_payment=0;
		}
	}	
	amount_payment = Math.ceil(amount_payment);
	dijit.byId('fixed_payment').attr('value',amount_payment);
	
	dijit.byId('for_installamount').attr('value',amount_principal);
}
function calculateDiscount(){
	total_sold = dijit.byId('total_sold').get('value');
	discount = dijit.byId('discount').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	other_fee = 0;
	if(isNaN(other_fee)){
		other_fee=0;
	}if(isNaN(discount)){
		discount=0;
	}
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	discount_percent = parseInt(total_sold*discount_percent/100);
	total_sold = total_sold-discount_percent-discount+other_fee;
	dijit.byId('sold_price').attr('value',total_sold);
	dijit.byId('remain_balance').attr('value',total_sold);
	Balance();
}
function Balance(){
	price = dijit.byId('sold_price').get('value');
	deposit =dijit.byId('deposit').get('value');
	if(isNaN(deposit)){
		deposit=0;
	}
	if(deposit>price){
		alert("Deposit can not biger than price ");
		dijit.byId('deposit').focus();
		dijit.byId('deposit').attr('value',price)
		dijit.byId('balance').attr('value',0)
	}else{ 
		schedule_opt = dijit.byId('schedule_opt').get('value');
		if(schedule_opt==2){
			dijit.byId('balance').attr('value',0);
		}else{
			if(schedule_opt==3){
				dijit.byId('for_installamount').attr('value',price-deposit);
			}
			dijit.byId('balance').attr('value',price-deposit);
		}
	}
}
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');	
	//dijit.byId('client_branch_id').attr('value',branch_id); // set branch id to popup client
	getAllPropertyBranch(branch_id);
	getLoanByBranch('');
	getReceiptByBranch('');
	getAllClientByBranch(branch_id);
	getAllClientNumberByBranch(branch_id);
}
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	property_type = dijit.byId('property_type').get('value');
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,'property_type':property_type
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_code').set('store', property_store);
		},
		error: function(err) {
		}
	});
} 
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(condition){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
			if(condition==1){
				getReceiptByBranch(data);
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}
var url_getreceipt = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-receipt-number')); ?>';
function getReceiptByBranch(new_sale_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('receipt').attr('value',data);
			if(new_sale_id!=''){
				printSave(new_sale_id,data);
			}
		},
		error: function(err) {
		}
	});
}
    function checkValidateDate(){
		return true;
     }
    
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	function doPrint() {
		dojo.byId('printblog2').innerHTML = dojo.byId('divPrint').innerHTML;
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML <?php if($this->data['showreceipt']>1){ ?>+ dojo.byId('divPrint1').innerHTML<?php }?>;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    printSubmit();
		hideDialog();
	}
	function printSubmit(){
		$('#frm_add_tran').submit();
	}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_name));?> );
var client_number_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_code));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );
var property_store  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
		checkScheduleOption();
		dijit.byId("paid_receivehouse").set("readOnly",true);
	  });
	 
	new dijit.form.FilteringSelect({
			store: property_store,//dojo.data.ObjectStore({objectStore: client_data}),
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,		           
			name: "land_code",
			id: "land_code",
			searchAttr: "name",
			class: 'fullside',
			required:true,
			onChange: function() {
				land_code = dijit.byId('land_code').get('value');
				if(land_code==-1){
				}else{
					getlandinfo();
				}
		}
			}, "land_code");
	 
	new dijit.form.FilteringSelect({
	store: client_store,//dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: false,
	queryExpr: "*${0}*",	           
	name: "member",
	id: "member",
	searchAttr: "name",
	required:true,
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			window.open('<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add'));?>');
		}else{
			dijit.byId('customer_code').attr('value',member);
			getcustomerinfo(member);
		}
}
	}, "member");
	
	new dijit.form.FilteringSelect({
	store: client_number_store,
	autoComplete: true,
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			window.open('<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add'));?>');
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");

});
</script>
<script type="text/javascript">
var url_getcustomer = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclient')); ?>';
function getcustomerinfo(client_id){
	dojo.xhrPost({
		url:url_getcustomer,	
		content:{ 
		    'client_id':client_id
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('joint_with').attr('value',data.hname_kh);
		},
		error: function(err) {
			alert(err);
		}
	});
}

var url_getlandinfodetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfo(){
	var typesale =dijit.byId('typesale').get('value');
	var oldprice= dijit.byId('total_sold').get('value');
	
	land_id = dijit.byId('land_code').get('value');
	if(land_id==''){return false;}
	dojo.xhrPost({
		url:url_getlandinfodetail,	
		content:{ 
		    'land_id':land_id
		},		    
		handleAs:"json",
		load: function(data) {
			if(typesale==2){//multi
				var had = 0;
		 		var landcode= dijit.byId('land_code').get('value');
		 		var rowId = $('#identity_land').val();
			 	if($("#identity_land").val()!='') {
			 		var rowIDArray = rowId.split(',');
		 			for(var n = 0; n < rowIDArray.length; n++) {
		 				if(landcode == rowIDArray[n]){
			 				alert("លេខដី/ផ្ទះ នេះបានជ្រើសរើសរួចហើយ");
			 				had = 1;
		 				}
		 			}
				 	if(had==1){}else{
						var identity = $("#identity_land").val();
						var price = oldprice + parseFloat(data.price);
						
						oldland_code =  oldland_code+","+data.land_code;
						address = address+"/"+data.land_address+','+data.street;
						size = parseFloat(size)+parseFloat(data.land_size);
						height = height+" , "+data.height;
						width = width+" , "+data.width;
						$("#identity_land").val(identity+','+data.id);
						
						dijit.byId('total_sold').attr('value',price);
						dijit.byId('sold_price').attr('value',price);

						dojo.byId('land_information').innerHTML ="លេខដី/ផ្ទះ  "+address+", ទំហំ "+size+" ម៉ែត្រការ៉េ ";
						dijit.byId('land_label').attr('value',address);
						}
				}else {
						$("#identity_land").val(data.id);
						dijit.byId('total_sold').attr('value',data.price);
						dijit.byId('sold_price').attr('value',data.price);

						oldland_code = data.land_code;
						address = data.land_address+','+data.street;
						size = data.land_size;
						height = data.height;
						width = data.width;
						dijit.byId('land_label').attr('value',address);
						dojo.byId('land_information').innerHTML ="លេខដី/ផ្ទះ  "+address+","+" ទំហំ "+size+" ម៉ែត្រការ៉េ ";
				}
			}else{//normal
				var price = oldprice + parseFloat(data.price);			
				dijit.byId('total_sold').attr('value',data.price);
				dijit.byId('sold_price').attr('value',data.price);
				dojo.byId('land_information').innerHTML ="លេខផ្ទះ/ឡូតិ៏  "+data.land_address+", លេខផ្លូវ  "+data.street+", ប្រភេទ  "+data.property_type+", ទំហំ "+data.land_size+" ម៉ែត្រការ៉េ, បណ្តោយ "+data.height+" ម៉ែត្រ, ទទឹង  "+data.width+" ម៉ែត្រ";
				dijit.byId('propertype').attr('value',data.house_type);
			}
			Balance();
		},
		error: function(err) {
			alert("alert get land"+err);
		}
	});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
}
function checkFirstRecord(){
	var rowId = $('#identity').val();
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
				paid = dijit.byId('deposit').get('value');
				if(total_amountpayment<paid){alert("សូមបញ្ជូលប្រាក់ត្រូវបង់ ធំជាងប្រាក់ដែលទទួលបាន! ");dijit.byId('percent'+rowIDArray[n]).focus();return false;}
			}
		}
  }
}
col=0;no=0;title=0;temp='';
function addRow(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	if(payment_method==4){addInstallment();}
	if(payment_method ==4 || payment_method==3 || payment_method==2 || payment_method==1){return false;}
	period = dijit.byId('period').get('value');
	if(period==0){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}

	no=0;title=0;temp='';$('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="color:#000 !important;background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	
	for(i=1;i<=period;i++){
		if(payment_method==6 || payment_method==5){
			col++;no++;
			template='';
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_AGREE");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				if(payment_method==5){
				temp+='<th><?php echo $tr->translate("រំលស់ជាមួយ");?></th>';
				}
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;

				epx_date = dijit.byId("first_payment").get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+1;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;
			}
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input type="text" class="fullside" data-dojo-type="dijit.form.NumberTextBox" id="percent_agree'+col+'" name="percent_agree'+col+'" /></td>';
				template+='<td><input type="text" onkeyup="calCulateAmount('+col+')" class="fullside" required="true" data-dojo-type="dijit.form.NumberTextBox"  id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input class="fullside" onkeyup="calCulateAmount('+col+',2)" type="text" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				if(payment_method==5){
					template+='<td width="140px"><select class="fullside" dojoType="dijit.form.FilteringSelect" id="pay_with'+col+'" name="pay_with'+col+'" ><option value="0">បង់ជាមួយម្ចាស់</option><option value="1">បង់ជាធនាគារ</option></select></td>';			
				}
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
	}
	dijit.byId("date_line").attr('value',epx_date);
}
function addInstallment(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	
	period = dijit.byId('period').get('value')*<?php echo $install_month;?>;
	if(period==0){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}
	temp='';

	result = checkFirstRecord();
	if(result==false){return false;}
	
		if(payment_method==4){
			col++;no++;
			template='';
			if(title!=1){    
				tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
				tmp+='<tr id="head-title" class="head-td" style="color:#000 !important;background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
				tmp+='</table>';
				dojo.query("#showrecord").append(tmp);
				
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_AGREE");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				epx_date ='<?php echo date('Y-m-d');?>';
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;

				mm_nextmonth = a.getMonth()+3;
				if(mm_nextmonth<10){
					mm_nextmonth = "0"+mm_nextmonth;
				}
				
				var start_date = y + '-'+ mm_nextmonth + '-'+dd ;
			}
			    dijit.byId("release_date").attr('value',epx_date);
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input type="text" class="fullside" data-dojo-type="dijit.form.NumberTextBox" id="percent_agree'+col+'" name="percent_agree'+col+'" /></td>';
				template+='<td><input onkeyup="calCulateAmount('+col+')" class="fullside" type="text" required="true" data-dojo-type="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td><input class="fullside" type="text" onkeyup="calCulateAmount('+col+',2)" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
}
function calCulateAmount(index,revers=1){
	balance = dijit.byId('sold_price').get('value');
	if(revers==1){//% to value
	    percent = dijit.byId('percent'+index).get('value');
	    amount_payment = parseInt(balance*percent/100);
	    dijit.byId('total_payment'+index).attr('value',amount_payment);
   }else{//value to %
	   amount_payment =  dijit.byId('total_payment'+index).get('value');
	   percent = amount_payment*100/balance;
	   dijit.byId('percent'+index).attr('value',percent);
     }
	calCulateSchedulePayment();
	 if(dijit.byId('percent'+index).get('value')>100){
		 alert("តម្លៃត្រូវបង់មិនអាចធំជាង ១០០ ភាគរយបានទេ !");
		 dijit.byId('percent'+index).attr("");
		 dijit.byId('percent'+index).focus();
     }
}
function calCulateSchedulePayment(){
	var total_amount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	if(rowId!=''){
	for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
			}
			if(isNaN(total_amountpayment)){
				total_amountpayment = 0;
			}
			total_amount = total_amount+ total_amountpayment;
		}
	}
	dijit.byId('total_installamount').attr('value',total_amount);
	total_sold = dijit.byId("sold_price").get("value");
	total_amount = total_sold-total_amount;
	dijit.byId('remain_balance').attr('value',total_amount);
	calCulateFixedPeriod();
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
	if(arrays.length==0){ dijit.byId('total_installamount').attr('value','');}
	calCulateSchedulePayment();
}
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	var a = new Date(date_release);
	mm = a.getMonth()+amount_date+1;
	 var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+1;

	var epx_date = y + '-'+ mm + '-'+dd ;
	calCulateEndDate();
	calCulateFirstPayment();
}
function calCulateEndDate(){
	amount_period = 1;
	if(dijit.byId("schedule_opt").get('value')==4){amount_period=<?php echo $install_month;?>;}
	amount_date = dijit.byId('period').get('value')*amount_period;
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		month = a.getMonth()+amount_date;
		mm = month%12;
		year = parseInt(month/12);
		 var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear()+year;
		var epx_date = y + '-'+ mm + '-'+dd ;
        payment_option = dijit.byId('schedule_opt').attr('value');
		if(payment_option==2){
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
		}else{
			dijit.byId('date_line').attr('value',epx_date);	
		}
    }
}
function CalculateDate(){
	pay_term = 1;
	amount_period = 1;
	if(dijit.byId("schedule_opt").get('value')==4){amount_period=<?php echo $install_month;?>;}
	amount_date = dijit.byId('period').get('value')*amount_period;
	
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = 1;
	amount_date = 1;
	method_id = dijit.byId('schedule_opt').get('value');
	addamount=1;
	if(method_id==3 || schedule_opt==6){
		addamount=0;
	}
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
		mm = a.getMonth()+amount_date+addamount;
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	
	dijit.byId('first_payment').attr('value',epx_date);
}
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==""){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img class="view" style="height:75px; max-width: 100%;" src="<?php echo $this->baseUrl()."/images/projects/"?>'+arr.logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;
		},
		error: function(e) {
		}
	});
}
function printSave(new_stu_id,new_receipt_no){
	getBranchInfo();
	schedule_opt = dijit.byId("schedule_opt").get("value");
	if(schedule_opt==2){//បង់ផ្តាច់
		  sold_price = dijit.byId("sold_price").get("value");
		  deposit = dijit.byId("deposit").get("value");
		  if(sold_price!=deposit){
			alert("បង់ផ្តាច់ តម្លៃលក់ ត្រូវស្មើរ នឹងប្រាក់ដែលត្រូវទទួល!");
			dijit.byId("deposit").focus();
			return false;
		  }
	}
	deposit = dijit.byId('deposit').get('value');
	if (deposit=='' || deposit==-1){
		alert('សូមបញ្ចូលប្រាក់ត្រូវបង់ ទើបបោះពុម្ភបង្កាន់ដៃបង់ប្រាក់បាន!');
		dijit.byId('deposit').focus();
		return false;
	}
	schedule_opt = dijit.byId("schedule_opt").get("value");
	if(schedule_opt==1 && new_receipt_no!=''){
		var r = confirm("<?php echo $tr->translate("ALERT_DEPOSIT_WARNING");?>"+"\n"+"<?php echo $tr->translate("ALERT_BEFORE_SAVE");?>");
		if (r == true) {
		} else {
		    return false;
		}
	}
	symbal=" $";
	if(new_stu_id=='' && new_receipt_no==''){
		getLoanByBranch(1);
		return false;
	}else{
		dojo.byId("lb_receipt").innerHTML = new_receipt_no;
	}
	dijit.byId("lbl_schedule").hide();
	dojo.byId("lbl_paidtimes").innerHTML = dijit.byId("schedule_opt").attr('displayedValue');

	date_payment = dijit.byId("date_buy").get('value');
	var a = new Date(date_payment);
	mm = a.getMonth()+1;
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	month = returnMOnth(mm);
	var y = a.getFullYear();
	var date_payment = dd +'-'+month+'-'+y ;
	
	dojo.byId("paid_date").innerHTML = date_payment;
	lbl_landaddress = dijit.byId("land_code").attr('displayedValue')+dijit.byId("propertype").attr('displayedValue');
	sale_type = dijit.byId("typesale").get('value');
	if(sale_type==2){
		lbl_landaddress =  dijit.byId("land_label").get('value');
	}
	dojo.byId("lb_hourseno").innerHTML = lbl_landaddress;
	dojo.byId("lb_saleprice").innerHTML = "$ "+dojo.number.format(dijit.byId("sold_price").get('value'),{places:2});
	
	sold_price = dijit.byId('sold_price').get('value');
	total_interest = dijit.byId("total_interest").get('value');
	total_principalpaid =dijit.byId("deposit").get('value')-total_interest;
	if(total_principalpaid<0){total_principalpaid=0;}
	balance = sold_price-total_principalpaid;
	if(isNaN(balance)){balance=0;}
	dojo.byId("lb_interest").innerHTML ="$ "+dojo.number.format(total_interest,{places:2});
	dojo.byId("lbl_total_paid1").innerHTML ="$ "+dojo.number.format(total_principalpaid,{places:2});
	dojo.byId("lbl_balance").innerHTML ="$ "+dojo.number.format(balance,{places:2});
	
	dojo.byId("lb_noted").innerHTML =dijit.byId("note").get('value');
	dojo.byId("lbl_paymenttype").innerHTML = "សាច់ប្រាក់";
	dojo.byId("lbl_paid_date1").innerHTML = date_payment;
	dojo.byId("lb_buydate1").innerHTML = date_payment;
	dojo.byId("lbl_totalpayment").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
	dojo.byId("lbl_total_receive").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
	dojo.byId("lb_amount").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
	
	joint_with = dijit.byId("joint_with").attr('displayedValue');
	if(joint_with!=''){joint_with = "/"+joint_with}
	
	dojo.byId("lbl_customer").innerHTML = dijit.byId("member").attr('displayedValue')+joint_with;
	dojo.byId("lb_customer").innerHTML = dijit.byId("member").attr('displayedValue');

	dojo.byId("lbl_project").innerHTML = dijit.byId("branch_id").attr('displayedValue');
	dijit.byId("terms").show();	
}
var url_previewloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'addschedultest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()){
		client = dijit.byId('member').get('value');
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('customer_code').focus();
			return false;
		}
		schedule_opt = dijit.byId("schedule_opt").get("value");
		remain_balance = dijit.byId("remain_balance").get("value");
		if(schedule_opt==6 || schedule_opt==5){ 
			identity = $("#identity").val(); 
			if(identity==''){ 
				alert("សូមបញ្ចូលប្រាក់ដែលអតិថិជននឹងត្រូវបង់!");
				addRow(); return false;
			}
			if(remain_balance!=0){
				alert("ការរៀបចំតារាងត្រូវបង់មិនទាន់គ្រប់ចំនួនទេ។សូមត្រួតពិនិត្យម្តងទៀត !");	
				return false;
			}
		}
		result = checkFirstRecord();
		if(result==false){return false;}
		loading();
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				 document.getElementsByClassName("overlay")[0].style.display="none";
				if(data.row_id=='row_id'){//return 1;
					printSave('','');
					}else{
						  temp='';	
						  fund_title=0;thead='';fund_title=0;
						  temp='<table class="collape tablesorter" style="font-size:13px; width:1000px !important; " id="table">'
						  temp+='<tr style="background:#ccc;"><th><?php echo $tr->translate("NUM");?></th>';
						  temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						  temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						  principal_permonth=0;total_interest=0;total_payment_after=0;
						for(i=0;i<data.length;i++){
							if(i==0){
								dijit.byId('total_interest').attr('value',data[i].total_interest);
							}
							principal_permonth=principal_permonth+parseFloat(data[i].principal_permonth);
							total_interest=total_interest+parseFloat(data[i].total_interest);
							total_payment_after=total_payment_after+parseFloat(data[i].total_payment_after);
					      r++;
						  temp+='<tr><td align="center">'+r+'</td>';
						  var myDate = new Date(data[i].date_payment);
						  d = new Date(data[i].date_name);
						  temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].begining_balance,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(data[i].total_payment_after,2)+'<b></td>';
						  temp+='<td><b>'+dojo.number.format((data[i].ending_balance),2)+'<b></td>';
						 }
						  temp+='<tr><td align="right" colspan="3" style="border-left:1px solid #fff;border-bottom:1px solid #fff;">&nbsp;សរុប -Total</td>';
						  temp+='<td>'+dojo.number.format(principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(total_payment_after,2)+'<b></td>';
						  temp+='<td></td>';
						temp+='</table>';
						dojo.byId('t_amountmoneytype').innerHTML = temp;
						dijit.byId("lbl_schedule").show();
					}
			},
			error: function(response, ioArgs) {
				 document.getElementsByClassName("overlay")[0].style.display="none";
				alert("Failed while doing the operation: " + ioArgs.xhr.response);
			}
	   });
	}
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("lbl_schedule").hide();
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
var url_add_staff = '<?php echo $this->url(array("module"=>"loan","controller"=>"index","action"=>"add-staff")); ?>';
function addStaff(){
	 if(dijit.byId('frm_staff').validate()){
		dijit.byId('save').set('disabled',true);
		dojo.xhrPost({
			url:url_add_staff,
			form: dojo.byId("frm_staff"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = { 
		    	  	id: data,
			        name: dijit.byId('kh_name').get('value')
			    };
		 		addDataToSelectbox(dijit.byId('staff_id'), staff_store, Itemmake, data);
			    dijit.byId('frm_staff').reset();
			    dijit.byId("popup_staff").hide();
			},
			error: function(err) {
				alert(err);
			}
		});
   }
}
function hideDialog1(){
	 dijit.byId("popup_staff").hide();
}

</script>
<style>
.hover:hover{background: #eee;}
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl();?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_staff" >
		<form style="background-color: buttonface; width:100%;" id='frm_staff' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_STAFF');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px; line-height: 32px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME_KH');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="kh_name" name="kh_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('SEX');?></td>
									<td>
										<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="sex" name="sex" value="" type="text">
											<option value="1"><?php echo $tr->translate("MALE");?></option>
											<option value="2"><?php echo $tr->translate("FEMALE");?></option>
										</select>
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('PHONE');?></td>
									<td><input type="hidden" name="branch_id_pop" id="branch_id_pop" dojoType="dijit.form.TextBox" />
										<input type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('NOTE');?></td>
									<td>
										<input type="text" name="note_pop" id="note_pop" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
								</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="<?php echo $tr->translate("CANCEL");?>" id="close" name="close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="<?php echo $tr->translate("GO_SAVE");?>" id="save" name="save" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addStaff();"/>
									</td>
								</tr>
								
							</table>
					</fieldset>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script>
function returnMOnth(monthnum){
	var month = new Array();
	month[1] = "Jan";
	month[2] = "Feb";
	month[3] = "Mar";
	month[4] = "Apr";
	month[5] = "May";
	month[6] = "Jun";
	month[7] = "Jul";
	month[8] = "Aug";
	month[9] = "Sep";
	month[10] = "Oct";
	month[11] = "Nov";
	month[12] = "Dec";
	return month[monthnum];
}
function calculateDuration(type=null){
	<?php if($autocalcualte==1){// 1 auto calculate date ,0 no calculate?>
		if(type==1){
			var total_paid_install = dijit.byId('total_installamount').get('value');
			if(total_paid_install == 0){
				sold_price = dijit.byId('sold_price').get('value');
			}else{
				sold_price = dijit.byId('sold_price').get('value')-dijit.byId('total_installamount').get('value');
			}
			interest_rate= dijit.byId('interest_rate').get('value')/<?php echo $install_month;?>/(100);//(100/30day)
			fixed_payment = dijit.byId('fixed_payment').get('value');
			if(isNaN(interest_rate)){interest_rate=0;}
			if(interest_rate>0){
				pi = (parseFloat(fixed_payment)-(parseFloat(sold_price)*parseFloat(interest_rate)));
				s = parseFloat(fixed_payment);
				top_ii = Math.log(s/pi);
				var duration =  Math.ceil(top_ii / Math.log(1+ parseFloat(interest_rate)));// ROUND UP
				duration = duration/<?php echo $install_month;?>;
				
			}else{
				duration = sold_price/fixed_payment;
				duration = parseInt(duration);
			}
			dijit.byId('period').attr('value',duration);
		}
	<?php }?>
}
</script>