<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("LOAN_IL"));
$url_copy =$this->url(array('module'=>'loan','controller'=>'newschedule','action'=>'add'));

$url_agreement =$this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-paymentschedules'));
$frm = $this->frm_search;
$edit_sale = $tr->translate("EDIT");
$aggreeement = $tr->translate("AGREEMENT");
$reschedule = $tr->translate("ISSUE_SCHEDULE");
$scheduleReport = $tr->translate("តារាងបង់");
$newReschedule=$tr->translate("NEW_SCHEDULE");
$payment=$tr->translate("RECEIVED_MONEY");

$urlEdit = $this->baseUrl()."/loan/index/editsale/id/";
$urlPayment = $this->baseUrl()."/loan/ilpayment/add/id/";
$urlRepaymentschedule = $this->baseUrl()."/loan/repaymentschedule/add/id/";
$urlAgreement = $this->baseUrl()."/report/paramater/rpt-agreement/id/";
$urlpaymentschedules = $this->baseUrl()."/report/loan/rpt-paymentschedules/id/";
$urlNewschedule = $this->baseUrl()."/loan/newschedule/add/id/";
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
   <table width="100%">
   <tr>  
        <td><?php echo $frm->getElement("adv_search");?></td>
   		<td><?php echo $frm->getElement("branch_id");?></td>
   		<td><?php echo $frm->getElement("client_name");?></td>
   		<td><input id="land_id" /></td>
   		<td><?php echo $frm->getElement('schedule_opt');?></td>
   </tr>
   <tr>
   		<td><?php echo $frm->getElement('co_id');?></td>
   		<td><?php echo $frm->getElement('start_date');?></td>
   		<td><?php echo $frm->getElement('end_date');?></td>
   		<td><?php echo $frm->getElement('status');?></td>
   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
   		
   		</td>
   </tr>
</table>
</form>
<?php echo $this->list;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
		}, "land_id");
});
land_id = '<?php echo $this->rssearch['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
} 
function reschedule(url){
	 id = dijit.byId('recordcopy').get('value');
	 if(id==''){alert("Please select record first!");return false;}
	 window.location.href = url+'/id/'+id;
}
function agreement(url){
	 id = dijit.byId('recordcopy').get('value');
	 if(id==''){alert("Please select record first!");return false;}
	 window.open(url+'/id/'+id);
}
function setValue(index){
	var recordcopy = $('input[name=copy]:checked').val();
	dijit.byId('recordcopy').attr('value',recordcopy);
}
function getmemberIdGroup(){
	customer_code= dijit.byId('customer_code').get('value');
	dijit.byId('member').attr('value',customer_code);
}
function checkMember(){
	customer_code= dijit.byId('member').get('value');
	dijit.byId('customer_code').attr('value',customer_code);
}


var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="edit"){
				url='<?php echo $urlEdit;?>';
				
			}else if(key=="agreement"){
				url='<?php echo $urlAgreement;?>';
			}else if(key=="payment"){
				url='<?php echo $urlPayment;?>';
			}else if(key=="schedulePay"){
				url='<?php echo $urlpaymentschedules;?>';
			}else if(key=="reschedule"){
				url='<?php echo $urlRepaymentschedule;?>';
			}else if(key=="newschedule"){
				url='<?php echo $urlNewschedule;?>';
			}
			gotoAction();
			//window.console && console.log(m) || alert(m); 
		},
		items: {
			"edit": {name: "<?php echo $edit_sale;?>", icon: "edit", accesskey: "e"},
			"agreement": {name: "<?php echo $aggreeement;?>", icon: "fa-file-text", accesskey: "c"},
			// first unused character is taken (here: o)
			"payment": {name: "<?php echo $payment;?>", icon: "fa-money", accesskey: "c o p y"},
			// words are truncated to their first letter (here: p)
			"schedulePay": {name: "<?php echo $scheduleReport;?>", icon: "paste", accesskey: "cool paste"},
			"reschedule": {name: "<?php echo $reschedule;?>", icon: "fa-calendar"},
			"newschedule": {name: "<?php echo $tr->translate("NEW_SCHEDULE");?>", icon: "fa-calendar"},
		}
	});
});
function setrowdata(index){
	row = index;
}

var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>