<?php 
	$tran = $this->tran_schedule;
	$client = $this->client;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$install_month = $this->data['install_by'];
	$interestSetting = SETTING_INTEREST;
	
	$dbGb = new Application_Model_DbTable_DbGlobal();
	$Rs = $dbGb->getInterestPolicy();
	
?>
<title><?php echo $tr->translate('REPORT WEEK');?></title>
<style>
td p{ margin-top:0px !important;}
</style>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
   <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
		require(["dojo/ready"], function(ready){
			 ready(function(){
				checkScheduleOption();
				calCulateSchedulePayment();
				calCulateEndDate();
			  });
		});
   </script>
<div style=" width:28cm; margin:0 auto; border: 1px dotted #ccc; padding: 0 40px;">
	<div id="divPrint">
	<style type="text/css">
	.style{
		line-height: 20px;font-size: 14px;
		font-family: 'Kh Battambang','Khmer Battambang',Arial,Helvetica,sans-serif;
	}
	.font_bold{
		font-family:'Khmer MEF2';
		font-size: 12px;
	}
	td p{ margin-top:-12px;}
	.fullside50{ width:48%;}
	</style>
<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
           schedule_opt = dijit.byId('payment_id').get('value');
           total_remain = dijit.byId('total_remain').get('value');
           total_duration = dijit.byId('total_duration').get('value');
           var rowId = $('#identity').val();
		   var rowIDArray = rowId.split(',');
		   record_no = rowIDArray.length;
           if((schedule_opt==3 || schedule_opt==6) && rowId==''){
				alert("សូមបញ្ចូលប្រាក់ដែលអតិថិជនត្រូវបង់ក្នុងតារាងបង់");
                addRow();
                return false;
		   }else if((schedule_opt==3 || schedule_opt==6) && total_remain!=0){
          		alert("សូមបញ្ចូលប្រាក់ដែលនៅសល់ ដាក់ក្នុងតារាងបង់អោយអស់!");
				dijit.byId('total_remain').focus()
                return false;
          }else if((schedule_opt==3 || schedule_opt==6) && record_no!=total_duration){
				alert("រយះពេលបង់នឹងតារាងត្រូវបង់ មិនត្រឹមត្រូវទេ!");
                dijit.byId('total_duration').attr('value',record_no)
				dijit.byId('total_duration').focus();
				return false;
			}
            dijit.byId('btn_save_close').set('disabled',true);
				return true;
			}else {
				return false;
			}
	</script>
	<table style="font-family:'Kh Battambang','Khmer Battambang',Arial,Helvetica,sans-serif; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<table width="100%" style="font-family:'Kh Battambang','Khmer Battambang',Arial,Helvetica,sans-serif;margin:0 auto;padding:0px; border:none;">
					<tr>
	                	<td width="30%" style=""></td>
	                	<td width="47%" valign="top">
	                	<h2 style="text-align:center; font-size:18px; font-family:'Khmer OS Muol'"><label><?php echo $tr->translate("BRAND_TITLE");?><?php //echo $this->data['brand_title'];?></label></h2>
	                	<h2 style="text-align:center; font-size:13px; font-family:'Khmer OS Muol'"><label><?php //echo $client['branch_name'];?></label></h2>
	                	<h2 style="text-align:center; font-size:16px; font-family:'Khmer OS Muol'"><?php //echo $tr->translate('rpt-paymentschedule');?> <?php echo $tr->translate('តារាងកាលវិភាគបង់ប្រាក់');?></h2></td>
	                    <td></td>
	                </tr>
	                <?php 
	                	  $db = new Application_Model_DbTable_DbGlobal();
	                	  $row = $db->getClientByType(null,$client['client_id'],1);
	                ?> 
	                <tr>
	                	<td colspan="3">
	                		<table width="100%" style="margin-top:10px; font-size: 14px !important;">
			                	<tr class='style'>
				                   <td width="35%">
				                   		<p>
				                   			<input type="hidden" name="branch_id" id="branch_id" value="<?php echo $client['branch_id'];?>" />
				                   		</p>
				                   		<p><?php 
				                   				echo $tr->translate("CLIENT_NUM")." : ".$client['client_number']
	                						?>
	                					</p>
				                	    <p><?php echo $tr->translate('CUSTOMER_NAME');?>:
				                	    	<select style="width:130px;" id='customer_id' name='customer_id' dojoType="dijit.form.FilteringSelect">
				                   			<?php 
					                   			if(!empty($this->customer)){
						                   			foreach($this->customer as $rs){?>
						   								 <option value="<?php echo $rs['id']?>" <?php if($rs['id']==$client['client_id']){echo 'selected';}?>><?php echo $rs['name']?></option>               				
						                   			<?php }
					                   			}
				                   			?>
				                   			</select>
				                   		</p>
				                		<p><?php echo $tr->translate("TEL");?> : <?php echo $client['tel'];?></p>
				                		<p><?php echo $tr->translate("ADDRESS");?>:<?php echo $row['village_name'];?> ,<?php echo $row['commune_name'];?> <br /><?php echo $row['district_name'];?> ,  <?php echo $row['province_en_name'];?>
				                	</td>
				                    <td valign="top" style="" width="33%">
				                    	<table width="100%" style="font-size: 14px;">
				                    		<tr>
					                    		<td><?php echo $tr->translate("តម្លៃមុនលក់");?></td>
					                    		<td><input onkeyup="calculateDiscount();" dojoType="dijit.form.NumberTextBox" style="width:90px" type="text" name="price_before" id="price_before" value="<?php echo $client['price_before'];?>" /></td>
					                    	</tr>
					                    	<tr>
					                    		<td><?php echo $tr->translate("បញ្ចុះតម្លៃ $");?></td>
					                    		<td><input  onkeyup="calculateDiscount();" dojoType="dijit.form.NumberTextBox" style="width:90px" type="text" name="discount_amount" id="discount_amount" value="<?php echo $client['discount_amount'];?>" /></td>
					                    	</tr>
					                    	<tr>
					                    		<td><?php echo $tr->translate("បញ្ចុះតម្លៃ %");?></td>
					                    		<td><input  onkeyup="calculateDiscount();" dojoType="dijit.form.NumberTextBox" style="width:90px" type="text" name="discount_percent" id="discount_percent" value="<?php echo $client['discount_percent'];?>" /></td>
					                    	</tr>
					                    	<tr>
					                    		<td><?php echo $tr->translate("SOLD_PRICE");?></td>
					                    		<td><input readonly onkeyup="calculateDiscount();" dojoType="dijit.form.NumberTextBox" style="width:90px" type="text" name="price_sold" id="price_sold" value="<?php echo $client['price_sold'];?>" /></td>
					                    	</tr>
				                    	</table>
				                    </td>
				                    <td valign="top">
				                    	<table width="100%" style="font-size: 14px;">
				                    		<tr>
					                    		<td><?php echo $tr->translate("BUY_DATE");?></td>
					                    		<td><input style="width:150px;" class="fullside" type="text" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" name="date_buy" id="date_buy" value="<?php echo $client['buy_date'];?>" /></td>
					                    	</tr>
					                    	<tr>
					                    		<td><?php echo $tr->translate("ថ្ងៃចេញកិច្ចសន្យា");?></td>
					                    		<td><input style="width:150px;" class="fullside" type="text" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" name="dateagreement" id="dateagreement" value="<?php echo $client['agreement_date'];?>" /></td>
					                    	</tr>
					                    	<tr>
					                    		<td><?php echo $tr->translate("លេខដី/ផ្ទះ");?></td>
					                    		<td><?php echo $client['land_address'].",".$client['stree'];?></td>
					                    	</tr>
					                    	<tr>
					                    		<td><?php echo $tr->translate("TYPE");?></td>
					                    		<td><?php echo $client['propertype'];?>
					                    		<input type="hidden" name="id" id="id" value="<?php echo $this->id;?>" />
					                    		<input type="hidden" name="client_id" id="client_id" value="<?php echo $client['client_id'];?>" />
					                    		<input type="hidden" name="house_id" id="house_id" value="<?php echo $client['house_id'];?>" />
					                    		</td>
					                    	</tr>
					                    	<tr>
					                    		<td><?php echo $tr->translate("តម្លៃដី");?></td>
					                    		<td><input type="text" style="width:150px;" name="land_price" id="land_price" dojoType="dijit.form.NumberTextBox" value="<?php echo $client['land_price'];?>" /></td>
					                    	</tr>
				                    	</table>
				                    </td>
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
	        </td>
	    </tr>
	    <tr>
	    	<td>
	    	<table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;font-family:'Kh Battambang','Khmer Battambang',Arial,Helvetica,sans-serif" width="100%">
	                 <tr class="style" align="center" style="line-height: 20px; height: 30px; white-space: nowrap;">
	                    <td>លុប</td>
	                    <td><?php echo $tr->translate("NUM");?></td>
	                    <td>ប្រាក់ដើមត្រូវបង់</td>
	                    <td><?php echo $tr->translate("គិតជា%");?></td>
	                    <td><?php echo $tr->translate("PERCENT_AGREE");?>%</td>
	                    <td>ការប្រាក់ត្រូវបង់</td>
	                    <td><?php echo $tr->translate("ត្រូវបង់សរុប");?></td>
						<td style="border-left:2px solid #000;"><?php echo $tr->translate("DAY_PAYMENT");?></td>
	                    <td>ប្រាក់ដើមបានបង់</td>
	                    <td>ការប្រាក់បានបង់</td>
	                    <td>បានបង់សរុប</td>
	                    <td>ថ្ងៃបានបង់</td>
	                    <td>ស្ថានការបង់</td>
	                     <td><?php echo $tr->translate("TYPE");?></td>
	                </tr>
	               <?php
					   $indentity = "";
					   $total_pricipale=0;
					   $recordstart=0;
		               $str = ''; if(!empty($tran)) foreach($tran as $key =>$row){
		               $recordstart=$recordstart+1;
	               	?>
	               	<tr align="center" style="height: 20px;" class="style" id='row<?php echo $key+1;?>'>
	               	<?php if($key==0){
	               		$str=$key+1;
	               	}else{
	               		$str.=",".($key+1);
	               	}
	               	$total_pricipale =$total_pricipale+$row['principal_permonth'];
	               	?>
	                    <td ><img onclick="deleteRecord(<?php echo $key+1;?>)" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>
	                    <td><?php echo ($key+1<10)?"0":""; echo $key+1;?>
	                        <input style="border:1px solid #fff;" type="hidden" name="interest_<?php echo $key+1;?>" id="interest" value="<?php //echo $row['total_interest'];?>" />
	                        <input type="hidden" style="border:1px solid #fff;width:150px;"  type="text" name="fundid_<?php echo $key+1;?>" id="fundid_<?php echo $key+1;?>" value="<?php echo $row['id'];?>" />
	                    </td>
	                    <td style="width:80px;" ><input onkeyup="calculatePayment(<?php echo $key+1;?>);" class="fullside" style="border:1px solid #fff;"  dojoType="dijit.form.NumberTextBox" type="text" name="principal_permonth_<?php echo $key+1;?>" id="principal_permonth_<?php echo $key+1;?>" value="<?php echo $row['principal_permonth']; ?>" /></td>
	                    <td style="width:60px;"><input onkeyup="calculatePayment(<?php echo $key+1;?>,2);" class="fullside" style="border:1px solid #fff;"  dojoType="dijit.form.NumberTextBox" type="text" name="percent<?php echo $key+1;?>" id="percent<?php echo $key+1;?>" value="<?php echo $row['percent']; ?>" /></td>
	                    <td style="width:60px;"><input class="fullside" style="border:1px solid #fff;"  dojoType="dijit.form.NumberTextBox" type="text" name="percent_agreement<?php echo $key+1;?>" id="percent_agreement<?php echo $key+1;?>" value="<?php echo $row['percent_agree']; ?>" /></td>
	                    <td style="width:80px;"><input onkeyup="calculatePayment(<?php echo $key+1;?>);" class="fullside" style="border:1px solid #fff;"  dojoType="dijit.form.NumberTextBox" type="text" name="total_interest_<?php echo $key+1;?>" id="total_interest_<?php echo $key+1;?>" value="<?php echo $row['total_interest']; ?>" /></td>
	                    <td align="center" style="white-space: nowrap; width:80px;"><input readonly class="fullside" style="border:1px solid #fff;"  dojoType="dijit.form.NumberTextBox" type="text" name="total_payment<?php echo $key+1;?>" id="total_payment<?php echo $key+1;?>" value="<?php echo $row['principal_permonth']+$row['total_interest']; ?>" /></td>
	                    <td style="border-left:2px solid #000;"><input onchange="setFirstPayment(<?php echo $key+1;?>);" class="fullside" style="border:1px solid #fff;" class="fullside" type="text" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" name="date_payment<?php echo $key+1;?>" id="date_payment<?php echo $key+1;?>" value="<?php echo $row['date_payment'];?>" /></td>
	                    <td style="width:100px;"><input style="border:1px solid #fff;" type="hidden" name="principal_<?php echo $key+1;?>" id="principal" value="<?php echo $row['principal_permonthafter'];?>" />
	                   	 	<input class="fullside" style="border:1px solid #fff;" type="text" onkeyup="calculatePaid(<?php echo $key+1;?>)" name="paid_principal<?php echo $key+1;?>" dojoType="dijit.form.NumberTextBox"  id="paid_principal<?php echo $key+1;?>" value="<?php echo $row['principal_paid'];?>" /></td>
	                    <td style="width:100px;"><input class="fullside" style="border:1px solid #fff;"  type="text" onkeyup="calculatePaid(<?php echo $key+1;?>)" dojoType="dijit.form.NumberTextBox" name="interest_paid<?php echo $key+1;?>" id="interest_paid<?php echo $key+1;?>" value="<?php echo $row['total_interestpaid'];?>" /></td>
	                    <td><input readonly style="border:1px solid #fff;" class="fullside" type="text" dojoType="dijit.form.NumberTextBox" name="paid_amount_<?php echo $key+1;?>" id="paid_amount_<?php echo $key+1;?>" value="<?php echo $row['total_recieve'];?>" /></td>
	                    <td style="width:100px;"><input style="border:1px solid #fff;" class="fullside" type="text" constraints="{datePattern:'dd/MM/yyyy'}" dojoType="dijit.form.DateTextBox" name="paid_date_<?php echo $key+1;?>" id="paid_date_<?php echo $key+1;?>" value="<?php echo $row['paid_date'];?>" />
	                    <td style="width:120px;"><select dojoType="dijit.form.FilteringSelect" class="fullside"  style="border:1px solid #fff;height: 30px;"  name="payment_option<?php echo $key+1;?>" id="payment_option<?php echo $key+1;?>">
	                    <option value="0" <?php if($row['is_completed']==0){ echo "selected='selected'"; }?>>មិនទាន់គ្រប់</option>
	                    <option value="1" <?php if($row['is_completed']==1){ echo "selected='selected'"; }?>>បង់ដាច់</option></select></td>
	                    <td width="140px">
		                    <select class="fullside" dojoType="dijit.form.FilteringSelect" id="pay_with<?php echo $key+1;?>" name="pay_with<?php echo $key+1;?>" >
		                   		<option value="0"><?php echo $tr->translate("PLEASE_SELECT");?></option>
		                   		<?php if (!empty($this->steppay)) foreach ($this->steppay as $stt){?>
		                   		<option value="<?php echo $stt['key_code']?>" <?php if($row['ispay_bank']==$stt['key_code']){ echo "selected='selected'"; }?>><?php echo $stt['name_en']?></option>
		                   		<?php }?>
		                    </select>
	                    </td>
	                </tr>
	                
	               <?php } ?>
	               <tfoot id="table_row">
	               </tfoot>
	            </table>
	    	</td>
	    </tr>
	    <tr>
	          <td>
	          	<div class="tab-content vertical">
			        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
			        	<div class="card-box">
			        		<div class="col-md-3">
			        			<input type="button" label="<?php echo $tr->translate('ADD_INSTALLMENT');?>" dojoType="dijit.form.Button" 
			 						iconClass="dijitIconEditProperty" onclick="addRow();" /> 
			        		</div>
			        		<div class="col-md-5">
			        			<div class="form-group">
				                   <div class="col-md-5 ">
				                   		<?php echo $tr->translate("សរុបរួមពីខាងលើ");
				                    		if($client['payment_id']==4){
				                    			$balance = $client['price_sold']-$client['total_installamount'];
				                    		}else{$balance=0;
				                    		}
			                    		?>
				                   </div>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<input class="fullside" readOnly style="color:red; font-weight: bold;" dojoType="dijit.form.NumberTextBox" type="text" name="total_installamount" id="total_installamount" value="<?php echo $client['price_sold']-$balance;?>" />
				                   </div>
				                </div>
				                <div class="form-group">
				                   <div class="col-md-5"><?php echo $tr->translate("Balance");?></div>
				                   <div class="col-md-7 col-sm-7 col-xs-12"><input class="fullside" dojoType="dijit.form.NumberTextBox" onkeyup="checkScheduleOption();"  type="text" name="total_remain" id="total_remain" value="<?php echo $client['price_sold']-$total_pricipale;?>"  /></div>
				                </div>
				                <div class="form-group" id="hidden_lastpayment" style="display:none;">
				                   <div class="col-md-5"><?php echo $tr->translate("LAST_PAYMENT");?></div>
				                   <div class="col-md-7 col-sm-7 col-xs-12"><input class="fullside" dojoType="dijit.form.NumberTextBox" onkeyup="checkScheduleOption();"  type="text" name="last_payment" id="last_payment" value="<?php echo $client['lastpayment_amount'];?>"  /></div>
				                </div>
				                <div class="form-group">
				                   <div class="col-md-5"><?php echo $tr->translate("PAYMENT_TYPE");?></div>
				                   <div class="col-md-4">
				                   		<select class="fullside" onchange="checkScheduleOption();"  dojoType="dijit.form.FilteringSelect" name="payment_id" id="payment_id" >
			                    			<?php if(!empty($this->payment_option)){ 
			                    			foreach($this->payment_option as $rs){  ?>
			                    				<option value="<?php echo $rs['key_code'];?>" <?php if($client['payment_id']==$rs['key_code']){echo"selected";}?>><?php echo $rs['name_en'];?></option>
			                    			<?php }
			                    			}?>
		                    			</select>
		                    		</div>
		                    		<div class="col-md-3 col-sm-3">
		                    			<select class="fullside" dojoType="dijit.form.FilteringSelect" name="install_type" id="install_type">
											<option value="1">រំលស់ថេរ</option>
											<option value="2">រំលស់ថយ</option>
										</select>
									</div>
				                </div>
				                <div class="form-group" style="<?php if ($interestSetting==0){ echo "display: none;";}?>">
				                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_POLICY");?></label>
				                   <div class="col-md-7 col-sm-7 col-xs-12">
				                   		<select class="fullside" dojoType="dijit.form.FilteringSelect" name="interest_policy" id="interest_policy">
											<option value="0"><?php echo $tr->translate("NORMAL_INTEREST")?></option>
											<?php if(!empty($Rs))foreach($Rs AS $row){?>
											<option value="<?php echo $row['id']?>"><?php echo $row['name']?></option>
											<?php }?>
										</select>
				                   </div>
				                </div>
				                <div class="form-group">
				                   <div class="col-md-5"><?php echo $tr->translate("INTEREST_RATE");?>/<?php echo $tr->translate("YEAR");?></div>
				                   <div class="col-md-7 col-sm-7"><input class="fullside" dojoType="dijit.form.NumberTextBox" onkeyup="checkScheduleOption();" type="text" name="interest_rate" id="interest_rate" value="<?php echo $client['interest_rate']; ?>" /></div>
				                </div>
				                <div class="form-group">
				                   <div class="col-md-5"><?php echo $tr->translate("TERM_BORROW");?></div>
				                   <div class="col-md-7 col-sm-7 col-xs-12"><input class="fullside" dojoType="dijit.form.NumberTextBox" onkeyup="checkScheduleOption();" type="text" name="total_duration" id="total_duration" value="<?php echo $client['total_duration']; ?>" /></div>
				                </div>
			        		</div>
			        		<div class="col-md-4">
			        			<div class="form-group">
				                   <div class="col-md-5"><?php echo $tr->translate("AMOUNT_GRAICE_PARIOD");?></div>
				                   <div class="col-md-7 col-sm-7 col-xs-12"><input  dojoType="dijit.form.NumberTextBox" type="text" name="fixed_payment" id="fixed_payment"  /></div>
				                </div>
				                <div class="form-group">
				                   <div class="col-md-5"><?php echo $tr->translate("FIRST_PAYMENT");?></div>
				                   <div class="col-md-7 col-sm-7 col-xs-12"><input constraints="{datePattern:'dd/MM/yyyy'}" onchange="calCulateEndDate();"   dojoType="dijit.form.DateTextBox" type="text" name="first_payment" id="first_payment" value="<?php echo $client['first_payment'];?>" /></div>
				                </div>
				                <div class="form-group">
				                   <div class="col-md-5"><?php echo $tr->translate("LIFE_LOAN");?></div>
				                   <div class="col-md-7 col-sm-7 col-xs-12"><input constraints="{datePattern:'dd/MM/yyyy'}"  dojoType="dijit.form.DateTextBox" type="text" name="end_date" id="end_date"  value="" /></div>
				                 </div>
				                 <div class="form-group">
				                   	<div class="col-md-5"><?php echo $tr->translate("paid_receivehouse");?></div>
				                   	<div class="col-md-7 col-sm-7 col-xs-12">
					                	<select name="paid_receivehouse" id="paid_receivehouse" dojoType="dijit.form.FilteringSelect">
									    	<option value="0" label="បង់បញ្ចាប់ពេលប្រគល់ផ្ទះ"><?php echo $tr->translate("RECEIVED_PROPERTY");?></option>
										    	<option value="1" label="យកតាមកាលបរិច្ឆេទបង់"><?php echo $tr->translate("BY_SCHEDULE_DATE");?></option>
										</select>
									</div>
				                </div>
				                <div class="form-group">
				                	<div class="col-md-12">
				                		<input type="hidden" name="id" id="id" value="<?php echo $this->id;?>" />
		                    	        <input type="hidden" name="identity" id="identity" value="<?php echo $str;?>" />
				               			<input type="button"  name="btn_save" label="<?php echo $tr->translate('GO_BACK');?>" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon"/>
				               			<input type="button" onclick="addPreviewLoan();" value="បោះពុម្ពតារាង" name="preview_submit" label="<?php echo $tr->translate('PREVIEW');?>" id="preview_submit" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
				               			<input type="submit" value="រក្សាទុក & ចាកចេញ"  id="btn_save_close" name="btn_save_close" label="<?php echo $tr->translate('SAVECLOSE');?>" id="submitButton_Save" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/>
				                	</div>
				                </div>
			        		</div>
			        	</div>
			        </div>
			     </div>
			</td>
		</tr>
	</table>
	</form>
</div>
</div>
<div class="dijitHidden">
	<style>
	.print tr td{
		padding:5px 2px; 
	}
	</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់'" id="lbl_schedule" style="width: 28cm !important;">
		<div id="rpt_print" class="print" style="text-align: center;">
			<div id="t_amountmoneytype" name="t_amountmoneytype">
			</div>
		</div>
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dojo.html");
	dojo.require("dijit.Dialog");
	dojo.require("dojo.number");

url_previewloan = '<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'addschedultest')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()){
		if(dijit.byId('payment_id').get('value')==3){
			return false;
		}
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data){
					temp='';	
					fund_title=0;thead='';fund_title=0;
						temp='<table class="collape tablesorter" style="font-size:13px; width:1000px !important; " id="table">'
						temp+='<tr style="background:#ccc;"><th><?php echo $tr->translate("NUM");?></th>';
						temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						principal_permonth=0;total_interest=0;total_payment_after=0;
						for(i=0;i<data.length;i++){
							principal_permonth=principal_permonth+parseFloat(data[i].principal_permonth);
							total_interest=total_interest+parseFloat(data[i].total_interest);
							total_payment_after=total_payment_after+parseFloat(data[i].total_payment_after);
					      	r++;
						  	temp+='<tr><td align="center">'+r+'</td>';
						  	var myDate = new Date(data[i].date_payment);
						  	d = new Date(data[i].date_name);
						  	temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						  	temp+='<td>'+dojo.number.format(data[i].begining_balance,2)+'</td>';
						  	temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						  	temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						  	temp+='<td><b>'+dojo.number.format(data[i].total_payment_after,2)+'<b></td>';
						  	temp+='<td><b>'+dojo.number.format((data[i].ending_balance),2)+'<b></td>';
						 }
						  temp+='<tr><td align="right" colspan="3" style="border-left:1px solid #fff;border-bottom:1px solid #fff;">&nbsp;សរុប -Total</td>';
						  temp+='<td>'+dojo.number.format(principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(total_payment_after,2)+'<b></td>';
						  temp+='<td></td>';
						temp+='</table>';
					dojo.byId('t_amountmoneytype').innerHTML = temp;
					dijit.byId("lbl_schedule").show();
			},
			error: function(response, ioArgs) {
			}
	   });
	}
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function calCulateEndDate(){
	amount_period = 1;
	if(dijit.byId("payment_id").get('value')==4){amount_period=<?php echo $install_month;?>;}
	amount_date = dijit.byId('total_duration').get('value')*amount_period;
	release_date = dijit.byId("first_payment").get('value');
	if(isNaN(amount_date)){
	}else{
		var a = new Date(release_date);
		month = a.getMonth()+amount_date;
		mm = month%12;
		year = parseInt(month/12);
		 var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear()+year;
		var epx_date = y + '-'+ mm + '-'+dd ;
        payment_option = dijit.byId('payment_id').attr('value');
		if(payment_option==2){
		}else{
			dijit.byId('end_date').attr('value',epx_date);	
		}
    }
}
var steppayoption = '<?php echo $this->stepoption;?>';
col=<?php echo $recordstart;?>;
no=<?php echo $recordstart;?>;
title=0;temp='';
function addRow(){
	temp='';
			col++;no++;
			template='';
			if(title!=1){    
				tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
				tmp+='<tr id="head-title" class="head-td" style="background:#eee; font-size: 14px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
				tmp+='</table>';
				temp+='<th width="26px"><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				title=1;
			}else{
			}
			indexs = col-1;
			indexs = col-1;
			if(indexs==0){
				epx_date = dijit.byId("first_payment").get('value');
			}else{
				epx_date = dijit.byId("date_payment"+indexs).get("value");
			}
			var a = new Date(epx_date);
			mm = a.getMonth()+2;
			mmm = a.getMonth()+3;
			var dd = a.getDate();
			 if(dd<10){
				 dd = "0"+dd;
			}
			if(mm<10){
				 mm = "0"+mm;
			}
			var y = a.getFullYear();
			var epx_date = y+'-'+ mm + '-'+dd ;
			var first_date = y+'-'+ mmm + '-'+dd ;
				template+='<td style="width:25px;" align="center"><span style="width:26px !important;display: block;"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></span></td>';
				template+='<td style="width:26px;" align="center"><span style="width:26px !important;display: block;">'+col+'</span></td>';
				template+="<td style='width:88px;'><input required='1' onkeyup='calculatePayment("+col+",1)' class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.NumberTextBox' id='principal_permonth_"+col+"' name='principal_permonth_"+col+"' /></td>";
				template+='<td style="width:62px;"><input onkeyup="calculatePayment('+col+',2)" class="fullside" type="text" data-dojo-type="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';
				template+='<td style="width:62px;"><input class="fullside" type="text" data-dojo-type="dijit.form.NumberTextBox" id="percent_agreement'+col+'" name="percent_agreement'+col+'" /></td>';
				template+='<td style="width:85px;"><input class="fullside" type="text"  data-dojo-type="dijit.form.NumberTextBox" id="total_interest_'+col+'" name="total_interest_'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td style="width:78px;"><input readOnly  class="fullside" type="text"  data-dojo-type="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td style="width:100px;"><input onchange="setFirstPayment('+col+');" class="fullside" type="text" class="fullside"  constraints='+'{datePattern:"dd/MM/yyyy"}'+' required="1" value="'+epx_date+'" data-dojo-type="dijit.form.DateTextBox" id="date_payment'+col+'" name="date_payment'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td style="width:100px;"><input class="fullside"" class="fullside" type="text" data-dojo-type="dijit.form.NumberTextBox" id="paid_principal'+col+'" name="paid_principal'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td style="width:103px;"><input class="fullside" class="fullside" type="text"  data-dojo-type="dijit.form.NumberTextBox" id="interest_paid'+col+'" name="interest_paid'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td style="width:185px;"><input class="fullside" readOnly class="fullside" type="text" data-dojo-type="dijit.form.NumberTextBox" id="paid_amount_'+col+'" name="paid_amount_'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+="<td style='width:100px;'><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='paid_date_"+col+"' name='paid_date_"+col+"' /></td>";
				template+='<td style="width:120px;"><select class="fullside" id="payment_option'+col+'" name="payment_option'+col+'" dojoType="dijit.form.FilteringSelect"><option value="0">មិនទាន់គ្រប់</option><option value="1">បង់ដាច់</option></select></td>';
				template+='<td width="140px"><select class="fullside" dojoType="dijit.form.FilteringSelect" id="pay_with'+col+'" name="pay_with'+col+'" >'+steppayoption+'</select></td>';
				
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;font-size: 14px; width:100%;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
			dijit.byId('first_payment').attr("value",first_date);
			setFirstPayment(col);
}
function calculatePayment(key,reverse=1){
	principal_permonth= dijit.byId("principal_permonth_"+key).get("value");
	sold_price= dijit.byId("price_sold").get("value");
	if(reverse==2){
		principal_percent= dijit.byId("percent"+key).get("value");
		principal_permonth = parseFloat(sold_price)*parseFloat(principal_percent)/100;
		principal_permonth = parseInt(principal_permonth);
		dijit.byId("principal_permonth_"+key).attr("value",principal_permonth);
		dijit.byId("percent_agreement"+key).attr("value",principal_percent);
	}else{
		principal_percent = principal_permonth/sold_price*100;
		dijit.byId("percent"+key).attr("value",principal_percent);
		dijit.byId("percent_agreement"+key).attr("value",principal_percent);
	}
	total_interest= dijit.byId("total_interest_"+key).get("value");
	total_interest = isNaN(total_interest)?0:total_interest;
	total_payment = principal_permonth+total_interest;
	dijit.byId("total_payment"+key).attr("value",total_payment);
	calCulateSchedulePayment();
	calCulateEndDate();
}
function calCulateAmount(index,revers=1){
	balance = dijit.byId('price_sold').get('value');
	if(revers==1){//% to value
	    percent = dijit.byId('percent'+index).get('value');
	    amount_payment = balance*percent/100;
	    dijit.byId('total_payment'+index).attr('value',amount_payment);
	    dijit.byId('principal_permonth_'+index).attr('value',amount_payment);
	    
   }else{//value to %
	   amount_payment =  dijit.byId('total_payment'+index).get('value');
	   percent = amount_payment*100/balance;
	   dijit.byId('percent'+index).attr('value',percent);
     }
	calCulateSchedulePayment();
	 if(dijit.byId('percent'+index).get('value')>100){
		 alert("តម្លៃត្រូវបង់មិនអាចធំជាង ១០០ ភាគរយបានទេ !");
		 dijit.byId('percent'+index).focus();
     }
	 calCulateEndDate();
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var txt;
	var r = confirm("តើលោកអ្នកចង់លុបទិន្នន័យនេះឫទេ?");
	if (r == true) {
		paid_amount = dijit.byId('paid_amount_'+index).get('value');
		if(paid_amount>0){
			alert("ទិន្នន័យបានបង់រួចហើយ មិនអាចលុបបានទេ !");
		}else{
			var strings = arrays.join(',');
			$('#identity').val(strings);
			$("#row"+index).remove();
			calCulateSchedulePayment();
		}
	}
}
function checkScheduleOption(){
	document.getElementById('hidden_lastpayment').style.display='none';
	dijit.byId("install_type").set("readOnly",true);
	method_id = dijit.byId('payment_id').get('value');
	amount_principal = dijit.byId('price_sold').get('value');	
	debt_amount = dijit.byId('total_duration').get('value')*<?php echo $install_month;?>;
	if(method_id==3 || method_id==6){
		debt_amount = dijit.byId('total_duration').get('value');
	}
	if(method_id==4 || method_id==7){
		dijit.byId("install_type").set("readOnly",false);
		if(method_id==7){
			document.getElementById('hidden_lastpayment').style.display='flow-root';
		}
		calCulateFixedPeriod();	
		}else {
			dijit.byId('fixed_payment').attr('value',0);
			dijit.byId('fixed_payment').set("readOnly",true);
		if(method_id==1){//booking
		}else if(method_id==2){//payoff
		}else if(method_id==3){//times
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			amount_principal=dijit.byId('price_sold').get('value');
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(0);
			if(debt_amount!=0){
				dijit.byId('fixed_payment').attr("value",total_collect);
			}
			if(dijit.byId('interest_rate').get('value')==0){
				dijit.byId('interest_rate').attr("value",0);}
				dijit.byId('interest_rate').set("readOnly",false);
		}else if(method_id==5){//times
			if(dijit.byId('interest_rate').get('value')==0 ){
				dijit.byId('interest_rate').attr("value",0);
			}
			dijit.byId('interest_rate').set("readOnly",true);
		}
		else if(method_id==6){//times			
			if(dijit.byId('total_duration').get('value')==12){
				dijit.byId('total_duration').attr('value',12);
			}			
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(2);
			if(isNaN(total_collect)){
				total_collect=0;
			}
			dijit.byId('fixed_payment').attr("value",total_collect);
			if(dijit.byId('interest_rate').get('value')==0){
			dijit.byId('interest_rate').attr("value",0);}
			dijit.byId('interest_rate').set("readOnly",false);
		}
	}
	calCulateEndDate();
}
function calCulateSchedulePayment(){
	var total_amount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	if(rowId!=''){
	for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('principal_permonth_'+rowIDArray[n]).get('value'));
			if(n==0){ 
			}
			if(isNaN(total_amountpayment)){
				total_amountpayment = 0;
			}
			total_amount = total_amount+ total_amountpayment;
			if(n+1==rowIDArray.length){
				setFirstPayment(n+1);
			}
		}
	}
	dijit.byId('total_installamount').attr('value',total_amount);
	if(dijit.byId("payment_id").get("value")==3){
		dijit.byId("total_duration").attr("value",rowIDArray.length);
	}
	calCulateFixedPeriod();
}
function setFirstPayment(index){
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	if(rowId!=''){
		for(var n = 0; n < rowIDArray.length; n++) {
			if(n+1==rowIDArray.length){
				end_payment = dijit.byId("date_payment"+rowIDArray[n]).get("value");
				var a = new Date(end_payment);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var first_date = y+'-'+ mm + '-'+dd ;
				dijit.byId("first_payment").attr("value",first_date);
			}
		}
	}
}
function calCulateFixedPeriod(){
	
	var total_paid_install = dijit.byId('total_installamount').get('value');
	var last_payment = dijit.byId('last_payment').get('value');
	last_payment = dijit.byId('last_payment').get('value');
	if(isNaN(last_payment)){
		last_payment = 0;
	}

	
	if(total_paid_install == 0){
		amount_principal = dijit.byId('price_sold').get('value')-last_payment;
	}else{
		amount_principal = dijit.byId('price_sold').get('value')-dijit.byId('total_installamount').get('value')-last_payment;
	}
		
	dijit.byId('fixed_payment').set('readOnly',false);
	collect_amount = 1;
	debt_amount = dijit.byId('total_duration').get('value')*<?php echo $install_month;?>;
	
	term = (debt_amount)/(collect_amount);
	interest_rate=dijit.byId('interest_rate').get('value')/12/(100);
	if(interest_rate==0){
		amount_payment = parseFloat(amount_principal/debt_amount);
		amount_payment = amount_payment.toFixed(0);
		if(amount_payment=='Infinity' || amount_payment=='NaN'){amount_payment=0;}
	}else{
		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		amount_payment = amount_payment.toFixed(0);
		if(isNaN(amount_payment)){
			amount_payment=0;
		}
	}	
	dijit.byId('fixed_payment').attr('value',amount_payment);
	dijit.byId('total_remain').attr('value',amount_principal);
}
function calculatePaid(key){
	principal_permonth= dijit.byId("paid_principal"+key).get("value");
	principal_permonth = isNaN(principal_permonth)?0:principal_permonth;
	interest_paid= dijit.byId("interest_paid"+key).get("value");
	interest_paid = isNaN(interest_paid)?0:interest_paid;
	paid_amount = interest_paid+principal_permonth;
	dijit.byId("paid_amount_"+key).attr("value",paid_amount);	
}
function calculateDiscount(){
	total_sold = dijit.byId('price_before').get('value');
	discount = dijit.byId('discount_amount').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	if(isNaN(discount)){
		discount=0;
	}
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	discount_percent = total_sold*discount_percent/100;
	total_sold = total_sold-discount_percent-discount;
	dijit.byId('price_sold').attr('value',total_sold);
}
</script>