<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('SALE_CANCEL'));
	$frm = $this->frm_loan;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.Textarea");
</script>
 <div class="card">
	<div class="card-content collapse show">
		<form id="add_cancel" action="<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			 <script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					dijit.byId('saveclose').set('disabled',true);
    				return true;
   				}else {
    				return false;
  			 	}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-edit" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SALE_CANCEL');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('branch_id');?>
	                    	<?php echo $frm->getElement('old_sale_id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CLIENT_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="sale_client" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SALE_NO");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="sale_no" ><?php echo $frm->getElement('property_id')?>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-8 col-sm-8 col-xs-12">
	             	<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-user" aria-hidden="true"></i> <?php echo $tr->translate("INFO_INDILOAN");?> 
		                   </label>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SOLD_PRICE");?> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                    	<?php echo $frm->getElement('price_sold')?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_TYPE");?> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                    	<?php echo $frm->getElement('schedule_opt')?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("PAYMENT_INFO");?> 
		                   </label>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BUY_DATE");?> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
							<?php echo $frm->getElement('sold_date')?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INSTALLMENT_PAID");?> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
							<?php echo $frm->getElement('installment_paid')?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAID_AMOUNT");?> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                    	<?php echo $frm->getElement('paid_amount')?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BALANCE");?> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                    	<?php echo $frm->getElement('balance')?>
		                   </div>
		                </div>
		             </div>
		             <div class="col-md-6 col-sm-6 col-xs-12">
		          		<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CANCEL_DATE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('cancel_date');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("REASON");?> :
	                   </label>
	                </div>
	                 <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                   		<input style=" min-height: 60px; font-family:inherit;" dojoType="dijit.form.Textarea" class="fullside" id="reason" name="reason" value="" type="text">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-map" aria-hidden="true"></i> <?php echo $tr->translate("ADDEXPENSE");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RETURN_MONEY_BACK");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('return_back')?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("EXPENSE_DATE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('expense_date')?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CATEGORY");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="income_category" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("STATUS");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('status_using')?>
	                   </div>
	                </div>
		           </div>
	            </div>
	        </div>
	    	<div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               		   <input type="submit" name="saveclose"​​ value="រក្សាទុក​  + ចាកចេញ" label="<?php echo $tr->translate('GO_EDIT')?>" id="submitBtn" dojoType="dijit.form.Button"
				 		  iconClass="dijitEditorIcon dijitEditorIconSave"/>
				 	   <input type="button" label="<?php echo $tr->translate("PREVIEW")?>" name='print' value=''print'' dojoType="dijit.form.Button"
				 		   iconClass="dijitIconNewTask" onClick="printSave('<?php echo $this->row['reciept'];?>');displayNone();" />
    			</div>
    		</div>
		</form>
	</div>
</div>
<table>
<tr>
</tr>
</table>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_category" >
		<form style="background-color: buttonface; width:100%;" id='frm_category' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_CATEGORY');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('EXPENSE_TITLE');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="cate_name" name="cate_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('STATUS');?></td>
									<td>
										<select name="status_j" id="status_j" dojoType="dijit.form.FilteringSelect"   class="fullside">
		    								<option value="1" label="active"><?php echo $tr->translate("ACTIVE");?></option>
		    								<option value="0" label="deactive"><?php echo $tr->translate("DACTIVE");?></option>
										</select>
									</td>
								</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="<?php echo $tr->translate("CANCEL");?>" id="close" name="close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="<?php echo $tr->translate("GO_SAVE");?>" id="save" name="save" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addCategory();"/>
									</td>
								</tr>
							</table>
					</fieldset>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<div class="dijitHidden" style="width: 23cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:22cm;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="print_expense" >
		<div id="divPrint" style="width: 100% !important; height: 13cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-weight: bold;font-size: 22px;}
				.value{ font:14px 'Khmer OS Battambang';border: 1px solid #000; height: 28px; width: 100%;margin-right:5px; display: block;
						line-height: 28px;
					    text-align: center;
						}
				.print tr td{
					padding:2px 2px; 
				}
			   .khmerbold{font:16px 'Khmer OS Battambang';}
			   .khmer{font:16px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;}
			   .noted{
					white-space: pre-wrap;     
					word-wrap: break-word;      
					word-break: break-all;
					white-space: pre;
					font:12px 'Khmer OS Battambang';
					border: 1px solid #000;
                    line-height:20px;font-weight: normal !important;
                }
			</style>	
			<table width="100%" style="white-space: nowrap;font-size:16px;margin-top: 10px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer OS Muol Light';white-space:nowrap;">
							<tr>
								<td width="25%" id="projectlogo">
									<img style="height:80px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:18px 'Khmer OS Muol Light';" valign="top" align="center"><u><span style=" font-family: Arial Black;font-family:'Khmer OS Muol Light';">បង្កាន់ដៃចំណាយ</span></u>
									<div style="line-height:10px;"><strong style="font-size: 16px;">PAYMENT VOUCHER</strong></div>
								</td>
								<td width="25%"></td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table  width="100%" style="white-space: nowrap;font-size:14px;margin-top:-5px;" class="print" cellspacing="3px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="37%" ></td>
					<td width="15%" ></td>
					<td width="13%" ></td>
					<td width="10%" ></td>
					<td width="20%" ></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">គម្រោង</td>
                    <td><strong><label id="lb_branch" class="value"></label></strong></td>
				    <td class="one khmerbold">&nbsp;&nbsp;&nbsp;វិក័យប័ត្រលេខ</td>
                    <td colspan="3"><strong><label id="lb_invoice" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">ប្រភេទចំណាយ</td>
					<td ><strong><label id="lb_income_category" class="value"></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ថ្ងៃចំណាយ</td>
				    <td colspan="3"><strong><label id="lb_date" class="value"></label></strong></td>
				</tr>
				<tr>
					<td class="one khmerbold">ចំណាយសរុប</td>
					<td><strong><label id="lb_total_amount" class="value"></label></strong></td>
					<td class="one khmerbold" rowspan="2">&nbsp;&nbsp;&nbsp;សម្គាល់</td>
				    <td colspan="3" rowspan="2" align="center" style="border: 1px solid #000 !important;text-align: left;" class="noted"><label style="white-space: nowrap;text-align: center; " id="lb_description" ></label></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">ពណ៌នាចំនាយ</td>
				    <td><label id="lb_income_title" class="value"></label></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td class="khmerbold" style="line-height: 14px;"colspan="4"  align="center" >&nbsp;&nbsp;<span style=" font-family: Arial Black;font-family:'Khmer OS Muol Light';"></span></td>
				    <td colspan="2" class="khmerbold" style="line-height: 14px;" align="center" ><span style=" font-family: Arial Black;font-family:'Khmer OS Muol Light';">ស្នាមមេដៃអ្នកប្រគល់</span></td>
				</tr>
				<tr height="30px">
					<td colspan="6"></td>
				</tr>
				<tr style="white-space: nowrap;" >
					<td class="one khmerbold" colspan="4" align="center" valign="bottom">
					</td>
				    <td class="one khmerbold" colspan="2" align="center" valign="bottom">&nbsp;
			  			<h4 style="font-weight:normal; padding-right: 5px ! important;margin-bottom: -10px  !important;">
			              <?php 
			                   $session_user=new Zend_Session_Namespace('authinstall');
					           $last_name=$session_user->last_name;
					           $username = $session_user->first_name;
					           echo $last_name." ".$username;?>
					    </h4>  
					</td>
				</tr>
				<tr style="line-height: 20px;font-size: 11px;">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;font-family:'Khmer OS Battambang'">សំគាល់ ៖</span>
					</td>
					<td colspan="5" style="font-family:'Khmer OS Battambang';">
						<span style="font-size: 10px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 10px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)"></td>
				</tr>
				<tr style="line-height: 15px;">
					<td colspan="6" >
						<?php echo $this->footer;?>
					</td>
				</tr>
			</table>
		</div>
		<table>
			<tr>
				<td>
					<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
					<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
					type="button" onclick="doPrint();">បោះពុម្ភ/Print</button>
				</td>
			</tr>
		</table>
		<div id="divPrint1" style="width: 21cm !important; height: 12cm ; padding: 0px; margin: 0px;">
			<?php if($this->data['showreceipt']>1){?>
				<div style="border:2px dashed #000; vertical-align: middle;margin:20px 0px 40px 0px"></div>
			<?php }?>
			<div id="printblog2"></div>
		</div>
	</div>
</div>
<script type="text/javascript">
var sale_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var sale_client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var income_category_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->all_category));?> );

dojo.ready(function(){
	try{
		new dijit.form.FilteringSelect({
		store: sale_store,
		autoComplete: false,
		queryExpr: "*${0}*",  
		required: false,		           
		name: "sale_no",
		id: "sale_no",
		value: "<?php echo $this->row['sale_id'];?>",
		searchAttr: "name",
		class: 'fullside',
			onChange: function() {
				getLandAndClientDetail();
			}
		}, "sale_no");
		new dijit.form.FilteringSelect({
			store: sale_client_store,
			autoComplete: false,
			queryExpr: "*${0}*",  
			required: false,		           
			name: "sale_client",
			id: "sale_client",
			value: "<?php echo $this->row['sale_id'];?>",
			searchAttr: "name",
			class: 'fullside',
				onChange: function() {
					getLandAndClientDetail("2");
				}
			}, "sale_client");

		new dijit.form.FilteringSelect({
			store: income_category_store,
			autoComplete: false,
			queryExpr: "*${0}*",                      
		    id: "income_category",
		    name: "income_category",  
		    class: 'fullside',  
		    value:'<?php echo $this->expense_id;?>',
		    placeHolder:"<?php echo $tr->translate("SELECT_CATEGORY");?>", 
		    onChange: function() {          
			   	fa_job = dijit.byId('income_category').get('value');
			    if(fa_job==-1){
			   	 dijit.byId("popup_category").show();
			    }
		    } 
		}, "income_category");
		getSaleClie();
		getSaleNo();
		getBranchinfo();
		
		}catch(e){
		}
});

var url_add_category = '<?php echo $this->url(array("module"=>"loan","controller"=>"expense","action"=>"add-category")); ?>';
function addCategory(){
	if(dijit.byId('frm_category').validate()){
		dijit.byId('save').set('disabled',true);
			dojo.xhrPost({
				url:url_add_category,
				form: dojo.byId("frm_category"),
				handleAs:"json",
				load: function(data) {
					var Itemmake = { 
			    		id: data,
				        name: dijit.byId('cate_name').get('value')
				    };
			 		addDataToSelectbox(dijit.byId('income_category'), income_category_store, Itemmake, data);
				    dijit.byId('frm_category').reset();
				    dijit.byId("popup_category").hide();
				    dijit.byId('save').set('disabled',false);
				},
				error: function(err) {
				}
			});
	}
}

var oldbranch='<?php echo $this->row['branch_id'];?>';
var oldsale='<?php echo $this->row['sale_id'];?>';
var	url_getSaleNo = '<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'get-sale'));?>';
	function getSaleNo(){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id==0){
			return false;}
		dojo.xhrPost({
			url:url_getSaleNo,	
			content:{ 
				'branch_id': branch_id
			},
			handleAs:"json",
			load: function(data) {	
				sale_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('sale_no').set('store', sale_store);
			    if(oldbranch==branch_id){
			    dijit.byId('sale_no').attr('value',oldsale);
			    }
			},
			error: function(err) {
			}
		});
	}
	var	url_getSaleClien = '<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'get-saleclie'));?>';
	function getSaleClie(){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id==0){
			return false;}
		dojo.xhrPost({
			url:url_getSaleClien,	
			content:{ 
				'branch_id': branch_id , 'sale_id':oldsale,
				'is_completed':1
			},
			handleAs:"json",
			load: function(data) {	
				sale_client_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('sale_client').set('store', sale_client_store);
			    getBranchinfo();
			},
			error: function(err) {
			}
		});
	}
	var url_land= '<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'get-info'));?>';
	function getLandAndClientDetail(inds){
		if(inds == "2"){
			sale_id = dijit.byId('sale_client').get('value');
			dijit.byId('sale_no').set("value",sale_id)
		}else{
			sale_id = dijit.byId('sale_no').get('value');
			dijit.byId('sale_client').set("value",sale_id);
		}
		dojo.xhrPost({
			url:url_land,	
			content:{ 
			    'sale_id':sale_id
			},		    
			handleAs:"json",
			load: function(data) {
				dijit.byId('installment_paid').attr('value',data.installment_paid);
				total_principal= data.total_principal;
				if(isNaN(total_principal) || total_principal==null){total_principal=0;}
			    paid_amount = data.paid_amount;
				if(isNaN(paid_amount) || paid_amount==null){paid_amount=0;}
				total_principal = parseFloat(total_principal);
				dijit.byId('paid_amount').attr('value',total_principal);
				balance = data.price_sold-total_principal;
				dijit.byId('balance').attr('value',balance);
				dijit.byId('price_sold').attr('value',data.price_sold);
				dijit.byId('schedule_opt').attr('value',data.payment_id);
				dojo.byId("property_id").value = data.property_id;
				dijit.byId('sold_date').attr('value',data.create_date);
			},
			error: function(err) {
			}
		});
	}
function checkreturnAmount(){
		paid_amount = dijit.byId('paid_amount').get('value');
		return_back = dijit.byId('return_back').get('value');
		sale_id = dijit.byId('sale_client').get('value');
		if(sale_id==''){
			alert('សូមេជ្រើសរើសអតិថិជនជាមុនសិន!');
			dijit.byId('sale_client').focus();
			dijit.byId('return_back').attr('value',0);
			return false;
		}
		if(return_back>paid_amount){
			alert('ប្រាក់ដែលប្រគល់ត្រឡប់់មិនអាចធំជាងប្រាក់ដែលបានបង់នោះទេ!');
			dijit.byId('return_back').attr('value',paid_amount);
		}
}
function printSave(new_invoice_no){
				branch_id = dijit.byId('branch_id').get('value');
				if(branch_id==0){
				alert('Select branch');
				dijit.byId('branch_id').focus();
				return false;
				}
				total_amount = dijit.byId('return_back').get('value');
				if(isNaN(total_amount)){
				alert('Income can not be null');
				dijit.byId('return_back').focus();
				return false;
				}
				if(new_invoice_no==''){
					getInvoiceNo(1);
				}else{
					dojo.byId("lb_invoice").innerHTML = new_invoice_no;
				}
				
				dojo.byId("lb_branch").innerHTML = dijit.byId("branch_id").attr('displayedValue');
				dojo.byId("lb_income_category").innerHTML = dijit.byId("income_category").attr('displayedValue');
				dojo.byId("lb_income_title").innerHTML = dijit.byId("sale_client").attr('displayedValue');
				dojo.byId("lb_total_amount").innerHTML = currencyFormat(dijit.byId("return_back").get('value'));
				
				date_payment = '<?php echo date("Y-m-d");?>';
				var a = new Date(date_payment);
				mm = a.getMonth()+1;
				var dd = a.getDate();
				if(dd<10){
				dd = "0"+dd;
				}
				month = returnMOnth(mm);
				var y = a.getFullYear();
				var date_payment = dd +'-'+month+'-'+y ;
				
				dojo.byId("lb_date").innerHTML = date_payment;
				dojo.byId("lb_description").innerHTML = $("#reason").val();
				dijit.byId("print_expense").show();
			}
			function currencyFormat(num) {
			    return "$ " + num.toFixed(2).replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,")
			}
			function displayNone(){
				document.getElementById('divPrint1').style.display="none";
			}
			var url_get_invoice = '<?php echo $this->url(array('module'=>'loan','controller'=>'expense','action'=>'get-invoice-no')); ?>';
			function getInvoiceNo(condition){
				branch_id = dijit.byId('branch_id').get('value');
				if(branch_id==0){
					branch_id=1;
				}
				dojo.xhrPost({
					url:url_get_invoice,
					content:{
						'branch_id':branch_id
						},
					handleAs:"json",
					load: function(data) {
						if(condition==1){
							printSave(data);
						}
					},
					error: function(err) {
					}
				});
			}
			function returnMOnth(monthnum){
				var month = new Array();
				month[1] = "Jan";
				month[2] = "Feb";
				month[3] = "Mar";
				month[4] = "Apr";
				month[5] = "May";
				month[6] = "Jun";
				month[7] = "Jul";
				month[8] = "Aug";
				month[9] = "Sep";
				month[10] = "Oct";
				month[11] = "Nov";
				month[12] = "Dec";
				return month[monthnum];
			}
			function doPrint() {
				dojo.byId("printblog2").innerHTML = dojo.byId('divPrint').innerHTML;
				window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML <?php if($this->data['showreceipt']>1){ ?>+ dojo.byId('divPrint1').innerHTML<?php }?>;
			    window.frames["print_frame"].window.focus();
			    window.frames["print_frame"].window.print();
			    printSubmit();
			    hideDialog();
			}
			function printSubmit(){
				 $('#add_cancel').submit();
			}
			function getBranchinfo(){
				var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
				branch_id = dijit.byId('branch_id').get('value');
				if(branch_id==""){
					return false;
				}
				dojo.xhrPost({
				    url: url_submit,	
				    content:{ 
					    'branch_id':branch_id
					},	
					load: function(data) {
						var arr = JSON.parse(data);
						var imagesUrl = '<img class="view" style="height:80px; max-width: 100%;" src="<?php echo $this->baseUrl()."/images/projects/"?>'+arr.logo+'" />';
						document.getElementById('projectlogo').innerHTML = imagesUrl;
					},
					error: function(e) {
					}
				});
			}
</script>