<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('BAD_LOAN'));
 $frm = $this->frm_cancel;
 $frmser = $this->frm_search;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">	<table>
				<table>	
					<tr>
						<td><?php echo $frm->getElement('adv_search');?></td>
						<td><?php echo $frm->getElement('branch_id_search');?></td>
						<td><?php echo $frm->getElement('client_name');?></td>
						<td><?php echo $frm->getElement('from_date_search');?></td>
						<td><?php echo $frm->getElement('to_date_search');?></td>
						<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
					</tr>
				</table>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
