<?php	
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$this->headTitle($tr->translate('SET_COMMISSION_AGENCY'));
	echo $this->headTitle();
?>
<style>
.fullside50{ width:48%;}
.hover:hover{background: #eee !important;}
</style>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
</script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id = dijit.byId('branch_id').get('value');
				if(branch_id=='' || branch_id==-1){
					infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH")?>!');
					dijit.byId('branch_id').focus();
					return false;
				}
				
				staff_id = dijit.byId('staff_id').get('value');
				if(staff_id=='' || staff_id==-1){
					infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_STAFF")?>!');
					dijit.byId('staff_id').focus();
					return false;
				}
				
				var identity = $('#identity').val();
				if(identity==''){
					infoMessageAlert("<?php echo $tr->translate("PLEASE_SET_SALE_COMMISSION");?>");
					dijit.byId("loan_number").focus();
					return false;
				}

				loadingBlock();
				dijit.byId('savenew').set('disabled',true);
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-list" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SET_COMMISSION_AGENCY');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-user" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("AGENCY_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branch_id')?>
									   </div>
									</div>
									 <div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CO_NAME");?>  :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="staff_id" />
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	    		</div>
	    		<div class="col-md-8 col-sm-8 col-xs-12">
					 <div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-tasks" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INFO_INDILOAN");?></p>
										</div> 
									</div>
									<div class="form-group" style="background: #d8e0e2;padding: 5px 15px;margin: 0;border: solid 1px #697996;border-radius: 2px;margin-top: 10px;">
										<div class="form-group">
										   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("INFO_INDILOAN");?> :
										   </label>
										   <div class="col-md-7 col-sm-7 col-xs-12">
												<input id='loan_number' />
												<input type="hidden" name="identity" id="identity"  value="" >
										   </div>
										</div>
									</div>
									<div  id="showrecord"></div>
									<div id='data_table_loan_haspay' name='data_table_loan_haspay' style="white-space: nowrap;"></div>
								</div>
							</div>
						</div>
					</div>
	    		</div>
	    	</div>
	    	<div class="col-md-4 col-sm-4 col-xs-12">
	    	</div>
	    	<div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" class="button-class button-danger" iconClass="glyphicon glyphicon-repeat" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk"  label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button"/>
    			</div>
    		</div>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_staff" data-dojo-props="title:'<?php echo $tr->translate("ADD_STAFF")?>'" >
		<form style=" width:100%;" id='frm_staff' dojoType="dijit.form.Form" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<div class="card-box">
	    		<div class="col-md-12 col-sm-12 col-xs-12">
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PARENT");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="parent_id" />
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NAME_KH");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="kh_name" name="kh_name" value="" type="text">
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SEX");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input type="hidden" name="branch_id_pop" id="branch_id_pop" dojoType="dijit.form.TextBox" />
							<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="sex" name="sex"  type="text">
								<option value="1"><?php echo $tr->translate("MALE");?></option>
								<option value="2"><?php echo $tr->translate("FEMALE");?></option>
							</select>
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox" />
	                   </div>
	                </div>
					<div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input type="text" name="note_pop" id="note_pop" class="fullside" dojoType="dijit.form.TextBox" />
	                   </div>
	                </div>
					
				</div>
			</div>
			 <div class="clearfix"></div>
			 <div class="card-box">
				<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
					<input type="button" class="button-class button-danger" iconClass="glyphicon glyphicon-repeat" value="ចាកចេញ" label="<?php echo $tr->translate("CANCEL");?>" id="close" name="close" dojoType="dijit.form.Button"  onclick="hideDialog1();"/>
					<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk"  value="save" label="<?php echo $tr->translate("GO_SAVE");?>" id="save" name="save" dojoType="dijit.form.Button"  onclick="addStaff();"/>
			   </div>
			</div>
		</form>
	</div>
</div>



<script type="text/javascript">	
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

var sale_store  = getDataStorefromJSON('id','name', null );
var staff_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
require(["dojo/ready"], function(ready){
	 ready(function(){

		 getAllStaffByBranch();
		 var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllStaffByBranch();
		});

	  });
	  
	  new dijit.form.FilteringSelect({
		store: sale_store,
		required: false,		           
		name: "loan_number",
		id: "loan_number",
		autoComplete: false,
		queryExpr: "*${0}*",      
		searchAttr: "name",
		class: 'fullside',
		onChange: function(){
			addRow();
	    }
		}, "loan_number");
		
	 new dijit.form.FilteringSelect({
	 	store: staff_store,
	 	autoComplete: false,
	 	queryExpr: "*${0}*",                       
	     id: "staff_id",
	     name: "staff_id",  
	     class: 'fullside',  
	     required:false,
	     placeHolder:"<?php echo $tr->translate("SELECT_SALE_AGENT");?>", 
	     onChange: function() {        
	     	branch_id = dijit.byId('branch_id').get('value');
	     	staff_id = dijit.byId('staff_id').get('value');
	     	if(branch_id==0){
	     		if(staff_id==-1){
	     			infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH")?>');
	     			dijit.byId('branch_id').focus();
	     			return false;
	         	}
	     	}else{
	 		    if(staff_id==-1){
	 		    	dijit.byId('branch_id_pop').attr('value',branch_id);
	 		   		dijit.byId("popup_staff").show();
	 		    }
	     	}
	     } 
	 }, "staff_id");

	 new dijit.form.FilteringSelect({
		 	store: staff_store,
		 	autoComplete: false,
		 	queryExpr: "*${0}*",                       
		     id: "parent_id",
		     name: "parent_id",  
		     class: 'fullside',  
		     required:false,
		     placeHolder:"<?php echo $tr->translate("SELECT_SALE_AGENT");?>", 
		     onChange: function() {        
		     	
		     } 
		 }, "parent_id");

});
var url_add_staff = '<?php echo $this->url(array("module"=>"group","controller"=>"co","action"=>"add-staff")); ?>';
function addStaff(){
	 if(dijit.byId('frm_staff').validate()){
		dijit.byId("save").attr("disabled",true);
		dojo.xhrPost({
			url:url_add_staff,
			form: dojo.byId("frm_staff"),
			handleAs:"json",
			load: function(data) {
		
				getAllStaffByBranch(data);
			    dijit.byId('frm_staff').reset();
			    dijit.byId("popup_staff").hide();

			    
			},
			error: function(err) {
			
			}
		});
   }
}
url_getgroup = '<?php echo $this->url(array('module'=>'group','controller'=>'co','action'=>'getallstaff'));?>';
function getAllStaffByBranch(staff_id=null){
	dijit.byId('staff_id').reset();

	branch_id = null
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id
			},
		handleAs:"json",
		load: function(data) {
			group_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('staff_id').set('store',group_store);
			if(staff_id!=null){
				dijit.byId('staff_id').set('value',staff_id);
			}
			getAllStaffByBranchPop();   
		},
		error: function(err) {
		}
	});
}
function getAllStaffByBranchPop(){
	dijit.byId('parent_id').reset();
	branch_id=null;
	dojo.xhrPost({
		url: url_getgroup,
		content:{
			'branch_id':branch_id,'noaddnew':1
			},
		handleAs:"json",
		load: function(data) {
			group_store  = getDataStorefromJSON('id','name', data);
			dijit.byId('parent_id').set('store',group_store);
		},
		error: function(err) {
		}
	});
}

var sale_number_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getsalenumber = "<?php echo $this->url(array('module'=>'loan','controller'=>'setcommission','action'=>'getsalenosetcommission')); ?>";
function getAllSaleNumber(branch_id){//used
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value'),
		},		    
		handleAs:"json",
		load: function(data) {
			sale_number_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('loan_number').set('store',sale_number_store); 
		},
		error: function(err) {
			
		}
	});
}

col=0;no=0;
title=0;
temp='';
function addRow(){
	loan_number=dijit.byId("loan_number").get("value");
	if(loan_number=='' || loan_number==-1){
		return false;
	}
	var iden = $("#identity").val();
	var arrays = iden.split(',');
	 if(arrays!=""){
		 for(var i=0;i< arrays.length;i++){
			 readychoose = dijit.byId('sale_id'+arrays[i]).get('value');
			 if(readychoose==loan_number){
				 infoMessageAlert("<?php echo $tr->translate("Choosen ready")?>");
				 return false;
			 }
		}
	}
	temp='';
	col++;no++;
	template='';
	if(title!=1){    
		tmp='<table id="table_row" class="collape responsiveTable">';
		tmp+='<tr id="head-title" class="head-td" align="center"></tr>';
		tmp+='</table>';
		dojo.query("#showrecord").append(tmp);
		
		temp+='<th scope="col" width="47px"><?php echo $tr->translate("DEL");?></th>';
		temp+='<th scope="col" width="2%"><?php echo $tr->translate("NUM");?></th>';
		temp+='<th scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></th>';
		temp+='<th scope="col" width="100px;"><?php echo $tr->translate("SOLD_PRICE");?></th>';
		temp+='<th scope="col" id="lbl_titlemetion" width="100px"><?php echo $tr->translate("PAID");?></th>';
		temp+='<th scope="col" id="lbl_titlemetion" width="100px"><?php echo $tr->translate("BALANCE");?></th>';
		temp+='<th scope="col" width="100px"><?php echo $tr->translate("COMISSION_EXPECTED");?></th>';
		
		dojo.query("#head-title").append(temp);
		title=1;
	}else{
	}
		sale_label = dijit.byId("loan_number").attr("displayedValue");
		sale_id = dijit.byId("loan_number").get("value");
		template+='<td data-label="<?php echo $tr->translate("DEL");?>" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD");?>" class="removeRow" onclick="deleteRecord('+col+');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span></td>';
		template+='<td data-label="<?php echo $tr->translate("NUM");?>"  align="center">'+no+'</td>';
		template+='<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" style="white-space: nowrap"><input class="fullside" value="'+sale_id+'" type="hidden" data-dojo-type="dijit.form.TextBox" id="sale_id'+col+'" name="sale_id'+col+'" />'+sale_label+'</td>';	
		template+='<td data-label="<?php echo $tr->translate("SOLD_PRICE");?>" ><input readonly class="fullside" type="text"  name="price_sold'+col+'" id="price_sold'+col+'" dojoType="dijit.form.TextBox" /></td>';	
		template+='<td data-label="<?php echo $tr->translate("PAID");?>" ><input readonly class="fullside" type="text"  name="paid'+col+'" id="paid'+col+'" dojoType="dijit.form.TextBox" /></td>';			
		template+='<td data-label="<?php echo $tr->translate("BALANCE");?>"><input readonly class="fullside" type="text"  name="balance'+col+'" id="balance'+col+'" dojoType="dijit.form.TextBox" /></td>';
		template+='<td data-label="<?php echo $tr->translate("COMISSION_EXPECTED");?>"><input required class="fullside" type="text" data-dojo-props="constraints:{min:0.01},rangeMessage:'+"'<?php echo $tr->translate("MINIMUM_VALUE_IS_ONE");?>'"+'" name="commission_amount'+col+'" id="commission_amount'+col+'" dojoType="dijit.form.NumberTextBox" /><input class="fullside" value="" type="hidden" data-dojo-type="dijit.form.TextBox" id="house_id'+col+'" name="house_id'+col+'" /></td>';
	tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
	tmp+="</tr>";
	dojo.query("#table_row").append(tmp);

	if($("#identity").val()!="") {
		var identity = $("#identity").val();
		$("#identity").val(identity+','+col);
	} else {$("#identity").val(col);}
	dojo.html.set(dojo.byId("row"+col),template , {
	     parseContent: true,
	});
	getInfoByLoanNumber(col);
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}

function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	getAllSaleNumber(branch_id);
}

function setBranchID(){}

var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH")?>!');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
		},
		error: function(err) {
			
		}
	});
}

var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getInfoByLoanNumber(index){
	loan_id = dijit.byId('loan_number').get('value');
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'sale_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {
			dijit.byId('price_sold'+index).attr('value', data.price_sold);
			dijit.byId('paid'+index).attr('value', data.total_principal);
			dijit.byId('balance'+index).attr('value', data.price_sold - data.total_principal);
			dijit.byId('house_id'+index).attr('value', data.house_id);
			
		},
		error: function(err) {
			infoMessageAlert(err);
		}
	});
}


</script>