<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("RENT_PAYMENT"));
	$frm = $this->frm_search;
	$url_copy =$this->url(array('module'=>'report','controller'=>'rent','action'=>'updatereceipt'));
	
	$urlReciept = $this->baseUrl()."/report/rent/receipt/id/";
	$urlDelete = $this->baseUrl()."/rent/payment/delete/id/";
	$updateReciept = $this->baseUrl()."/rent/payment/updatereceipt/id/";
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RENT_PAYMENT');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<?php echo $frm->getElement("advance_search");?>
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                	<?php echo $frm->getElement("branch_id");?>
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                	<input id="land_id" />
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                	<?php echo $frm->getElement('client_name');?>
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                	<?php echo $frm->getElement('paymnet_type');?>
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                	<?php echo $frm->getElement('status');?>
	               </div>
	            </div>
			   <div class="form-group">
	               <div class="col-md-2 col-sm-2 col-xs-12">
	               		<?php echo $frm->getElement('payment_method');?>
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                	<?php echo $frm->getElement('start_date');?>
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                	<?php echo $frm->getElement('end_date');?>
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				   			<input type="hidden" name="recordcopy" id="recordcopy" dojoType="dijit.form.TextBox" />
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	               </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	               </div>
	            </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	function copyRecord(url){
		 id = dijit.byId('recordcopy').get('value');
		 window.location.href = url+'/id/'+id;
	}
	
	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}
	
	var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
	require(["dojo/ready"], function(ready){
		ready(function(){
			 getAllPropertyBranch();
		});
		new dijit.form.FilteringSelect({
			store: property_store,
			required: false,
			autoComplete: false,
			queryExpr: "*${0}*",
			name: "land_id",
			id: "land_id",
			value:-1,
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				land_id=-1;
		}
			}, "land_id");
		new dijit.form.FilteringSelect({
			name: "branch_id",
			id: "branch_id",
			class: 'fullside',
			autoComplete: false,
			onChange: function() {
				 getAllPropertyBranch();
			}
			}, "branch_id");
		 
	});
	land_id = '<?php echo $this->search['land_id']?>';
	var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
	function getAllPropertyBranch(branch_id){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id<0){
			 dijit.byId('land_id').reset();
			return false;
		}
		dojo.xhrPost({
			url:url_getland,	
			content:{ 
			    'branch_id':branch_id,
			    'action':1
			},		    
			handleAs:"json",
			load: function(data) {
				property_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('land_id').set('store', property_store);
			    dijit.byId('land_id').reset();
			    if(land_id>0){
			    	dijit.byId('land_id').attr('value',land_id);
				 }
			},
			error: function(err) {
			}
		});
	} 

	var row=0;
	var url="";
	var indexkey="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				indexkey="";
				var m = "clicked: " + key;
				if(key=="reciept"){
					url='<?php echo $urlReciept;?>';
				}else if(key=="delete"){
					url='<?php echo $urlDelete;?>';
					indexkey = 'delete';
				}
				else if(key=="update"){
					url='<?php echo $updateReciept;?>';
					indexkey = 'update';
				}
				
				gotoAction();
			},
			items: {
				"reciept": {name: "<?php echo $tr->translate("RECEIPT");?>", icon: "fa-print", accesskey: "c o p y"},
				"delete": {name: "<?php echo $tr->translate("DELETE");?>", icon: "delete"},
				"update": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit"},
				
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		if(indexkey=='delete'){
		    if (confirm("<?php echo $tr->translate("Do you want to delete this record ?");?>")) {
		    	window.location.href = url+row;
		    } else {
		    	 return false;
		    }
		}else{
		 	window.open(url+row, '_blank');
		}
	}
</script>
