<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Customer Information'));
?>	
<?php  $frm = $this->frm_customer;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.form.TextArea");
</script>
<form id='add_customer' action="<?php echo $this->url(array('module'=>'group','controller'=>'customer','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()){
				dijit.byId('save_new').set('disabled',true);
				return true;
			} else {
				return false;
			}
</script>
<table  width="75%" style="margin-top:-5px;">
	<tr>
		<td style="padding-left:30%">
		<fieldset style="background: #fff;">
				<legend ><strong><?php echo $tr->translate("CUSTOMER_REQUIREMENT");?></strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td valign="top" width="33%">
									<table width="100%">
										<tr>
											<td><?php echo $tr->translate("CUSTOMER_NAME")?></td>
										    <td><?php echo $frm->getElement('name');?></td>
										</tr>
                                         <tr>
											<td><?php echo $tr->translate("PHONE")?></td>
									        <td><?php echo $frm->getElement('phone');?></td>
										</tr>
                                        <tr>
											<td><?php echo $tr->translate("DATE")?></td>
									        <td><?php echo $frm->getElement('date');?></td>
										</tr>
                                        
                                          <tr>
											<td><?php echo $tr->translate("FROM_PRICE")?></td>
									        <td><?php echo $frm->getElement('from_price');?></td>
										</tr>
                                        
                                         <tr>
											<td><?php echo $tr->translate("TO_PRICE")?></td>
									        <td><?php echo $frm->getElement('to_price');?></td>
										</tr>
                                        <tr>
											<td><?php echo $tr->translate("REQUIREDMENT")?></td>
									        <td><?php echo $frm->getElement('requirement');?></td>
										</tr>
                                         <tr>
											<td><?php echo $tr->translate("PROPERTIESTYPE")?></td>
									        <td><?php echo $frm->getElement('type');?></td>
										</tr>
                                          <tr>
											<td><?php echo $tr->translate("DESCRIPTION")?></td>
									       <td><?php echo $frm->getElement('description');?></td>
										</tr>
	
									</table>
							</td>
						
							
						</tr>
						<tr>
							<td colspan="3" align="center">
								<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
									 iconClass="dijitIconClear" /> 
								<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
									 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
							</td>
						</tr>
					</table>		
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>
