<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('CUSTOMER_REQUIREMENT'));
?>	
<?php  $frm = $this->frm_customer;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.form.TextArea");
</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CUSTOMER_REQUIREMENT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="card-box">
    		<form id='add_customer' action="<?php echo $this->url(array('module'=>'group','controller'=>'customer','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
				<script type="dojo/method" event="onSubmit">			
					if(this.validate()){
						if(isDuplicatePhone==1){
							alert("<?php echo $tr->translate('PHONE_NUMBER_IS_DUPLICATED')?>");
							dijit.byId('phone').focus();
							return false;
						}
						loadingBlock();
						dijit.byId('save_new').set('disabled',true);
						return true;
					} else {
						return false;
					}
				</script>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-user" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('CUSTOMER_INFO')?> </p>
											
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><strong><?php echo $tr->translate("CUSTOMER_NAME");?>*</strong>  :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('name');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PHONE");?> :
											<span id="message" style="color: red; display: block;"></span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('phone');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TELEGRAM");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('telegram');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("KNOW_BY");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('know_by');?>
									   </div>
									</div>
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-tasks" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('SALE_INFO')?> </p>
											
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROJECT_NAME");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('branchId');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_CODE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="saleId" />
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-list-alt" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('CUSTOMER_REQUIREMENT')?> </p>
											
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DATE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('date');?>
									   </div>
									</div>
									
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FROM_PRICE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('from_price');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TO_PRICE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('to_price');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("REQUIREDMENT");?> <span class="required"></span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('requirement');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_TYPE");?> <span class="required"></span> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('type');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DESCRIPTION");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php  echo $frm->getElement('description');?>
									   </div>
									</div>
									 <div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS_REQ");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('statusreq');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
									
	               
                </div>
				<div class="clearfix"></div>
				<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new" /> 
				</div>
			</form>
    	</div>
    </div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("STATUS_REQ")?>'"  id="frm_statusreq" >
		<form id="form_propertytype" >
			<table style="margin: 0 auto; width: 100%;" cellspacing="7">
				<tr>
					<td>
						<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="newstatusreq" name="newstatusreq" value="" type="text">
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button" id="save_status" value="Save" label="<?php echo $tr->translate('GO_SAVE');?>" dojoType="dijit.form.Button"
							iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewstatusreq();"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<?php 
	echo $this->frm_popupOther;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
var other_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->knowby));?> );
require(["dojo/ready"], function(ready){
	new dijit.form.FilteringSelect({
		name: "know_by",
		id: "know_by",
		autoComplete: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popUpKnowBy();
	    }
	}, "know_by");
	
	new dijit.form.FilteringSelect({
			autoComplete: false,
			queryExpr: "*${0}*",		           
			name: "saleId",
			placeHolder:'<?php echo $tr->translate('PROPERTY_CODE');?>',
			id: "saleId",
			searchAttr: "name",
			class: 'fullside',
			required:false,
			onChange: function() {
				saleId = dijit.byId('saleId').get('value');
				if(saleId==-1){
				}else{
					getSaleInfomation();
				}
		}
	}, "saleId");
	
	
	
	
});

dojo.ready(function(){

	var phoneControl = dijit.byId('phone');
	 phoneControl.on('keyup', function(evt) {
		 checkPhoneNumber();
    });
});
					
var isDuplicatePhone=0;
var urlCheckDuplicateNumber = '<?php echo $this->url(array('module'=>'group','controller'=>'customer','action'=>'checkphone')); ?>';
function checkPhoneNumber(){
	var phone =  dijit.byId('phone').get('value');
	if(phone==""){
		return false;
	}
	if(phone.length<8){
		return false
	}
	if(phone.length>10){
		alert("<?php echo $tr->translate("PHONE_NUMBER_INVALID_FORMAT")?>");
		return false;
	}
	dojo.xhrPost({
		url: urlCheckDuplicateNumber,	
		content:{ 
		    'phone':phone,
		},		    
		handleAs:"json",
		load: function(data) {
			if(data !== false ){
				isDuplicatePhone=1;
		   		document.getElementById('message').innerHTML ='<?php echo $tr->translate('PHONE_NUMBER_IS_DUPLICATED')?>';
		   		dijit.byId('phone').focus();
			}else{
				isDuplicatePhone=0;
				document.getElementById('message').innerHTML ='';
			}
		},
		error: function(err) {
		}
	});
}
function popUpKnowBy(){
	var know_by =  dijit.byId('know_by').get('value');
	if(know_by==-1){
		dijit.byId("frm_datapop").show();
	}
}
var url_branch = '<?php echo $this->url(array('module'=>'group','controller'=>'customer','action'=>'addnewdata')); ?>';
function addData(){
	if(dijit.byId('form_popup').validate()){
		loadingBlock();
		dojo.xhrPost({
			url:url_branch,
			form: dojo.byId("form_popup"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
						name: dijit.byId('title').get('value')
				};
				addDataToSelectbox(dijit.byId('know_by'),other_store , Itemmake, data);	
				dijit.byId('form_popup').reset();
				dijit.byId("frm_datapop").hide();
				HideloadingBlock();
			},
			error: function(err) {
				HideloadingBlock();
			}
		});
	}
}
function showstatusreq(){
	statusreq = dijit.byId('statusreq').get('value');
	if(statusreq==''){
		alert("<?php echo $tr->translate("PLEASE_SELECT_STATUS")?>");
		dijit.byId('statusreq').focus();
		return false;
	}else if(statusreq==-1){
		dijit.byId('frm_statusreq').show();
	}
}
var statusreqStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->statusreq));?> );
function addNewstatusreq(){
	if(dijit.byId('frm_statusreq').validate()){
		dijit.byId('save_status').set('disabled',true);
		var Itemmake = {					
				id: dijit.byId('newstatusreq').get('value'),
			    name: dijit.byId('newstatusreq').get('value')
		};		
		addDataToSelectbox(dijit.byId('statusreq'), statusreqStore, Itemmake, dijit.byId('newstatusreq').get('value'));	
		dijit.byId('newstatusreq').attr('value',dijit.byId('newstatusreq').get('value'));
		dijit.byId('frm_statusreq').reset();
		dijit.byId('frm_statusreq').hide();
		dijit.byId('save_status').set('disabled',false);
	}
}

function filterByBranch(){
	getAllPropertyBranch();
}
var urlGetSaleNumber = "<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-sale-number')); ?>";
function getAllPropertyBranch(){
	dijit.byId('saleId').reset();
	saleStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	dijit.byId('saleId').set('store', saleStore);
	
	branchId = dijit.byId('branchId').get('value');
	if(branchId== 0 || branchId==-1){
		return false;
	}
	dojo.xhrPost({
		url: urlGetSaleNumber,	
		content:{ 
		    'branch_id':branchId,
		},		    
		handleAs:"json",
		load: function(data) {
			saleStore  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('saleId').set('store', saleStore);
		},
		error: function(err) {
		}
	});
} 
var urlGetSaleInfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getsaleinfo')); ?>';
function getSaleInfomation(){
	dojo.xhrPost({
		url: urlGetSaleInfo,	
		content:{ 
		    'sale_id': dijit.byId('saleId').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('phone').attr('value',data.customerPhone);
		},
		error: function(err) {
		}
	});
}
</script>