<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Customer Information"));
$frm = $this->frm_search;

$formList = new Application_Form_Frmtable();
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'customer','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
<table width="100%">
   <tr>
   	 <td><?php echo $frm->getElement("adv_search");?></td>  
   	 <td><?php echo $frm->getElement('start_date');?></td>
     <td><?php echo $frm->getElement('end_date');?></td>
     <td><?php echo $frm->getElement('status');?></td>
     <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>    
   </tr>
</table>  
<?php echo $this->list;?> 
</form>
<style>
		.btn-action{
			padding: 3px 10px;
   			    background: #3a3a5d;
			    border: none;
			    font-size: 10pt;
			    float: left;
			    color: #fff;
			    padding-left: 15px;
			    -webkit-border-radius: 5px;
			    -moz-border-radius: 5px;
			    border-radius: 5px;
		}
	
	</style>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
</script>