<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("CUSTOMER_REQUIREMENT"));
	$frm = $this->frm_search;
	
	$formList = new Application_Form_Frmtable();
	$urlContact = $this->baseUrl()."/group/customer/contact/id/";
	$urlEdit = $this->baseUrl()."/group/customer/edit/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'customer','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<table width="100%">
				   <tr>
				   	 <td><?php echo $frm->getElement("adv_search");?></td>  
				   	 <td><?php echo $frm->getElement('start_date');?></td>
				     <td><?php echo $frm->getElement('end_date');?></td>
				     <td><?php echo $frm->getElement('know_by');?></td>
				     <td><?php echo $frm->getElement('statusreq');?></td>
				     <td><?php echo $frm->getElement('status');?></td>
				     <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>    
				   </tr>
				</table>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?> 
		</div>
	</div>
</div>
<style>
		.btn-action{
			padding: 3px 10px;
   			    background: #3a3a5d;
			    border: none;
			    font-size: 10pt;
			    float: left;
			    color: #fff;
			    padding-left: 15px;
			    -webkit-border-radius: 5px;
			    -moz-border-radius: 5px;
			    border-radius: 5px;
		}
	</style>
<script type="text/javascript">
	dojo.require("dijit.form.DateTextBox");
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
			
				var m = "clicked: " + key;
				if(key=="contact"){
					url='<?php echo $urlContact;?>';
				
				}else if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}
				gotoAction();
			},
			items: {
				"contact": {name: "<?php echo $tr->translate("CREATE_CONTACT_HISTORY");?>", icon: "fa-phone"},
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "fa-magic"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}

	var recordid ='';
	function gotoAction(){
		 window.open(url+row);
	}
</script> 