<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate('EDIT_TRANSFER_STOCK'));
$frm = $this->frm;

?>
<style>
	.image-box {
		text-align: center;
	}

	.image-box img {
		width: 150px;
		height: 100px;
		border: solid 1px #eee;
	}

	.button_browse {
		position: relative;
		overflow: hidden;
		text-align: center;
		width: 100%;
		height: 30px;
		cursor: pointer;
		background: #fbf9f9;
		border: 1px solid #e8e8e8;
	}

	.button_browse span {
		line-height: 33px;
		font-weight: 600;
		cursor: pointer;
	}

	input.btn_borwse_image {
		position: absolute;
		width: 100%;
		height: 30px;
		top: 0;
		left: 0;
		z-index: 2;
		opacity: 0;
		cursor: pointer;
	}
</style>
<script src="<?php echo $this->baseUrl(); ?>/js/help.js" type="text/javascript"></script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add' action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
			<script type="dojo/method" event="onSubmit">
				if(this.validate()){
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id=='' || branch_id<=0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH'); ?>');
						dijit.byId('branch_id').focus();
						return false;
					}
					toProjectId = dijit.byId('toProjectId').get('value');
					if(toProjectId=='' || toProjectId<=0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH'); ?>');
						dijit.byId('toProjectId').focus();
						return false;
					}
					if(branch_id==toProjectId){
						alert('<?php echo $tr->translate('PLEASE_OTHER_BRANCH'); ?>');
						dijit.byId('toProjectId').focus();
						return false;
					}
					var rowId = $('#identity').val();
					if(rowId==''){ 
						dijit.byId('productId').focus();
						alert("<?php echo $tr->translate("PLEASE_ADD_RECORD"); ?>");
						return false;
					}
					loadingBlock();
					return true;
				   }else {
					return false;
				   }
			</script>
			<div class="card-box">
				<div class="col-sm-12 border-botom">
					<div class="col-sm-8 pd-0">
						<h4 class="m-b-0"><i class="fa fa-cubes" aria-hidden="true"></i>&nbsp;<i class="fa fa-random"
								aria-hidden="true"></i>&nbsp;&nbsp;
							<?php echo $tr->translate('EDIT_TRANSFER_STOCK'); ?>
						</h4>
						<span id="message" style="color: red; display: block;"></span>
					</div>
					<div class="col-sm-4 text-right">
					</div>
				</div>
			</div>
			<div class="col-md-12">
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex">
										<div class="settings-main-icon ">
											<i class="fa fa-cubes" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("WITHDRAW_INFO"); ?>
											</p>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("BRANCH_NAME"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branch_id'); ?>
											<?php echo $frm->getElement('id'); ?>
											<?php echo $frm->getElement('oldPhoto'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("TRANFER_NO"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('requestNo'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("TRANSFER_STOCK_DATE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('transferDate'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("DRIVER"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('driver'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("DISTRIBUTOR"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('transferer'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("STATUS"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('status'); ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex">
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-queen" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("TO_PROJECT_INFO"); ?>
											</p>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("TO_PROJECT"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('toProjectId'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("RECEIVER"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('receiver'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("USAGE_FOR"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('useFor'); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("NOTE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('note'); ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex">
										<div class="settings-main-icon ">
											<i class="fa fa-file-image-o" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("PRODUCT_TRANSFER__PIC"); ?>
											</p>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-12 col-sm-12 col-xs-12">
											<?php
											$images = $this->baseUrl() . '/images/no-photo.png';
											if (!empty($this->transferphoto)) {
												$images = $this->baseUrl() . '/images/transferpic/' . $this->transferphoto;
											}
											?>
											<div class="account-image">
												<div class="image-box">
													<img id="profile_wiew" src="<?php echo $images; ?>" alt="" />
												</div>
												<div class="button_browse">
													<div id='preview'></div>
													<span>Upload <span><i class="fa fa-camera"
																aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="photo"
														name="photo" />
												</div>
											</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="form-group"
						style="background: #d8e0e2;padding: 5px 15px;margin: 0;border: solid 1px #697996;border-radius: 2px;margin-top: 10px;">
						<label style=" margin: 0; line-height: 30px; "
							class="control-label bold col-md-2 col-sm-2 col-xs-12">
							<?php echo $tr->translate("CATEGORY"); ?>
						</label>
						<div class="col-md-3 col-sm-3 col-xs-12">
							<?php echo $frm->getElement("categoryId"); ?>
						</div>
						<label style=" margin: 0; line-height: 30px; text-align: center;"
							class="control-label bold col-md-2 col-sm-2 col-xs-12">
							<?php echo $tr->translate("PRODUCT"); ?>
						</label>
						<div class="col-md-5 col-sm-5 col-xs-12">
							<input id="productId" />
						</div>
					</div>
					<div class="form-group">
						<table class="collape responsiveTable">
							<thead>
								<tr id="head-title" class="head-td" align="center">
									<th scope="col">
										<?php echo $tr->translate("DEL"); ?>
									</th>
									<th scope="col">
										<?php echo $tr->translate("N_O"); ?>
									</th>
									<th scope="col" width="20%">
										<?php echo $tr->translate("PRODUCT_NAME"); ?>
									</th>
									<th scope="col" class="currentQty">
										<?php echo $tr->translate("STOCK_REMAIN"); ?>
									</th>
									<th scope="col" width="10%">
										<?php echo $tr->translate("QTY_TRANSFER"); ?>
									</th>

									<th scope="col" width="20%">
										<?php echo $tr->translate("NOTE"); ?>
									</th>

								</tr>
							</thead>
							<tbody id="table_row">
							</tbody>
						</table>
					</div>
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="">
				</div>
			</div>
			<div class="clearfix"></div>
			<div class="card-box">
				<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
					<input type="reset" value="CLEAR" tabindex="2" label="<?php echo $tr->translate('CLEAR'); ?>"
						id="save_close" dojoType="dijit.form.Button" name="save_close"
						class="button-class button-danger" iconClass="	glyphicon glyphicon-erase" />
					<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW'); ?>"
						id="save_new" dojoType="dijit.form.Button" name="save_new" class="button-class button-primary"
						iconClass="	glyphicon glyphicon-floppy-open" />
				</div>
			</div>
		</form>
	</div>
</div>
<?php if (!empty($this->rowDetail))
	foreach ($this->rowDetail as $key => $rs) { ?>
		<div id="proCode<?php echo $key ?>" style="display: none;"><?php echo $rs['proCode']; ?></div>
		<div id="productName<?php echo $key ?>" style="display: none;"><?php echo $rs['proName']; ?></div>
		<div id="measureTitle<?php echo $key ?>" style="display: none;"><?php echo $rs['measureTitle']; ?></div>
		<div id="itemsNote<?php echo $key ?>" style="display: none;"><?php echo $rs['note']; ?></div>
	<?php } ?>
<script src="<?php echo $this->baseUrl(); ?>/admin/js/global.js" type="text/javascript"></script>
<script type="text/javascript">
	dojo.require('dijit.form.DateTextBox');
	dojo.require('dijit.form.TextArea');
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.NumberTextBox");

	var productStore = getDataStorefromJSON('id', 'name', null);
	require(["dojo/ready"], function (ready) {
		ready(function () {
			getDataByBranch();
			initailize();
		});
		new dijit.form.FilteringSelect({
			store: productStore,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,
			name: "productId",
			placeHolder: '<?php echo $tr->translate('PRODUCT_NAME'); ?>',
			id: "productId",
			searchAttr: "name",
			class: 'fullside',
			onChange: function () {
				addRowProductRequest();
			}
		}, "productId");
	});

	function getDataByBranch() {
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id == '' || branch_id == 0) {
			return false;
		}

		title = 1;


		getAllProduct(branch_id);
		getRequestNo(branch_id);
	}

	var url_getrequest = '<?php echo $this->url(array('module' => 'stockinout', 'controller' => 'transferout', 'action' => 'getrequestno')); ?>';
	function getRequestNo(branch_id) {
		dojo.xhrPost({
			url: url_getrequest,
			content: {
				'branch_id': branch_id,
			},
			handleAs: "json",
			load: function (data) {
				dijit.byId('requestNo').attr('value', data);
			},
			error: function (err) {
			}
		});
	}
	function getAllProduct(branch_id = null) {
		var urlGetAllProduct = '<?php echo $this->url(array('module' => 'requesting', 'controller' => 'request', 'action' => 'getallproduct')); ?>';
		categoryId = dijit.byId('categoryId').get('value');
		if (categoryId == '' || categoryId == 0) {
			categoryId = 0;
		}
		if (branch_id == null) {
			branch_id = dijit.byId('branch_id').get('value');
			if (branch_id == '' || branch_id == 0) {
				return false;
			}
		}
		objectContentFilter = { 'branch_id': branch_id, 'categoryId': categoryId };
		getAllProductStoreFunction(urlGetAllProduct, objectContentFilter);
	}


	var col = 0; var no = 0;
	var title = 0;
	var urlGetProductInfo = '<?php echo $this->url(array('module' => 'requesting', 'controller' => 'request', 'action' => 'productinfo')); ?>';
	function addRowProductRequest() {

		template = '';
		temp = "";

		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id == '' || branch_id <= 0) {
			alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH'); ?>');
			dijit.byId('branch_id').focus();
			return false;
		}
		productId = dijit.byId('productId').get('value');
		if (productId == '' || productId <= 0) {
			dijit.byId('productId').reset();
			dijit.byId('productId').focus();
			return false;
		}

		var iden = $("#identity").val();
		var arrays = iden.split(',');
		if (arrays != "") {
			for (var i = 0; i < arrays.length; i++) {
				readychoose = dijit.byId('proId' + arrays[i]).get('value');
				if (readychoose == productId) {
					alert("<?php echo $tr->translate("Choosen ready") ?>");
					dijit.byId('productId').reset();
					return false;
				}
			}
		}
		col++; no++;
		dojo.xhrPost({
			url: urlGetProductInfo,
			content: {
				'branch_id': branch_id,
				'productId': productId
			},
			handleAs: "json",
			load: function (data) {
				template += '<td class="numberRecord" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD"); ?>" class="removeRow" onclick="deleteRecord(' + col + ');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span></td>';
				template += '<td align="center" class="numberRecord" data-label="<?php echo $tr->translate("N_O"); ?>">' + no + '</td>';

				template += '<td class="productName" >' + data.proCode + ' ' + data.proName + '<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="proId' + col + '" name="proId' + col + '" value="' + data.id + '" type="text"  ><input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="costing' + col + '" name="costing' + col + '" value="' + data.currentPrice + '" type="text"  ></td>';
				template += '<td class="currentQty"  width="10%">' + data.currentQty + ' (' + data.measureTitle + ')</td>';
				template += '<td><input dojoType="dijit.form.NumberTextBox" required="true" data-dojo-props="constraints:{min:0.0000001,max:' + data.currentQty + '}" class="fullside" id="qtyRequest' + col + '" name="qtyRequest' + col + '" placeholder="' + '<?php echo $tr->translate("QTY_REQUEST"); ?> "  type="text"  ></td>';
				template += '<td><input dojoType="dijit.form.TextBox" class="fullside" id="note' + col + '" name="note' + col + '" placeholder="' + '<?php echo $tr->translate("NOTE"); ?> " value="" type="text"  ></td>';
				tmp = '<tr class="rowData" id="row' + col + '">';
				tmp += "</tr>";
				dojo.query("#table_row").append(tmp);
				if ($("#identity").val() != "") {
					var identity = $("#identity").val();
					$("#identity").val(identity + ',' + col);
				} else { $("#identity").val(col); }
				dojo.html.set(dojo.byId("row" + col), template, {
					parseContent: true,
				});
				dijit.byId('productId').reset();
			},
			error: function (err) {
			}
		});
	}

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for (var i = 0; i < arrays.length; i++) {
			if (arrays[i] == index) arrays.splice(i, 1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row" + index).remove();
	}

	function initailize() {

		<?php if (!empty($this->rowDetail))
			foreach ($this->rowDetail as $key => $rowD) {
				$currentQty = empty($rowD['currentQty']) ? 1 : $rowD['currentQty'];
				$currentQty = $currentQty + $rowD['qtyRequest'];
				?>

				col++; no++;
				template = '';
				tmp = "";

				var proCodeString = $('#proCode' + '<?php echo $key; ?>').html();
				var productNameString = $('#productName' + '<?php echo $key; ?>').html();
				var measureTitleString = $('#measureTitle' + '<?php echo $key; ?>').html();
				var itemsNoteString = $('#itemsNote' + '<?php echo $key; ?>').html();

				template += '<td class="numberRecord" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD"); ?>" class="removeRow" onclick="deleteRecord(' + col + ');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span></td>';
				template += '<td align="center" class="numberRecord" data-label="<?php echo $tr->translate("N_O"); ?>">' + no + '<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="detailId' + col + '" name="detailId' + col + '" value="<?php echo $rowD['id']; ?>" type="text"  ></td>';


				template += '<td class="productName" >' + proCodeString + ' ' + productNameString + '<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="proId' + col + '" name="proId' + col + '" value="<?php echo $rowD['proId']; ?>" type="text"  ><input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="costing' + col + '" name="costing' + col + '" value="<?php echo $rowD['unitPrice']; ?>" type="text"  ></td>';
				template += '<td class="currentQty"  width="10%"><?php echo $currentQty; ?> (' + measureTitleString + ')</td>';
				template += '<td><input dojoType="dijit.form.NumberTextBox" required="true" data-dojo-props="constraints:{min:0.0000001,max:<?php echo $currentQty; ?>}" class="fullside" id="qtyRequest' + col + '" name="qtyRequest' + col + '" value="<?php echo $rowD['qtyRequest']; ?>" placeholder="' + '<?php echo $tr->translate("QTY_REQUEST"); ?> "  type="text"  ></td>';
				template += '<td><input dojoType="dijit.form.TextBox" class="fullside" id="note' + col + '" name="note' + col + '" placeholder="' + '<?php echo $tr->translate("NOTE"); ?> " value="' + itemsNoteString + '" type="text"  ></td>';
				tmp = '<tr class="rowData" id="row' + col + '">';
				tmp += "</tr>";

				dojo.query("#table_row").append(tmp);
				if ($("#identity").val() != "") {
					var identity = $("#identity").val();
					$("#identity").val(identity + ',' + col);
				} else { $("#identity").val(col); }
				dojo.html.set(dojo.byId("row" + col), template, {
					parseContent: true,
				});


			<?php } ?>
	}

	$("#photo").change(function () {
		readURL(this);
	});
	$(function () {
		bs_input_file();
	});

	function readURL(input) {
		if (input.files && input.files[0]) {
			var reader = new FileReader();
			reader.onload = function (e) {
				$('#profile_wiew').attr('src', e.target.result);
			}
			reader.readAsDataURL(input.files[0]);
		}
	}

	function bs_input_file() {
		$(".input-file").before(
			function () {
				if (!$(this).prev().hasClass('input-ghost')) {
					var element = $("<input  type='file' accept='image/*' class='input-ghost' style='visibility:hidden; height:0'>");
					element.attr("name", $(this).attr("name"));
					element.change(function () {
						element.next(element).find('input').val((element.val()).split('\\').pop());
					});
					$(this).find("button.btn-choose").click(function () {
						element.click();
					});
					$(this).find('input').css("cursor", "pointer");
					$(this).find('input').mousedown(function () {
						$(this).parents('.input-file').prev().click();
						return false;
					});
					return element;
				}
			}
		);
	}
</script>