 <?php 

	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("SALE_DASHBOARD")); 
	$baseUrl = $this->baseUrl();
		echo $this->render('frontDashHead.phtml');
	?>
	

<div class="home-list ">
		
		<div class="section pad-30">
			<h5 class="pagetitle"><?php echo $tr->translate("SALE_DASHBOARD"); ?></h5>
		</div>
		<div class="row ">
            <div class="col s12 pad-0">
				
				<div class="row">
					<div class="col s12 ">
						<ul class="tabs dashboard-tab transparent z-depth-1">
							<li class="tab col s3 m4 "><a class="active white-text" href="#property_info"><?php echo $tr->translate("PROPERTY_INFO"); ?></a></li>
							<li class="tab col s3 m4 "><a class="white-text" href="#sell_info"><?php echo $tr->translate("INFO_INDILOAN"); ?></a></li>
							<li class="tab col s3 m4 "><a class="white-text" href="#payment_info"><?php echo $tr->translate("PAYMENT_INFO"); ?></a></li>
						</ul>
					</div>

					<div id="property_info" class="col s12 ">
						<div class="tab-content z-depth-1">
							<div class="col s12 m6 ">
								<ul class="collection with-header">
									<li class="collection-header"><h5><i class="mdi mdi-bank "></i> &nbsp;<?php echo $tr->translate("PROPERTY_INFO"); ?></h5></li>
									<li class="collection-item avatar">
										<i class="mdi mdi-city circle light blue darken-2 "></i>
										<span class="title">លេខផ្ទះ</span>
										<p>L100</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-google-maps circle cyan darken-2 "></i>
										<span class="title">លេខប្លង់</span>
										<p>123</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-city circle teal darken-2 "></i>
										<span class="title">ប្រភេទផ្ទះ</span>
										<p>Villa</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-road circle green darken-2 "></i>
										<span class="title">លេខផ្លូវ</span>
										<p>St12</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-cash-multiple circle light green darken-2 "></i>
										<span class="title">តម្លៃផ្ទះ</span>
										<p>$1200</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-directions circle lime darken-2 "></i>
										<span class="title">ផ្ទះមុខទៅទិស</span>
										<p>West</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-ruler circle yellow darken-2 "></i>
										<span class="title">បណ្តោយ</span>
										<p>200m</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-ruler circle amber darken-2 "></i>
										<span class="title">ទទឹង</span>
										<p>200m</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-checkbox-multiple-blank circle orange  darken-2 "></i>
										<span class="title">ទំហំ</span>
										<p>6000m(2)</p>
									</li>
								</ul>
								<ul class="collection with-header">
									<li class="collection-header"><h5><i class="mdi mdi-bank "></i> &nbsp;<?php echo $tr->translate("ព័ត៍មានសាងសង់"); ?></h5></li>
									<li class="collection-item avatar">
										<i class="mdi mdi-poll circle cyan darken-2"></i>
										<span class="title">ភាគរយសាងសង់</span>
										<p>
											<span class="green-text">60%</span>        
											<div class="progress green lighten-4">
												<div class="determinate green lighten-2" style="width: 60%"></div>
											</div>
										</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-calendar circle blue lighten-2"></i>
										<span class="title">ថ្ងៃចាប់ផ្តើមសាងសង់</span>
										<p>22-Dec-2023</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-calendar circle deep-orange lighten-2"></i>
										<span class="title">ថ្ងៃត្រូវផុតការសាងសង់</span>
										<p>23-Des-202</p>
									</li>
								</ul>

							</div>
						
							<div class="col s12 m6  pad-0">
								<ul class="collection with-header">
									<li class="collection-header"><h5><i class="mdi mdi-bank "></i> &nbsp;<?php echo $tr->translate("កិច្ចការរត់ប្លង់"); ?></h5></li>
									<li class="collection-item avatar">
										<i class="mdi mdi-poll circle cyan darken-2"></i>
										<span class="title">ដំណើការរត់ប្លង់</span>
										<p>
											<span class="green-text">60%</span>        
											<div class="progress Lime lighten-4">
												<div class="determinate Lime lighten-2" style="width: 60%"></div>
											</div>
										</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-rotate-3d circle cyan lighten-2"></i>
										<span class="title">បានប្រគល់</span>
										<p>Yes/No</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-google-maps circle cyan lighten-2"></i>
										<span class="title">ប្រភេទប្លង់</span>
										<p>រឹង/ទន់</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-account-convert circle cyan lighten-2"></i>
										<span class="title">អ្នកប្រគល់</span>
										<p>Mai Seyha</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-account-check circle cyan lighten-2"></i>
										<span class="title">អ្នកទទួល</span>
										<p>Vanndy</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-calendar circle cyan lighten-2"></i>
										<span class="title">កាលបរិច្ឆេទ</span>
										<p>22-Dec-2023</p>
									</li>
								</ul>
							</div>
							<div class="col s12 m6  pad-0">
								<ul class="collection with-header">
									<li class="collection-header"><h5><i class="mdi mdi-bank "></i> &nbsp;<?php echo $tr->translate("កិច្ចការប្រគល់ផ្ទះ"); ?></h5></li>
									<li class="collection-item avatar">
										<i class="mdi mdi-domain circle cyan darken-2"></i>
										<span class="title">ផ្ទះហើយរឺនៅ </span>
										<p>Yes/No</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-cash circle indigo darken-2"></i>
										<span class="title">ប្រភេទបង់</span>
										<p>ផ្តាច់/រំលស់</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-camera-timer circle  light blue darken-2"></i>
										<span class="title">លេខកុងទ័រទឹក</span>
										<p>ផ្តាច់/រំលស់</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-camera-timer circle lime darken-2"></i>
										<span class="title">លេខកុងទ័រភ្លើង</span>
										<p>ផ្តាច់/រំលស់</p>
									</li>
									<li class="collection-item avatar">
										<i class="mdi mdi-calendar circle amber darken-2"></i>
										<span class="title">ថ្ងៃទទួល</span>
										<p>23-Des-202</p>
									</li>
								</ul>
							</div>

						</div>
					</div>

					<div id="sell_info" class="col s12">
						<div class="tab-content ">
							<div class="ui-profile">
								<div class="primg">
									<img src="<?php //echo $userProfile; ?>" alt="">
									<div class="prname white-text">
										<h3 class="name"><?php //echo $studenName; ?> ម៉ៃ សីហា</h3>
										<div class="pos"><?php //echo $studenLatinName; ?> Mai Seyha</div>
									</div>
								</div>
								<div class="prinfo card-panel primary-bg white-text">
									<div class="count col-2">
										<h4 class="num">ថ្ងៃខែលក់ <span class="tit">22-Dec-2023</span></h4>
										<h4 class="num">តម្លៃលក់ <span class="tit">12000$</span></h4>
										<h4 class="num">ប្រាក់បានបង់ <span class="tit">11500$</span></h4>
										<h4 class="num">ប្រាក់ជំពាក់ <span class="tit">500$</span></h4>
									</div>
									<div class="count col-2">
										<h4 class="num">ប្រភេទបង់ <span class="tit">បង់រំលស់</span></h4>
										<h4 class="num">រយពេលបង់ <span class="tit">6 ឆ្នាំ</span></h4>
										<h4 class="num">ប្រាក់ត្រូវបង់ប្រចាំខែ <span class="tit">350$</span></h4>
										<h4 class="num">ស្ថានភាព <span class="tit">ដំណើការ</span></h4>
									</div>
								</div>
							
								<div class="section pad-0">
									<div id="client_info" class="col s12 m6 ">
										<ul class="collection info-collection">
											<li class="collection-item avatar collection-title ">
												<h5 class="sec-tit  "><?php echo $tr->translate("CLIENT_INFO"); ?></h5>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-account-multiple circle cyan darken-2"></i>
												<p><?php echo $tr->translate("NAME"); ?></p>
												<span class="title"><?php //echo $nationality; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-account-multiple circle cyan darken-2"></i>
												<p><?php echo $tr->translate("SEX"); ?></p>
												<span class="title"><?php //echo $nationality; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-account-location circle cyan darken-2"></i>
												<p><?php echo $tr->translate("NATIONALITY"); ?></p>
												<span class="title"><?php //echo $nationality; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-calendar-text circle cyan darken-2"></i>
												<p><?php echo $tr->translate("DOB"); ?></p>
												<span class="title"><?php //echo $dob; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-map circle cyan darken-2"></i>
												<p><?php echo $tr->translate("POB"); ?></p>
												<span class="title"><?php //echo $pob; ?></span>
											</li>

											<li class="collection-item avatar collection-title ">
												<h5 class="sec-tit  "><?php echo $tr->translate("CONTACT"); ?></h5>
											</li>

											<li class="collection-item avatar">
												<i class="mdi mdi-credit-card circle cyan darken-2"></i>
												<p><?php echo $tr->translate("NATIONAL_ID"); ?></p>
												<span class="title"><?php //echo $pob; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-account-card-details circle cyan darken-2"></i>
												<p><?php echo $tr->translate("NATIONALITY_NO"); ?></p>
												<span class="title"><?php //echo $pob; ?></span>
											</li>
									
											<li class="collection-item avatar">
												<i class="mdi mdi-phone-classic circle cyan darken-2"></i>
												<p><?php echo $tr->translate("TEL"); ?></p>
												<span class="title"><?php //echo $mother_phone; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-home-outline circle cyan darken-2"></i>
												<p><?php echo $tr->translate("HOME_NUMBER"); ?></p>
												<span class="title"><?php //echo $home_num; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-road-variant circle cyan darken-2"></i>
												<p><?php echo $tr->translate("STREE_NUMBER"); ?></p>
												<span class="title"><?php //echo $street_num; ?></span>
											</li>
											
											<li class="collection-item avatar collection-title ">
											<h5 class="sec-tit  "><?php echo $tr->translate("ADDRESS"); ?></h5>
											</li>
											<li class="collection-item avatar">
											<i class="mdi mdi-city  circle cyan darken-2"></i>
											<p><?php echo $tr->translate("PROVINCE_CITY"); ?></p>
											<span class="title"><?php //echo $provinceTitle; ?></span>
											</li>
											<li class="collection-item avatar">
											<i class="mdi mdi-flag-variant-outline circle cyan darken-2"></i>
											<p><?php echo $tr->translate("DISTRICT"); ?></p>
											<span class="title"><?php //echo $districtTitle; ?></span>
											</li>
											<li class="collection-item avatar">
											<i class="mdi mdi-pillar circle cyan darken-2"></i>
											<p><?php echo $tr->translate("COMMUNE"); ?></p>
											<span class="title"><?php //echo $communeTitle; ?></span>
											</li>
										</ul>
									</div>

									<div id="join_info" class="col s12 m6 ">
										<ul class="collection info-collection">
											<li class="collection-item avatar collection-title ">
												<h5 class="sec-tit  "><?php echo $tr->translate("JOIN_INFO"); ?></h5>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-account-multiple circle cyan darken-2"></i>
												<p><?php echo $tr->translate("JOIN_NAME"); ?></p>
												<span class="title"><?php //echo $nationality; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-account-multiple circle cyan darken-2"></i>
												<p><?php echo $tr->translate("SEX"); ?></p>
												<span class="title"><?php //echo $nationality; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-account-location circle cyan darken-2"></i>
												<p><?php echo $tr->translate("NATIONALITY"); ?></p>
												<span class="title"><?php //echo $nationality; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-calendar-text circle cyan darken-2"></i>
												<p><?php echo $tr->translate("DOB"); ?></p>
												<span class="title"><?php //echo $dob; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-map circle cyan darken-2"></i>
												<p><?php echo $tr->translate("POB"); ?></p>
												<span class="title"><?php //echo $pob; ?></span>
											</li>

											<li class="collection-item avatar collection-title ">
												<h5 class="sec-tit  "><?php echo $tr->translate("CONTACT"); ?></h5>
											</li>

											<li class="collection-item avatar">
												<i class="mdi mdi-credit-card circle cyan darken-2"></i>
												<p><?php echo $tr->translate("NATIONAL_ID"); ?></p>
												<span class="title"><?php //echo $pob; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-account-card-details circle cyan darken-2"></i>
												<p><?php echo $tr->translate("NATIONALITY_NO"); ?></p>
												<span class="title"><?php //echo $pob; ?></span>
											</li>
									
											<li class="collection-item avatar">
												<i class="mdi mdi-phone-classic circle cyan darken-2"></i>
												<p><?php echo $tr->translate("TEL"); ?></p>
												<span class="title"><?php //echo $mother_phone; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-home-outline circle cyan darken-2"></i>
												<p><?php echo $tr->translate("HOME_NUMBER"); ?></p>
												<span class="title"><?php //echo $home_num; ?></span>
											</li>
											<li class="collection-item avatar">
												<i class="mdi mdi-road-variant circle cyan darken-2"></i>
												<p><?php echo $tr->translate("STREE_NUMBER"); ?></p>
												<span class="title"><?php //echo $street_num; ?></span>
											</li>
											
											<li class="collection-item avatar collection-title ">
											<h5 class="sec-tit  "><?php echo $tr->translate("ADDRESS"); ?></h5>
											</li>
											<li class="collection-item avatar">
											<i class="mdi mdi-city  circle cyan darken-2"></i>
											<p><?php echo $tr->translate("PROVINCE_CITY"); ?></p>
											<span class="title"><?php //echo $provinceTitle; ?></span>
											</li>
											<li class="collection-item avatar">
											<i class="mdi mdi-flag-variant-outline circle cyan darken-2"></i>
											<p><?php echo $tr->translate("DISTRICT"); ?></p>
											<span class="title"><?php //echo $districtTitle; ?></span>
											</li>
											<li class="collection-item avatar">
											<i class="mdi mdi-pillar circle cyan darken-2"></i>
											<p><?php echo $tr->translate("COMMUNE"); ?></p>
											<span class="title"><?php //echo $communeTitle; ?></span>
											</li>
										</ul>
									</div>

								</div>

							</div>

							
						</div>
					</div>

					<div id="payment_info" class="col s12 ">
						<div class="tab-content ">
							<div class="col s12 pad-0 card-info z-depth-1">
								<ul class="collection with-header border-none z-depth-0">
										<li class="collection-header border-none"><h5 class="pad-0 mrg-0" ><i class="mdi mdi-bank "></i> &nbsp;<?php echo $tr->translate("PAYMENT"); ?></h5></li>
								</ul>
								<div class="col s6 ">
									<ul class="collection with-header z-depth-0">
										<li class="collection-item"><div><span>ប្រាក់បានបង់</span><span class="secondary-content">$11500</span></div></li>
										<li class="collection-item"><div><span>ថ្ងៃបង់ចុងក្រោយ</span><span class="secondary-content">22-Dec-2023</span></div></li>
										<li class="collection-item"><div><span>ទឹកប្រាក់បង់ចុងក្រោយ</span><span class="secondary-content">$500</span></div></li>
									</ul>
								</div>
								<div class="col s6 ">
									<ul class="collection with-header z-depth-0">
										<li class="collection-item"><div><span>បង់ដាច់</span><span class="secondary-content">..</span></div></li>
										<li class="collection-item"><div><span>បង់ជាភាគ</span><span class="secondary-content">...</span></div></li>
										<li class="collection-item"><div><span>បង់ជាភាគ</span><span class="secondary-content">...</span></div></li>
									</ul>
								</div>
							</div>
							<div class="col s12 pad-0">
								<ul class="collection with-header">
									<li class="collection-header"><h5><i class="mdi mdi-bank "></i> &nbsp;<?php echo $tr->translate("PAYMENT_HISTORY"); ?></h5></li>
									<li class="collection-item pad-0">
										<table class="centered dashboard-pmt-history">
											<thead>
												<tr>
													<th>ល.រ</th>
													<th>Payment Date</th>
													<th>លេខផ្ទះ</th>
													
													<th>Price</th>
												</tr>
											</thead>
											<tbody>
												<tr>
													<td>1</td>
													<td>22-Dec-2023</td>
													<td>Alvin</td>
													
													<td>$0.87</td>
												</tr>
												<tr class="odd">
													<td>2</td>
													<td>22-Dec-2023</td>
													<td>Alan</td>
													
													<td>$3.76</td>
												</tr>
												<tr>
													<td>3</td>
													<td>22-Dec-2023</td>
													<td>Jonathan</td>
													
													<td>$7.00</td>
												</tr>
											</tbody>
										</table>
									</li>
								</ul>  
								
							</div>
						</div>
					</div>

 	 			</div>
    		</div>
    	</div>
</div>

<?php 
	echo $this->render('frontDashFooter.phtml');
?>


<script type="text/javascript">
         $("#tabs-swipe-demo").tabs({ swipeable: true });
		 $(".tabs").tabs();
         $("#tabs-swipe-demo").tabs({ swipeable: true });
</script>


