<?php 
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
     $result = $this->rs;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<title><?php echo $this->tr->translate("EDIT_CLOSING_STOCK")?></title>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-database" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_CLOSING_STOCK');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form action="<?php echo $this->url(array('module'=>'product','controller'=>'closingstock','action'=>'edit')); ?>" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
					loadingBlock();
					return true;
	  			 }else {
					return false;
	   			}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
									<div class="col-md-12 col-sm-12 col-xs-12"> 
											<div class="d-flex"> 
												<div class="settings-main-icon ">
													<i class="glyphicon glyphicon-object-align-right" aria-hidden="true"></i>
												</div> 
												<div class="col-md-10 col-sm-10 col-xs-12"> 
													<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("CLOSING_STOCK_INFO");?></p>
												</div> 
											</div>
											<div class="form-group" >
												<label class="control-label bold col-md-4 col-sm-4 col-xs-12"><?php echo $tr->translate("BRANCH_NAME");?> </label>
												<div class="col-md-8 col-sm-8 col-xs-12">
													<input dojoType="dijit.form.TextBox" readOnly value="<?php echo @$result['projectName'];?>" class="fullside" id="projectName" name="projectName" type="text">
													<input dojoType="dijit.form.TextBox"  value="<?php echo @$result['id'];?>" class="fullside" id="id" name="id" type="hidden">
												</div>
											</div>
											<div class="form-group" >
												<label class="control-label bold col-md-4 col-sm-4 col-xs-12"><?php echo $tr->translate("PRODUCT_NAME");?> </label>
												<div class="col-md-8 col-sm-8 col-xs-12">
													<input dojoType="dijit.form.TextBox" readOnly value="<?php echo @$result['proName'];?>" class="fullside" id="proName" name="proName" type="text">
												</div>
											</div>
											<div class="form-group" >
												<label class="control-label bold col-md-4 col-sm-4 col-xs-12"><?php echo $tr->translate("COUNT_QTY");?> </label>
												<div class="col-md-8 col-sm-8 col-xs-12">
													<input dojoType="dijit.form.NumberTextBox"  value="<?php echo @$result['count_qty'];?>" data-dojo-props="constraints:{min:0.00}" class="fullside" required="true" id="count_qty" name="count_qty" type="text">
												</div>
											</div>
											<div class="form-group" >
												<label class="control-label bold col-md-4 col-sm-4 col-xs-12"><?php echo $tr->translate("CLOSING_DATE");?> </label>
												<div class="col-md-8 col-sm-8 col-xs-12">
													<input dojoType="dijit.form.DateTextBox" value="<?php echo @$result['closing_date'];?>" data-dojo-props="constraints:{min:0.00}" class="fullside" id="closing_date" name="closing_date" type="text">
												</div>
											</div>
											<div class="form-group" >
												<label class="control-label bold col-md-4 col-sm-4 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
												<div class="col-md-8 col-sm-8 col-xs-12">
													<input dojoType="dijit.form.TextBox" value="<?php echo @$result['note'];?>" data-dojo-props="constraints:{min:0.00}"  class="fullside" id="note" name="note" type="text">
												</div>
											</div>
									</div>
							</div>
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<div class="col-md-4 col-sm-4 col-xs-12">
						<input type="submit" value="save_close" id="save_new" name="save_new" label="<?php echo $tr->translate("GO_EDIT");?>" dojoType="dijit.form.Button" 
							class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk"/>
					</div>
               	</div>
             </div>
		</form>
    </div>
</div>
<style>
table#table_row td.productName {
    font-size: 12px;
    line-height: 14px;
    font-weight: 600;
}
table#table_row td.currentQty {
    text-align: center;
    color: #f74545;
    font-weight: 600;
}
tr.rowData {
    border-bottom: solid 2px #02014a;
}
#table tr td{
	border:1px solid #cccccc;
	text-align: center;
}
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
}
</style>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
    dojo.require("dijit.form.NumberTextBox");
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.DateTextBox");
</script>