<?php
$this->tr = Application_Form_FrmLanguages::getCurrentlanguage();
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$db = new Po_Model_DbTable_DbPurchasing();
$frm = $this->frm;
?>
<style>
	.filterBoxItems.dark {
		color: black;
	}
</style>
<script src="<?php echo $this->baseUrl(); ?>/js/help.js"></script>
<title>
	<?php echo $this->tr->translate("CREATE_PO") ?>
</title>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
			<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
					<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;
						<?php echo $tr->translate('CREATE_PO'); ?>
					</h4>
				</div>
				<div class="col-sm-4 text-right">
				</div>
			</div>
		</div>
		<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">
				if (this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if (branch_id == '' || branch_id <= 0) {
						infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH'); ?>');
						dijit.byId('branch_id').focus();
						return false;
					}
					requestId = dijit.byId('requestId').get('value');
					if (requestId == '' || requestId <= 0) {
						infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_REQUEST_NO'); ?>');
						dijit.byId('requestId').focus();
						return false;
					}
					supplierId = dijit.byId('supplierId').get('value');
					if (supplierId == '' || supplierId <= 0) {
						infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_SUPPLIER'); ?>');
						dijit.byId('supplierId').focus();
						return false;
					}
					var rowId = $('#identity').val();
					if (rowId == '') {
						infoMessageAlert("<?php echo $tr->translate("PLEASE_ADD_RECORD"); ?>");
						return false;
					}
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex">
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-open-file" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("PURCHASING_INFO"); ?>
											</p>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("BRANCH_NAME"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("branch_id"); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("PO_NO"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("purchaseNo"); ?>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("REQUEST_NO"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<input id="requestId" />
											<?php echo $frm->getElement("requestDate"); ?>
										</div>
									</div>

									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("PO_DATE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("date"); ?>
										</div>
									</div>

								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="d-flex">
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-user" aria-hidden="true"></i>
										</div>
										<div class="col-md-10 col-sm-10 col-xs-12">
											<p class="tx-20 font-weight-semibold d-flex ">
												<?php echo $tr->translate("SUPPLIER"); ?>
											</p>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("SUPPLIER"); ?>
										</label>
										<div class="col-md-4 col-sm-4 col-xs-12">
											<?php echo $frm->getElement("supplierId"); ?>
										</div>
										<div class="col-md-3 col-sm-3 col-xs-12">
											<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-refresh" dojoType="dijit.form.Button" onclick="getRefreshData();" label="<?php echo $tr->translate("GET_DATA"); ?>" />
										</div>
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("NOTE"); ?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement("note"); ?>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div id="request-info" class="information-style"></div>
					<div class="form-group filterBoxItems">
						<label style=" margin: 0; line-height: 30px; " class="control-label bold col-md-2 col-sm-2 col-xs-12">
							<?php echo $tr->translate("CATEGORY"); ?>
						</label>
						<div class="col-md-3 dark col-sm-3 col-xs-12">
							<?php echo $frm->getElement("categoryId"); ?>
						</div>
						<label style=" margin: 0; line-height: 30px; text-align: center;" class="control-label bold col-md-1 col-sm-1 col-xs-12">
							<?php echo $tr->translate("PRODUCT"); ?>
						</label>
						<div class="col-md-3 col-sm-3 col-xs-12">
							<input id="productId" />
						</div>

					</div>
					<table class="collape responsiveTable tbPOItems">
						<thead>
							<tr id="head-title" class="head-td" align="center">
								<th scope="col" rowspan="2">
									<?php echo $tr->translate("DEL"); ?>
								</th>
								<th scope="col" rowspan="2">
									<?php echo $tr->translate("N_O"); ?>
								</th>

								<th scope="col" colspan="5">
									<?php echo $tr->translate("PRODUCT_INFO"); ?>
								</th>

								<th scope="col" colspan="2">
									<?php echo $tr->translate("DISCOUNT_INFO"); ?>
								</th>
								<th scope="col" rowspan="2" width="15%">
									<?php echo $tr->translate("STATUS"); ?>
								</th>
							</tr>
							<tr class="head-td" align="center">
								<th scope="col" width="20%">
									<?php echo $tr->translate("PRODUCT_NAME"); ?>
								</th>
								<th scope="col" width="10%" class="currentQty">
									<?php echo $tr->translate("STOCK_REMAIN"); ?>
								</th>
								<th scope="col" width="10%">
									<?php echo $tr->translate("QTY_APPROVED"); ?>
								</th>
								<th scope="col" width="10%">
									<?php echo $tr->translate("QTY"); ?>
								</th>
								<th scope="col" width="10%">
									<?php echo $tr->translate("UNIT_PRICE"); ?>
								</th>

								<th scope="col" width="10%">
									<?php echo $tr->translate("DISCOUNT_PERCENT"); ?>
								</th>
								<th scope="col" width="10%">
									<?php echo $tr->translate("DISCOUNT") . " " . $tr->translate("CURRENCY_SIGN"); ?>
								</th>

							</tr>
						</thead>
						<tbody id="table_row">
						</tbody>
					</table>
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="">
					<div class="form-group" style="margin-bottom: 0;">
						<label class="control-label bold col-md-7 col-sm-7 col-xs-12" style="text-align:right;">
							<?php echo $tr->translate("TOTAL") . " " . $tr->translate("CURRENCY_SIGN"); ?>
						</label>
						<div class="col-md-5 col-sm-5 col-xs-12">
							<?php echo $frm->getElement("total"); ?>
						</div>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
			<div class="card-box mt-20">
				<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE_CLOSE"); ?>" dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="save_close" id="save_new" name="save_new" label="<?php echo $tr->translate("SAVENEW"); ?>" dojoType="dijit.form.Button" />
				</div>
			</div>
		</form>
	</div>
</div>

<script src="<?php echo $this->baseUrl(); ?>/admin/js/global.js" type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");
	dojo.require("dojo.NodeList-manipulate");
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.form.DateTextBox");

	currentProjectId = '<?php echo empty($this->reqResult['projectId']) ? 0 : $this->reqResult['projectId']; ?>';
	currentRequestId = '<?php echo empty($this->reqResult['id']) ? 0 : $this->reqResult['id']; ?>';

	var productStore = getDataStorefromJSON('id', 'name', null);
	var requestStore = getDataStorefromJSON('id', 'name', null);
	require(["dojo/ready"], function(ready) {
		ready(function() {
			<?php if (!empty($this->reqResult['projectId'])) { ?>
				dijit.byId('branch_id').set('value', currentProjectId);
			<?php } ?>
			onChageFunctionByBranch();
		});

		new dijit.form.FilteringSelect({
			store: requestStore,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,
			name: "requestId",
			placeHolder: '<?php echo $tr->translate('REQUEST_NO'); ?>',
			id: "requestId",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				getAllProduct();
				getRequestInfo();
			}
		}, "requestId");

		new dijit.form.FilteringSelect({
			store: productStore,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,
			name: "productId",
			placeHolder: '<?php echo $tr->translate('PRODUCT_NAME'); ?>',
			id: "productId",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {

				addRowProductPO();
			}
		}, "productId");
	});






	function getRefreshData() {
		urlGetAllSuppilyer = '<?php echo $this->url(array('module' => 'po', 'controller' => 'supplier', 'action' => 'getSuppliername')) ?>';
		getAllSupplier(urlGetAllSuppilyer);

	}


	function onChageFunctionByBranch() {

		getAllApprovedRequest();

		//getAllProduct();
		//getPurchaseNoByBranch();
	}
	var urlGetAllApprovedRequest = '<?php echo $this->url(array('module' => 'requesting', 'controller' => 'request', 'action' => 'getallapprovedrequest')); ?>';

	function getAllApprovedRequest() {
		dijit.byId('requestId').reset();
		requestStore = getDataStorefromJSON('id', 'name', <?php print_r(Zend_Json::encode(array())); ?>);
		dijit.byId('requestId').set('store', requestStore);

		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id == '' || branch_id <= 0) {
			branch_id = 0;
		}
		dojo.xhrPost({
			url: urlGetAllApprovedRequest,
			content: {
				'branch_id': branch_id
			},
			handleAs: "json",
			load: function(data) {
				requestStore = getDataStorefromJSON('id', 'name', data);
				dijit.byId('requestId').set('store', requestStore);
				<?php if (!empty($this->reqResult['projectId'])) { ?>
					dijit.byId('requestId').set('value', currentRequestId);
				<?php } ?>
			},
			error: function(err) {}
		});
	}
	var urlGetAllProduct = '<?php echo $this->url(array('module' => 'requesting', 'controller' => 'request', 'action' => 'getallproduct')); ?>';

	function getAllProduct() {
		var no = 0;
		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id == '' || branch_id <= 0) {
			branch_id = 0;
		}
		categoryId = dijit.byId('categoryId').get('value');
		if (categoryId == '' || categoryId == 0) {
			categoryId = 0;
		}
		requestId = dijit.byId('requestId').get('value');
		if (requestId == '' || requestId == 0) {
			infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_REQUEST_NO'); ?>');
			dijit.byId('requestId').focus();
			return false;
		}

		var urlGetAllProduct = '<?php echo $this->url(array('module' => 'requesting', 'controller' => 'request', 'action' => 'getallproduct')); ?>';
		objectContentFilter = {
			//'branch_id': branch_id,
			'categoryId': categoryId,
			'requestId': requestId
		};
		getAllProductStoreFunction(urlGetAllProduct, objectContentFilter);

	}
	var urlGetRequestNo = '<?php echo $this->url(array('module' => 'po', 'controller' => 'index', 'action' => 'getpurchaseno')); ?>';

	function getPurchaseNoByBranch() {

		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id == '' || branch_id <= 0) {
			return false;
		}
		dateRequest = dijit.byId('requestDate').get('value');
		if (dateRequest == '') {
			alert('<?php echo $tr->translate('PLEASE_SELECT_DATE'); ?>');
			dijit.byId('date').focus();
			return false;
		}
		var a = new Date(dateRequest);
		mm = a.getMonth() + 1;
		var dd = a.getDate();
		if (dd < 10) {
			dd = "0" + dd;
		}
		//month = returnMOnth(mm);
		month = mm;
		if (mm < 10) {
			month = "0" + mm;
		}

		var y = a.getFullYear();
		var dateRequest = dd + '-' + month + '-' + y;

		dojo.xhrPost({
			url: urlGetRequestNo,
			content: {
				'branch_id': branch_id,
				'dateRequest': dateRequest
			},
			handleAs: "json",
			load: function(data) {
				dijit.byId('purchaseNo').set('value', data);
			},
			error: function(err) {}
		});
	}
	var col = 0;
	var no = 0;
	var title = 0;
	var urlGetProductInfo = '<?php echo $this->url(array('module' => 'requesting', 'controller' => 'request', 'action' => 'productinfo')); ?>';

	function addRowProductPO() {

		template = '';
		temp = "";


		branch_id = dijit.byId('branch_id').get('value');
		if (branch_id == '' || branch_id <= 0) {
			infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH'); ?>');
			dijit.byId('branch_id').focus();
			return false;
		}
		requestId = dijit.byId('requestId').get('value');
		if (requestId == '' || requestId <= 0) {
			infoMessageAlert('<?php echo $tr->translate('PLEASE_SELECT_REQUEST_NO'); ?>');
			dijit.byId('requestId').focus();
			return false;
		}
		productId = dijit.byId('productId').get('value');
		productLabel = dijit.byId('productId').attr('displayedValue');
		if (productId == '' || productId <= 0) {
			dijit.byId('productId').reset();
			dijit.byId('productId').focus();
			return false;
		}

		var iden = $("#identity").val();
		var arrays = iden.split(',');
		if (arrays != "") {
			for (var i = 0; i < arrays.length; i++) {
				readychoose = dijit.byId('proId' + arrays[i]).get('value');
				if (readychoose == productId) {
					infoMessageAlert("<?php echo $tr->translate("Choosen ready") ?> " + productLabel);
					dijit.byId('productId').reset();
					return false;
				}
			}
		}
		col++;
		no++;
		dojo.xhrPost({
			url: urlGetProductInfo,
			content: {
				'branch_id': branch_id,
				'productId': productId,
				'requestId': requestId,
				'IsNotLocation': 1,

			},
			handleAs: "json",
			load: function(data) {

				// var lastUnitPrice = data.latestUnitPrice;
				// var subTotalRow = data.qtyApprovedAfter * lastUnitPrice;
				var subTotalRow = 0;
				template += '<td rowspan="2" class="numberRecord infoCol" align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD"); ?>" class="removeRow" onclick="deleteRecord(' + col + ');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span></td>';
				template += '<td  class="numberRecord infoCol" data-label="<?php echo $tr->translate("N_O"); ?>" align="center" >' + no + '</td>';
				template += '<td  data-label="<?php echo $tr->translate("PRODUCT_NAME"); ?>" class="productName infoCol" >' + productLabel + '<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="proId' + col + '" name="proId' + col + '" value="' + productId + '" type="text"  ></td>';
				template += '<td  data-label="<?php echo $tr->translate("STOCK_REMAIN"); ?>" class="currentQty infoCol"  >' + data.currentQty + ' (' + data.measureTitle + ')</td>';
				template += '<td  data-label="<?php echo $tr->translate("QTY_APPROVED"); ?>" class="currentQty infoCol"  >' + data.qtyApproved + '<small><?php echo $tr->translate("QTY_REMAIN"); ?> : ' + data.qtyApprovedAfter + '</small><input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="qtyApprovedAfter' + col + '" name="qtyApprovedAfter' + col + '" value="' + data.qtyApprovedAfter + '" type="text"  ></td>';
				template += '<td  data-label="<?php echo $tr->translate("QTY"); ?>" ><input required dojoType="dijit.form.NumberTextBox" class="fullside" data-dojo-props="constraints:{min:0.01,max:' + data.qtyApprovedAfter + '},rangeMessage:' + "'<?php echo $tr->translate("MINIMUM_VALUE_IS_ZEROONE_AND_MAX_VALUE_IS"); ?> " + data.qtyApprovedAfter + "'" + '"  onKeyup="checkingQtyPO(' + col + '); calculateTotal(' + col + ');" id="qty' + col + '" name="qty' + col + '" placeholder="' + '<?php echo $tr->translate("QTY"); ?>" value="' + data.qtyApprovedAfter + '" type="text"  ></td>';
				template += '<td data-label="<?php echo $tr->translate("UNIT_PRICE"); ?>"><input required dojoType="dijit.form.NumberTextBox" class="fullside" data-dojo-props="constraints:{min:0.01},rangeMessage:' + "'<?php echo $tr->translate("MINIMUM_VALUE_IS_ZEROONE"); ?>'" + '"  onKeyup="calculateTotal(' + col + ');" id="unitPrice' + col + '" name="unitPrice' + col + '" placeholder="' + '<?php echo $tr->translate("UNIT_PRICE"); ?> " value="" type="text"  ></td>';


				template += '<td data-label="<?php echo $tr->translate("DISCOUNT_PERCENT"); ?>">';
				template += '<input dojoType="dijit.form.NumberTextBox" class="fullside" data-dojo-props="constraints:{min:0,max:100},rangeMessage:' + "'<?php echo $tr->translate("MAX_VALUE_IS"); ?> 100'" + '"  onKeyup="calculateTotal(' + col + ');" id="discountPercent' + col + '" name="discountPercent' + col + '" placeholder="' + '<?php echo $tr->translate("DISCOUNT_PERCENT"); ?> " value="0" type="text"  >';
				template += '</td>';
				template += '<td data-label="<?php echo $tr->translate("DISCOUNT"); ?>">';
				template += '<input dojoType="dijit.form.NumberTextBox" class="fullside"  onKeyup="calculateTotal(' + col + ');" id="discountAmount' + col + '" name="discountAmount' + col + '" placeholder="' + '<?php echo $tr->translate("DISCOUNT") . " " . $tr->translate("CURRENCY_SIGN"); ?> " value="0" type="text"  >';
				template += '<input dojoType="dijit.form.TextBox" class="fullside"   id="totalDiscount' + col + '" name="totalDiscount' + col + '" placeholder="' + '<?php echo $tr->translate("DISCOUNT") . " " . $tr->translate("CURRENCY_SIGN"); ?> " value="0" type="hidden"  >';
				template += '</td>';


				template += '<td rowspan="2" data-label="<?php echo $tr->translate("STATUS"); ?>"><select class="fullside" name="isCompletedPO' + col + '" id="isCompletedPO' + col + '" dojoType="dijit.form.FilteringSelect" ><option value="0"><?php echo $tr->translate("UNCOMPLETE_PO"); ?></option><option value="1"><?php echo $tr->translate("COMPLETE_PO"); ?></option></select></td>';

				templateii = '';
				templateii += '<td colspan="4" class="infoCol" data-label="<?php echo $tr->translate("NOTE"); ?>"><input dojoType="dijit.form.TextBox" class="fullside" id="note' + col + '" name="note' + col + '" placeholder="' + '<?php echo $tr->translate("NOTE"); ?> " value="" type="text"  ></td>';
				templateii += '<td colspan="4" class="red bold" data-label="<?php echo $tr->translate("SUB_TOTAL"); ?>"><input readOnly dojoType="dijit.form.NumberTextBox" class="fullside"  id="subTotal' + col + '" name="subTotal' + col + '" placeholder="' + '<?php echo $tr->translate("SUB_TOTAL"); ?> " value="' + subTotalRow + '" type="text"  ></td>';

				tmp = '<tr class="rowData" id="row' + col + '">';
				tmp += "</tr>";
				tmp += '<tr class="rowData" id="rowii' + col + '">';
				tmp += "</tr>";

				dojo.query("#table_row").append(tmp);
				if ($("#identity").val() != "") {
					var identity = $("#identity").val();
					$("#identity").val(identity + ',' + col);
				} else {
					$("#identity").val(col);
				}
				dojo.html.set(dojo.byId("row" + col), template, {
					parseContent: true,
				});

				dojo.html.set(dojo.byId("rowii" + col), templateii, {
					parseContent: true,
				});

				dijit.byId('productId').reset();
				netTotal();
			},
			error: function(err) {}
		});
	}

	function checkingQtyPO(index) {
		qtyApprovedAfter = dijit.byId('qtyApprovedAfter' + index).get('value');
		qty = dijit.byId('qty' + index).get('value');
		if (qty > qtyApprovedAfter) {
			dijit.byId('qty' + index).set('value', qtyApprovedAfter);
			infoMessageAlert("<?php echo $tr->translate("MAXIMUM_QTY_OF_THIS_ITEMS_IS_ONLY") ?>" + " " + qtyApprovedAfter);
		}
	}

	function calculateTotal(index) {
		unitPrice = dijit.byId('unitPrice' + index).get('value');
		unitPrice = isNaN(unitPrice) ? 0 : unitPrice;

		discountPercent = dijit.byId('discountPercent' + index).get('value');
		discountPercent = isNaN(discountPercent) ? 0 : discountPercent;
		if (discountPercent > 100) {
			discountPercent = 100;
		}

		discountAmount = dijit.byId('discountAmount' + index).get('value');
		discountAmount = isNaN(discountAmount) ? 0 : discountAmount;


		qty = dijit.byId('qty' + index).get('value');
		qty = isNaN(qty) ? 0 : qty;

		var subtotal = 0;
		subtotal = (qty * unitPrice);

		discountPercentAmt = parseFloat(subtotal * discountPercent / 100);
		//

		subtotal = subtotal - discountPercentAmt;
		if (discountAmount > subtotal) {
			dijit.byId('subTotal' + index).set('value', 0);
			dijit.byId('discountAmount' + index).set('value', subtotal);
			infoMessageAlert("<?php echo $tr->translate("DISCOUNT_CAN_NOT_BIGER_THAN_TOTAL") ?>" + " " + subtotal);
			netTotal();
			return false;
		}
		subtotal = subtotal - discountAmount;
		totalDiscount = (discountAmount + discountPercentAmt).toFixed(3);
		dijit.byId('totalDiscount' + index).set('value', totalDiscount);

		dijit.byId('subTotal' + index).set('value', subtotal);
		netTotal();
	}

	function netTotal() {
		var netTotal = 0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		if (rowId == '') {
			infoMessageAlert("<?php echo $tr->translate('PLEASE_SELECT_PRODUCT'); ?>");
			dijit.byId("productId").focus();
			dijit.byId('total').attr('value', netTotal.toFixed(3));
			return false;
		}
		for (var n = 0; n < rowIDArray.length; n++) {
			netTotal += dijit.byId('subTotal' + rowIDArray[n]).get('value');
		}
		dijit.byId('total').attr('value', netTotal.toFixed(3));
	}

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for (var i = 0; i < arrays.length; i++) {
			if (arrays[i] == index) arrays.splice(i, 1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row" + index).remove();
		dojo.query("#rowii" + index).remove();
		netTotal();
	}


	var urlGetRequestInfo = '<?php echo $this->url(array('module' => 'requesting', 'controller' => 'request', 'action' => 'get-requestinfohtml')); ?>';

	function getRequestInfo() {

		dojo.query("#table_row").append('');
		$("#identity").val("");
		requestId = dijit.byId('requestId').get('value');
		if (requestId == '' || requestId == 0) {
			dojo.byId("request-info").innerHTML = '';
			return false;
		}

		dojo.xhrPost({
			url: urlGetRequestInfo,
			content: {
				'requestId': requestId
			},
			handleAs: "json",
			load: function(data) {
				if (data != '') {
					dijit.byId('requestDate').set('value', data.rowResult.date);
					dojo.byId("request-info").innerHTML = data.htmlBlog;
				}
				getPurchaseNoByBranch();
			},
			error: function(err) {}
		});
	}

	function addNewSupplier() {
		supplierId = dijit.byId('supplierId').get('value');
		if (supplierId == -1) {
			window.open('<?php echo $this->baseUrl(); ?>/po/supplier/add?isAddSupplier=1');
			dijit.byId('supplierId').reset();
		}
	}


	var urlGetAllSuppilyer = '<?php echo $this->url(array('module' => 'po', 'controller' => 'supplier', 'action' => 'getallsupplier')); ?>';

	function getRefreshData() {

		dojo.xhrPost({
			url: urlGetAllSuppilyer,
			handleAs: "json",
			load: function(data) {
				supplierStore = getDataStorefromJSON('id', 'name', data);
				dijit.byId('supplierId').set('store', supplierStore);


			},
			error: function(err) {}
		});

	}
</script>