<?php 
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
     $frm = $this->frm;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<title><?php echo $this->tr->translate("CREATE_PO")?></title>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CREATE_PO');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id=='' || branch_id<=0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>');
						dijit.byId('branch_id').focus();
						return false;
					}
					requestId = dijit.byId('requestId').get('value');
					if(requestId=='' || requestId<=0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_REQUEST_NO');?>');
						dijit.byId('requestId').focus();
						return false;
					}
					supplierId = dijit.byId('supplierId').get('value');
					if(supplierId=='' || supplierId<=0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_SUPPLIER');?>');
						dijit.byId('supplierId').focus();
						return false;
					}
					var rowId = $('#identity').val();
					if(rowId==''){ 
						alert("<?php echo $tr->translate("PLEASE_ADD_RECORD");?>");
						return false;
					}
					loadingBlock();
					return true;
	  			 }else {
					return false;
	   			}
			</script>
			<div class="card-box">
				<div class="col-md-3 col-sm-3 col-xs-12">
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("BRANCH_NAME");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("branch_id");?>
		                </div>
		             </div>
					 <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("PO_NO");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("purchaseNo");?>
		                </div>
		             </div>
					<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("REQUEST_NO");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
							<input id="requestId" />
							<?php echo $frm->getElement("requestDate");?>
		                </div>
		             </div>  
					 <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SUPPLIER");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("supplierId");?>
		                </div>
		             </div>
					 <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DATE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("date");?>
		                </div>
		             </div>
					 
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("note");?>
		                </div>
		             </div>
				</div>
				<div class="col-md-9 col-sm-9 col-xs-12">
					<div id="request-info"></div>
					<div class="form-group" style="background: #d8e0e2;padding: 5px 15px;margin: 0;border: solid 1px #697996;border-radius: 2px;margin-top: 10px;">
						<label style=" margin: 0; line-height: 30px; " class="control-label bold col-md-2 col-sm-2 col-xs-12"><?php echo $tr->translate("CATEGORY");?> </label>
						 <div class="col-md-3 col-sm-3 col-xs-12">
								<?php echo $frm->getElement("categoryId");?>
						</div>
						<label style=" margin: 0; line-height: 30px; text-align: center;" class="control-label bold col-md-1 col-sm-1 col-xs-12"><?php echo $tr->translate("PRODUCT");?> </label>
						<div class="col-md-3 col-sm-3 col-xs-12">
							<input id="productId" />
						</div>
						
					</div>
					<div class="form-group" style="margin-bottom: 0;">
		                <label class="control-label bold col-md-7 col-sm-7 col-xs-12" style="text-align:right;"><?php echo $tr->translate("TOTAL")." ".$tr->translate("CURRENCY_SIGN");?> </label>
		                <div class="col-md-5 col-sm-5 col-xs-12">
		                	<?php echo $frm->getElement("total");?>
		                </div>
		             </div>	
					<table class="collape tablesorter" id="table_row" style="width:100%; white-space: nowrap;border:1px solid #ddd;">
				    	<tr id="head-title" class="head-td" align="center"></tr>
					</table>
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
					
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE_CLOSE");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="submit" value="save_close" id="save_new" name="save_new" label="<?php echo $tr->translate("SAVENEW");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
    </div>
</div>
<style>
table#table_row td.productName {
    font-size: 12px;
    line-height: 14px;
    font-weight: 600;
}
table#table_row td.currentQty {
    text-align: center;
    color: #f74545;
    font-weight: 600;
}
table#table_row td.currentQty small {
    font-size: 10px;
    display: block;
    line-height: 8px;
}
tr.rowData {
    border-bottom: solid 2px #02014a;
}
tr.rowData td {
    padding: 5px 0;
}
#table tr td{
	border:1px solid #cccccc;
	text-align: center;
}
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
}

div#request-info .form-group {
	display: block;
	font-size: 12px;
	background: #fdfbbd;
	border: solid 2px #dc0303;
	border-radius: 5px;
}
div#request-info .form-group ul li span.lbl-tt {
	color: #02014a;
}
span.red {
	color: #f00;
	font-weight: bold;
}
div#request-info .form-group ul {
    margin: 0;
    padding: 0px 5px;
}
div#request-info .form-group ul li {
	display: inline-block;
	width: 47%;
	vertical-align: top;
}
</style>
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
    dojo.require("dijit.form.Textarea");
    dojo.require("dijit.form.NumberTextBox");
    dojo.require("dijit.form.DateTextBox");
	
	currentProjectId ='<?php echo empty($this->reqResult['projectId'])?0:$this->reqResult['projectId']; ?>';
	currentRequestId ='<?php echo empty($this->reqResult['id'])?0:$this->reqResult['id']; ?>';
	
	var productStore  = getDataStorefromJSON('id','name', null );
	var requestStore  = getDataStorefromJSON('id','name', null );
    require(["dojo/ready"], function(ready){
		ready(function(){
			<?php if(!empty($this->reqResult['projectId'])){?>
			dijit.byId('branch_id').set('value', currentProjectId);
			<?php } ?>
			onChageFunctionByBranch();
		});

		new dijit.form.FilteringSelect({
			store: requestStore,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,		           
			name: "requestId",
			placeHolder:'<?php echo $tr->translate('REQUEST_NO');?>',
			id: "requestId",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				getAllProduct();
				getRequestInfo();
			}
		}, "requestId");
	 
		new dijit.form.FilteringSelect({
			store: productStore,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,		           
			name: "productId",
			placeHolder:'<?php echo $tr->translate('PRODUCT_NAME');?>',
			id: "productId",
			searchAttr: "name",
			class: 'fullside',
			onChange: function() {
				addRowProductPO();
			}
		}, "productId");
	 });
    
	function onChageFunctionByBranch(){
		
		getAllApprovedRequest();
		
		//getAllProduct();
		//getPurchaseNoByBranch();
	}
	var urlGetAllApprovedRequest = '<?php echo $this->url(array('module'=>'requesting','controller'=>'request','action'=>'getallapprovedrequest')); ?>';
	function getAllApprovedRequest(){
		dijit.byId('requestId').reset();
		requestStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('requestId').set('store', requestStore);
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id<=0){
			branch_id = 0;
		}
		dojo.xhrPost({
			url:urlGetAllApprovedRequest,	
			content:{ 
				'branch_id':branch_id
			},		    
			handleAs:"json",
			load: function(data) {
				requestStore  = getDataStorefromJSON('id','name', data);		
				dijit.byId('requestId').set('store', requestStore);
				<?php if(!empty($this->reqResult['projectId'])){?>
				dijit.byId('requestId').set('value', currentRequestId);
				<?php } ?>
			},
			error: function(err) {
			}
		});
	}
	var urlGetAllProduct = '<?php echo $this->url(array('module'=>'requesting','controller'=>'request','action'=>'getallproduct')); ?>';
	function getAllProduct(){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id<=0){
			branch_id = 0;
		}
		categoryId = dijit.byId('categoryId').get('value');
		if(categoryId=='' || categoryId==0){
			categoryId=0;
		}
		requestId = dijit.byId('requestId').get('value');
		if(requestId=='' || requestId==0){
			alert('<?php echo $tr->translate('PLEASE_SELECT_REQUEST_NO');?>');
			dijit.byId('requestId').focus();
			return false;
		}
		
		var urlGetAllProduct = '<?php echo $this->url(array('module'=>'requesting','controller'=>'request','action'=>'getallproduct')); ?>';
		objectContentFilter = {'branch_id':branch_id,'categoryId':categoryId,'requestId':requestId};
		getAllProductStoreFunction(urlGetAllProduct,objectContentFilter);
		
	}
	var urlGetRequestNo = '<?php echo $this->url(array('module'=>'po','controller'=>'index','action'=>'getpurchaseno')); ?>';
	function getPurchaseNoByBranch(){
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id<=0){
			return false;
		}
		dateRequest = dijit.byId('requestDate').get('value');
		if(dateRequest==''){
			alert('<?php echo $tr->translate('PLEASE_SELECT_DATE');?>');
			dijit.byId('date').focus();
			return false;
		}
			var a = new Date(dateRequest);
			mm = a.getMonth()+1;
			var dd = a.getDate();
			 if(dd<10){
				 dd = "0"+dd;
			}
			//month = returnMOnth(mm);
			month=mm;
			if(mm<10){
				 month = "0"+mm;
			}
			
			var y = a.getFullYear();
			var dateRequest = dd +'-'+month+'-'+y ;
	
		dojo.xhrPost({
			url:urlGetRequestNo,	
			content:{ 
				'branch_id':branch_id,'dateRequest':dateRequest
			},		    
			handleAs:"json",
			load: function(data) {
				dijit.byId('purchaseNo').set('value', data);
			},
			error: function(err) {
			}
		});
	} 	
	var col= 0; var no=0;
	var title = 0;
	var urlGetProductInfo = '<?php echo $this->url(array('module'=>'requesting','controller'=>'request','action'=>'productinfo')); ?>';
	function addRowProductPO(){
		
		template='';
		temp = "";
		if(title!=1){
			temp+='<td><?php echo $tr->translate("DEL");?></td>';
			temp+='<td><?php echo $tr->translate("N_O");?></td>';
			temp+='<td width="20%"><?php echo $tr->translate("PRODUCT_NAME");?></td>';
			temp+='<td class="currentQty"><?php echo $tr->translate("STOCK_REMAIN");?></td>';
			temp+='<td width="10%"><?php echo $tr->translate("QTY_APPROVED");?></td>';
			temp+='<td width="10%"><?php echo $tr->translate("QTY");?></td>';
			temp+='<td width="10%"><?php echo $tr->translate("UNIT_PRICE");?></td>';
			temp+='<td width="10%"><?php echo $tr->translate("DISCOUNT")." ".$tr->translate("CURRENCY_SIGN");?></td>';
			temp+='<td width="10%"><?php echo $tr->translate("SUB_TOTAL");?></td>';
			temp+='<td width="20%"><?php echo $tr->translate("NOTE");?></td>';
			temp+='<td width="20%"><?php echo $tr->translate("STATUS");?></td>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id<=0){
			alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>');
			dijit.byId('branch_id').focus();
			return false;
		}
		requestId = dijit.byId('requestId').get('value');
		if(requestId=='' || requestId<=0){
			alert('<?php echo $tr->translate('PLEASE_SELECT_REQUEST_NO');?>');
			dijit.byId('requestId').focus();
			return false;
		}
		productId = dijit.byId('productId').get('value');
		if(productId=='' || productId<=0){
			//alert('<?php echo $tr->translate('PLEASE_SELECT_PRODUCT');?>');
			dijit.byId('productId').reset();
			dijit.byId('productId').focus();
			return false;
		}
		
		var iden = $("#identity").val();
		var arrays = iden.split(',');
		 if(arrays!=""){
			 for(var i=0;i< arrays.length;i++) {
				 readychoose = dijit.byId('proId'+arrays[i]).get('value');
				 if(readychoose==productId){
					 alert("<?php echo $tr->translate("Choosen ready")?>");
					 dijit.byId('productId').reset();
					 return false;
				 }
			}
		}
		col++;no++;
		
		
		dojo.xhrPost({
			url:urlGetProductInfo,	
			content:{ 
				'branch_id':branch_id,'productId':productId,'requestId':requestId
			},		    
			handleAs:"json",
			load: function(data) {
				template+='<td width="2%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td align="center" width="2%">'+no+'</td>';
				template+='<td class="productName" >'+data.proCode+'<br />'+data.proName+'<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="proId'+col+'" name="proId'+col+'" value="'+data.id+'" type="text"  ></td>';	
				template+='<td class="currentQty"  width="5%">'+data.currentQty+' ('+data.measureTitle+')</td>';	
				template+='<td class="currentQty"  width="15%">'+data.qtyApproved+'<small><?php echo $tr->translate("QTY_REMAIN");?> : '+data.qtyApprovedAfter+'</small><input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="qtyApprovedAfter'+col+'" name="qtyApprovedAfter'+col+'" value="'+data.qtyApprovedAfter+'" type="text"  ></td>';	
				template+='<td><input dojoType="dijit.form.NumberTextBox" class="fullside"  onKeyup="checkingQtyPO('+col+'); calculateTotal('+col+');" id="qty'+col+'" name="qty'+col+'" placeholder="'+'<?php echo $tr->translate("QTY");?>" value="'+data.qtyApprovedAfter+'" type="text"  ></td>';	
				template+='<td><input dojoType="dijit.form.NumberTextBox" class="fullside"  onKeyup="calculateTotal('+col+');" id="unitPrice'+col+'" name="unitPrice'+col+'" placeholder="'+'<?php echo $tr->translate("UNIT_PRICE");?> " value="0" type="text"  ></td>';	
				template+='<td><input dojoType="dijit.form.NumberTextBox" class="fullside"  onKeyup="calculateTotal('+col+');" id="discountAmount'+col+'" name="discountAmount'+col+'" placeholder="'+'<?php echo $tr->translate("DISCOUNT")." ".$tr->translate("CURRENCY_SIGN");?> " value="0" type="text"  ></td>';	
				template+='<td><input readOnly dojoType="dijit.form.NumberTextBox" class="fullside"  id="subTotal'+col+'" name="subTotal'+col+'" placeholder="'+'<?php echo $tr->translate("SUB_TOTAL");?> " value="0" type="text"  ></td>';	
				template+='<td><input dojoType="dijit.form.TextBox" class="fullside" id="note'+col+'" name="note'+col+'" placeholder="'+'<?php echo $tr->translate("NOTE");?> " value="" type="text"  ></td>';	
				template+='<td><select class="fullside" name="isCompletedPO'+col+'" id="isCompletedPO'+col+'" dojoType="dijit.form.FilteringSelect" ><option value="0"><?php echo $tr->translate("UNCOMPLETE_PO");?></option><option value="1"><?php echo $tr->translate("COMPLETE_PO");?></option></select></td>';
		
				tmp='<tr class="rowData" id="row'+col+'">';
				tmp+="</tr>";
				dojo.query("#table_row").append(tmp);
				if($("#identity").val()!="") {
					var identity = $("#identity").val();
					$("#identity").val(identity+','+col);
				} else {$("#identity").val(col);}
				dojo.html.set(dojo.byId("row"+col),template , {
					 parseContent: true,
				});
				dijit.byId('productId').reset();
			},
			error: function(err) {
			}
		});
	}
	function checkingQtyPO(index){
		qtyApprovedAfter = dijit.byId('qtyApprovedAfter'+index).get('value');
		qty = dijit.byId('qty'+index).get('value');
		if(qty>qtyApprovedAfter){
			dijit.byId('qty'+index).set('value',qtyApprovedAfter);
			alert("<?php echo $tr->translate("MAXIMUM_QTY_OF_THIS_ITEMS_IS_ONLY")?>"+" "+qtyApprovedAfter);
		}
	}
	function calculateTotal(index){
		unitPrice = dijit.byId('unitPrice'+index).get('value');
		unitPrice=isNaN(unitPrice)?0:unitPrice;
		
		discountAmount = dijit.byId('discountAmount'+index).get('value');
		discountAmount=isNaN(discountAmount)?0:discountAmount;
		
		qty = dijit.byId('qty'+index).get('value');
		qty=isNaN(qty)?0:qty;
		
		var subtotal=0;
		subtotal = (qty*unitPrice);
		
		if(discountAmount>subtotal){
			dijit.byId('subTotal'+index).set('value',0);
			dijit.byId('discountAmount'+index).set('value',subtotal);
			alert("<?php echo $tr->translate("DISCOUNT_CAN_NOT_BIGER_THAN_TOTAL")?>"+" "+subtotal);
			netTotal();
			return false;
		}
		subtotal=subtotal-discountAmount;
		dijit.byId('subTotal'+index).set('value',subtotal);
		netTotal();
	}
	function netTotal(){
		var netTotal=0;
		var rowId = $('#identity').val();
		var rowIDArray = rowId.split(',');
		if(rowId==''){
			alert("<?php echo $tr->translate('PLEASE_SELECT_PRODUCT');?>");
			dijit.byId("productId").focus();
			return false;
		}
		for(var n = 0; n < rowIDArray.length; n++) {
			netTotal += dijit.byId('subTotal'+rowIDArray[n]).get('value');
		}
		dijit.byId('total').attr('value',netTotal.toFixed(2));
	}
	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
	
	var urlGetRequestInfo = '<?php echo $this->url(array('module'=>'requesting','controller'=>'request','action'=>'get-requestinfo')); ?>';
function getRequestInfo(){
	requestId = dijit.byId('requestId').get('value');
	if(requestId==''){
		dojo.byId("score-info").innerHTML = '';
		subject ='';
		filterStudent();
		return false;
	}
	dojo.xhrPost({
		url: urlGetRequestInfo,
		content:{
			'requestId':requestId
			},
		handleAs:"json",
		load: function(data) {
			var string='';
			if(data!=''){
			string+='<div class="form-group" style=" padding: 10px; ">';
				string+='<span class="note_score"><i class="fa fa-file-text-o" aria-hidden="true"></i> <?php echo $tr->translate("REQUEST_INFO");?></span>';
				string+='<ul>';
					string+='<li><span class="lbl-tt"><?php echo $tr->translate("REQUEST_NO");?></span>: <span class="red">'+data.requestNo+'</span></li>';
					string+='<li><span class="lbl-tt"><?php echo $tr->translate("REQUEST_NO_FROM");?></span>: <span class="red">'+data.requestNoLetter+'</span></li>';
					string+='<li><span class="lbl-tt"><?php echo $tr->translate("REQUEST_DATE");?></span>: <span class="red">'+data.requestDateDMY+'</span></li>';
					string+='<li><span class="lbl-tt"><?php echo $tr->translate("PURPOSE");?></span>: <span class="red">'+data.purpose+'</span></li>';
				string+='</ul>';
			string+='</div>';
			
			dijit.byId('requestDate').set('value', data.date);
			}
			dojo.byId("request-info").innerHTML = string;
			
			getPurchaseNoByBranch();
		},
		error: function(err) {
		}
	});
}
</script>