<?php 
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
    $frm = $this->frmBudget;
  	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>

<script src="<?php echo $baseurl;?>/js/help.js"></script>
<title><?php echo $this->tr->translate("INITIALIZE_BUGET_TEIM")?></title>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-database" aria-hidden="true"></i> <i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('INITIALIZE_BUGET_TEIM');?></h4>
    			</div>
    			<div class="col-sm-4 text-right"></div>
    		</div>
    	</div>
    	<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id=='' || branch_id<=0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>');
						dijit.byId('branch_id').focus();
						return false;
					}
					var rowId = $('#identity').val();
					if(rowId==''){ 
						alert("<?php echo $tr->translate("PLEASE_ADD_RECORD");?>");
						return false;
					}
					loadingBlock();
					return true;
	  			 }else {
					return false;
	   			}
			</script>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="form-group" style="background: #d8e0e2;padding: 5px 15px;margin: 0;border: solid 1px #697996;border-radius: 2px;margin-top: 10px;">
		                <div class="col-md-3 col-sm-3 col-xs-12">
			                <label class="control-label bold col-md-2 col-sm-2 col-xs-12"><?php echo $tr->translate("BRANCH_NAME");?> </label>
			                <div class="col-md-9 col-sm-9 col-xs-12">
			                	<?php echo $frm->getElement("branch_id");?>
			                </div>
		                </div>
		                <div class="col-md-9 col-sm-9 col-xs-12">
							<label style=" margin: 0; line-height: 30px; " class="control-label bold col-md-2 col-sm-2 col-xs-12"><?php echo $tr->translate("BUDGET_TYPE");?> </label>
							 <div class="col-md-3 col-sm-3 col-xs-12">
							 		<?php echo $frm->getElement("budgetType");?>
							</div>
							<label style=" margin: 0; line-height: 30px; text-align: center;" class="control-label bold col-md-2 col-sm-2 col-xs-12"><?php echo $tr->translate("BUDGET_ITEM");?> </label>
							<div class="col-md-3 col-sm-3 col-xs-12">
									<?php echo $frm->getElement("budgetItem");?>
							</div>
							<div class="col-md-1 col-sm-1 col-xs-12">
								<input type="button" dojoType="dijit.form.Button" onclick="getRefreshData();" label="Get Data" iconClass="dijitEditorIcon dijitEditorIconUndo" /> 
	                   		</div>
						</div>
					</div>
					<div class="card-box">
						<table class="collape tablesorter" id="table_row" style="margin-top:10px;width:100%; white-space: nowrap;border:1px solid #ddd;">
					    	<tr id="head-title" class="head-td" align="center"></tr>
						</table>
					</div>
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" value="save_close" id="save_new" name="save_new" label="<?php echo $tr->translate("SAVENEW");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
    </div>
</div>
<style>
table#table_row td.budgetName {
    font-size: 12px;
    line-height: 14px;
    font-weight: 600;
}
table#table_row td.currentQty {
    text-align: center;
    color: #f74545;
    font-weight: 600;
}
tr.rowData {
    border-bottom: solid 2px #02014a;
}
#table tr td{
	border:1px solid #cccccc;
	text-align: center;
}
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
}
</style>
	
<script src="<?php echo $this->baseUrl();?>/admin/js/global.js"  type="text/javascript"></script>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
    dojo.require("dijit.form.NumberTextBox");

    	function getRefreshData(){
    		urlGetBudgetType ='<?php echo $this->url(array('module'=>'budget','controller'=>'type','action'=>'getbudgettype'))?>';
    		getAllBudgetType(urlGetBudgetType);
    		getBudgetItem();
    	}
    	function getBudgetItem(){
    		budgetType = dijit.byId('budgetType').get('value');
    		if(budgetType){
	    		urlGetBudgetItem = '<?php echo $this->url(array('module'=>'budget','controller'=>'item','action'=>'get-allbudgetitem'));?>';
				notinBranchId = dijit.byId('branch_id').get('value');
				contentData = {
		    			'budgetType':budgetType,
		    			'notinBranchId':notinBranchId
		    		};
				getAllBudgetItem(urlGetBudgetItem,contentData);
           }
	}
    require(["dojo/ready"], function(ready){
		ready(function(){
			 var budgetItem = dijit.byId('budgetItem');
			 budgetItem.on('change', function(evt) {
				 branch_id = dijit.byId('branch_id').get('value');
				 if(branch_id=='' || branch_id==null){
					 dijit.byId('budgetItem').attr('value','');
					 dijit.byId('branch_id').focus();
					 return false;
				}
				 budgetItem =  dijit.byId('budgetItem').get('value');
				 if(budgetItem==-1){
					 window.open('<?php echo $this->url(array('module'=>'budget','controller'=>'item','action'=>'add'))?>');
				}
				if(budgetItem>0){
					 addRowBudget();
				}
				
			});
		});

	 });
    
	
	var col= 0; var no=0;
	var title = 0;
	function addRowBudget(){
		col++;
		template='';
		temp = "";
	
		if(title!=1){
			temp+='<td><?php echo $tr->translate("DEL");?></td>';
			temp+='<td><?php echo $tr->translate("N_O");?></td>';
			temp+='<td width="20%"><?php echo $tr->translate("BUDGET_ITEM");?></td>';
			temp+='<td width="10%"><?php echo $tr->translate("INITIALIZE_BUDGET_AMOUNT");?></td>';
			temp+='<td width="10%"><?php echo $tr->translate("BUDGET_AMT_ALERT");?></td>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id<=0){
			alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>');
			dijit.byId('branch_id').focus();
			return false;
		}
		budgetItem = dijit.byId('budgetItem');
		budgetItemValue = budgetItem.get('value');
		
		if(budgetItemValue=='' || budgetItemValue<=0){
			budgetItem.focus();
			return false;
		}
		
		var iden = $("#identity").val();
		var arrays = iden.split(',');
		 if(arrays!=""){
			 for(var i=0;i< arrays.length;i++) {
				 readychoose = dijit.byId('budgetItem'+arrays[i]).get('value');
				 if(readychoose==budgetItemValue){
					 alert("<?php echo $tr->translate("Choosen ready")?>");
					 budgetItem.attr('value','');
					 return false;
				 }
			}
		}

		 budgetItemLable = budgetItem.attr("displayedValue");
		 budgetItem.attr('value','');
		 
		no++;
		/*dojo.xhrPost({
			url:urlGetProductInfo,	
			content:{ 
				'productId':productId
			},		    
			handleAs:"json",
			load: function(data) {*/
				template+='<td width="2%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td align="center" width="2%">'+no+'</td>';
				template+='<td class="budgetName" >'+budgetItemLable+'<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="budgetItem'+col+'" name="budgetItem'+col+'" value="'+budgetItemValue+'" type="text"  ></td>';	
				template+='<td><input dojoType="dijit.form.NumberTextBox" required="true" class="fullside" id="budgetAmount'+col+'" name="budgetAmount'+col+'" placeholder="'+'<?php echo $tr->translate("QTY_BEGIN");?> " value="0" type="text"  ></td>';	
				template+='<td><input dojoType="dijit.form.NumberTextBox" class="fullside" id="qtyAmount'+col+'" name="qtyAmount'+col+'" placeholder="'+'<?php echo $tr->translate("QTY_ALERT");?> "  type="text"  ></td>';	
				
				tmp='<tr class="rowData" id="row'+col+'">';
				tmp+="</tr>";
				dojo.query("#table_row").append(tmp);
				if($("#identity").val()!="") {
					var identity = $("#identity").val();
					$("#identity").val(identity+','+col);
				} else {$("#identity").val(col);}
				dojo.html.set(dojo.byId("row"+col),template , {
					 parseContent: true,
				});
			/*},
			error: function(err) {
			}
		});*/
	}
	
	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
</script>