<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("DISTRICT_LIST"));
$frm = $this->frm_district;

$urlEdit = $this->baseUrl()."/other/district/edit/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-map" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('DISTRICT_LIST');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <div class="form-group">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
                   </div>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                   		<?php echo $frm->getElement("province_name");?>
                   </div>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                    <?php echo $frm->getElement('search_status');?>
                   </div>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                   		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
                   </div>
                   <div class="col-md-3 col-sm-3 col-xs-12">
                   </div>
                </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
 <script type="text/javascript">
	function setValue(index){
		var recordcopy = $('input[name=copy]:checked').val();
		dijit.byId('recordcopy').attr('value',recordcopy);
	}
	var row=0;
	var url="";
	$(function(){
		$.contextMenu({
			selector: '.context-menu-one', 
			callback: function(key, options) {
				var m = "clicked: " + key;
				if(key=="edit"){
					url='<?php echo $urlEdit;?>';
				}
				gotoAction();
			},
			items: {
				"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
			}
		});
	});
	function setrowdata(index){
		row = index;
	}
	var recordid ='';
	function gotoAction(){
		 window.open(url+row+'?rightclick=true', '_blank');
	}
</script>
