<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;

?>
<title> <?php echo $tr->translate("LOANTYPE")?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">	
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'loantype','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			      <table>
			      	<tr>
			      		<td> <?php echo $frm->getElement("adv_search");?></td>
				      	<td><?php echo $frm->getElement('type');?></td>
				      	<td><?php echo $frm->getElement('status');?></td>
				      	<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			      	</tr>
			      </table>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
