<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;

?>
<title> <?php echo $tr->translate("COLLECTERALL_TYPE")?></title>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'loantype','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
      <table>
      	<tr>
      		<td> <?php echo $frm->getElement("adv_search");?></td>
      	<td><?php echo $frm->getElement('type');?></td>
      	<td><?php echo $frm->getElement('status');?></td>
      	<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
      	</tr>
      </table>
</form>
<?php echo $this->list;?>
