<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate("DELIVERY_NOTE")); 
	echo $this->headTitle();
?>
<div class="reportblog">
	<div class="card-box">
		<div class="col-sm-12 border-botom">
			<div class="col-sm-8 pd-0">
				<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i> <?php echo $tr->translate('DELIVERY_NOTE');?></h4>
			</div>
			<div class="col-sm-4 text-right">
			</div>
		</div>
	</div>
	<div class="card-box">
		<div id="divPrint">
			<style>
				table.tableTop tr td,span {
					font-size:12px ;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table.tableTop tr td span.project-name{
					font-size:12px ;
					font-family:"Times New Roman","Khmer OS Muol Light";
				}
				table tr td{
					padding:0 2px;
					line-height: 14px;
				}
				table.content-data{
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:13px;
				}
				table.content-data thead tr.style {
				   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #c1d0f3;
					font-weight:600;
				}
				table.content-data  tr.regurlar {
					background: #eee;
				}
				table.content-data tr td{
					padding:5px 3px; 
					border:1;
					vertical-align:middle;
				}
				table.content-data tr.headRow td{
					border:solid 1px #000;
					padding:10px 2px; 
					vertical-align:middle;
				}
				.content-data tr.headRow td span {
					display: block;
					line-height: 14px;
				}
				.content-data tr.headRow td small {
					display: block;
					line-height: 12px;
					font-size: 10px;
				}

				table.requestInfo {
					width: 100%;
					margin-top: 10px;
				}
				table.requestInfo tr td {
					vertical-align: top;
				}
				table.requestInfo span.lbTitle {
					line-height: 14px;
					float: left;
					vertical-align: top;
					min-width: 20%;
				}
				table.requestInfo span.lbTitle small {
					display: block;
					font-style: italic;
					font-weight: 200;
					line-height: 10px;
				}
				table.requestInfo tr td span {
					line-height: 14px;
					vertical-align: top;
					min-width: 75%;
				}
				td.centerText{
						text-align: center;
				}
				td.rightText {
					text-align: right;
				}
				.bold {
					font-weight: 600;
				}
				span.redColor {
					color: #ff0000;
				}
				tr.style.rejected {
					background: #ffe5e5;
				}
				tr.rowFooter td span {
					font-weight: 600;
					font-size: 12px;
				}
				tr.rowFooter td span.gtotalVal {
					color: #000000;
					display: block;
					width: 100%;
					border-bottom: dashed 1px #959595;
					text-align: right;
				}
				span.gtotalVal.mainTotal {
					font-size: 14px;
				}
				
			</style>
				
			<table class="tableTop" width="100%" >
				<tr>
					<td width="30%" id="projectlogo">
						<br />
						<img style="height:85px; max-width: 100%;" src="">
					</td>
					<td width="40%" valign="top" style=" padding-bottom: 40px;">
					</td>
					<td width="30%" align="right" style="vertical-align:top; position: relative;">
						<span class="project-name" id="projectName"></span>
						<?php echo $this->printByFormat;?>
					</td>
				</tr> 
				<tr>
					<td colspan="3" align="center">
						<span style='font-family: "Times New Roman","Khmer OS Muol Light"; display: block;line-height: 14px;'>ប័ណ្ណទទួលទំនិញ</span>
						<span style='font-family: "Times New Roman","Khmer OS Muol Light";display: block;line-height: 14px;text-transform: uppercase;font-weight: 600;' >Delivery Note</span>
						<span style='font-family: "Times New Roman","Khmer OS Muol Light";display: block;line-height: 12px;text-transform: uppercase;' >(ស្នើ/Request)</span>
					</td>
				</tr>
				<tr>
					<td colspan="3" style="position:relative;" >
						<table class="requestInfo">
							<tr>
							<?php 
								$rs = $this->rsRow;
							?>
								<td width="30%">
									<span class="lbTitle">
								        ឈ្មោះអ្នកផ្គត់ផ្គង់ : 
										<small>Supplier Name : </small>
									</span>
									<span class="bold redColor"><?php echo $rs['supplierName']?></span>
								</td>
								<td width="40%">&nbsp;</td>
								<td width="30%">
									<span class="lbTitle">
										គម្រោង : 
										<small>Project Name : </small>
									</span>	
									<span class="bold "><?php echo $rs['projectName']?></span>
									
								</td>
							</tr>
							<tr>
								<td >
									<span class="lbTitle">
									អ្នកប្រគល់ទំនិញ : 
										<small>Giver : </small>
									</span>
									<span class="bold"><?php echo $rs['driverName']?></span>
								</td>
								<td></td>
								<td >
									<span class="lbTitle">
									ប្រភេទឯកសាទទួល : 
										<small>Document Type : </small>
									</span>
									<span class="bold"><?php echo $rs['dnType']?></span>
								</td>
							</tr>
							<tr>
								<td >
									<span class="lbTitle">
									ស្លាកលេខឡាន: 
										<small>Plate No. : </small>
									</span>
									<span class="bold"><?php echo $rs['plateNo']?></span>
								</td>
								<td></td>
								<td >
									<span class="lbTitle">
									លេខប័ណ្ណទទួល/វិក្កយបត្រ : 
										<small>DN/Invoice N <sup>o</sup> : </small>
									</span>
									<span class="bold"><?php echo $rs['dnNumber']?></span>
								</td>
							</tr>
							<tr>
								<td >
									<span class="lbTitle">
									អ្នករាប់ទំនិញ : 
										<small>Counter : </small>
									</span>
									<span class="bold"><?php echo $rs['staffCounter']?></span>
								</td>
								<td></td>
								<td>
									<span class="lbTitle">
									កាលបរិច្ឆេទ ទទួល : 
										<small>Receive Date : </small>
									</span>
									<span class="bold"><?php echo $rs['receiveDate']?></span>
								</td>
								purchaseNo
							</tr>
							<tr>
								<td >
									<span class="lbTitle">
									លេខបញ្ជាទិញ : 
										<small>Purchase No. : </small>
									</span>
									<span class="bold"><a target="_blank" href="<?php echo $this->baseUrl()."/report/stockmg/purchase-letter/id/".$rs['poId'];?>"><?php echo $rs['purchaseNo']?></a></span>
								</td>
								<td></td>
								<td>
								</td>
								
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3" >
						<table class="content-data" width="100%" border="1"  cellspacing="0" cellpadding="0">
							<thead>
								<tr class="style headRow" align="center" >
									<td scope="col" class="center">
										<span>ល.រ</span>
										<small>N<sup>o</sup></small>
									</td>
									<td scope="col" class="center" style="width:200px;">
										<span>ឈ្មោះទំនិញ</span>
										<small>Product Name</small>
									</td>
									
									<td scope="col" class="center">
										<span>បរិមាណទិញ</span>
										<small>Purchase Qty</small>
									</td>
									<td scope="col" class="center">
										<span>បរិមាណទទួល</span>
										<small>Receive Qty</small>
									</td>
									<td scope="col" class="center">
										<span>បរិមាណនៅសល់</span>
										<small>Remaining Qty</small>
									</td>
									<td scope="col" class="center" style="width:200px;">
										<span>សម្គាល់</span>
										<small>Note</small>
									</td>
								</tr>
								
							</thead>
							 <?php 
							 $i=0;
				                if(!empty($this->dnDetail)) foreach ($this->dnDetail as $index => $result){ 
				                $i++;
							?>
								<tr class="style" style=" white-space:nowrap;">
					               	<td data-label="ល.រ​ /N.o" class="centerText"><?php echo $index+1;?></td>
									<td data-label="ឈ្មោះទំនិញ/Product Name" ><?php echo $result['proName']." ".$result['proCode'];?></td>
									<td data-label="បរិមាណទិញ/Purchase Qty" class="centerText"><?php echo number_format($result['qtyReceive']+$result['qtyAfterReceive'],2).' '.$result['measureLabel'];?></td>
									<td data-label="បរិមាណទទួល/Receive Qty" class="centerText"><?php echo number_format($result['qtyReceive'],2).' '.$result['measureLabel'];?></td>
									<td data-label="បរិមាណនៅសល់/Remaining Qty" style="font-size: 10px;"><?php echo number_format($result['qtyAfterReceive'],2).' '.$result['measureLabel'];?></td>
									<td data-label="សម្គាល់/Note" style="font-size: 10px;"><?php echo $result['note'];?></td>
								</tr>
							<?php 
								}
							for($num=$i;$num<10;$num++){
							?>
							<tr class="style" style=" white-space:nowrap;">
				               	<td class="centerText"><?php echo $num+1;?></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
							</tr>
							<?php }?>
						</table><br />
						
					</td>
				</tr>

				<tr>
					<td colspan="3" >
					<br />
						
						
						<div class="clearfix" style="clear: both !important;"></div>
						<table width="100%" cellspacing="0" cellpadding="0" style="margin-top:10px;" >
							<tr>
								<td style="width:40%; vertical-align: top;line-height: 16px; text-align:center;">
									<span style="font-weight: 600; display: block;">អ្នកប្រគល់ទំនិញ/Deliver</span>
								</td>
								<td style="width:20%; vertical-align: top;line-height: 16px; text-align:center;">
									<span style="font-weight: 600; display: block;">អ្នករាប់ទំនិញ/Product Counter</span>
								</td>
								<td style="width:40%; vertical-align: top;line-height: 16px; text-align:center;">
									<span style="font-weight: 600; display: block;">អ្នកផ្ទៀងផ្ទាត់ / Verifier</span>
								</td>
							</tr>
							<tr>
								<td colspan="3" style="height:80px;" >
									&nbsp;
								</td>
							</tr>
							<tr>
								<td style="text-align:center;">
									<span style="font-weight: 600; display: block; line-height: 16px;"><?php echo $rs['driverName']."<br />".$rs['receiveDate'];?></span>

								</td>
								<td style="text-align:center;">
									<span style="font-weight: 600; display: block; line-height: 16px;"><?php echo $rs['staffCounter']."<br />".$rs['receiveDate'];?></span>
									
								</td>
								<td style="text-align:center;">
									<span style="font-weight: 600; display: block; line-height: 16px;"><?php echo $rs['verifiedBy']."<br />".$rs['verifiedDate'];?></span>
								</td>
							</tr>
						</table>
						<div class="clearfix" style="clear: both !important;"></div>
					</td>
				</tr>
				
			</table>
		</div>
	</div>
</div>
<script>
require(["dojo/ready"], function(ready){
	ready(function(){
		 getBranchInfo();
	});
});
		
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->rsRow['projectId'])?0:$this->rsRow['projectId'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:65px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			document.getElementById('projectName').innerHTML = 'គម្រោង៖ '+arr.project_name;
		},
		error: function(e) {
		}
	});
}
</script>
