<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseUrl = $this->baseUrl();
	
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
?>

		<footer>
		  <div class="row">
			 <div class="twelve columns">
				<ul class="copyright">
				   <li><?php echo $tr->translate('Developed By'); ?> <a target="_blank" href="http://cam-app.com/"><?php echo $tr->translate('Cam App Technology'); ?></a>.</li>
				</ul>
			 </div>
		  </div>
	   </footer>
	   
	   
	
	   <script src="<?php echo $baseUrl; ?>/frontsite/js/jquery-2.1.1.min.js"></script>
	   <script src="<?php echo $baseUrl; ?>/frontsite/js/owl.carousel.min.js"></script>
	   <script src="<?php echo $baseUrl; ?>/frontsite/js/waypoints.js"></script>
	   <script src="<?php echo $baseUrl; ?>/frontsite/js/jquery.fittext.js"></script>
	   <script src="<?php echo $baseUrl; ?>/frontsite/js/magnific-popup.js"></script>
	   <script src="<?php echo $baseUrl; ?>/frontsite/js/wow.min.js"></script>
	   <script src="<?php echo $baseUrl; ?>/frontsite/js/jquery.nicescroll.min.js"></script>
	   
		<?php if ($action=="myreport"){?>
		<link href="<?php echo $this->baseUrl()."/datatable/"?>datatables.min.css" rel="stylesheet" type="text/css" />
		<link href="<?php echo $this->baseUrl()."/datatable/"?>responsive.dataTables.min.css" rel="stylesheet" type="text/css" />
		<script src="<?php echo $this->baseUrl()."/datatable/"?>datatables.min.js" type="text/javascript"></script>
		<script src="<?php echo $this->baseUrl()."/datatable/"?>dataTables.responsive.min.js" type="text/javascript"></script>
		
		 <script>
		$(document).ready(function() {
			$('#datatable-responsive').DataTable( {
				responsive: true,
			 "dom": '<"top"i>rt<"bottom"flp><"clear">',
				searching: false,
				iDisplayLength: 50,
			} );
		} );
		</script>
		<?php }?>
	   <script src="<?php echo $baseUrl."/templates/plugin/"?>select2/js/select2.min.js"></script>
		
	   <script src="<?php echo $baseUrl; ?>/frontsite/js/script.js"></script>
	</body>
</html>