<?php	
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
	$install_month = $this->data['install_by'];
	$autocalcualte = $this->data['autocalcualte_period'];
	$this->headTitle($tr->translate('REPAYMENTSCHEDULE'));
	echo $this->headTitle();
	$percentage = 1;
	
	$urlsubmit = array('module'=>'loan','controller'=>'repaymentschedule','action'=>'add');
	if (!empty($this->rightclick)){
		$urlsubmit = array('module'=>'loan','controller'=>'repaymentschedule','action'=>'add','rightclick'=>'true');
	}
?>
<style>
.fullside50{ width:48%;}
.agreement{
	border: 1px solid #92b0ea;
    background: #cbdcff;
    font-weight: bold;
    text-align: center;
}
.blog-left-content {
    min-height: 250px;
    border: 1px solid #eee;
    margin: 0 !important;
    padding: 10px !important;
    background: #e4edfc;
}

    
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
 </script>
 <div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="<?php echo $this->url($urlsubmit); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id = dijit.byId('branch_id').get('value');
        		if(branch_id=='' || branch_id==-1){
					alert('Please Select Branch!');
					dijit.byId('branch_id').focus();
					return false;
				}

			schedule_opt = dijit.byId('schedule_opt').get('value');
           	var rowId = $('#identity').val();
           		
			if(schedule_opt==6 || schedule_opt==5){ 
				identity = $("#identity").val(); 
				if(identity==''){ 
					alert("សូមបញ្ចូលប្រាក់ដែលអតិថិជននឹងត្រូវបង់!");
					addRow(); return false;
				}
				remain_balance = dijit.byId("for_installamount").get("value");
				if(remain_balance!=0){
					alert("ការរៀបចំតារាងត្រូវបង់មិនទាន់គ្រប់ចំនួនទេ។សូមត្រួតពិនិត្យម្តងទៀត !");	
					return false;
				}
			}
				if(schedule_opt==2){
					balance_before = dijit.byId("balance_before").get("value");
					sold_price = dijit.byId("sold_price").get("value");
					if(sold_price!=(deposit+paid_before)){
						alert("បង់ផ្តាច់ ប្រាក់ត្រូវបង់ត្រូវស្មើរនិងប្រាក់នៅជំពាក់");
						dijit.byId('deposit').focus();
						return false;
					}
				}

				for_installamount =  dijit.byId('total_installamount').get('value');
				sold_price = dijit.byId("sold_price").get("value");
				if(for_installamount!=sold_price && schedule_opt==6 ){
					alert("សូមបញ្ចូលប្រាក់ដែលត្រូវបង់ក្នុងតារាងខាងក្រោម អោយគ្រប់ចំនួន នៃតម្លៃ ដី/ផ្ទះ!");
					document.getElementById('table_row').style.background='#ff8a8a';
					return false;
				}

				client = dijit.byId('member').get('value');
				if (client=='' || client==-1){
					alert('Please Select Client Name !');
					dijit.byId('member').focus();
					return false;
				}
				rs = checkValidateDate();
				if(rs==false){
            	  return false;			
            	}
				dijit.byId('saveclose').set('disabled',true);
				return true;
			
			}else {
				return false;
			}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPAYMENTSCHEDULE');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("INFO_INDILOAN");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('branch_id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROPERTY_CODE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id='loan_number' />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="member" /> <?php //echo $frm->getElement('member');?>
							<input dojoType="dijit.form.TextBox" class="fullside" id="joint_with" name="joint_with" type="hidden">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RESCHEDULE_DATE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('date_buy');?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DESCRIPTION");?> :
	                   </label>
	                </div>
	                 <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12" style="height: auto; min-height:50px; border:1px solid #aac4e6; font-size: 13px; color:#284db7;padding:5px;">
	                    	<label id="land_information"></label>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate("AGREEMENT");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("AGREEMENT_DATE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('agreement_date');?>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BUILD_PERIOD");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('amount_build');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BUILD_START");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('start_building');?>
	                   </div>
	                </div>
					
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-map" aria-hidden="true"></i> <?php echo $tr->translate("PROPERTY_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROPERTY_CODE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="land_code" /><input dojoType="dijit.form.TextBox"  id="propertype" name="propertype" type="hidden">
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PRICE_BEFORE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('total_sold');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Discount");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<div class="col-md-6 col-sm-6 col-xs-12">
	                   			<input readonly type="text" style="width: 80%;"  dojoType="dijit.form.TextBox" name="bdiscount_percent" id="bdiscount_percent"  value="" > %
	                   		</div>
	                   		<div class="col-md-6 col-sm-6 col-xs-12">
	                   			<input readonly type="text" style="width: 85%;" dojoType="dijit.form.TextBox" name="bdiscount_fixed" id="bdiscount_fixed"  value="" > $
	                   		</div>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SOLD_PRICE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('house_price');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAID");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('paid_before');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label style="color:red;"  class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Balance");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('balance_before');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Discount");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('discount_percent');?><?php echo $frm->getElement('discount');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SOLD_PRICE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<?php echo $frm->getElement('sold_price');?>
	                   </div>
	                </div>
	                <?php if($this->data['note_agreement']==1){?>
	                <div class="form-group">
	                   <label id="lbl_dateline" class="control-label   col-md-5 col-sm-5 col-xs-12" for="first-name">
	                   <?php echo $tr->translate("AGREEMENT_NOTE")?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('note_agreement');?>
	                   </div>
	                </div>
	                <?php }?>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-money" aria-hidden="true"></i> <?php echo $tr->translate("INSTALLMENT_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_TYPE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<div class="col-md-6 col-sm-6 col-xs-12">
	                   			<?php echo $frm->getElement('schedule_opt');?>
	                   		</div>
	                   		<div class="col-md-6 col-sm-6 col-xs-12">
	                   			<select class="fullside" dojoType="dijit.form.FilteringSelect" name="install_type" id="install_type">
									<option value="1">រំលស់ថេរ</option>
									<option value="2">រំលស់ថយ</option>
								</select>
	                   		</div>
	                   </div>
	                   </div>
	                   <div class="form-group">
		                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_FORINTALLMENT");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<input readonly type="text" class="fullside" dojoType="dijit.form.TextBox" name="for_installamount" id="for_installamount"  value="" >
							<input type="hidden" class="fullside" dojoType="dijit.form.TextBox" name="total_installamount" id="total_installamount"  value="" >
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name">
		                   	<span id='lbl_period'><?php echo $tr->translate("TERM_BORROW")?></span><span class="bold" id='lbl_year'><?php echo $tr->translate("YEAR")?></span> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement('period');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("INTEREST_RATE");?>/<?php echo $tr->translate("YEAR");?>
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement('interest_rate');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name">
		                   	<span id="lbl_property_price"><?php echo $tr->translate("AMOUNT_FUND_GRAICE_PARIOD")?></span> :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement('fixed_payment');?>
		                   </div>
		                </div>
					
		                <div class="form-group">
		                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name">
		                  	 <span id="lbl_release"><?php echo $tr->translate("LOAN_RELEASE");?></span>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement('release_date');?>
		                   </div>
		                </div>
					
		                <div class="form-group">
		                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("FIRST_PAYMENT");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement('first_payment');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LIFE_LOAN");?>  :
		                   </label>
		                   <div class="col-md-7 col-sm-7 col-xs-12">
		                   		<?php echo $frm->getElement('date_line');?>
		                   </div>
		                </div>
		                <div class="form-group">
		                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("paid_receivehouse");?>  :
		                   </label>
		                   <div class="col-md-4 col-sm-4 col-xs-12">
		                   		<?php echo $frm->getElement('paid_receivehouse');?>
		                   </div>
		                   <div class="col-md-3 col-sm-3 col-xs-12">
		                   		<?php echo $frm->getElement('delay_day');?>
		                   </div>
		                </div>
	                
	            </div>
	         </div>
	         
	         <div class="card-box">
	             <div class="col-md-8 col-sm-8 col-xs-12">
					<div class="form-group blog-left-title">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold m-0" for="first-name"><i class="fa fa-calendar" aria-hidden="true"></i> <?php echo $tr->translate("SCHEDULE_INSTALLMENT");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                	 <div class="col-md-12 col-sm-12 col-xs-12 blog-left-content">
	                	 	<div  id="showrecord"></div>
							<input type="button" label="<?php echo $tr->translate('ADD_INSTALLMENT');?>" dojoType="dijit.form.Button" 
					 		iconClass="dijitIconEditProperty" onclick="addRow();" />
	                	 </div>
	                </div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-money" aria-hidden="true"></i> <?php echo $tr->translate("PAYMENT_INFORMATION");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RECEIPT_NO");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('receipt');?>
	                   </div>
	                </div>
					
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DAY_PAYMENT");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input constraints="{datePattern:'dd/MM/yyyy'}" type="text" class="fullside" dojoType="dijit.form.DateTextBox" name="paid_date" id="paid_date"  value="<?php echo date("Y-m-d");?>" >
	                   </div>
	                </div>
				  
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Paid");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('deposit');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Balance");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('balance');?>
	                   </div>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_TYPE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('payment_method');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CHEQUE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('cheque');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
	                   </label>
	                </div>
	                <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12">
	                    	<?php echo $frm->getElement('note');?>
	                   </div>
	                </div>
	             </div>
	         </div>
	         <div class="clearfix">
	         <input type="hidden" name="sale_code" id="sale_code" dojoType="dijit.form.TextBox" value="" />
			<input type="hidden" name="id" id="id" dojoType="dijit.form.TextBox" value="<?php echo $this->id;?>" />
			<input type="hidden" name="identity" id="identity"  value="" />
			<input type="hidden" name="old_paymentmethod" id=old_paymentmethod dojoType="dijit.form.TextBox" value="" />
	         </div>
			 <div class="card-box">
             	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
             		<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
					<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" id='saveclose' name='saveclose' value='saveclose' dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
					<input type="button" onclick="addPreviewLoan();displayNone();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
	
    			</div>
    		</div>
		</form>
	</div>
</div>

<div class="dijitHidden" style="z-index: 1000;">
<style>
.print tr td{
	/*padding:5px 2px; */
}
</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់'" id="lbl_schedule" style="width:1000px;z-index: 1000 !important">
	<div id="rpt_print" class="print" style="text-align: center;">
		<input style="text-align: center;" type="button" onclick="printSave();" label="<?php echo $tr->translate("បោះពុម្ភបង្កាន់ដៃ")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		<div id="t_amountmoneytype" name="t_amountmoneytype">
		</div>
	</div>
</div>
</div>
<div class="dijitHidden" style="width: 25cm !important; height: 5cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="terms" >
		<div id="divPrint" style="height: 13.4cm ; padding: 0px; margin: 0px;">
			<style>
				.fontbig{
					font-size: 16px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}

				.label{ font-size: 22px;}
				.value{ border: 1px solid #000; height: 30px; padding: 0 2px;width: 100%;margin-right:5px; display: block;
						line-height: 32px;}
				.values{ border: 1px solid #000; height: 25px; padding: 0 10px;display: block;
						line-height: 25px;}
				.h{}
				.print tr td{
					/*padding:2px 2px; */
				}
			   .khmerbold{font:12px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;/*margin-left:4px;*/}
			   .noted{
					white-space: pre-wrap;     
					word-wrap: break-word;      
					word-break: break-all;
					white-space: pre;
					font:12px 'Khmer OS Battambang';
					border: 1px solid #000;
                   line-height:20px;font-weight: normal !important;
                }
                td span{line-height: 20px;}	
			</style>
			<table width="100%" style="backgroud:red;white-space: nowrap;font-size:14px; padding:0px;margin-top: -15px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td id="projectlogo" width="25%">
									<img style="height:75px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>"> 
								</td>					
								<td width="50%" style="font:18px 'Kh Muol';" valign="bottom" align="center"><u><div style=" font-family: Arial Black;font-family:'Khmer MEF2';margin-top: 15px;padding-top: 15px;">បង្កាន់ដៃទទួលប្រាក់</div></u>
									<div style="line-height:30px;margin-top:-10px"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table style="width:22cm !important;white-space: nowrap;margin-top: -30px;font-family:'Khmer OS Battambang';font-size: 16px;" class="print" cellspacing="3px"  cellpadding="0">
				<tr>
					<td width="10%"></td>
					<td width="30%"></td>
					<td width="15%"></td>
					<td width="17%"></td>
					<td width="10%"></td>
					<td width="18%"></td>
				</tr>
				<tr style="white-space: nowrap;font-size: 16px;">
				    <td colspan="5"></td>
					<td align="right"><strong style="font-family:Arial !important;"> <label id="lb_receipt" ></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td>គម្រោង</td>
				    <td><strong><label id="lbl_project" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;ប្រាក់ដើមត្រូវបង់</td>
                    <td><strong><label id="lbl_principle_amount" class="value"></label></strong></td>
                    <td>&nbsp;&nbsp;បង់លើកទី</td>
                    <td><strong><label id="lbl_paidtimes" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td >ឈ្មោះ​អតិថិជន </td>
				    <td ><strong><label id="lb_customer" class="value"></label></strong></td>
					<td >​&nbsp;&nbsp;ប្រាក់ការ</td>
				    <td><strong><label id="lb_discount" class="value">0.00 $</label></strong></td>
				    <td>&nbsp;&nbsp;ប្រាក់ពិន័យ</td>
                    <td><label id="" class="value">0.00 $</label></td>
                </tr>
				<tr style="white-space: nowrap;">
					<td ><?php echo $tr->translate("PROPERTY_CODE");?></td>
                    <td><strong><label id="lb_hourseno" class="value"></label></strong></td>
				   <td >&nbsp;&nbsp;ប្រាក់បង់បន្ថែម</td>
					<td colspan="3"><strong><label id="lbl_extrapayment" class="value"> 0.00 $</label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td  width="10%"><?php echo $tr->translate("HOUSE_PRICE");?></td>
				    <td width="40%"><strong><label id="lblpropertyprice" class="value"></label></strong></td>
					<td >&nbsp;&nbsp;ប្រាក់ត្រូវបង់</td>
                    <td colspan="3"><strong><label id="lbl_total_payment" class="value"></label></strong></td>
				</tr>
				<tr class="fontsize">
					<td >ប្រាក់បានបង់សរុប</td>
					<td >
						<table width="100%" style="border-spacing: 0px !important;">
							<tr>
								<td width="33%" style="white-space:nowrap;"><strong><label id="lbl_total_paid" class="value"></label></strong></td>
								<td width="33%" style="white-space:nowrap;">ប្រាក់នៅសល់</td>
								<td width="33%" style="white-space:nowrap;"><strong><label id="lbl_ending_balance" class="value"></label></strong></td>
							</tr>
						</table>
					</td>
					<td>&nbsp;&nbsp;ប្រាក់ទទួលបាន</td>
					<td colspan="3" colspan="3"><strong><label id="lb_paid" class="value"></label></strong></td>
		        </tr>
				<tr style="white-space: nowrap;">
					<td rowspan="2">សម្គាល់</td>
				    <td rowspan="2" class="noted" valign="top"><label id="lb_noted" ></label></td>
					<td >&nbsp;&nbsp;ថ្ងៃត្រូវបង់</td>
				    <td><strong><label id="lb_buydate" class="value"></label></strong></td>
					<td>&nbsp;ថ្ងៃទទួល</td>
					<td><strong><label id="lbl_paid_date" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="padding">&nbsp;&nbsp;បង់ជា</td>
					<td ><strong><label id="lbl_paymenttype" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;លេខ</td>
					<td  ><strong><label id="lbl_cheque" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="65px;">
					<td colspan="6">
						<table width="100%" border="0" style="font-size:14px;line-height: 18px;">
							<tr>
								<td width="30%">&nbsp;
									<?php echo $this->data['account_sign'];?>
								</td>
								<td align="center" width="40%">
									<?php echo $this->data['customer_sign'];?>
								</td>
								<td align="center" width="30%">
									<?php echo $this->data['teller_sign'];?>
								</td>
							</tr>
							<tr height="80">
								<td colspan="3">&nbsp;
								</td>
							</tr>
							<tr>
								<td width="30%">&nbsp;
								</td>
								<td align="center" width="40%">
									<strong><label id="lbl_customer"></label></strong>
								</td>
									
								<td align="center" width="30%">
									<strong>
										<?php 
										   $session_user=new Zend_Session_Namespace('authinstall');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</strong>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr style="line-height: 0px;">
					<td>&nbsp;</td>
				</tr>
				<tr style="line-height: 20px;font-size: 13px;font-family:'Khmer OS Battambang';">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;">&nbsp;សំគាល់ ៖</span>
					</td>
					<td colspan="5">
						<span style="font-size: 11px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 11px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					 <td colspan="6" style="border-bottom: 2px solid rgba(255, 235, 59, 0.88)">
					 </td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" >
						<?php echo $this->footer;?>
					</td>
				</tr>
			</table>
		</div>
		<table width="100%">
			<tr>
				<td align="center">
					<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
					<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
						type="button" onclick="doPrint();">បោះពុម្ភ/Print</button>
				</td>
			</tr>
	</table>
		<div id="divPrint1" style="width: 21cm !important; height: 13.4cm ; padding: 0px; margin: 0px;">
			<?php if($this->data['showreceipt']>1){?>
				<div style="border:2px dashed <?php echo $this->data['border_receiptcolor'];?>; vertical-align: middle;margin:20px 0px 40px 0px"></div>
			<?php }?>
			<div id="innerdivPrint1"></div>
		</div>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("INTEREST_RATE")?>'"  id="frm_interest" >
		<form id="form_interestrate" dojoType="dijit.form.Form">
			<table style="margin: 0 auto; width: 100%;" cellspacing="7">
				<tr>
					<td>
						<input dojoType="dijit.form.NumberTextBox" required="true" class="fullside" id="interest_ratenew" name="interest_ratenew" value="" type="text">
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button" value="Save" label="<?php echo $tr->translate('GO_SAVE');?>" dojoType="dijit.form.Button"
							iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addinterest();"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script type="text/javascript">	
						           	
var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-il-loan-Detail')); ?>';
function getLaonPayment(){
	loan_number = dijit.byId("loan_number").get('value');
		dojo.xhrPost({
		    url: url_submit,
		    content : { 
			    'loan_number':loan_number,
			},	
			handleAs:"json",
			load: function(respone) {
					/*dijit.byId('identity').attr('value',"");
					dijit.byId('priciple_amount').attr('value',0);
					dijit.byId('os_amount').attr('value',0);
					dijit.byId('total_payment').attr('value',0);
					dijit.byId('amount_receive').attr('value',0);
					dijit.byId('discount').attr('value',0);
					dijit.byId('service_charge').attr('value',0);
					dijit.byId('penalize_amount').attr('value',0);
					dijit.byId('total_interest').attr('value',"");
					dijit.byId('amount_return').attr('value',0);
					dijit.byId('payment_term').attr('value',"");
					dijit.byId('currency_type').attr('value',"");*/
				
			},
			error: function(e) {
				//alert(e);
			}
		});
}
function checkScheduleOption(){
	interest_rate = dijit.byId("interest_rate").get("value");
  	if(interest_rate==-1){
  		dijit.byId('frm_interest').show();
  		return false;
	}
	dijit.byId("install_type").set("readOnly",true);
	dijit.byId('first_payment').set("readOnly",false);
	dijit.byId('period').set("readOnly",false);
	dijit.byId('interest_rate').set("readOnly",false);
	dijit.byId('release_date').set("readOnly",false);
	dijit.byId('date_line').set("readOnly",true);
	method_id = dijit.byId('schedule_opt').get('value');

	amount_principal = dijit.byId('balance').get('value');	
	debt_amount = dijit.byId('period').get('value')*<?php echo $install_month;?>;
	if(method_id==3 || method_id==6){
		debt_amount = dijit.byId('period').get('value');
	}

	dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TERM_BORROW")?>";
	dojo.byId('lbl_year').innerHTML="<?php echo ($install_month==12)?$tr->translate("YEAR"):$tr->translate("MONTH")?>";
	
	dojo.query("#table_row").append('');
	dijit.byId("total_installamount").attr("value",0);
	$('#identity').val('');
	dojo.query("#showrecord").append('');
	title=0;
	no=0;	
	if(method_id==4){
			dijit.byId("install_type").set("readOnly",false);
			calCulateFixedPeriod();	
		}else {
			dijit.byId('fixed_payment').attr('value',0);
			dijit.byId('fixed_payment').set("readOnly",true);
		if(method_id==1){//booking
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('date_line').set("readOnly",false);
			dijit.byId('period').set("readOnly",true);
			dijit.byId('period').attr("value",0);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('interest_rate').set("readOnly",true);
		}else if(method_id==2){//payoff
			dijit.byId('release_date').set("readOnly",true);
			dijit.byId('first_payment').set("readOnly",true);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('period').set("readOnly",true);
			amount_principal = dijit.byId("sold_price").get("value")-dijit.byId("paid_before").get("value");
			dijit.byId('deposit').attr("value",amount_principal);
			dijit.byId('balance').attr("value",0);
			dijit.byId('period').attr("value",0);
			dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
			dijit.byId('first_payment').attr('value','<?php echo date("Y-m-d");?>');			
		}else if(method_id==3){//times
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE")?>";
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH")?>';
			if(dijit.byId("old_paymentmethod").get("value")==1){amount_principal = dijit.byId("sold_price").get('value');}
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}
			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(0);
			if(debt_amount!=0){
				dijit.byId('fixed_payment').attr("value",total_collect);
			}
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			
		}else if(method_id==5){//times
			dijit.byId('release_date').set("readOnly",true);
			//dijit.byId('first_payment').set("readOnly",true);
			
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('interest_rate').set("readOnly",true);
			dijit.byId('period').set("readOnly",false);
		}
		else if(method_id==6){//times ដំណាក់កាលមិនថេ			
			dijit.byId('interest_rate').attr('value',0);
			if(dijit.byId('period').get('value')==12){
				//dijit.byId('period').attr('value',0);
			}
			$('#identity').val('');
			dijit.byId('first_payment').attr("value",'<?php echo date("Y-m-d");?>');
			dojo.byId('lbl_period').innerHTML="<?php echo $tr->translate("TOTAL_INSTALLMENT")?>";
			dojo.byId('lbl_release').innerHTML="<?php echo $tr->translate("START_DATE")?>";
			if(isNaN(amount_principal)){amount_principal=0;}if(isNaN(debt_amount)){debt_amount=0;}

			total_collect = amount_principal/debt_amount;
			total_collect = total_collect.toFixed(2);
			if(isNaN(total_collect)){
				total_collect=0;
			}
			dojo.byId('lbl_year').innerHTML='<?php echo $tr->translate("MONTH")?>';
			dijit.byId('fixed_payment').attr("value",0);
			dijit.byId('fixed_payment').set("readOnly",true);
			dijit.byId('interest_rate').attr("value",0);
			dijit.byId('interest_rate').set("readOnly",true);
		}
	}
}
function calCulateFixedPeriod(){
	var total_paid_install = dijit.byId('total_installamount').get('value');
	deposit = dijit.byId('deposit').get('value');
	if(isNaN(deposit)){deposit=0;}
	if(total_paid_install == 0){//មិនមានតារាងរំលស់ខាងក្រោម
		amount_principal = dijit.byId('sold_price').get('value');
	}else{//មានតារាងរំលស់ខាងក្រោម
		amount_principal = dijit.byId('sold_price').get('value')-dijit.byId('total_installamount').get('value');
	}	
	//dijit.byId('remain_balance').attr('value',amount_principal);
	if(dijit.byId("old_paymentmethod").get("value")==1 && total_paid_install!=0 ){
		amount_principal = amount_principal;
	}
	dijit.byId('fixed_payment').set('readOnly',false);
	dojo.byId('lbl_property_price').innerHTML="<?php echo $tr->translate("AMOUNT_GRAICE_PARIOD")?>";
	debt_term=30;
	collect_term = 1;
	collect_amount = 1;
	collect_term=30;
	debt_amount = dijit.byId('period').get('value')*<?php echo $install_month;?>;
	
	term = (debt_term*debt_amount)/(collect_term*collect_amount);
	interest_rate=dijit.byId('interest_rate').get('value')/<?php echo 12;//$install_month;?>/(100);//(100/30day)
	if(interest_rate==0){
		amount_payment = parseFloat(amount_principal/debt_amount);
		//amount_payment = amount_payment.toFixed(2);
		if(amount_payment=='Infinity' || amount_payment=='NaN'){amount_payment=0;}
	}else{
		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
		//amount_payment = amount_payment.toFixed(0);
		if(isNaN(amount_payment)){amount_payment=0;
		}
	}		
	dijit.byId('for_installamount').attr('value',amount_principal);
	amount_payment = Math.ceil(amount_payment);
	dijit.byId('fixed_payment').attr('value',amount_payment);
	
	if( dijit.byId('install_type').get('value')==2){
		dijit.byId('fixed_payment').attr('value',0);
		dijit.byId("fixed_payment").set("readOnly",false);
	}
}
function calculateDiscount(){
	total_sold = dijit.byId('total_sold').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	bdiscount_percent = dijit.byId('bdiscount_percent').get('value');
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	if(isNaN(bdiscount_percent)){
		bdiscount_percent=0;
	}
	discount_percent=parseFloat(discount_percent)+parseFloat(bdiscount_percent);
	
	bdiscount_fixed = dijit.byId('bdiscount_fixed').get('value');
	discount = dijit.byId('discount').get('value');
	if(isNaN(discount)){
		discount=0;
	}
	if(isNaN(bdiscount_fixed)){
		bdiscount_fixed=0;
	}
	discount = parseFloat(discount)+parseFloat(bdiscount_fixed);

	discount_percent = parseInt(total_sold*discount_percent/100);
	total_sold = total_sold-discount_percent-discount;
	
	if(dijit.byId('old_paymentmethod').get('value')==1){
		//total_sold = total_sold-dijit.byId('paid_before').get('value');
	}
	dijit.byId('sold_price').attr('value',total_sold);
	//dijit.byId('remain_balance').attr('value',total_sold);
	Balance();
}
function Balance(){
	price = dijit.byId('sold_price').get('value');
	deposit =dijit.byId('deposit').get('value');
	paid_before = dijit.byId("paid_before").get("value");
	
	if(isNaN(deposit)){
		deposit=0;
	}
	if((deposit+paid_before)>price){
		alert("ប្រាក់បង់មិនអាចធំជាងតម្លៃលក់បានទេ!");
		dijit.byId('deposit').focus();
		dijit.byId('deposit').attr('value',price-paid_before)
		dijit.byId('balance').attr('value',0)
	}else{ 
		schedule_opt = dijit.byId('schedule_opt').get('value');
		if(schedule_opt==2){
			dijit.byId('balance').attr('value',0);
		}else{
			if(schedule_opt==3){
				dijit.byId('for_installamount').attr('value',price-deposit);
			}
			paid_before = dijit.byId('paid_before').get('value');
			if(isNaN(paid_before)){paid_before=0;}
			dijit.byId('balance').attr('value',price-deposit-paid_before);
		}
		//checkScheduleOption();
	}
}
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	getAllPropertyBranch(branch_id);
	getAllClientByBranch(branch_id);
	getAllSaleNumber(branch_id);
	getBranchInfo(branch_id);
}
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){//used
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_code').set('store', property_store);
		},
		error: function(err) {
		}
	});
} 
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
/*var url_getclientnum = '<?php //echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}*/
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
		},
		error: function(err) {
			//alert(err);
		}
	});
}

var url_getreceipt = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-receipt-number')); ?>';
function getReceiptByBranch(condition){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('receipt').attr('value',data);
			if(condition==1){
			}
		},
		error: function(err) {
			//alert(err);
		}
	});
}
    function calCulatorBalance(){
    	price = dijit.byId('land_price').get('value');
    	deposit =dijit.byId('deposit').get('value');
    	if(isNaN(deposit)){
    		deposit=0;
    	}
    	if(deposit>price){
    		alert("Deposit can not biger than price ");
    		dijit.byId('deposit').focus();
    		dijit.byId('deposit').attr('value',price)
    	}
        dijit.byId('balance').attr('value',price-deposit);
        checkScheduleOption();
    }
    
    function checkValidateDate(){
		return true;
     }
    function setDefaultPaymentAmount(){
    	amount_principal = dijit.byId('land_price').get('value');
    	debt_term = dijit.byId('pay_every').get('value');
    	debt_amount = dijit.byId('period').get('value')*<?php echo $install_month;?>;
    	if(debt_term==1){
    		debt_term=1;
    	}else if(debt_term==2){
    		debt_term=7;
    	}
    	else{
    		debt_term=30;
    	}
    	//collect_term = dijit.byId('collect_termtype').get('value');
		collect_amount = 1;
		if(collect_term==1){
			collect_term=1;
    	}else if(collect_term==2){
    		collect_term=7;
    	}
    	else{
    		collect_term=30;
    	}
		
    	term = (debt_term*debt_amount)/(collect_term*collect_amount);

		interest_rate=dijit.byId('interest_rate').get('value')/100;

		top_pow = Math.pow((1+interest_rate),term);
		bellow = Math.pow((1+interest_rate),(term))-1;
		
		amount_payment = (amount_principal*interest_rate*top_pow)/(bellow);
	}
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	function doPrint() {
		dojo.byId("innerdivPrint1").innerHTML = dojo.byId('divPrint').innerHTML;
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML<?php if($this->data['showreceipt']>1){ ?> + dojo.byId('divPrint1').innerHTML<?php }?>;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
		printSubmit();
		hideDialog();
	}
	function printSubmit(){
		$('#frm_add_tran').submit();
	}
	function displayNone(){
		document.getElementById('divPrint1').style.display="none";
	}
</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");
dojo.require("dijit.form.Textarea");


var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_name));?> );
var client_number_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_code));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );
var property_store  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	 ready(function(){
		setFirstPaymentAndDateLine(3,<?php echo date('d-m-Y');?>,1);
		<?php if(!empty($this->rsresult)){?>
		dijit.byId('branch_id').attr('value','<?php echo $this->rsresult['branch_id'];?>');
		filterClient();
		<?php }?>
		dijit.byId('schedule_opt').attr('value',4);
		checkScheduleOption();
		<?php if($this->data['enable_receipt']==1){?>
			dijit.byId("receipt").set("readOnly",false);
		<?php }?>
	  });
	 
	new dijit.form.FilteringSelect({
			store: property_store,//dojo.data.ObjectStore({objectStore: client_data}),
			autoComplete: true,
			required: false,		           
			name: "land_code",
			id: "land_code",
			searchAttr: "name",
			class: 'fullside',
			required:true,
			onChange: function() {
				land_code = dijit.byId('land_code').get('value');
				if(land_code==-1){
				}else{
					getlandinfo();
				}
		}
			}, "land_code");
	 
	new dijit.form.FilteringSelect({
	store: client_store,//dojo.data.ObjectStore({objectStore: client_data}),
	autoComplete: true,
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	required:true,
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			showPopupclient();
		}else{
			//dijit.byId('customer_code').attr('value',member);
			getcustomerinfo(member);
		}
}
	}, "member");
/*	
	new dijit.form.FilteringSelect({
	store: client_number_store,//dojo.data.ObjectStore({objectStore: client_number}),
	autoComplete: true,
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			showPopupclient();
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");*/

	new dijit.form.FilteringSelect({
		store: co_store,//dojo.data.ObjectStore({objectStore: client_number}),
		autoComplete: false,
		queryExpr: "*${0}*",          
		required: false,		           
		name: "loan_number",
		id: "loan_number",
		searchAttr: "name",
		class: 'fullside',
		onChange: function(){
			getInfoByLoanNumber();
	    }
		}, "loan_number");

	});
</script>
<script type="text/javascript">
var url_getcustomer = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclient')); ?>';
function getcustomerinfo(client_id){
	dojo.xhrPost({
		url:url_getcustomer,	
		content:{ 
		    'client_id':client_id
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('joint_with').attr('value',data.hname_kh);
		},
		error: function(err) {
			alert(err);
		}
	});
}
function calculateDuration(type=null){
	<?php if($autocalcualte==1){// 1 auto calculate date ,0 no calculate?>
	if(type==1){
		sold_price = dijit.byId('for_installamount').get('value');
		interest_rate= dijit.byId('interest_rate').get('value')/12/(100);
		fixed_payment = dijit.byId('fixed_payment').get('value');
		if(interest_rate>0){
			if(isNaN(interest_rate)){interest_rate=0;}
			
			pi = (parseFloat(fixed_payment)-(parseFloat(sold_price)*parseFloat(interest_rate)));
			s = parseFloat(fixed_payment);
			top_ii = Math.log(s/pi);
	
			var duration =  Math.ceil(top_ii / Math.log(1+ parseFloat(interest_rate)));// ROUND UP
			duration = duration/<?php echo $install_month;?>;//year 
		}else if(interest_rate==0){
			duration = sold_price/fixed_payment;
			duration = parseInt(duration);
		}
		dijit.byId('period').attr('value',duration);
	}
	<?php }?>
}

var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getInfoByLoanNumber(){
	loan_id = dijit.byId('loan_number').get('value');
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'sale_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {
			total_principal= data.total_principal;
			if(isNaN(total_principal) || total_principal==null){total_principal=0;}
		    paid_amount = data.paid_amount;
			if(isNaN(paid_amount) || paid_amount==null){paid_amount=0;}
			total_principal = parseFloat(total_principal);
			
			dijit.byId('sale_code').attr('value',data.sale_number);
			 <?php if($this->data['note_agreement']==1){?>
				dijit.byId('note_agreement').attr('value',data.note_agreement);
			 <?php }?>
			dijit.byId('amount_build').attr('value',data.amount_build);
			dijit.byId("start_building").attr('value',data.build_start);
			dijit.byId("agreement_date").attr('value',data.agreement_date);
			dijit.byId("member").attr('value',data.client_id);
			
			dijit.byId('land_code').attr('value',data.house_id);
			dijit.byId('member').set('readOnly',true);
			dijit.byId('bdiscount_percent').attr('value',data.discount_percent);
			dijit.byId('bdiscount_fixed').attr('value',data.discount_amount);
			dijit.byId('paid_before').attr('value',data.total_principal);

			
			
			price_before = data.price_before;
			paid_amount = data.total_principal;
			discount_percent = parseFloat(data.discount_percent)*parseFloat(price_before)/100;
			balance_before = parseFloat(price_before)-parseFloat(paid_amount)-parseFloat(discount_percent);
			
			//dijit.byId('balance_before').attr('value',balance_before);
			dijit.byId('balance_before').attr('value',data.price_sold-paid_amount);
			if(data.payment_id==1){
				dijit.byId('sold_price').attr('value',data.price_sold);//ok
			}else{
				dijit.byId('sold_price').attr('value',data.price_sold-data.paid_amount);
			}
			dijit.byId('old_paymentmethod').attr('value',data.payment_id);
			//alert(data.payment_id);
			
			dijit.byId('house_price').attr('value',parseFloat(data.price_sold));
			//dijit.byId('house_price').attr('value',parseFloat(data.paid_amount)+parseFloat(balance_before));
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
var sale_number_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getsalenumber = "<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-sale-number')); ?>";
function getAllSaleNumber(branch_id){//used
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			sale_number_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('loan_number').set('store',sale_number_store); 
		    <?php if(!empty($this->rsresult)){?>
		    	dijit.byId('loan_number').attr('value','<?php echo $this->rsresult['id'];?>');
		    <?php }?>

		},
		error: function(err) {
			
		}
	});
}
var url_getlandinfodetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfo(){
	dijit.byId('total_sold').attr('value',0);
	//dijit.byId('sold_price').attr('value',0);
	dojo.xhrPost({
		url:url_getlandinfodetail,	
		content:{ 
		    'land_id':dijit.byId('land_code').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('land_code').set('readOnly',true);
			dijit.byId('paid_before').set('readOnly',true);
			dijit.byId('balance_before').set('readOnly',true);
			dijit.byId('total_sold').attr('value',data.price);
			dojo.byId('land_information').innerHTML ="លេខផ្ទះ/ឡូតិ៏  "+data.land_address+", លេខផ្លូវ  "+data.street+", ប្រភេទ  "+data.property_type+", ទំហំ "+data.land_size+" ម៉ែត្រការ៉េ, បណ្តោយ "+data.height+" ម៉ែត្រ, ទទឹង  "+data.width+" ម៉ែត្រ";
			paid_before = dijit.byId('paid_before').get('value');
			dijit.byId('propertype').attr('value',data.house_type);
			//dijit.byId('balance_before').attr('value',data.price-paid_before);
			//dijit.byId('sold_price').attr('value',data.price-paid_before);
			
			checkScheduleOption();
			Balance();
			
		},
		error: function(err) {
			alert(err);
		}
	});
}
function clearTextBox(){
	dijit.byId('member').set('value','');
	dijit.byId('total_amount').set('value',0);
}
function getClientInfo(type){
	if(type==1){
		//customer_code= dijit.byId('customer_code').get('value');
		//dijit.byId('member').attr('value',customer_code);
	}else{
		//customer_code= dijit.byId('member').get('value');
		//dijit.byId('customer_code').attr('value',customer_code);
	}
}
var url_submitdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'add-newdistrict')); ?>';
function addNewDistrict(){
		dojo.xhrPost({
	    url: url_submitdistrict,	
		form: dojo.byId("form_district"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_district').reset(); 
			dijit.byId('frm_district').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'add-newcommune')); ?>';
function addNewCommune(){
		dojo.xhrPost({
	    url: url_submitcommune,	
		form: dojo.byId("form_commune"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_commune').reset(); 
			dijit.byId('frm_commune').hide();
		},
		error: function(err) {
			alert("Your message could not be sent, please try again!.");
		}
	});
}
var url_submitvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'add-newvillage')); ?>';
function addNewVillage(){
		dojo.xhrPost({
	    url: url_submitvillage,	
		form: dojo.byId("form_village"),		    
		handleAs:"json",
		load: function(data) {	
			dojo.byId('form_village').reset(); 
			dijit.byId('frm_village').hide();
		},
		error: function(err) {
		alert("Your message could not be sent, please try again!.");
				        
		}
	});
}
</script>
<script>
function checkFirstRecord(){
	var rowId = $('#identity').val();
	if(rowId!=''){
		var rowIDArray = rowId.split(',');
		for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
				paid = dijit.byId('deposit').get('value');
				if(total_amountpayment<paid){alert("សូមបញ្ជូលប្រាក់ត្រូវបង់ ធំជាងប្រាក់ដែលទទួលបាន! ");dijit.byId('percent'+rowIDArray[n]).focus();return false;}
			}
		}
  }
}
col=0;no=0;title=0;temp='';
var steppayoption = '<?php echo $this->stepoption;?>';
function addRow(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	if(payment_method==4){addInstallment();}//រំលស់
	if(payment_method ==4 || payment_method==3 || payment_method==2 || payment_method==1){return false;}
	
	period = dijit.byId('period').get('value');
	if(period==0 || isNaN(period)){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}

	no=0;title=0;temp='';$('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="color:#000;background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);
	
	for(i=1;i<=period;i++){
		if(payment_method==6 || payment_method==5){
			col++;no++;
			template='';
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_AGREE");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				//if(payment_method==5){
					temp+='<th><?php echo $tr->translate("TYPE");?></th>';
				//}
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;		
				epx_date = dijit.byId("first_payment").get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+1;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;
				}
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td style='width:100px;'><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input type="text" class="fullside" required="true" data-dojo-type="dijit.form.NumberTextBox" id="percent_agree'+col+'" name="percent_agree'+col+'" /></td>';
				template+='<td><input type="text" onkeyup="calCulateAmount('+col+')" class="fullside" required="true" data-dojo-type="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input class="fullside"  onkeyup="calCulateAmount('+col+',2)" type="text" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				//if(payment_method==5){
					template+='<td width="140px"><select class="fullside" dojoType="dijit.form.FilteringSelect" id="pay_with'+col+'" name="pay_with'+col+'" >'+steppayoption+'</select></td>';			
				//}
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
	}
	dijit.byId("date_line").attr('value',epx_date);
}
function addInstallment(){
	result = checkFirstRecord();
	if(result==false){return false;}
	payment_method = dijit.byId('schedule_opt').get('value');
	
	period = dijit.byId('period').get('value');
	
	if(period==0){alert("សូមបញ្ជូលចំនួនដង ត្រូវបង់!");dijit.byId('period').focus();return false;}
	period = dijit.byId('period').get('value')*<?php echo $install_month;?>;
	temp='';

	result = checkFirstRecord();
	if(result==false){return false;}
	
		if(payment_method==4){
			col++;no++;
			template='';
			if(title!=1){    
				tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
				tmp+='<tr id="head-title" class="head-td" style="color:#000;background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
				tmp+='</table>';
				dojo.query("#showrecord").append(tmp);
				
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE_PAYMENT");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_AGREE");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("PERCENT_PAID");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("OS_AMOUNT");?></th>';
				temp+='<th><?php echo $tr->translate("TYPE");?></th>';
				temp+='<th><?php echo $tr->translate("REMARK");?></th>';
				dojo.query("#head-title").append(temp);
				title=1;
				epx_date ='<?php echo date('Y-m-d');?>';
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;

				mm_nextmonth = a.getMonth()+3;
				if(mm_nextmonth<10){
					mm_nextmonth = "0"+mm_nextmonth;
				}
				
				var start_date = y + '-'+ mm_nextmonth + '-'+dd ;
				dijit.byId("first_payment").attr('value',start_date);
			}
			    dijit.byId("release_date").attr('value',epx_date);
				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input type="text" class="fullside" data-dojo-type="dijit.form.NumberTextBox" id="percent_agree'+col+'" name="percent_agree'+col+'" /></td>';
				template+='<td><input onkeyup="calCulateAmount('+col+')" class="fullside" type="text" required="true" data-dojo-type="dijit.form.NumberTextBox" id="percent'+col+'" name="percent'+col+'" /></td>';	//data-dojo-props='+'regExp:"[0-9]{1,2}"'+'		
				template+='<td><input onkeyup="calCulateAmount('+col+',2)" class="fullside" type="text" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td width="140px"><select class="fullside" dojoType="dijit.form.FilteringSelect" id="pay_with'+col+'" name="pay_with'+col+'" >'+steppayoption+'</select></td>';
				template+='<td <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';
			tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
			tmp+="</tr>";
			dojo.query("#table_row").append(tmp);
		
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
		}
}

function calCulateAmount(index,revers=1){
	balance = dijit.byId('sold_price').get('value');
	if(revers==1){//% to value
	    percent = dijit.byId('percent'+index).get('value');
	    old_paymentmethod = dijit.byId("old_paymentmethod").get("value");
	    if(old_paymentmethod==1){ balance = parseFloat(dijit.byId('sold_price').get('value'));}
	    amount_payment = parseInt(balance*percent/100);
	    dijit.byId('total_payment'+index).attr('value',amount_payment);
	    dijit.byId('percent_agree'+index).attr('value',percent);
   }else{//value to %
	   amount_payment =  dijit.byId('total_payment'+index).get('value');
	   percent = amount_payment*100/balance;
	   dijit.byId('percent'+index).attr('value',percent);
	   dijit.byId('percent_agree'+index).attr('value',percent);
     }
	calCulateSchedulePayment();
	 if(dijit.byId('percent'+index).get('value')>100){
		 alert("តម្លៃត្រូវបង់មិនអាចធំជាង ១០០ ភាគរយបានទេ !");
		 dijit.byId('percent'+index).focus();
     }
}
function calCulateSchedulePayment(){
	var total_amount=0;
	var rowId = $('#identity').val();
	var rowIDArray = rowId.split(',');
	total_firstrecord = 0;
	if(rowId!=''){
		for(var n = 0; n < rowIDArray.length; n++) {
			total_amountpayment = (dijit.byId('total_payment'+rowIDArray[n]).get('value'));
			if(n==0){ 
				total_firstrecord = total_amountpayment;
			}
			if(isNaN(total_amountpayment)){
				total_amountpayment = 0;
			}
			total_amount = total_amount+ total_amountpayment;
		}
	}
	dijit.byId('total_installamount').attr('value',total_amount);
	total_paidbefore = dijit.byId("paid_before").get("value");
	paid_new = total_firstrecord - total_paidbefore;
	dijit.byId('deposit').attr('value',paid_new);
	
	//total_sold = dijit.byId("sold_price").get("value");
	//total_amount = total_sold-total_amount;
	
	Balance();
	calCulateFixedPeriod();
}
function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
	if(arrays.length==0){ dijit.byId('total_installamount').attr('value','');}
	calCulateSchedulePayment();
}
function setFirstPaymentAndDateLine(pay_term,date_release,amount_date){
	var a = new Date(date_release);
	mm = a.getMonth()+amount_date+1;
   
	 var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear()+1;

	var epx_date = y + '-'+ mm + '-'+dd ;
	calCulateEndDate();
	calCulateFirstPayment();
}
function calCulateEndDate(){
	amount_date = dijit.byId('period').get('value')*<?php echo $install_month;?>;
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
		dijit.byId('date_line').attr('value','<?php echo date("Y-m-d");?>');
	}else{
		var a = new Date(release_date);
		month = a.getMonth()+amount_date;
		mm = month%12;
		year = parseInt(month/12);
		 var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		 if(mm<10){
			 mm = "0"+mm;
		}
		var y = a.getFullYear()+year;
		var epx_date = y + '-'+ mm + '-'+dd ;
		dijit.byId('date_line').attr('value',epx_date);	
    }
}
function CalculateDate(){
	pay_term = 1;
	amount_date = dijit.byId('period').get('value');
	release_date = dijit.byId("first_payment").get('value');//just update follow by first payment
	if(isNaN(amount_date)){
	}else{
		setFirstPaymentAndDateLine(pay_term,release_date,amount_date);		
    }
}
function checkReleaseDate(){
	CalculateDate();
}
function getFirstPayment(){
	calCulateFirstPayment();
}
function calCulateFirstPayment(){
	pay_term = 1;
	amount_date = 1;
	method_id = dijit.byId('schedule_opt').get('value');
	addamount=1;
	if(method_id==3 || schedule_opt==6){
		addamount=0;
	}
	release_date = dijit.byId("release_date").get('value');
	var a = new Date(release_date);
		mm = a.getMonth()+amount_date+addamount;
	var dd = a.getDate();
	 if(dd<10){
		 dd = "0"+dd;
	}
	 if(mm<10){
		 mm = "0"+mm;
	}
	var y = a.getFullYear();
	var epx_date = y + '-'+ mm + '-'+dd ;
	dijit.byId('first_payment').attr('value',epx_date);
}
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==""){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data){
			var arr = JSON.parse(data);
			var imagesUrl = '<img class="view" style="height:75px;" src="<?php echo $this->baseUrl()."/images/projects/"?>'+arr.logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;
		},
		error: function(e) {
		}
	});
}
function printSave(new_receipt_no){	
	<?php if($this->data['enable_receipt']==1){?>
		new_receipt_no = dijit.byId("receipt").get('value');
	<?php }?>
	deposit = dijit.byId('deposit').get('value');
	paid_before = dijit.byId("paid_before").get("value");
	if (deposit=='' || deposit==-1){
		alert('សូមបញ្ចូលប្រាក់ត្រូវបង់ ទើបបោះពុម្ភបង្កាន់ដៃបង់ប្រាក់បាន!');
		dijit.byId('deposit').focus();
		return false;
	}
	schedule_opt = dijit.byId('schedule_opt').get('value');
	if(schedule_opt==2){
		sold_price = dijit.byId("sold_price").get("value");
		if(sold_price!=(deposit+paid_before)){
			alert("បង់ផ្តាច់ ប្រាក់ត្រូវបង់ត្រូវស្មើរនិងប្រាក់នៅជំពាក់");
			dijit.byId('deposit').focus();
			return false;
		}
	}
	
	dijit.byId("lbl_schedule").hide();		
	symbal = " $";
	dojo.byId("lbl_project").innerHTML = dijit.byId("branch_id").attr('displayedValue');
	dojo.byId("lb_receipt").innerHTML = dijit.byId("receipt").get('value');
	
	dojo.byId("lb_hourseno").innerHTML = dijit.byId("land_code").attr('displayedValue')+dijit.byId("propertype").attr('displayedValue');
	deposit = dijit.byId("deposit").get("value");
	
	total_paid = deposit+paid_before;
	dojo.byId("lbl_total_paid").innerHTML = dojo.number.format(total_paid,{places:2})+" "+symbal;
	dojo.byId("lblpropertyprice").innerHTML = dojo.number.format(dijit.byId('sold_price').get('value'),{places:2})+" "+symbal;//dijit.byId("schedule_opt").attr('displayedValue');
	begining_balance = dijit.byId('sold_price').get('value')
    total_paidamount =begining_balance-total_paid;
	dojo.byId("lbl_ending_balance").innerHTML = dojo.number.format(total_paidamount,{places:2})+" "+symbal;
	
	dojo.byId("lbl_principle_amount").innerHTML = dojo.number.format(deposit,{places:2})+" "+symbal;
	total_sold = dijit.byId('total_sold').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	bdiscount_percent = dijit.byId('bdiscount_percent').get('value');
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	if(isNaN(bdiscount_percent)){
		bdiscount_percent=0;
	}
	
	bdiscount_fixed = dijit.byId('bdiscount_fixed').get('value');
	discount = dijit.byId('discount').get('value');
	if(isNaN(discount)){
		discount=0;
	}
	if(isNaN(bdiscount_fixed)){
		bdiscount_fixed=0;
	}
	discount = parseFloat(discount)+parseFloat(bdiscount_fixed);
	discount_percent=parseFloat(discount_percent)+parseFloat(bdiscount_percent);
	discount_percent = total_sold*discount_percent/100;
	total_discount = discount_percent+discount;

	//dojo.byId("lb_discount").innerHTML = dojo.number.format(total_discount,{places:2})+" "+symbal;
	dojo.byId("lbl_total_payment").innerHTML =dojo.number.format(deposit,{places:2})+" "+symbal;
	dojo.byId("lb_paid").innerHTML = dojo.number.format(deposit,{places:2})+" "+symbal;
	dojo.byId("lb_noted").innerHTML =dijit.byId("note").get('value');
	schedule_opt = dijit.byId("schedule_opt").get("value");

	date_payment = dijit.byId('paid_date').get('value');
	var format_date_payment = new Date(date_payment);
	day = format_date_payment.getDate();
	month = format_date_payment.getMonth() + 1;
	month = returnMOnth(month);
	year = format_date_payment.getFullYear();
	collect_payment = day+'-'+month+'-'+year;
	dojo.byId("lbl_paid_date").innerHTML = collect_payment;
	dojo.byId("lb_buydate").innerHTML = collect_payment;

	joint_with = dijit.byId("joint_with").attr('displayedValue');
	if(joint_with!=''){joint_with = "/"+joint_with}
	
	dojo.byId("lbl_customer").innerHTML = dijit.byId("member").attr('displayedValue')+joint_with;
	dojo.byId("lb_customer").innerHTML = dijit.byId("member").attr('displayedValue')+joint_with;
	dojo.byId("lbl_paidtimes").innerHTML = 1;
	dojo.byId("lbl_paymenttype").innerHTML = dijit.byId("payment_method").attr('displayedValue');
	document.getElementById('lbl_cheque').innerHTML = dijit.byId('cheque').get('value');

	if(schedule_opt==1){
		//EXPIRED_DATE
	}
	 dijit.byId("terms").show();	
}
function returnMOnth(monthnum){
	var month = new Array();
	month[1] = "Jan";
	month[2] = "Feb";
	month[3] = "Mar";
	month[4] = "Apr";
	month[5] = "May";
	month[6] = "Jun";
	month[7] = "Jul";
	month[8] = "Aug";
	month[9] = "Sep";
	month[10] = "Oct";
	month[11] = "Nov";
	month[12] = "Dec";
	return month[monthnum];
}
var url_previewloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'previewreschedul')); ?>';
function addPreviewLoan(){
	r=0;
	if(dijit.byId('frm_add_tran').validate()){
		client = dijit.byId('member').get('value');
		if (client=='' || client==-1){
			alert('Please Select Client Name !');
			dijit.byId('member').focus();
			return false;
		}

			schedule_opt = dijit.byId("schedule_opt").get("value");
			remain_balance = dijit.byId("for_installamount").get("value");
			if(schedule_opt==6 || schedule_opt==5){ 
				identity = $("#identity").val(); 
				if(identity==''){ 
					alert("សូមបញ្ចូលប្រាក់ដែលអតិថិជននឹងត្រូវបង់!");
					addRow(); return false;
				}
				if(remain_balance!=0){
					alert("ការរៀបចំតារាងត្រូវបង់មិនទាន់គ្រប់ចំនួនទេ។សូមត្រួតពិនិត្យម្តងទៀត !");	
					return false;
				}
			}
			result = checkFirstRecord();
			if(result==false){return false;}
			loading();
		dojo.xhrPost({
		    url: url_previewloan,	
			form: dojo.byId("frm_add_tran"),		    
			handleAs:"json", 
			load: function(data) {
				if(data.row_id=='row_id'){//return 1;
					printSave();
					document.getElementsByClassName("overlay")[0].style.display="none";
					}else{
						  document.getElementsByClassName("overlay")[0].style.display="none";
						  temp='';	
						  fund_title=0;thead='';fund_title=0;
						  temp='<table class="collape tablesorter" style="font-size:13px; width:1000px !important; " id="table">'
						  temp+='<tr style="background:#ccc;"><th><?php echo $tr->translate("NUM");?></th>';
						  temp+='<th><?php echo $tr->translate("ថ្ងៃបង់ប្រាក់");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមគ្រា");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើម");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ការ");?></th>';
						  temp+='<th><?php echo $tr->translate("សរុប");?></th>';
						  temp+='<th><?php echo $tr->translate("ប្រាក់ដើមនៅសល់");?></th>';
						  principal_permonth=0;total_interest=0;total_payment_after=0;
						for(i=0;i<data.length;i++){
							principal_permonth=principal_permonth+parseFloat(data[i].principal_permonth);
							total_interest=total_interest+parseFloat(data[i].total_interest);
							total_payment_after=total_payment_after+parseFloat(data[i].total_payment_after);
					      r++;
						  temp+='<tr><td align="center">'+r+'</td>';
						  var myDate = new Date(data[i].date_payment);
						  d = new Date(data[i].date_name);
						  temp+='<td>'+getDayName(d.getDay())+'-'+data[i].date_payments+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].begining_balance,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(data[i].total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(data[i].total_payment_after,2)+'<b></td>';
						  temp+='<td><b>'+dojo.number.format((data[i].ending_balance),2)+'<b></td>';
						 }
						  temp+='<tr><td align="right" colspan="3" style="border-left:1px solid #fff;border-bottom:1px solid #fff;">&nbsp;សរុប -Total</td>';
						  temp+='<td>'+dojo.number.format(principal_permonth,2)+'</td>';
						  temp+='<td>'+dojo.number.format(total_interest,2)+'</td>';
						  temp+='<td><b>'+dojo.number.format(total_payment_after,2)+'<b></td>';
						  temp+='<td></td>';
						temp+='</table>';
						dojo.byId('t_amountmoneytype').innerHTML = temp;
						dijit.byId("lbl_schedule").show();
					}
				
			},
			error: function(response, ioArgs) {
				alert("មិនអាចមើលតារាងបាន");
				document.getElementsByClassName("overlay")[0].style.display="none";
				//alert("Failed while doing the operation: " + ioArgs.xhr.response);
			}
	   });
	}
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function hideDialog() {		
	dijit.byId("lbl_schedule").hide();
}

function showPopupclient(){
	dijit.byId("frmpop_client").show();
}
var individual_client_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-client'));?>';
function addNewindividual(){
	if(dijit.byId('addclient').validate()){
	dojo.xhrPost({
		url:individual_client_url,	
		form:dojo.byId('addclient'),
		content:{
			'branch_id':1
			},
		handleAs:"json",
		load: function(response) {
			dijit.byId('frmpop_client').hide();	
			var myNewItem = {					
					id: response.id,
					name: dijit.byId('name_en').get('value')+' - '+dijit.byId('name_kh').get('value'),
			};			
			addDataToSelectbox(dijit.byId('member'), client_store, myNewItem, response.id);
			dijit.byId('addclient').reset();
		},
		error: function(err) {
		}
	});
 }	
}
var interestStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->rs_interest));?> );
function addinterest(){
	if(dijit.byId('form_interestrate').validate()){
		var Itemmake = {					
				id: dijit.byId('interest_ratenew').get('value'),
			    name: dijit.byId('interest_ratenew').get('value')
		};		
		addDataToSelectbox(dijit.byId('interest_rate'), interestStore, Itemmake, dijit.byId('interest_ratenew').get('value'));	
		dijit.byId('interest_rate').attr('value',dijit.byId('interest_ratenew').get('value'));
		dijit.byId('frm_interest').reset();
		dijit.byId('frm_interest').hide();
	}
}
function printSubmit(){
	 $('#frm_add_tran').submit();
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
</script>
<style>
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>