<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("ISSUE_SCHEDULE"));
$frm = $this->frm_search;
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'loan','controller'=>'repaymentschedule','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
			   <table width="100%"​​>
			   		<tr>
			   			<td><?php echo $frm->getElement("adv_search");?></td>
			   			<td> <?php echo $frm->getElement('branch_id');?></td>
			   			<td><input id="land_id" /><?php //echo $frm->getElement('land_id');?></td>
			   			<td><?php echo $frm->getElement("client_name");?></td>
			   			<td><?php echo $frm->getElement('schedule_opt');?></td>
			   		</tr>
			   		<tr>
			   			<td><?php echo $frm->getElement('status');?></td>
			   			<td><?php echo $frm->getElement('start_date');?></td>
			   			<td><?php echo $frm->getElement('end_date');?></td>
			   			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			   		</tr>
			   </table>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
function getmemberIdGroup(){
	customer_code= dijit.byId('customer_code').get('value');
	dijit.byId('member').attr('value',customer_code);
}
function checkMember(){
	customer_code= dijit.byId('member').get('value');
	dijit.byId('customer_code').attr('value',customer_code);
}

dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			//dijit.byId('land_id').attr('value','');
			land_id=-1;
	}
		}, "land_id");
	new dijit.form.FilteringSelect({
		name: "branch_id",
		id: "branch_id",
		class: 'fullside',
		autoComplete: false,
		onChange: function() {
			 getAllPropertyBranch();
		}
		}, "branch_id");
	 
});
land_id = '<?php echo $this->search['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		 dijit.byId('land_id').reset();
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    dijit.byId('land_id').reset();
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
} 
</script>