<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$rs = $this->rsexpense;
	
	$images = $this->baseUrl().'/images/logo.png';
	if (!empty($rs['photo'])){
		$images = $this->baseUrl().'/images/projects/'.$rs['photo'];
	}
	
	$montFomat="d-m-Y";
	if(MONTH_FORMATE_DATE_RECEIPT==1){
		$montFomat="d-M-Y";
	}
?>
<title><?php echo $tr->translate("	");?></title>
<div class="reportblog">
	<div class="card-box">
		<div class="col-sm-12 border-botom">
			<div class="col-sm-8 pd-0">
				<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('បង្កាន់ដៃចំណាយ');?></h4>
			</div>
			<div class="col-sm-4 text-right">
			</div>
		</div>
	</div>
	<div id="divPrint" style="width: 100%; padding-top: 30px;">
		<div id="divPrint1" style="width: 100%; height: 12.5cm ; padding: 0px; margin: 0px;">
		<?php 
		echo $this->officailreceipt;
		?>
	</div>

	<div id="divPrint2" style="width: 100%;height: 12.5cm ; padding: 0px; margin: 0px;">
		<div style="border:2px dashed <?php echo $this->data['border_receiptcolor'];?>; vertical-align: middle; margin:40px 0px 30px 0px"></div>
		<div id="printblog2"></div>
	</div>

	</div>
	<div style="clear: both;"></div>
	<div id="noteContent" style="display: none;"><?php echo $this->rs['description'];?></div>
</div>
<script>
require(["dojo/ready"], function(ready){
	 ready(function(){
		 loadingBlock();
		 getBranchInfo();
		 printSave();
		 setTimeout(function () {
			dojo.byId('printblog2').innerHTML = dojo.byId('divPrint1').innerHTML;
	        HideloadingBlock();
	    }, 500);
		 
	 });
});	 
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->rs['branch_id'])?0:$this->rs['branch_id'];?>';
	if(branch_id==""){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img class="view" style="height:80px; max-width: 100%;" src="<?php echo $this->baseUrl()."/images/projects/"?>'+arr.logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;

			document.getElementById('ft_branch_title_lb').innerHTML = arr.footer_title;
			document.getElementById('ft_website_lb').innerHTML = arr.office_website;
			document.getElementById('ft_email_client_lb').innerHTML = arr.office_email;
			document.getElementById('ft_address_lb').innerHTML = arr.office_address;
			document.getElementById('ft_phone_lb').innerHTML = arr.office_tel;
		},
		error: function(e) {
		}
	});
}
function printSave(){
	symbal=" $";
	dojo.byId("lb_receipt").innerHTML = '<?php echo $this->rs['invoice'];?>';
	dojo.byId("lb_invoice").innerHTML = '<?php echo $this->rs['other_invoice'];?>';
	dojo.byId("lb_branch").innerHTML = '<?php echo $this->rs['branch_name'];?>';
	dojo.byId("lb_date").innerHTML = "<?php echo date($montFomat,strtotime($this->rs['date']));?>";
	
	dojo.byId("lb_supplier").innerHTML = '<?php echo $this->rs['supplier_name'];?>';
	dojo.byId("lb_expense_category").innerHTML = '<?php echo $this->rs['category_name'];?>';
	dojo.byId("lbl_paymenttype").innerHTML = '<?php echo $this->rs['payment_method'];?>';
	dojo.byId("lb_cheque").innerHTML = '<?php echo $this->rs['cheque'];?>';
	dojo.byId("lb_expense_title").innerHTML = '<?php echo $this->rs['title'];?>';
	
	var htmlString = $( '#noteContent' ).html();
	$( '#lb_description' ).text( htmlString );
	
	dojo.byId("lb_total_amount").innerHTML = '<?php echo "$ ".number_format($this->rs['total_amount'],2);?>';
}
</script>