<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("CLOSING_OTHER_INCOME");?></title>
<div class="reportblog">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CLOSING_OTHER_INCOME');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('branch_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<input id="land_id" />
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("client_name");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('category_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php //echo $frm->getElement('ordering');?>
					<?php echo $frm->getElement('queryOrdering');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('start_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('is_closed');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
				
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
			</div>
		</div>
	 </form> 
	<div style="min-height:22cm; margin:0 auto;">
		<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
			<tr>
		    	<td align="center">
		    	 <div id="divPrint">
		    	 	<style>
						.style{
							line-height: 20px;font-size: 14px !important;
							font-family: 'Times New Roman','Khmer OS Battambang';
							}
							th{padding: 5px;}
					.hide{visibility: hidden;}
					@media print {
					  div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: 110px;}
					}
					td span {
					line-height: 16px;
				}
				table.content-data{
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:13px;
					font-family: 'Times New Roman','Khmer OS Battambang';
					white-space: nowrap;
					line-height: 22px;
				}
				table.content-data thead tr.style {
				   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #c1d0f3;
				}
				table.tb-footer{
					border-collapse:collapse;
					border:1px solid #000; 
					font-family: 'Times New Roman','Khmer OS Battambang';
					font-size:11px;
				}
				table.tb-footer tr{
				 line-height: 14px;  padding:2px 0px; height: 25px;
				}
				
					</style>
					<div class="divFooter">
		        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
			        	<tr>
			                <td width="25%"><img src="<?php echo $logo;?>" style="max-height:85px;max-width:100%;"></td>
			                <td width="50%" valign="top">
			                <h2 style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-weight:200; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $branch_title;//$tr->translate("BRAND_TITLE");?></h2>
			                <h2 style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-weight:200;font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("CLOSING_OTHER_INCOME");?></h2>
			                <p style="text-align:center; font-size:14px; font-weight:200; font-family:'Times New Roman','Khmer OS Muol Light'"><?php if(!empty($this->search['start_date'])){echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("d-M-Y",strtotime($this->search['end_date']));}?></p>
			                </td>
			                <td width="25%"></td>
			             </tr> 
			          </table>
			          </div>
			          <form id="list" name="list" action="<?php echo $this->url(array('module'=>'report','controller'=>'incomeexpense','action'=>'submitentryincome')); ?>" dojoType="dijit.form.Form" method="post">
						<script type="dojo/method" event="onSubmit" >			
							id_selected = dijit.byId('id_selected').get('value');
							if(id_selected==''){
								alert('No record to close !!! ');
								return false;
							}
							loadingBlock();
							return true;
						</script>
			         <table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
		            	<tr>	
		            	<td colspan="3" id="exportExcel">
		            		<table  class="content-data" border="1" width="100%"  >  
						    	<thead>
						    	<tr class="hide" style="border:1px solid #000;">
						             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						        </tr>
						    	<tr class="style" align="center"  >
									<td>
										<?php 
											$countOtherInc = count($this->row);
											$countHouserepairInc = count($this->houserepair);
											$totalCouunt = $countOtherInc+$countHouserepairInc;
										?>
										<input type="checkBox" onclick="checkAll('<?php echo $totalCouunt;?>');" name="checkall" id="checkall" />
										<input type="hidden" name="id_selected" id="id_selected" dojoType="dijit.form.TextBox" />
										<?php echo $tr->translate("NUM");?>
									</td>
								    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
								    <td><?php echo $tr->translate("INCOME_TITLE");?></td>
								    <td><?php echo $tr->translate("RECEIPT_NO");?></td>
								    <td><?php echo $tr->translate("CLIENT_NAME");?></td>
								    <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
								    <td><?php echo $tr->translate("CATEGORY");?></td>
								    <td><?php echo $tr->translate("TOTAL_INCOME");?></td>
								    <td><?php echo $tr->translate("CHEQUE");?></td>
								    <td><?php echo $tr->translate("NOTE");?></td>
								    <td><?php echo $tr->translate("DATE");?></td>
								    <td><?php echo $tr->translate("BY_USER");?></td>
								     <td><?php echo $tr->translate("STATUS");?></td>
								</tr>
								</thead>
						       <?php $branch_id=''; $n=0; $i=0; $total=0; if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
								<tr class=""  align="left">
								   <td align="center">&nbsp;
										<input style="height: 15px;margin-top: 5px;" type="checkBox" onClick="checked_id(<?php echo $i;?>)" name="check_box<?php echo $i;?>" id="check_box<?php echo $i;?>" />
							            <input type="hidden" id="id_<?php echo $i;?>" name="id_<?php echo $i;?>" value="<?php echo $row['id'];?>" dojoType="dijit.form.TextBox" />
										<input type="hidden" id="type_record<?php echo $i;?>" name="type_record<?php echo $i;?>" value="1" dojoType="dijit.form.TextBox" />
								   <?php echo $i; ?>&nbsp;
								   </td>
								   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
								   <td align="center" style="min-width: 120px;max-width: 150px;">
								   		&nbsp;
								   		<a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt-otherincome','id'=>$row['id']));?>">
								   		<?php echo $row['title'];?>
								   		</a>
								   		&nbsp;
								   	</td>
								   <td align="center">
								   		&nbsp;
									   	<a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt-otherincome','id'=>$row['id']));?>">
									   	<?php echo $row['invoice'];?>
									   	</a>
									   	&nbsp;
								   	</td>
								   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['client_name'];?>&nbsp;</td>
								   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['house_name'];?>&nbsp;</td>
								   <td style="white-space: nowrap;">&nbsp;<?php echo $row['category_name'];?></td>
								   <td align="center">&nbsp;<strong><?php echo number_format($row['total_amount'],2);?></strong>&nbsp;</td>
								   <td align="center">&nbsp;<?php echo $row['cheque'];?>&nbsp;</td>
								   <td align="center">&nbsp;<?php echo $row['description'];?>&nbsp;</td>
								   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-M-Y",strtotime($row['date']));?>&nbsp;</td>
								    <td align="center">&nbsp;<?php echo $row['user_name'];?>&nbsp;</td>
								    <td class="">&nbsp;<?php echo($row['is_closed']==0)?"Unclose":"Closed";?>&nbsp;</td>
								</tr>
									<?php $total = $total +$row['total_amount'];?>
								<?php }?>
								<?php 
					            	if (!empty($this->houserepair)){
					            ?>
					            <tr  style="border:1px solid #000;">
					                <td colspan="12" align="center">
					                	<h2 style="font-weight:normal; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'">
							             	<span><?php echo $tr->translate("REPAIR_HOUSE_INCOME");?></span>
							             </h2>
					                </td>
					             </tr>
					            <?php foreach ($this->houserepair as $index => $rs){ $i++;?>
						   		<tr  class=" stylehover <?php //if($index%2==1){echo"even";}?>" style=" <?php if ($rs['status']==0){ echo "background: #f7c6c6;";}?>  font-family: 'Times New Roman','Khmer OS Battambang';white-space: nowrap;" width="100%">
				               		<td style="text-align: center;">
										<input style="height: 15px;margin-top: 5px;" type="checkBox" onClick="checked_id(<?php echo $i;?>)" name="check_box<?php echo $i;?>" id="check_box<?php echo $i;?>" />
							            <input type="hidden" id="id_<?php echo $i;?>" name="id_<?php echo $i;?>" value="<?php echo $rs['id'];?>" dojoType="dijit.form.TextBox" />
										<input type="hidden" id="type_record<?php echo $i;?>" name="type_record<?php echo $i;?>" value="2" dojoType="dijit.form.TextBox" />
									<?php echo $index+1; ?>&nbsp;
									
									</td>
				               		<td align="center">&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
				               		<td align="center">&nbsp;<a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt-otherincome','id'=>$rs['id']));?>?repair=1"><?php echo $rs["title_income"];?></a>&nbsp;</td> 
				               		<td align="center">&nbsp;<a target="_blank" style="<?php if ($rs['status']==0){ echo "color:red;";}else{ echo "color:#000;";}?>text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt-otherincome','id'=>$rs['id']));?>?repair=1"><?php echo $rs["invoice"];  if ($rs['status']==0){ echo " ".$tr->translate("មោឃៈ");}?></a>&nbsp;</td>
				               		<td align="center">&nbsp;<a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt-otherincome','id'=>$rs['id']));?>?repair=1"><?php echo $rs["name_kh"];?></a>&nbsp;</td> 
				               		<td align="center">&nbsp;<?php echo $rs["land_address"]." (".$rs["street"].")";?>&nbsp;</td>
				               		<td valign="top">&nbsp;<?php echo $rs["category"];?>&nbsp;</td>
				               		<td align="center">&nbsp;<strong><?php  if ($rs['status']==0){ echo "-";}else{ echo number_format($rs["total_amount"],2);}?></strong>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["cheque"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["description"];?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date"]));?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php echo $rs["user_name"];?>&nbsp;</td>
									<td class="">&nbsp;<?php echo($rs['is_close']==0)?"Unclose":"Closed";?>&nbsp;</td>
				                </tr>
				                <?php 
				                if ($rs['status']==0){
				                }else{
				               		 $total = $total +$rs['total_amount'];
					            }?>
						   		<?php }?>
					            <?php }?>
						    </table>
		            	</td>
		            </tr>
		            <tr style=" border-bottom: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;">
						<td colspan="11">
							<table align="right" style="margin-right: 6px;">
								  <tr style="font-size:10px; color:#000; height: 18px;"​ align="center">
									<td style="width:146px;  font-size: 16px;">&nbsp;<?php echo $tr->translate('TOTAL_INCOME');?>&nbsp;</td>
									<td style="background: rgba(249, 225, 11, 0.7); color:#000; width:112px; font-size: 14px;"><strong>$ <?php echo number_format($total,2);?></strong></td>
								  </tr>
							</table>
						</td>
					</tr>
					<tr style=" border-bottom: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;">
						<td colspan="11" align="center">
							 <button iconclass="dijitIconSave" dojoType="dijit.form.Button" showLabel="true" type="submit">Closing Entry</button>
						</td>
					</tr>
		            </table>
		           
		            </form>
					<br />
					<?php echo $this->footerReport;?>
					</div>
		    	</td>
		    </tr>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<?php $urlprint = $this->baseUrl()."/report/incomeexpense/receipt-otherincome/id/";?>
 <script>
 dojo.require("dojo.data.ItemFileWriteStore"); 
 var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
 require(["dojo/ready"], function(ready){
 	ready(function(){
 		 getAllPropertyBranch();
 	});
 	new dijit.form.FilteringSelect({
 		store: property_store,
 		required: false,
 		autoComplete: false,
 		queryExpr: "*${0}*",
 		name: "land_id",
 		id: "land_id",
 		value:-1,
 		searchAttr: "name",
 		class: 'fullside fullside50',
 		onChange: function() {
 			land_id=-1;
 	}
 		}, "land_id");
 });
 land_id = '<?php echo $this->rssearch['land_id']?>';
 var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
 function getAllPropertyBranch(branch_id){
 	branch_id = dijit.byId('branch_id').get('value');
 	if(branch_id<0){
 		return false;
 	}
 	dojo.xhrPost({
 		url:url_getland,	
 		content:{ 
 		    'branch_id':branch_id,
 		    'action':1
 		},		    
 		handleAs:"json",
 		load: function(data) {
 			property_store  = getDataStorefromJSON('id','name', data);		
 		    dijit.byId('land_id').set('store', property_store);
 		    if(land_id>0){
 		    	dijit.byId('land_id').attr('value',land_id);
 			 }
 		},
 		error: function(err) {
 		}
 	});
 } 

 var row=0;
 var url="";
 var typeprint=0;
 $(function(){
 	$.contextMenu({
 		selector: '.context-menu-one', 
 		callback: function(key, options) {
 			var m = "clicked: " + key;
 			if(key=="print"){
 				url='<?php echo $urlprint;?>';
 			
 			}
 			gotoAction();
 		},
 		items: {
 			"print": {name: "<?php echo $tr->translate("PRINT");?>", icon: "fa-print", accesskey: "c o p y"},
 		}
 	});
 });
 function setrowdata(index,typeri){
 	row = index;
 	typeprint = typeri;
 }
 var recordid ='';
 function gotoAction(){
	 if(typeprint==1){
		 window.open(url+row+'?repair=1', '_blank');
	 }else{
 	 	window.open(url+row+'?rightclick=true', '_blank');
	 }
 }


 
function checkAll(array_length){
	dijit.byId('id_selected').attr('value','');
	if(dojo.byId('checkall').checked){
		for(var j=1;j<=array_length;j++){
			$('#check_box'+j).each(function() { 
				this.checked = true;  
			});
			checked_id(j);
		}
	}else{
		for(var j=1;j<=array_length;j++){
			$("#check_box"+j).removeAttr("checked");
			checked_id(j);
		}
	}
}

function checked_id(index){
	row_id = index;//dijit.byId('id_'+index).get('value');
	if(dojo.byId('check_box'+index).checked){
		if($("#id_selected").val()!="") {
			var identity = $("#id_selected").val();
			$("#id_selected").val(identity+','+row_id);
		}else{
			$("#id_selected").val(row_id);
		}
	}else{
		var identity = $('#id_selected').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == row_id) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#id_selected').val(strings);
	}
}
 </script>
