<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_INCOME");?></title>
<div class="reportblog">	
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('REPORT_INCOME');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'incomeexpense','action'=>'rpt-income')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('branch_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<input id="land_id" />
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("client_name");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('category_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('queryOrdering');?>
					<?php //echo $frm->getElement('ordering');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('start_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				</div>
				
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button class="button-class button-primary " iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
				
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
			</div>
		</div>
	 </form> 
	<div style="min-height:22cm; margin:0 auto;">
		<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
			<tr>
		    	<td align="center">
		    	 <div id="divPrint">
		    	 	<style>
						th{padding: 5px;}
						.hide{visibility: hidden;}
						@media print {
							  div.divFooter {
								position: fixed;
								top: 0;
								width: 100%;
								height: 100px;
								bottom:0px;
								margin:0;
							  }
							.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						}
						table tr td{
							padding: 1px;
						}
					
						table.content-data { page-break-inside:auto }
						table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
						table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:13px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
						}
						table.content-data thead tr.style {
						   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 30px; 
							background: #c1d0f3; font-weight: bold;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
						table tr td{
							padding:0 2px;
						}
					</style>
					<div class="divFooter">
						<?php echo $this->headerReport;?>
					</div>
			         <table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
		            	<tr>	
		            	<td colspan="3" id="exportExcel">
		            		<table  class="content-data" border="1" width="100%"  >  
						    	<thead>
						    	<tr class="hide" style="border:1px solid #000;">
						             <td colspan="13" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						        </tr>
						    	<tr class="style" align="center"  >
									<td scope="col" ><?php echo $tr->translate("NUM");?></td>
								    <td scope="col" ><?php echo $tr->translate("BRANCH_NAME");?></td>
								    <td scope="col" ><?php echo $tr->translate("INCOME_TITLE");?></td>
								    <td scope="col" ><?php echo $tr->translate("RECEIPT_NO");?></td>
								    <td scope="col" ><?php echo $tr->translate("CLIENT_NAME");?></td>
								    <td scope="col" ><?php echo $tr->translate("PROPERTY_CODE");?></td>
								    <td scope="col" ><?php echo $tr->translate("CATEGORY");?></td>
								    <td scope="col" ><?php echo $tr->translate("TOTAL_INCOME");?></td>
								    <td scope="col" ><?php echo $tr->translate("PAYMENT_TYPE");?></td>
								    <td scope="col" ><?php echo $tr->translate("NUMBER");?></td>
								    <td scope="col" ><?php echo $tr->translate("NOTE");?></td>
								    <td scope="col" ><?php echo $tr->translate("DATE");?></td>
								    <td scope="col" ><?php echo $tr->translate("BY_USER");?></td>
								</tr>
								</thead>
						       <?php $branch_id=''; $n=0; $i=0; $total=0; if(!empty($this->row)) foreach($this->row as $key =>$row){ $i++;?>
								<tr class="context-menu-one" oncontextmenu="setrowdata('<?php echo $row['id'];?>');return false;" align="left">
								   <td data-label="<?php echo $tr->translate("NUM");?>"  align="center"><?php echo $i; ?></td>
								   <td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"  align="center" style="white-space: nowrap;"><?php echo $row['branch_name'];?></td>
								   <td data-label="<?php echo $tr->translate("INCOME_TITLE");?>"  align="center" style="min-width: 120px;max-width: 150px;">
								   		<a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'incomeexpense','action'=>'receipt-otherincome','id'=>$row['id']));?>">
								   			<?php echo $row['title'];?>
								   		</a>
								   </td>
								   <td data-label="<?php echo $tr->translate("RECEIPT_NO");?>"  align="center">
									   	<a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'incomeexpense','action'=>'receipt-otherincome','id'=>$row['id']));?>">
									   		<?php echo $row['invoice'];?>
									   	</a>
								   </td>
								   <td data-label="<?php echo $tr->translate("CLIENT_NAME");?>"  align="center" style="white-space: nowrap;"><?php echo $row['client_name'];?></td>
								   <td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>"  align="center" style="white-space: nowrap;"><?php echo $row['house_name'];?></td>
								   <td data-label="<?php echo $tr->translate("CATEGORY");?>"  style="white-space: nowrap;"><?php echo $row['category_name'];?></td>
								   <td data-label="<?php echo $tr->translate("TOTAL_INCOME");?>"  align="center"><strong><?php echo number_format($row['total_amount'],2);?></strong></td>
								   <td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>"  align="center"><?php echo $row['payment_type'];?><?php if(!empty($row["bank"])){ echo "(". $row["bank" ].")";}else{echo  "";} ?></td>
								   <td data-label="<?php echo $tr->translate("NUMBER");?>"  align="center"><?php echo $row['cheque'];?></td>
								   <td data-label="<?php echo $tr->translate("NOTE");?>"  align="left" style="font-size:11px; max-width:200px;padding: 2px;overflow-wrap: break-word;white-space: normal;"><?php echo $row['description'];?></td>
								   <td data-label="<?php echo $tr->translate("DATE");?>"  align="center" style="white-space: nowrap;"><?php echo date("d-m-Y",strtotime($row['date']));?></td>
								   <td data-label="<?php echo $tr->translate("BY_USER");?>"  align="center"><?php echo $row['user_name'];?></td>
								</tr>
									<?php $total = $total +$row['total_amount'];?>
								<?php }?>
								<?php 
					            	if (!empty($this->houserepair)){
					            ?>
					            <tr  style="border:1px solid #000;">
					                <td colspan="12" align="center">
					                	<span style="font-weight:normal;font-size:12px; font-family:'Times New Roman','Khmer OS Muol Light'">
							             	<?php echo $tr->translate("REPAIR_HOUSE_INCOME");?>
							             </span>
					                </td>
					             </tr>
					            <?php foreach ($this->houserepair as $index => $rs){ $i++?>
							   		<tr oncontextmenu="setrowdata('<?php echo $rs['id'];?>',1);return false;" class=" context-menu-one stylehover <?php //if($index%2==1){echo"even";}?>" style=" <?php if ($rs['status']==0){ echo "background: #f7c6c6;";}?>  font-family: 'Times New Roman','Khmer OS Battambang';white-space: nowrap;" width="100%">
					               		<td data-label="<?php echo $tr->translate("NUM");?>"  style="text-align: center;"><?php echo $i; ?></td>
					               		<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"  align="center"><?php echo $rs["branch_name"];?></td>
					               		<td data-label="<?php echo $tr->translate("INCOME_TITLE");?>"  align="center"><a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'incomeexpense','action'=>'receipt-otherincome','id'=>$rs['id']));?>?repair=1"><?php echo $rs["title_income"];?></a></td> 
					               		<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>"  align="center"><a target="_blank" style="<?php if ($rs['status']==0){ echo "color:red;";}else{ echo "color:#000;";}?>text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'incomeexpense','action'=>'receipt-otherincome','id'=>$rs['id']));?>?repair=1"><?php echo $rs["invoice"];  if ($rs['status']==0){ echo " ".$tr->translate("មោឃៈ");}?></a></td>
					               		<td data-label="<?php echo $tr->translate("CLIENT_NAME");?>"  align="center"><a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'incomeexpense','action'=>'receipt-otherincome','id'=>$rs['id']));?>?repair=1"><?php echo $rs["name_kh"];?></a></td> 
					               		<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>"  align="center"><?php echo $rs["land_address"]." (".$rs["street"].")";?></td>
					               		<td data-label="<?php echo $tr->translate("CATEGORY");?>"  valign="top"><?php echo $rs["category"];?></td>
					               		<td data-label="<?php echo $tr->translate("TOTAL_INCOME");?>"  align="center"><strong><?php  if ($rs['status']==0){ echo "-";}else{ echo number_format($rs["total_amount"],2);}?></strong></td>
					               		<td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>"  align="center"><?php echo $rs['payment_type'];?><?php if(!empty($rs["bank"])){ echo "(". $rs["bank" ].")";}else{echo  "";} ?></td>
					               		<td data-label="<?php echo $tr->translate("NUMBER");?>" ><?php echo $rs["cheque"];?></td>
					               		<td data-label="<?php echo $tr->translate("NOTE");?>"  align="left" style="font-size:11px; max-width:200px;padding: 2px;overflow-wrap: break-word;white-space: normal;"><?php echo $rs["description"];?></td>
					               		<td data-label="<?php echo $tr->translate("DATE");?>"  align="center"><?php echo date("d-m-Y",strtotime($rs["date"]));?></td>
					               		<td data-label="<?php echo $tr->translate("BY_USER");?>"  align="center"><?php echo $rs["user_name"];?></td>
					                </tr>
				                <?php 
				                if ($rs['status']==0){
				                }else{
				               		 $total = $total +$rs['total_amount'];
					            }?>
						   		<?php }?>
					            <?php }?>
					            
					            <tr class="style style1" style="font-weight: 600; background: #c1d0f3;">
				                	<td colspan="7" align="right"><?php echo $tr->translate('TOTAL_INCOME');?></td>
				                	<td colspan="2"  align="right">$ <?php echo number_format($total,2);?></td>
				                    <td colspan="4"></td>
				                </tr>
						    </table>
		            	</td>
		            </tr>
		            </table>
					<br />
					<?php echo $this->footerReport;?>
					</div>
		    	</td>
		    </tr>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<?php $urlprint = $this->baseUrl()."/report/incomeexpense/receipt-otherincome/id/";?>
 <script>
 dojo.require("dojo.data.ItemFileWriteStore"); 
 var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
 require(["dojo/ready"], function(ready){
 	ready(function(){
 		 getAllPropertyBranch();
		 
		getBranchInfo();
		document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
		document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("REPORT_INCOME");?>';
		document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
	
 	});
 	new dijit.form.FilteringSelect({
 		store: property_store,
 		required: false,
 		autoComplete: false,
 		queryExpr: "*${0}*",
 		name: "land_id",
 		id: "land_id",
 		value:-1,
 		searchAttr: "name",
 		class: 'fullside fullside50',
 		onChange: function() {
 			land_id=-1;
 	}
 		}, "land_id");
 });
 land_id = '<?php echo $this->rssearch['land_id']?>';
 var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
 function getAllPropertyBranch(branch_id){
 	branch_id = dijit.byId('branch_id').get('value');
 	if(branch_id<0){
 		return false;
 	}
 	dojo.xhrPost({
 		url:url_getland,	
 		content:{ 
 		    'branch_id':branch_id,
 		    'action':1
 		},		    
 		handleAs:"json",
 		load: function(data) {
 			property_store  = getDataStorefromJSON('id','name', data);		
 		    dijit.byId('land_id').set('store', property_store);
 		    if(land_id>0){
 		    	dijit.byId('land_id').attr('value',land_id);
 			 }
 		},
 		error: function(err) {
 		}
 	});
 } 

 var row=0;
 var url="";
 var typeprint=0;
 $(function(){
 	$.contextMenu({
 		selector: '.context-menu-one', 
 		callback: function(key, options) {
 			var m = "clicked: " + key;
 			if(key=="print"){
 				url='<?php echo $urlprint;?>';
 			
 			}
 			gotoAction();
 		},
 		items: {
 			"print": {name: "<?php echo $tr->translate("PRINT");?>", icon: "fa-print", accesskey: "c o p y"},
 		}
 	});
 });
 function setrowdata(index,typeri){
 	row = index;
 	typeprint = typeri;
 }
 var recordid ='';
 function gotoAction(){
	 if(typeprint==1){
		 window.open(url+row+'?repair=1', '_blank');
	 }else{
 	 	window.open(url+row+'?rightclick=true', '_blank');
	 }
 }
 
 function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
 </script>
