<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_CATE_EXPENSE')); 
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
	
?>	
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_CATE_EXPENSE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="" action="" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
			<div class="form-group">
	        	<div class="col-md-3 col-sm-3 col-xs-12">
	        		<?php echo $frm->getElement("adv_search");?>
	        	</div>
	        	<div class="col-md-3 col-sm-3 col-xs-12">
	        		<?php echo $frm->getElement('branch_id');?>
	        	</div>
	        	<div class="col-md-2 col-sm-2 col-xs-12">
	        		<?php echo $frm->getElement('supplier_id');?>
	        	</div>
	        	<div class="col-md-2 col-sm-2 col-xs-12">
	        		<?php echo $frm->getElement('category_id_expense');?>
	        	</div>
	        	<div class="col-md-2 col-sm-2 col-xs-12">
	        		<?php echo $frm->getElement('payment_type');?>
	        	</div>
	        	<div class="col-md-2 col-sm-2 col-xs-12">
	        	</div>
	        </div>
	        <div class="form-group">
	        	<div class="col-md-3 col-sm-3 col-xs-12">
			   		<?php echo $frm->getElement('cheque_issuer_search');?>
			   		</div>
	        	<div class="col-md-3 col-sm-3 col-xs-12">
	        		<?php echo $frm->getElement('start_date');?>
	        	</div>
	        	<div class="col-md-2 col-sm-2 col-xs-12">
	        		<?php echo $frm->getElement('end_date');?>
	        	</div>
	        	<div class="col-md-2 col-sm-2 col-xs-12">
	        		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	        	</div>
	        	<div class="col-md-2 col-sm-2 col-xs-12">
	        	</div>
	        	<div class="col-md-2 col-sm-2 col-xs-12">
	        	</div>
	        	<div class="col-md-2 col-sm-2 col-xs-12">
	        	</div>
	        </div>
	     </div>        
	 </form> 
	 <div id="divPrint">
		<style>
			table.content-data{
				border-collapse:collapse;
				width:100%;
				border:none; 
				font-family:'Times New Roman','Khmer OS Battambang';
				font-size:12px;
				white-space: nowrap;
				margin:0 auto;
			}
			table.content-data tr.style-head {
			   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #ccd9ff;
				text-align: center;
			}
			table.content-data tr.style-rowdata {
				font-size:12px; 
				height: 23px;
			}
			table.content-data td {
				padding: 2px;
			}
			.border_bottom{
				border-bottom:2px solid #000;
			}
			
			  @page {
				margin-left: 5px;
				margin-right: 5px;
			 }
		</style>
		<div>
			<table  style="background:#fff; margin: 0 auto; ;white-space: nowrap;width: 100%">
				<tr>
					<td colspan="3">
						<div class="divFooter">
							<?php echo $this->headerReport;?>
						</div>
					</td>
				</tr>
				
				<tr>
					<td colspan="3" id="exportExcel" valign="top">
						<table class="content-data" cellpadding="5"​ border="0" width="100%">
							<thead>
								<tr class="style-head">
									<td style="text-align: right;" colspan="2"><?php echo $tr->translate('CATEGORY')?></td>
									<td style=""></td>
									<td style=""><?php echo $tr->translate('TOTAL_EXPENSE')?></td>
								</tr>
							</thead>
						<?php $i=0;
							$total_expense = 0;
							$parent='';
							
							$total_sub_cate=0;
						if(!empty($this->row)){foreach ($this->row AS $keyIndex => $row) { $i++;?>
							<?php if ( $row['parent']!=0 AND $parent != $row['parent']){?>
								<?php if ($keyIndex>0 && $total_sub_cate>0){?>
		             				<tr height="21px">
			             				<td style="">&nbsp;</td>
										<td style="text-align: right;">&nbsp;</td>
										<td style="white-space: nowrap;width:200px;"></td>
			             				<td class="" align="right" style="background:#ccc;">&nbsp;<strong><?php echo number_format($total_sub_cate,2);?></strong>&nbsp;</td>
			             			</tr>
		             			<?php }?>
	             				<tr height="21px">
		             				<td >&nbsp;</td>
		             				<td style="text-align: right;"><strong><?php echo $row['parent_title'];?></strong>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
		             				<td>&nbsp;</td>
		             				<td>&nbsp;</td>
		             				<?php $parent = $row['parent']; $total_sub_cate=0;?>
		             			</tr>
		             		<?php }?>
							<tr class="hover" style="font-size:15px; height: 20px;" align="center" >
								<td style=""></td>
								<td style="text-align: right;"><?php echo $row['category_name'];?></td>
								<td style="white-space: nowrap;width:200px;">...................................................................................</td>
								<td style=""><?php echo number_format($row['total_amount'],2);
									$total_expense = $total_expense+$row['total_amount'];
									
									$total_sub_cate = $total_sub_cate+$row['total_amount'];
									?>
								</td>
							</tr>
						<?php }}?>
						<?php if ($total_sub_cate>0){?>
							<tr height="21px">
	             				<td style="">&nbsp;</td>
								<td style="text-align: right;">&nbsp;</td>
								<td style="white-space: nowrap;width:200px;"></td>
	             				<td class="" align="right" style="background:#ccc;">&nbsp;<strong><?php echo number_format($total_sub_cate,2);?></strong>&nbsp;</td>
	             			</tr>
						<?php }?>
						
						
						<?php if (!empty($this->expense_changehouse)) foreach ($this->expense_changehouse as $expenseHouse){ 
									$total_expense = $total_expense+abs($expenseHouse['total_amount']);
						?>
	             			<tr height="21px">
	             				<td style=""></td>
	             				<td style="text-align: right;"><?php echo $expenseHouse['category_name'];?>&nbsp;</td>
	             				<td style="white-space: nowrap;width:200px;">...................................................................................</td>
	             				<td class="" ><?php echo number_format(abs($expenseHouse['total_amount']),2);
	             				?></td>
	             			</tr>
	             			<?php }?>
	             			
	             			
						<?php if (!empty($this->expense_comission)) foreach ($this->expense_comission as $comission){ 
									$total_expense = $total_expense+$comission['total_amount'];
						?>
	             			<tr height="21px">
	             				<td style=""></td>
	             				<td style="text-align: right;"><?php echo $comission['category_name'];?>&nbsp;</td>
	             				<td style="white-space: nowrap;width:200px;">...................................................................................</td>
	             				<td class="" ><?php echo number_format($comission['total_amount'],2);
	             				?></td>
	             			</tr>
	             			<?php }?>
							<tr>
								<td colspan="3"></td>
								<td style="border-bottom: 5px double #000;text-align: center;">$&nbsp;<strong><?php echo number_format($total_expense,2);?></strong></td>
							</tr>	
						</table>	
					</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="3">&nbsp;</td>
				</tr>
				<tr >
					<td colspan="3" width="100%">
						<table width="100%" style="font-size: 15px; font-family:'Times New Roman','Khmer OS Muol Light';">
							<tr>
								<td  width="25%" align="center">
									<span><?php echo $tr->translate('VERIFIED_BY')?></span>
								</td>
								<td  width="50%">
									&nbsp;
								</td>
								<td align="center"  width="25%">
									<span><?php echo $tr->translate('PREPARED_BY')?></span>
								</td>
							</tr>
						</table>
						<?php //echo $this->footerReport;?>
					</td>
				</tr>
			</table>
			</div>
	</div>	
</div>
<script>
require(["dojo/ready"], function(ready){
	ready(function(){
		
		getBranchInfo();
		document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
		document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("RPT_CATE_EXPENSE");?>';
		document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
	
		 		 
		
	});
});

function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>
