<?php $frm = $this->frm_search;
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$commission = $this->row;
?>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{background: #ccc;}
img.view{height: 85px !important;}
</style>
<title><?php echo $tr->translate("RECEIPT");?></title>
<div style=" width:29cm;min-height:23cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm;background: #fff;">
	<div id="divPrint" style="width: 100%;">
		<style>
			.fontbig{
				font-size: 15px;	
			}
			.fonttel{
				font-size: 18px;	
			}
			.pleft{
				width: 110px;	
			}

			.label{ font-weight: bold;font-size: 22px;}
			.value{ font:14px 'Khmer OS Battambang';border: 1px solid #000; height: 29px; width: 100%;margin-right:5px; display: block;
					line-height: 28px;
				    text-align: center;
					}
			.print tr td{
				padding:4px 2px; 
			}
		   .khmerbold{font:16px 'Khmer OS Battambang';}
		   .khmer{font:16px 'Khmer OS Battambang';}
		   .one{white-space:nowrap;}
		   .h{ margin-top: -10px;/*margin-left:4px;*/}
		</style>
		<?php for($i=0; $i<2; $i++){ ?>	
		<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;" >
			<tr>
				<td width="25%">
					<img style="height:75px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
				</td>					
				<td width="50%" style="font:bold 18px 'Kh Muol';" valign="top" align="center"><u><b><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃចំណាយ</strong></b></u>
					<div style="line-height:25px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
				</td>
				<td width="25%">
				</td>
			</tr>
		</table>
		<table width="100%" style="white-space: nowrap;font-size:14px;margin-top: 20px;" class="print" cellspacing="3px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="37%" ></td>
					<td width="15%" ></td>
					<td width="13%" ></td>
					<td width="10%" ></td>
					<td width="20%" ></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">គម្រោង</td>
                    <td><strong><label id="lb_branch" class="value"><?php echo $commission['brach_name']?></label></strong></td>
				    <td class="one khmerbold">&nbsp;&nbsp;&nbsp;វិក័យប័ត្រលេខ</td>
                    <td colspan="3"><strong><label id="lb_invoice" class="value"><?php echo $commission['invoice']?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">ប្រភេទចំណាយ</td>
					<td ><strong><label id="lb_income_category" class="value"><?php echo $commission['cate_title']?></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ពណ៌នាចំនាយ</td>
				    <td colspan="3"><strong><label id="lb_income_title" class="value">ចំណាយលើកម្រៃជើងសារ</label></strong></td>
				</tr>
				<tr>
					<td class="one khmerbold">លេខដី/ផ្ទះ</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_cheque" class="value"><?php echo $commission['cutomer_name']." (".$commission['land_address'].",".$commission['street'].")"; ?></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ចំណាយសរុប</td>
					<td colspan="3"><strong><label id="lb_total_amount" class="value"><?php echo '$ '.number_format($commission['total_amount'],2); ?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សម្គាល់</td>
				    <td colspan="1" align="center"><strong style="white-space: nowrap;"><label style="white-space: nowrap;text-align: center; " id="lb_description" class="value"><?php echo $commission['desc'];?></label></strong></td>					
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ថ្ងៃចំណាយ</td>
				    <td colspan="3"><strong><label id="lb_date" class="value"><?php echo date("d-M-Y",strtotime($commission['for_date'])); ?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td class="khmerbold" style="line-height: 14px;"colspan="4"  align="center" >&nbsp;&nbsp;<strong style=" font-family: Arial Black;font-family:'Khmer MEF2';"><?php echo $this->data['teller_sign'];?></strong></td>
				    <td colspan="2" class="khmerbold" style="line-height: 14px;" align="center" ><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';"><?php echo $this->data['customer_sign'];?></strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="100px;">
					<td class="one khmerbold" colspan="4" align="center" valign="bottom">
						<h4 id="agent-sign" style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
						<?php echo $commission['co_khname']; ?>
						</h4>
					</td>
				    <td class="one khmerbold" colspan="2" align="center" valign="bottom">&nbsp;
			  			<h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
			              <?php $session_user=new Zend_Session_Namespace('authinstall');
				           $last_name=$session_user->last_name;
				           $username = $session_user->first_name;
				           echo $last_name." ".$username;
					      ?></h4>  
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
					</td>
				</tr>
				<tr style="line-height: 15px;">
					<td colspan="6" >
						<table width="100%" style="font-family: 'Khmer OS Battambang'; font-size:13px;line-height: 15px;margin-top: -5px;margin-bottom:15px;white-space:nowrap;"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang'; "><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr style="white-space:nowrap;">
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?> </span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<?php if($i==0){?>
				<tr>
					<td colspan="6">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="6" style="border-top:2px dashed #000;" >
					</td>
				</tr>
				<?php }?>
			</table>
			<?php } ?>
	</div>
</div>
