<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_staff;
	$url_commissionbalance = $this->url(array('module'=>'report','controller'=>'paramater','action'=>'commissionreceipt'));
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
	
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_COMISSION_BALANCE");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_COMISSION_BALANCE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("branch_id");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<input id="land_id" />
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("co_khname");?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("start_date");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("end_date");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"  type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
				</div>
			</div>
		</div>
	</form> 
<div id="divPrint">
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 	<style>
					.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
						}
						th{padding: 5px;}
					.hide{visibility: hidden;}
						@media print {
						  div.divFooter {
						    position: fixed;
						    top: 0;
						  	width: 100%;
						  	height: 100px;
						  	bottom:0px;
							margin:0;
						  }
					.hide{visibility: visible; height: 110px;}
					}
					.hover:hover{background: #ccc;}
					table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:13px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
							width: 100%;
						}
						table.content-data thead tr.style {
						   line-height: 25px;
						   font-size:12px !important;
						   padding:1px 0px;
						   white-space: nowrap;
						   height: 22px; 
						   background:#ccd9ff;
						   font-weight: bolder;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
				</style>
					<div class="divFooter">
			        	<table width="100%" style="margin:0; padding:0;border:none;" >
			            	<tr>
						    	<td align="center">
							    	<div class="divFooter">
										<?php echo $this->headerReport;?>
							         </div>
								</td>
							</tr>
			            </table>
		            </div>
				<table id="exportExcel" class="content-data" width="100%" border="1" bordercolor="black">  
			    	<thead>
				    	<tr class="hide" >
		                	<td colspan="17" style="border-top:1px solid #fff;border-right:1px solid #fff;border-left:1px solid #fff;border-botom:1px solid #000;"></td>
		             	</tr>
				    	<tr class="style" align="center"  >
			        		<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
				            <td rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></td>
				            <td rowspan="2"><?php echo $tr->translate("STAFF");?></td>
				            <td rowspan="2"><?php echo $tr->translate("TEL");?></td>
				            <td rowspan="2"><?php echo $tr->translate("SEX");?></td>
				            <td colspan="6"><?php echo $tr->translate("INFO_INDILOAN");?></td>
				            <td colspan="3"><?php echo $tr->translate("COMMISSION_INFO");?></td>
				         </tr>
				         <tr class="style" align="center">
				            <td><?php echo $tr->translate("BUY_DATE");?></td>
				         	<td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
				         	<td><?php echo $tr->translate("PROPERTY_INFO");?></td>
				         	<td><?php echo $tr->translate("SOLD_PRICE");?></td>
				         	<td><?php echo $tr->translate("PAID");?></td>
				         	<td><?php echo $tr->translate("PERCENTAGE");?></td>
				         	<td><?php echo $tr->translate("TOTAL");?></td>
				            <td><?php echo $tr->translate("PAID");?></td>
				            <td><?php echo $tr->translate("REMAIN");?></td>
				         </tr>
			         </thead>
			       <?php  
			       		$total = 0;
			       		$totalpaid_com = 0;
			       		$balance = 0;
			       		$key=0; 
			       	   if(!empty($this->row))foreach($this->row as $key =>$row){
					   	   $total = $total +$row['full_commission'];	
						   $paidcommision = $row['totoal_comminssion']+$row['total_sale_commission'];
						   $remain = $row['full_commission'] - $paidcommision;
						   $balance = $balance+$remain;
						   $totalpaid_com = $totalpaid_com+$paidcommision;
						   if($row['price_sold']>0){
						   		$percentpaid = @($row['total_sale_paid']*100)/$row['price_sold'];
				       	   }else{
				       	   		$percentpaid=100;
				       	   }
					  ?>
					   <tr oncontextmenu="setrowdata(<?php echo $row['sale_id'];?>);return false;" style="font-size: 12px; font-family: 'Times New Roman','Khmer OS Battambang'" align="left" class="hover context-menu-one">
					     <td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
					     <td align="left" style="white-space: nowrap;">&nbsp;<?php echo $row['branch_name']?>&nbsp;</td>
						 <td style="white-space: nowrap;">&nbsp;<?php echo $row['co_khname'];?>&nbsp;</td>
						 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['tel'];?>&nbsp;</td>
						 <td align="center" style="white-space: nowrap;">&nbsp;<?php if($row['sex']==1){ echo "ប្រុស";}else{ echo 'ស្រី';}?>&nbsp;</td>
						 <td style="white-space: nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($row['buy_date']));?>&nbsp;</td>
						 <td style="white-space: nowrap;">&nbsp;<?php echo $row['cutomer_name'];?>&nbsp;</td>
						 <td style="white-space:normal;width:200px;">&nbsp;<?php echo $row['land_address'].', '.$row['street'];?>&nbsp;</td>
						 <td style="white-space: nowrap;">&nbsp;<?php echo number_format($row['price_sold'],2);?>&nbsp;</td>
						 <td style="white-space: nowrap;">&nbsp;<?php echo number_format($row['total_sale_paid'],2);?>&nbsp;</td>
						 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo number_format($percentpaid,2)."%";?>&nbsp;</td>
						 <td align="right" style="white-space: nowrap; font-weight:bold;">&nbsp;<?php echo number_format($row['full_commission'],2);?>&nbsp;</td>
						 <td align="right" style="white-space: nowrap; font-weight:bold;">&nbsp;<?php echo number_format($paidcommision,2);?>&nbsp;</td>
						 <td align="right" style="white-space: nowrap; font-weight:bold;">&nbsp;<?php echo number_format($remain,2);?>&nbsp;</td>
					</tr>
					<?php }?>
					<tr style="background:#87acff;font-weight:bold; font-size:14px;text-align: center;">
						<td colspan="11"></td>
						<td><?php echo '$ '.number_format($total,2);?></td>
						<td><?php echo '$ '.number_format($totalpaid_com,2);?></td>
						<td><?php echo '$ '.number_format($balance,2);?></td>
					</tr>	
			    </table>
	    	</td>
	    </tr>
	</table>
	   <br />
	   <?php echo $this->footerReport;?>
</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
	require(["dojo/ready"], function(ready){
		ready(function(){
			 getAllPropertyBranch();
		});
		new dijit.form.FilteringSelect({
			store: property_store,
			required: false,
			autoComplete: false,
			queryExpr: "*${0}*",
			name: "land_id",
			id: "land_id",
			value:-1,
			searchAttr: "name",
			class: 'fullside',
			onChange: function(){
				land_id=-1;
			}
		}, "land_id");
		new dijit.form.FilteringSelect({
			name: "branch_id",
			id: "branch_id",
			class: 'fullside',
			autoComplete: false,
			onChange: function() {
				 getAllPropertyBranch();
			}
		}, "branch_id");

		getBranchInfo();
		document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
		document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("REPORT_CLIENT");?>';
		document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>'; 
		
});
land_id = '<?php echo $this->search['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		 dijit.byId('land_id').reset();
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load:function(data){
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    dijit.byId('land_id').reset();
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err){
		}
	});
} 


var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="commission_detail"){
				url='<?php echo $this->baseUrl()."/report/paramater/commissionreceipt/id/";?>';
			}
			gotoAction();
		},
		items: {
			"commission_detail": {name: "<?php echo $tr->translate("DETAIL");?>", icon: "fa-calendar"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}

function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>