<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm;
	
	$dbGb = new Setting_Model_DbTable_DbGeneral();
	$settingRow = $dbGb->geLabelByKeyName('crmConnectWithSale');
	$crmConnectWithSale = empty($settingRow["keyValue"]) ? 0 : $settingRow["keyValue"];
	
	$featureClass="disabledClass";
	if($crmConnectWithSale==1){
		$featureClass="";
	}
	
	$branch_title = $tr->translate("BRAND_TITLE");
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_CUSTOMER_REQUIREMENT");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">		
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_CUSTOMER_REQUIREMENT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("start_date");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("end_date");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("know_by");?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("statusreq");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("user");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<button class="button-class button-primary" iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button"  type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
				</div>
			</div>
		</div>
	</form> 
	<div id="divPrint">
		<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
			<tr>
		    	<td align="center">
		    	 	<style>
						.style{
							line-height: 20px;font-size: 14px !important;
							font-family: 'Times New Roman','Khmer OS Battambang';
							}
							th{padding: 5px;}
							.hover:hover{background: #ccc;}
							.hide{visibility: hidden;}
							@media print {
								div.divFooter {
									position: fixed;
									top: 0;
									width: 100%;
									height: 100px;
									bottom:0px;
									margin:0;
								}
								.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
							}
						table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:13px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
							width: 100%;
						}
						table.content-data thead tr.style {
						   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
							background: #c1d0f3;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
						.disabledClass{
							display:none !important;
						}
					</style>
					<div class="divFooter">
			        	<?php echo $this->headerReport;?>
			         </div>
					<table id="exportExcel" class="content-data" width="100%" border="1" bordercolor="black">  
				    	<thead>
				    	 <tr class="hide" style="border:1px solid #000;">
			                <td colspan="16" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
			             </tr>
						 <tr class="style" align="center" >
							<td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?></td>
							<td scope="col" colspan="2"><?php echo $tr->translate("CUSTOMER_INFO");?></td>
							<td scope="col" colspan="8"><?php echo $tr->translate("CUSTOMER_REQUIREMENT");?></td>
							<td scope="col" colspan="2" class="<?php  echo $featureClass;?>"><?php echo $tr->translate("SALE_INFO");?></td>
							<td scope="col" rowspan="2"><?php echo $tr->translate("USER_NAME");?></td>
						 </tr>
				    	<tr class="style" align="center" >
				        		
					            <td scope="col"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
					            <td scope="col"><?php echo $tr->translate("PHONE");?></td>
								
					            <td scope="col"><?php echo $tr->translate("KNOW_BY");?></td>
					            <td scope="col"><?php echo $tr->translate("FROM_PRICE");?></td>
					            <td scope="col"><?php echo $tr->translate("TO_PRICE");?></td>
					            <td scope="col"><?php echo $tr->translate("PROPERTY_TYPE");?></td>
					            <td scope="col"><?php echo $tr->translate("REQUIREDMENT");?></td>
					            <td scope="col"><?php echo $tr->translate("DESCRIPTION");?></td>
					            <td scope="col"><?php echo $tr->translate("DATE");?></td>
					            <td scope="col"><?php echo $tr->translate("STATUS_REQ");?></td>
								
					            <td scope="col" class="<?php  echo $featureClass;?>"><?php echo $tr->translate("PROPERTY_CODE");?></td>
					            <td scope="col" class="<?php  echo $featureClass;?>"><?php echo $tr->translate("BUY_DATE");?></td>
				         </tr>
				         </thead>
				       <?php  
				       	   if(!empty($this->row))foreach($this->row as $key =>$row){
						  ?>
						   <tr oncontextmenu="setrowdata(<?php echo $row['id'];?>,1);return false;" style="font-size: 12px; font-family: 'Times New Roman','Khmer OS Battambang'" align="left" class="hover context-menu-one">
						     <td data-label="<?php echo $tr->translate("NUM");?>" align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
						     <td data-label="<?php echo $tr->translate("CUSTOMER_NAME");?>" align="center">&nbsp;<?php echo $row['name']?>&nbsp;</td>
							 <td data-label="<?php echo $tr->translate("PHONE");?>">&nbsp;<?php echo $row['phone'];?>&nbsp;</td>
							 <td data-label="<?php echo $tr->translate("KNOW_BY");?>">&nbsp;<?php echo $row['know_by'];?>&nbsp;</td>
							 <td data-label="<?php echo $tr->translate("FROM_PRICE");?>" align="right" style="white-space: nowrap;">&nbsp;<?php echo $row['from_price'];//number_format($row['from_price'],2);?>&nbsp;</td>
							 <td data-label="<?php echo $tr->translate("TO_PRICE");?>" align="right" style="white-space: nowrap;">&nbsp;<?php echo $row['to_price'];//number_format($row['to_price'],2);?>&nbsp;</td>
							 <td data-label="<?php echo $tr->translate("PROPERTY_TYPE");?>" style="white-space: nowrap;">&nbsp;<?php echo $row['type'];?>&nbsp;</td>
							 <td data-label="<?php echo $tr->translate("REQUIREDMENT");?>" style="white-space: nowrap;">&nbsp;<?php echo $row['requirement'];?>&nbsp;</td>
							 <td data-label="<?php echo $tr->translate("DESCRIPTION");?>" style="white-space: pre-line;">&nbsp;<?php echo $row['description'];?>&nbsp;</td>
							 <td data-label="<?php echo $tr->translate("DATE");?>" style="white-space: nowrap;">&nbsp;<?php echo date("d M Y",strtotime($row['date']));?>&nbsp;</td>
							 <td data-label="<?php echo $tr->translate("STATUS_REQ");?>" style="white-space: nowrap;">&nbsp;<?php echo $row['statusreq'];?>&nbsp;</td>
							 <td class="<?php  echo $featureClass;?>" data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" style="white-space: nowrap;">&nbsp;<?php echo $row['landAddress']." ".$row['landStreet'];?>&nbsp;</td>
							 <td class="<?php  echo $featureClass;?>" data-label="<?php echo $tr->translate("BUY_DATE");?>" align="center">&nbsp;<?php echo empty($row['buyDate']) ? "-" : date("d-M-Y",strtotime($row['buyDate']));?>&nbsp;</td>
							 
							 <td data-label="<?php echo $tr->translate("USER_NAME");?>" style="white-space: nowrap;">&nbsp;<?php echo $row['user_name'];?>&nbsp;</td>
							</tr>
						<?php }?>
				    </table>
		    	</td>
		    </tr>
		</table>
		<br />
	   <?php echo $this->footerReport;?>
	</div>
</div>
<?php 
$urlprint = $this->baseUrl()."/report/paramater/rpt-customer-contact/id/";
?>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	require(["dojo/ready"], function(ready){
		ready(function(){
			 getBranchInfo();
	
			 
			 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			 document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("REPORT_CUSTOMER_REQUIREMENT");?>';
			 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
		});
		
	});

var row=0;
var url="";
var typeprint=0;
 $(function(){
 	$.contextMenu({
 		selector: '.context-menu-one', 
 		callback: function(key, options) {
 			var m = "clicked: " + key;
 			if(key=="contact"){
 				url='<?php echo $urlprint;?>';
 			}
 			gotoAction();
 		},
 		items: {
 			"contact": {name: "<?php echo $tr->translate("CONTACT_HISTORY_DETAIL");?>", icon: "fa-print", accesskey: "c o p y"},
 		}
 	});
 });
 function setrowdata(index,typeri){
 	row = index;
 	typeprint = typeri;
 }
 var recordid ='';
 function gotoAction(){
	 window.open(url+row, '_blank');
 }
 
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}


</script>