<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$day = array(
		"Mon" =>'ច័ន្ទ',
		"Tue" =>'អង្គារ',
		"Wed" =>'ពុធ',
		"Thu" =>'ព្រហស្បតិ៍',
		"Fri" =>'សុក្រ',
		"Sat" =>'សៅរ៍',
		"Sun" =>'អាទិត្យ',
	);
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	$dbparmeter = new Report_Model_DbTable_DbParamater();
	$boreyName = $tr->translate("BRAND_TITLE");
	$arrgender = array(1=>"ប្រុស",2=>"ស្រី");
	$arrTitle = array(1=>"លោក",2=>"លោកស្រី");
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title><?php echo $tr->translate("AGREEMENT");?></title>
<style>
	.reff{ font-size: 20px !important; line-height:34px !important;}
	#divPrint tr td h2,#divPrint p, #divPrint pre, #divPrint span,#divPrint table tr td{ font-size: 20px !important; line-height:34px !important;}
		#padding-left-p-2{
		 padding-left: 105px !important;	
		}
		.padding-buttom{
			margin-top: -5px !important;
		}
	#printfooter{display: none !important;}
</style>
<div  id="exportword" style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    		<div id="divPrint" >
		    	 	<style>		
					    #padding-left-p-2{
						 padding-left: 105px !important;	
						}
						.padding-buttom{
							margin-top: -5px !important;
						}
    	 				.reff{ font-size: 16px !important; line-height:34px !important;}
						tr td h2,p,pre,span{ font-size: 15px ; line-height:30px;}
						#padding-left{
						padding-left: 18px;
						}
						#bold-padding-right{
							margin-right: 15px;
							font-family: khmer os battambang;
							font-size:19px;
						}
						
						#padding-left-2{
						/*margin-top: -10px;*/
						padding-left:15px;
						}
						.padding-buttom{
							margin-top: -5px;
						}
						#padding-left-p-2{
						 margin-top:-1px; 
						 padding-left: 85px;	
						}
						#padding-left-p{
					    padding-left: 105px;
						}
						th{padding: 5px;}
						span.value{ line-height:12px;display: inline-block; text-align: center;}
						span.child {display:block; margin-left:25px; line-height: 25px;}
						span{line-height: 26px;}
						body {
						    position: relative;
						}
						#printfooter {
						    position: absolute;
						    bottom: 0;
						    position: fixed;
						    display: block ;
						}
						span.margin-left {
						    margin-left: 40px;
						}
		    </style>
		    	<div>
		        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="padding:0;margin:0;border:0px;" >
		        	<tr>
		                <td width="30%" valign="top">
			                <?php $imagelogo = $this->baseUrl()."/images/logo.jpg";
			                	if (!empty($this->agreement['project_logo'])){
			                		$imagelogo = $this->baseUrl()."/images/projects/".$this->agreement['project_logo'];
			                	}
			                ?>
			                <img src="<?php echo $imagelogo;?>" style="max-width:100%">
		                </td>
		                <?php 
	             				if (!empty($this->agreement['project_name'])){
	             					$projectName = " ".$this->agreement['project_name'];
	             				}else{ 
	             					$projectName = " បុរី C&T VILLA (SHOP HOUSE)";
	             				}
             				?>
		                <td width="40%" align="center">
			                <span style="text-align:center; line-height:28px; font-size:17px;font-family:'Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា</span>
			                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
			                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.jpg" height="25px"></span>
			                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("កិច្ចសន្យាទិញ-លក់").$projectName;?></span>
			                
		                <td width="30%"></td>
		             </tr> 
		             <tr>
		             	<td colspan="3">
		             		<p style="font-family:'Khmer OS Battambang','Times New Roman',; text-align:justify; line-height:24px; font-size:14px; font-weight: normal !important;">
			             			<span style="width: 100%; display: block; line-height: 28px;"> 
			             			<span style="text-decoration:underline; text-align:left; line-height:28px; width: 100%; display: block; font-size:16px; font-weight:200; font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("កិច្ចសន្យានេះធ្វើឡើងរវាងៈ");?></span>
			             				<table border="0">
			             					<tr>
			             						<td style="text-align: justify;">
			             						<span class="margin-left">&nbsp;</span>
			             						<strong><?php echo $boreyName;?></strong> មានទីតាំងស្ថិត<?php echo $this->agreement['project_location'];?>
			             						ដែលតំណាងដោយ លោក <span class="value" style=" font-weight:200; font-family:'Khmer OS Muol Light';"><?php echo $this->agreement['project_manager_namekh'];?></span> 
			             						 <span style=" font-weight:200; font-family:'Khmer OS Muol Light';">ម្ចាស់បុរី</span> 
			             						សញ្ជាតិ<?php echo $this->agreement['project_manager_nationality'];?> 
			             						កាន់អត្តសញ្ញាណប័ណ្ណសញ្ជាតិខ្មែរលេខ៖ <?php echo $dbparmeter->getNumberInkhmer($this->agreement['project_manager_nation_id']);?> 
			             						ចុះថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['p_nationid_issue'])));?> ខែ<?php echo $month[date("m",strtotime($this->agreement['p_nationid_issue']))];?> ឆ្នំា<?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['p_nationid_issue'])));?> 
			             						មានទីលំនៅ <?php echo $dbparmeter->getNumberInkhmer($this->agreement['project_manager_p_current_address']);?>
			             						 ហៅកាត់ថា ភាគី(ក)។
			             					</tr>
			             					<tr>
			             						<td  align="center">
			             						<span style="font-family:'Khmer OS Muol Light';font-weight:200;  text-align:center; min-width: 100%; display: inline-block;">និង</span>
			             						</td>
			             					</tr>
			             					<tr>
			             						<td style="padding-left: 20px;text-align: justify;">
			             							<span class="margin-left">&nbsp;</span>
						             				<span class="value" style="min-width:50px; font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['client_namekh'];?></span>
						             				ភេទ<?php if (!empty($arrgender[$this->agreement['sex']])){ echo $arrgender[$this->agreement['sex']];}?> 
						             				សញ្ជាតិ<?php echo $this->agreement['client_nationality'];?>
						             				<?php echo $this->agreement['client_d_type'];?>លេខ៖ <span class="value" style="min-width:50px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['client_nation_id']);?></span> 
						             				<?php if(!empty($this->agreement['client_issuedateid'])){ ?>
						             				ចុះថ្ងៃទី<?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['client_issuedateid'])));?> ខែ<?php echo $month[date("m",strtotime($this->agreement['client_issuedateid']))];?> ឆ្នាំ<?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['client_issuedateid']))); }?>
						             		   		  អាសយដ្ឋានផ្ទះ<span class="value" style="min-width:50px;"><?php echo $this->agreement['client_house_no'];?></span> 
						             		   		  ផ្លូវ<span class="value" style=""><?php echo $this->agreement['client_street'];?></span> 
											    	 ភូមិ <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_village_kh'];?></span>       
											     	 ឃុំ/សង្កាត់  <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_commune_kh'];?></span> 
											     	  ស្រុក/ខណ្ឌ <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_districtkh'];?></span>
			             					      	 ខេត្ត/ក្រុង <span class="value" style="min-width:50px;">&nbsp;<?php echo $this->agreement['client_province_kh'];?></span>
			             					      	 
					             			   <?php if(!empty($this->agreement['hname_kh'])){?> និង<span class="value" style="min-width:50px;font-family:'Khmer OS Muol Light';"><?php echo $this->agreement['hname_kh'];?></span>  
												ភេទ<?php if (!empty($arrgender[$this->agreement['w_sex']])){ echo $arrgender[$this->agreement['w_sex']];}?> 
												សញ្ជាតិ<span class="value" style="width:30px;"><?php echo $this->agreement['p_nationality'];?></span> 
					             			    <?php echo $this->agreement['joint_doc_type'];?>លេខ៖  <span class="value" style="min-width:50px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['rid_no']);;?></span>
			             						<?php if(!empty($this->agreement['join_issuedateid'])){ ?> ចុះថ្ងៃទី<?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['join_issuedateid'])));?> ខែ<?php echo $month[date("m",strtotime($this->agreement['join_issuedateid']))];?> ឆ្នាំ<?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['join_issuedateid']))); }?> 
											   	អាសយដ្ឋានផ្ទះ<span class="value" style="min-width:45px;"><?php echo $this->agreement['with_house'];?></span> 
											         ផ្លូវ<span class="value" style="min-width:45px;"><?php echo $this->agreement['w_street'];?></span> 
											          ភូមិ<span class="value" style="min-width:45px;"><?php echo $this->agreement['joint_village'];?></span> 
											          ឃុំ-សង្កាត់  <span class="value" style="min-width:70px;"><?php echo $this->agreement['join_commune'];?></span> 
											          ស្រុក-ខណ្ឌ <span class="value" style="min-width:80px;"><?php echo $this->agreement['join_district'];?></span>
												ខេត្ត-ក្រុង <span class="value" style="min-width:100px;"><?php echo $this->agreement['join_province'];?></span>
												<?php }?>		
												ហៅកាត់ ភាគី(ខ)។​
			             						</td>
			             					</tr>
			             				</table>
									</span>
									<p style="text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;text-align: center;margin: 0;padding: 0;">បុព្វកថា</p>           		
			             			<span style="width: 100%; display: block; line-height: 28px;">
			             			<span class="margin-left">&nbsp;</span>ដោយភាគី(ក) ជាម្ចាស់សំណង់ផ្ទះល្វែងឈ្មោះ <strong><?php echo $boreyName;?></strong> សម្រាប់លក់ជូនអតិថិជននិងភាគី(ខ) មានបំណងចង់ទិញផ្វះល្វែង ពីភាគី(ក)។
			             			</span>
			             			<p style="text-decoration:underline;font-family:'Khmer OS Muol Light';font-weight:200;text-align: center;margin: 0;padding: 0;">ភាគីទាំងពីរឯកភាពគ្នាតាមប្រការដូចខាងក្រោមៈ</p>
			             			<span style="width: 100%; display: block; line-height: 28px;">
			             				<div class="padding-buttom">
				             				<span style="font-family:'Khmer OS Muol Light'; text-decoration: underline;">ប្រការ១: ទំហំដី និងផ្ទះ </span>
				             			</div>
					             			<table width="100%" border="0"> 
					             				<tr>
											    	<td align="justify" style="vertical-align:top; text-align:right; width:9%;"></td>
												    <td align="justify" style="padding-left:5px">
											    		១.១- ភាគី(ក) យល់ព្រមលក់ ហើយភាគី(ខ) យល់ព្រមទិញពីភាគី(ក) នូវផ្ទះល្វែង  
											    		មានទំហំដី <?php echo $dbparmeter->getNumberInkhmer($this->agreement['land_size']);?>ម៉ែត្រក្រឡា និងផ្ទះមួយល្វែង 
											    		ដែលសង់នៅលើផ្ទៃដីនោះមានទំហំ <?php echo $dbparmeter->getNumberInkhmer($this->agreement['full_size']);?>ម៉ែត្រក្រឡា 
											    		ដែលមានទទឹង <?php echo $dbparmeter->getNumberInkhmer($this->agreement['property_width']);?>ម៉ែត្រ     
											    		បណ្តោយ <?php echo $dbparmeter->getNumberInkhmer($this->agreement['property_height']);?>ម៉ែត្រ 
											    		ផ្ទះលេខ<?php echo $this->agreement['property_title'];?>
											    		ប្លុក <?php echo $this->agreement['type_tob'];?>
											    		ប្រភេទផ្ទះ <?php echo $this->agreement['property_type_en'];?> 
											    		កម្ពស់ <?php echo $this->agreement['property_note'];?> 
											    		ជាសំណង់ផ្ទះល្វែងស្ថិតក្នុងទីតាំងរបស់ភាគី(ក) 
											    		ស្ថិតផ្លូវជាតិលេខ២ ភូមិព្រែករទាំង សង្កាត់ព្រែកកំពឹស ខណ្ឌដង្កោ រាជធានីភ្នំពេញ ។ តាមប្លង់គោលដូចភ្ជាប់ជូនខាងលើ (ភាគី “ក” រក្សាសិទ្ធិកែប្រែប្លង់គោល តាមករណីជាក់ស្តែង )
												    </td>
												 </tr>
										</table>
				             		</span>
				             		<span style="width: 100%; display: block; line-height: 28px;">
			             				<div class="padding-buttom">
				             				<span style="font-family:'Khmer OS Muol Light'; text-decoration: underline;">ប្រការ២: តម្លៃផ្ទះ</span>
				             			</div>
					             			<table width="100%" border="0"> 
					             				<tr>
											    	<td align="justify" style="vertical-align:top; text-align:right; width:9%;"></td>
												    <td align="justify" style="padding-left:5px">
											    		២.១- ភាគី(ក) យល់ព្រមលក់ដី    និងផ្ទះល្វែងខាងលើជូនភាគី(ខ)  តំលៃព្រមព្រៀងចំនួន  $ 
											    		<strong><?php echo $dbparmeter->getNumberInkhmer(number_format($this->agreement['price_before'],2));?> (<span id="lable_pricekhmer" style="font-family:'Khmer os battambang';"></span> <span style="font-family:'khmer os battambang';">ដុល្លារអាមេរិក</span>)</strong>។
											    		<script>
															a_sold ='<?php echo ($this->agreement['price_before']) ?>';
															money_khmersold=read_money_in_khmer(a_sold);
															
															decimalmoney_khmersold='<?php echo substr(number_format($this->agreement['price_before'],2),-2);?>';
															str_centsold = 'សេន';
															if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
															last_number_sold='<?php echo substr(number_format($this->agreement['price_before'],2),-2);?>';
															
															if(last_number_sold<=0){last_number_sold='';}
															money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
															dojo.byId('lable_pricekhmer').innerHTML=money_khmersold+" ";
														</script>
												    </td>
												 </tr>
										</table>
				             		</span>
				             		
				             		<span style="width: 100%; display: block; line-height: 28px;">
			             				<div class="padding-buttom">
				             				<span style="font-family:'Khmer OS Muol Light'; text-decoration: underline;">ប្រការ៣: ការទូទាត់ប្រាក់</span>
				             			</div>
					             			<table width="100%" border="0"> 
					             				<tr>
											    	<td align="justify" style="vertical-align:top; text-align:right; width:9%;"></td>
												    <td align="justify" style="padding-left:5px">
												    ភាគី(ខ) ត្រូវទូទាត់ប្រាក់ថ្លៃទិញ-លក់ជូនភាគី(ក) តាមចំនួននឹងកាលបរិច្ឆេទកំណត់នៃកិច្ចសន្យានេះ ដោយឯកភាពគ្នាតាមលក្ខខណ្ឌតារាងបង់​ប្រាក់​ក្នុង (ឧបសម្ព័ន្ធទីមួយ)។ 
												    </td>
												 </tr>
										</table>
				             		</span>
				             		
				             		<span style="width: 100%; display: block; line-height: 28px;">
			             				<div class="padding-buttom">
				             				<span style="font-family:'Khmer OS Muol Light'; text-decoration: underline;">ប្រការ៤: សិទ្ធិ និងកាតព្វកិច្ចរបស់ភាគី(ក)</span>
				             			</div>
					             			<table width="100%" border="0"> 
					             				<tr>
											    	<td align="justify" style="vertical-align:top; text-align:right; width:9%;"></td>
												    <td align="justify" style="padding-left:5px">
												    ៤.១- ភាគី(ក) ធានាសាងសងផ្ទះល្វែងជូនភាគី(ខ)តាមគំនូសផ្ទះគំរូ និងសាងសង់ផ្ទះឱ្យបានរួចរាល់ក្នុងរយៈពេល ១៨ខែ គិតពីថ្ងៃចុះកិច្ចសន្យា លើកលែងក្នុងករណីប្រធានស័ក្កដូចជា៖ ទឹកជំនន់ រញ្ជួយដី វិបត្តិនយោបាយ អស្ថេរភាពសង្គមកើតឡើយ ដែលហេតុការណ៍ទាំងនេះ បណ្តាលឱ្យមានការរាំងស្ទះដល់ការសាងសង់។
													<br />
													៤.២- ភាគី(ក) ត្រូវធានារយៈពេល ០៦ខែ ចំពោះករណីជញ្ជាំង ប្រេះស្រាំ ប្រពន្ធ័លូ និងប្រព័ន្ធទឹកស្ទះ។ 
													<br />
													៤.៣- ក្នុងករណីភាគី(ក) មិនបានសាងសង់ផ្ទះល្វែងជូនភាគី(ខ) តាមការកំណត់ខាងលើនោះ ភាគី(ក) យល់ព្រមបង់ប្រាក់ពិន័យចំនួន <strong>$ ១,០០០ (មួយពាន់ដុល្លារគត់)</strong> ក្នុងមួយខែ រហូតដល់ផ្ទះសាងសង់រួចរាល់។
													<br />
													៤.៤- ភាគី(ក) អះអាងថា ផ្ទះល្វែងដែលបានលក់ខាងលើ ជាកម្មសិទ្ធិស្របច្បាប់របស់ខ្លួនយ៉ាងពិតប្រាកដ ដោយពុំជាប់ពាក់ព័ន្ធនឹងផលប្រយោជន៍រូបវន្តបុគ្គល ឬនីតិបុគ្គលណាមួយឡើយ។
													<br />
													៤.៥- ភាគី(ក) ទទួលខុសត្រូវក្នុងការកាត់ប្លង់រឹង និងបង់ពន្ធប្រថាប់ត្រាជូនភាគី(ខ) ដោយសោហ៊ុយចំណាយជាបន្ទុករបស់ភាគី(ក)។
													<br />
													៤.៦- ភាគី(ក) ទទួលខុសត្រូវក្នុងការភ្ជាប់បណ្តាញទឹករដ្ឋ ភ្លើងរដ្ឋក្នុងទំហំ ៣២អំពែ។
												    
												    </td>
												 </tr>
										</table>
				             		</span>
				             		
				             		<span style="width: 100%; display: block; line-height: 28px;">
			             				<div class="padding-buttom">
				             				<span style="font-family:'Khmer OS Muol Light'; text-decoration: underline;">ប្រការ៥ សិទ្ធិកាតព្វកិច្ចរបស់ភាគី (ខ)</span>
				             			</div>
					             			<table width="100%" border="0"> 
					             				<tr>
											    	<td align="justify" style="vertical-align:top; text-align:right; width:9%;"></td>
												    <td align="justify" style="padding-left:5px">
												    	៥.១ ភាគី(ខ) ពុំមានសិទ្ធិកែប្រែប្លង់សាងសង់ ឬសាងសង់បន្ថែមខុសពីផ្ទះគំរូឡើយ ទោះបីជាក្រោយពេលភាគី (ក) ប្រគល់ផ្ទះល្វែងជូនភាគី(ខ) រួចហើយក៏ដោយ។ <br />
														៥.២ ក្នុងកំឡុងពេលអនុវត្តន៍កិច្ចសន្យានេះ ភាគី(ខ) អាចលក់ ឬផ្ទេរកិច្ចសន្យានេះអោយអតិថិជនណាមួយ      “លុះត្រាតែផ្ទះសង់បាន ៨០%” ដោយភាគី(ខ) ត្រូវបំពេញបែបបទលក់ ឬផ្ទេរនៅមុខភាគី(ក) ជាមុនសិន។
														<br />
														៥.៣ ភាគី(ខ) ត្រូវទទួលបន្ទុកបង់សោហ៊ុយក្នុងការលក់ ឬផ្ទេរកិច្ចសន្យាចំនួន..............ជូនភាគី(ក) អតិថិជនដែលទទួលសិទ្ធិបន្តត្រូវអនុវត្តន៍តាមកិច្ចសន្យានេះទាំងស្រុង។ <br />
													 	៥.៤  ភាគី(ខ) ត្រូវអនុវត្តន៍ការទូទាត់ប្រាក់នៅស្នាក់ការរបស់ភាគី(ក)ដូចកំណត់ខាងលើ។ <br />
														៥.៥  ភាគី(ខ) ត្រូវធ្វើការទូទាត់ប្រាក់តាមប្រព័ន្ធធនាគារ ឬតាមមធ្យោបាយសមស្របណាមួយ ប្រសិនមានការ 
														  ស្នើសុំពីភាគី(ក) អ្នកតំណាងរបស់ភាគី(ខ) ឬអតិថិជនណាមួយ ដែលយកប្រាក់មកទូទាត់ថ្លៃទិញ-លក់ នៃកិច្ច
														  សន្យានេះត្រូវ សន្មត់ថាធ្វើការទូទាត់ដើម្បីប្រយោជន៍ទាំងស្រុងរបស់ភាគី(ខ)។ <br />
														៥.៦ ក្នុងករណីភាគី(ខ) ខកខានមិនបានបង់ប្រាក់ថ្លៃទិញ-លក់គ្រប់ចំនួន នឹងត្រូវអនុវត្តន៍ ដូចខាងក្រោម៖ <br />
														<ul style="margin: 0;padding: 0;list-style: none;margin-left: 40px;">
															<li>
																- ក្នុងករណីដល់ថ្ងៃកំណត់ត្រូវទូទាត់ ប៉ុន្តែភាគី(ខ) ខកខានមិនបានទូទាត់ នោះភាគី(ក) ទុកពេលជូន ភាគី(ខ) ចំនួន០៧ថ្ងៃទៀត។ បើផុតរយៈពេលនេះភាគី(ខ) បានឯកភាពថាលះសិទ្ធិក្នុងការទិញ កិច្ចសន្យានេះត្រូវរំលាយស្វ័យប្រវត្តិពុំចាំបាច់មានការជូនដំណឹងអំពីការរំលាយកិច្ចសន្យានេះ ទៅភាគី(ខ) ឡើយហើយប្រាក់ថ្លៃទិញ-លក់ដែលបានបង់កន្លងមក  ត្រូវក្លាយជាកម្មសិទ្ធិរបស់ភាគី(ក)ទាំងស្រុង និងភាគី(ក) មានសិទ្ធិយកដី  និងផ្ទះតាមកិច្ចសន្យានេះ  ទៅលក់ឲ្យអតិថិជន  ឬចាត់ចែងផ្សេងៗទៀត។
															</li>
														</ul>	
														៥.៧ ភាគី (ខ) ត្រូវបង់សេវាសន្តិសុខ អំពូលភ្លើងផ្លូវ ថែសួន អនាម័យសាធារណះ ជារៀងរាល់ខែ ចំនួនUSD............(.......................) ក្នុងមួយខែ គិតចាប់ពីថ្ងៃប្រគល់ផ្ទះ ទោះជាស្នាក់នៅ ឬមិនស្នាក់នៅក៏ដោយ។ 
														 <br />
														៥.៨ ភាគី(ខ) ត្រូវគោរពតាមបទបញ្ជាផ្ទៃក្នុង និង គោលការណ៍រួមរបស់គំរោង រួមទាំងការគ្រប់គ្រងរបស់ <strong><?php echo $boreyName?></strong>។ 
												    </td>
												 </tr>
										</table>
				             		</span>
				             		
				             		<span style="width: 100%; display: block; line-height: 28px;">
			             				<div class="padding-buttom">
				             				<span style="font-family:'Khmer OS Muol Light'; text-decoration: underline;">ប្រការ ៦ អនុភាពនៃកិច្ចសន្យា</span>
				             			</div>
					             			<table width="100%" border="0"> 
					             				<tr>
											    	<td align="justify" style="vertical-align:top; text-align:right; width:9%;"></td>
												    <td align="justify" style="padding-left:5px">
												    	៦.១ ភាគីទាំងពីរបានអានរាល់ខ្លឹមសារទាំងអស់ នៃកិច្ចសន្យានេះ ហើយសន្យាគោរពឲ្យបានរាល់ខ្លឹមសារទាំងអស់នៃកិច្ចសន្យា បើភាគីណាមួយមិនគោរព នឹងត្រូវទទួលខុសត្រូវចំពោះមុខច្បាប់ជាធរមាន។ 
														<br />
														៦.២ កិច្ចសន្យានេះធ្វើឡើង ដោយស្ម័គ្រចិត្តរវាងភាគីទាំងពីរ ឥតមានការបង្ខិតបង្ខំ ឬគំរាមកំហែងពីភាគីណាមួយ ឬ ពីតតិយជនណាមួយឡើយ។
														<br />
														៦.៣ ការជូនដំណឹងទៅភាគីនីមួយៗ ត្រូវផ្ញើទៅអាសយដ្ឋាន ដូចបញ្ជាក់ខាងលើ ឬបញ្ជូនលិខិតដោយផ្ទាល់ និង តាមការជូនដំណឹងតាមរយៈទូរស័ព្ទ។ 
														<br />
														៦.៤ កិច្ចសន្យានេះធ្វើឡើងចំនួន ០៣ច្បាប់ ក្នុងមួយច្បាប់មានបីទំព័រ រក្សាទុកនៅភាគី(ក) ចំនួន០១ច្បាប់     ភាគី(ខ) ចំនួន ០១ច្បាប់ និង មេធាវីភាគី(ក) ចំនួន 0១ច្បាប់ មានតម្លៃស្មើៗគ្នា។
														<br />
														៦.៥ ដើម្បីបញ្ជាក់កិច្ចសន្យានេះ  ភាគីទាំងពីរសុខចិត្តផ្តិតមេដៃទុកជាភស្តុតាង នៅចំពោះមុខមេធាវីភាគី(ក)។
														<br />
														៦.៦ កិច្ចសន្យាទិញ-លក់ ផ្ទះល្វែងនេះ មានប្រសិទ្ធិភាពចាប់ពីថ្ងែផ្តិតមេដៃ នេះតទៅ ។
												    </td>
												 </tr>
										</table>
				             		</span>
		             		</p>
		             	</td>
		             </tr>
		             <tr>
		             	<td colspan="3">
		             		<table align="center" width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';">
		             				<tr>
								        <td  colspan="7" class="reff" style="text-align:right; font-family:'Khmer OS Battambang';font-weight:200;white-space:nowrap;">រាជធានីភ្នំពេញ ថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['agreement_date'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['agreement_date'])));?></td>
								   </tr>
								   <tr style="font-size: 14px;">
								        <td class="reff" style="width:23%;text-align:center; font-weight:200;white-space: nowrap;">ស្នាមមេដៃស្តាំភាគី (ក)</td>
								        <td>&nbsp;</td>
								        <td class="reff" style="width:23%;text-align:center; text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;"></td>
								        <td>&nbsp;</td>
								        <td class="reff" style="width:23%;text-align:center; text-decoration:underline; font-weight:200;"></td>
								        <td colspan="2" class="reff" style="text-align:center; font-family:'Khmer OS Muol Light';font-weight:200;">ស្នាមមេដៃស្តាំភាគី (ខ)</td>
								   </tr>
								   <tr height="80px">
						             	<td>&nbsp;</td>
						           </tr>
						           <tr style="font-size: 14px;">
						           		 <td class="reff" colspan="2" align="center" style="white-space:nowrap;font-family:'Khmer OS Muol Light'">&nbsp;<?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"/".$this->agreement['hname_kh']:"";?></td>
								        <td class="reff" align="center" colspan="3" style=""></td>
								        <td colspan="2" style="text-align:center;font-family:'Khmer OS Muol Light'"><?php echo $this->agreement['project_manager_namekh'];?></td>
								 </tr>
							</table>
		             	</td>
		             </tr>
		             <tr height="15px">
						    <td colspan="3">&nbsp;</td>
					</tr>
		            <tr>
		             	<td colspan="3">
		             		<table align="center" width="100%" style="font-weight:bold;font-family: 'Times New Roman','Khmer OS Battambang';">
		             			<tr style="font-size: 14px;">
		             				 <td align="center" class="reff" style="font-family:'Khmer OS Muol Light';font-weight:200;">បានឃើញ</td>
		             			</tr>
		             			<tr style="font-size: 14px;">
		             				 <td align="center" class="reff" style=" font-family:'Khmer OS Battambang';font-weight:200;">គូភាគីព្រមព្រៀងផ្តិតស្នាមមេដៃនៅចំពោះមុខមេធាវី</td>
		             			</tr>
		             			<tr style="font-size: 14px;">
		             				 <td align="center" class="reff" style="font-family:'Khmer OS Battambang';font-weight:200;">រាជធានីភ្នំពេញថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['agreement_date'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['agreement_date'])));?></td>
		             			</tr>
		             			<tr style="font-size: 14px;">
		             				 <td align="center" class="reff" style="font-family:'Khmer OS Muol Light';font-weight:200;">ហត្ថលេខា និង ត្រា</td>
		             			</tr>
		             		</table>
		             	</td>
		            </tr>
		             <tfoot>
		             <tr height="60px">
						    <td colspan="3">&nbsp;</td>
					</tr>
					</tfoot>
		        </table>
		        	<div id="printfooter">
		        		<table  width="100%" style="background: #fff;border-top: 2px solid #000;font-family: 'Khmer OS Battambang'; font-size:10px;line-height: 15px;white-space:nowrap;"> 
							<tbody>
								<tr style="white-space:nowrap;line-height: 15px;">
									<td width="40%" align="left">&#x260F; <?php echo $this->keyValue['tel-client'];?></td>
									<td width="40%" align="right"><?php echo $this->keyValue['footer_branch'];?></td>
								</tr>
								
							</tbody>
						</table>
		        	</div>
		        	</div>
		        </div>
    	</td>	
</tr>
</table>
</div>