<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_cancel;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id_search'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id_search']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("CANCEL_SALE_REPORT");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-cancel-sale')); ?>" dojoType="dijit.form.Form" method="post">
		<table style="margin: 0 auto;">
			 <tr>
				<td><?php echo $frm->getElement('adv_search');?></td>
				<td><?php echo $frm->getElement('branch_id_search');?></td>
				<td><?php echo $frm->getElement('property_type');?></td>
				<td><?php echo $frm->getElement('client_name');?>
				<td><?php echo $frm->getElement('from_date_search');?></td>
				<td><?php echo $frm->getElement('to_date_search');?></td>
				<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			</tr>
		</table>
	 </form> 
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint">
	    	 	<style>
					.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
						}
						th{padding: 2px;}
						.hide{visibility: hidden;}
								@media print {
								  div.divFooter {
								    position: fixed;
								    top: 0;
								  	width: 100%;
								  	height: 100px;
								  	bottom:0px;
									margin:0;
								  }
								.hide{visibility: visible; height: 110px;}
								}
						table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:13px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
							width: 100%;
						}
						table.content-data thead tr.style {
						   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
							background: #c1d0f3;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
					</style>
	        		<div class="divFooter">
	        			<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0 auto;padding:0px; border:none;">
				        	<tr>
				                <td width="30%"><img src="<?php echo $logo;?>" height="85px"></td>
				                <td width="40%" valign="top">
				                <h2 style="text-align:center; font-size:18px; font-weight:normal; font-family:'Khmer OS Muol Light'"><?php echo $branch_title;?></h2>
				                <h2 style="text-align:center; font-size:16px; font-weight:normal; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("CANCEL_SALE_REPORT");?></h2>
				                <h2 style="text-align:center; font-size:16px; font-weight:normal;"><?php if(!empty($this->search['from_date_search'])){echo date("d-M-Y",strtotime($this->search['from_date_search'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['to_date_search']));}?></h2>
				                <td width="30%"></td>
				             </tr> 
			             </table>
			          </div>
		          <table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0; border:none;" >
		            <tr>
		            	<td colspan="3">
		            		<table id="exportExcel" class="content-data" width="100%"  border="1" >  
						      	 <thead>
					                <tr class="hide" style="border:1px solid #000;">
						                <td colspan="16" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						            </tr>
							      	<tr bgcolor="#a0baf5" class="style" align="center"  >
										<td><?php echo $tr->translate("NUM");?></td>
										<td><?php echo $tr->translate("PROJECT_NAME");?></td>
										<td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
										<td><?php echo $tr->translate("PROPERTY_TYPE");?></td>
										<td><?php echo $tr->translate("PROPERTY_CODE");?></td>
										<td><?php echo $tr->translate("PRICE");?></td>
						                <td><?php echo $tr->translate("PAID");?></td>
						                <td><?php echo $tr->translate("BALANCE");?></td>
						                <td><?php echo $tr->translate("INSTALLMENT_PAID");?></td>
						                <td><?php echo $tr->translate("RETURN_MONEY_BACK");?></td>
									    <td><?php echo $tr->translate("DATE");?></td>
									    <td><?php echo $tr->translate("REASON");?></td>
									    <td><?php echo $tr->translate("BY_USER");?></td>
									</tr>
								</thead>
						       <?php $property_type=''; $i=0; $total=0; 
						       if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
								<?php 
									$property_type= $row['property_type'];
								?>
								   <tr style="font-size: 12px;white-space: nowrap;" align="left">
								     <td align="center">&nbsp;<?php echo $i; ?></td>
								     <td>&nbsp;<?php echo $row['project_name'];?></td>
								     <td align="center">&nbsp;<?php echo $row['client_name'];?></td>
									 <td align="center">&nbsp;<?php echo $row['type_name'];?></td>
									 <td align="center">&nbsp;<?php echo $row['land_address'].','.$row['street'];?></td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo number_format($row['price_sold']-$row['other_fee'],2); ?>$</td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo number_format($row['paid_amount']);?> $</td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo number_format($row['price_sold']-$row['other_fee']-$row['paid_amount']);?> $</td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo (empty($row['installment_paid'])?"កក់ដំបូង":$row['installment_paid']);?> </td>
									 <td align="left" style="font-size: 10px;">&nbsp;<?php echo $row['return_back'];?></td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-M-Y",strtotime($row['create_date']));?> </td>
									 <td align="left" style="font-size: 10px;max-width:180px;white-space: pre-line;">&nbsp;<?php echo $row['reason'];?></td>
									 <td align="center" >&nbsp;<?php echo $row['user_name'];?>&nbsp;</td>
								  </tr>
								<?php 
								$total = $total+$row['return_back'];
						       }?>
								<tr style=" border-bottom: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;">
									<td colspan="14"  align="right">
										<table align="right" style="margin-right: 6px;">
										    <tr style="font-size:10px; color:#000; height: 18px;" align="center">
												<td style="width:146px;font-size: 14px;">&nbsp;ប្រាក់ប្រគល់សរុប&nbsp;</td>
												<td style="background: rgba(249, 225, 11, 0.7); color:#000; font-weight:bold; width:112px; font-size: 14px;"><?php echo number_format($total,2);?></td>
										  </tr>
										</table>
									</td>
								</tr>
						    </table>
		            	</td>
		             </tr>
		           </table>
			           <table align="center" width="100%">
						   <tr style="font-size: 14px;">
					        <td style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center;font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
						   </tr>
						</table>
	            </div>
	    	</td>
	    </tr>
	</table>
</div>