<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_property;

$dbGB = new Application_Model_DbTable_DbGlobal();
$logo = $this->baseUrl()."/images/logo.jpg";
$branch_title = $tr->translate("BRAND_TITLE");
if ($this->list_end_date['branch_id'] >0 ){
	$branch = $dbGB->getAllBranchInfoByID($this->list_end_date['branch_id']);
	if(file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
		$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
	}
	$branch_title = $branch['project_name'];
}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_PROPERTY");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('REPORT_PROPERTY');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-properties')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("branch_id");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("streetlist");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("property_type");?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("type_property_sale");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('start_date');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"  type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
				</div>
			</div>
		</div>
 </form> 
<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint">
    	 	<style>
			.style{
				line-height: 20px;font-size: 11px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
				}
				th{padding: 5px;}
				.hover:hover{background: #ccc;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
			table.content-data{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:13px;
				font-family: 'Times New Roman','Khmer OS Battambang';
				white-space: nowrap;
				line-height: 22px;
				width: 100%;
			}
			table.content-data thead tr.style {
			   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #c1d0f3;
			}
			table.tb-footer{
				border-collapse:collapse;
				border:1px solid #000; 
				font-family: 'Times New Roman','Khmer OS Battambang';
				font-size:11px;
			}
			table.tb-footer tr{
			 line-height: 14px;  padding:2px 0px; height: 25px;
			}			
			.border_bottom {
				border-bottom: 1px solid #000;
			}
			table tr td{
				padding:0 2px;
			}
 		</style>
	<div class="divFooter">
	    <table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;" >
	        <tr>
	          	<td width="30%"><img src="<?php echo $logo;?>" style="height:80px;max-width: 100%;"></td>
	              <td width="40%" valign="top">
	                <ul>
	                	<li style="white-space:nowrap;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $branch_title;?></li>
	                	<li style="white-space:nowrap;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("TABLE_PROPERTY");?></li>
	                	<li style="text-align:center; font-size:14px;"><?php if(!empty($this->list_end_date['start_date'])){ echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';}echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></li>
		            </ul>
		           </td>
	               <td width="30%"></td>
	         </tr> 
	   </table>
	</div>
     <table id="exportExcel" border="1" class="content-data" width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0; padding:0; border:1px solid #000; border-collapse: collapse;" >
		<?php
		   $all_totalland = 0;$all_totalhouse =0;$all_total=0;$all_propertype=0;
	       $total_land_pric=0; $total_house_price = 0; $property_type=0; $i=0; $total=0;
	       $is_lock=0; 
	       if(!empty($this->row))foreach($this->row as $key =>$row){?>
	     <?php  
	      	$all_totalhouse=$all_totalhouse+$row['house_price'];
	      	$all_total=$all_total+$row['price'];
	      	$all_propertype = $key+1;
	      	if($row['is_lock']=='null'){
	      		$row['is_lock']=0;
	      	}
	      	if($row['is_lock']==1){//ban sell hz
	      		$is_lock=$is_lock+1;
	      	}
			if($row['property_type']!=$property_type){	
				if($key>0 ){
			?>
			<tr >
				<td colspan="12" style="border-left: solid 1px #fff;">
					<br />
					 <table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
		                 <tr bgcolor="#a0baf5" class="style" style=" line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                 	<td></td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PROPERTY");?></span></td>
		                    <!-- 
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL_LAND_PRICE");?></span></td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL_HOUSE_PRICE");?></span></td>
		                     -->
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
		                    <td></td>
		                    <td></td>
		                    
		                    <td></td>
		                 </tr>
		                  <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                  	<td></td>
		                  	<td align="center"><?php echo $i;?></td>
		                    <!-- 
		                    <td align="center"><?php echo number_format($total_land_pric,2);?></td>
		                    <td align="center"><?php echo number_format($total_house_price,2);?></td>
		                     -->
		                    <td align="center"><strong><?php echo number_format($total,2);?></strong></td>
		                    <td></td>
		                    <td></td>
		                    <td></td>
		                  </tr>
			          </table>
			          <br />
				</td>
			</tr>
				<?php $i=0; $total_land_pric=0;$total_house_price=0;$total_house_price=0;$total=0;}?>
		     <thead>
		     	<tr bgcolor="#c1d0f3" class="style hover" align="center"  >
					<td><?php echo $tr->translate("NUM");?></td>
					<td><?php echo $tr->translate("BRANCH_NAME");?></td>
					<td><?php echo $tr->translate("PROPERTY_CODE");?></td>
					<td><?php echo $tr->translate("STREET_NO");?></td>
					<td><?php echo $tr->translate("PROPERTY_TYPE");?></td>
					<td><?php echo $tr->translate("SIZE");?></td>
					<td><?php echo $tr->translate("WIDTH");?></td>
					<td><?php echo $tr->translate("HEIGHT");?></td>
					<td><?php echo $tr->translate("PRICE");?></td>
					<td><?php echo $tr->translate("NOTE");?></td>
					<td><?php echo $tr->translate("BY_USER");?></td>
					<td><?php echo $tr->translate("STATUS");?></td>
				</tr>
			</thead>
			<?php }  $i++;?>
			   <tr class="hover" style="font-size: 12px;border:1px solid #000; white-space: nowrap;line-height: 25px;<?php if ($row['is_lock']==1){ echo'background:#fbbfbf;';}?>" align="left">
			     <td align="center"><?php echo $i; ?></td>
			     <td align="center"><?php echo $row['branch_name'];?></td>
			     <td align="center"><?php echo $row['land_address'];?></td>
				 <td align="center"><?php echo $row['street'];?></td>
				 <td ><?php echo $row['pro_type'];?></td>
				 <td align="center"><?php echo $row['land_size'];?></td>
				 <td align="center"><?php echo $row['width'];?></td>
				 <td align="center"><?php echo $row['height'];?></td>
				 <td align="right"><?php echo number_format($row['price'],2);?>​</td>
				 <td align="left"><span style="max-width: 220px; width: 220px; display: block; white-space: pre-line; line-height: 16px; overflow-wrap: break-word;padding: 0 1px;" ><?php echo $row['note'];?></span></td>
				 <td><?php echo $row['user_name']?></td>
				 <td align="center" ><?php if ($row['is_lock']==1){ echo $tr->translate("SOLD_OUT");}else{ echo $tr->translate("NOT_YET_SALE"); }?></td>
			 </tr>
				<?php $total = $total + $row['price'];
				$total_land_pric= $total_land_pric +$row['land_price'];
				$total_house_price= $total_house_price +$row['house_price'];
				$property_type = $row['property_type'];
				$all_totalland = $all_totalland+$row['land_price'];
				?>
			<?php }?>
			<?php if(!empty($this->row)){?>
			<tr >
				<td colspan="12" style="border-left: solid 1px #fff;border-bottom: solid 1px #fff;border-right: solid 1px #fff;">
					<br />
					 <table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
		                 <tr bgcolor="#a0baf5" class="style" style=" line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                 	<td></td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PROPERTY");?></span></td>
		                    <!-- 
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL_LAND_PRICE");?></span></td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL_HOUSE_PRICE");?></span></td>
		                     -->
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
		                    <td></td>
		                 </tr>
		                  <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                  	<td></td>
		                  	<td align="center"><?php echo $i;?></td>
		                    <!-- 
		                    <td align="center"><?php echo number_format($total_land_pric,2);?></td>
		                    <td align="center"><?php echo number_format($total_house_price,2);?></td>
		                     -->
		                    <td align="center"><strong><?php echo number_format($total,2);?></strong></td>
		                    <td></td>
		                  </tr>
			          </table>
			          <br />
				</td>
			</tr>
			<tr>
            	<td colspan="13" style=" border: #fff solid 1px;    border-top: solid 1px #000;">
	            	 <br />
		             <table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
		                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                 	<td></td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("PROPERTY");?></span></td>
		                    <td align="center"></td>
		                    <td align="center"></td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("PRICE");?></span></td>
		                    <td></td>
		                 </tr>
		                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                    <td align="center"><?php echo $tr->translate("TOTAL_PROPERTY");?></td>
		                    <td align="center"><?php echo $all_propertype;?></td>
		                    <td></td>
		                    
		                    <td align="right"><?php echo $tr->translate("TOTAL");?>$</td>
		                    <td align="right"><strong><?php echo number_format($all_total,2);?></strong></td>
		                    
		                    <!-- 
		                    <td align="right"><?php echo $tr->translate("TOTAL_LAND_PRICE");?>$</td>
		                    <td align="right"><strong><?php echo number_format($all_totalland,2);?></strong></td>
		                     -->
		                    <td></td>
		                 </tr>
		                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                 	 <td align="center"><?php echo $tr->translate("PROPERTY").$tr->translate("SOLD_OUT");?></td>
		                 	 <td align="center"><?php echo $is_lock;?></td>
		                 	 <td></td>
		                 	<!-- 
		                 	 <td align="right"><?php echo $tr->translate("TOTAL_HOUSE_PRICE");?>$</td>
		                 	 <td align="right"><strong><?php echo number_format($all_totalhouse,2);?></strong></td>
		                 	 -->
		                 	 <td></td>
		                 	 <td></td>
		                 	 
		                 	 <td></td>
		                 </tr>
		                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                    <td align="center"><?php echo $tr->translate("PROPERTY").$tr->translate("NOT_YET_SALE");?></td>
		                    <td align="center"><?php echo $all_propertype-$is_lock;;?></td>
		                    <td></td>
		                    <!-- 
		                    <td align="right"><?php echo $tr->translate("TOTAL");?>$</td>
		                    <td align="right"><strong><?php echo number_format($all_total,2);?></strong></td>
		                     -->
		                     <td></td>
		                 	 <td></td>
		                 	 
		                    <td></td>
		                 </tr>
		             </table>
	            </td>
	         </tr>
			
			<?php }?>
	    </table>
	 </div>
	</td>
  </tr>
</table>
</div>