<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$day = array(
			"Mon" =>'ច័ន្ទ',
			"Tue" =>'អង្គារ',
			"Wed" =>'ពុធ',
			"Thu" =>'ព្រហស្បតិ៍',
			"Fri" =>'សុក្រ',
			"Sat" =>'សៅរ៍',
			"Sun" =>'អាទិត្យ',
			);
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	$dbparmeter = new Report_Model_DbTable_DbParamater();
	$key = new Application_Model_DbTable_DbKeycode();
	$dataterm = $key->getKeyCodeMiniInv(TRUE);
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title style="color:#fff;"><?php echo $tr->translate(".");?></title>
<style>
	#divPrint .reff{ font-size: 20px !important; line-height:34px !important;}
	#divPrint tr td h2,#divPrint p, #divPrint pre, #divPrint span{ font-size: 20px !important; line-height:34px !important;}
	#divPrint #padding-left-p-2{
	 padding-left: 105px !important;	
	}
	#divPrint .padding-buttom{
		margin-top: -5px !important;
	}
#mainbody{
	    display: block !important;
    position: relative !important;
}
#watermark{
	display: none !important;	
}
ul.blogsub li{
	line-height:34px !important;
}
#printfooter{display: none !important;}
</style>
<?php    
    $paid=0; 
    $addressIssue = "ផ្ទះលេខ 287BE<sub>2</sub> ផ្លូវ 182 ភូមិ 13 សង្កាត់ ទឹកល្អក់ 2 ខណ្ឌ ទួលគោក រាជធានី ភ្នំពេញ";
    
	$propertytype = $this->agreement['property_type'];
    if($propertytype==1){// L
    	$str_sizehouse='4.3m x 15m';
    }else{//LV
    	$str_sizehouse='4.5m x 11m';
    }
?>
<!-- Start Land and House -->
		<div  id="exportword" style="min-height:22cm; margin:0 auto;padding:0px 0.5cm">
			<table style="font-family: 'Khmer OS Content'; width:100%;"  >
				<tr>
			    	<td align="center">
				    	 <div id="divPrint" style="position: relative;" >
				    	 	<style>		
								body {
								    position: relative;
								}
							    #divPrint #padding-left-p-2{
								 padding-left: 105px !important;	
								}
								#divPrint .padding-buttom{
									margin-top: -5px !important;
								}
		    	 				#divPrint .reff{ font-size: 16px !important; line-height:34px !important;}
								#divPrint tr td h2,#divPrint p, #divPrint pre, #divPrint span{ font-size: 16px ; line-height:30px;}
								#divPrint #padding-left{
								padding-left: 18px;
								}
								#divPrint #bold-padding-right{
									margin-right: 15px;
									font-family: khmer os battambang;
									font-size:19px;
								}
								
								#divPrint #padding-left-2{
								/*margin-top: -10px;*/
								padding-left:15px;
								}
								#divPrint .padding-buttom{
									margin-top: -5px;
								}
								#divPrint #padding-left-p-2{
								 margin-top:-1px; 
								 padding-left: 85px;	
								}
								#divPrint #padding-left-p{
							    padding-left: 105px;
								}
								#divPrint th{padding: 5px;}
								#divPrint span.value{ line-height:12px;display: inline-block; text-align: center;}
								#divPrint span.child {display:block; margin-left:25px; line-height: 25px;}
								#divPrint span{line-height: 26px;}
								body {
								    position: relative;
								}
								
								ul.blogsub li{
									list-style-type: square;
									line-height: 26px;
								}
								ul.reference li{
									line-height: 26px;
									list-style: none;
								}
								ul.blogsub{
									padding:0;margin:0;
								}
								#printfooter {
								    position: absolute;
								    bottom: -2;
								    position: fixed;
								    display: block ;
								}
@page {

        margin-bottom: 40px;
        counter-increment: page;

        @bottom-right {
            border-top: 1px solid #000000;
            padding-right:20px;
            font-size: 12px !important;
            content: "Page " counter(page) " of " counter(pages);
        }
        @bottom-left {
            content: "Footer content goes here.";
            border-top: 1px solid #000000;
        }

    }		</style>
		    	<div id="mainbody" style="position: absolute;z-index: 5;top: 0;height: 100%;">
		    	  <div id="watermark" style=" top: 0; position: fixed; display: block; height: 100%;z-index: -1; width: 100%;  opacity: 0.3;" ></div>
		        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="padding:0;margin:0;border:0px;" >
			        	<tr>
			                <td width="30%" valign="top"></td>
			                <td width="40%" align="center">
			                	<span style="text-align:center; line-height:28px; font-size:16px;font-family:'Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា</span>
				                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
				                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.jpg" height="25px"></span>
				                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("កិច្ចសន្យា ទិញ-លក់ ផ្ទះល្វែង");?></span>
	              			</td>
			                <td width="30%"></td>
			             </tr> 
			             <tr>
			             	<td colspan="3">
			                	<span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Battambang'">កិច្ចសន្យានេះធ្វើឡើងនៅថ្ងៃទី  <?php echo date("d",strtotime($this->agreement['agreement_date']));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo date("Y",strtotime($this->agreement['agreement_date']));?> <br />
			                	<span style="font-family:'Khmer OS Muol Light';">រវាង</span></span>
			             	</td>
			             </tr>
			             <tr>
			             	<td colspan="3">
			             		<p style="margin:0 auto;font-family:'Khmer OS Battambang','Times New Roman';text-align: justify; text-justify: inter-word;line-height:24px; font-weight: normal !important;">
									<span style="text-align:left; min-width: 100%; display: inline-block;text-indent: 40px;">
									ឈ្មោះ  <span style=" font-family:'Khmer OS Muol Light';"><?php echo $this->agreement['project_manager_namekh'];?></span> កើតឆ្នាំ 1980 កាន់អត្តសញ្ញាណប័ណ្ណលេខ  <span class="value" style="min-width:30px;"><?php echo $this->agreement['project_manager_nation_id'];?></span> 
									មានទីលំនៅ <?php echo $this->agreement['project_manager_p_current_address'];?>
									ជាអ្នកលក់ តទៅហៅថា ភាគី(ក) ។
									</span>
									<span style="font-weight:200; text-align:left; min-width: 100%; display: inline-block;">ទូរស័ព្ទការិយាល័យទំនាក់ទំនងលេខ ៖  <?php echo $this->agreement['branch_tel'];?></span>
									<span style="font-weight:200; text-align:center; min-width: 100%; display: inline-block;font-family:'Khmer OS Muol Light'">និង</span>
									<span style="text-align:left; min-width: 100%; display: inline-block;text-indent: 40px;">
									ឈ្មោះ <span class="value" style="min-width:100px;font-family:'Khmer OS Muol Light';"><?php echo $this->agreement['client_namekh'];?></span>
									ភេទ <span class="value" style="min-width:30px;"><?php echo $this->agreement['sexKh'];?></span>
									កើតឆ្នាំ<span class="value" style="min-width:30px;"><?php if (!empty($this->agreement['dob'])){ echo date("Y",strtotime($this->agreement['dob']));}?></span>
									កាន់<?php echo $this->agreement['client_d_type'];?>លេខ<span class="value" style="min-width:80px;"><?php echo $this->agreement['client_nation_id'];?></span>	
									មានទីលំនៅផ្ទះលេខ <span class="value" style="min-width:55px;"><?php echo $this->agreement['client_house_no'];?></span>
									 ផ្លូវ <span class="value" style=""><?php echo $this->agreement['client_street'];?></span> 
									  ភូមិ <span class="value" style="min-width:50px;"><?php echo str_replace("ភូមិ", "", $this->agreement['client_village_kh']);?></span>
									  ឃុំ/សង្កាត់  <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_commune_kh'];?></span>
									 ស្រុក/ខណ្ឌ/ក្រុង  <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_districtkh'];?></span>
									 ខេត្ដ/រាជធានី  <span class="value" style="min-width:50px;">&nbsp;<?php echo $this->agreement['client_province_kh'];?></span>
									<?php if(!empty($this->agreement['hname_kh'])){?>
									និងឈ្មោះ  <span class="value" style="min-width:130px;font-family:'Khmer OS Muol Light';"><?php echo $this->agreement['hname_kh'];?></span> 
									ភេទ <span class="value" style="min-width:30px;"><?php echo $this->agreement['partner_gender'];?></span>
									កើតឆ្នាំ<span class="value" style="min-width:30px;"><?php if (!empty($this->agreement['dob_buywith'])){ echo date("Y",strtotime($this->agreement['dob_buywith']));}?></span>
									កាន់<?php echo $this->agreement['joint_doc_type'];?>លេខ <span class="value" style="min-width:100px;"><?php echo $this->agreement['rid_no'];?></span>  
									មានទីលំនៅផ្ទះលេខ<span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_house'];?></span>
									ផ្លូវលេខ<span class="value" style="min-width:30px;"><?php echo $this->agreement['w_street'];?></span>
									ភូមិ <span class="value" style="min-width:30px;"><?php echo str_replace("ភូមិ", "",$this->agreement['w_client_village_kh']);?></span>
									ឃុំ/សង្កាត់ <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_commune_kh'];?></span> 
									ស្រុក/ខណ្ឌ/ក្រុង <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_districtkh'];?></span> 
									ខេត្ត/រាជធានី  <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_province_kh'];?></span>	  
									<?php }?>
									ជាអ្នកទិញតទៅហៅថា  ភាគី(ខ)។
									</span>
				             			<span class="value" style="min-width:100px;">ទូរស័ព្ទទំនាក់ទំនងលេខ  ៖  <?php echo $this->agreement['phone'];?></span>
				             				<br /><span style="font-family:'Khmer OS Muol Light';">យោង ៖</span>
				             			<ul class="reference" style="padding-top:0;margin-bottom: 0;margin-top:-5;list-style-type: none;text-align:justify; margin-left: -20px" start="1">
				             				<li ><span>- ឧបសម្ព័ន្ធ១ ៖ តារាងកាលវិភាគបង់ប្រាក់</span></li>
				             				<li ><span>- ឧបសម្ព័ន្ធ២ ៖ ប្លង់ទីតាំងផ្ទះក្នុងគម្រោង</span></li>
				             				<li ><span>- ឧបសម្ព័ន្ធ៣ ៖ សម្ភារៈដែលបំពាក់ក្នុងគេហដ្ឋាន</span></li>
										</ul>   				
										<span>ដោយផ្អែកលើគោលការណ៍ស្ម័គ្រចិត្ត និងស្មើភាពភាគី(ក) និងភាគី(ខ) បានព្រមព្រៀងគ្នា​ធ្វើកិច្ចសន្យាទិញ-លក់ដូចខាងក្រោម៖</span>
				             			<span style="width: 100%; display: block; line-height: 32px;">
				             				<div class="padding-buttom">
					             				<span style="font-family:'Khmer OS Muol Light';">ប្រការ១៖  <span id="padding-left-2">កម្មវត្ថុនៃការទិញ-លក់ និងតម្លៃ</span></span>
					             			</div>
						             			<table width="100%" border="0"> 
												  <tr>
													    <td align="justify" style="vertical-align:top; text-align:center;width:9%;"></td>
													    <td align="justify" style="padding-left:5px">
													    	<ul class="blogsub">
												    			<li>
													    			ភាគី(ក) យល់ព្រមលក់ ហើយភាគី(ខ) យល់ព្រមទិញផ្ទះ ដែលមានអាសយដ្ឋាន
													    			 ផ្ទះលេខ <span class="value" style="min-width:70px;"><?php echo $this->agreement['property_title'];?></span> 
																	  ផ្លូវលេខ<span class="value" style="min-width:100px;"><?php echo $this->agreement['property_street'];?></span>
																	  ក្នុងតម្លៃ  USD <?php echo number_format($this->agreement['price_before'],2);?> (<label id="lable_pricekhmer" style="font-family:'Khmer os battambang';"></label><span style="font-family:'khmer os battambang';">ដុល្លារអាមេរិក)</span>
																	  ដែលមានទីតាំងស្ថិតនៅ  <?php echo $this->agreement['project_location'];?> ។
																	 តម្លៃនេះជាតម្លៃដែលមានបំពាក់សម្ភារៈប្រើប្រាស់ដូចមានក្នុងឧបសម្ព័ន្ធ៣។ ផ្ទះប្រភេទ  <?php echo $this->agreement['property_type_en'];?> មានទំហំ <?php echo $this->agreement['property_width'];?>m x <?php echo $this->agreement['property_height'];?>m សំរាប់ជាន់ E<sub>0</sub> ទំហំ  <?php echo $this->agreement['land_width'];?>m x <?php echo $this->agreement['land_height'];?>m<?php //echo $str_sizehouse; ?> សំរាប់ជាន់ E<sub>1</sub> 
																	 <!-- មានទំហំដី <?php //echo $this->agreement['property_width'];?>m x <?php //echo $this->agreement['property_height'];?>m --> ដែលមានដូចខាងក្រោម៖
												    			</li>
												    		</ul>
													    </td>  
												  </tr>
												  <script>
														a_sold ='<?php echo ($this->agreement['price_before']) ?>';
														money_khmersold=read_money_in_khmer(a_sold);
														
														decimalmoney_khmersold='<?php echo substr(number_format($this->agreement['price_before'],2),-2);?>';
														str_centsold = 'សេន';
														if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
														last_number_sold='<?php echo substr(number_format($this->agreement['price_before'],2),-2);?>';
														
														if(last_number_sold<=0){last_number_sold='';}
														money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
														dojo.byId('lable_pricekhmer').innerHTML=money_khmersold+" ";
												</script>
												<tr>
													<td></td>
													<td>
														<table border="0" cellpadding="0" cellspacing="0">
													  		<tr>
														  		<td>១. 	បន្ទប់គេង</td>
														  		<td>ចំនួន២</td>
														  	</tr>
														  	<tr>
														  		<td>២. 	បន្ទប់ទឹក</td>
														  		<td>ចំនួន៣</td>
														  	</tr>
														  	<tr>
														  		<td>៣.	បន្ទប់ទទួលភ្ញៀវ&nbsp;&nbsp;&nbsp;&nbsp;</td>
														  		<td>ចំនួន១</td>
														  	</tr>
														  	<tr>
														  		<td>៤. 	ផ្ទះបាយ</td>
														  		<td>ចំនួន១</td>
														  	</tr>				  			
														</table>
													</td>
												</tr>
											</table>
					             		</span>
					             		<span style="width: 100%; display: block; line-height: 32px;">
				             				<div class="padding-buttom">
					             				<span style="font-family:'Khmer OS Muol Light';">ប្រការ២៖	<span id="padding-left-2">កាលបរិច្ឆេទនៃការបង់ប្រាក់</span></span>
					             			</div>
					             				<table width="100%" border="0"> 
												  <tr>
													    <td align="justify" style="vertical-align:top; text-align:right; width:9%;"></td>
													    <td align="justify" style="padding-left:5px">
														    <ul class="blogsub">
														    	<li>ភាគី (ខ) ត្រូវទូទាត់ប្រាក់សរុបថ្លៃទិញផ្ទះតាមដំណាក់កាលជាបន្តបន្ទាប់ដូចមានចែងក្នុងតារាងកាលវិភាគបង់ប្រាក់ក្នុងឧបសម្ព័ន្ធ១។ 
														    	ភាគី(ខ) អាចមកបង់ប្រាក់នៅការិយាល័យផ្ទាល់ ឬអាចបង់ប្រាក់ចូលគណនីរបស់ភាគី(ក)   តាមរយៈធនាគារ<strong> ABA</strong> ដែលមានគណនីឈ្មោះ <strong>អែម សុគៀង និង តាំង គួងហាវ</strong> លេខគណនី <strong>000563989</strong>។</li>
														    	<li>
														    		ក្នុងករណីដែលភាគី(ខ) យឺតយ៉ាវ ឬខកខានមិនបានបង់ប្រាក់តាមកាលកំណត់ក្នុងតារាងកាលវិភាគបង់ប្រាក់លើសរយៈ​​ពេល ១០ថ្ងៃ នោះភាគី(ខ)​ ត្រូវបង់ប្រាក់ពិន័យក្នុងអត្រា ១០% (ដប់ភាគរយ) នៃទឹកប្រាក់ត្រូវបង់ក្នុងមួយខែ។ ករណីមានការយឺតយ៉ាវ និងខកខានបង់ប្រាក់លើសពី៣ខែ នោះចាត់ទុកថាភាគី(ខ) បានបោះបង់ចោលការទិញផ្ទះនេះជាឯកតោភាគី។ ក្នុងករណីនេះភាគី(ក) មានសិទ្ធិលក់ផ្ទះខាងលើអោយទៅអ្នកផ្សេងទៀតបាន ហើយប្រាក់ដែលភាគី(ខ) បានបង់គ្រប់ដំណាក់កាលនីមួយៗត្រូវចាត់ទុកជាអសារបង់។
														    	</li>
														    </ul>
													    
													   </td>  
												  </tr>
											</table>
					             		</span>
					             		
				             			<span style="width: 100%; display: block; line-height: 32px;">
				             				<div class="padding-buttom">
					             				<span style="font-family:'Khmer OS Muol Light';">ប្រការ៣៖	<span id="padding-left-2">កាតព្វកិច្ច និងការទទួលខុសត្រូវរបស់ភាគី(ក)</span></span>
					             			</div>
					             				<table width="100%" border="0"> 
												  <tr>
													    <td align="justify" style="vertical-align:top; text-align:right; width:9%;"></td>
													    <td align="justify" style="padding-left:5px">
														    <ul class="blogsub">
														    	<li>ភាគី(ក) ធានាថាផ្ទះល្វែងនៃគម្រោងជាដីស្របច្បាប់។</li>
														    	<li>ភាគី(ក) សន្យាសាងសង់សំណង់អោយរួចរាល់ក្នុងអំឡុងពេលចន្លោះពី ១៨ខែទៅ ២៤ខែ សម្រាប់គម្រោងទី១  និងចន្លោះពី ១៨ខែទៅ ៣០ខែ សម្រាប់គម្រោងទី២ ដូចដែលបានបញ្ជាក់លើឧបសម្ព័ន្ធ២ ដោយបានភ្ជាប់រួចជាស្រេចនូវបណ្តាញអគ្គិសនី ទឹកស្អាត       លូបង្ហូរ ផ្លូវបេតុងក្នុងគម្រោង។  លើកលែងតែអ្នកទិញមិនបានបង់ប្រាក់តាមការកំណត់ ឬករណីប្រធានសក្តិ ដូចជាទឹកជំនន់ រញ្ជួយដី វិបត្តិនយោបាយ    អស្ថេរភាពសង្គមកើតឡើងដែលអាចបណ្តាលអោយរាំងស្ទះដល់ដំណើរការសាងសង់។</li>
														    	<li>ភាគី(ក) នឹងប្រគល់ប្លង់បំបែកក្បាលដី (មិនទាន់ផ្ទេរសិទ្ធិ) ជូនភាគី(ខ) នៅពេលដែលភាគី(ខ) បានទូទាត់ប្រាក់ជូនភាគី(ក) គ្រប់ចំនួន។</li>
														    	<li>ភាគី(ក) ធានាគុណភាព បច្ចេកទេសសំណង់ ការជួសជុលការប្រេះស្រាំ និងការលេចទឹករយៈពេល ១ឆ្នាំគិតចាប់ពីថ្ងៃប្រគល់ផ្ទះ។</li>
														    	<li>ប្រសិនបើភាគី(ក) មានការយឺតយ៉ាវក្នុងការប្រគល់ផ្ទះជូនភាគី(ខ) នោះ ភាគី(ក) នឹងមានសំណងជូនភាគី(ខ) ចំនួនការប្រាក់ ១%ក្នុងមួយខែនៃទឹកប្រាក់ដែលភាគី(ខ) បានបង់រួច។</li>
														    </ul>
													   </td>  
												  </tr>
											</table>
					             		</span>
					             		<span style="width: 100%; display: block; line-height: 32px;">
					             			<div class="padding-buttom">
					             				<span style="font-family:'Khmer OS Muol Light';">ប្រការ៤៖	<span id="padding-left-2">កាតព្វកិច្ច និងការទទួលខុសត្រូវរបស់ភាគី(ខ)</span></span>
					             			</div>	             			
											 <table width="100%" border="0"> 
												  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;"></td>
												    <td align="justify" style="padding-left:5px">
													    <ul class="blogsub">
															<li>ភាគី(ខ) មានកាតព្វកិច្ចបង់សេវាចំនួន $១៥០ (មួយរយហាសិបដុល្លារអាមេរិកគត់) ក្នុង១ឆ្នាំ លើផ្នែកសេវាដែលមានដូចជាភ្លើងបំភ្លឺផ្លូវ អនាម័យសាធារណៈ និងសន្តិសុខ ២៤ម៉ោង។ ភាគី(ក) មានសិទ្ធិកែប្រែតម្លៃខាងលើ ប្រសិនបើមានការកែប្រែ ភាគី(ក) នឹងជូនដំណឹងជាសាធារណៈរយៈពេលមួយខែមុន។</li>
													    	<li>ភាគី(ខ) មានកាតព្វកិច្ចទៅលើ ការចំណាយកាត់ឈ្មោះបង់ពន្ធប្រថាប់ត្រា៤% បង់ពន្ធអចលនទ្រព្យបន្ទាប់ពីរ     ភាគី(ក) ប្រគល់ផ្ទះជូន។</li>
													    	<li>ភាគី(ខ) យល់ព្រមបង្វិលការបង់ប្រាក់រំលស់ប្រចាំខែជាមួយភាគី(ក) អោយទៅជាឥណទានផ្ទះជាមួយគ្រឹះស្ថានហិរញ្ញវត្ថុដែលណែនាំដោយភាគី(ក) ឬរកបានដោយខ្លួនឯងក្នុងអត្រាការប្រាក់ដដែល ឬទាបជាង នៅពេលដែលសំណង់ផ្ទះរួចរាល់ ៧០% និងទទួលខុសត្រូវរាល់ចំណាយផ្សេងៗលើការស្នើសុំឥណទាន។</li>
													    </ul>
												    </td>
												  </tr>	
											</table>
					             		</span>
				             			<span style="width: 100%; display: block; line-height: 32px;">
				             				<span style="font-family:'Khmer OS Muol Light';">ប្រការ៥៖<span id="padding-left-2">លក្ខខណ្ឌរួម</span></span>
						             		<table width="100%" >
						             			<tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;"></td>
												    <td align="justify" style="padding-left:5px">
												    	<ul class="blogsub">
															<li>ភាគី(ខ) មិនអាចសង់របងនៅមុខផ្ទះបានឡើយ។</li>
															<li>ការកែប្រែផ្ទះដូចជា ការវាយទំលុះផ្ទះឬរបង ការសាងសង់សំណង់បន្ថែម ត្រូវធ្វើការដាក់ពាក្យស្នើសុំ និងមានការឯកភាព យល់ព្រមពីភាគី(ក) ជាមុនសិន ទើបភាគី(ខ) អាចធ្វើការកែប្រែ និងសាងសង់បាន ដើម្បីអោយត្រូវ នឹង      ស្តង់ដារ និងរក្សាសោភ័ណ្ឌភាពក្នុងគម្រោងផ្ទះល្វែង។ បើសិនជាភាគី(ខ) មិនគោរពតាមគោលការណ៍ណែនាំរបស់ភាគី(ក) នោះភាគី(ខ) ត្រូវរុះរើចេញសំណង់ដែលគ្មានការអនុញ្ញាត ។</li>
															<li>អំឡុងពេលសាងសង់ ភាគី(ខ) អាចលក់ឬផ្ទេរសិទ្ធិកិច្ចសន្យាបាន ដោយតម្រូវអោយស្នើរសុំជាទម្រង់លិខិត        រដ្ឋបាល និងត្រូវបង់សេវា $១៥០(មួយរយហាសិបដុល្លារអាមេរិកគត់) ជូនភាគី(ក) ។ ភាគីទីបីដែលទទួលយកការផ្ទេរសិទ្ធិពីភាគី(ខ) ត្រូវគោរពតាមខ្លឹមសារទាំងស្រុងនៃកិច្ចសន្យានេះ។</li>
														</ul>
												   </td>  
											</table>
										</span>
					             		<span style=";text-align:justify;line-height:25px;">
						             		កិច្ចព្រមព្រៀងនេះត្រូវធ្វើឡើងដោយគ្មានការគំរាមកំហែង បង្ខិតបង្ខំ ឬមានបញ្ហាខុសច្បាប់ណាមួយឡើយ ជាការធានាដល់សុក្រិតភាពនៃកិច្ចសន្យានេះភាគីទាំងពីរបានព្រមព្រៀងគ្នាផ្ដិតមេដៃស្ដាំដើម្បីជាភស្ដុតាងក្នុងការទទួលខុសត្រូវចំពោះមុខ ច្បាប់ ។ កិច្ចសន្យានេះធ្វើឡើង ជាភាសាខ្មែរ ០២ច្បាប់ ដែលមានតម្លៃស្មើរគ្នា ០១ច្បាប់សម្រាប់ភាគី(ក) និង ០១ច្បាប់ សម្រាប់ភាគី (ខ)។
						             	</span>
			             	</td>
			             </tr>
			             <tr>
			             	<td colspan="3">
			             		<br />
			             		<table align="center" width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';">
									   <tr style="font-size: 16px;">
									        <td class="reff" style="width:23%;text-align:center; font-family:'Khmer OS Muol Light';font-weight:200;white-space: nowrap;">ស្នាមមេដៃស្ដាំភាគី(ក)</td>
									        <td >&nbsp;</td>
									        <td class="reff" style="width:23%;white-space:nowrap;width:20%;text-align:center;  font-family:'Khmer OS Muol Light';font-weight:200;">ស្នាមមេដៃស្ដាំ(សាក្សី)</td>
									        <td >&nbsp;</td>
									        <td  class="reff" style="width:23%; text-align:center; font-family:'Khmer OS Muol Light';font-weight:200;white-space: nowrap;">ស្នាមមេដៃស្ដាំភាគី (ខ)</td>
									   </tr>
									   <tr height="100px">
							             	<td>&nbsp;</td>
							           </tr>
							           <tr style="font-size: 16px;">
						             		<td  style="text-align:center;font-family:'Khmer OS Muol Light';">&nbsp;<span><?php echo $this->agreement['project_manager_namekh'];?></span></td>
									        <td >&nbsp;</td>
								          	<td >&nbsp;</td>
									        <td >&nbsp;</td>
									        <td class="reff" align="center" style="white-space:nowrap;font-family:'Khmer OS Muol Light';">&nbsp;<span><?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?" ".$this->agreement['hname_kh']:"";?></span></td>
									 </tr>
								</table>
			             	</td>
			             </tr>
			        	</table>
		        	 	<div id="printfooter" style="font-size: 10px;margin-top:2px;font-family:'khmer os battambang';width:100%;">
			        		<span>ម្ចាស់គម្រោងមានសិទិ្ធកែប្រែប្លង់ដោយមិនបាច់ជូនដំណឹងទៅអតិថិជន</span>
			        	</div> 
			        </div>
			    </td>	
			</tr>
		</table>
	</div>
<script>
function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
}
</script>