<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$frmPayme = $this->frm_searchloantype;
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
	<script>
		dojo.require("dijit.form.DateTextBox");
	</script>
	<style>
		.hover:hover{background: #ccc;}
	</style>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPAIR_HOUSE_PAYMENT");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPAIR_HOUSE_PAYMENT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('branch_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('land_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('client_name');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('payment_method');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('user_id');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('start_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frmPayme->getElement('type');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<input id="category_id" />
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
			</div>
		</div>
	 </form> 
<div style="min-height:22cm; margin:0 auto;">
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
		<tr>
	    	<td align="center">
				<div id="divPrint">
					<style>
						.style{
							line-height: 20px;font-size: 12px !important;
							font-family: 'Times New Roman','Khmer OS Battambang';
							}
							th{padding: 5px;}
							
							table.content-data { page-break-inside:auto }
							table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
							#header {
							  display: table-header-group;
							  page-break-inside:avoid; page-break-after:auto;
							}
							.hide{visibility: hidden;}
								@media print {
								  div.divFooter {
									position: fixed;
									top: 0;
									width: 100%;
									height: 100px;
									bottom:0px;
									margin:0;
								 }
							.hide{visibility: visible; height: 110px;}
							}
							table.content-data{
								border-collapse:collapse;
								border:1px solid #000; 
								font-size:13px;
								font-family: 'Times New Roman','Khmer OS Battambang';
								white-space: nowrap;
								line-height: 22px;
							}
							table.content-data tr.style,
							table.content-data thead tr.style {
							   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
								background: #c1d0f3;
							}
							table.tb-footer{
								border-collapse:collapse;
								border:1px solid #000; 
								font-family: 'Times New Roman','Khmer OS Battambang';
								font-size:11px;
							}
							table.tb-footer tr{
							 line-height: 14px;  padding:2px 0px; height: 25px;
							}
						</style>
			        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
							<tr>
								<td colspan="3" style="border:1px solid #fff;">
									<div class="divFooter">
										<table  width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;" >
											<tr>
												<td width="20%"><img src="<?php echo $logo;?>" height="85px"></td>
												<td width="60%" valign="top">
													<h2 style="text-align:center; font-weight:200; font-size:18px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $branch_title;//$tr->translate("BRAND_TITLE");?></h2>
													<h2 style="text-align:center; font-weight:200; font-size:16px; font-family:'Times New Roman','Khmer OS Muol Light'">
														<?php echo $tr->translate("REPAIR_HOUSE_PAYMENT");?>
													</h2>
													<p style="text-align:center; font-weight:200; font-size:13px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php if (!empty($this->search['start_date'])){ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("d-M-Y",strtotime($this->search['end_date']));}?></p>
												</td>
												<td width="20%"></td>
											</tr>
									   </table>
								   </div>
							   </td>
							 </tr>
							<tr>
								<?php 
									$houserepair = 0;
								?>
								<td colspan="3" id="exportExcel">
								</td>
							</tr>
							<tr>
								<td colspan="3">
									<table class="content-data" id="exportExcel" border="1" width="100%" style="border-collapse:collapse; line-height: 20px; font-size: 12px; border:solid 1px #000;" >  
										<thead>
										<tr class="hide" style="border:1px solid #fff;">
											 <td colspan="11" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
										</tr>
										 <tr class="style" align="center" >
											<td scope="col"><?php echo $tr->translate("NUM");?></td>
											<td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td>
											<td scope="col"><?php echo $tr->translate("INCOME_TITLE");?></td>
											<td scope="col"><?php echo $tr->translate("CLIENT_NAME");?></td>
											<td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
											<td scope="col"><?php echo $tr->translate("RECEIPT");?></td>
											<td scope="col"><?php echo $tr->translate("CATEGORY");?></td>
											<td scope="col"><?php echo $tr->translate("TOTAL_INCOME");?></td>
											<td scope="col"><?php echo $tr->translate("PAYMENT_TYPE");?></td>
											<td scope="col"><?php echo $tr->translate("NOTE");?></td>
											<td scope="col"><?php echo $tr->translate("DATE");?></td>
											<td scope="col"><?php echo $tr->translate("BY_USER");?></td>
										</tr>
										</thead>
										<?php if (!empty($this->houserepair)){?>
										<tr  style="border:1px solid #000;">
												<td colspan="12" align="center">
													<span style="font-weight:normal;font-size:12px; font-family:'Times New Roman','Khmer OS Muol Light'">
														<?php echo $tr->translate("REPAIR_HOUSE_INCOME");?>
													 </span>
												</td>
											 </tr>
										<?php foreach ($this->houserepair as $index => $rs){?>
										<tr class=" stylehover" style="font-family: 'Times New Roman','Khmer OS Battambang';white-space: nowrap;<?php if($rs['status']==0){echo'background:#f7c6c6';}?>" width="100%">
											<td data-label="<?php echo $tr->translate("NUM");?>" style="text-align: center;">&nbsp;<?php echo ++$index; ?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>" align="center">&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("INCOME_TITLE");?>" align="center">&nbsp;<?php echo $rs["title_income"];?>&nbsp;</td> 
											<td data-label="<?php echo $tr->translate("CLIENT_NAME");?>" align="center">&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td> 
											<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="center">&nbsp;<?php echo $rs["land_address"]." (".$rs["street"].")";?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("RECEIPT");?>" align="center">&nbsp;<?php echo $rs["invoice"];?> <?php if($rs['status']==0){echo ' ('.$tr->translate("VOID").')';}?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("CATEGORY");?>" valign="top">&nbsp;<?php echo $rs["category"];?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("TOTAL_INCOME");?>" align="center">&nbsp;<strong><?php echo number_format($rs["total_amount"],2);?></strong>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>">&nbsp;<?php echo $rs["payment_method"];?>&nbsp;<?php if(!empty($rs["bank"])){ echo "(". $rs["bank" ].")";}else{echo  "";} ?></td>
											<td data-label="<?php echo $tr->translate("NOTE");?>">&nbsp;<?php echo $rs["description"];?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("DATE");?>" align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date"]));?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("BY_USER");?>" align="center">&nbsp;<?php echo $rs["user_name"];?>&nbsp;</td>
										</tr>
										<?php 
											if($rs['status']==1){
												$houserepair = $houserepair+$rs["total_amount"];
											}?>
										<?php }?>
										<tr  style="border:1px solid #000;">
											<td colspan="12" align="right">
											<span style="font-weight:normal;font-size:12px; font-family:'Times New Roman','Khmer OS Muol Light'">
												<?php echo $tr->translate("TOTAL_INCOME");?>
											 </span>
											<strong>$ <?php echo number_format($houserepair,2);?></strong></td>
										 </tr>
										<?php }?>
										<?php $houserepairExpense=0; if (!empty($this->houserepairExpense)){?>
										<tr  style="border:1px solid #000;">
												<td colspan="12" align="center">
													<span style="font-weight:normal;font-size:12px; font-family:'Times New Roman','Khmer OS Muol Light'">
														<?php echo $tr->translate("REPAIR_HOUSE_EXPENSE");?>
													 </span>
												</td>
											 </tr>
										<?php foreach ($this->houserepairExpense as $index => $rs){?>
										<tr class=" stylehover" style="font-family: 'Times New Roman','Khmer OS Battambang';white-space: nowrap;<?php if($rs['status']==0){echo'background:#f7c6c6';}?>" width="100%">
											<td data-label="<?php echo $tr->translate("NUM");?>" style="text-align: center;">&nbsp;<?php echo ++$index; ?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>" align="center">&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("INCOME_TITLE");?>" align="center">&nbsp;<?php echo $rs["title_income"];?>&nbsp;</td> 
											<td data-label="<?php echo $tr->translate("CLIENT_NAME");?>" align="center">&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td> 
											<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="center">&nbsp;<?php echo $rs["land_address"]." (".$rs["street"].")";?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("RECEIPT");?>" align="center">&nbsp;<?php echo $rs["invoice"];?> <?php if($rs['status']==0){echo ' ('.$tr->translate("VOID").')';}?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("CATEGORY");?>" valign="top">&nbsp;<?php echo $rs["category"];?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("TOTAL_INCOME");?>" align="center">&nbsp;<strong><?php echo number_format(abs($rs["total_amount"]),2);?></strong>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>">&nbsp;<?php echo $rs["payment_method"];?>&nbsp;<?php if(!empty($rs["bank"])){ echo "(". $rs["bank" ].")";}else{echo  "";} ?></td>
											<td data-label="<?php echo $tr->translate("NOTE");?>">&nbsp;<?php echo $rs["description"];?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("DATE");?>" align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date"]));?>&nbsp;</td>
											<td data-label="<?php echo $tr->translate("BY_USER");?>" align="center">&nbsp;<?php echo $rs["user_name"];?>&nbsp;</td>
										</tr>
										<?php 
											if($rs['status']==1){
												$houserepairExpense = $houserepairExpense+abs($rs["total_amount"]);
											}?>
										<?php }?>
										<tr  style="border:1px solid #000;">
											<td colspan="12" align="right">
											<span style="font-weight:normal;font-size:12px; font-family:'Times New Roman','Khmer OS Muol Light'">
												<?php echo $tr->translate("TOTAL_EXPENSE");?>
											 </span>
											<strong>$ <?php echo number_format($houserepairExpense,2);?></strong></td>
										 </tr>
										<?php }?>
									</table>
								</td>
							</tr>
							<tr>
								<td colspan="3">
								<?php $total = $houserepair - $houserepairExpense;?>
									<table align="right">
									  <tr style="font-size:10px; color:#000; height: 18px;"​ align="center">
										<td style="width:146px; font-family:'Times New Roman','Khmer OS Muol Light'; font-size: 16px;">&nbsp;<?php echo $tr->translate('TOTAL');?>&nbsp;</td>
										<td style="background: rgba(249, 225, 11, 0.7); color:#000; width:112px; font-size: 14px;"><strong>$ <?php echo number_format($total,2);?></strong></td>
									  </tr>
									</table>
								</td>
							</tr>
					   </table>
					<br />
					<?php echo $this->footerReport;?>
	          </div>
	       </td>
	    </tr>
	</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
var income_category_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
require(["dojo/ready"], function(ready){
	new dijit.form.FilteringSelect({
		store: income_category_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "category_id",
		id: "category_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			land_id=-1;
	}
		}, "category_id");

	 ready(function(){
		 getCategoryByType();
		 var catetype = dijit.byId('type');
		 catetype.on('change', function(evt) {
			 getCategoryByType();
	    });
	});
	 
});

oldtype = '<?php echo $this->search['type']?>';
var url_getcatebytype = '<?php echo $this->url(array('module'=>'loan','controller'=>'incomeotherpayment','action'=>'get-categorybytype')); ?>';
function getCategoryByType(){
	cate_type = dijit.byId('type').get('value');
	dijit.byId('category_id').reset(); 
	if(cate_type=="" || cate_type ==-1){
		income_category_store  = getDataStorefromJSON('id','name', <?php print_r(array())?>);
	    dijit.byId('category_id').set('store',income_category_store);   
		return false;
	}
	dojo.xhrPost({
		url: url_getcatebytype,
		content:{
			'cate_type':cate_type
			},
		handleAs:"json",
		load: function(data) {
			income_category_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('category_id').set('store',income_category_store);
		    if(oldtype==cate_type){
		    	dijit.byId('category_id').set('value','<?php echo $this->search['category_id']?>');
		    }   
		},
		error: function(err) {
		}
	});
}

</script>