<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$day = array(
			"Mon" =>'ច័ន្ទ',
			"Tue" =>'អង្គារ',
			"Wed" =>'ពុធ',
			"Thu" =>'ព្រហស្បតិ៍',
			"Fri" =>'សុក្រ',
			"Sat" =>'សៅរ៍',
			"Sun" =>'អាទិត្យ',
			);
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	$dbparmeter = new Report_Model_DbTable_DbParamater();
	$key = new Application_Model_DbTable_DbKeycode();
	$dataterm = $key->getKeyCodeMiniInv(TRUE);
	$branch_title = $tr->translate("BRAND_TITLE");
	
	$arrgender = array(1=>"ប្រុស",2=>"ស្រី");
?>
<title><?php echo $tr->translate("AGREEMENT");?></title>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<style>
	#divPrint .reff{ font-size: 20px !important; line-height:34px !important;}
	#divPrint tr td h2,p,pre,#divPrint span,#divPrint td{ font-size: 20px !important; line-height:34px !important;}
	#divPrint #padding-left-p-2{
	 padding-left: 105px !important;	
	}
	#divPrint .padding-buttom{
		margin-top: -5px !important;
	}
	#divPrint #printfooter{display: none !important;}
ul li{line-height: 30px !important;}
</style> 
<div  id="exportword" style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint" >
	    	 	<style>		
						    #padding-left-p-2{
							 padding-left: 105px !important;	
							}
							.padding-buttom{
								margin-top: -5px !important;
							}
	    	 				.reff{ font-size: 16px !important; line-height:34px !important;}
							tr td h2,p,pre,span{ font-size: 15px ; line-height:30px;}
							#padding-left{
							padding-left: 18px;
							}
							#bold-padding-right{
								margin-right: 15px;
								font-family: khmer os battambang;
								font-size:19px;
							}
							
							#padding-left-2{
							/*margin-top: -10px;*/
							padding-left:15px;
							}
							.padding-buttom{
								margin-top: -5px;
							}
							#padding-left-p-2{
							 margin-top:-1px; 
							 padding-left: 85px;	
							}
							#padding-left-p{
						    padding-left: 105px;
							}
							th{padding: 5px;}
							span.value{ line-height:12px;display: inline-block; text-align: center;}
							span.child {display:block; margin-left:25px; line-height: 25px;}
							span{line-height: 26px;}
							
							.value_label{
						        border-bottom: dashed 1px #000;
							    line-height: 12px !important;
							    min-width: 100%;
							    display: inline-block;
							}
							body {
							    position: relative;
							}
							#printfooter {
							    position: absolute;
							    bottom: 0;
							    position: fixed;
							    display: block ;
							}
							span.margin-left{
								margin-left:85px; display: inline-block;
							}
							.color-name{
								color: #2d348f;
							}
							.page-break{
								page-break-before: always;
							}
	   			 </style>
	    	 	<div class="page-break">
			        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang'; padding:0;margin:0;border:0px;" >
			        		<tr>
				                <td width="40%" valign="top" style="padding-top: 30px;">
				                	<?php $imagelogo = $this->baseUrl()."/images/logo.jpg";
				                	if (!empty($this->agreement['project_logo'])){
				                		$imagelogo = $this->baseUrl()."/images/projects/".$this->agreement['project_logo'];
				                	}
				                	?>
				                	<img src="<?php echo $imagelogo;?>" style="max-width:100%;width: 210px;">
				                </td>
				                <td width="30%" align="center" >&nbsp;</td>
				               	<td width="40%" align="center" style="color:#000;" valign="top">
					                <span class="color-name" style="text-align:center; line-height:28px; font-size:16px;font-family:'Times New Roman','Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា</span>
					                <span class="color-name" style="text-align:center; line-height:28px; width: 100%; display: block; font-size:15px; font-family:'Khmer OS Muol Light';white-space: nowrap;"><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
					                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:15px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.jpg" height="25px"></span>
				               </td>
				             </tr>
			        		<tr>
			                <td colspan="3" align="center">
				                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'; text-decoration: underline;"><?php echo $tr->translate("កិច្ចសន្យាទិញ / លក់ដីឡូតិ៍");?></span>
			                </td>
			             </tr> 
			             <tr>
			             	<td colspan="3">
			             		<p style="font-family:'Times New Roman','Khmer OS Battambang'; text-align:justify; line-height:24px; font-size:14px; font-weight: normal !important;">
			             				<?php 
			             				$sex="ប្រុស";
			             				$w_sex="ប្រុស";
			             				$title="លោក";
			             				if($this->agreement['p_sex']==2){
			             					$sex="ស្រី";
			             					$title="លោកស្រី";
			             				}
			             				if($this->agreement['w_sex']==2){
			             					$w_sex="ស្រី";
			             				}
			             				$project_location=$this->agreement['project_location'];
			             				$address=$tr->translate("ADDRESS_COMPANY");
			             				?>
			             				<table border="0">
			             					<tr>
			             						<td width="10%" valign="top">
			             							<span style=" font-family:'Khmer OS Muol Light'; font-weight:200; text-decoration: underline;">រវាង:</span>
			             						</td>
			             						<td valign="top">
			             							<span style="width: 100%; display: block; line-height: 25px;">
														ឈ្មោះ <span class="color-name" style="font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['project_manager_namekh'];?></span> ភេទ <?php echo $sex;?> 
														អត្តសញ្ញាណប័ណ្ណលេខ <?php echo $dbparmeter->getNumberInkhmer($this->agreement['project_manager_nation_id']);?> 
														<?php if (!empty($this->agreement['w_manager_namekh'])){?>
														និងឈ្មោះ <span class="color-name" style="font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['w_manager_namekh'];?></span> ភេទ <?php echo $w_sex;?> 
														អត្តសញ្ញាណប័ណ្ណលេខ <?php echo $dbparmeter->getNumberInkhmer($this->agreement['w_manager_nation_id']);?>
														<?php }?> 
														មានទីលំនៅ <?php echo $this->agreement['project_manager_p_current_address'];?> 
														ហៅកាត់ថា ភាគី (<span style="font-family:'Khmer OS Muol Light';font-weight:200;">ក</span>) ជាអ្នកលក់។
													</span>
			             						</td>
			             					</tr>
			             					<tr>
			             						<td width="10%" valign="top">
			             							<span style=" font-family:'Khmer OS Muol Light'; font-weight:200; text-decoration: underline;">និង:</span>
			             						</td>
			             						<td valign="top">
			             							<?php 
							             				$cussex="ប្រុស";
							             				if($this->agreement['sex']==2){
							             					$cussex="ស្រី";
							             				}
							             				$with_sex="ប្រុស";
							             				if($this->agreement['ksex']==2){
							             					$with_sex="ស្រី";
							             				}
							             				?>
								             			<span style="width: 100%; display: block; line-height: 25px;"> 
								             				ឈ្មោះ <span class="value " style="min-width:50px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['client_namekh'];?></span> ភេទ <?php echo $cussex;?> 
								             				ឆ្នាំកំណើត  <?php if (!empty($this->agreement['dob']) AND date("Y",strtotime($this->agreement['dob']))){ ?> <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['dob'])));}?>
								             				សញ្ជាតិ<span class="value" style="min-width:30px;"><?php echo $this->agreement['client_nationality'];?></span> 
								             				កាន់<?php echo $this->agreement['client_d_type'];?> លេខ<span class="value" style="min-width:50px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['client_nation_id']);?></span> 
								             				ចុះថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['client_issuedateid'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['client_issuedateid']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['client_issuedateid'])));?>
								             				
								             				<?php if(!empty($this->agreement['hname_kh'])){?> និង ឈ្មោះ  <span class="value" style="min-width:70px;font-family:'Khmer OS Muol Light';"><?php echo $this->agreement['hname_kh'];?></span> ភេទ <?php echo $with_sex;?> 
								             				ឆ្នាំកំណើត <?php if (!empty($this->agreement['dob_buywith'])){ echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['dob_buywith'])));}?>  
								             				សញ្ជាតិ<span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_nationality'];?></span> 
															 កាន់<?php echo $this->agreement['joint_doc_type'];?>លេខ <span class="value" style="min-width:60px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['rid_no']);?></span>
															 ចុះថ្ងៃទី <span class="value" style="min-width:80px;"><?php if (!empty($this->agreement['hname_kh'])){ echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['join_issuedateid']))); }?></span> ខែ <span class="value" style="min-width:80px;"><?php if (!empty($this->agreement['hname_kh'])){ echo $month[date("m",strtotime($this->agreement['join_issuedateid']))];}?></span> ឆ្នាំ <span class="value" style="min-width:80px;"><?php if (!empty($this->agreement['hname_kh'])){ echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['join_issuedateid'])));}?></span> 
															<?php }?> 
															លេខទំនាក់ទំនង <span class="value" style="min-width:90px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['client_phone']);?></span>
															មានទីលំនៅបច្ចុប្បន្ន 
															ផ្ទះលេខ : <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_house_no'];?></span> ផ្លូវ  <span class="value" style=""><?php echo $this->agreement['client_street'];?></span> 
															   ភូមិ <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_village_kh'];?></span>       
															      ឃុំ/សង្កាត់  <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_commune_kh'];?></span> 
															      ក្រុង/ស្រុក/ខណ្ឌ <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_districtkh'];?></span>
							             					      រាជធានី/ខេត្ត/ក្រុង <span class="value" style="min-width:50px;">&nbsp;<?php echo $this->agreement['client_province_kh'];?></span> 
															ជាអ្នកទិញ ហៅកាត់ថា ភាគី “<span style="font-family:'Khmer OS Muol Light';font-weight:200;">ខ</span>” ជាអ្នកទិញ។
														</span>   
			             						</td>
			             					</tr>
			             				</table>
										
				             			
										<?php
												$countland = 1;
				             				 if (!empty($this->agreement['old_land_id'])){
				             					$idse = explode(",", $this->agreement['old_land_id']);
				             					$countland = count($idse);
				             				}?>
				             			<span style="width: 100%; display: block; font-family:'Khmer OS Muol Light';font-weight:200;text-align: center; text-decoration: underline;">ភាគីទាំងពីរ ព្រមព្រៀងតាមលក្ខខណ្ឌដូចខាងក្រោម ៖</span>
				             			<span style="width: 100%; display: block; line-height: 25px; text-align: center;">
				             				<?php 
									    	$dbland = new Project_Model_DbTable_DbLand();
									    	$amtProperty = 1;
									    	if (!empty($this->agreement['old_land_id'])){
									    		$idse = explode(",", $this->agreement['old_land_id']);
									    		$amtProperty = count($idse);
									    	}
									    		?>
				             				ភាគី “ក” បានយល់ព្រមលក់ ហើយភាគី “ខ”  យល់ព្រមទិញ <span class="value" style="text-align:center; min-width:20px;"><?php echo $this->agreement['property_type_en']?></span> ចំនួន : <span class="value" style="text-align:center; min-width:20px;"><?php echo $dbparmeter->getNumberInkhmer($amtProperty);?></span> ឡូតិ៍ ដែលមានលេខសំគាល់ : <span class="value" style="text-align:center; min-width:70px;font-weight: bold;"><?php echo $this->agreement['property_title'];?></span> 
				             			</span>
				             			<span style="width: 100%; display: block; line-height: 25px;">
				             				<span style="display: block; width: 100%;" class="padding-buttom">
					             				<span style="font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ១៖ </span> <span id="padding-left-2">តំលៃទិញ/លក់ ៖</span>
					             			</span>
					             			<table width="100%" border="0"> 
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">១.១.</td>
												    <td align="justify" style="padding-left:5px">តម្លៃព្រមព្រៀងទិញ/លក់សរុបៈ USD<span style="font-weight: bold;"> <?php echo number_format($this->agreement['price_sold'],2);?> (<span id="lable_pricekhmer" style="font-family:'Khmer os battambang';"></span>ដុល្លារអាមេរិក)</span> ។</td>  
											  </tr>
											   <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;">១.២.</td>
												    <td align="justify" style="padding-left:5px">ភាគី “ខ” បានយល់ព្រមបង់ប្រាក់តាមគោលការណ៍ តារាងបង់ប្រាក់ក្នុងឧបសម្ព័ន្ធទីមួយ។</td>  
											  </tr>
											</table>
											<script>
												a_sold ='<?php echo ($this->agreement['price_sold']) ?>';
												money_khmersold=read_money_in_khmer(a_sold);
												
												decimalmoney_khmersold='<?php echo substr(number_format($this->agreement['price_sold'],2),-2);?>';
												str_centsold = 'សេន';
												if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
												last_number_sold='<?php echo substr(number_format($this->agreement['price_sold'],2),-2);?>';
												
												if(last_number_sold<=0){last_number_sold='';}
												money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
												dojo.byId('lable_pricekhmer').innerHTML=money_khmersold+" ";
											</script>
				             				<span style="display: block; width: 100%;" class="padding-buttom">
					             				<span style="font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ២៖ </span> <span id="padding-left-2">ការផ្ទេរសិទ្ធិ:</span>
					             			</span>
					             			<table width="100%" border="0"> 
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">២.‌១.</td>
												    <td align="justify" style="padding-left:5px">ភាគី “ក” មានភារៈបំបែកក្បាលដីល្វែងជូនភាគី “ខ” ។</td>  
											  </tr>
											   <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;">២.២.</td>
												    <td align="justify" style="padding-left:5px">ភាគី “ក” មានភារៈមកផ្តិតមេដៃលើលិខិតផ្ទេរសិទ្ធិកាន់កាប់ផ្ទះល្វែងជូនភាគី “ខ” នៅពេលដែលភាគី“ខ” បានបង់ប្រាក់ថ្លៃទិញដីល្វែងគ្រប់ចំនួនជូនភាគី “ក” ។ </td>  
											  </tr>
											</table>
											<span style="display: block; width: 100%;" class="padding-buttom">
					             				<span style="font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ៣: </span> <span id="padding-left-2">អំពីលក្ខខណ្ឌរួម ៖</span>
					             			</span>
											<table width="100%" border="0">
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៣.១.</td>
												    <td align="justify" style="padding-left:5px">ភាគី “ខ” បានឃើញ និង ឯកភាពព្រមផ្តិតមេដៃលើកាលវិភាគបង់ប្រាក់រំលស់ប្រចាំខែដែលភាគី “ក” បានរៀបចំអោយ ។</td>  
											  </tr>
											   <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៣.២.</td>
												    <td align="justify" style="padding-left:5px">ភាគី “ខ” សន្យាមកបង់ប្រាក់រំលស់ប្រចាំខែ នៅការិយាល័យរបស់ភាគី “ក” អោយបានទៀងទាត់តាមកាលបរិច្ឆេទនៅក្នុងតារាងកាលវិភាគបង់ប្រាក់រំលស់ ។</td>  
											  </tr>
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៣.៣.</td>
												    <td align="justify" style="padding-left:5px">ក្នុងករណីភាគី “ខ” កែប្រែចិត្តថាមិនទិញវិញ នោះទឹកប្រាក់ដែលភាគី “ខ” បានបង់មុន និង បង់កន្លងមកត្រូវទុកជាប្រយោជន៍របស់ភាគី “ក” ហើយភាគី “ក” មានសិទ្ធគ្រប់គ្រាន់ក្នុងការរឹបអូសដីមកវិញ ដើម្បីដាក់លក់ឡៃឡុងតាមតំលៃទីផ្សារនៅពេលអនា គត ទៅអោយអ្នកដទៃវិញភ្លាមដោយភាគី “ខ” មិនមានសិទ្ធណាមួយក្នុងការតវ៉ា និងទាមទារអ្វីឡើយ ។ កិច្ចសន្យាត្រូវបញ្ចប់។</td>  
											  </tr>
											  
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៣.៤.</td>
												    <td align="justify" style="padding-left:5px">ក្នុងករណីភាគី “ខ” យឺតយ៉ាវមិនបានបង់ប្រាក់តាមកាលបរិច្ឆេទនៅក្នុងតារាងបង់ប្រាក់ហួសពី៥ថ្ងៃ ត្រូវរងការផាកពិន័យ ៣% លើប្រាក់បង់ប្រចាំខែ គុណនឹងចំនួនថ្ងៃដែលហួសបន្ទាប់ពី ៥ថ្ងៃ ។</td>  
											  </tr>
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៣.៥.</td>
												    <td align="justify" style="padding-left:5px">ក្នុងករណីភាគី “ខ” យឺតយ៉ាវមិនបានបង់ប្រាក់តាមកាលបរិច្ឆេទនៅក្នុងតារាងបង់ប្រាក់ហួសពី១៥ថ្ងៃ ត្រូវរងការផាកពិន័យ ៥% លើប្រាក់បង់ប្រចាំខែគុណនឹងចំនួនថ្ងៃដែលហួសបន្ទាប់ពី ១៥ថ្ងៃ ។</td>  
											  </tr>
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៣.៦.</td>
												    <td align="justify" style="padding-left:5px">ក្នុងករណីភាគី “ខ” ខកខាន ឬយឺតយាវមិនបានបង់ប្រាក់រំលស់ប្រចាំខែតាមកាលបរិច្ឆេទក្នុងកាលវិភាគបង់ប្រាក់រំលស់លើសពី ៣០ថ្ងៃឡើងទៅ (រាប់ទាំងថ្ងៃឈប់សំរាក និង បុណ្យជាតិ) នោះទឹកប្រាក់ដែលភាគី “ខ” បានកក់ កក់បន្ថែម និង បង់រំលស់ កន្លងមកត្រូវទុកជាប្រយោជន៍របស់ភាគី “ក” ហើយភាគី “ក” មានសិទ្ធគ្រប់គ្រាន់ក្នុងការរឹបអូសដីល្វែងមកវិញ ដើម្បីដាក់លក់ឡៃឡុងតាមតំលៃទីផ្សារនៅពេលអនាគត ទៅអោយអ្នកដទៃវិញភ្លាមដោយភាគី “ខ” មិនមានសិទ្ធណាមួយក្នុងការតវ៉ា និងទាមទារអ្វីឡើយ ។ កិច្ចសន្យាត្រូវបញ្ចប់។</td>  
											  </tr>
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៣.៧.</td>
												    <td align="justify" style="padding-left:5px">ក្នុងករណីភាគី “ក” កែប្រែចិត្តថាមិនលក់វិញ  ភាគី “ក” ត្រូវសងប្រាក់ដែលភាគី “ខ” បានកក់ បូករួមជាមួយប្រាក់ដែលបានបង់រំលស់កន្លងមក ទ្វេមួយជាពីរជូនភាគី “ខ” វិញ ដោយគ្មានលក្ខខណ្ឌ និងការតវ៉ា។ កិច្ចសន្យាត្រូវបញ្ចប់។</td>  
											  </tr>
											</table>
											
											<span style="display: block; width: 100%;" class="padding-buttom">
					             				<span style="font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ៤:  </span> <span id="padding-left-2">សុពលភាពកិច្ចសន្យា</span>
					             			</span>
					             			<table width="100%" border="0">
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៤.១.</td>
												    <td align="justify" style="padding-left:5px">ភាគី “ក” និង ភាគី “ខ” សន្យាគោរពយ៉ាងម៉ឺងម៉ាត់រាល់ប្រការនីមួយៗ ។ ក្នុងករណីមានភាគីណាមួយអនុវត្តន៍ផ្ទុយ ឬ រំលោភបំពានលើលក្ខខណ្ឌណាមួយនៃកិច្ចសន្យានេះ ភាគីនោះត្រូវទទួលខុសត្រូវចំពោះមុខច្បាប់ជាធរមាន។ រាល់ការចំណាយ ដែលទាក់ទងក្នុងការដោះស្រាយលើវិវាទ ជាបន្ទុករបស់ភាគីដែលរំលោភបំពានលើកិច្ចសន្យា ។</td>  
											  </tr>
											   <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៤.២.</td>
												    <td align="justify" style="padding-left:5px">កិច្ចសន្យានេះធ្វើជាភាសាខ្មែរ និងមានពីរ(០២)ទំព័រ និងធ្វើជាពីរ(០២)ច្បាប់ សម្រាប់តម្កល់នៅភាគី “ក” ចំនួនមួយ(០១)ច្បាប់ ភាគី “ខ” ចំនួនមួយ(០១)ច្បាប់។</td>  
											  </tr>
											  <tr>
												    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">៤.៣.</td>
												    <td align="justify" style="padding-left:5px">ភាគីទាំងសងខាងបានអានពិនិត្យ និងយល់ច្បាស់រាល់ខ្លឹមសារទាំងអស់ ដែលមានចែងនៅក្នុងកិច្ចសន្យា និងយល់ព្រមផ្តិតមេដៃដោយស្ម័គ្រចិត្តទុកជាភស្តុតាង។</td>  
											  </tr>
											</table>
											
					             		</span>
			             	</td>
			             </tr>
			             <tr>
			             	<td colspan="3">
			             		<table align="center" width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';">
			             				<tr>
									        <td  colspan="7" class="reff" style="text-align:right; font-family:'Khmer OS Battambang';font-weight:200;white-space:nowrap;">ធ្វើនៅ,ភ្នំពេញ ថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['agreement_date'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['agreement_date'])));?></td>
									   </tr>
									   <tr style="font-size: 14px;">
									   		<td class="reff" style="font-family:'Khmer OS Battambang';font-weight:200; width:20%;text-align:center; white-space: nowrap;"><span>ស្នាមមេដៃភាគី ក”អ្នកលក់</span></td>
									        <td>&nbsp;</td>
									        <td class="reff" style="font-family:'Khmer OS Battambang';font-weight:200; width:20%;text-align:center; white-space: nowrap;"><span>សាក្សីទី១</span></td>
									        <td>&nbsp;</td>
									         <td class="reff" style="font-family:'Khmer OS Battambang';font-weight:200; width:20%;text-align:center; white-space: nowrap;"><span>សាក្សីទី២</span></td>
									        <td>&nbsp;</td>
									         <td class="reff" style="white-space:nowrap; font-family:'Khmer OS Battambang';font-weight:200; width:20%; text-align:center; "><span >ស្នាមមេដៃភាគី “ខ”អ្នកទិញ </span></td>
									   </tr>
									   <tr height="70px">
							             	<td>&nbsp;</td>
							           </tr>
							           <tr style="font-size: 14px;">
							           	<td  style="text-align:center;"><span style="font-family:'Khmer OS Muol Light';font-weight:200; "><?php echo str_replace('លោក','',$this->agreement['project_manager_namekh']); //echo $dataterm['signatur_agree'];?></span></td>
									       <td>&nbsp;</td>
									       <td class="reff"  align="center" style="white-space:nowrap;"><span style="font-family:'Khmer OS Muol Light';font-weight:200; "><?php //echo $this->agreement['user_name'];?></span></td>
									       <td>&nbsp;</td>
									       <td class="reff"  align="center" style="white-space:nowrap;"><span style="font-family:'Khmer OS Muol Light';font-weight:200; "><?php //echo $this->agreement['staff_name'];?></span></td>
									       <td>&nbsp;</td>
									       <td class="reff"  align="center" style="white-space:nowrap;"><span style="font-family:'Khmer OS Muol Light';font-weight:200; "><?php echo $this->agreement['client_namekh']; echo (!empty($this->agreement['hname_kh']))?"/".$this->agreement['hname_kh']:""; ?></span></td>
									       
									 </tr>
								</table>
			             	</td>
			             </tr>
			        </table>
	    	 	</div>
	    	 	<?php if ($this->agreement['payment_id']==4){?>
	    	 	<div class="page-break">
	    	 		<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang'; padding:0;margin:0;border:0px;" >
			        		<tr>
				                <td width="40%" valign="top" style="padding-top: 30px;">
				                	<?php $imagelogo = $this->baseUrl()."/images/logo.jpg";
				                	if (!empty($this->agreement['project_logo'])){
				                		$imagelogo = $this->baseUrl()."/images/projects/".$this->agreement['project_logo'];
				                	}
				                	?>
				                	<img src="<?php echo $imagelogo;?>" style="max-width:100%;width: 210px;">
				                </td>
				                <td width="30%" align="center" >&nbsp;</td>
				               	<td width="40%" align="center" style="color:#000;" valign="top">
					                <span class="color-name" style="text-align:center; line-height:28px; font-size:16px;font-family:'Times New Roman','Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា</span>
					                <span class="color-name" style="text-align:center; line-height:28px; width: 100%; display: block; font-size:15px; font-family:'Khmer OS Muol Light';white-space: nowrap;"><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
					                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:15px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.jpg" height="25px"></span>
				               </td>
				             </tr>
			        		<tr>
			                <td colspan="3" align="center">
				                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'; "><?php echo $tr->translate("ល័ក្ខខ័ណ្ឌ");?></span>
				                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("សំរាប់អ្នកទិញ-លក់ បង់រំលស់");?></span>
			                </td>
			             </tr> 
			             <tr>
			             	<td colspan="3">
			             		<table width="100%" border="0"> 
								  <tr>
									    <td align="justify" style="vertical-align:top; text-align:right;width:9%;">១.</td>
									    <td align="justify" style="padding-left:5px">អ្នកទិញ បានឃើញ និង ឯកភាពព្រមផ្តិតមេដៃលើកាលវិភាគបង់ប្រាក់រំលស់ប្រចាំខែដែលក្រុមហ៊ុន បានរៀបចំអោយ ។</td>  
								  </tr>
								   <tr>
									    <td align="justify" style="vertical-align:top; text-align:right;">២.</td>
									    <td align="justify" style="padding-left:5px">អ្នកទិញសន្យាមកបង់ប្រាក់រំលស់ប្រចាំខែ នៅការិយាល័យក្រុមហ៊ុន អោយបានទៀងទាត់តាមកាលបរិច្ឆេទនៅក្នុងតារាង កាលវិភាគបង់ប្រាក់រំលស់ ។</td>  
								  </tr>
								  <tr>
									    <td align="justify" style="vertical-align:top; text-align:right;">៣.</td>
									    <td align="justify" style="padding-left:5px">ក្នុងករណីអ្នកទិញ កែប្រែចិត្តថាមិនទិញវិញ នោះទឹកប្រាក់ដែល កក់ រឺបានបង់មុន និង បង់កន្លងមកត្រូវទុកជាប្រយោជន៍របស់ក្រុមហ៊ុន  ។</td>  
								  </tr>
								  <tr>
									    <td align="justify" style="vertical-align:top; text-align:right;">៤.</td>
									    <td align="justify" style="padding-left:5px">ក្នុងករណី យឺតយ៉ាវមិនបានបង់ប្រាក់តាមកាលបរិច្ឆេទនៅក្នុងតារាងបង់ប្រាក់ហួសពី៥ថ្ងៃ ត្រូវរងការផាកពិន័យ ៣% លើប្រាក់បង់ប្រចាំខែ គុណនឹងចំនួនថ្ងៃដែលហួសបន្ទាប់ពី ៥ថ្ងៃ ។</td>  
								  </tr>
								  <tr>
									    <td align="justify" style="vertical-align:top; text-align:right;">៥.</td>
									    <td align="justify" style="padding-left:5px">ក្នុងករណីយឺតយ៉ាវមិនបានបង់ប្រាក់តាមកាលបរិច្ឆេទនៅក្នុងតារាងបង់ប្រាក់ហួសពី១៥ថ្ងៃ ត្រូវរងការផាកពិន័យ ៥% លើប្រាក់បង់ប្រចាំខែគុណនឹងចំនួនថ្ងៃដែលហួសបន្ទាប់ពី ១៥ថ្ងៃ ។</td>  
								  </tr>
								  <tr>
									    <td align="justify" style="vertical-align:top; text-align:right;">៦.</td>
									    <td align="justify" style="padding-left:5px">ក្នុងករណី ខកខាន ឬយឺតយាវមិនបានបង់ប្រាក់រំលស់ប្រចាំខែតាមកាលបរិច្ឆេទក្នុងកាលវិភាគបង់ប្រាក់រំលស់លើសពី ៣០ថ្ងៃឡើងទៅ (រាប់ទាំងថ្ងៃឈប់សំរាក និង បុណ្យជាតិ) នោះទឹកប្រាក់ដែលអ្នកទិញ បានកក់ កក់បន្ថែម និង បង់រំលស់ កន្លងមកត្រូវទុកជាប្រយោជន៍របស់ក្រុមហ៊ុន ហើយ ក្រុមហ៊ុន មានសិទ្ធគ្រប់គ្រាន់ក្នុងការរឹបអូសដីល្វែងមកវិញ ដើម្បីដាក់លក់ឡៃឡុងតាមតំលៃទីផ្សារនៅពេលអនាគត ទៅអោយអ្នកដទៃវិញភ្លាមដោយភាគី អ្នកទិញ មិនមានសិទ្ធណាមួយក្នុងការតវ៉ា និងទាមទារអ្វីឡើយ ។ កិច្ចសន្យាត្រូវបញ្ចប់។</td>  
								  </tr>
								</table>
			             	</td>
			             </tr>
			             <tr>
			             	<td colspan="3">
			             		<table align="center" width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';">
			             				<tr>
			             					<td width="50%">&nbsp;</td>
									        <td  class="reff" style="text-align:right; font-family:'Khmer OS Battambang';font-weight:200;white-space:nowrap;">
									        	ធ្វើនៅ,ភ្នំពេញ ថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['agreement_date'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['agreement_date'])));?>
									        </td>
									        <td width="30%">&nbsp;</td>
									   </tr>
									   <tr>
			             					<td width="50%">&nbsp;</td>
									        <td  class="reff" align="center">
									        	ស្នាមមេដៃភាគី  <strong>អ្នកទិញ</strong>
									        </td>
									        <td width="30%">&nbsp;</td>
									   </tr>
									   <tr>
									   		<td colspan="3" height="70px">&nbsp;</td>
									   </tr>
									   <tr>
			             					<td width="50%">&nbsp;</td>
									        <td  class="reff" align="center">
									        	<?php echo $this->agreement['client_namekh']; echo (!empty($this->agreement['hname_kh']))?"/".$this->agreement['hname_kh']:""; ?>
									        </td>
									        <td width="30%">&nbsp;</td>
									   </tr>
								</table>
							</td>
						</tr>
			          </table>
	    	 	</div>
	    	 	<?php }?>
	    	<div>
	    	
	        	<div id="printfooter" style="display: none">
	        		<table width="100%" style="background: #fff;border-top: 2px solid #000;font-family: 'Khmer OS Battambang'; font-size:10px;line-height: 15px;white-space:nowrap;"> 
						<tbody>
							<tr style="white-space:nowrap;line-height: 12px;">
								<td width="40%"><?php echo $this->keyValue['website'];?></td>
								<td width="40%" align="right"><?php echo $this->keyValue['email_client'];?></td>
							</tr>
							<tr style="white-space:nowrap;line-height: 15px;">
								<td><?php echo $this->keyValue['footer_branch'];?></td>
								<td width="40%" align="right"><?php echo $this->keyValue['tel-client'];?></td>
							</tr>
						</tbody>
					</table>
	        	</div>
	        	</div>
	        </div>
	    </td>	
	</tr>
	</table>
</div>