<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
	<script>
		dojo.require("dijit.form.DateTextBox");
	</script>
	<style>
		.hover:hover{background: #ccc;}
	</style>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_DAILY_CASH");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-daily-cash')); ?>" dojoType="dijit.form.Form" method="post">
		<table style="margin: 0 auto;width:100%;">
			<tr>  
		        <td><?php echo $frm->getElement("adv_search");?></td>
		        <td><?php echo $frm->getElement('branch_id');?></td>
		        <td><?php echo $frm->getElement('land_id');?></td>
		        <td><?php echo $frm->getElement('streetlist');?></td>
		   		<td><?php echo $frm->getElement('client_name');?></td>
		   	</tr>
		   	<tr>
		   		<td><?php echo $frm->getElement('user_id');?></td>
		   		<td><?php echo $frm->getElement('payment_method');?></td>
		   		<td><?php echo $frm->getElement('start_date');?></td>
		   		<td><?php echo $frm->getElement('end_date');?></td>
		   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		   </tr>
		</table>
	 </form> 
<div style="min-height:22cm; margin:0 auto;">
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint">
	    	 	<style>
						.style{
							line-height: 20px;font-size: 12px !important;
							font-family: 'Khmer OS Battambang';
							}
							th{padding: 5px;}
							table { page-break-inside:auto }
							tr{ page-break-inside:avoid; page-break-after:auto; }
							#header {
							  display: table-header-group;
							  page-break-inside:avoid; page-break-after:auto;
							}
							.hide{visibility: hidden;}
							@media print {
							  div.divFooter {
							    position: fixed;
							    top: 0;
							  	width: 100%;
							  	height: 100px;
							  	bottom:0px;
								margin:0;
							  }
							.hide{visibility: visible; height: 110px;}
							}
						</style>
			        	<table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
			        	<tr>
			        		<td colspan="3" style="border:1px solid #fff;">
				        		<div class="divFooter">
					        		<table  width="100%" style="font-family:'Khmer OS Battambang';margin:0; padding:0;border:none;" >
						                <td width="20%"><img src="<?php echo $logo;?>" height="85px"></td>
						                <td width="60%" valign="top">
							                <h2 style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><label><?php echo $branch_title;//$tr->translate("BRAND_TITLE");?></label></h2>
							                <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("REPORT_DAILY_CASH");?></label></h2>
							                <p style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php if (!empty($this->search['start_date'])){ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("d-M-Y",strtotime($this->search['end_date']));}?></p>
						                </td>
					                	<td width="20%"></td>
					               </table>
				               </div>
			               </td>
			             </tr>
			            
			            <tr>
			        <?php 
			            $category_id=0; $category_id_expense=0; 
			        ?>
	            	<td colspan="3" id="exportExcel">
	            			<table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
				                <thead>
				                	<tr class="hide" >
				                		<td colspan="14" style="border:1px solid #fff"></td>
				                	</tr>
				                	<tr  style="border:1px solid #000;">
						                <td colspan="14" style="border:1px solid #fff;border-bottom:1px solid #000;">
						                	<h2 style="text-align:left; font-size:14px; font-family:'Khmer MEF2'">
								             	<label><?php echo $tr->translate("COLLECT_MONEY_INCOME");?></label>
								             </h2>
						                </td>
						             </tr>
					                <tr bgcolor="#c1d0f3" class="style" align="center" style="padding:0px 2px;white-space: nowrap;font-weight: bold;">
					                    <td rowspan="2"><?php echo $tr->translate("NUM");?></td>
					                    <td rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></td>
					                    <!--<td rowspan="2"><?php //echo $tr->translate("CLIENT_NUM");?></td>     -->              
					                    <td rowspan="2"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
					                    <td rowspan="2"><?php echo $tr->translate("PROPERTY_CODE");?></td>
					                    <td rowspan="2"><?php echo $tr->translate("PAYMENT_TYPE");?></td>   
					                    <td colspan="4"><?php echo $tr->translate("PAID_PRINCIPAL");?></td>
					                    <td rowspan="2"><?php echo $tr->translate("INTEREST");?></td>
					                    <td rowspan="2"><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
					                    <td rowspan="2"><?php echo $tr->translate("TOTAL");?></td>    
					                    <td rowspan="2"><?php echo $tr->translate("INPUT_DATE");?></td>
					                    <td rowspan="2"><?php echo $tr->translate("RECIEPT_NO");?></td>
					                    <td rowspan="2"><?php echo $tr->translate("PAYMENT_OPTION");?></td>
					                    <th rowspan="2"><?php echo $tr->translate("BY_USER");?></th>
					                </tr>
					                <tr class="style" style="white-space: nowrap;text-align: center;font-weight: bold;">
					                	<td><?php echo $tr->translate("DEPOSIT");?></td>                   
					                    <td><?php echo $tr->translate("កក់បង្គ្រប់");?></td>     
					                    <td><?php echo $tr->translate("រំលស់ប្រចាំខែ");?></td>
					                    <td><?php echo $tr->translate("EXTRA_PAYMENT");?></td>
					                </tr>
				                </thead>
			                <?php 
			                     $amt_r1 = 0; $amn_r2 = 0; $amn_r3 = 0;$amt_r4 = 0;$amn_r5 = 0;
			                	 $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;
			                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;
			                	 $i=1;$oldloan_number='';
			                	 $total_d=0;$total_b=0;$total_r=0;
			                	 $total_cash = 0;$total_cheque = 0;$total_bank = 0;
			                	 
			                	 $depsit=0;
			                	 $install = 0;
			                	 $income_daily = 0;
			                	 
			                	 $total_other_income=0;
			                	 $total_expese=0;
			                	 $total_extra=0;
			                ?>
			                <?php $is_set =0; if(!empty($this->collectMoney)) foreach ($this->collectMoney as $index => $rs){ ?>
			               <?php 
								$amt_d1 = $amt_d1+$rs['total_principal_permonthpaid'];
								$amt_d2 = $amt_d2+$rs['total_interest_permonthpaid'];
								$total_extra = $total_extra+$rs['extra_payment'];
								$amt_d3 = $amt_d3+$rs['penalize_amountpaid'];
								$amt_d5 = $amt_d5+$rs['service_chargepaid'];
								$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5+$total_extra;
								
								if($rs['payment_methodid']==1){
									$total_cash = $total_cash + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
								}elseif($rs['payment_methodid']==2){
									$total_cheque = $total_cheque + + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
								}else{
									$total_bank = $total_bank + + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
								}
			               ?>
			                <tr class="hover style style1" style="font-family: 'Khmer OS Content'; white-space:nowrap; ">
			               		<td style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
			               		<td>&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
			               		<!-- <td>&nbsp;<?php //echo $rs["sale_number"];?>&nbsp;</td> -->
			               		<td>&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>                 		
			               		<td>&nbsp;<?php echo $rs["land_address"].",".$rs["street"];?>&nbsp;</td>
			               		<td>&nbsp;<?php echo $rs["payment_method"];?>&nbsp;</td>
			               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php if($rs['field3']==1){ echo number_format($rs['total_principal_permonthpaid'],2);$depsit = $depsit+$rs['total_principal_permonthpaid'];}else{ echo"-";}?>&nbsp;</td>
			               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php if($rs['field3']==0){ echo number_format($rs['total_principal_permonthpaid'],2);$install = $install+$rs['total_principal_permonthpaid'];}else{echo"-";}?>&nbsp;</td>
			               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php if($rs['field3']==3){ echo number_format($rs['total_principal_permonthpaid'],2);$income_daily = $income_daily+$rs['total_principal_permonthpaid'];}else{echo"-";}?>&nbsp;</td>        
			               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php if($rs['extra_payment']>0){ echo number_format($rs['extra_payment'],2);}else{echo"-";}?>&nbsp;</td>       		
			               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['total_interest_permonthpaid'],2);?>&nbsp;</td>
			               		<td align="center" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['penalize_amountpaid'],2);?>&nbsp;</td>
			               		<!-- <td align="center" style="font:bolder 11px Arial;">&nbsp;<?php //echo number_format($rs['service_chargepaid'],2);?>&nbsp;</td> -->
			               		<td style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['amount_payment'],2);?>&nbsp;</td>
			               		<td style="white-space:nowrap; ">&nbsp;<?php echo date("d-m-Y",strtotime($rs["date_pay"]));?>&nbsp;</td>
			               		<td>&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
			               		<td style="font-site:9px; <?php if($rs["payment_option"]==4){echo " background:#ccc";} ?>" align="center" >&nbsp;<?php echo $rs["paymentoption"];?>&nbsp;</td>
			               		<td >&nbsp;<?php echo $rs["user_name"];?>&nbsp;</td>
			                </tr>
			                <?php }?>
			                <tr style="font-weight: bold;text-align: center;font-size: 14px;">
			                	<td colspan="3" style="border: 1px solid #fff;border-top: 1px solid #000;border-right: 1px solid #000"></td>
			                	<td colspan="2" style="font-size:14px; font-family:'Khmer MEF2';" ><?php echo $tr->translate("TOTAL_AMOUNT");?></td>
			                	<td ><?php echo number_format($depsit,2);?></td>
			                	<td ><?php echo number_format($install,2);?></td>
			                	<td ><?php echo number_format($income_daily,2);?></td>
			                	<td ><?php echo number_format($total_extra,2);?></td>
			                	<td ><?php echo number_format($amt_d2,2);?></td>
			                	<td ><?php echo number_format($amt_d3+$amt_d5,2);?></td>
			                	<td ><?php echo number_format($total_d,2);?></td>
			                	<td colspan="3" style="border: 1px solid #fff;border-top: 1px solid #000;border-left: 1px solid #000"></td>
			                </tr>
			            </table>
	            	</td>
	            </tr>
	            <?php if(!empty($this->row)){?>
	            <tr>
	            	<td colspan="3">
	            		<table id="exportExcel" border="1" width="100%" style="border-collapse:collapse; line-height: 20px; font-size: 12px; border:solid 1px #000;" >  
					    	<thead>
					    	<tr class="hide" >
				                <td colspan="10" style="border:1px solid #fff"></td>
				            </tr>
		                	<tr  style="border:1px solid #000;">
				                <td colspan="10" style="border:1px solid #fff;border-bottom:1px solid #000;">
				                	<h2 style="text-align:left; font-size:14px; font-family:'Khmer MEF2'">
						             	<label><?php echo $tr->translate("OTHER_INCOME");?></label>
						             </h2>
				                </td>
				             </tr>
					    	<tr bgcolor="#c1d0f3" class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
								<th ><?php echo $tr->translate("NUM");?></th>
							    <th><?php echo $tr->translate("BRANCH_NAME");?></th>
							    <th><?php echo $tr->translate("INCOME_TITLE");?></th>
							    <th><?php echo $tr->translate("CLIENT_NAME");?></th>
							    <th><?php echo $tr->translate("PROPERTY_CODE");?></th>
							    <th><?php echo $tr->translate("RECEIPT_NO");?></th>
							    <th><?php echo $tr->translate("CATEGORY");?></th>
							    <th><?php echo $tr->translate("TOTAL_INCOME");?></th>
							    <th><?php echo $tr->translate("NOTE");?></th>
							    <th><?php echo $tr->translate("DATE");?></th>
							    <th><?php echo $tr->translate("BY_USER");?></th>
							</tr>
							</thead>
					       <?php $branch_id=''; $i=0;  foreach($this->row as $key =>$row){ $i++;?>
							<tr style="font-size: 12px; line-height:20px; white-space: nowrap;" align="left">
							   <td align="center">&nbsp;<?php echo $i; ?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo $row['title'];?>&nbsp;</td>
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['client_name'];?></td>
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['house_name'];?></td>
							   <td align="center">&nbsp;<?php echo $row['invoice'];?>&nbsp;</td>
							   <td>&nbsp;<?php echo $row['category_name'];?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo number_format($row['total_amount'],2);?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo $row['description'];?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo date("d-M-Y",strtotime($row['date']));?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo $row["user_name"];?>&nbsp;</td>
							</tr>
								<?php $total_other_income = $total_other_income +$row['total_amount'];?>
							<?php }?>
					    </table>
	            	</td>
	            </tr>
	            <?php }
	            if(!empty($this->rowExpense)){
	            ?>
	             <tr>
	            	<td colspan="3">
	            		<table id="exportExcel" border="1" width="100%" style="border-collapse:collapse; line-height: 20px; font-size: 12px; border:solid 1px #000;" >  
					    	<thead>
						       <tr class="hide" >
					                <td colspan="10" style="border:1px solid #fff"></td>
					           </tr>
					           <tr  >
					                <td colspan="10" style="border:1px solid #fff;border-bottom:1px solid #000;font-size:14px; font-family:'Khmer MEF2'">
					                <?php echo $tr->translate("OTHER_EXPENSE");?></td>
					           </tr>
						    	<tr bgcolor="#c1d0f3" class="style" align="center" style="border-top:1px solid #000;padding:0px 2px;white-space: nowrap;">
									<th ><?php echo $tr->translate("NUM");?></th>
								    <th><?php echo $tr->translate("BRANCH_NAME");?></th>
								    <th><?php echo $tr->translate("EXPENSE_TITLE");?></th>
								    <th><?php echo $tr->translate("RECEIPT_NO");?></th>
								    <th><?php echo $tr->translate("CATEGORY");?></th>
								    <th><?php echo $tr->translate("TOTAL_EXPENSE");?></th>
								    <th><?php echo $tr->translate("NOTE");?></th>
								    <th><?php echo $tr->translate("DATE");?></th>
								    <th ><?php echo $tr->translate("BY_USER");?></th>
								</tr>
							<thead>
					       <?php $branch_id=''; $i=0; 
					       foreach($this->rowExpense as $key =>$rows){ $i++;
					       ?>
							<tr style="font-size: 12px; line-height:20px; white-space: nowrap;" align="left">
							   <td align="center">&nbsp;<?php echo $i; ?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo $rows['branch_name'];?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo $rows['title'];?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo $rows['invoice'];?>&nbsp;</td>
							   <td>&nbsp;<?php echo $rows['category_name'];?></td>
							   <td align="center">&nbsp;<?php echo number_format($rows['total_amount'],2);?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo $rows['description'];?></td>
							   <td align="center">&nbsp;<?php echo date("d-M-Y",strtotime($rows['date']));?>&nbsp;</td>
							   <td align="center">&nbsp;<?php echo $rs["user_name"];?>&nbsp;</td>
							</tr>
								<?php $total_expese = $total_expese +$rows['total_amount'];?>
							<?php }?>
					    </table>
	            	</td>
	            </tr>
	            <?php }?>
	            	<?php $total = ($total_d + $total_other_income) - $total_expese ;?>
	            <tr>
	            	<td colspan="3">
	            		<br /><table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
		                 <tr>
		                 	<td class="hide" colspan="8" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
		                 </tr>
		                 <tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold;padding:0px 2px;white-space: nowrap;">
		                 	<td colspan="5">&nbsp;<?php echo $tr->translate("COLLECT_MONEY_INCOME");?>&nbsp;</td>
		                 	<td rowspan="2">&nbsp;<?php echo $tr->translate("OTHER_INCOME");?>&nbsp;</td>
		                 	<td rowspan="2">&nbsp;<?php echo $tr->translate("OTHER_EXPENSE");?>&nbsp;</td>
		                 	<td rowspan="2">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
		                 </tr>
		                 <tr bgcolor="#c1d0f3" class="style" align="center" style="padding:0px 2px;white-space: nowrap;font-weight:bold">
		                    <td><?php echo $tr->translate("PRINCIPAL");?></td>                    
		                    <td><?php echo $tr->translate("EXTRA_PAYMENT");?></td>
		                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
		                    <td><?php echo $tr->translate("TOTAL_PENILIZE_AMOUNT");?></td>
		                    <td><?php echo $tr->translate("TOTAL");?></td>
		                </tr>
		                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($total_extra,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
		                    <td>&nbsp;<?php echo number_format($total_other_income,2);?></td>
		                    <td>&nbsp;<?php echo number_format($total_expese,2);?></td>
		                    <td>&nbsp;<?php echo number_format($total,2);?></td>
		                </tr>
		              </table>
	            	</td>
	            </tr>
	           </table>
	          </div>
	       </td>
	    </tr>
	</table>
   <br />
   <table align="center" width="100%">
	   <tr style="font-size: 16px;">
	      <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
	      <th></th>
	      <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
	      <th></th>
	      <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
	   </tr>
	</table>
	</div>
</div>
