<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$day = array(
		"Mon" =>'ច័ន្ទ',
		"Tue" =>'អង្គារ',
		"Wed" =>'ពុធ',
		"Thu" =>'ព្រហស្បតិ៍',
		"Fri" =>'សុក្រ',
		"Sat" =>'សៅរ៍',
		"Sun" =>'អាទិត្យ',
		);
$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
$dbparmeter = new Report_Model_DbTable_DbParamater();

$branch_title = $tr->translate("BRAND_TITLE");
$address="ផ្ទះលេខ 1-3 ផ្លូវបេតុង ភូមិជ្រៃកោង សង្កាត់ចោមចៅ២ ខណ្ឌពោសែនជ័យ រាជាធានីភ្នំពេញ";
// $commercialIssueDate ="២៣ ខែ កក្កដា ឆ្នាំ ២០១៨";
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title><?php echo $tr->translate("AGREEMENT");?></title>
<style>
	.reff{ font-size: 20px !important; line-height:34px !important;}
	#divPrint tr td h2, #divPrint p,#divPrint pre,#divPrint span,#divPrint td span,#divPrint td{ font-size: 20px !important; line-height:34px !important;}
	#padding-left-p-2{
	 padding-left: 105px !important;	
	}
	.padding-buttom{
		margin-top: -5px !important;
	}
	#printfooter{display: none !important;}
</style>
<div  id="exportword" style=" width:28cm;min-height:22cm; margin:0 auto; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint" >
    	 	<style>		
					    #padding-left-p-2{
						 padding-left: 105px !important;	
						}
						.padding-buttom{
							margin-top: -5px !important;
						}
						#divPrint tr td h2,#divPrint p,#divPrint pre,#divPrint span,#divPrint td{ font-size: 13px ; line-height:25px;}
						#padding-left{
						padding-left: 18px;
						}
						#bold-padding-right{
							margin-right: 15px;
							font-family: khmer os battambang;
						}
						
						#padding-left-2{
						padding-left:15px;
						}
						.padding-buttom{
							margin-top: -5px;
						}
						#padding-left-p-2{
						 margin-top:-1px; 
						 padding-left: 85px;	
						}
						#padding-left-p{
					    padding-left: 105px;
						}
						th{padding: 5px;}
						span.value{ line-height:12px;display: inline-block; text-align: center;}
						span.child {display:block; margin-left:25px; line-height: 25px;}
						span{line-height: 26px;}
						div.pages-break{
							page-break-inside:always; page-break-after:always; 
						}
						body {
						    position: relative;
						}
	
	#printfooter {
	    position: absolute;
	    bottom: 0;
	    position: fixed;
	    display: block ;
	}
	span.border_bt.value{
	    border-bottom: dashed 1px #000;
	}
	.value_label{
	    border-bottom: dotted 1px #000;
	}
	ul.border-land {
	    margin: 0;
	    padding: 0;
	}
	ul.border-land li {
	    float: left;
	    width: 50%;
		list-style: none;
	}
    </style>
    	<div class="pages-break">
        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang'; padding:0; margin:0; border:0px;" >
        	<tr>
                <td width="30%" valign="top">
                <?php 
                	$imagelogo = $this->baseUrl()."/images/logo.jpg";
                	if (!empty($this->agreement['project_logo'])){
                		$imagelogo = $this->baseUrl()."/images/projects/".$this->agreement['project_logo'];
                	}
                ?>
                <img src="<?php echo $imagelogo;?>" style="max-width:100%;max-height:80px">
               </td>
                <td width="40%" align="center">
                <span style="text-align:center; line-height:28px; font-family:'Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា</span>
                <span style="text-align:center; line-height:28px; width: 100%; display: block;font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
                <span style="text-align:center; line-height:28px; width: 100%; display: block;  font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.jpg" height="25px"></span>
                <span style="margin-bottom:10px;text-align:center; line-height:28px; width: 100%; display: block; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("កិច្ចសន្យាលក់-ទិញដីឡូត៍");?></span>
                <td width="30%"></td>
             </tr>
             <tr>
             	<td colspan="3">
                	<span style=" line-height:28px; width: 100%; display: block; font-family:'Khmer OS Battambang'">កិច្ចសន្យាលក់-ទិញដីឡូតិ៍ ធ្វើឡើងនៅរាជធានីភ្នំពេញ, ថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['agreement_date'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['agreement_date'])));?></span>
             	</td>
             </tr> 
             <tr>
             	<td colspan="3" >
             		<table width="100%" border="0">
						<tr>
						    <td align="justify" style="vertical-align:top; text-align:left;width:10px;">
							- 
							</td>
							<td align="justify" style="padding-left:5px">
								<strong>អ្នកលក់ដីឡូតិ៍៖ </strong> <strong><?php echo $branch_title?></strong> មានអាសយដ្ឋាន <?php echo $address;?> ហៅថា <strong>ភាគី”ក”</strong> មានតំណាងចុះកិច្ចសន្យាដោយឈ្មោះ  <span class="value" style="min-width:135px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['project_manager_namekh']; if (!empty($this->agreement['w_manager_namekh'])){ echo " ឬ ".$this->agreement['w_manager_namekh'];}?></span> និង
							</td>
						</tr>
						<tr>
						    <td align="justify" style="vertical-align:top; text-align:left;width:10px;">
							- 
							</td>
							<td align="justify" style="padding-left:5px">
								<?php 
		             				$cussex="ប្រុស";
		             				if($this->agreement['sex']==2){
		             					$cussex="ស្រី";
		             				}
		             				$with_sex="ប្រុស";
		             				if($this->agreement['ksex']==2){
		             					$with_sex="ស្រី";
		             				}
		             			?>
								<strong>អ្នកទិញដីឡូតិ៍៖</strong> ឈ្មោះ <span class="value" style="min-width:50px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['client_namekh'];?></span> ភេទ <?php echo $cussex;?> 
								អាយុ <span class="value" style="min-width:30px;"><?php 
		             			if (!empty($this->agreement['dob'])){ 
		             				$from = new DateTime($this->agreement['dob']);
		             				$to   = new DateTime($this->agreement['buy_date']);
		             				echo $dbparmeter->getNumberInkhmer($from->diff($to)->y);
		             			}
		             			?>ឆ្នាំ </span> ជនជាតិ<span class="value" style="min-width:30px;"><?php echo $this->agreement['client_nationality'];?></span> កាន់<?php echo $this->agreement['client_d_type'];?>លេខ <span class="value" style="min-width:50px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['client_nation_id']);?></span> 
		             			មានទីលំនៅផ្ទះលេខ <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_house_no'];?></span> 
		             			ភូមិ <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_village_kh'];?></span> 
		             			 ឃុំ/សង្កាត់  <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_commune_kh'];?></span> 
								 ក្រុង/ស្រុក/ខណ្ឌ <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_districtkh'];?></span>
             					  រាជធានី/ខេត្ត/ក្រុង <span class="value" style="min-width:50px;">&nbsp;<?php echo $this->agreement['client_province_kh'];?></span> 
             					  <?php if(!empty($this->agreement['hname_kh'])){?>
             					  និងឈ្មោះ <span class="value" style="min-width:70px;font-family:'Khmer OS Muol Light';"><?php echo $this->agreement['hname_kh'];?></span> ភេទ <?php echo $with_sex;?> 
             					  អាយុ <span class="value" style="min-width:30px;"><?php 
		             			if (!empty($this->dob_buywith['dob'])){ 
		             				$from = new DateTime($this->agreement['dob_buywith']);
		             				$to   = new DateTime($this->agreement['buy_date']);
		             				echo $dbparmeter->getNumberInkhmer($from->diff($to)->y);
		             			}
		             			?>ឆ្នាំ </span> ជនជាតិ<span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_nationality'];?></span> កាន់<?php echo $this->agreement['joint_doc_type'];?>លេខ <span class="value" style="min-width:50px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['rid_no']);?></span> 
		             			មានទីលំនៅផ្ទះលេខ <span class="value" style="min-width:50px;"><?php echo $this->agreement['with_house'];?></span> 
		             			ភូមិ <span class="value" style="min-width:50px;"><?php echo $this->agreement['joint_village'];?></span> 
		             			 ឃុំ/សង្កាត់  <span class="value" style="min-width:50px;"><?php echo $this->agreement['join_commune'];?></span> 
								 ក្រុង/ស្រុក/ខណ្ឌ <span class="value" style="min-width:50px;"><?php echo $this->agreement['join_district'];?></span>
             					  រាជធានី/ខេត្ត/ក្រុង <span class="value" style="min-width:50px;">&nbsp;<?php echo $this->agreement['join_province'];?></span> 
             					 <?php }?> ហៅថា <strong>ភាគី”ខ”</strong>។ 
             					 <strong>ទូរស័ព្ទទំនាក់ទំនងលេខ</strong> <span class="value" style="min-width:100px;">&nbsp;<?php echo $dbparmeter->getNumberInkhmer($this->agreement['client_phone']); ?>&nbsp;</span>
							</td>
						</tr>
					</table>
					<span style="text-align:center; width: 100%; display: block; font-weight:600;">ភាគីទាំងពីរបានព្រមព្រៀងគ្នាផ្តិតស្នាមមេដៃលើកិច្ចសន្យានេះ តាមខ្លឹមសារ និងលក្ខខណ្ឌដូចខាងក្រោម៖</span>
             		<table width="100%" border="0">
						<tr>
						    <td align="justify" style="vertical-align:top; text-align:left;width:9%;">
							<span style="font-weight:600;">ប្រការ១៖</span>
							</td>
							<td align="justify" style="padding-left:5px">
								<strong>-ភាគី”ក”</strong> បានយល់ព្រមលក់ដីឡូតិ៍លេខ <span class="value" style="min-width:70px;"><?php echo $this->agreement['property_title'];?></span> ដែលមានព្រំប្រទល់ដូចខាងក្រោម៖
								<ul class="border-land">
									<li>
										&#9758; ខាងជើងទល់នឹង <?php echo $this->agreement['border_north'];?>
									</li>
									<li>
										&#9758; ខាងត្បូងទល់នឹង <?php echo $this->agreement['border_south'];?>
									</li>
									<li>
										&#9758; ខាងកើតទល់នឹង <?php echo $this->agreement['border_east'];?>
									</li>
									<li>
										&#9758; ខាងលិចទល់នឹង <?php echo $this->agreement['border_west'];?>
									</li>
								</ul>
								ស្ថិតនៅ <span class="value" style="min-width:150px;"><?php echo $this->agreement['project_location'];?></span> 
								ទៅឲ្យ <strong>ភាគី”ខ”</strong> ក្នុងតម្លៃសរុបចំនួន <strong>USD</strong> <span><?php echo number_format($this->agreement['price_sold'],2);?></span> (<span id="lable_pricekhmer" style="font-family:'Khmer os battambang';"></span>ដុល្លារអាមេរិក)
								<script>
									a_sold ='<?php echo ($this->agreement['price_sold']) ?>';
									money_khmersold=read_money_in_khmer(a_sold);
									
									decimalmoney_khmersold='<?php echo substr(number_format($this->agreement['price_sold'],2),-2);?>';
									str_centsold = 'សេន';
									if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
									last_number_sold='<?php echo substr(number_format($this->agreement['price_sold'],2),-2);?>';
									
									if(last_number_sold<=0){last_number_sold='';}
									money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
									dojo.byId('lable_pricekhmer').innerHTML=money_khmersold;
								</script>
							</td>
						</tr>
						<tr>
						    <td align="justify" style="vertical-align:top; text-align:left;width:9%;">
							<span style="font-weight:600;">ប្រការ២៖</span>
							</td>
							<td align="justify" style="padding-left:5px">
							-<strong>ភាគី”ខ”</strong> បានយល់ព្រមបង់ប្រាក់ជូន<strong>ភាគី“ក”</strong> ទៅតាមគោលការណ៍តារាងបង់ប្រាក់ក្នុង<strong><?php echo $tr->translate("ARTICLE_1");?></strong>។ 
							<br />
							-<strong>ភាគី”ក”</strong> នឹងជូនដំណឹងទៅ <strong>ភាគី”ខ”</strong> ដើម្បីមកទូទាត់ផ្តាច់ និងទទួលប្លង់កម្មសិទ្ធិ ដោយមានរយៈពេលកំណត់ចំនួនដប់ប្រាំ (១៥)ថ្ងៃ ។ ក្នុងករណីលើសកំណត់១៥ថ្ងៃ <strong>ភាគី”ខ”</strong> យល់ព្រមបង់ប្រាក់ពិន័យចំនួន <strong>មួយភាគរយ (១%) ក្នុងមួយថ្ងៃ</strong> នៃទឹកប្រាក់ដែលនៅសល់ មកអោយ<strong>ភាគី”ក”</strong> <strong><i>ដោយមិនមានការតវ៉ាឡើយ </i></strong>។ បើ<strong>ភាគី”ខ”</strong> ខកខានក្នុងការមិនមកទូទាត់ផ្តាច់លើសពី ៤៥ (សែសិបប្រាំ)ថ្ងៃ នោះទឹកប្រាក់ដែលភាគី”ខ” បានបង់ទាំងអស់នឹងត្រូវបានជាកម្មសិទ្ធិរបស់ភាគី”ក” ហើយកិច្ចសន្យានេះនឹងត្រូវរំលាយចោលជាស្វ័យប្រវត្តិ។ ក្នុងករណីនេះ ភាគី”ក” មានសិទ្ធិចាត់ចែងលក់ដីឡូតិ៍កំណត់ក្នុងប្រការ១ខាងលើ អោយទៅអ្នកដទៃបានគ្រប់ពេលវេលា ដោយភាគី”ខ”គ្មានសិទ្ធិតវ៉ាឡើយ។
							</td>
						</tr>
						<tr>
						    <td align="justify" style="vertical-align:top; text-align:left;width:9%;">
							<span style="font-weight:600;">ប្រការ៣៖</span>
							</td>
							<td align="justify" style="padding-left:5px">
							-<strong>ភាគី”ខ”</strong> អាចមានសិទ្ធិក្នុងការសាងសង់ ឬអាចអាស្រ័យផលលើដីឡូតិ៍នេះបាន ប៉ុន្តែការសាងសង់សំណង់ត្រូវតែរក្សាទុកកំពស់និងដែកតោងជញ្ជាំងតាមស្ដង់ដារ កំណត់របស់ក្រុមហ៊ុន និងចន្លោះផ្លូវថ្មើរជើងចំនួន <strong>០៥ (ប្រាំ)ម៉ែត្រ</strong> ពីចិញ្ចើមផ្លូវ និងទុកចន្លោះខាងក្រោយយ៉ាងតិច <strong>០២ (ពីរ)ម៉ែត្រ</strong>  ចៀសវាងការសាង់សង់សំណង់អាណាធិបតេយ្យដែលធ្វើអោយប៉ះប៉ាល់ដល់សោភ័ណ្ឌភាពទីតាំងទាំងមូល ។ ក្នុងករណីដែលការសាងសង់ផ្ទុយពីការបញ្ជាក់ដូចមានចែងក្នុងកិច្ចសន្យានេះ និងមិនត្រូវបានអនុញ្ញាតិអោយសាងសង់ឡើយ ។
							</td>
						</tr>
						<tr>
						    <td align="justify" style="vertical-align:top; text-align:left;width:9%;">
							<span style="font-weight:600;">ប្រការ៤៖</span>
							</td>
							<td align="justify" style="padding-left:5px">
							-<strong>ភាគី”ក”</strong> សូមសន្យាថា ក្រោយពីទទួលប្រាក់កក់ហើយ មិនកែរប្រែតម្លៃ ឬ ប្រែថាមិនលក់ឡើយ ។ បើការអនុវត្តន៍ ផ្ទុយពីនេះ ខ្ញុំបាទ/នាងខ្ញុំ សុខចិត្តសងប្រាក់.X2. ដងនៃប្រាក់កក់កន្លងមក ម្យ៉ាងវិញទៀត បើថ្ងៃក្រោយមានជនដ៏ទៃណាទោះក្នុងគ្រួសារ ឬក្រៅគ្រួសារ មកតវ៉ាថាដីនេះជាសម្បត្តិរបស់ខ្លួន ខ្ញុំបាទ/នាងខ្ញុំសូម ទទួលខុសត្រូវទាំងស្រុងចំពោះមុខច្បាប់ជាធរមាន ។
							</td>
						</tr>
					</table>
					<br />
					<span style="text-align:center; width: 100%; display: block; font-size: 13px;">ជាការធានាដល់សុក្រិតភាពនៃកិច្ចសន្យានេះ ភាគីទាំងពីរបានព្រមព្រៀងផ្តិតមេដៃស្តាំ ដើម្បីទុកជាភស្តុតាងក្នុងការទទួលខុសត្រូវចំពោះមុខច្បាប់៕</span>
					<span style="font-style:italic; text-align:center; width: 100%; display: block; font-size: 12px;">(ឯកសារនេះមិនមែនជាកម្មវត្ថុដែលអាចអនុញ្ញាតឲ្យ <strong>ភាគី”ខ”</strong> យកទៅដាក់បញ្ចាំបានឡើយ)</span>
					<br />
					<br />
					<div>
             			<div style="width:28%; text-align: center; display: inline-block;">
             				<span class="value">ស្នាមមេដៃអ្នកទិញ</span>
             			</div>
             			<div style="width:20%; text-align: center; display: inline-block;">
             				<span class="value">សាក្សីទី១</span>
             			</div>
             			<div style="width:20%; text-align: center; display: inline-block;">
             				<span class="value">សាក្សីទី២</span>
             			</div>
             			<div style="white-space:nowrap; width:28%; text-align: center; display: inline-block;">
             				<span class="value">ស្នាមមេដៃតំណាងស្របច្បាប់របស់អ្នកលក់</span>
             			</div>
             			<div style="height: 90px;">
             			</div>
             			<div style="width:28%;text-align: center; display: inline-block;">
             				<span class="border_bt  value" style="width:80%; white-space: nowrap;text-align: center;" >&nbsp;&nbsp;<?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"/".$this->agreement['hname_kh']:"";?>&nbsp;</span>
             			</div>
             			<div style="width:20%; text-align: center; display: inline-block;">
             				<span class="border_bt  value" style="width:80%;" >&nbsp;</span>
             			</div>
             			<div style="width:20%; text-align: center; display: inline-block;">
             				<span class="border_bt  value" style="width:80%;" >&nbsp;</span>
             			</div>
             			<div style="width:28%; text-align: center; display: inline-block;">
             				<span class="border_bt  value" style="width:80%;" >&nbsp;<?php echo $this->agreement['project_manager_namekh'];?></span>
             			</div>
             		</div>
             		
             		
             		
             	</td>
             </tr>
        </table>
        </div>
        </div>
    </td>	
</tr>
</table>
</div>