<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	
	$expenseFeatureList = EXPENSE_FEATURE_LIST;
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>
<style>
	.hover:hover{background: #ccc;}
</style>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_DAILY_CASH");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('REPORT_DAILY_CASH');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-daily-cash')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('branch_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('land_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('streetlist');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('client_name');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('user_id');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('payment_method');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
			   		<?php echo $frm->getElement('cheque_issuer_search');?>
			   	</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('start_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('queryOrdering');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
				
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
			</div>
		</div>
	 </form> 
<div style="min-height:22cm; margin:0 auto;">
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
		<tr>
	    	<td align="left">
	    	 <div id="divPrint">
	    	 	<style>
					.style{
    			line-height: 20px;font-size: 11px !important;
            font-family: 'Times New Roman','Khmer OS Battambang';
        }
        .hideblog{display: none;}
        .hiddenblog{display: block !important;}
        .style1:hover{ background: #ccc; }
        table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
        table.content-data { page-break-inside:auto }
		table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
        #header {
        display: table-header-group;
        page-break-inside:avoid; page-break-after:auto;
        margin-top: 100px;
        }
        .hide{visibility: hidden;}
        @media print {
        div.divFooter {
            position: fixed;
            top: 0;
            width: 100%;
            height: 100px;
            bottom:0px;
            margin:0;
        }
            .hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
            
        }
        .center{text-align: center !important;}
        table.content-data{
            border-collapse:collapse;
            border:1px solid #000; 
            font-size:8px;
        }
        table.content-data thead tr.style {
        line-height: 25px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
            background: #c1d0f3;
            font-weight:600;
        }
        table.content-data tr.style {
         white-space: nowrap;
        
        }
        table.tb-footer{
            border-collapse:collapse;
            border:1px solid #000; 
            font-size:11px;
            font-family: 'Times New Roman','Khmer OS Battambang';
        }
        table.tb-footer tr{
        line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
        }
        table tr td{
            padding:0 2px;
        }
        tr.voidclass {
            background: #fff7f7;
        }
        td.centerText{
            text-align: center;
        }
        .redBold {
            font-weight: 600;
            color: #f80000;
        }

/*

					.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					th{padding: 5px;}
					table { page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
						
						
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
						font-family: 'Times New Roman','Khmer OS Battambang';
						white-space: nowrap;
						line-height: 22px;
						width:100%;
					}
					table.content-data tr.style,
					table.content-data thead tr.style {
						line-height: 25px; font-size:13px !important;  white-space: nowrap;height: 22px; 
						background: #c1d0f3;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-family: 'Times New Roman','Khmer OS Battambang';
						font-size:11px;
					}
					table.tb-footer tr{
						line-height: 14px;  padding:2px 0px; height: 25px;
					}
					td.h2{
						font-weight:normal;
					}

					*/
					
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
						position: absolute;
						top: 0;
						width: 100%;
						height: 100px;
						bottom:0px;
						margin:0;
					  }
					  .hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
					}
				</style>
			    <table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
					<tr>
						<td colspan="3" style="border:1px solid #fff;">
							<div class="divFooter">
								<?php echo $this->headerReport;?>
						   </div>
					   </td>
					 </tr>
					
					 <tr>
						<td colspan="3" class="hide" >							
						</td>
					</tr>
					<tr>
			        <?php 
					
			            $category_id=0; $category_id_expense=0; 
	                	 $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;
	                	 $i=1;
	                	 $total_d=0;
						 
	                	 $total_cash = 0;
	                	 $total_cheque = 0;
	                	 $total_bank = 0;
						 
	                	 $principal=0;
	                	 $total_other_income=0;
	                	 $total_expese=0;
	                	 $total_extra=0;
	                	 $houserepair=0;
	                ?>
	            	<td colspan="3" id="exportExcel">
						<table class="content-data" width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
							
									
							<?php if(!empty($this->collectMoney)){?>
								 <tr>
									<td colspan="14" align="center" >
										<h2 style=" font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
											<span><?php echo $tr->translate("COLLECT_MONEY_INCOME");?></span>
										 </h2>
									</td>
								</tr>
								<thead>
								<tr class="style" align="center">
									<td scope="col"><?php echo $tr->translate("NUM");?></td>
									<td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td>
									<td scope="col"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
									<td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
									<td scope="col"><?php echo $tr->translate("PAYMENT_TYPE");?></td>   
									<td scope="col"><?php echo $tr->translate("PAID_PRINCIPAL");?></td>
									<td scope="col"><?php echo $tr->translate("EXTRA_PAYMENT");?></td>
									<td scope="col"><?php echo $tr->translate("INTEREST");?></td>
									<td scope="col"><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
									<td scope="col"><?php echo $tr->translate("TOTAL");?></td>    
									<td scope="col"><?php echo $tr->translate("INPUT_DATE");?></td>
									<td scope="col"><?php echo $tr->translate("RECIEPT_NO");?></td>
									<td scope="col"><?php echo $tr->translate("PAYMENT_OPTION");?></td>
									<td scope="col"><?php echo $tr->translate("BY_USER");?></td>
								</tr>
								</thead>
			               
			                <?php $is_set =0; if(!empty($this->collectMoney)) foreach ($this->collectMoney as $index => $rs){ ?>
			               <?php 
								$amt_d1 = $amt_d1+$rs['total_principal_permonthpaid'];
								$amt_d2 = $amt_d2+$rs['total_interest_permonthpaid'];
								$total_extra = $total_extra+$rs['extra_payment'];
								$amt_d3 = $amt_d3+$rs['penalize_amountpaid'];
								$amt_d5 = $amt_d5+$rs['service_chargepaid'];
								$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5+$total_extra;
								
// 								if($rs['payment_methodid']==1){
// 									$total_cash = $total_cash + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
// 								}elseif($rs['payment_methodid']==2){
// 									$total_cheque = $total_cheque + + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
// 								}else{
// 									$total_bank = $total_bank + + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
// 								}
								if($rs['payment_methodid']==1){
									$total_cash = $total_cash + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
								}elseif($rs['payment_methodid']==2){
									$total_bank = $total_bank  + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
								}else{
									$total_cheque = $total_cheque + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
								}
			               ?>
			                <tr class="hover style" >
			               		<td data-label="<?php echo $tr->translate("NUM");?>" style="text-align: center;"><?php echo $i++; ?></td>
			               		<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"><?php echo $rs["branch_name"];?></td>
			               		<td data-label="<?php echo $tr->translate("CUSTOMER_NAME");?>" ><?php echo $rs["name_kh"];?></td>                 		
			               		<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>"><?php echo $rs["land_address"].",".$rs["street"];?></td>
			               		<td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>" ><?php echo $rs["payment_method"];?> <?php if(!empty($rs["bank"])){ echo "(". $rs["bank" ].")";}else{echo  "";} ?></td>
			               		<td data-label="<?php echo $tr->translate("PAID_PRINCIPAL");?>" >
			               			<?php echo number_format($rs['total_principal_permonthpaid'],2);
			               			$principal = $principal+$rs['total_principal_permonthpaid'];
			               			?></td>
			               		<td data-label="<?php echo $tr->translate("EXTRA_PAYMENT");?>"><?php if($rs['extra_payment']>0){ echo number_format($rs['extra_payment'],2);}?></td>       		
			               		<td data-label="<?php echo $tr->translate("INTEREST");?>" ><?php echo number_format($rs['total_interest_permonthpaid'],2);?></td>
			               		<td data-label="<?php echo $tr->translate("PENALIZE AMOUNT");?>" ><?php echo number_format($rs['penalize_amountpaid'],2);?></td>
			               		<td data-label="<?php echo $tr->translate("TOTAL");?>" ><?php echo number_format($rs['amount_payment'],2);?></td>
			               		<td data-label="<?php echo $tr->translate("INPUT_DATE");?>" ><?php echo date("d-m-Y",strtotime($rs["date_pay"]));?></td>
			               		<td data-label="<?php echo $tr->translate("RECIEPT_NO");?>" ><?php echo $rs["receipt_no"];?></td>
			               		<td data-label="<?php echo $tr->translate("PAYMENT_OPTION");?>" style="font-site:9px; <?php if($rs["payment_option"]==4){echo " background:#ccc";} ?>" align="center" ><?php echo $rs["paymentoption"];?></td>
			               		<td data-label="<?php echo $tr->translate("BY_USER");?>" ><?php echo $rs["user_name"];?></td>
			                </tr>
			                <?php }?>
			                <tr style="text-align: center;font-size: 14px;">
			                	<td colspan="3" style="border: 1px solid #fff;border-top: 1px solid #000;border-right: 1px solid #000"></td>
			                	<td colspan="2" style=" background: #c1d0f3; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light';" ><?php echo $tr->translate("TOTAL_AMOUNT");?></td>
			                	<td data-label="<?php echo $tr->translate("PAID_PRINCIPAL");?>" style="background: #c1d0f3;"><?php echo number_format($principal,2);?></td>
			                	<td data-label="<?php echo $tr->translate("EXTRA_PAYMENT");?>" style="background: #c1d0f3;"><?php echo number_format($total_extra,2);?></td>
			                	<td data-label="<?php echo $tr->translate("INTEREST");?>" style="background: #c1d0f3;"><?php echo number_format($amt_d2,2);?></td>
			                	<td data-label="<?php echo $tr->translate("PENALIZE AMOUNT");?>" style="background: #c1d0f3;"><?php echo number_format($amt_d3+$amt_d5,2);?></td>
			                	<td data-label="<?php echo $tr->translate("TOTAL");?>" style="background: #c1d0f3;"><?php echo number_format($total_d,2);?></td>
			                	<td colspan="3" style="border: 1px solid #fff;border-top: 1px solid #000;border-left: 1px solid #000"></td>
			                </tr>
			                <?php }?>
			                
			                <?php 
				            	if (!empty($this->houserepair)){
				            ?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("REPAIR_HOUSE_INCOME");?></span>
						             </h2>
				            	</td>
				            </tr>
				            
				            <thead>
								<tr class="style" align="center" >
										<td scope="col"><?php echo $tr->translate("NUM");?></td>
										<td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td>
										<td scope="col"><?php echo $tr->translate("INCOME_TITLE");?></td>
										
										<td scope="col"><?php echo $tr->translate("CLIENT_NAME");?></td>
										<td scope="col"><?php echo $tr->translate("PAYMENT_TYPE");?></td>
										
										<td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
										<td scope="col"><?php echo $tr->translate("CATEGORY");?></td>
										<td scope="col"><?php echo $tr->translate("TOTAL_INCOME");?></td>
										
										<td scope="col"><?php echo $tr->translate("NUMBER");?></td>
										<td scope="col" colspan="2"><?php echo $tr->translate("NOTE");?></td>
										<td scope="col"><?php echo $tr->translate("RECEIPT_NO");?></td>
										<td scope="col"><?php echo $tr->translate("DATE");?></td>
										<td scope="col"><?php echo $tr->translate("BY_USER");?></td>
								</tr>
							</thead>
					   		<?php foreach ($this->houserepair as $index => $rs){
									
							?>
					   		<tr class=" style hover" style="<?php if($rs['status']==0){echo'background:#f7c6c6';}?>" width="100%">
			               		<td data-label="<?php echo $tr->translate("NUM");?>" style="text-align: center;"><?php echo $index+1; ?></td>
			               		<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"><?php echo $rs["branch_name"];?></td>
			               		<td data-label="<?php echo $tr->translate("INCOME_TITLE");?>" align="center"><?php echo $rs["title_income"];?></td> 
			               		<td data-label="<?php echo $tr->translate("CLIENT_NAME");?>" align="center"><?php echo $rs["name_kh"];?></td> 
								<td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>" valign="top"><?php echo $rs["payment_type"];?><?php if(!empty($rs["bank"])){ echo "(". $rs["bank" ].")";}else{echo  "";} ?></td>
			               		<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="center"><?php echo $rs["land_address"]." (".$rs["street"].")";?></td>
			               		<td data-label="<?php echo $tr->translate("CATEGORY");?>" valign="top"><?php echo $rs["category"];?></td>
			               		<td data-label="<?php echo $tr->translate("TOTAL_INCOME");?>" align="center"><strong><?php echo number_format($rs["total_amount"],2);?></strong></td>
			               		
			               		<td data-label="<?php echo $tr->translate("NUMBER");?>"><?php echo $rs["cheque"];?></td>
			               		<td data-label="<?php echo $tr->translate("NOTE");?>" colspan="2" style="white-space: normal !important;max-width:180px;text-align: left;"><?php echo $rs["description"];?></td>
			               		<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>" align="center"><?php echo $rs["invoice"];?> <?php if($rs['status']==0){ echo ' ('.$tr->translate("VOID").')';}?></td>
			               		<td data-label="<?php echo $tr->translate("DATE");?>" align="center"><?php echo date("d-m-Y",strtotime($rs["date"]));?></td>
			               		<td data-label="<?php echo $tr->translate("BY_USER");?>" align="center"><?php echo $rs["user_name"];?></td>
			                </tr>
			                <?php 
			                	if($rs['status']==1){
			                		$houserepair = $houserepair+$rs["total_amount"];
									if($rs['payment_id']==1){
										$total_cash = $total_cash + $rs["total_amount"];
									}elseif($rs['payment_id']==2){
										$total_bank = $total_bank + $rs["total_amount"];
									}else{
										$total_cheque = $total_cheque + $rs["total_amount"];
									}
			                	}
			                ?>
					   		<?php }
				             }?>
				            
				            
				            <?php if (!empty($this->row)){?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("OTHER_INCOME");?></span>
						             </h2>
				            	</td>
				            </tr>
				           <thead>
							<tr class="style" align="center" >
									<td scope="col"><?php echo $tr->translate("NUM");?></td>
									<td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td>
									<td scope="col"><?php echo $tr->translate("INCOME_TITLE");?></td>
									
									<td scope="col"><?php echo $tr->translate("CLIENT_NAME");?></td>
									<td scope="col"><?php echo $tr->translate("PAYMENT_TYPE");?></td>
									<td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
									<td scope="col"><?php echo $tr->translate("CATEGORY");?></td>
									
									<td scope="col"><?php echo $tr->translate("NUMBER");?></td>
									<td scope="col"><?php echo $tr->translate("TOTAL_INCOME");?></td>
									<td colspan="2"><?php echo $tr->translate("NOTE");?></td>
									<td scope="col"><?php echo $tr->translate("RECEIPT_NO");?></td>
									<td scope="col"><?php echo $tr->translate("DATE");?></td>
									<td scope="col"><?php echo $tr->translate("BY_USER");?></td>
								</tr>
						   </thead>
					       <?php $branch_id=''; $i=0;  foreach($this->row as $key =>$row){ $i++;?>
							<tr   class="hover style" >
							   <td data-label="<?php echo $tr->translate("NUM");?>" align="center"><?php echo $i; ?></td>
							   <td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"><?php echo $row['branch_name'];?></td>
							   <td data-label="<?php echo $tr->translate("INCOME_TITLE");?>" align="center" ><?php echo $row['title'];?></td>
							  
							   <td data-label="<?php echo $tr->translate("CLIENT_NAME");?>" align="center" ><?php echo $row['client_name'];?></td>
							   <td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>"><?php echo $row['payment_type'];?><?php if(!empty($row["bank"])){ echo "(". $row["bank" ].")";}else{echo  "";} ?></td>
							   <td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="center" ><?php echo $row['house_name'];?></td>
							   <td data-label="<?php echo $tr->translate("CATEGORY");?>"><?php echo $row['category_name'];?></td>
							   
							   <td data-label="<?php echo $tr->translate("NUMBER");?>"><?php echo $row['cheque'];?></td>
							   <td data-label="<?php echo $tr->translate("TOTAL_INCOME");?>" align="center"><?php echo number_format($row['total_amount'],2);?></td>
							   <td data-label="<?php echo $tr->translate("NOTE");?>" colspan="2" align="center" ><?php echo $row['description'];?></td>
								<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>" align="center"><?php echo $row['invoice'];?></td>
							   <td data-label="<?php echo $tr->translate("DATE");?>" align="center"><?php echo date("d-m-Y",strtotime($row['date']));?></td>
							   <td data-label="<?php echo $tr->translate("BY_USER");?>" align="center"><?php echo $row["user_name"];?></td>
							</tr>
								<?php $total_other_income = $total_other_income +$row['total_amount'];
								
								if($row['payment_id']==1){
									$total_cash = $total_cash + $row["total_amount"];
								}elseif($row['payment_id']==2){
									$total_bank = $total_bank + $row["total_amount"];
								}else{
									$total_cheque = $total_cheque + $row["total_amount"];
								}
								?>
							<?php }
				           }?>
				           
				           <?php 
				           $houserepairExpesnse = 0;
				           if (!empty($this->houserepairExpense)){?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("REPAIR_HOUSE_EXPENSE");?></span>
						             </h2>
				            	</td>
				            </tr>
				            <thead>
							<tr class="style" align="center" >
									<td scope="col"><?php echo $tr->translate("NUM");?></td>
								    <td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td>
								    <td scope="col"><?php echo $tr->translate("INCOME_TITLE");?></td>
								    
								    <td scope="col"><?php echo $tr->translate("CLIENT_NAME");?></td>
									<td scope="col"><?php echo $tr->translate("PAYMENT_TYPE");?></td>
								    <td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
								    <td scope="col"><?php echo $tr->translate("CATEGORY");?></td>
								    <td scope="col"><?php echo $tr->translate("TOTAL_INCOME");?></td>
								    
								    <td scope="col"><?php echo $tr->translate("NUMBER");?></td>
								    <td scope="col" colspan="2"><?php echo $tr->translate("NOTE");?></td>
									<td scope="col"><?php echo $tr->translate("RECEIPT_NO");?></td>
								    <td scope="col"><?php echo $tr->translate("DATE");?></td>
								    <td scope="col"><?php echo $tr->translate("BY_USER");?></td>
							</tr>
							</thead>
					   		<?php foreach ($this->houserepairExpense as $index => $rs){?>
					   		<tr class=" style hover" style="<?php if($rs['status']==0){echo'background:#f7c6c6';}?>" width="100%">
			               		<td data-label="<?php echo $tr->translate("NUM");?>" style="text-align: center;"><?php echo $index+1; ?></td>
			               		<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"><?php echo $rs["branch_name"];?></td>
			               		<td data-label="<?php echo $tr->translate("INCOME_TITLE");?>" align="center"><?php echo $rs["title_income"];?></td> 
			               		<td data-label="<?php echo $tr->translate("CLIENT_NAME");?>" align="center"><?php echo $rs["name_kh"];?></td>
								<td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>" valign="top"><?php echo $rs["payment_type"];?><?php if(!empty($rs["bank"])){ echo "(". $rs["bank" ].")";}else{echo  "";} ?></td>								
			               		<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="center"><?php echo $rs["land_address"]." (".$rs["street"].")";?></td>
			               		<td data-label="<?php echo $tr->translate("CATEGORY");?>" valign="top"><?php echo $rs["category"];?></td>
			               		<td data-label="<?php echo $tr->translate("TOTAL_INCOME");?>" align="right"><strong><?php echo number_format(abs($rs["total_amount"]),2);?></strong></td>
			               		
			               		<td data-label="<?php echo $tr->translate("NUMBER");?>"><?php echo $rs["cheque"];?></td>
			               		<td data-label="<?php echo $tr->translate("NOTE");?>" colspan="2" style="white-space: normal !important;max-width:180px;text-align: left;"><?php echo $rs["description"];?></td>
			               		<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>" align="center"><?php echo $rs["invoice"];?> <?php if($rs['status']==0){ echo ' ('.$tr->translate("VOID").')';}?></td>
			               		<td data-label="<?php echo $tr->translate("DATE");?>" align="center"><?php echo date("d-m-Y",strtotime($rs["date"]));?></td>
			               		<td data-label="<?php echo $tr->translate("BY_USER");?>" align="center"><?php echo $rs["user_name"];?></td>
			                </tr>
			                <?php 
			                	if($rs['status']==1){
			                		$houserepairExpesnse = $houserepairExpesnse+abs($rs["total_amount"]);
			                		$total_expese = $total_expese + abs($rs["total_amount"]);
									
									if($rs['payment_id']==1){
										$total_cash = $total_cash + $rs["total_amount"];
									}elseif($rs['payment_id']==2){
										$total_bank = $total_bank + $rs["total_amount"];
									}else{
										$total_cheque = $total_cheque + $rs["total_amount"];
									}
			                	}
			                ?>
					   		<?php }
				           }?>
				           
				   <?php if($expenseFeatureList==1){?>
							<?php 
				           if (!empty($this->rowExpensePayment)){?>
								<tr>
									<td colspan="14" align="center" style="border-top:2px solid #000; ">
										<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
											<span><?php echo $tr->translate("OTHER_EXPENSE");?></span>
										 </h2>
									</td>
								</tr>
								<thead>
									<tr class="style" align="center">
										<td scope="col"><?php echo $tr->translate('NUM');?></td>
										<td  scope="col"><?php echo $tr->translate('BRANCH_NAME');?></td>
										<td  scope="col" colspan="2"><?php echo $tr->translate('SUPPLIER_NAME');?></td>
										<td  scope="col"><?php echo $tr->translate('PAYMENT_TYPE');?></td>
										<td  scope="col" colspan="2"><?php echo $tr->translate('CHEQUE_ISSUER');?></td>
										<td  scope="col"><?php echo $tr->translate('NUMBER');?></td>
										<td  scope="col"><?php echo $tr->translate('TOTAL_PAID');?></td>
										<td  scope="col" colspan="2"><?php echo $tr->translate('NOTE');?></td>
										<td  scope="col"><?php echo $tr->translate('RECEIPT_NO');?></td>
										<td  scope="col"><?php echo $tr->translate('DATE');?></td>
										<td  scope="col"><?php echo $tr->translate('BY_USER');?></td>
									</tr>
								</thead>
								 <?php $branch_id=''; $i=0; 
									foreach($this->rowExpensePayment as $key =>$rows){ $i++;
									?>
									<tr class="style hover"  align="left">
									   <td data-label="<?php echo $tr->translate("NUM");?>"  align="center"><?php echo $i; ?></td>
									   <td data-label="<?php echo $tr->translate("BRANCH_NAME");?>" ><?php echo $rows['branch_name'];?></td>
									   <td data-label="<?php echo $tr->translate("SUPPLIER_NAME");?>"  colspan="2" align="left"><?php echo $rows['supplier_name'];?></td>
									   <td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>"  align="center"><?php echo $rows['paid_by'];?></td>
									   <td data-label="<?php echo $tr->translate("CHEQUE_ISSUER");?>"  colspan="2" align="left"><?php echo $rows['cheque_issuer'];?></td>
									   <td data-label="<?php echo $tr->translate("NUMBER");?>"  align="center"><?php echo $rows['cheque_no'];?></td>
									   <td data-label="<?php echo $tr->translate("TOTAL_PAID");?>"  align="right"><?php echo number_format($rows['total_paid'],2);?></td>
									    <td data-label="<?php echo $tr->translate("NOTE");?>"  colspan="2" align="left"><?php echo $rows['note'];?></td>
										<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>"  align="center"><?php echo $rows['receipt_no'];?></td>
										<td data-label="<?php echo $tr->translate("DATE");?>"  align="center"><?php echo date("d-m-Y",strtotime($rows['date_payment']));?></td>
										<td data-label="<?php echo $tr->translate("BY_USER");?>"  align="center"><?php echo $rows['user_name'];?></td>
									 </tr>
									 <?php 
											$total_expese = $total_expese +$rows['total_paid'];
											if($rows['paid_by_id']==1){
												$total_cash = $total_cash + $rows["total_paid"];
											}elseif($rows['paid_by_id']==2){
												$total_bank = $total_bank + $rows["total_paid"];
											}else{
												$total_cheque = $total_cheque + $rows["total_paid"];
											}
										?>
							   <?php }?>
						   <?php }?>
				   <?php }else{?>
						<?php 
				           if (!empty($this->rowExpense)){?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("OTHER_EXPENSE");?></span>
						             </h2>
				            	</td>
				            </tr>
				            <thead>
								<tr class="style" align="center">
									<td scope="col"><?php echo $tr->translate("NUM");?></td>
									<td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td>
									<td scope="col" colspan="2"><?php echo $tr->translate("EXPENSE_TITLE");?></td>
									<td scope="col"><?php echo $tr->translate("PAYMENT_TYPE");?></td>
									<td scope="col"><?php echo $tr->translate("CATEGORY");?></td>
									<td scope="col"><?php echo $tr->translate("NUMBER");?></td>
									<td scope="col"><?php echo $tr->translate("CHEQUE_ISSUER");?></td>
									<td scope="col"><?php echo $tr->translate("TOTAL_EXPENSE");?></td>
									<td scope="col" colspan="2"><?php echo $tr->translate("NOTE");?></td>
									<td scope="col"><?php echo $tr->translate("RECEIPT_NO");?></td>
									<td scope="col"><?php echo $tr->translate("DATE");?></td>
									<td scope="col"><?php echo $tr->translate("BY_USER");?></td>
								</tr>
							</thead>
					       <?php $branch_id=''; $i=0; 
					       foreach($this->rowExpense as $key =>$rows){ $i++;
					       ?>
							<tr class="style hover"   align="left">
							   <td data-label="<?php echo $tr->translate("NUM");?>" align="center"><?php echo $i; ?></td>
							   <td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"><?php echo $rows['branch_name'];?></td>
							   <td data-label="<?php echo $tr->translate("EXPENSE_TITLE");?>" colspan="2" align="center" style="white-space: normal !important;max-width:180px;text-align: left;"><?php echo $rows['title'];?></td>
							    <td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>"><?php echo $rows['payment_type'];?></td>
							   <td data-label="<?php echo $tr->translate("CATEGORY");?>"><?php echo $rows['category_name'];?></td>
							  
							   <td data-label="<?php echo $tr->translate("NUMBER");?>"><?php echo $rows['cheque'];?></td>
							   <td data-label="<?php echo $tr->translate("CHEQUE_ISSUER");?>"><?php echo $rows['cheque_issuer'];?></td>
							   <td data-label="<?php echo $tr->translate("TOTAL_EXPENSE");?>" align="right"><?php echo number_format($rows['total_amount'],2);?></td>
							   <td data-label="<?php echo $tr->translate("NOTE");?>" colspan="2" align="center" style="white-space: normal !important;max-width:120px;text-align: left;"><?php echo $rows['description'];?></td>
							   
							   <td data-label="<?php echo $tr->translate("RECEIPT_NO");?>" align="center"><?php echo $rows['invoice'];?></td>
							   <td data-label="<?php echo $tr->translate("DATE");?>" align="center"><?php echo date("d-m-Y",strtotime($rows['date']));?></td>
							   <td data-label="<?php echo $tr->translate("BY_USER");?>" align="center"><?php echo $rows["user_name"];?></td>
							</tr>
								<?php 
									$total_expese = $total_expese +$rows['total_amount'];
									if($rows['payment_id']==1){
										$total_cash = $total_cash + $rows["total_amount"];
									}elseif($rows['payment_id']==2){
										$total_bank = $total_bank + $rows["total_amount"];
									}else{
										$total_cheque = $total_cheque + $rows["total_amount"];
									}
								?>
							<?php }}?>
				   <?php }?>
				           
				            
				            <?php 
				            $total_commission = 0;
	            			if(!empty($this->rscomisison)){?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("COMMISSION");?></span>
						             </h2>
				            	</td>
				            </tr>
					    		<thead>

								<tr class="style" align="center" >
						        	<td scope="col"><?php echo $tr->translate("NUM");?></td>
							        <td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td>
							        <td scope="col"><?php echo $tr->translate("STAFF_NAME");?></td>
							        <td scope="col"><?php echo $tr->translate("TEL");?></td>
									<td scope="col"><?php echo $tr->translate("PAYMENT_TYPE");?></td>
							        <td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
							        
							        
								    <td scope="col" colspan="2"><?php echo $tr->translate("NUMBER");?></td>
								    <td scope="col" colspan="2"><?php echo $tr->translate("CHEQUE_ISSUER");?></td>
							    
							        <td scope="col"><?php echo $tr->translate("COMISSION");?></td>
							        <td scope="col"><?php echo $tr->translate("RECEIPT");?></td>
							        <td scope="col"><?php echo $tr->translate("DATE");?></td>
							        <td scope="col"><?php echo $tr->translate("BY_USER");?></td>
					         	</tr>
								</thead>
						       <?php  
						       	$key=0; 
								$record = $key;
								foreach($this->rscomisison as $key => $rscom){?>
								<?php 
									$total_commission = $total_commission +$rscom['total_amount'];
									
									if($rscom['payment_id']==1){
										$total_cash = $total_cash + $rscom["total_amount"];
									}elseif($rscom['payment_id']==2){
										$total_bank = $total_bank + $rscom["total_amount"];
									}else{
										$total_cheque = $total_cheque + $rscom["total_amount"];
									}
								?>
								 <tr class="style hover"  align="left" >
								     <td data-label="<?php echo $tr->translate("NUM");?>" align="center"><?php echo $key+1+$record; ?></td>
								     <td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"><?php echo $rscom['project_name']?></td>
									 <td data-label="<?php echo $tr->translate("STAFF_NAME");?>"><?php echo $rscom['staff_name'];?></td>
									 <td data-label="<?php echo $tr->translate("TEL");?>" align="center"><?php echo $rscom['tel'];?></td>
									  <td data-label="<?php echo $tr->translate("PAYMENT_TYPE");?>"><?php echo $rscom['payment_type'];?></td>
									 <td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" ><?php echo $rscom['land_address'].', '.$rscom['street'];?></td>
									 
									
									 <td data-label="<?php echo $tr->translate("NUMBER");?>" colspan="2"><?php echo $rscom['cheque'];?></td>
									 <td data-label="<?php echo $tr->translate("CHEQUE_ISSUER");?>" colspan="2"><?php echo $rscom['cheque_issuer'];?></td>
							   
									 <td data-label="<?php echo $tr->translate("COMISSION");?>" align="right"><?php echo number_format($rscom['total_amount'],2);?></td>
									 <td data-label="<?php echo $tr->translate("RECEIPT");?>" align="center"><?php echo $rscom['invoice']?></td>
									 <td data-label="<?php echo $tr->translate("DATE");?>" ><?php echo date("d-m-Y",strtotime($rscom['create_date']));?></td>
									 <td data-label="<?php echo $tr->translate("BY_USER");?>" align="center"><?php echo $rscom['user_name'];?></td>
								</tr>
								<?php } ?>
				            <?php }?>
			            </table>
	            	</td>
	            </tr>
	            
	            	<?php $total = ($total_d + $total_other_income +$houserepair) - ($total_expese+$total_commission) ;?>
	            <tr>
	            	<td colspan="3">
	            		<br />
	            		<table class="content-data" border="1"​  width="100%" cellspacing="0">
		                 <thead>
						 <tr  class="style" align="center" >
		                 	<td scope="col" colspan="5"><?php echo $tr->translate("COLLECT_MONEY_INCOME");?></td>
		                 	<td scope="col" rowspan="2"><?php echo $tr->translate("TOTAL_HOUSE_INCOME_RE");?></td>
		                 	<td scope="col" rowspan="2"><?php echo $tr->translate("OTHER_INCOME");?></td>
		                 	<td scope="col" rowspan="2"><?php echo $tr->translate("TOTAL_HOUSE_EXPENSE");?></td>
		                 	<td scope="col" rowspan="2"><?php echo $tr->translate("OTHER_EXPENSE");?></td>
		                 	<td scope="col" rowspan="2"><?php echo $tr->translate("COMMISSION");?></td>
		                 	<td scope="col" rowspan="2"><?php echo $tr->translate("TOTAL");?></td>
		                 </tr>
		                 <tr  class="style" align="center" >
		                    <td scope="col"><?php echo $tr->translate("PRINCIPAL");?></td>                    
		                    <td scope="col"><?php echo $tr->translate("EXTRA_PAYMENT");?></td>
		                    <td scope="col"><?php echo $tr->translate("TOTAL_INTEREST");?></td>
		                    <td scope="col"><?php echo $tr->translate("TOTAL_PENILIZE_AMOUNT");?></td>
		                    <td scope="col"><?php echo $tr->translate("TOTAL");?></td>
		                </tr>
						 </thead>
		                 <tr class="style" >
		                    <td data-label="<?php echo $tr->translate("PRINCIPAL");?>"  align="right"><?php echo number_format($amt_d1,2);?></td>
		                    <td data-label="<?php echo $tr->translate("EXTRA_PAYMENT");?>"  align="right"><?php echo number_format($total_extra,2);?></td>
		                    <td data-label="<?php echo $tr->translate("TOTAL_INTEREST");?>"  align="right"><?php echo number_format($amt_d2,2);?></td>
		                    <td data-label="<?php echo $tr->translate("TOTAL_PENILIZE_AMOUNT");?>"  align="right"><?php echo number_format($amt_d3,2);?></td>
		                    <td data-label="<?php echo $tr->translate("TOTAL");?>"  align="right"><strong><?php echo number_format($total_d,2);?></strong></td>
		                    <td data-label="<?php echo $tr->translate("TOTAL_HOUSE_INCOME_RE");?>"  align="right"><?php echo number_format($houserepair,2);?></td>
		                    <td data-label="<?php echo $tr->translate("OTHER_INCOME");?>"  align="right"><?php echo number_format($total_other_income,2);?></td>
		                    <td data-label="<?php echo $tr->translate("TOTAL_HOUSE_EXPENSE");?>"  align="right"><?php echo number_format($houserepairExpesnse,2);?></td>
		                    <td data-label="<?php echo $tr->translate("OTHER_EXPENSE");?>"  align="right"><?php echo number_format($total_expese,2);?></td>
		                    <td data-label="<?php echo $tr->translate("COMMISSION");?>"  align="right"><?php echo number_format($total_commission,2);?></td>
		                    <td data-label="<?php echo $tr->translate("TOTAL");?>"  align="center"><strong><?php echo number_format($total,2);?></strong></td>
		                </tr>
		              </table>
	            	</td>
	            </tr>
	           </table>
			   <br />
			 <table class="tb-footer" border="1"​ width="30%" cellspacing="0">
				<tr align="center" bgcolor="#c1d0f3" >
					<td colspan="2" align="center"><?php echo $tr->translate("TYPE");?></td>
				</tr>
				<tr>
					<td><?php echo $tr->translate("CASH");?></td>
					<td><?php echo number_format($total_cash,2);?></td>
				</tr>
				 <tr>
					<td><?php echo $tr->translate("PAYWITH_BANK");?></td>
					<td><?php echo number_format($total_bank,2);?></td>
				</tr>
				 <tr>
					<td><?php echo $tr->translate("CHEQUE");?></td>
					<td><?php echo number_format($total_cheque,2);?></td>
				</tr>
			  </table>
	           <br />
			   <?php echo $this->footerReport;?>
	          </div>
	       </td>
	    </tr>
	</table>
  
	</div>
</div>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore"); 
	require(["dojo/ready"], function(ready){
		ready(function(){
			 getBranchInfo();
			 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			 document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("REPORT_DAILY_CASH");?>';
			 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
		});
		
	});
	
	
	function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>
