<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_staff;

$dbGB = new Application_Model_DbTable_DbGlobal();
$logo = $this->baseUrl()."/images/logo.jpg";
$branch_title = $tr->translate("BRAND_TITLE");
if($this->search['branch_id'] >0){
	$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
	if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
		$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
	}
	//$branch_title = $branch['project_name'];
}

$headerReportType = REPORT_LETER_HEAD;
$classHideHeight="110px";
if($headerReportType==2){
	$classHideHeight="125px";
}
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT STAFF");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT STAFF');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-staff')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("branch_id");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("co_khname");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("co_sex");?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('search_status');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button"  type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
				</div>
			</div>
		</div>
 	</form> 
	<div id="divPrint">
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 	<style>
					.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
						}
						.hover:hover{background: #ccc;}
						.hide{visibility: hidden;}
							@media print {
							  div.divFooter {
							    position: fixed;
							    top: 0;
							  	width: 100%;
							  	height: 100px;
							  	bottom:0px;
								margin:0;
							  }
							.hide{visibility: visible; height: 110px;}
							}
						table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:13px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
							width: 100%;
						}
						table.content-data thead tr.style {
						   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
							background: #c1d0f3;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
						.hide{visibility: hidden;}
						@media print {
						 div.divFooter {
							position: absolute;
							top: 0;
							width: 100%;
							height: 100px;
							bottom:0px;
							margin:0;
						  }
							.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						}
				</style>
				<div class="divFooter">
					<?php echo $this->headerReport;?>
			   </div>
				<table id="exportExcel" class="content-data" width="100%" border="1" bordercolor="black">  
			    	<thead>
		                 <tr class="hide" style="border:1px solid #000;">
			                <td colspan="16" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
			             </tr>
				    	<tr bgcolor="#c1d0f3" class="style" align="center"  >
				        	<td scope="col"><?php echo $tr->translate("NUM");?></td>
				            <td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td>
				            <td scope="col"><?php echo $tr->translate("CO_NAME");?></td>
				            <td scope="col"><?php echo $tr->translate("SEX");?></td>
				            <td scope="col"><?php echo $tr->translate("PHONE");?></td>
				            <td scope="col"><?php echo $tr->translate("NATIONALITY_NO");?></td>
				            <td scope="col"><?php echo $tr->translate("EMAIL");?></td>
				            <td scope="col"><?php echo $tr->translate("POB");?></td>
				            <td scope="col"><?php echo $tr->translate("ADDRESS");?></td>
				            <td scope="col"><?php echo $tr->translate("NOTE");?></td>
				            <td scope="col"><?php echo $tr->translate("BY_USER");?></td>
				         </tr>
			         </thead>
			       <?php if(!empty($this->staff_list))foreach($this->staff_list as $key =>$row){?>
					   <tr style="font-size: 12px; " align="left" class="hover">
					     <td data-label="<?php echo $tr->translate("NUM");?>">&nbsp;<?php echo $key+1; ?></td>
					     <td data-label="<?php echo $tr->translate("BRANCH_NAME");?>" style="white-space: nowrap;">&nbsp;<?php echo $row['branch_name']?></td>
						 <td data-label="<?php echo $tr->translate("CO_NAME");?>">&nbsp;<?php echo $row['co_khname'];?></td>
						 <td data-label="<?php echo $tr->translate("SEX");?>">&nbsp;<?php echo $row['sex']?></td>
						 <td data-label="<?php echo $tr->translate("NATIONALITY_NO");?>" style="white-space: nowrap;">&nbsp;<?php echo $row['tel']?></td>
						 <td data-label="<?php echo $tr->translate("EMAIL");?>">&nbsp;<?php echo $row['national_id']?></td>
						 <td data-label="<?php echo $tr->translate("POB");?>">&nbsp;<?php echo $row['email']?></td>
						 <td data-label="<?php echo $tr->translate("ADDRESS");?>" style="white-space: pre;">&nbsp;<?php echo $row['pob']?></td>
						 <td data-label="<?php echo $tr->translate("NUM");?>" style="white-space: pre;">&nbsp;<?php echo $row['address']?></td>
						 <td data-label="<?php echo $tr->translate("NOTE");?>">&nbsp;<?php echo $row['note']?></td>
						 <td data-label="<?php echo $tr->translate("BY_USER");?>">&nbsp;<?php echo $row['user_name']?></td>
						</tr>
					<?php }?>
			    </table>
	    	</td>
	    </tr>
	</table>
	   <br />
	   <?php echo $this->footerReport;?>
	</div>
</div>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	require(["dojo/ready"], function(ready){
		ready(function(){

			 getBranchInfo();
	
			 
			 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			 document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("REPORT STAFF");?>';
			document.getElementById('dateReport').innerHTML = '&nbsp;';
			/*---- document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
			*/
		});
		
	});
	
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>