<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_cancel;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id_search'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id_search']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>

<meta charset="utf-8">
<title><?php echo $tr->translate("CANCEL_SALE_REPORT");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('CANCEL_SALE_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-cancel-sale')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('adv_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('branch_id_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('property_type');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('client_name');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('cancelTypeSearch');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('from_date_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('to_date_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
			</div>
		</div>
	 </form> 
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint">
	    	 	<style>
					.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
						font-weight: bold;						
						}
						th{padding: 2px;}
						.hide{visibility: hidden;}
						@media print {
						  div.divFooter {
							position: fixed;
							top: 0;
							width: 100%;
							height: 100px;
							bottom:0px;
							margin:0;
						  }
							.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						}
						table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:13px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
							width: 100%;
						}
						table.content-data thead tr.style {
						   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
							background: #c1d0f3;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
						table tr td{
							padding:0 2px;
						}
					</style>
	        		<div class="divFooter">
	        			<?php echo $this->headerReport;?>
			          </div>
		          <table id="exportExcel" class="content-data" width="100%"  border="1" >  
						      	 <thead>
					                <tr class="hide" style="border:1px solid #000;">
						                <td colspan="16" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						            </tr>
							      	<tr bgcolor="#a0baf5" class="style" align="center"  >
										<td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?></td>
										<td scope="col" colspan="5"><?php echo $tr->translate("INFO_INDILOAN");?></td>
										<td scope="col" colspan="3"><?php echo $tr->translate("PAYMENT_INFO");?></td>
										<td scope="col" colspan="5"><?php echo $tr->translate("CANCEL_INFO");?></td>
										
									    <td scope="col" rowspan="2"><?php echo $tr->translate("BY_USER");?></td>
									</tr>
									<tr bgcolor="#a0baf5" class="style" align="center"  >
										<td scope="col"><?php echo $tr->translate("PROJECT_NAME");?></td>
										<td scope="col"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
										<td scope="col"><?php echo $tr->translate("PROPERTY_TYPE");?></td>
										<td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
										<td scope="col"><?php echo $tr->translate("SOLD_PRICE");?></td>
										
						                <td scope="col"><?php echo $tr->translate("PAID");?></td>
						                <td scope="col"><?php echo $tr->translate("BALANCE");?></td>
						                <td scope="col"><?php echo $tr->translate("INSTALLMENT_PAID");?></td>
										
										<td scope="col"><?php echo $tr->translate("DATE");?></td>
										<td scope="col"><?php echo $tr->translate("CANCEL_TYPE");?></td>
						                <td scope="col"><?php echo $tr->translate("RETURN_MONEY_BACK");?></td>
						                <td scope="col"><?php echo $tr->translate("PAID");?></td>
									    <td scope="col"><?php echo $tr->translate("REASON");?></td>
									</tr>
								</thead>
						       <?php $property_type=''; $i=0; $total=0; 
						       if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
								<?php 
									$property_type= $row['property_type'];
								?>
								   <tr style="font-size: 12px;white-space: nowrap;" align="left">
								     <td data-label="<?php echo $tr->translate("NUM");?>" align="center"><?php echo $i; ?></td>
								     <td data-label="<?php echo $tr->translate("PROJECT_NAME");?>"><?php echo $row['project_name'];?></td>
								     <td data-label="<?php echo $tr->translate("CUSTOMER_NAME");?>" align="left"><?php echo $row['client_name'];?></td>
									 <td data-label="<?php echo $tr->translate("PROPERTY_TYPE");?>" align="left"><?php echo $row['type_name'];?></td>
									 <td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="left"><?php echo $row['land_address'].','.$row['street'];?></td>
									 <td data-label="<?php echo $tr->translate("SOLD_PRICE");?>" align="right" style="white-space: nowrap;"><?php echo number_format($row['price_sold'],2); ?></td>
									 <td data-label="<?php echo $tr->translate("PAID");?>" align="right" style="white-space: nowrap;"><?php echo number_format($row['paid_amount'],2);?></td>
									 <td data-label="<?php echo $tr->translate("BALANCE");?>" align="right" style="white-space: nowrap;"><?php echo number_format($row['price_sold']-$row['paid_amount'],2);?></td>
									 <td data-label="<?php echo $tr->translate("INSTALLMENT_PAID");?>" align="center" style="white-space: nowrap;"><?php echo (empty($row['installment_paid'])?"កក់ដំបូង":$row['installment_paid']);?></td>
									
									 <td data-label="<?php echo $tr->translate("DATE");?>" align="center" style="white-space: nowrap;"><?php echo date("d-m-Y",strtotime($row['create_date']));?></td>
									 <td data-label="<?php echo $tr->translate("CANCEL_TYPE");?>"  align="left" ><?php echo $row['cancelTypeTitle'];?></td>
									 <td data-label="<?php echo $tr->translate("RETURN_MONEY_BACK");?>" align="right" ><?php if($row['cancel_type']==1){ echo "-";}else{ echo number_format($row['return_back'],2);}?></td>
									 <td data-label="<?php echo $tr->translate("PAID");?>" align="right" ><?php if($row['cancel_type']==1){ echo "-";}else{echo number_format($row['totalReturnPaid'],2);}?></td>
									
									 <td data-label="<?php echo $tr->translate("REASON");?>" align="left" ><?php echo $row['reason'];?></td>
									 <td data-label="<?php echo $tr->translate("BY_USER");?>" align="center" ><?php echo $row['user_name'];?></td>
								  </tr>
								<?php 
								//$total = $total+$row['return_back'];
								$total = $total+$row['totalReturnPaid'];
						       }?>
						       <tr style="height: 30px; font-weight:bold; text-align: center;background:#87acff;">
									<td colspan="12" align="right"><?php echo $tr->translate("ប្រាក់ប្រគល់សរុប");?></td>
									<td><?php echo number_format($total,2);?></td>
									<td colspan="3">
									</td>
								</tr>
								
						    </table>
			          <br />
			          <?php echo $this->footerReport;?>
	            </div>
	    	</td>
	    </tr>
	</table>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dojo.data.ItemFileWriteStore"); 
	require(["dojo/ready"], function(ready){
		ready(function(){
			getBranchInfo();
			document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("CANCEL_SALE_REPORT");?>';
			document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['from_date_search'])){ if( date("Y-m-d",strtotime($this->search['from_date_search']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['to_date_search'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['to_date_search']));} }else{ echo date("d-M-Y",strtotime($this->search['to_date_search'])); }?>'; 
		});
		
	});
	
	
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id_search'])?0:$this->search['branch_id_search'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>