<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_cancel;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id_search'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id_search']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("CANCEL_SALE_REPORT");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CANCEL_SALE_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-cancel-sale')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('adv_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('branch_id_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('property_type');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('client_name');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('from_date_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('to_date_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
			</div>
		</div>
	 </form> 
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint">
	    	 	<style>
					.style{
						line-height: 20px;font-size: 12px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
						font-weight: bold;						
						}
						th{padding: 2px;}
						.hide{visibility: hidden;}
								@media print {
								  div.divFooter {
								    position: fixed;
								    top: 0;
								  	width: 100%;
								  	height: 100px;
								  	bottom:0px;
									margin:0;
								  }
								.hide{visibility: visible; height: 110px;}
								}
						table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:13px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
							width: 100%;
						}
						table.content-data thead tr.style {
						   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
							background: #c1d0f3;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
					</style>
	        		<div class="divFooter">
	        			<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0 auto;padding:0px; border:none;">
				        	<tr>
				                <td width="30%"><img src="<?php echo $logo;?>" style="height:80px;max-width:100%;"></td>
				                <td width="40%" valign="top">
				                <h2 style="white-space:nowrap;text-align:center; font-size:14px; font-weight:normal; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $branch_title;?></h2>
				                <h2 style="text-align:center; font-size:14px; font-weight:normal; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("CANCEL_SALE_REPORT");?></h2>
				                <h2 style="text-align:center; font-size:14px; font-weight:normal;"><?php if(!empty($this->search['from_date_search'])){echo date("d-M-Y",strtotime($this->search['from_date_search'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['to_date_search']));}?></h2>
				                <td width="30%"></td>
				             </tr> 
			             </table>
			          </div>
		          <table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0; border:none;" >
		            <tr>
		            	<td colspan="3">
		            		<table id="exportExcel" class="content-data" width="100%"  border="1" >  
						      	 <thead>
					                <tr class="hide" style="border:1px solid #000;">
						                <td colspan="16" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						            </tr>
							      	<tr bgcolor="#a0baf5" class="style" align="center"  >
										<td><?php echo $tr->translate("NUM");?></td>
										<td><?php echo $tr->translate("PROJECT_NAME");?></td>
										<td><?php echo $tr->translate("CUSTOMER_NAME");?></td>
										<td><?php echo $tr->translate("PROPERTY_TYPE");?></td>
										<td><?php echo $tr->translate("PROPERTY_CODE");?></td>
										<td><?php echo $tr->translate("SOLD_PRICE");?></td>
						                <td><?php echo $tr->translate("PAID");?></td>
						                <td><?php echo $tr->translate("BALANCE");?></td>
						                <td><?php echo $tr->translate("INSTALLMENT_PAID");?></td>
						                <td><?php echo $tr->translate("RETURN_MONEY_BACK");?></td>
									    <td><?php echo $tr->translate("DATE");?></td>
									    <td><?php echo $tr->translate("REASON");?></td>
									    <td><?php echo $tr->translate("BY_USER");?></td>
									</tr>
								</thead>
						       <?php $property_type=''; $i=0; $total=0; 
						       if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
								<?php 
									$property_type= $row['property_type'];
								?>
								   <tr style="font-size: 12px;white-space: nowrap;" align="left">
								     <td align="center">&nbsp;<?php echo $i; ?></td>
								     <td>&nbsp;<?php echo $row['project_name'];?></td>
								     <td align="left">&nbsp;<?php echo $row['client_name'];?></td>
									 <td align="left">&nbsp;<?php echo $row['type_name'];?></td>
									 <td align="left">&nbsp;<?php echo $row['land_address'].','.$row['street'];?></td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo number_format($row['price_sold'],2); ?>$</td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo number_format($row['paid_amount']);?> $</td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo number_format($row['price_sold']-$row['paid_amount']);?> $</td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo (empty($row['installment_paid'])?"កក់ដំបូង":$row['installment_paid']);?> </td>
									 <td align="center" >&nbsp;<?php echo $row['return_back'];?>&nbsp;</td>
									 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($row['create_date']));?> </td>
									 <td align="left" style="font-size: 10px;max-width:180px;white-space: pre-line;">&nbsp;<?php echo $row['reason'];?></td>
									 <td align="center" >&nbsp;<?php echo $row['user_name'];?>&nbsp;</td>
								  </tr>
								<?php 
								$total = $total+$row['return_back'];
						       }?>
						       <tr style="height: 30px; font-weight:bold; text-align: center;background:#87acff;">
									<td colspan="9" align="right">&nbsp;<?php echo $tr->translate("ប្រាក់ប្រគល់សរុប");?>&nbsp;</td>
									<td>&nbsp;<?php echo number_format($total,2);?>&nbsp;</td>
									<td colspan="3">
									</td>
								</tr>
								
						    </table>
		            	</td>
		             </tr>
		           </table>
			          <br />
			          <?php echo $this->footerReport;?>
	            </div>
	    	</td>
	    </tr>
	</table>
</div>