<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;

$dbGB = new Application_Model_DbTable_DbGlobal();
$logo = $this->baseUrl()."/images/logo.jpg";
$branch_title = $tr->translate("BRAND_TITLE");
if ($this->search['branch_id'] >0 ){
	$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
	if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
		$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
	}
	$branch_title = $branch['project_name'];
}
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_EXPENSE");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-expense')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
        	<div class="col-md-3 col-sm-3 col-xs-12">
        		<?php echo $frm->getElement("adv_search");?>
        	</div>
        	<div class="col-md-3 col-sm-3 col-xs-12">
        		<?php echo $frm->getElement('branch_id');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('supplier_id');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('category_id_expense');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('payment_type');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12"></div>
        </div>
        <div class="form-group">
        	<div class="col-md-3 col-sm-3 col-xs-12">
        		<?php echo $frm->getElement('start_date');?>
        	</div>
        	<div class="col-md-3 col-sm-3 col-xs-12">
        		<?php echo $frm->getElement('end_date');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement('ordering');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	</div>
        </div>        
	 </form> 
	<div style="min-height:22cm; margin:0 auto;">
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint">
	    	 	<style>
						.style{
							line-height: 20px;font-size: 14px !important;
							font-family: 'Khmer OS Battambang';
							}
							th{padding: 2px;}
							.hide{visibility: hidden;}
								@media print {
								  div.divFooter {
								    position: fixed;
								    top: 0;
								  	width: 100%;
								  	height: 100px;
								  	bottom:0px;
									margin:0;
								 }
							.hide{visibility: visible; height: 110px;}
							}
						</style>
				<div class="divFooter">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
		            	<tr>
			                <td width="20%"><img src="<?php echo $logo;?>" height="85px"></td>
			                <td width="60%" valign="top">
			                <h2 style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><label><?php echo $branch_title;?></label></h2>
			                <h2 style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("REPORT_EXPENSE");?></label></h2>
			                <p style="text-align:center; font-size:13px; font-family:'Khmer MEF2';margin-top: -15px;"><?php if(!empty($this->search['start_date'])){ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("d-M-Y",strtotime($this->search['end_date']));}?></p>
			                </td>
		                	<td width="20%"></td>
		             	</tr> 
		            </table>
		        </div>
	        	<table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
		            <tr>
	            	   <td colspan="3">
	            		<table id="exportExcel" border="1" width="100%" style="border-collapse:collapse; line-height: 24px; font-size: 14px; border:solid 1px #000;" >  
					    	<thead>
					    		<tr class="hide" style="border:1px solid #000;">
						             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						        </tr>
						    	<tr bgcolor="#c1d0f3" class="style" align="center" style="white-space:nowrap; font-weight:bold; line-height: 14px; line-height: 24px; font-size:14px; padding:5px 0px; " >
									<th><?php echo $tr->translate("NUM");?></th>
								    <th><?php echo $tr->translate("BRANCH_NAME");?></th>
								    <th><?php echo $tr->translate("SUPPLIER");?></th>
								    <th><?php echo $tr->translate("EXPENSE_TITLE");?></th>
								    <th><?php echo $tr->translate("RECIEPT_NO");?></th>
								    <th><?php echo $tr->translate("CATEGORY");?></th>
								    <th><?php echo $tr->translate("TOTAL_EXPENSE");?></th>
								    <th><?php echo $tr->translate("PAYMENT_TYPE");?></th>
								    <th><?php echo $tr->translate("CHEQUE_NUMBER");?></th>
								    <th><?php echo $tr->translate("NOTE");?></th>
								    <th><?php echo $tr->translate("DATE");?></th>
								    <th><?php echo $tr->translate("BY_USER");?></th>
								</tr>
							</thead>
					       <?php $branch_id=''; $i=0; $total=0; if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
							<tr style="font-size: 12px; line-height:20px;" align="left">
							   <td align="center">&nbsp;<?php echo $i; ?></td>
							   <td align="center"  style="white-space:nowrap">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
							   <td  style="white-space:nowrap">&nbsp;<?php echo $row['supplier_name'];?>&nbsp;</td>
							   <td >&nbsp;<?php echo $row['title'];?></td>
							   <td align="center">&nbsp;<?php echo $row['invoice'];?></td>
							   <td>&nbsp;<?php echo $row['category_name'];?></td>
							   <td align="center">&nbsp;<?php echo number_format($row['total_amount'],2);?></td>
							   <td align="center">&nbsp;<?php echo $row['payment_type'];?></td>
							   <td align="center">&nbsp;<?php echo $row['cheque'];?></td>
							   <td align="center">&nbsp;<?php echo $row['description'];?></td>
							   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-M-Y",strtotime($row['date']));?></td>
							   <td align="center">&nbsp;<?php echo $row['user_name'];?></td>
							</tr>
								<?php $total = $total +$row['total_amount'];?>
							<?php }?>
					    </table>
					    កម្រៃជើងសា
					    <table id="exportExcel" width="100%" border="1" style="border-collapse:collapse;font-size: 14px;" bordercolor="black">  
				    	<tr class="style" align="center" style="background:#b2ccff !important;font-weight:bold; line-height: 28px; font-size:12px; padding:5px 0px; " >
				        	<td><?php echo $tr->translate("NUM");?></td>
					        <td><?php echo $tr->translate("BRANCH_NAME");?></td>
					        <td><?php echo $tr->translate("STAFF_NAME");?></td>
					        <td><?php echo $tr->translate("TEL");?></td>
					        <td><?php echo $tr->translate("SEX");?></td>
					        <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
					        <td><?php echo $tr->translate("COMISSION");?></td>
					        <td><?php echo $tr->translate("DATE");?></td>
					        <th><?php echo $tr->translate("BY_USER");?></th>
				         </tr>
				       <?php  
				       	$key=0; 
						$record = $key;
						if(!empty($this->rscomisison))foreach($this->rscomisison as $key => $rscom){?>
						<?php 
							$total = $total +$rscom['total_amount'];
						?>
						 <tr style="font-size: 12px; font-family: 'Khmer OS Battambang'" align="left" class="hover">
						     <td align="center">&nbsp;<?php echo $key+1+$record; ?>&nbsp;</td>
						     <td align="center">&nbsp;<?php echo $rscom['project_name']?>&nbsp;</td>
							 <td>&nbsp;<?php echo $rscom['staff_name'];?>&nbsp;</td>
							 <td align="center">&nbsp;<?php echo $rscom['tel'];?>&nbsp;</td>
							 <td align="center">&nbsp;<?php if($rscom['sex']==1){ echo "ប្រុស";}else{ echo 'ស្រី';}?>&nbsp;</td>
							 <td style="white-space: nowrap;">&nbsp;<?php echo $rscom['land_address'].', '.$rscom['street'];?>&nbsp;</td>
							 <td align="right">&nbsp;<?php echo '$ '.number_format($rscom['total_amount'],2);?>&nbsp;</td>
							 <td style="white-space: nowrap;">&nbsp;<?php echo date("d-M-Y",strtotime($rscom['create_date']));?>&nbsp;</td>
							 <td align="center">&nbsp;<?php echo $rscom['user_name'];?></td>
						</tr>
						<?php } ?>
				    </table>
	            	</td>
	            </tr>
	            <tr style=" border-bottom: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;">
					<td colspan="11">
						<table align="right" style="margin-right: 6px;">
							  <tr style="font-size:14px; color:#000; height: 18px;"​ align="center">
								<td style="  width:146px; font-weight:bold; font-size: 14px;">&nbsp;<?php echo $tr->translate('TOTAL_EXPENSE');?>&nbsp;</td>
								<td style=" background: rgba(249, 225, 11, 0.7);  color:#000; font-weight:bold; width:112px; font-size: 14px;"></td>
								<td style="background: rgba(249, 225, 11, 0.7); color:#000; font-weight:bold; width:112px; font-size: 14px;">$ <?php echo number_format($total,2);?></td>
							  </tr>
						</table>
					</td>
				</tr>
	            </table>
			</div>
	    </td>
	   </tr>
   </table>
	<br />
		<table align="center" width="100%">
		   <tr style="font-size: 14px;">
		        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
		        <th></th>
		        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
		        <th></th>
		        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
		   </tr>
		</table>
	</div>
</div>