<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<style>
	.hover:hover{background: #ccc;}
</style>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_INC_EXP_OTHER");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('REPORT_INC_EXP_OTHER');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('branch_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<input id="land_id"/>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('streetlist');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('client_name');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('user_id');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('payment_method');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
			   		<?php echo $frm->getElement('cheque_issuer_search');?>
			   	</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('start_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
			</div>
		</div>
	 </form> 
<div style="min-height:22cm; margin:0 auto;">
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint">
	    	 	<style>
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
					}
					th{padding: 5px;}
					table { page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					
					
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
						font-family: 'Times New Roman','Khmer OS Battambang';
						white-space: nowrap;
						line-height: 22px;
					}
					table.content-data tr.style,
					table.content-data thead tr.style {
					   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-family: 'Times New Roman','Khmer OS Battambang';
						font-size:11px;
					}
					table.tb-footer tr{
					 line-height: 14px;  padding:2px 0px; height: 25px;
					}
					td.h2{
						font-weight:normal;
					}
					table tr td{
						padding:0 2px;
					}
					.hide{visibility: hidden;}
					@media print {
					  div.divFooter {
						position: fixed;
						top: 0;
						width: 100%;
						height: 100px;
						bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
					}
				</style>
					<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
			        	<tr>
			        		<td colspan="3" style="border:1px solid #fff;">
				        		<div class="divFooter">
					        		<?php echo $this->headerReport;?>
				               </div>
			               </td>
			             </tr>
			            <tr>
			        <?php 
			            $category_id=0; $category_id_expense=0; 
			        ?>
			         <?php 
	                	 $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;
	                	 $i=1;
	                	 $total_d=0;
	                	 $total_cash = 0;
	                	 $total_cheque = 0;
	                	 $total_bank = 0;
	                	 $principal=0;
	                	 $total_other_income=0;
	                	 $total_expese=0;
	                	 $total_extra=0;
	                	 $houserepair=0;
	                ?>
	            	<td colspan="3" id="exportExcel">
						<table class="content-data" width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
			                <tr class="hide" style="border:1px solid #000;">
								<td style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
							 </tr>
			                <?php 
				            	if (!empty($this->houserepair)){
				            ?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("REPAIR_HOUSE_INCOME");?></span>
						             </h2>
				            	</td>
				            </tr>
				            
				            <tr class="style" align="center" >
								<td><?php echo $tr->translate("NUM");?></td>
								    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
								    <td><?php echo $tr->translate("INCOME_TITLE");?></td>
								    <td><?php echo $tr->translate("RECEIPT_NO");?></td>
								    <td><?php echo $tr->translate("CLIENT_NAME");?></td>
								    <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
								    <td><?php echo $tr->translate("CATEGORY");?></td>
								    <td><?php echo $tr->translate("TOTAL_INCOME");?></td>
								    <td><?php echo $tr->translate("PAYMENT_TYPE");?></td>
								    <td><?php echo $tr->translate("NUMBER");?></td>
								    <td colspan="2"><?php echo $tr->translate("NOTE");?></td>
								    <td><?php echo $tr->translate("DATE");?></td>
								    <td><?php echo $tr->translate("BY_USER");?></td>
							</tr>
					   		<?php foreach ($this->houserepair as $index => $rs){?>
					   		<tr class=" stylehover" style="font-family: 'Times New Roman','Khmer OS Battambang';white-space: nowrap;<?php if($rs['status']==0){echo'background:#f7c6c6';}?>" width="100%">
			               		<td style="text-align: center;"><?php echo $index+1; ?></td>
			               		<td align="center"><?php echo $rs["branch_name"];?></td>
			               		<td align="center"><?php echo $rs["title_income"];?></td> 
			               		<td align="center"><?php echo $rs["invoice"];?> <?php if($rs['status']==0){ echo ' ('.$tr->translate("VOID").')';}?></td>
			               		<td align="center"><?php echo $rs["name_kh"];?></td> 
			               		<td align="center"><?php echo $rs["land_address"]." (".$rs["street"].")";?></td>
			               		<td valign="top"><?php echo $rs["category"];?></td>
			               		<td align="right"><strong><?php echo number_format($rs["total_amount"],2);?></strong></td>
			               		<td valign="top"><?php echo $rs["payment_type"];?></td>
			               		<td><?php echo $rs["cheque"];?></td>
			               		<td colspan="2" style="white-space: normal !important;max-width:180px;text-align: left;"><?php echo $rs["description"];?></td>
			               		<td align="center"><?php echo date("d-m-Y",strtotime($rs["date"]));?></td>
			               		<td align="center"><?php echo $rs["user_name"];?></td>
			                </tr>
			                <?php 
			                	if($rs['status']==1){
			                		$houserepair = $houserepair+$rs["total_amount"];
			                	}
			                ?>
					   		<?php }
				             }?>
				            
				            
				            <?php if (!empty($this->row)){?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("OTHER_INCOME");?></span>
						             </h2>
				            	</td>
				            </tr>
				            <tr class="style" align="center" >
								<td><?php echo $tr->translate("NUM");?></td>
							    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
							    <td><?php echo $tr->translate("INCOME_TITLE");?></td>
							    <td><?php echo $tr->translate("RECEIPT_NO");?></td>
							    <td><?php echo $tr->translate("CLIENT_NAME");?></td>
							    <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
							    <td><?php echo $tr->translate("CATEGORY");?></td>
							    <td><?php echo $tr->translate("PAYMENT_TYPE");?></td>
							    <td><?php echo $tr->translate("NUMBER");?></td>
							    <td><?php echo $tr->translate("TOTAL_INCOME");?></td>
							    <td colspan="2"><?php echo $tr->translate("NOTE");?></td>
							    <td><?php echo $tr->translate("DATE");?></td>
							    <td><?php echo $tr->translate("BY_USER");?></td>
							</tr>
					       <?php $branch_id=''; $i=0;  foreach($this->row as $key =>$row){ $i++;?>
							<tr style="font-size: 12px; line-height:20px; white-space: nowrap;" align="left">
							   <td align="center"><?php echo $i; ?></td>
							   <td align="center"><?php echo $row['branch_name'];?></td>
							   <td align="center" style="white-space: normal !important;max-width:180px;text-align: left;"><?php echo $row['title'];?></td>
							   <td align="center"><?php echo $row['invoice'];?></td>
							   <td align="center" style="white-space: nowrap;"><?php echo $row['client_name'];?></td>
							   <td align="center" style="white-space: nowrap;"><?php echo $row['house_name'];?></td>
							   <td><?php echo $row['category_name'];?></td>
							   <td><?php echo $row['payment_type'];?></td>
							   <td><?php echo $row['cheque'];?></td>
							   <td align="right"><?php echo number_format($row['total_amount'],2);?></td>
							   <td colspan="2" align="center" style="white-space: normal !important;max-width:180px;text-align: left;"><?php echo $row['description'];?></td>
							   <td align="center"><?php echo date("d-m-Y",strtotime($row['date']));?></td>
							   <td align="center"><?php echo $row["user_name"];?></td>
							</tr>
								<?php $total_other_income = $total_other_income +$row['total_amount'];?>
							<?php }
				           }?>
				           
				           <?php 
				           $houserepairExpesnse = 0;
				           if (!empty($this->houserepairExpense)){?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("REPAIR_HOUSE_EXPENSE");?></span>
						             </h2>
				            	</td>
				            </tr>
				            <tr class="style" align="center" >
								<td><?php echo $tr->translate("NUM");?></td>
								    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
								    <td><?php echo $tr->translate("INCOME_TITLE");?></td>
								    <td><?php echo $tr->translate("RECEIPT_NO");?></td>
								    <td><?php echo $tr->translate("CLIENT_NAME");?></td>
								    <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
								    <td><?php echo $tr->translate("CATEGORY");?></td>
								    <td><?php echo $tr->translate("TOTAL_INCOME");?></td>
								    <td><?php echo $tr->translate("PAYMENT_TYPE");?></td>
								    <td><?php echo $tr->translate("NUMBER");?></td>
								    <td colspan="2"><?php echo $tr->translate("NOTE");?></td>
								    <td><?php echo $tr->translate("DATE");?></td>
								    <td><?php echo $tr->translate("BY_USER");?></td>
							</tr>
					   		<?php foreach ($this->houserepairExpense as $index => $rs){?>
					   		<tr class=" stylehover" style="font-family: 'Times New Roman','Khmer OS Battambang';white-space: nowrap;<?php if($rs['status']==0){echo'background:#f7c6c6';}?>" width="100%">
			               		<td style="text-align: center;"><?php echo $index+1; ?></td>
			               		<td align="center"><?php echo $rs["branch_name"];?></td>
			               		<td align="center"><?php echo $rs["title_income"];?></td> 
			               		<td align="center"><?php echo $rs["invoice"];?> <?php if($rs['status']==0){ echo ' ('.$tr->translate("VOID").')';}?></td>
			               		<td align="center"><?php echo $rs["name_kh"];?></td> 
			               		<td align="center"><?php echo $rs["land_address"]." (".$rs["street"].")";?></td>
			               		<td valign="top"><?php echo $rs["category"];?></td>
			               		<td align="right"><strong><?php echo number_format(abs($rs["total_amount"]),2);?></strong></td>
			               		<td valign="top"><?php echo $rs["payment_type"];?></td>
			               		<td><?php echo $rs["cheque"];?></td>
			               		<td colspan="2" style="white-space: normal !important;max-width:180px;text-align: left;"><?php echo $rs["description"];?></td>
			               		<td align="center"><?php echo date("d-m-Y",strtotime($rs["date"]));?></td>
			               		<td align="center"><?php echo $rs["user_name"];?></td>
			                </tr>
			                <?php 
			                	if($rs['status']==1){
			                		$houserepairExpesnse = $houserepairExpesnse+abs($rs["total_amount"]);
			                		$total_expese = $total_expese + abs($rs["total_amount"]);
			                	}
			                ?>
					   		<?php }
				           }?>
				           
				           <?php 
				           if (!empty($this->rowExpense)){?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("OTHER_EXPENSE");?></span>
						             </h2>
				            	</td>
				            </tr>
				            <tr class="style" align="center">
								<td><?php echo $tr->translate("NUM");?></td>
							    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
							    <td colspan="2"><?php echo $tr->translate("EXPENSE_TITLE");?></td>
							    <td><?php echo $tr->translate("RECEIPT_NO");?></td>
							    <td><?php echo $tr->translate("CATEGORY");?></td>
							    <td><?php echo $tr->translate("PAYMENT_TYPE");?></td>
							    <td><?php echo $tr->translate("NUMBER");?></td>
							    <td><?php echo $tr->translate("CHEQUE_ISSUER");?></td>
							    <td><?php echo $tr->translate("TOTAL_EXPENSE");?></td>
							    <td colspan="2"><?php echo $tr->translate("NOTE");?></td>
							    <td><?php echo $tr->translate("DATE");?></td>
							    <td><?php echo $tr->translate("BY_USER");?></td>
							</tr>
					       <?php $branch_id=''; $i=0; 
					       foreach($this->rowExpense as $key =>$rows){ $i++;
					       ?>
							<tr style="font-size: 12px; line-height:20px; white-space: nowrap;" align="left">
							   <td align="center"><?php echo $i; ?></td>
							   <td align="center"><?php echo $rows['branch_name'];?></td>
							   <td colspan="2" align="center" style="white-space: normal !important;max-width:180px;text-align: left;"><?php echo $rows['title'];?></td>
							   <td align="center"><?php echo $rows['invoice'];?></td>
							   <td><?php echo $rows['category_name'];?></td>
							   <td><?php echo $rows['payment_type'];?></td>
							   <td><?php echo $rows['cheque'];?></td>
							   <td><?php echo $rows['cheque_issuer'];?></td>
							   <td align="right"><?php echo number_format($rows['total_amount'],2);?></td>
							   <td colspan="2" align="center" style="white-space: normal !important;max-width:120px;text-align: left;"><?php echo $rows['description'];?></td>
							   <td align="center"><?php echo date("d-m-Y",strtotime($rows['date']));?></td>
							   <td align="center"><?php echo $rows["user_name"];?></td>
							</tr>
								<?php $total_expese = $total_expese +$rows['total_amount'];?>
							<?php }}?>
				            
				            <?php 
				            $total_commission = 0;
	            			if(!empty($this->rscomisison)){?>
				            <tr>
				            	<td colspan="14" align="center" style="border-top:2px solid #000; ">
				            		<h2 style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light';padding: 0;margin: 0;">
						             	<span><?php echo $tr->translate("COMMISSION");?></span>
						             </h2>
				            	</td>
				            </tr>
					    		<tr class="style" align="center" >
						        	<td><?php echo $tr->translate("NUM");?></td>
							        <td><?php echo $tr->translate("BRANCH_NAME");?></td>
							        <td><?php echo $tr->translate("STAFF_NAME");?></td>
							        <td><?php echo $tr->translate("TEL");?></td>
							        <td><?php echo $tr->translate("SEX");?></td>
							        <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
							        
							        <td><?php echo $tr->translate("PAYMENT_TYPE");?></td>
								    <td colspan="2"><?php echo $tr->translate("NUMBER");?></td>
								    <td colspan="2"><?php echo $tr->translate("CHEQUE_ISSUER");?></td>
							    
							        <td><?php echo $tr->translate("COMISSION");?></td>
							        <td><?php echo $tr->translate("DATE");?></td>
							        <td><?php echo $tr->translate("BY_USER");?></td>
					         	</tr>
						       <?php  
						       	$key=0; 
								$record = $key;
								foreach($this->rscomisison as $key => $rscom){?>
								<?php 
									$total_commission = $total_commission +$rscom['total_amount'];
								?>
								 <tr style="font-size: 12px; font-family: 'Times New Roman','Khmer OS Battambang'" align="left" class="hover">
								     <td align="center"><?php echo $key+1+$record; ?></td>
								     <td align="center"><?php echo $rscom['project_name']?></td>
									 <td><?php echo $rscom['staff_name'];?></td>
									 <td align="center"><?php echo $rscom['tel'];?></td>
									 <td align="center"><?php if($rscom['sex']==1){ echo "ប្រុស";}else{ echo 'ស្រី';}?></td>
									 <td style="white-space: nowrap;"><?php echo $rscom['land_address'].', '.$rscom['street'];?></td>
									 
									 <td><?php echo $rscom['payment_type'];?></td>
									 <td colspan="2"><?php echo $rscom['cheque'];?></td>
									 <td colspan="2"><?php echo $rscom['cheque_issuer'];?></td>
							   
									 <td align="right"><?php echo number_format($rscom['total_amount'],2);?></td>
									 <td style="white-space: nowrap;"><?php echo date("d-m-Y",strtotime($rscom['create_date']));?></td>
									 <td align="center"><?php echo $rscom['user_name'];?></td>
								</tr>
								<?php } ?>
				            <?php }?>
			            </table>
	            	</td>
	            </tr>
	            
	            	<?php $total = ($total_d + $total_other_income +$houserepair) - ($total_expese+$total_commission) ;?>
	            <tr>
	            	<td colspan="3">
	            		<br />
	            		<table class="tb-footer" border="1"​  width="100%" cellspacing="0">
		                 <tr bgcolor="#c1d0f3" class="style" align="center" >
		                 	<td ><?php echo $tr->translate("OTHER_INCOME");?></td>
		                 	<td><?php echo $tr->translate("OTHER_EXPENSE");?></td>
		                 	<td ><?php echo $tr->translate("COMMISSION");?></td>
		                 	<td ><?php echo $tr->translate("TOTAL");?></td>
		                 </tr>
		                 <tr class="style" >
		                    <td align="right"><?php echo number_format($total_other_income,2);?></td>
		                    <td align="right"><?php echo number_format($total_expese,2);?></td>
		                    <td align="right"><?php echo number_format($total_commission,2);?></td>
		                    <td align="center"><strong><?php echo number_format($total,2);?></strong></td>
		                </tr>
		              </table>
	            	</td>
	            </tr>
	           </table>
	           <br />
			   <?php echo $this->footerReport;?>
	          </div>
	       </td>
	    </tr>
	</table>
  
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
	require(["dojo/ready"], function(ready){
		new dijit.form.FilteringSelect({
				store: property_store,
				required: false,
				autoComplete: false,
				queryExpr: "*${0}*",
				name: "land_id",
				id: "land_id",
				value:-1,
				searchAttr: "name",
				class: 'fullside fullside50',
				onChange: function() {
					land_id=-1;
			}
				}, "land_id");
				
		ready(function(){
			 getAllPropertyBranch();
			 getBranchInfo();
			 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			 document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("REPORT_INC_EXP_OTHER");?>';
			 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
		});
		
	});
	
land_id = '<?php echo $this->search['land_id']?>';
	var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
	function getAllPropertyBranch(branch_id){
		dijit.byId('land_id').reset();
		property_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
		dijit.byId('land_id').set('store', property_store);
		
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id<=0){
			return false;
		}
		
		dojo.xhrPost({
			url:url_getland,	
			content:{ 
			    'branch_id':branch_id,
			    'action':1
			},		    
			handleAs:"json",
			load: function(data) {
				property_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('land_id').set('store', property_store);
			    if(land_id>0){
			    	dijit.byId('land_id').attr('value',land_id);
				 }
			},
			error: function(err) {
			}
		});
	} 
	
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>
