<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_EXPENSE");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('REPORT_EXPENSE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-expense')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
        	<div class="col-md-3 col-sm-3 col-xs-12">
        		<?php echo $frm->getElement("adv_search");?>
        	</div>
        	<div class="col-md-3 col-sm-3 col-xs-12">
        		<?php echo $frm->getElement('branch_id');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('supplier_id');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('category_id_expense');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('payment_type');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12"></div>
        </div>
        <div class="form-group">
        	<div class="col-md-3 col-sm-2 col-xs-12">
	   		<?php echo $frm->getElement('cheque_issuer_search');?>
	   		</div>
        	<div class="col-md-3 col-sm-3 col-xs-12">
        		<?php echo $frm->getElement('start_date');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('end_date');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
				<?php echo $frm->getElement('queryOrdering');?>
				<?php //echo $frm->getElement('ordering');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        	</div>
        </div>        
	 </form> 
		<div id="divPrint" >
    	 	<style >
			.style{
				line-height: 20px;font-size: 14px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
				}
				th{padding:1px;}
				.hide{visibility: hidden;}
				@media print {
					  div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					 }
					.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
				}
			table.content-data{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:13px;
				font-family: 'Times New Roman','Khmer OS Battambang';
				white-space: nowrap;
				line-height: 22px;
			}
			table.content-data tr.style,
			table.content-data thead tr.style {
			   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #c1d0f3;
			}
			table.content-data td{
				padding: 3px;
			}
			table.tb-footer{
				border-collapse:collapse;
				border:1px solid #000; 
				font-family: 'Times New Roman','Khmer OS Battambang';
				font-size:11px;
			}
			table.tb-footer tr{
			 line-height: 14px;  padding:1px 0px; height: 25px;
			}
			table tr td{
				padding:0 2px;
			}
		</style>
		<div class="divFooter">
        	<?php echo $this->headerReport;?>
        </div>
            		<table class="content-data"  border="1" width="100%"  >  
				    	<thead>
				    		<tr class="hide" style="border:1px solid #000;">
				             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
				        </tr>
				    	<tr bgcolor="#c1d0f3" class="style" align="center"  >
							<td><?php echo $tr->translate("NUM");?></td>
						    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
						    <td><?php echo $tr->translate("SUPPLIER");?></td>
						    <td><?php echo $tr->translate("EXPENSE_TITLE");?></td>
						    <td><?php echo $tr->translate("RECIEPT_NO");?></td>
						    <td><?php echo $tr->translate("CATEGORY");?></td>
						    <td><?php echo $tr->translate("INVOICE");?></td>
						    <td><?php echo $tr->translate("TOTAL_EXPENSE");?></td>
						    <td><?php echo $tr->translate("PAYMENT_TYPE");?></td>
						    <td><?php echo $tr->translate("NUMBER");?></td>
						    <td><?php echo $tr->translate("CHEQUE_ISSUER");?></td>
						    <td><?php echo $tr->translate("NOTE");?></td>
						    <td><?php echo $tr->translate("DATE");?></td>
						    <td><?php echo $tr->translate("BY_USER");?></td>
						</tr>
					</thead>
			       <?php $branch_id=''; $i=0; $total=0; if(!empty($this->row)){foreach($this->row as $key =>$row){ $i++;?>
					<tr class="context-menu-one" oncontextmenu="setrowdata('<?php echo $row['id'];?>');return false;" style="font-size: 12px; line-height:20px;" align="left">
					   <td align="center"><?php echo $i; ?></td>
					   <td align="center"  style="white-space:nowrap"><?php echo $row['branch_name'];?></td>
					   <td  style="white-space:nowrap"><?php echo $row['supplier_name'];?></td>
					   <td style="line-height: 18px;white-space: normal !important; max-width: 150px;width: 150px;padding: 2px;overflow-wrap: break-word;"><?php echo $row['title'];?></td>
					   <td align="center"><?php echo $row['invoice'];?></td>
					   <td style="line-height: 18px;white-space: normal !important; max-width: 150px;width: 150px;padding: 2px;overflow-wrap: break-word;"><?php echo $row['category_name'];?></td>
					   <td align="center"><?php echo $row['other_invoice'];?></td>
					   <td align="right"><?php echo number_format($row['total_amount'],2);?></td>
					   <td align="center"><?php echo $row['payment_type'];?></td>
					   <td align="center"><?php echo $row['cheque'];?></td>
					   <td align="center"><?php echo $row['cheque_issuer'];?></td>
					   <td align="center" style="line-height: 18px;white-space: normal !important; max-width: 200px;width: 200px;padding: 2px;overflow-wrap: break-word;"><?php echo $row['description'];?></td>
					   <td align="center" style="white-space: nowrap;"><?php echo date("d-m-Y",strtotime($row['date']));?></td>
					   <td align="center"><?php echo $row['user_name'];?></td>
					</tr>
						<?php $total = $total +$row['total_amount'];?>
					<?php }}?>
					 <?php if(!empty($this->rscomisison)){?>
					 <tr  style="font-size: 12px; line-height:20px;">
					   <td align="center" colspan="14">
					   	<span style="font-weight:normal;font-size:12px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("COMMISSION");?></span>
					   </td>
					 </tr>
						<tr class="style" align="center" >
				        	<td><?php echo $tr->translate("NUM");?></td>
					        <td><?php echo $tr->translate("BRANCH_NAME");?></td>
					        <td colspan="2"><?php echo $tr->translate("STAFF_NAME");?></td>
					        <td><?php echo $tr->translate("RECIEPT_NO");?></td>
					        <td colspan="2"><?php echo $tr->translate("Customers");?></td>
					        
					        <td ><?php echo $tr->translate("COMISSION");?></td>
					        <td><?php echo $tr->translate("PAYMENT_TYPE");?></td>
						    <td><?php echo $tr->translate("NUMBER");?></td>
						    <td><?php echo $tr->translate("CHEQUE_ISSUER");?></td>
						    
					        
					        <td colspan="2"><?php echo $tr->translate("DATE");?></td>
					        <td><?php echo $tr->translate("BY_USER");?></td>
			         	</tr>
			         	<?php  
					       	$key=0; 
							$record = $key;
							foreach($this->rscomisison as $key => $rscom){?>
							<?php 
								$total = $total +$rscom['total_amount'];
							?>
							 <tr style="font-size: 12px; font-family: 'Times New Roman','Khmer OS Battambang'" align="left" class="hover">
							     <td align="center"><?php echo $key+1+$record; ?></td>
							     <td align="center"><?php echo $rscom['project_name']?></td>
								 <td colspan="2" ><?php echo $rscom['staff_name'];?> <?php if($rscom['sex']==1){ echo "(ប្រុស)";}else{ echo '(ស្រី)';} echo empty($rscom['tel'])?"":" ".$rscom['tel'];?> </td>
								 <td align="center"><?php echo $rscom['invoice'];?></td>
								 <td colspan="2"><?php echo $rscom['client_name']; echo " ".$rscom['land_address'].', '.$rscom['street'];?></td>
								 
								 <td align="right"><?php echo number_format($rscom['total_amount'],2);?></td>
								 <td align="center"><?php echo $rscom['payment_type'];?></td>
								 <td align="center"><?php echo $rscom['cheque'];?></td>
								 <td align="center"><?php echo $rscom['cheque_issuer'];?></td>
					   
								 
								 <td align="center" colspan="2" style="white-space: nowrap;"><?php echo date("d-m-Y",strtotime($rscom['create_date']));?></td>
								 <td align="center"><?php echo $rscom['user_name'];?></td>
							</tr>
							<?php }
							?>
					 <?php }?>
					 <?php if(!empty($this->rowCommissionPayment)){?>
						 <tr  style="font-size: 12px; line-height:20px;">
						   <td align="center" colspan="14">
							<span style="font-weight:normal;font-size:12px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("COMMISSION_PAYMENT");?></span>
						   </td>
						 </tr>
						 <tr class="style" align="center" >
				        	<td><?php echo $tr->translate("NUM");?></td>
					        <td><?php echo $tr->translate("BRANCH_NAME");?></td>
					        <td colspan="2"><?php echo $tr->translate("STAFF_NAME");?></td>
					        <td><?php echo $tr->translate("RECIEPT_NO");?></td>
					        <td colspan="2"><?php echo $tr->translate("CATEGORY");?></td>
					        
					        <td ><?php echo $tr->translate("COMISSION");?></td>
					        <td><?php echo $tr->translate("PAYMENT_TYPE");?></td>
						    <td><?php echo $tr->translate("NUMBER");?></td>
						    <td><?php echo $tr->translate("CHEQUE_ISSUER");?></td>
						    
					        
					        <td colspan="2"><?php echo $tr->translate("DATE");?></td>
					        <td><?php echo $tr->translate("BY_USER");?></td>
			         	</tr>
						 <?php $c=0; foreach ($this->rowCommissionPayment AS $rs){ $c++; $total = $total +$rs['total_paid']; ?>
							<tr style="font-size: 12px; font-family: 'Times New Roman','Khmer OS Battambang'" align="left" class="hover">
							     <td align="center"><?php echo $c; ?></td>
							     <td align="center"><?php echo $rs['branch_name']?></td>
								 <td colspan="2" ><?php echo $rs['staff_name'];?> <?php if($rs['sex']==1){ echo "(ប្រុស)";}else{ echo '(ស្រី)';} echo empty($rs['tel'])?"":" ".$rs['tel'];?> </td>
								 <td align="center"><?php echo $rs['receipt_no'];?></td>
								 <td colspan="2"><?php echo $rs['category_name'];?></td>
								 
								 <td align="right"><?php echo number_format($rs['total_paid'],2);?></td>
								 <td align="center"><?php echo $rs['payment_type'];?></td>
								 <td align="center"><?php echo $rs['cheque_no'];?></td>
								 <td align="center"><?php echo $rs['cheque_issuer'];?></td>
					   
								 
								 <td align="center" colspan="2" style="white-space: nowrap;"><?php echo date("d-m-Y",strtotime($rs['date_payment']));?></td>
								 <td align="center"><?php echo $rs['user_name'];?></td>
							</tr>
						 <?php }?>
					 <?php }?>
					 <?php 
		            	if (!empty($this->houserepair)){
		            	?> 
						 <tr  style="font-size: 12px; line-height:20px;">
						   <td align="center" colspan="14">
						   		<span style="font-weight:normal;font-size:12px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("ចំណាយពីការកែផ្ទះ");?></span>
						   </td>
						 </tr>
						 <tr class="style" align="center"  >
							<td><?php echo $tr->translate("NUM");?></td>
						    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
						    
						    <td colspan="2"><?php echo $tr->translate("EXPENSE_TITLE");?></td>
						    <td><?php echo $tr->translate("RECEIPT_NO");?></td>
						   ​​ 
						   	<td ><?php echo $tr->translate("CATEGORY");?></td>
						   	<td><?php echo $tr->translate("Customers");?></td>
						    
						    <td><?php echo $tr->translate("TOTAL");?></td>
						    <td><?php echo $tr->translate("PAYMENT_TYPE");?></td>
						    <td><?php echo $tr->translate("CHEQUE");?></td>
						    <td colspan="2"><?php echo $tr->translate("NOTE");?></td>
						    <td><?php echo $tr->translate("DATE");?></td>
						    <td><?php echo $tr->translate("BY_USER");?></td>
						</tr>
						<?php foreach ($this->houserepair as $index => $rs){?>
					   		<tr class="stylehover" style="<?php if ($rs['status']==0){ echo "background: #f7c6c6;";}?>  font-family: 'Times New Roman','Khmer OS Battambang';white-space: nowrap;" width="100%">
			               		<td style="text-align: center;"><?php echo $index+1; ?></td>
			               		<td align="center"><?php echo $rs["branch_name"];?></td>
			               		
			               		<td colspan="2" align="center"><a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt-otherincome','id'=>$rs['id']));?>?repair=1"><?php echo $rs["title_income"];?></a></td> 
			               		<td align="center"><a target="_blank" style="<?php if ($rs['status']==0){ echo "color:red;";}else{ echo "color:#000;";}?>text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt-otherincome','id'=>$rs['id']));?>?repair=1"><?php echo $rs["invoice"];  if ($rs['status']==0){ echo " ".$tr->translate("មោឃៈ");}?></a></td>
			               		<td valign="top" ><?php echo $rs["category"];?></td>
			               		
			               		<td><a target="_blank" style="color:#000;text-decoration: none;" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt-otherincome','id'=>$rs['id']));?>?repair=1"><?php echo $rs["name_kh"]; echo " ".$rs["land_address"]." (".$rs["street"].")";?></a></td>
			               		
			               		<td align="right"><strong><?php  if ($rs['status']==0){ echo "-";}else{ echo number_format(abs($rs["total_amount"]),2);}?></strong></td>
			               		<td><?php echo $rs["payment_method"];?></td>
			               		<td align="center"><?php echo $rs["cheque"];?></td>
			               		<td colspan="2"><?php echo $rs["description"];?></td>
			               		<td align="center"><?php echo date("d-m-Y",strtotime($rs["date"]));?></td>
			               		<td align="center"><?php echo $rs["user_name"];?></td>
			                </tr>
			                 <?php 
			                if ($rs['status']!=0){
			                	$total = $total + abs($rs['total_amount']);
			                }
			               ?>
					   		<?php }?>
					  <?php }?>
					 <!-- 
					   <tr>
		                    <td colspan="14"></td>
		                </tr>
					  -->
					  <tr class="style style1" style="font-weight: 600; background: #c1d0f3;">
	                	<td colspan="7" align="right"><?php echo $tr->translate('TOTAL_EXPENSE');?></td>
	                	<td colspan="2"  align="right">$ <?php echo number_format($total,2);?></td>
	                    <td colspan="5"></td>
	                </tr>
			    </table>
			<br />
			<?php echo $this->footerReport;?>
		</div>
		<!-- end of print -->
	</div>
<?php 
$urlprint = $this->baseUrl()."/report/loan/receipt-expense/id/";
$urlDetail = $this->baseUrl()."/report/loan/expense-detail/id/";
$urlExpensDetailItems = $this->baseUrl()."/report/paramater/rpt-expense-detail/id/";
$settingDoc = SETTING_EXPENSE_DOC;
$expenseFeatureList = EXPENSE_FEATURE_LIST;
?>
<script type="text/javascript">

require(["dojo/ready"], function(ready){
 	ready(function(){
		getBranchInfo();
		document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
		document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("REPORT_EXPENSE");?>';
		document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
	
 	});
 	
 });
 
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="print"){
				url='<?php echo $urlprint;?>';
			}else if(key=="detail"){
				url='<?php echo $urlDetail;?>';
			}else if(key=="detailList"){
				url='<?php echo $urlExpensDetailItems;?>';
			}
			gotoAction();
		},
		items: {
			"print": {name: "<?php echo $tr->translate("PRINT");?>", icon: "fa-print", accesskey: "c o p y"},
			<?php 
			if($settingDoc==1){
			?>
			"detail": {name: "<?php echo $tr->translate("PAYMENT_VOUCHER​_DOCUMENT");?>", icon: "fa-print", accesskey: "c o p y"},
			<?php 
			}
			?>
			<?php 
			if($expenseFeatureList==1){
			?>
			"detailList": {name: "<?php echo $tr->translate("PAYMENT_VOUCHER​_LIST");?>", icon: "fa-print", accesskey: "c o p y"},
			<?php 
			}
			?>
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row+'?rightclick=true', '_blank');
}

 function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>
