<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_property;
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->list_end_date['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->list_end_date['branch_id']);
		if(file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_PROPERTY");?></title>
<div class="reportblog">
<form name="frm_rptstaff" action="" dojoType="dijit.form.Form" method="post">
	<table style="margin: 0 auto;width: 100%;">
		 <tr> 
			  <td><?php echo $frm->getElement("adv_search");?></td>
			  <td><?php echo $frm->getElement("branch_id");?></td>
			  <td><?php echo $frm->getElement("streetlist");?></td>
			  <td><?php echo $frm->getElement("property_type");?></td>
			  <td><?php echo $frm->getElement("type_property_sale");?></td>
	   	  </tr>
	   	  <tr>
	   	  	  <td><?php echo $frm->getElement("plong_processtype");?></td>
	   	  	  <td><?php echo $frm->getElement("process_status");?></td>
	   	  	  <td><?php echo $frm->getElement("plong_type");?></td>
		   	  <td><?php echo $frm->getElement('start_date');?></td>
		      <td><?php echo $frm->getElement('end_date');?></td>
		      <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button"  type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
			  </td>
		   </tr>
	</table>
 </form> 
<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint">
    	 	<style>
			.style{
				line-height: 20px;font-size: 11px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
				font-weight: bold;
			}
				th{padding: 5px;}
				.hover:hover{background: #ccc;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
			table.content-data{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:13px;
				font-family: 'Times New Roman','Khmer OS Battambang';
				white-space: nowrap;
				line-height: 22px;
				width: 100%;
			}
			table.content-data tr td{
				padding:0 1px;
			}
			table.content-data thead tr.style {
			   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #c1d0f3;
			}
			table.tb-footer{
				border-collapse:collapse;
				border:1px solid #000; 
				font-family: 'Times New Roman','Khmer OS Battambang';
				font-size:11px;
			}
			table.tb-footer tr{
			 line-height: 14px;  padding:2px 0px; height: 25px;
			}			
			.border_bottom {
			    border-bottom: 1px solid #000;
			}
 		</style>
	<div class="divFooter">
	    <table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;" >
	        <tr>
	          	<td width="30%"><img src="<?php echo $logo;?>" style="height:80px;max-width: 100%;"></td>
	              <td width="40%" valign="top">
		                <ul>
		                	<li style="white-space:nowrap;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $branch_title;?></li>
		                	<li style="white-space:nowrap;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("RPT_PLONG_LIST");?></li>
		                	<li style="text-align:center; font-size:14px;"><?php if(!empty($this->list_end_date['start_date'])){ echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';}echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></li>
			            </ul>
		           </td>
	               <td width="30%"></td>
	         </tr> 
	   </table>
	</div>
     <table id="exportExcel" class="content-data" border="1"​ width="100%" cellspacing="0" >
		     <thead>
		     	<tr bgcolor="#c1d0f3" class="style hover" align="center">
					<td  rowspan="2"><?php echo $tr->translate("NUM");?></td>
					<td  rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></td>
					<td colspan="3"><span><?php echo $tr->translate("PROPERTY_INFO");?></span></td>
					
					<td colspan="2"><span><?php echo $tr->translate("INFO_INDILOAN");?></span></td>
					<td colspan="2"><span><?php echo $tr->translate("HEAD_TITL_INFO");?></span></td>
					
					<td colspan="4"><?php echo $tr->translate("កិច្ចការការទទួល");?></td>
				</tr>
				<tr bgcolor="#c1d0f3" class="style hover" align="center">
					<td ><?php echo $tr->translate("PROPERTY_CODE");?></td>
					<td ><?php echo $tr->translate("STREET_NO");?></td>
					<td ><?php echo $tr->translate("PROPERTY_TYPE");?></td>
					
					<td ><?php echo $tr->translate("SOLD_PRICE");?></td>
					<td ><?php echo $tr->translate("PAID");?></td>
					
					<td><?php echo $tr->translate("HEAD_TITLE_NO");?></td>
					<td><?php echo $tr->translate("PLONG_STEP");?></td>
					
					<td ><?php echo $tr->translate("CUSTOMER_NAME");?></td>
					<td ><?php echo $tr->translate("TEL");?></td>
					<td ><?php echo $tr->translate("LAYOUT_TYPE");?></td>
					<td ><?php echo $tr->translate("RECEIVED_DATE");?></td>
				</tr>
			</thead>
			<?php 
				$org_plong = 0;$processing_plong=0;$give_plong=0;
				if(!empty($this->row))foreach($this->row as $key =>$row){?>
					   <tr class="hover" style="font-size: 12px;border:1px solid #000; white-space: nowrap;line-height: 25px;" align="left">
					     <td align="center"><?php echo $key+1; ?></td>
					     <td align="center"><?php echo $row['branch_name'];?></td>
					     <td align="center"><?php echo $row['land_address'];?></td>
					     <td align="center"><?php echo $row['street'];?></td>
						
						<td align="center"><?php echo $row['pro_type'];?></td>
						<td align="center"><?php if(!empty($row['price_sold'])){ echo number_format($row['price_sold'],2);}else{ echo "-";} ?></td>
					    
						<td align="center"><?php if(!empty($row['totalPaid'])){ echo number_format($row['totalPaid'],2);}else{ echo "-";} ?></td>
						
						 <td align="center" style="border:1px solid #000;"><?php echo $row['hardtitle'];?></td>
						 <td><?php echo $row['processing']; ?></td>
						 <td><?php echo $row['client_name'];?></td>
						 <td><?php echo $row['tel']; ?></td>
						 <td align="center" ><?php echo $row['layout_type']; ?></td>
						 <td align="center"><?php echo empty($row['received_date'])?"":date("d-m-Y",strtotime($row['received_date'])); ?></td>
					 </tr>
				<?php 
					if(!empty($row['hardtitle']) AND empty($row['processing']) AND empty($row['layout_type'])){
						$org_plong = $org_plong+1;
					}
					if(!empty($row['processing']) AND empty($row['layout_type'])){
						$processing_plong = $processing_plong+1;
					}
					if(!empty($row['layout_type'])){
						$give_plong = $give_plong+1;
					}
				?>
			<?php }?>
			<?php if(!empty($this->row)){?>
			<tr>
				<td colspan="12" style="border: solid 1px #fff;border-top: solid 1px #000;">
					<br />
					 <table style=" font-size:14px;width:70%;margin:0 auto;" cellspacing="0">
		                 <tr bgcolor="#a0baf5" class="style" style=" line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                 	<td>&nbsp;</td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("ប្លង់មិនទាន់រត់");?></span>&nbsp;&nbsp;</td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("ប្លង់កំពុងរត់មិនទាន់ប្រគល់");?></span></td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("ប្លង់ប្រគល់អោយអតិថិជន");?></span></td>
		                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL");?></span></td>
		                    <td>&nbsp;</td>
		                 </tr>
		                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
		                  	<td>&nbsp;</td>
		                  	<td align="center"><?php echo $org_plong;?></td>
		                    <td align="center"><?php echo $processing_plong;?></td>
		                    <td align="center"><?php echo $give_plong;?></td>
		                    <td align="center"><strong><?php echo $org_plong+$processing_plong+$give_plong;?></strong></td>
		                    <td>&nbsp;</td>
		                  </tr>
			          </table>
			          <br />
				</td>
			</tr>
			<?php }?>
	    </table>
	 </div>
	</td>
  </tr>
</table>
</div>