<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$day = array(
		"Mon" =>'ច័ន្ទ',
		"Tue" =>'អង្គារ',
		"Wed" =>'ពុធ',
		"Thu" =>'ព្រហស្បតិ៍',
		"Fri" =>'សុក្រ',
		"Sat" =>'សៅរ៍',
		"Sun" =>'អាទិត្យ',
		);
$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
$dbparmeter = new Report_Model_DbTable_DbParamater();
$key = new Application_Model_DbTable_DbKeycode();
$dataterm = $key->getKeyCodeMiniInv(TRUE);
$branch_title = $tr->translate("BRAND_TITLE");
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title><?php echo $tr->translate("AGREEMENT");?></title>
<style>
	.reff{ font-size: 20px !important; line-height:34px !important;}
	#divPrint tr td h2,#divPrint p,#divPrint pre,#divPrint span,#divPrint td{ font-size: 20px !important; line-height:34px !important;}
	#divPrint span.font-size12 { font-size: 16px !important;}
	#padding-left-p-2{
	 padding-left: 105px !important;	
	}
	.padding-buttom{
		margin-top: -5px !important;
	}
	#printfooter{display: none !important;}
</style>
<div  id="exportword" style=" width:28cm;min-height:22cm; margin:0 auto; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint" >
    	 	<style>		
					    #padding-left-p-2{
						 padding-left: 105px !important;	
						}
						.padding-buttom{
							margin-top: -5px !important;
						}
    	 				.reff{ font-size: 16px !important; line-height:34px !important;}
						tr td h2,p,pre,span{ font-size: 15px ; line-height:30px;}
						#padding-left{
						padding-left: 18px;
						}
						#bold-padding-right{
							margin-right: 15px;
							font-family: khmer os battambang;
							font-size:19px;
						}
						
						#padding-left-2{
						/*margin-top: -10px;*/
						padding-left:15px;
						}
						.padding-buttom{
							margin-top: -5px;
						}
						#padding-left-p-2{
						 margin-top:-1px; 
						 padding-left: 85px;	
						}
						#padding-left-p{
					    padding-left: 105px;
						}
						th{padding: 5px;}
						span.value{ line-height:12px;display: inline-block; text-align: center;}
						span.child {display:block; margin-left:25px; line-height: 25px;}
						span{line-height: 26px;}
						div.pages-break{
							page-break-inside:always; page-break-after:always; 
						}
						div.watermark{
							top: 0; position: fixed; display: block; 
							background: url('<?php echo $this->baseUrl()."/images/watermark-sh-realestate.png";?>') no-repeat center; 
					    	height: 100%;z-index: -1; width: 100%;  
							opacity: 0.1;
						}
						body {
						    position: relative;
						}
							
							#printfooter {
							    position: absolute;
							    bottom: 0;
							    position: fixed;
							    display: block ;
							}
							span.border_bt.value{
							    border-bottom: dashed 1px #000;
							}
							.value_label{
							    border-bottom: dotted 1px #000;
							}
							span.margin-left{
								margin-left:40px; display: inline-block;
							}
    </style>
    	<div class="pages-break ">
    		<div class="watermark"></div>
        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="padding:0;margin:0;border:0px;" >
        	<tr>
                <td width="30%" valign="top">
                	<?php $imagelogo = $this->baseUrl()."/images/logo.jpg";
	                	if (!empty($this->agreement['project_logo'])){
	                		$imagelogo = $this->baseUrl()."/images/projects/".$this->agreement['project_logo'];
	                	}
	                	?>
                	<img src="<?php echo $imagelogo;?>" style="max-width:100%; height: 85px; margin-top: 20px;">
                </td>
                <td width="40%" align="center">
                <span style="text-align:center; line-height:28px; font-size:17px;font-family:'Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា</span>
                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.jpg" height="25px"></span>
                <span style="margin-bottom:10px;text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("កិច្ចសន្យាកក់ប្រាក់");?></span>
                <td width="30%" valign="top" align="right">
                	<br /><br /><br />
                	<span style="text-align:center; line-height:28px; font-size:17px;font-family:'Times New Roman','Khmer OS Battambang';">N<sup>o</sup></span> <span style="width:100px; display: inline-block; border-bottom: dashed 1px #000;"></span>
                </td>
             </tr> 
             <tr>
             	<td colspan="3">
             		<p style="font-family:'Khmer OS Battambang','Times New Roman',; text-align:justify; line-height:24px; font-size:14px; font-weight: normal !important;">
             			<?php $certificat_No = "០០០៣៣៧២០";?>
             			<span class="margin-left">&nbsp;</span><strong><?php echo $branch_title;?></strong> ដែលមានវិញ្ញាបនបត្របញ្ជាក់ការចុះបញ្ជីនៅក្រសួងពាណិជ្ជកម្មលេខ <strong><?php echo $dbparmeter->getNumberInkhmer($certificat_No);?></strong> តំណាងស្របច្បាប់ដោយលោក <span class="value" style="min-width:135px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['project_manager_namekh'];?></span> 
             			ភេទ<span class="value" style="min-width:10px;"><?php echo $this->agreement['manager_sex'];?></span> 
             			សញ្ជាតិ<span class="value" style="min-width:10px;"><?php echo $this->agreement['project_manager_nationality'];?></span> 
             			កាន់អត្តសញ្ញាណប័ណ្ណលេខ <span class="value" style="min-width:60px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['project_manager_nation_id']);?></span> 
             			អាសយដ្ឋាន<?php echo $this->agreement['project_manager_p_current_address'];?>
             			<?php if (!empty($this->agreement['w_manager_namekh'])){?>
             			 និងឈ្មោះ <span class="value" style="min-width:50px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['w_manager_namekh'];?></span> 
             			ភេទ  <span class="value" style="min-width:10px;"><?php echo $this->agreement['sc_manager_sex'];?></span>
             			សញ្ជាតិ <span class="value" style="min-width:10px;"><?php echo $this->agreement['w_manager_nationality'];?></span>
             			កាន់អត្តសញ្ញាណប័ណ្ណលេខ <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_manager_nation_id'];?></span>
             			អាសយដ្ឋាន <span class="value" style="min-width:150px;"><?php echo $this->agreement['w_current_address'];?></span>
             			<?php }?> ។ បានព្រមព្រៀងគ្នាលក់ <span class="value" style="min-width:20px;"><?php echo $this->agreement['property_type_kh'];?></span> មួយកន្លែង ដែលមានលេខ<span class="value"><?php echo $this->agreement['property_title'];?></span> ទំហំ <span class="value" style="min-width:70px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['land_size']);?></span> ម៉ែត្រក្រឡា 
             			ស្ថិតនៅ<?php echo $this->agreement['project_location'];?>។
             			<span style="display:block; width:100%; font-family:'Khmer OS Muol Light'; text-align: center; font-weight: 200;">ដែលមានព្រំប្រទល់ដូចខាងក្រោម:</span>
             			<span style=" margin-left: 50px;"></span>- ខាងជើងទល់នឹង <span class="value" style="min-width:150px;"><?php echo $this->agreement['border_north'];?></span> - ខាងត្បូងទល់នឹង 	<span class="value" style="min-width:150px;"><?php echo $this->agreement['border_south'];?></span>
             			<br />
             			<span style=" margin-left: 50px;"></span>- ខាងលិចទល់នឹង<span class="value" style="min-width:150px;"><?php echo $this->agreement['border_west'];?></span> - ខាងកើតទល់នឹង <span class="value" style="min-width:150px;"><?php echo $this->agreement['border_east'];?></span> 
             			<br />
             			<span class="margin-left">&nbsp;</span>បានលក់ជូនទៅឈ្មោះ <span class="value" style="font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['client_namekh'];?></span> 
             			ភេទ <span class="value" style="min-width:10px;"><?php echo $this->agreement['sexKh'];?></span>
	             		អាយុ  <span class="value" style="min-width:10px;"><?php if (!empty($this->agreement['dob'])){ echo $dbparmeter->getNumberInkhmer(date("Y") - date("Y",strtotime($this->agreement['dob'])));}?></span> ឆ្នាំ
	             		សញ្ជាតិ <span class="value" style="min-width:10px;"><?php echo $this->agreement['client_nationality'];?></span> 
	             		<?php if(!empty($this->agreement['hname_kh'])){?>
		             		ព្រមទំាងឈ្មោះ <span class="value" style="min-width:150px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['hname_kh'];?></span> ភេទ  <span class="value" style="min-width:40px;"><?php echo $this->agreement['client_buywith_sex'];?></span>
		             		អាយុ <span class="value" style="min-width:30px;"><?php if (!empty($this->agreement['w_client_dob_buywith'])){ echo $dbparmeter->getNumberInkhmer(date("Y") - date("Y",strtotime($this->agreement['w_client_dob_buywith'])));}?></span> ឆ្នាំ
		             		សញ្ជាតិ <span class="value" style="min-width:20px;"><?php echo $this->agreement['w_client_nationality'];?></span>
             			<?php }?> 
             			មានទីលំនៅបច្ចុប្បន្ន ភូមិ <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_village_kh'];?></span> ឃុំ/សង្កាត់ <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_commune_kh'];?></span> ស្រុក/ខណ្ឌ <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_districtkh'];?></span> ខេត្ត/ក្រុង  <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_province_kh'];?></span> 
             			ទូរស័ព្ទលេខ <span class="value" style="min-width:20px;"><?php echo $this->agreement['phone'];?></span>។
             			<br />
             			
             		
             		</p>
             		<p>
             			<span style=" padding-left: 50px; min-width: 29%; display: inline-block;">ភាគីទាំងពីរបានឯកភាពគ្នាក្នុងតម្លៃ  </span> 
             				<span class="value" style="text-align:left; padding-left: 10px;"><strong>$ <?php echo number_format($this->agreement['price_sold'],2);?></strong> </span><span> <span id="lable_pricesoldkhmer" style="font-family:'Khmer os battambang';"></span>ដុល្លារអាមេរិក</span>
             			<br />
             			<?php $dbs = new Loan_Model_DbTable_DbLandpayment();
		             			$resultdeposit = $dbs->getDepositFirstPaymentMoney($this->agreement['id']);
		             			$start_id=0;
		             			$paid_amount=0;
		             			$rowpaid = $dbs->getPaymentPayoff($this->agreement['id']);
		             			$paid_payoff = $rowpaid['outstanding'];
		             			$paid = 0;
		             			$keytime=0;
		             		?>
		             		<?php //if(!empty($resultdeposit) AND $this->agreement['is_reschedule']==1){
		             			if(!empty($resultdeposit)){?><!-- ប្រាក់កក់ -->
	             				<?php foreach($resultdeposit as $keydeposite =>$rsdeposite){ $keytime++;?>
	             				<span style=" display: inline-block;white-space: nowrap;">
	             				<?php 
	             				$labelpaid="ភាគីទិញបានកក់ប្រាក់លើកទី";
	             				if ($keytime>1){
	             					$labelpaid="កក់លើកទី";
		             			}?>
	             				<?php echo $labelpaid.$dbparmeter->getNumberInkhmer($keytime);?> ចំនួន
		             				<span class="value"><strong>$ <?php echo @number_format($rsdeposite['total_principal_permonthpaid'],2);?></strong> <span id="lable_depositpaid<?php echo $keydeposite+1;?>" style="font-family:'Khmer os battambang';"></span>ដុល្លារអាមេរិក</span> 
		             				<span>នៅថ្ងៃទី  <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($rsdeposite['date_input'])));?>  ខែ  <?php echo $month[date("m",strtotime($rsdeposite['date_input']))];?>  ឆ្នាំ  <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($rsdeposite['date_input'])));?></span>
	             				</span>
	             				<script>
													a ='<?php echo ($rsdeposite['total_principal_permonthpaid']) ?>';
													money_khmer=read_money_in_khmer(a);
													decimalmoney_khmer='<?php echo substr(number_format($rsdeposite['total_principal_permonthpaid'],2),-2);?>';
													str_cent = 'សេន';
													if(decimalmoney_khmer>0){string='និង';}else{string="";str_cent='';}
													
													last_number='<?php echo substr(number_format($rsdeposite['total_principal_permonthpaid'],2),-2);?>';
													
													if(last_number<=0){last_number='';}
													money_khmer = money_khmer+" "+string+" "+read_in_khmer_from_10_to_99(decimalmoney_khmer)+''+read_in_khmer_from_0_to_9(last_number)+''+str_cent;
													dojo.byId('lable_depositpaid<?php echo $keydeposite+1;?>').innerHTML=money_khmer;
												</script>
             				<?php 
								$paid_amount = $paid_amount+$rsdeposite['total_principal_permonthpaid'];
	             				}
		             		echo "<br />";
		             		}?>
	             			<!--
	             			<?php 
		             			///$i=0; $numrow = 0;
		             			//if (!empty($this->sale_schedule))  foreach ($this->sale_schedule as $key=> $row){$i++;  ?>
		             			<?php 
		             			//if($row['is_completed']==1 AND $this->agreement['is_reschedule']==3){continue;}
		             			//$paid = $paid+$row['principal_permonth'];?>             	
		             			<?php //if($key==0){?>
			             		<?php
			             			//if($row['date_payment']==$this->agreement['buy_date'] AND $paid_amount==$row['principal_permonth'] ){
			             				//continue;
			             			//}
		             			//	$paidbefore = $row['principal_permonth']-$paid_amount;
		             				//if(strlen($paidbefore)<=3){$row['principal_permonth']=number_format($paidbefore,2);}
		             				//else{
		             					//$row['principal_permonth'] = ($paidbefore);
		             				//}
		             			//}$keytime++;?>
		             			 
		             			<?php 
		             				//$numrow=$numrow+1;?>
		             				<span style="display: inline-block;white-space: nowrap;">
		             						បង់ប្រាក់លើកទី<?php //echo $dbparmeter->getNumberInkhmer($keytime);?>  ចំនួន
			             				<span class="value"><strong>$ <?php //echo @number_format($row['principal_permonth'],2);?></strong> </span>
			             				<span> ជាអក្សរ <span id="lable_depositkhmer<?php //echo $i;?>" style="font-family:'Khmer os battambang';"></span>ដុល្លារអាមេរិក</span>
			             				<?php //if($row['last_optiontype']==1){?><span>នៅថ្ងៃទី<?php ///echo $dbparmeter->getNumberInkhmer(date("d",strtotime($row['date_payment'])));?>  ខែ <?php //echo $month[date("m",strtotime($row['date_payment']))];?> ឆ្នាំ   <?php //echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($row['date_payment'])));?></span><?php //}?>
			             				<?php //if($row['last_optiontype']==0){//received plong?><span>បង់បង្គ្រាប់ពេលប្រគល់ប្លង់</span><?php //}?>
			             			</span>	
		             				 <script>
										a ='<?php //echo ($row['principal_permonth']) ?>';
										money_khmer=read_money_in_khmer(a);
										decimalmoney_khmer='<?php //echo substr(number_format($row['principal_permonth'],2),-2);?>';
										str_cent = 'សេន';
										if(decimalmoney_khmer>0){string='និង';}else{string="";str_cent='';}
										
										last_number='<?php //echo substr(number_format($row['principal_permonth'],2),-2);?>';
										
										if(last_number<=0){last_number='';}
										money_khmer = money_khmer+" "+string+" "+read_in_khmer_from_10_to_99(decimalmoney_khmer)+''+read_in_khmer_from_0_to_9(last_number)+''+str_cent;
										dojo.byId('lable_depositkhmer<?php //echo $i;?>').innerHTML=money_khmer;
									</script>
	             					<?php //if($row['ispay_bank']==1){?>
				             				<span class="padding-left"  >&nbsp;&nbsp;&nbsp;<?php //echo $this->keyValue['bank_info'];?></span>
				             			<?php //break;
				             			//}?>
				             			
		             		<?php // }?>
		             			 -->
		             		<?php if(!empty($this->agreement['note_agreement'])){?>
			             		<p>សម្គាល់ ៖
			             			<?php echo $this->agreement['note_agreement'];?>
			             		</p>
		             		<?php }?>
		             		<span>កក់លើកទី<?php echo $dbparmeter->getNumberInkhmer($keytime+1);?></span> 
		             		<?php if ($this->agreement['second_depostit']>0){?>
		             		<span class="value"><strong>$ <?php echo @number_format($this->agreement['second_depostit'],2);?></strong> </span>
			             	<span> ជាអក្សរ <span id="lable_seconddepositkhmer" style="font-family:'Khmer os battambang';"></span>ដុល្លារអាមេរិក</span>
			             	<script>
								a ='<?php echo ($this->agreement['second_depostit']) ?>';
								money_khmer=read_money_in_khmer(a);
								decimalmoney_khmer='<?php echo substr(number_format($this->agreement['second_depostit'],2),-2);?>';
								str_cent = 'សេន';
								if(decimalmoney_khmer>0){string='និង';}else{string="";str_cent='';}
								
								last_number='<?php echo substr(number_format($this->agreement['second_depostit'],2),-2);?>';
								
								if(last_number<=0){last_number='';}
								money_khmer = money_khmer+" "+string+" "+read_in_khmer_from_10_to_99(decimalmoney_khmer)+''+read_in_khmer_from_0_to_9(last_number)+''+str_cent;
								dojo.byId('lable_seconddepositkhmer').innerHTML=money_khmer;
							</script>
							<?php }else{?>
							<span class="value" style="display: inline-block; width: 350px; border-bottom: dashed 1px #000;">&nbsp;</span>
							<?php }?>
		             		<span> នៅថ្ងៃទី  <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['validate_date'])));?></span> <span style="width: 100px;"></span> ខែ  <?php echo $month[date("m",strtotime($this->agreement['validate_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['validate_date'])));?>
		             		<br />
		             		<span>ហើយចំនួនប្រាក់ដែលនៅសល់</span> <span class="value" style="display: inline-block; width: 500px; border-bottom: dashed 1px #000;">&nbsp;</span>
             		<p>
             			<script>
							a_sold ='<?php echo ($this->agreement['price_sold']) ?>';
							money_khmersold=read_money_in_khmer(a_sold);
							decimalmoney_khmersold='<?php echo substr(number_format($this->agreement['price_sold'],2),-2);?>';
							str_centsold = 'សេន';
							if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
							last_number_sold='<?php echo substr(number_format($this->agreement['price_sold'],2),-2);?>';
							
							if(last_number_sold<=0){last_number_sold='';}
							money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
							dojo.byId('lable_pricesoldkhmer').innerHTML=money_khmersold+" ";
							
						</script>
						
						<script>
							a_sold ='<?php echo ($this->first_deposit['recieve_amount']); ?>';
							money_khmersold=read_money_in_khmer(a_sold);
							decimalmoney_khmersold='<?php echo substr(number_format($this->first_deposit['recieve_amount'],2),-2);?>';
							str_centsold = 'សេន';
							if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
							last_number_sold='<?php echo substr(number_format($this->first_deposit['recieve_amount'],2),-2);?>';
							
							if(last_number_sold<=0){last_number_sold='';}
							money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
							dojo.byId('lable_firstpaymentkhmer').innerHTML=money_khmersold+" ";
							
						</script>
             			<script>
             					<?php $second_deposit = ($this->first_deposit['second_depostit'])>0?$this->first_deposit['second_depostit']:0;?>
							a_sold ='<?php echo $second_deposit; ?>';
							money_khmersold=read_money_in_khmer(a_sold);
							decimalmoney_khmersold='<?php echo substr(number_format($second_deposit,2),-2);?>';
							str_centsold = 'សេន';
							if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
							last_number_sold='<?php echo substr(number_format($second_deposit,2),-2);?>';
							
							if(last_number_sold<=0){last_number_sold='';}
							money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
							dojo.byId('lable_secondpaymentkhmer').innerHTML=money_khmersold+" ";
						</script>
             		</p>
             		
             		<p>
             			<span class="margin-left">&nbsp;</span>បើដល់ថ្ងៃកំណត់ភាគីទិញមិនបានប្រគល់ប្រាក់គ្រប់ចំនួនទេ ប្រាក់កក់កន្លងមកនឹងត្រូវបានដាច់ទៅលើក្រុមហ៊ុន។
             			<br />
             			ភាគីលក់សូមសន្យាថា ក្រោយពីទទួលប្រាក់ហើយ មិនកែប្រែតម្លៃ ឬ ប្រែថាមិនលក់ឡើយ ។
             			<br />
             			<span class="margin-left">&nbsp;</span>ក្រែងពុំពិតប្រាកដដូចកិច្ចសន្យាខាងលើ  យើងខ្ញុំសូមផ្តិតមេដៃស្តាំទុកជាភស្តុតាង  ។
             		</p>
             		<p style=" text-align: right;margin-top: -20px;">
             			<!-- ធ្វើនៅ<span class="border_bt  value" style="width:15%;" ></span>ថ្ងៃ..................ខែ............ឆ្នាំ............នព្វស័ក ព.ស២៥......
             			<br /> -->
             			 <?php if ($this->agreement['payment_id']!=1){?>
             			ធ្វើនៅថ្ងៃទី<span class="value" style="min-width:50px;"> <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['agreement_date'])));?></span>ខែ <span class="value" style="min-width:50px;"> <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?></span> ឆ្នាំ <span class="value" style="min-width:50px;"> <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['agreement_date'])));?></span>
             			 <?php }else { //case ដាក់ប្រាក់កក់ យកថ្ងៃលក់?>
             			 ធ្វើនៅថ្ងៃទី<span class="value" style="min-width:50px;"> <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['buy_date'])));?></span>ខែ <span class="value" style="min-width:50px;"> <?php echo $month[date("m",strtotime($this->agreement['buy_date']))];?></span> ឆ្នាំ <span class="value" style="min-width:50px;"> <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['buy_date'])));?></span>
             			 <?php }?>
             		</p>
             		<p>
             			<div style="white-space:nowrap; font-weight:bold; width:24%; text-align: center; display: inline-block;">
             				<span class="value">ស្នាមមេដៃស្តាំអ្នកប្រគល់ប្រាក់</span>
             			</div>
             			<div style="font-weight:bold; width:24%; text-align: center; display: inline-block;">
             				<span class="value">សាក្សីទី១</span>
             			</div>
             			<div style="font-weight:bold; width:24%; text-align: center; display: inline-block;">
             				<span class="value">សាក្សីទី២</span>
             			</div>
             			<div style="white-space:nowrap; font-weight:bold; width:24%; text-align: center; display: inline-block;">
             				<span class="value">ស្នាមមេដៃស្តាំអ្នកទទួលប្រាក់</span>
             			</div>
             			<div style="height: 90px;">
             			</div>
             			<div style="width:24%;text-align: center; display: inline-block;">
             				<span class="border_bt  value" style="width:80%;white-space: nowrap;text-align: center;" >&nbsp;&nbsp;<?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"/".$this->agreement['hname_kh']:"";?>&nbsp;</span>
             			</div>
             			<div style="width:24%; text-align: center; display: inline-block;">
             				<span class="border_bt  value" style="width:80%;" >&nbsp;</span>
             			</div>
             			<div style="width:24%; text-align: center; display: inline-block;">
             				<span class="border_bt  value" style="width:80%;" >&nbsp;</span>
             			</div>
             			<div style="width:24%; text-align: center; display: inline-block;">
             				<span class="border_bt  value" style="width:80%;" >&nbsp;<?php echo $this->agreement['user_name'];?><?php //echo $this->agreement['project_manager_namekh'];?></span>
             			</div>
             		</p>
             	</td>
             </tr>
			</tfoot>
        </table>
        </div>
        <?php if ($this->agreement['payment_id']!=1){?>
        <div class="pages-break">
        	<div class="watermark"></div>
	        <table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="padding:0;margin:0;border:0px;" >
	        	<tr>
	                <td width="30%" valign="top">
	                	<?php $imagelogo = $this->baseUrl()."/images/logo.jpg";
		                	if (!empty($this->agreement['project_logo'])){
		                		$imagelogo = $this->baseUrl()."/images/projects/".$this->agreement['project_logo'];
		                	}
		                	?>
	                	<img src="<?php echo $imagelogo;?>" style="max-width:100%; height: 85px; margin-top: 20px;">
	                </td>
	                <td width="40%" align="center">
	                <span style="text-align:center; line-height:28px; font-size:17px;font-family:'Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា</span>
	                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
	                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.jpg" height="25px"></span>
	                <span style="margin-bottom:10px;text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("កិច្ចសន្យាលក់ដី");?></span>
	                <td width="30%" valign="top" align="right">
	                	<br /><br /><br />
	                	<span style="text-align:center; line-height:28px; font-size:17px;font-family:'Times New Roman','Khmer OS Battambang';">N<sup>o</sup></span> <span style="width:100px; display: inline-block; border-bottom: dashed 1px #000;"></span>
	                </td>
	             </tr> 
	             <tr>
	             	<td colspan="3">
	             		<p style="font-family:'Khmer OS Battambang','Times New Roman',; text-align:justify; line-height:24px; font-size:14px; font-weight: normal !important;">
	             			<?php $certificat_No = "០០០៣៣៧២០";?>
	             			<span class="margin-left">&nbsp;</span><strong><?php echo $branch_title;?></strong> ដែលមានវិញ្ញាបនបត្របញ្ជាក់ការចុះបញ្ជីនៅក្រសួងពាណិជ្ជកម្មលេខ <strong><?php echo $dbparmeter->getNumberInkhmer($certificat_No);?></strong> តំណាងស្របច្បាប់ដោយលោក <span class="value" style="min-width:135px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['project_manager_namekh'];?></span> 
	             			ភេទ<span class="value" style="min-width:10px;"><?php echo $this->agreement['manager_sex'];?></span> 
	             			សញ្ជាតិ<span class="value" style="min-width:10px;"><?php echo $this->agreement['project_manager_nationality'];?></span> 
	             			កាន់អត្តសញ្ញាណប័ណ្ណលេខ <span class="value" style="min-width:60px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['project_manager_nation_id']);?></span> 
	             			អាសយដ្ឋាន<?php echo $this->agreement['project_manager_p_current_address'];?>
	             			<?php if (!empty($this->agreement['w_manager_namekh'])){?>
	             			 និងឈ្មោះ <span class="value" style="min-width:50px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['w_manager_namekh'];?></span> 
	             			ភេទ  <span class="value" style="min-width:10px;"><?php echo $this->agreement['sc_manager_sex'];?></span>
	             			សញ្ជាតិ <span class="value" style="min-width:10px;"><?php echo $this->agreement['w_manager_nationality'];?></span>
	             			កាន់អត្តសញ្ញាណប័ណ្ណលេខ <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_manager_nation_id'];?></span>
	             			អាសយដ្ឋាន <span class="value" style="min-width:150px;"><?php echo $this->agreement['w_current_address'];?></span>
	             			<?php }?> ។ បានព្រមព្រៀងគ្នាលក់ <span class="value" style="min-width:20px;"><?php echo $this->agreement['property_type_kh'];?></span> មួយកន្លែង ដែលមានលេខ<span class="value"><?php echo $this->agreement['property_title'];?></span> ទំហំ <span class="value" style="min-width:70px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['land_size']);?></span> ម៉ែត្រក្រឡា 
	             			ស្ថិតនៅ<?php echo $this->agreement['project_location'];?>។
	             			<span style="display:block; width:100%; font-family:'Khmer OS Muol Light'; text-align: center; font-weight: 200;">ដែលមានព្រំប្រទល់ដូចខាងក្រោម:</span>
	             			<span style=" margin-left: 50px;"></span>- ខាងជើងទល់នឹង <span class="value" style="min-width:150px;"><?php echo $this->agreement['border_north'];?></span> - ខាងត្បូងទល់នឹង 	<span class="value" style="min-width:150px;"><?php echo $this->agreement['border_south'];?></span>
	             			<br />
	             			<span style=" margin-left: 50px;"></span>- ខាងលិចទល់នឹង<span class="value" style="min-width:150px;"><?php echo $this->agreement['border_west'];?></span> - ខាងកើតទល់នឹង <span class="value" style="min-width:150px;"><?php echo $this->agreement['border_east'];?></span> 
	             			<br />
	             			<span class="margin-left">&nbsp;</span>បានលក់ជូនទៅឈ្មោះ <span class="value" style="font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['client_namekh'];?></span> 
	             			ភេទ <span class="value" style="min-width:10px;"><?php echo $this->agreement['sexKh'];?></span>
		             		អាយុ  <span class="value" style="min-width:10px;"><?php if (!empty($this->agreement['dob'])){ echo $dbparmeter->getNumberInkhmer(date("Y") - date("Y",strtotime($this->agreement['dob'])));}?></span> ឆ្នាំ
		             		សញ្ជាតិ <span class="value" style="min-width:10px;"><?php echo $this->agreement['client_nationality'];?></span> 
		             		<?php if(!empty($this->agreement['hname_kh'])){?>
			             		ព្រមទំាងឈ្មោះ <span class="value" style="min-width:150px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['hname_kh'];?></span> ភេទ  <span class="value" style="min-width:40px;"><?php echo $this->agreement['client_buywith_sex'];?></span>
			             		អាយុ <span class="value" style="min-width:30px;"><?php if (!empty($this->agreement['w_client_dob_buywith'])){ echo $dbparmeter->getNumberInkhmer(date("Y") - date("Y",strtotime($this->agreement['w_client_dob_buywith'])));}?></span> ឆ្នាំ
			             		សញ្ជាតិ <span class="value" style="min-width:20px;"><?php echo $this->agreement['w_client_nationality'];?></span>
	             			<?php }?> 
	             			មានទីលំនៅបច្ចុប្បន្ន ភូមិ <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_village_kh'];?></span> ឃុំ/សង្កាត់ <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_commune_kh'];?></span> ស្រុក/ខណ្ឌ <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_districtkh'];?></span> ខេត្ត/ក្រុង  <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_province_kh'];?></span> 
	             			ទូរស័ព្ទលេខ <span class="value" style="min-width:20px;"><?php echo $this->agreement['phone'];?></span>។
	             			<br />
	             			
	             		
	             		</p>
	             		<p>
	             			<span style=" padding-left: 50px; min-width: 29%; display: inline-block;">ភាគីទាំងពីរបានឯកភាពគ្នាក្នុងតម្លៃ  </span> 
	             				<span class="value" style="text-align:left; padding-left: 10px;"><strong>$ <?php echo number_format($this->agreement['price_sold'],2);?></strong> </span><span> <span id="lable_pricesoldkhmer" style="font-family:'Khmer os battambang';"></span>ដុល្លារអាមេរិក</span>
	             			<br />
	             			<?php $dbs = new Loan_Model_DbTable_DbLandpayment();
			             			$resultdeposit = $dbs->getDepositFirstPaymentMoney($this->agreement['id']);
			             			$start_id=0;
			             			$paid_amount=0;
			             			$rowpaid = $dbs->getPaymentPayoff($this->agreement['id']);
			             			$paid_payoff = $rowpaid['outstanding'];
			             			$paid = 0;
			             			$keytime=0;
			             		?>
			             		<?php //if(!empty($resultdeposit) AND $this->agreement['is_reschedule']==1){
			             			if(!empty($resultdeposit)){?><!-- ប្រាក់កក់ -->
		             				<?php foreach($resultdeposit as $keydeposite =>$rsdeposite){ $keytime++;?>
		             				<span style=" display: inline-block;white-space: nowrap;">
		             				<?php 
		             				$labelpaid="ភាគីទិញបានកក់ប្រាក់លើកទី";
		             				if ($keytime>1){
		             					$labelpaid="កក់លើកទី";
			             			}?>
		             				<?php echo $labelpaid.$dbparmeter->getNumberInkhmer($keytime);?> ចំនួន
			             				<span class="value"><strong>$ <?php echo @number_format($rsdeposite['total_principal_permonthpaid'],2);?></strong> <span id="lable_depositpaid<?php echo $keydeposite+1;?>" style="font-family:'Khmer os battambang';"></span>ដុល្លារអាមេរិក</span> 
			             				<span>នៅថ្ងៃទី  <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($rsdeposite['date_input'])));?>  ខែ  <?php echo $month[date("m",strtotime($rsdeposite['date_input']))];?>  ឆ្នាំ  <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($rsdeposite['date_input'])));?></span>
		             				</span>
		             				<script>
														a ='<?php echo ($rsdeposite['total_principal_permonthpaid']) ?>';
														money_khmer=read_money_in_khmer(a);
														decimalmoney_khmer='<?php echo substr(number_format($rsdeposite['total_principal_permonthpaid'],2),-2);?>';
														str_cent = 'សេន';
														if(decimalmoney_khmer>0){string='និង';}else{string="";str_cent='';}
														
														last_number='<?php echo substr(number_format($rsdeposite['total_principal_permonthpaid'],2),-2);?>';
														
														if(last_number<=0){last_number='';}
														money_khmer = money_khmer+" "+string+" "+read_in_khmer_from_10_to_99(decimalmoney_khmer)+''+read_in_khmer_from_0_to_9(last_number)+''+str_cent;
														dojo.byId('lable_depositpaid<?php echo $keydeposite+1;?>').innerHTML=money_khmer;
													</script>
	             				<?php 
									$paid_amount = $paid_amount+$rsdeposite['total_principal_permonthpaid'];
		             				}
			             		echo "<br />";
			             		}?>
		             			<?php 
			             			$i=0; $numrow = 0;
			             			if (!empty($this->sale_schedule))  foreach ($this->sale_schedule as $key=> $row){$i++;  ?>
			             			<?php 
			             			if($row['is_completed']==1 AND $this->agreement['is_reschedule']==3){continue;}
			             			$paid = $paid+$row['principal_permonth'];?>             	
			             			<?php if($key==0){?>
				             		<?php
				             			if($row['date_payment']==$this->agreement['buy_date'] AND $paid_amount==$row['principal_permonth'] ){
				             				continue;
				             			}
			             				$paidbefore = $row['principal_permonth']-$paid_amount;
			             				if(strlen($paidbefore)<=3){$row['principal_permonth']=number_format($paidbefore,2);}
			             				else{
			             					$row['principal_permonth'] = ($paidbefore);
			             				}
			             			}$keytime++;?>
			             			<?php 
			             				$numrow=$numrow+1;?>
			             				<span style="display: inline-block;white-space: nowrap;">
			             						បង់ប្រាក់លើកទី<?php echo $dbparmeter->getNumberInkhmer($keytime);?>  ចំនួន
				             				<span class="value"><strong>$ <?php echo @number_format($row['principal_permonth'],2);?></strong> </span>
				             				<span> ជាអក្សរ <span id="lable_depositkhmer<?php echo $i;?>" style="font-family:'Khmer os battambang';"></span>ដុល្លារអាមេរិក</span>
				             				<?php if($row['last_optiontype']==1){?><span>នៅថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($row['date_payment'])));?> ខែ <?php echo $month[date("m",strtotime($row['date_payment']))];?> ឆ្នាំ   <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($row['date_payment'])));?></span><?php }?>
				             				<?php if($row['last_optiontype']==0){//received plong?><span>បង់បង្គ្រាប់ពេលប្រគល់ប្លង់</span><?php }?>
				             			</span>	
			             				 <script>
											a ='<?php echo ($row['principal_permonth']) ?>';
											money_khmer=read_money_in_khmer(a);
											decimalmoney_khmer='<?php echo substr(number_format($row['principal_permonth'],2),-2);?>';
											str_cent = 'សេន';
											if(decimalmoney_khmer>0){string='និង';}else{string="";str_cent='';}
											
											last_number='<?php echo substr(number_format($row['principal_permonth'],2),-2);?>';
											
											if(last_number<=0){last_number='';}
											money_khmer = money_khmer+" "+string+" "+read_in_khmer_from_10_to_99(decimalmoney_khmer)+''+read_in_khmer_from_0_to_9(last_number)+''+str_cent;
											dojo.byId('lable_depositkhmer<?php echo $i;?>').innerHTML=money_khmer;
										</script>
		             					<?php if($row['ispay_bank']==1){?>
					             				<!-- <span class="padding-left"  >&nbsp;&nbsp;&nbsp;<?php //echo $this->keyValue['bank_info'];?></span> -->
					             			<?php break;
					             			}?>
					             			
			             		<?php  }?>
			             		<?php if(!empty($this->agreement['note_agreement'])){?>
				             		<p>សម្គាល់ ៖
				             			<?php echo $this->agreement['note_agreement'];?>
				             		</p>
			             		<?php }?>
			             		<br />
			             		<span>ហើយចំនួនប្រាក់ដែលនៅសល់</span> <span class="value" style="display: inline-block; width: 500px; border-bottom: dashed 1px #000;">&nbsp;</span>
	             		<p>
	             			<script>
								a_sold ='<?php echo ($this->agreement['price_sold']) ?>';
								money_khmersold=read_money_in_khmer(a_sold);
								decimalmoney_khmersold='<?php echo substr(number_format($this->agreement['price_sold'],2),-2);?>';
								str_centsold = 'សេន';
								if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
								last_number_sold='<?php echo substr(number_format($this->agreement['price_sold'],2),-2);?>';
								
								if(last_number_sold<=0){last_number_sold='';}
								money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
								dojo.byId('lable_pricesoldkhmer').innerHTML=money_khmersold+" ";
								
							</script>
							
							<script>
								a_sold ='<?php echo ($this->first_deposit['recieve_amount']); ?>';
								money_khmersold=read_money_in_khmer(a_sold);
								decimalmoney_khmersold='<?php echo substr(number_format($this->first_deposit['recieve_amount'],2),-2);?>';
								str_centsold = 'សេន';
								if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
								last_number_sold='<?php echo substr(number_format($this->first_deposit['recieve_amount'],2),-2);?>';
								
								if(last_number_sold<=0){last_number_sold='';}
								money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
								dojo.byId('lable_firstpaymentkhmer').innerHTML=money_khmersold+" ";
								
							</script>
	             			<script>
	             					<?php $second_deposit = ($this->first_deposit['second_depostit'])>0?$this->first_deposit['second_depostit']:0;?>
								a_sold ='<?php echo $second_deposit; ?>';
								money_khmersold=read_money_in_khmer(a_sold);
								decimalmoney_khmersold='<?php echo substr(number_format($second_deposit,2),-2);?>';
								str_centsold = 'សេន';
								if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
								last_number_sold='<?php echo substr(number_format($second_deposit,2),-2);?>';
								
								if(last_number_sold<=0){last_number_sold='';}
								money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
								dojo.byId('lable_secondpaymentkhmer').innerHTML=money_khmersold+" ";
							</script>
	             		</p>
	             		
	             		<p>
	             			<span class="margin-left">&nbsp;</span>បើដល់ថ្ងៃកំណត់ភាគីទិញមិនបានប្រគល់ប្រាក់គ្រប់ចំនួនទេ ប្រាក់កក់កន្លងមកនឹងត្រូវបានដាច់ទៅលើក្រុមហ៊ុន។ ភាគីលក់សូមសន្យាថា ក្រោយពីទទួលប្រាក់ហើយ មិនកែប្រែតម្លៃ ឬ ប្រែថាមិនលក់ឡើយ ។ ក្នុងករណីការអនុវត្តន៍ផ្ទុយ ពីនេះ ខ្ញុំបាទ/នាងខ្ញុំសុខចិត្តសងប្រាក់..................ដងនៃប្រាក់ដែលបានបង់កន្លងមក។ ម៉្យាងវិញទៀត បើថ្ងៃក្រោយ មានជនដ៏ទៃណា ទោះក្នុងគ្រួសារ ឬក្រៅគ្រួសារមកតវ៉ាថាដីនេះជាសម្បិត្តិរបស់ខ្លួន ខ្ញុំបាទ/នាងខ្ញុំសូមទទួលខុសត្រូវចំពោះ មុខច្បាប់ជាធរមាន។
	             			<br />
	             			<span class="margin-left">&nbsp;</span>ក្រែងពុំពិតប្រាកដដូចកិច្ចសន្យាខាងលើ  យើងខ្ញុំសូមផ្តិតមេដៃស្តាំទុកជាភស្តុតាង  ។
	             		</p>
	             		<p style=" text-align: right;margin-top: -20px;">
	             			<!-- ធ្វើនៅ<span class="border_bt  value" style="width:15%;" ></span>ថ្ងៃ..................ខែ............ឆ្នាំ............នព្វស័ក ព.ស២៥......
	             			<br /> -->
	             			ធ្វើនៅថ្ងៃទី<span class="value" style="min-width:50px;"> <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['agreement_date'])));?></span>ខែ <span class="value" style="min-width:50px;"> <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?></span> ឆ្នាំ <span class="value" style="min-width:50px;"> <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['agreement_date'])));?></span>
	             		</p>
	             		<p>
	             			<div style="white-space:nowrap; font-weight:bold; width:24%; text-align: center; display: inline-block;">
	             				<span class="value">ស្នាមមេដៃស្តាំអ្នកប្រគល់ប្រាក់</span>
	             			</div>
	             			<div style="font-weight:bold; width:24%; text-align: center; display: inline-block;">
	             				<span class="value">សាក្សីទី១</span>
	             			</div>
	             			<div style="font-weight:bold; width:24%; text-align: center; display: inline-block;">
	             				<span class="value">សាក្សីទី២</span>
	             			</div>
	             			<div style="white-space:nowrap; font-weight:bold; width:24%; text-align: center; display: inline-block;">
	             				<span class="value">ស្នាមមេដៃស្តាំអ្នកទទួលប្រាក់</span>
	             			</div>
	             			<div style="height: 90px;">
	             			</div>
	             			<div style="width:24%;text-align: center; display: inline-block;">
	             				<span class="border_bt  value" style="width:80%;white-space: nowrap;text-align: center;" >&nbsp;&nbsp;<?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"/".$this->agreement['hname_kh']:"";?>&nbsp;</span>
	             			</div>
	             			<div style="width:24%; text-align: center; display: inline-block;">
	             				<span class="border_bt  value" style="width:80%;" >&nbsp;</span>
	             			</div>
	             			<div style="width:24%; text-align: center; display: inline-block;">
	             				<span class="border_bt  value" style="width:80%;" >&nbsp;</span>
	             			</div>
	             			<div style="width:24%; text-align: center; display: inline-block;">
	             				<span class="border_bt  value" style="width:80%;" >&nbsp;<?php echo $this->agreement['user_name'];?><?php //echo $this->agreement['project_manager_namekh'];?></span>
	             			</div>
	             		</p>
	             	</td>
	             </tr>
				</tfoot>
	        </table>
        </div>
        <?php }?>
    </td>	
</tr>
</table>
</div>