<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$day = array(
		"Mon" =>'ច័ន្ច',
		"Tue" =>'អង្គារ',
		"Wed" =>'ពុធ',
		"Thu" =>'ព្រហស្បតិ័',
		"Fri" =>'សុក្រ',
		"Sat" =>'សៅរ៍',
		"Sun" =>'អាទិត្យ',
		);
$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មិនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កញ្ញា","08"=>"កក្កដា","09"=>"សីហា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
$base_url = Application_Form_FrmMessage::getUrl("/");

?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title><?php echo $tr->translate("AGREEMENT");?></title>
<style>
	.reff{ font-size: 20px !important; line-height:39px !important;}
	tr td h2,p,
	pre{ font-size: 20px !important; line-height:25px !important;}
span{ line-height:35px !important;}
</style>
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint">
    	 	<style>
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Khmer OS Battambang';
						}
						th{padding: 5px;}
						span.value{   line-height: 15px !important;padding-bottom:4x;  display: inline-block; border-bottom: 1px #000 dotted;text-align: center;}
						span.child {display:block; margin-left:25px;}
						span{ line-height:28px;}
					</style>
        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="padding:0;margin:0;border:0px;" >
        	<tr>
                <td width="30%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" style="max-width:100%;height: 130px; "></td>
                <td width="40%" align="center">
                <span style="text-align:center; line-height:28px; font-size:16px;font-family:'Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា</span>
                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light'"><label><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></label></span>
                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:14px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.JPG" height="25px"></span>
                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; font-family:'Khmer OS Muol Light';margin-top: 20px;"><label><?php echo $tr->translate("កិច្ចសន្យាលក់-ទិញដីឡូតិ៍");?></label></span>
                <td width="30%"></td>
             </tr> 
             <tr>
             	<td colspan="3">
             		<p style="font-family: 'Times New Roman','Khmer OS Battambang'; text-align:justify; line-height:24px; font-size:14px;">
             			<span style="width: 100%; display: block;"> <span style=" font-family:'Khmer OS Muol Light';font-weight:200;">កិច្ចសន្យាលក់-ទិញដីឡូតិ៍ </span> នេះ ត្រូវបានធ្វើឡើងនៅព្រែកលួង ថ្ងៃទី <?php echo date("d",strtotime($this->agreement['agreement_date']));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo date("Y",strtotime($this->agreement['agreement_date']));?> រវាង :</span>
             			<span style="font-family:'Khmer OS Muol Light';font-weight:200;">-អ្នកលក់ដីឡូតិ៍ ៖  <?php echo $this->keyValue['party_a'];?></span> ភេទ <?php echo $this->keyValue['party_a_sex'];?> ឆ្នាំកំណើត <?php echo $this->keyValue['party_a_dob'];?> ជនជាតិ<?php echo $this->keyValue['party_a_nationality'];?> កាន់អត្តសញ្ញាណប័ណ្ណលេខ:<?php echo $this->keyValue['party_a_nation_id'];?></span> 
						មានលំនៅ<?php echo $this->agreement['project_manager_p_current_address'];?> ហៅថា <span style=" font-family:'Khmer OS Muol Light';font-weight:200;">“អ្នកលក់”</span> ដែលមានតំណាងចុះកិច្ចសន្យាដោយឈ្មោះ  <span style=" font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['w_manager_namekh'];?></span> តួនាទី 
						<span style=" font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['w_manager_position'];?></span> ទូរស័ព្ទ: <span style="font-weight:200; text-align:left; white-space: nowrap; text-align: left;"><?php echo $this->agreement['w_manager_tel'];?></span>
						 និងឈ្មោះ <span style="font-weight:200; text-align:left; white-space: nowrap; text-align: left;font-family:'Khmer OS Muol Light';"><?php echo $this->agreement['w_managername1'];?></span>
						 តួនាទី <span style=" font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['w_manager_position1'];?></span> ទូរស័ព្ទ: <span style="font-weight:200; text-align:left; white-space: nowrap; text-align: left;"><?php echo $this->agreement['w_manager_tel1'];?></span>
						។</p>
             			<span style="text-align:center; width: 100%; display: inline-block;white-spacing: 15px;margin-top:-15px;font-size:14px; font-family:'Khmer OS Muol Light';font-weight:200;"> និង</span>
             			<p style="font-family: 'Times New Roman','Khmer OS Battambang'; text-align:justify; line-height:24px; font-size:14px;margin-top: -2px;">
             			<span style="width: 100%; display: block;">
							<span style=" font-family:'Khmer OS Muol Light';font-weight:200;">-អ្នកទិញដីឡូតិ៍ ៖</span>ឈ្មោះ <span class="value" style="min-width:200px;font-weight:190;"><?php echo $this->agreement['client_namekh'];?></span> ភេទ <span class="value" style="width:50px;font-weight:200;"><?php echo $this->agreement['client_sex'];?></span> ឆ្នាំកំណើត <span class="value" style="width:90px;font-weight:200;"><?php if(!empty($this->agreement['client_dob'])){ echo date("d/m/Y",strtotime($this->agreement['client_dob']));}?></span> ជាជនជាតិ <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_nationality'];?></span> កាន់អត្តសញ្ញាណប័ណ្ណលេខ <span class="value" style="width:100px;"><?php echo $this->agreement['client_nation_id'];?></span>
							<?php if(!empty($this->agreement['with_client_name'])){?>និងឈ្មោះ <span class="value" style="width:130px;"><?php echo $this->agreement['with_client_name'];?></span> ភេទ  <span class="value" style="width:50px;font-weight:200;"><?php echo $this->agreement['with_client_sex'];?></span> ឆ្នាំកំណើត <span class="value" style="min-width:80px;font-weight:200;"><?php echo date("d/m/Y",strtotime($this->agreement['dob_buywith']));?></span> ជាជនជាតិ <span class="value" style="width:30px;"><?php echo $this->agreement['with_client_nationlity'];?></span> កាន់អត្តសញ្ញាណប័ណ្ណលេខ <span class="value" style="width:100px;"><?php echo $this->agreement['rid_no'];?></span><?php }?>
							មានទីលំនៅផ្ទះលេខ: <span class="value" style="min-width:55px;"><?php echo $this->agreement['client_house_no'];?></span> ផ្លូវលេខ  <span class="value" style="min-width:55px;"><?php echo $this->agreement['client_street'];?></span> ឃុំ-សង្កាត់  <span class="value" style="width:150px;"><?php echo $this->agreement['client_commune_kh'];?></span> ស្រុក-ខណ្ឌ <span class="value" style="width:130px;"><?php echo $this->agreement['client_districtkh'];?></span>
							ខេត្ត-ក្រុង <span class="value" style="width:100px;"><?php echo $this->agreement['client_province_kh'];?></span>ហៅថា  <span style=" font-family:'Khmer OS Muol Light';font-weight:200;">“អ្នកទិញ”</span> ។
							ទូរស័ព្ទលេខ:<span class="value" style="min-width:150px;"><?php echo $this->agreement['client_phone'];?></span>។
						</span>
						<span style="width: 100%; display: block;">
							<span class="child">ភាគីទាំងពីរបានព្រមព្រៀងគ្នាផ្តិតហត្ថលេខាលើកិច្ចសន្យានេះ តាមខ្លឹមសារ និងលក្ខខណ្ឌដូចខាងក្រោម ៖</span>
							<span style=" font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ១. ការលក់ -ទិញដីឡូតិ៍៖ </span><span style="font-weight:700;">អ្នកទិញ</span> យល់ព្រមទិញពី<span style="font-weight:700;">អ្នកលក់</span> ហើយ<span style="font-weight:700;">អ្នកលក់</span> យល់ព្រមលក់ និងផ្ទេរសិទិ្ធជូន <span style="font-weight:700;">អ្នកទិញ</span>
							នូវ ៖ ប្រភេទដីឡូត៌ៈ <span class="value" style="width:90px;"><?php echo $this->agreement['property_title'];?></span> ផ្លូវលេខៈ <span class="value" style="width:90px;"><?php echo $this->agreement['property_street'];?></span> ដែលមានទំហំ៖   ទទឹង <span class="value" style="width:75px;"><?php echo $this->agreement['property_width'];?></span> ម៉ែត្រ, បណ្ដោយ<span class="value" style="width:75px;"><?php echo $this->agreement['property_height'];?></span> ម៉ែត្រ,
							ទំហំសរុប  <span class="value" style="min-width:90px;"><?php echo number_format($this->agreement['property_size'],2);?></span> ម៉ែត្រការ៉េ ដែលមានទីតាំងស្ថិតនៅ <?php echo $this->agreement['project_location'];?> (ហៅថា <span style=" font-family:'Khmer OS Muol Light';font-weight:200;">“អចលនទ្រព្យ”</span> )។
						</span>
						<span style="width: 100%; display: block;">
							<span style=" font-family:'Khmer OS Muol Light';font-weight:200; width: 100%; display: inline-block;">ប្រការ២. តំលៃលក់-ទិញ និង នីតិវិធីទូទាត់ ៖ </span>
							*តំលៃលក់-ទិញដីឡូតិ៍(អចលនទ្រព្យ)គឺ US$ <span class="value" style="width:110px;font-weight: bold;">
							
							<?php echo number_format($this->agreement['price_sold'],2);?></span>(<span class="value" style=" text-align:left;">ជាអក្សរ.<label id="lable_pricekhmer"></label></span>)។</span>
							*<span style="font-weight:700;">អ្នកទិញ </span>ត្រូវប្រគល់ប្រាក់ថ្លៃទិញដីឡូតិ៍<span style="font-weight:700;">ជូនអ្នកលក់ អោយបានទៀងទាត់</span> តាមដំណាក់កាលនីមួយៗដូចមានក្នុងតារាង បង់ប្រាក់ដែលភ្ជាប់មកជាមួយ ។ 
							<span style="color: #04294e;">។ (បញ្ជាក់: ការបង់រំលោះក្នុងតារាង គឺពុំមានគិតការប្រាក់ទេ) ។</span>
							<script>
							a ='<?php echo ($this->agreement['price_sold']) ?>';//;dojo.number.format(b);
							money_khmer=read_money_in_khmer(a);
							dojo.byId('lable_pricekhmer').innerHTML=money_khmer+" ដុល្លារគត់";
							</script>
						</span>
						<span style="width: 100%; display: block;">
							<span style=" font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ៣. ការបំពានកាតព្វកិច្ចបង់ប្រាក់ ៖ </span>ក្នុងករណី <span style="font-weight:700;">អ្នកទិញ</span>មិនបានបង់ប្រាក់រំលោះតាមកាលកំណត់ក្នុងការទូទាត់ប្រាក់ថ្លៃទិញដីឡូតិ៍ តាមតារាងបង់ប្រាក់ដែលភ្ជាប់ជាមួយ មិនអោយលើសពី 15 (ដប់ប្រាំ) ថ្ងៃ ។ 
							ករណីលើសពីដប់ប្រាំថ្ងៃត្រូវពិន័យ ១០(ដប់)ដុល្លា ក្នុងមួយថ្ងៃ ប្រសិនបើការយឺតយ៉ាវលើសពី៣០(សាមសិប)ថ្ងៃ នោះទឹកប្រាក់ដែល <span style="font-weight:700;">អ្នកទិញ</span> បានបង់ទាំងអស់ នឹងត្រូវបានជាកម្មសិទ្ធិរបស់<span style="font-weight:700;">អ្នកលក់</span>ហើយកិច្ចសន្យានេះនឹងត្រូវរំលាយចោលជាស្វ័យប្រវត្តិ។ ក្នុងករណីនេះ 
							<span style="font-weight:700;">អ្នកលក់</span>មានសិទ្ធិចាត់ចែងលក់ដីឡូតិ៍នេះកំណត់ក្នុងប្រការ១ ខាងលើ អោយទៅអ្នកដទៃបានគ្រប់ពេលវេលា ដោយ<span style="font-weight:700;">អ្នកទិញ</span>គ្មានសិទ្ធិតវ៉ាឡើយ ហើយ<span style="font-weight:700;">អ្នកទិញ</span> ត្រូវផ្តិតមេដៃលើលិខិតផ្ទេរសិទ្ធិកាន់កាប់ដីឡូតិ៍ត្រលប់មក<span style="font-weight:700;">អ្នកលក់</span>វិញ (ករណីលិខិតផ្ទេរសិទ្ធិកាន់កាប់       ដីឡូតិ៍បានផ្ទេរមកឈ្មោះ<span style="font-weight:700;">អ្នកទិញ</span> រួចហើយនោះ)។
						</span>
						<span style="width: 100%; display: block;">
							<span style=" font-family:'Khmer OS Muol Light';font-weight:200; width: 100%; display: inline-block;">ប្រការ៤. ករណីយកិច្ច និង កិច្ចធានារបស់ភាគី ៖  </span>
							<span class="child">៤.១ <span style="font-weight:700;">អ្នកលក់</span> មានសិទិ្ធពេញច្បាប់ ដើម្បីផ្ទេរសិទ្ធិកាន់កាប់ប្រើប្រាស់អចលនវត្ថុ(ដីឡូតិ៍) មានបញ្ជាក់ពីអាជ្ញាធរ ភូមិ, ឃុំ
								និងស្រុក ទៅ<span style="font-weight:700;">អ្នកទិញ</span>  ក្រោយពេល<span style="font-weight:700;">អ្នកទិញ</span> បានបង់ប្រាក់ថ្លៃទិញដីឡូតិ៍បានលើសពី ៥០% (ហាសិបភាគរយ)
								ហើយ ឯកសារផ្ទេរសិទ្ធិកាន់កាប់ប្រើប្រាស់អចលនវត្ថុ(ដីឡូតិ៍) ត្រូវរក្សាទុកនៅ<span style="font-weight:700;">អ្នកលក់</span> សិន(អាចថតចំលងជូនអ្នកទិញបាន) អ្នកទិញ នឹងទទួលបាន លិខិតផ្ទេរសិទ្ធិកាន់កាប់ប្រើប្រាស់អចលនវត្ថុ(ដីឡូតិ៍)ច្បាប់ដើម នៅក្រោយ
								ពេល<span style="font-weight:700;">អ្នកទិញ</span> បានបង់ប្រាក់គ្រប់ចំនួន ដោយតំលៃសេវាផ្ទេរសិទ្ធិនេះ ជាបន្ទុកចំណាយរបស់អ្នកលក់។ រាល់ការបង់ពន្ធជាបន្ទុករបស់<span style="font-weight:700;">អ្នកទិញ</span> ។
							</span>
							<span class="child">
								៤.២ ករណី<span style="font-weight:700;">អ្នកទិញ</span>កែប្រែមិនទិញវិញ នោះប្រាក់ថ្លៃទិញដីឡូតិ៍ដែលបានបង់ជូនអ្នកលក់រួច មិនត្រូវបង្វិលជូនអ្នកទិញ     ឡើយ។ 
							</span>
							<span class="child">
								៤.៣ ករណី<span style="font-weight:700;">អ្នកលក់</span>កែប្រែមិនលក់វិញ ត្រូវប្រគល់ប្រាក់ទៅអោយអ្នកទិញវិញ ស្មើនឹងប្រាក់ដែលបានទទួលគុណនឹង ៣ដង។
							</span>
							<span class="child">
								៤.៤  <span style="font-weight:700;">អ្នកលក់</span>ធានារៀបចំដីឡូតិ៍, ប្រព័ន្ធទឹក, ភ្លើង, លូ និងផ្លូវ អោយបានរួចរាល់ក្នុងរយះពេល៣៦ខែ គិតចាប់ពីថ្ងៃធ្វើកិច្ចសន្យា ជាកំណត់ជូនអ្នកទិញ។ បញ្ជាក់៖ អ្នកលក់ទទួលបន្ទុករៀបចំ ទឹក ភ្លើង លូ តែប្រព័ន្ធមេប៉ុណ្ណោះ ចំពោះការតភ្ជាប់ទៅកាន់ដីឡូតិ៍នីមួយៗជាបន្ទុករបស់អ្នកទិញម្នាក់ៗ។ ក្នុងករណីដល់ពេលកំណត់ខាងលើ អ្នកលក់មិនបានបញ្ចប់តាមគោលការណ៍ នោះអ្នកលក់ធានាសងសំណងជូនអ្នកទិញវិញ ស្មើនឹង 50ភាគរយនៃចំនួនទឹកប្រាក់ដែលបានបង់រួច។ ការរៀបចំខាងលើមិនអាចដំណើរការបានដោយសារតែ<span style="font-weight:700;">អ្នកទិញ</span>មិនបានបង់ប្រាក់តាមកាលកំណត់ ឬករណីប្រធានសក្តិ ដូចជាទឹកជំនន់ រញ្ជួយដី វិបត្តិ នយោបាយ អស្ថេរភាពសង្គមកើតឡើង ដែលអាចបណ្តាលអោយមានការរាំងស្ទះដល់ដំណើរការសាងសង់ ទើបមានការពន្យាពេល។ ហើយការយឺតយ៉ាវបែបនេះមិនផ្តល់សំណងជូនអ្នកទិញនោះទេ។ 
							</span>
							<span class="child">
							៤.៥	<span style="font-weight:700;">អ្នកទិញ</span> មិនអាចសាងសង់ផ្ទះ, អគារ ដែលខុសពីការកំណត់របស់អ្នកលក់ និងអាជ្ញាធរបានឡើយ លុះត្រាតែមានការឯកភាពជាលាយលក្ខណ៍អក្សរពី<span style="font-weight:700;">អ្នកលក់</span> និងអាជ្ញាធរ ជាមុនសិន។
							</span>
						</span>
             			<span style="width: 100%; display: block;">
							<span style=" font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ៥. ការស្នងបន្ត ៖</span>រាល់សិទ្ធិ និងករណីយកិច្ចទាំងអស់របស់<span style="font-weight:700;">អ្នកទិញ</span> ដែលមានក្នុងកិច្ចសន្យានេះ នឹងមានអានុភាពផង
							ដែរចំពោះទាយាទ អ្នកស្នងបន្ត និង អ្នកទទួលសិទ្ធិរបស់<span style="font-weight:700;">អ្នកទិញ</span> តាមរយៈលិខិតជាលាយលក្ខណ៍អក្សរមានសាក្សីដឹងឮ  ឬមេធាវី
							បញ្ជាក់។ ដោយឡែក ប្រសិនបើមានហេតុការណ៍អាក្រក់ណាមួយកើតឡើងចំពោះ<span style="font-weight:700;">អ្នកលក់</span> នោះសិទិ្ធ និងករណីយកិច្ចទាំងអស់
							របស់<span style="font-weight:700;">អ្នកលក់</span> នឹងត្រូវបានទៅលើទាយាទ ឬ អ្នកស្នងបន្ត ឬក៏អ្នកទទួលសិទ្ធិរបស់<span style="font-weight:700;">អ្នកលក់</span> តាមរយៈលិខិតជាលាយលក្ខណ៍អក្សរមានសាក្សីដឹងឮ  ឬមេធាវីបញ្ជាក់ដឹងឮ។
						</span>
						<span style="width: 100%; display: block;">
							<span style=" font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ៦. ច្បាប់គ្រប់គ្រង និងដំណោះស្រាយវិវាទ ៖</span>កិច្ចសន្យានេះគ្រប់គ្រងដោយច្បាប់កម្ពុជា។ ភាគីទាំងពីរយល់ព្រម                ដោះស្រាយជម្លោះ ដោយសំរុះសំរួលគ្នាដោយសន្តិវិធីនៅប្រទេសកម្ពុជា។ ប្រសិនបើពុំបានទទួលជោគជ័យ ភាគីទាំងពីរយល់ព្រមដាក់ជម្លោះដែលកើតចេញពីកិច្ចសន្យានេះ ជូនតុលាការ នៃព្រះរាជាណាចក្រកម្ពុជា ដែលមានសមត្ថកិច្ច ដើម្បីដោះស្រាយ។
						</span>	
						<span style="width: 100%; display: block;">
							<span style=" font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ៧. សុពលភាពនៃកិច្ចសន្យា ៖</span>កិច្ចសន្យានេះ ជាកិច្ចព្រមព្រៀងទាំងមូលរបស់ភាគីទាំងពីរ។ រាល់កិច្ចព្រមព្រៀងមុនៗទាំងអស់ ទោះជាដោយមាត់ទទេក្តី ឬ ជាលាយលក្ខណ៍អក្សរក្តី ដែលផ្ទុយកិច្ចសន្យានេះត្រូវទុកជាមោឃៈ។  ការកែប្រែកិច្ចសន្យានេះ មិនត្រូវមានប្រសិទ្ធិភាពឡើយ  លើកលែងតែធ្វើឡើងជាលាយលក្ខណ៍អក្សរ  ហើយផ្តិតមេដៃ ដោយភាគីទាំងពីរ។
						</span>
						<span style="width: 100%; display: block;">
							<span style=" font-family:'Khmer OS Muol Light';font-weight:200;">ដើម្បីជាសក្ខីភាព </span><span style="font-weight:700;">អ្នកលក់</span> និង <span style="font-weight:700;">អ្នកទិញ</span> ព្រមចុះហត្ថលេខា និងផ្តិតមេដៃស្តាំខាងក្រោមនេះ ដើម្បីទទួលស្គាល់ និងអនុវត្តចាប់ពីកាលបរិច្ឆេទខាងលើតទៅ។ កិច្ចសន្យានេះ មានចំនួន ០២ច្បាប់ ដោយគូរភាគីរក្សាទុកម្នាក់ ០១ច្បាប់។
						</span>
             		</p>
             	</td>
             </tr>
             <tr>
             	<td colspan="3">
             		<table align="center" width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';">
						   <tr style="font-size: 14px;">
						        <td class="reff" style="width:20%;text-align:center; text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;">អ្នកលក់</td>
						        <td>&nbsp;</td>
						        <td class="reff" style="width:20%;text-align:center; text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;">សាក្សី</td>
						        <td>&nbsp;</td>
								<td class="reff" style="width:20%;text-align:center; text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;">សាក្សី</td>
						        <td>&nbsp;</td>
						        <td class="reff" style="width:20%;text-align:center; text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;">អ្នកទិញ</td>
						   </tr>
						   <tr height="100px">
				             	<td>&nbsp;</td>
				           </tr>
				           <tr style="font-size: 14px;">
								<td class="reff" align="center" style="font-family:'Khmer OS Muol Light';font-weight:200;white-space: nowrap;"><?php echo $this->agreement['w_manager_namekh']." / ".$this->agreement['w_managername1'];?></td>
			             		<td colspan="5" >&nbsp;</td>
								<td class="reff" align="center" style="font-family:'Khmer OS Muol Light';font-weight:200;white-space: nowrap;"><?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"/".$this->agreement['hname_kh']:"";?></td>
						 </tr>
					</table>
             	</td>
             </tr>
             
    	</td>
    </tr>
</table>
</div>
