<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;

	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
	$dbparam  = new Report_Model_DbTable_DbParamater();
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_BUGET_PLAN");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_BUGET_PLAN');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<form name="frm_rptstaff" action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement("adv_search");?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('branch_id');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<select class="fullside" id="monthlytype" name="monthlytype" dojoType="dijit.form.FilteringSelect">
					<option value="1" <?php if ($this->search['monthlytype']==1){ echo 'selected=selected';}?>><?php  echo $tr->translate("MONTH");?></option>
					<option value="2" <?php if ($this->search['monthlytype']==2){ echo 'selected=selected';}?>><?php  echo $tr->translate("YEAR");?></option>
				</select>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('start_date');?>
        	</div>
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<?php echo $frm->getElement('end_date');?>
        	</div>
        	
        	<div class="col-md-2 col-sm-2 col-xs-12">
        		<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
        	</div>
        </div>        
	 </form> 
	<div style="min-height:22cm; margin:0 auto;">
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint">
	    	 	<style>
		.style{
   				 line-height: 20px;font-size: 11px !important;
            font-family: 'Times New Roman','Khmer OS Battambang';
        }
        .hideblog{display: none;}
        .hiddenblog{display: block !important;}
        .style1:hover{ background: #ccc; }
        table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
        table { page-break-inside:auto }
        tr{ page-break-inside:avoid; page-break-after:auto; }
        #header {
        display: table-header-group;
        page-break-inside:avoid; page-break-after:auto;
        margin-top: 100px;
        }
        .hide{visibility: hidden;}
        @media print {
        div.divFooter {
            position: fixed;
            top: 0;
            width: 100%;
            height: 100px;
            bottom:0px;
            margin:0;
        }
            .hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
            
        }
        .center{text-align: center !important;}
        table.content-data{
            border-collapse:collapse;
            border:1px solid #000; 
            font-size:8px;
        }
        table.content-data thead tr.style {
        line-height: 25px; font-size:12px !important; padding:3px 0px; white-space: nowrap;height: 22px; 
            background: #c1d0f3;
            font-weight:600;
        }
        table.content-data tr.style {
         white-space: nowrap;
        
        }
        table.tb-footer{
            border-collapse:collapse;
            border:1px solid #000; 
            font-size:11px;
            font-family: 'Times New Roman','Khmer OS Battambang';
        }
        table.tb-footer tr{
        line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
        }
        table tr td{
            padding:0 2px;
        }
        tr.voidclass {
            background: #fff7f7;
        }
        td.centerText{
            text-align: center;
        }
        .redBold {
            font-weight: 600;
            color: #f80000;
        }
					/*
					.style{
						line-height: 20px;font-size: 14px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
						}
						th{padding: 2px;}
						.hide{visibility: hidden;}
							@media print {
							  div.divFooter {
							    position: fixed;
							    top: 0;
							  	width: 100%;
							  	height: 100px;
							  	bottom:0px;
								margin:0;
							 }
						.hide{visibility: visible; height: 110px;}
					}
					td.verites-col {
					    text-align: center;
					    white-space: nowrap;
					    g-origin: 50% 50%;
					    -webkit-transform: rotate(270deg);
					    -moz-transform: rotate(270deg);
					    -ms-transform: rotate(270deg);
					    -o-transform: rotate(270deg);
					    transform: rotate(270deg);
					}
					tr.hover td.verites-col span.verites,
					td.verites-col span.verites {
					    margin: 0 -100%;
					    display: inline-block;
					}
					tr.hover td.verites-col span.verites:before,
					td.verites-col span.verites:before {
					    content: '';
					    width: 0;
					    padding-top: 110%;
					    display: inline-block;
					    vertical-align: middle;
					}
					*/
					</style>
				
		        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;">
		            	<tr>
			                <td width="30%"><img src="<?php echo $logo;?>" style="height:85px; max-width: 100%;"></td>
			                <td width="40%" valign="top">
			                	<h2 style="white-space:nowrap;font-weight:normal; text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $branch_title;?></h2>
			               		<h2 style="font-weight:normal; text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_BUGET_PLAN");?></h2>
			                	<h2 style="font-weight:normal; text-align:center; font-size:13px; font-family:'Times New Roman','Khmer OS Muol Light';">
			                	<?php if ($this->search['monthlytype']==1){?>
			                		<?php if(!empty($this->search['start_date'])){ echo date("M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("M-Y",strtotime($this->search['end_date']));}?>
			                	<?php }else{?>
			                		<?php if(!empty($this->search['start_date'])){ echo date("Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("Y",strtotime($this->search['end_date']));}?>
			                	<?php }?>
			                	</h2>
			                </td>
		                	<td width="30%"></td>
		             	</tr> 
		            </table>
		    
		        <?php if ($this->search['monthlytype']==1){?>
	        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none; " >
		            <tr>
	            	   <td colspan="3">
	            		<table id="exportExcel" border="1" width="100%" class="content-data">  
					    	<thead>
					    		<tr class="hide" style="border:1px solid #000; margin-top: 100px;">
						             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						        </tr>
						    	<tr  class="style" align="center"  >
									<td scope="col">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
								    <td scope="col">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
								    <?php if (!empty($this->search['start_date'])){
								    	$startmonth= date("Y-m-01",strtotime($this->search['start_date']));
								    	$endmonth= date("Y-m-01",strtotime($this->search['end_date']));
								    	for ($i=0; date("Y-m-01",strtotime("$startmonth+$i month"))<= date("Y-m-01",strtotime($endmonth)); $i++){
								    ?>
								    <td scope="col" class="verites-col">&nbsp;<span class="verites"><strong><?php echo date("M-Y",strtotime(" $startmonth+$i month"));?></strong></span>&nbsp;</td>
								   <?php }
								    }?>
								    <td scope="col">&nbsp;<?php echo $tr->translate("TOTAL_EXPENSE");?>&nbsp;</td>
								    <td scope="col" >&nbsp;<?php echo $tr->translate("BUDGET_AMOUNT");?>&nbsp;</td>
								    <td scope="col">&nbsp;<?php echo $tr->translate("REMAIN");?>&nbsp;</td>
								</tr>
							</thead>
							<tbody>
								<?php 
									$total_expense= 0;
									$total_allexpense = 0;
									$total_remain = 0;
									$total_allbudget= 0;
									
								if (!empty($this->project)) foreach ($this->project as $key=> $pro){ ?>
								<tr class="style hover" align="center">
									<td data-label="<?php echo $tr->translate("NUM");?>"  align="center">&nbsp;<?php echo $key+1?>&nbsp;</td>
									<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>"  >&nbsp;<?php echo $pro['project_name']?>&nbsp;</td>
									 <?php if (!empty($this->search['start_date'])){
								    	$startmonth= date("Y-m-01",strtotime($this->search['start_date']));
								    	$endmonth= date("Y-m-01",strtotime($this->search['end_date']));
								    	for ($i=0; date("Y-m-01",strtotime("$startmonth+$i month"))<= date("Y-m-01",strtotime($endmonth)); $i++){
								    ?>
								    <td data-label="<?php echo date("M-Y",strtotime(" $startmonth+$i month"));?>"  class="verites-col" align="center" style="white-space: nowrap;">
								    	<span class="verites">
								    	&nbsp;
								    	<?php 
								    	$total = $dbparam->getExpensByMonth($pro['br_id'], date("Y-m",strtotime(" $startmonth+$i month")));
								     	if ($total>0){	echo "$ ".number_format($total,2);}else { echo "-";};
								     	$total_expense = $total_expense+$total;
								     	$total_allexpense = $total_allexpense+$total;
								     	?>&nbsp;
								     	</span>
								     </td>
								   <?php }
									 }
									 $total_allbudget = $total_allbudget+$pro['budget_amount'];
									 $total_remain = $pro['budget_amount'] - $total_expense;
									 ?>
								    <td data-label="<?php echo $tr->translate("TOTAL_EXPENSE");?>"  align="center" style="white-space: nowrap;">&nbsp;<strong><?php echo "$ ".number_format($total_expense,2);$total_expense=0;?></strong>&nbsp;</td>
								    <td data-label="<?php echo $tr->translate("BUDGET_AMOUNT");?>"  align="center" style="white-space: nowrap;">&nbsp;<strong><?php echo "$ ".number_format($pro['budget_amount'],2);?></strong>&nbsp;</td>
								    <td data-label="<?php echo $tr->translate("REMAIN");?>"  align="center" style="white-space: nowrap;">&nbsp;<strong style="color: red;"><?php if ($total_remain<0){ echo "$ (".number_format(abs($total_remain),2).")"; }else{ echo "$ ".number_format($total_remain,2);}?></strong>&nbsp;</td>
								</tr>
								<?php }?>
							</tbody>
					    </table>
					    <?php $totalAllREmain = $total_allbudget-$total_allexpense; ?>
					    <div style="text-align: right;">
					   		 <span style="display: inline-block;"><?php echo $tr->translate("TOTAL_EXPENSE");?></span> 
					   		 : <strong style="display: inline-block; min-width: 100px;"><?php echo "$ ".number_format($total_allexpense,2);?></strong>
					   </div>
					    <div style="text-align: right;">
					    	<span style="display: inline-block;"><?php echo $tr->translate("TOTAL_REMAIN");?></span> : 
					    	<strong style="display: inline-block; min-width: 100px;"><?php if ($totalAllREmain<0){ echo "$ (".number_format(abs($totalAllREmain),2).")"; }else{ echo "$ ".number_format($totalAllREmain,2);}?></strong></div>
	            	</td>
	            </tr>
	            </table>
	            <?php }else{?>
	            <table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;" >
		            <tr>
	            	   <td colspan="3">
	            		<table id="exportExcel" border="1" width="100%" class="content-data" >  
					    	<thead>
					    		<tr class="hide" style="border:1px solid #000;">
						             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						        </tr>
						    	<tr  class="style" align="center"  >
									<td scope="col">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
								    <td scope="col">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
								    <?php if (!empty($this->search['start_date'])){
								    	$startmonth= date("Y-m-01",strtotime($this->search['start_date']));
								    	$endmonth= date("Y-m-01",strtotime($this->search['end_date']));
								    	for ($i=0; date("Y-m-01",strtotime("$startmonth+$i year"))<= date("Y-m-01",strtotime($endmonth)); $i++){
								    ?>
								    <td scope="col" class="verites-col">&nbsp;<span class="verites">&nbsp;&nbsp;&nbsp;<strong><?php echo date("Y",strtotime(" $startmonth+$i year"));?></strong>&nbsp;&nbsp;&nbsp;</span>&nbsp;</td>
								   <?php }
								    }?>
								    <td scope="col">&nbsp;<?php echo $tr->translate("TOTAL_EXPENSE");?>&nbsp;</td>
								    <td scope="col">&nbsp;<?php echo $tr->translate("BUDGET_AMOUNT");?>&nbsp;</td>
								    <td scope="col">&nbsp;<?php echo $tr->translate("REMAIN");?>&nbsp;</td>
								</tr>
							</thead>
							<tbody>
								<?php 
									$total_expense= 0;
									$total_allexpense = 0;
									$total_remain = 0;
									$total_allbudget= 0;
									
								if (!empty($this->project)) foreach ($this->project as $key=> $pro){ ?>
								<tr>
									<td data-label="<?php echo $tr->translate("NUM");?>"  align="center">&nbsp;<?php echo $key+1?>&nbsp;</td>
									<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>">&nbsp;<?php echo $pro['project_name']?>&nbsp;</td>
									 <?php if (!empty($this->search['start_date'])){
								    	$startmonth= date("Y-m-01",strtotime($this->search['start_date']));
								    	$endmonth= date("Y-m-01",strtotime($this->search['end_date']));
								    	for ($i=0; date("Y-m-01",strtotime("$startmonth+$i year"))<= date("Y-m-01",strtotime($endmonth)); $i++){
								    ?>
								    <td data-label="<?php echo date("M-Y",strtotime(" $startmonth+$i month"));?>" class="verites-col" align="center" style="white-space: nowrap;">
								    	<span class="verites">
								    	&nbsp;
								    	<?php 
								    	$total = $dbparam->getExpensByMonth($pro['br_id'], date("Y-m",strtotime(" $startmonth+$i year")),$this->search['monthlytype']);
								     	if ($total>0){	echo "$ ".number_format($total,2);}else { echo "-";};
								     	$total_expense = $total_expense+$total;
								     	$total_allexpense = $total_allexpense+$total;
								     	?>&nbsp;
								     	</span>
								     </td>
								   <?php }
									 }
									 $total_allbudget = $total_allbudget+$pro['budget_amount'];
									 $total_remain = $pro['budget_amount'] - $total_expense;
									 ?>
								    <td data-label="<?php echo $tr->translate("TOTAL_EXPENSE");?>"  align="center" >&nbsp;<strong><?php echo "$ ".number_format($total_expense,2);$total_expense=0;?></strong>&nbsp;</td>
								    <td data-label="<?php echo $tr->translate("BUDGET_AMOUNT");?>"  align="center" >&nbsp;<strong><?php echo "$ ".number_format($pro['budget_amount'],2);?></strong>&nbsp;</td>
								    <td data-label="<?php echo $tr->translate("REMAIN");?>"  align="center" >&nbsp;<strong style="color: red;"><?php if ($total_remain<0){ echo "$ (".number_format(abs($total_remain),2).")"; }else{ echo "$ ".number_format($total_remain,2);}?></strong>&nbsp;</td>
								</tr>
								<?php }?>
							</tbody>
					    </table>
					    <?php $totalAllREmain = $total_allbudget-$total_allexpense; ?>
					    <div style="text-align: right;">
					   		 <span style="display: inline-block;"><?php echo $tr->translate("TOTAL_EXPENSE");?></span> 
					   		 : <strong style="display: inline-block; min-width: 100px;"><?php echo "$ ".number_format($total_allexpense,2);?></strong>
					   </div>
					    <div style="text-align: right;">
					    	<span style="display: inline-block;"><?php echo $tr->translate("TOTAL_REMAIN");?></span> : 
					    	<strong style="display: inline-block; min-width: 100px;"><?php if ($totalAllREmain<0){ echo "$ (".number_format(abs($totalAllREmain),2).")"; }else{ echo "$ ".number_format($totalAllREmain,2);}?></strong></div>
	            	</td>
	            </tr>
	            </table>
	            <?php }?>
	            <br />
	               <table align="center" width="100%">
					   <tr style="font-size: 14px;">
					        <td style="width:20%;text-align:center;  font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center;font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
					   </tr>
				  </table>
			</div>
	    </td>
	   </tr>
   </table>
</div>
</div>