<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_SALE_HISTORY");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_SALE_HISTORY');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-sale-history')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('branch_id');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<input id="land_id" />
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('client_name');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('start_date');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
				</div>
			</div>
		</div>
	 </form> 
	<div style="min-height:22cm; margin:0 auto;">
		<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
			<tr>
		    	<td align="center">
		    	 <div id="divPrint">
		    	 	<style>
						.style{
							line-height: 20px;font-size: 12px !important;
							font-family: 'Times New Roman','Khmer OS Battambang';
							}
							th{padding: 5px;}
							table.content-data{
								border-collapse:collapse;
								border:1px solid #000; 
								font-size:13px;
								font-family: 'Times New Roman','Khmer OS Battambang';
							}
							table.content-data thead tr.style {
							   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
							}
					</style>
					<div class="divFooter">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0; border:none;">
			        	<tr>
			                <td width="30%"><img src="<?php echo $logo;?>" height="85px" style="max-width:100%"></td>
			                <td width="40%" valign="top">
				                <h2 style="white-space:nowrap;text-align:center; font-weight:400; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $branch_title;?></h2>
				                <h2 style="text-align:center; font-weight:400; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_SALE_HISTORY");?></h2>
				            </td>
			             	<td width="30%"></td>
			             </tr>
					 </table>
				    </div>						 
			        <table borde="1" width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0; border:none;" > 
		             <tr>
		            	<td colspan="3">
		            		<table id="exportExcel" width="100%" style="border-collapse:collapse;font-size: 14px;" >  
						      <?php $property_id=0; $is_cancel=""; $i=0; $total=0; 
						       if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
						      <?php  
								if($row['house_id']!=$property_id){	
									if($key>0 ){
								?>
								<?php $i=1;}?>
								</table>
							</td>
						</tr>
						<tr><td></td></tr>
						<tr><td></td></tr>
						<tr><td></td></tr>
						<tr>
							<td colspan="3" >
								<table id="exportExcel" class="content-data" width="100%" border="1"  bordercolor="black">
									<thead>
										<tr style=" border-top: solid 1px #fff; border-left: solid 1px #fff;  border-right: solid 1px #fff;">
											<td colspan="7">
												<span style="font-family: Arial Black;color:#000; font-size: 14px;font-family:'Times New Roman','Khmer OS Muol Light'; padding:5px;" >
												<?php echo $tr->translate("PROPERTY_TYPE")." : ".$row['property_type_name']; ?>
												</span>
											</td>
										</tr>
										<tr bgcolor="#c1d0f3" class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
						                    <td rowspan="2"><?php echo $tr->translate("NUM");?></td>
						                    <td rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></td>
						                    <td rowspan="2"><?php echo $tr->translate("CLIENT_NUM");?></td>                  
						                    <td rowspan="2"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
						                    <td rowspan="2"><?php echo $tr->translate("PROPERTY_CODE");?></td>
						                    <td rowspan="2"><?php echo $tr->translate("STREET");?></td>	  
						                    <td colspan="6"><?php echo $tr->translate("PAYMENT_INFO");?></td>    
						                    <td rowspan="2"><?php echo $tr->translate("INPUT_DATE");?></td>
						                    <td rowspan="2"><?php echo $tr->translate("PAYMENT_OPTION");?></td>
						                    <td rowspan="2"><?php echo $tr->translate("STATUS");?></td>
						                    <td rowspan="2"><?php echo $tr->translate("BY_USER");?></td>
							              </tr>
							              <tr class="style" style="background:#c1d0f3;white-space: nowrap;text-align: center;">
						                	<td><?php echo $tr->translate("PRINCIPLE_PICE");?></td> 
						                    <td><?php echo $tr->translate("DISCOUNT");?></td>
						                    <td><?php echo $tr->translate("DISCOUNT");?>%</td>                  
						                    <td><?php echo $tr->translate("SOLD_PRICE");?></td>	                    
						                    <td><?php echo $tr->translate("PAID_AMOUNT");?></td>
						                    <td><?php echo $tr->translate("BALANCE");?></td>
							               </tr>
							             </thead>
									<?php }?>
									   <tr style="font-size: 12px;" align="left">
									     <td align="center">&nbsp;<?php echo $i; ?></td>
									     <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['project_name'];?>&nbsp;</td>
									     <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['client_code'];?>&nbsp;</td>
										 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['client_name_kh'];?>&nbsp;</td>
										 <td align="center">&nbsp;<?php echo $row['property_name'];?>&nbsp;</td>
										 <td align="center">&nbsp;<?php echo $row['street'];?>&nbsp;</td>
										 <td align="center">&nbsp;<?php echo number_format($row['price_before'],2);?>&nbsp;</td>
										 <td align="center">&nbsp;<?php echo number_format($row['discount_amount'],2);?>&nbsp;</td>
										 <td align="center">&nbsp;<?php echo number_format($row['discount_percent'],2);?>&nbsp;</td>
										 <td align="center">&nbsp;<?php echo number_format($row['price_sold'],2);?>&nbsp;</td>
										 <td align="center">&nbsp;<?php echo number_format($row['paid_amount'],2);?>&nbsp;</td>
										 <td align="center">&nbsp;<?php echo number_format($row['price_sold']-$row['paid_amount'],2); //number_format($row['balance'],2);?>&nbsp;</td>
										 <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date("d-M-Y",strtotime($row['create_date']));?>&nbsp;</td>
										 <td align="center">&nbsp;<?php echo $row['paymenttype'];?></td>
										 <td align="center">&nbsp;<?php if ($row['is_cancel']==1){ echo $tr->translate("CANCELED");}else{ echo $tr->translate(""); }?></td>
										 <td align="center">&nbsp;<?php echo $row['user_name'];?></td>
										</tr>
										<?php 
										$property_id = $row['house_id'];
										?>
									<?php }?>
							    </table>
							</td>
						</tr>
		            </table>
		            <br />
				   <?php echo $this->footerReport;?>
		            </div>
		    	</td>
		    </tr>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			//dijit.byId('land_id').attr('value','');
			land_id=-1;
	}
		}, "land_id");
	
	 
});
land_id = '<?php echo $this->search['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
} 
</script>