<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$day = array(
		"Mon" =>'ច័ន្ច',
		"Tue" =>'អង្គារ',
		"Wed" =>'ពុធ',
		"Thu" =>'ព្រហស្បតិ័',
		"Fri" =>'សុក្រ',
		"Sat" =>'សៅរ៍',
		"Sun" =>'អាទិត្យ',
		);
$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មិនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កញ្ញា","08"=>"កក្កដា","09"=>"សីហា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("AGREEMENT");?></title>
<style>
	.reff{ font-size: 20px !important; line-height:34px !important;}
	tr td h2,
	pre{ font-size: 20px !important; line-height:34px !important;}
</style>
<div style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint">
    	 	<style>
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Khmer OS Battambang';
						}
						th{padding: 5px;}
						span.value{ display: inline-block; border-bottom: 1px #000 dotted;text-align: center;}
						span.child {display:block; margin-left:25px;}
					</style>
        	<table width="100%" style="font-family:khmer;" style="margin:0; padding:0;border:none;" >
        	<tr>
                <td width="20%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="95px"></td>
                <td width="60%" valign="top">
                <h2 style="text-align:center; line-height:18px; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("ព្រះរាជាណាចក្រកម្ពុជា");?></label></h2>
                <h2 style="text-align:center; line-height:18px; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></label></h2>
                <h2 style="text-align:center; line-height:18px; font-size:16px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.JPG" height="25px"></h2>
                <h2 style="text-align:center; line-height:18px; font-size:16px; font-family:'Khmer MEF2'"><label><?php echo $tr->translate("កិច្ចព្រមព្រៀងទិញនិងលក់ផ្ទះ");?></label></h2>
                <td width="20%"></td>
             </tr> 
             <tr>
             	<td colspan="3">
             		<pre style="font-family: 'Khmer OS Battambang'; white-space: pre-line; text-align:justify; line-height:24px; font-size:14px;">
             			<span style=" font-family:'Khmer MEF2';font-weight:700;">កិច្ចព្រមព្រៀងទិញនិងលក់ផ្ទះ</span> នេះ (កិច្ចព្រមព្រៀង) ត្រូវបានធ្វើឡើងនៅភ្នំពេញថ្ងៃទី <?php echo date("d",strtotime($this->agreement['buy_date']));?> ខែ <?php echo date("m",strtotime($this->agreement['buy_date']));?> ឆ្នាំ <?php echo date("Y",strtotime($this->agreement['buy_date']));?> រវាង :
             			<span style=" font-family:'Khmer MEF2'; font-weight:700;">អ្នកលក់ <?php echo $this->keyValue['party_a'];?></span> ជនជាតិខ្មែរ កាន់អត្តសញ្ញាណប័ណ្ណលេខ:<span style=" font-family:'Khmer MEF2'; font-weight:700;"><?php echo $this->keyValue['party_a_nation_id'];?></span> <span style=" font-family:'Khmer MEF2';font-weight:700;"><?php echo $this->keyValue['party_b'];?></span> កាន់អត្តសញ្ញាណប័ណ្ណ
             			លេខ<span style=" font-family:'Khmer MEF2'; font-weight:700;"><?php echo $this->keyValue['party_b_nation_id'];?></span> មានអស័យដ្ធាននៅ<?php echo $this->keyValue['party_address'];?>។
             			ចាប់ពីពេលនេះតទៅហៅថា  <span style=" font-family:'Khmer MEF2'; font-weight:700;">(អ្នកលក់)</span> និង             			
             			<span style=" font-family:'Khmer MEF2'; font-weight:700;">លោក-លោកស្រី</span> <span class="value" style="width:250px;"><?php echo $this->agreement['client_namekh'];?></span>ជាជនជាតិ <span class="value" style="width:30px;"><?php echo $this->agreement['client_nationality'];?></span> កាន់អត្តសញ្ញាណប័ណ្ណលេខ <span class="value" style="width:80px;"><?php echo $this->agreement['client_nation_id'];?></span>
             			មានអស័យដ្ធានផ្ទះលេខ: <span class="value" style="width:55px;"><?php echo $this->agreement['client_house_no'];?></span> ផ្លូវលេខ  <span class="value" style="width:55px;"><?php echo $this->agreement['client_street'];?></span> សង្កាត់  <span class="value" style="width:150px;"><?php echo $this->agreement['client_commune_kh'];?></span> ខណ្ឌ <span class="value" style="width:150px;"><?php echo $this->agreement['client_districtkh'];?></span>
             			ខេត្ត-ក្រុង <span class="value" style="width:100px;"><?php echo $this->agreement['client_province_kh'];?></span>។ ចាប់ពិពេលនេះតទៅហៅថា   <span style=" font-family:'Khmer MEF2'; font-weight:700;">(អ្នកទិញ)</span>​។
             			<span style="font-family:'Khmer MEF2'; font-weight:700; text-decoration:underline; text-align:center; width: 100%; display: inline-block;">កិច្ចព្រមព្រៀង</span>
             			<span style=" font-family:'Khmer MEF2'; font-weight:700;">១. ការទិញនិងលក់ផ្ទះ ៖ </span>អ្នកទិញយល់ព្រមទិញពិអ្នកលក់ហើយអ្នកល់ក៏យល់ព្រមលក់និងផ្ទេរកម្មសិទ្ធិជូនអ្នកទិញនូវ:
             			ប្រភេទផ្ទះ  <span class="value" style="width:100px;"><?php echo $this->agreement['property_type_en'];?></span> ដែលមានទទឺងផ្ទះ <span class="value" style="width:75px;"><?php echo $this->agreement['property_width'];?></span> មែត្រ,បណ្ដោយផ្ទះ <span class="value" style="width:75px;"><?php echo $this->agreement['property_height'];?></span> មែត្រ,ផ្ទះលេខ <span class="value" style="width:70px;"><?php echo $this->agreement['property_title'];?></span> 
             			ផ្លូវលេខ: <span class="value" style="width:100px;"><?php echo $this->agreement['property_street'];?></span> នៅបុរីភ្នំពេញថ្មី () ។
             			(ពីពេលនេះតទៅហៅថា <span style=" font-family:'Khmer MEF2'; font-weight:700;">អចលនវត្ថុ</span>)។
             			<span style=" font-family:'Khmer MEF2'; font-weight:700;">២.ការធានានិងការរ៉ាប់រងរបស់អ្នកលក់ ៖ អ្នកលក់ធានា និង សន្យាថានៅថ្ងៃចុះកិច្ចព្រមព្រៀងនេះ </span>
             			<span class="child"><?php echo $this->termcodiction['con_khmer'];?></span><span style=" font-family:'Khmer MEF2'; font-weight:700; display: initial;">៣.តំលៃទិញ និង ការផ្ទេរសិទ្ធិ ៖ </span>
             			តំលៃទិញអចលនវត្ថុគឺUSD <span class="value" style="width:420px;"><?php echo number_format($this->agreement['price_sold'],2);?></span> (ដុល្លាអាមេរិក)។
             			អ្នកទិញត្រូវប្រគល់ប្រាក់ថ្លៃទិញជូនទៅ អ្នកលក់ តាមដំណាក់កាលដូចខាងក្រោមៈ
             				<span class="child"><?php $i=0; if (!empty($this->sale_schedule))  foreach ($this->sale_schedule as $row){$i++; echo $i; ?>. ប្រាក់កក់ដំបូងចំនួនUSD <span class="value" style="width:420px;"><?php echo number_format($row['begining_balance'],2);?></span> (ដុល្លាអាមេរិក)
             				អ្នកទិញបានបង់នៅថ្ងៃ <?php echo $day[date("D",strtotime($row['date_payment']))]." ខែ ".$month[date("m",strtotime($row['date_payment']))]." ឆ្នាំ ".date("Y",strtotime($row['date_payment'])); ?>
             				
             				<?php }?>
             				<?php echo $i+1;?>. ការបង់រំលស់ៈ អ្នកទិញស្នើរសុំបង់រំលស់ ហើយអ្នកលក់ក៏យល់ព្រមអោយអ្នកទិញបង់រំលស់នូវទឹកប្រាក់ចំនួន
             				USD <span class="value" style="width:550px;"><?php echo number_format($this->agreement['price_sold'],2);?></span> (ដុល្លាអាមេរិក)
             				សំរាប់រយៈពេល<span class="value" style="width:250px;">&nbsp;<?php echo ($this->agreement['total_duration']/12);?>&nbsp;</span>ឆ្នាំ(12ខែ)ជារៀងរាល់ខែគិតចាប់ពី ដូចបានចែងលំអិតក្នុង  
	             			ល័ក្ខខណ្ឌនៃការរំរលស់មានភ្ជាប់មកជាមួយកិច្ចព្រមព្រៀងនេះ។ ក្រោយពីការបង់ប្រាក់គ្រប់ចំនួន 
	             			ទើបអ្នកលក់ រៀបចំបែបបទផ្ទេរសិទ្ធិ កាន់កាប់វិញ្ញាបនប័ត្រសម្គាល់ម្ចាស់អចលនវិត្ថុ ជូនអ្នកទិញ នៅត្រឹមអាជ្ញាធរខណ្ឌ
	             			ដោយសោហ៊ុយចំណាយ ជាបន្ទុកអ្នកលក់។</span>
             			<span style=" font-family:'Khmer MEF2'; font-weight:700; display: initial;">៤ .ការបំពានកាតព្វកិច្ចរបស់អ្នកទិញ ៖   </span>ក្នុងករណីដែរអ្នកទិញ មិនបានបង់ប្រាក់ តាមការកំណត់ដូចបានចែងក្នុង
             			ប្រការ៣ខាងលើនោះអ្នកទិញនឹងត្រូវបង់ប្រាក់ពិន័យចំនួន<?php echo $this->penaly_percent['penaly_percent'];?> ក្នុងមួយខែនៃចំនួនទឹកប្រាក់ដែលត្រូវបង់។
             			ប្រសិនបើអ្នកទិញ ខកខានមិនបានបង់ប្រាក់លើសពី ៣០ ថ្ងៃ នោះទឹកប្រាក់ដែលអ្នកទិញបានបង់ទាំងអស់ និងត្រូវបានមកអ្នកលក់
             			ហើយកិច្ចព្រមព្រៀងនេះ នឹងត្រូវចាត់ទុកជាមោឃៈដោយស្វ័យប្រវត្តិ ដោយអ្នកទិញគ្មានសិទិ្ធតវ៉ាអ្វីឡើយ។ ក្នុងករណីនេះអ្នកលក់
             			មានសិទ្ធិលក់ផ្ទះនេះអោយអ្នកដទៃបានគ្រប់ពេលវេលា។
             			-	ករណីដែលភាគីអ្នកលក់កែប្រែមិនលក់វិញនោះនឹងត្រូវបង់ពិន័យទៅអោយភាគីអ្នកទិញស្មើនឹងប្រាក់ដែលបានបង់គុណនឹងពីរ។
             			<span style=" font-family:'Khmer MEF2'; font-weight:700; display: initial;">៥.ការស្នងបន្ត  ៖   </span>រាល់សិទ្ធិ និងកាតព្វកិច្ចទាំងអស់ របស់អ្នកទិញដែលមាន ក្រោមកិច្ចព្រមព្រៀងនេះ ត្រូវមានប្រសិទ្ធិភាពផងដែល
             			ចំពោះទាយាទអ្នកស្នងបន្ត និង អ្នកទទួលសិទ្ធិរបស់អ្នកទិញ តាមរយៈលិខិតជាលាយលក្ខអក្សរដោយមានសាក្សី ដឹងឮ និងមេធាវី។
             			ដោយឡែកចំពោះអ្នកលក់ប្រសិនបើមានហេតុការណ៍អាក្រក់ណាមួយកើតឡើងចំពោះអ្នកលក់ហើយបណ្ដាលអោយអ្នក់លក់
             			បាត់បង់នូវសមត្ថភាព កាយសម្បទាវិកលចរឹក ឬ រហូតដល់បាត់បង់ជីវិត នោះសិទ្ធិ និងកាតព្វកិច្ចទាំងអស់របស់អ្នកលក់នឹងត្រូវបាន
             			ទៅលើ <span style=" font-family:'Khmer MEF2';font-weight:700;"><?php echo $this->keyValue['party_b'];?></span> កាន់អត្តសញ្ញាណប័ណ្ណលេខៈ <span style=" font-family:'Khmer MEF2'; font-weight:700;"><?php echo $this->keyValue['party_b_nation_id'];?></span> ដែលត្រូវជាភរិយាស្របច្បាប់របស់អ្នកលក់។
             			ហើយករណីដូចគ្នាផងដែរ ប្រសិនបើមានហេតុការណ៍អាក្រក់ណាមួយ កើតឡើងចំពោះ <span style=" font-family:'Khmer MEF2';font-weight:700;"> <?php echo $this->keyValue['party_b'];?></span> នោះសិទ្ធិ និង
             			កាតព្វកិច្ចទាំងអស់របស់អ្នកលក់ នឹងត្រូវបានទៅលើ <span style=" font-family:'Khmer MEF2';font-weight:700;"><?php echo $this->keyValue['party_c'];?></span> កាន់អត្តសញ្ញាណប័ណ្ណលេខៈ <span style=" font-family:'Khmer MEF2'; font-weight:700;"><?php echo $this->keyValue['party_c_nation_id'];?></span> ដែលជា
             			ប្អូនស្រីរបស់ អ្នកលក់។
             			<span style=" font-family:'Khmer MEF2'; font-weight:700; display: initial;">៦.ច្បាប់គ្រប់គ្រង និង ដំណោះស្រាយវិវាទ ៖  </span>កិច្ចព្រមព្រៀងនេះ ត្រូវគ្រប់គ្រងដោយច្បាប់ប្រទេសកម្ពុជា។ ភាគីទាំងពី
             			យល់ព្រមដោះស្រាយជម្លោះ ដោយសម្រុះសម្រួល គ្នាដោយសន្តិវិធី នៅប្រទេសកម្ពុជា ។ ប្រសិនបើពុំបានទទួលជោគជ័យភាគីទាំងពីរ
             			យល់ព្រមដាក់ជម្លោះដែលកើតចេញពី កិច្ចព្រមព្រៀងនេះ ជួនតុលាការកម្ពុជាដែលមានសមត្ថកិច្ច។
             			<span style=" font-family:'Khmer MEF2'; font-weight:700; display: initial;">៧.កិច្ចព្រមព្រៀងទាំងមូល ៖  </span>កិច្ចព្រមព្រៀងនេះជាកិច្ចព្រមព្រៀងទាំងមូលរបស់ភាគីទាំងពីរ។ រាល់កិច្ចព្រមព្រៀងមុនៗទាំងអស់
             			ទោះបីជាមាត់ទទេរក្ដី ឬ ជាលាយលក្ខអក្សរក្ដី ដែលផ្ទុយនឹងកិច្ចព្រមព្រៀងនេះ ត្រូវទុកជាមោឃះ ។ ការកែប្រែកិច្ចព្រមព្រៀង នេះមិនត្រូវ
             			មានប្រសិទ្ធិភាពឡើយ លើកលែងតែធ្វើឡើងជាលាយលក្ខអក្សរ ហើយចុះហត្ថលេខាដោយភាគីទាំងពីរ។
             			<span style=" font-family:'Khmer MEF2'; font-weight:700; display: initial;">ជាសក្ខីភាពនៃសេក្ដីខាងលើ </span> អ្នកលក់និង អ្នកទិញព្រមចុះហត្ថលេខានិងផ្ដិតមេដៃស្ដាំខាងក្រោមនេះដើម្បីទទួលស្គាល់និង
             			អនុវត្តន៍តាមបទបញ្ញត្តិ ទាំងឡាយនៃកិច្ចព្រមព្រៀងនេះ នូវកាលបរិច្ឆេទដែល បានសរសេរដំបូងខាងលើ។
             		</pre>
             	</td>
             </tr>
             <tr>
             	<td colspan="3">
             		<table align="center" width="100%">
						   <tr style="font-size: 14px;">
						        <td class="reff" style="width:20%;text-align:center; text-decoration:underline;  font-family:'Khmer MEF2'">អ្នកលក់</td>
						        <td></td>
						        <td class="reff" style="width:20%;text-align:center; text-decoration:underline; font-family:'Khmer MEF2'">សាក្សី</td>
						        <td></td>
						        <td class="reff" style="width:20%;text-align:center; text-decoration:underline; font-family:'Khmer MEF2'">អ្នកទិញ</td>
						        <td></td>
						        <td class="reff" style="width:20%;text-align:center; text-decoration:underline; font-family:'Khmer MEF2'">សាក្សី</td>
						   </tr>
					</table>
             	</td>
             </tr>
             <tr height="60px">
             	<td>&nbsp;</td>
             </tr>
             <tr>
             	<td colspan="3">
             		<pre style="font-family: 'Khmer OS Battambang'; white-space: pre-line; text-align:justify; line-height:24px; font-size:14px;">
             			<span class="value" style="width:90%; text-align:right;"><?php echo $this->agreement['client_namekh'];?></span><span class="value" style="width:10%;">&nbsp;</span>
             			លេខទូរស័ព្ទ<span class="value" style="width:260px; ">&nbsp;</span>លេខទូរស័ព្ទ<span class="value" style="width:260px; "><?php echo $this->agreement['client_phone'];?></span>
             		</pre>
             	</td>
             </tr>
            </table>
    	</td>
    </tr>
</table>
</div>
