<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$day = array(
		"Mon" =>'ច័ន្ទ',
		"Tue" =>'អង្គារ',
		"Wed" =>'ពុធ',
		"Thu" =>'ព្រហស្បតិ៍',
		"Fri" =>'សុក្រ',
		"Sat" =>'សៅរ៍',
		"Sun" =>'អាទិត្យ',
	);
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	$dbparmeter = new Report_Model_DbTable_DbParamater();
	$key = new Application_Model_DbTable_DbKeycode();
	$dataterm = $key->getKeyCodeMiniInv(TRUE);
	$arrgender = array(1=>"ប្រុស",2=>"ស្រី");
	
	function getGenderTitle($genderId){
		$genderTitle = array(
				0=>'លោក',
				1=>'លោកស្រី',
				2=>'កញ្ញា'
			);
		return $genderTitle[$genderId];
		
	}
	$titleRepresent="លោក";
	$representName="ចាន់ ពន្លឺ";
	$representDate="04-04-1998";
	$representIDNo="090736749";
	$representAddress="ភូមិសាលាកន្សែង សង្កាត់ស្វាយដង្គំ  ក្រុងសៀមរាប ខេត្តសៀមរាប";
	$representPhone="០៨៥ ៣៧០ ៩៤០";
	$representPrefixWord="ខ្ញុំបាទ";
	if(date("d-m-Y",strtotime($this->agreement['create_date']))>"01-10-2022"){
		$titleRepresent="លោកស្រី ";
		$representName="យឿយ ចាន់ថ្លា";
		$representDate="03-02-1997";
		$representIDNo="180631301";
		$representAddress="ភូមិស្លែង ឃុំស្រណាល ស្រុកក្រឡាញ់ ខេត្តសៀមរាប";
		$representPhone="010 991 200";
		$representPrefixWord="នាងខ្ញុំ";
	}
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title style="color:#fff;"><?php echo $tr->translate("AGREEMENT");?></title>
<style>
	#divPrint .reff,#divPrint1 .reff{ font-size: 20px !important; line-height:34px !important;}
	#divPrint tr td h2,
	#divPrint p, 
	#divPrint pre, 
	#divPrint span,
	#divPrint tr td,
	#divPrint1 tr td h2,
	#divPrint1 p, 
	#divPrint1 pre, 
	#divPrint1 span,
	#divPrint1 tr td
	{
		font-size: 20px !important; line-height:35px !important;
    }
	#divPrint #padding-left-p-2{
	 	padding-left: 105px !important;	
	}
	#divPrint .padding-buttom{
		margin-top: -5px !important;
	}
	#mainbody{
		display: block !important;
	    position: relative !important;
	}
	#watermark{
		display: none !important;	
	}
	ul.blogsub li{
		line-height:34px !important;
	}
	#printfooter{display: none !important;}
	body{
		margin:0 !important;
	}
</style>
	<div  id="exportword" style="min-height:22cm; margin:0 auto;padding:0px 0.5cm">
		<table style="font-family: 'Khmer OS Content'; width:100%;"  >
			<tr>
			    <td align="center">
					<?php if($this->agreement['branch_id']==1){?>
					<div id="divPrint" style="position: relative;" >
							<style>		
								#padding-left-p-2{
									padding-left:105px !important;	
								}
								.padding-buttom{
									margin-top:-10px !important;
								}
								tr td,tr td h2,p,pre,span{ 
									font-size: 16px ; line-height:36px;
								}
								#padding-left{
									padding-left: 18px;
								}
								#bold-padding-right{
									margin-right:15px;
									font-family:'Times New Roman','Khmer OS Siemreap';
								}
								#padding-left-2{
								
									padding-left:15px;
								}
								#padding-left-p-2{
								   margin-top:-1px; 
								   padding-left: 85px;	
								}
								#padding-left-p{
									padding-left: 105px;
								}
								th{padding: 5px;}
								span.value{ line-height:10px;display: inline-block; text-align: center;}
								span.child {display:block; margin-left:25px; line-height: 22px;}
								.value_label{
									border-bottom: dashed 1px #000;
									line-height: 12px !important;
									min-width: 100%;
									display: inline-block;
								}
								body{
									position: relative;
								}
								#printfooter {
									position: absolute;
									bottom: 0;
									position: fixed;
									display: block ;
								}
								span.margin-left{
									margin-left:35px; display: inline-block;
								}
								ul.blogsub li{
									list-style-type: square;
									line-height: 24px;
								}
								ul.reference li{
									line-height: 24px;
									list-style: none;
								}
								ul.blogsub{
									padding:0;margin:0;
								}
								#printfooter {
									position: absolute;
									bottom:-5;
									position: fixed;
									display: block ;
								}
								body {
									margin:0.4cm 0.4cm 0cm 0.4cm;
								}
								ul.border-land {
									margin: 0;
									padding: 0;
									display: block;
									width: 100%;
									padding-left: 65px;
								}
								ul.border-land li {
									float: left;
									width: 50%;
									list-style: none;
								}
								span.property_note{
									white-space: pre-line; display: block; width: 100%; margin-left: 65px;
								}
								strong {
									font-weight:bold !important;
								}
								.noted{
									white-space: pre-wrap;
									word-wrap: break-word;
									word-break: break-all;
									line-height:14px;font-weight: normal !important;
									padding: 4px 2px !important;				 
								}
								@media print {
								  table.breakPage {page-break-after: always;}
									@page {
									  margin-bottom:0cm;
									}
								}
								
							</style>
								<table class="breakPage" width="100%" style="font-family:'Times New Roman','Khmer OS Siemreap'; padding:0; margin:0;border:0px;" >
										<tr>
											<td width="30%" valign="top" style="text-align: center;">
											<?php $imagelogo = $this->baseUrl()."/images/logo.jpg";
												if (!empty($this->agreement['project_logo'])){
													$imagelogo = $this->baseUrl()."/images/projects/".$this->agreement['project_logo'];
												}
												?>
												<img src="<?php echo $imagelogo;?>" style="max-width:100%; height: 80px; margin-top: 10px;">
											</td>
											<td width="40%" align="center" valign="top">
												<span style=" font-family:'Khmer OS Muol Light'; text-align:center; line-height:32px !important; font-size:18px; ">ព្រះរាជាណាចក្រកម្ពុជា</span>
												<span style=" font-family:'Khmer OS Muol Light'; text-align:center; line-height:32px !important; width: 100%; display: block; font-size:16px; "><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
												<span style=" text-align:center;line-height:55px !important;margin:5px 0px; width: 100%; display: block; font-size:15px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/style.png" height="12px"></span>
												<span style=" font-family:'Khmer OS Muol Light'; padding:2px 0; text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; "><?php echo $tr->translate("លិខិតប្រគល់-ទទួលប្រាក់");?></span>
											</td>
											<td width="30%"></td>
										 </tr>
										 
										 <tr>
											<td colspan="3" align="center">
												<span style=" margin-top:35px; text-align:left; line-height:28px; width: 100%; display: block; ">
													<span style="font-family:'Khmer OS Muol Light';">យោង ៖ </span>  កិច្ចសន្យាលក់-ទិញផ្ទះ ចុះថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['agreement_date'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['agreement_date'])));?> 
													ផ្ទះលេខ <strong><?php echo $this->agreement['property_title'];?></strong>
												</span>
											</td>
										 </tr>
										 <tr>
											  <td colspan="3" align="center">
											  </td>
										 </tr>
										 
										 <tr>
											<td colspan="3" style="text-align: justify;">
												<?php 
													
													$sex="ប្រុស";
													$title="លោក";
													
													if($this->agreement['p_sex']==2){
														$sex="ស្រី";
														$title="លោកស្រី";
													}
													$sexWithManager="ប្រុស";
													$titleWithManager="លោក";
													if($this->agreement['w_sex']==2){
														$sexWithManager="ស្រី";
														$titleWithManager="លោកស្រី";
													}
													$project_location=$this->agreement['project_location'];
													$address=$tr->translate("ADDRESS_COMPANY");//"ផ្ទះលេខ ៥សេ ផ្លូវជាតិលេខ៤ ភូមិកន្ទោកជើង សង្កាត់កន្ទោក ខណ្ឌពោធិ៍សែនជ័យ រាជធានី ភ្នំពេញ";
													$wing_phone_getMoney="070 924 701";
												
													$projectName="អង្គរ អ៊ីកូ រ៉េស៊ីដេន (Angkor Eco Residence)";
													$amountProperty=1;
													 if (!empty($this->agreement['old_land_id'])){
														$idse = explode(",", $this->agreement['old_land_id']);
														$amountProperty = count($idse);
													}
													
													
												?>
												<span style="margin:0 auto;font-family:'Times New Roman','Khmer OS Siemreap';text-align: justify; text-justify: inter-word;font-weight: normal !important;">
													<span style="text-align:left; min-width: 100%; display: inline-block;">
														<span class="margin-left">&nbsp;</span>
														<?php echo $titleRepresent;?> <span style=" font-weight:600;"><?php echo $representName;?></span>
														កើតនៅថ្ងៃទី  <strong><?php echo $dbparmeter->getNumberInkhmer(date("d-m-Y",strtotime($representDate))); ?></strong>
														 កាន់អត្តសញ្ញាណប័ណ្ណលេខ  <strong><?php echo $dbparmeter->getNumberInkhmer($representIDNo);?></strong> 
														
														<!--
														<?php if(!empty($this->agreement['w_manager_namekh'])){?>
														និង <?php echo $titleWithManager;?> <span style=" font-weight:600;"><?php echo $this->agreement['w_manager_namekh'];?></span>
														កើតនៅថ្ងៃទី <strong><?php echo $dbparmeter->getNumberInkhmer(date("d-m-Y",strtotime($this->agreement['w_dob']))); ?></strong> 
														កាន់អត្តសញ្ញាណប័ណ្ណលេខ  <strong><?php echo $dbparmeter->getNumberInkhmer($this->agreement['w_manager_nation_id']);?></strong> 
														<?php }?>
														-->
														មានទីលំនៅ<?php echo $representAddress;?> 
														លេខទូរស័ព្ទ <?php echo $dbparmeter->getNumberInkhmer($representPhone);?> 
														តទៅនេះត្រូវបានហៅថាជាអ្នកតំណាងឲ្យម្ចាស់គម្រោង <strong><?php echo $projectName;?> ឬភាគី(ក)</strong> ។<br />
														
														<?php echo $representPrefixWord;?>បានប្រគល់ប្រាក់ចំនួន <strong>USD <?php echo number_format($this->agreement['amountReturnBack'],2);?></strong> ជាអក្សរ (<strong><span id="lableAmountRefundKh" style="font-family:'Khmer OS Siemreap';"></span>ដុល្លារអាមេរិកគត់</strong> )
														
														<script>
															a_sold ='<?php echo ($this->agreement['amountReturnBack']) ?>';
															money_khmersold=read_money_in_khmer(a_sold);
															
															decimalmoney_khmersold='<?php echo substr(number_format($this->agreement['amountReturnBack'],2),-2);?>';
															str_centsold = 'សេន';
															if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
															last_number_sold='<?php echo substr(number_format($this->agreement['amountReturnBack'],2),-1);?>';
															
															if(last_number_sold<=0){last_number_sold='';}
															money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
															dojo.byId('lableAmountRefundKh').innerHTML=money_khmersold+" ";
													</script>
													</span>
													<span style="font-weight:600; text-align:center; min-width: 100%; display: inline-block;">ទៅឲ្យ</span>
													<span style="text-align:left; min-width: 100%; display: inline-block;">
													
													<?php 
														$sexClient="ប្រុស";
														$titleClient="លោក";
														if($this->agreement['sex']==2){
															$sexClient="ស្រី";
															$titleClient="លោកស្រី";
														}
														$sexWithClient="ប្រុស";
														$titleWithClient="លោក";
														if($this->agreement['ksex']==2){
															$sexWithClient="ស្រី";
															$titleWithClient="លោកស្រី";
														}
													?>
														<span class="margin-left">&nbsp;</span>
														<?php echo getGenderTitle($this->agreement['gendertitle']); //echo $titleClient;?> <span class="value" style="min-width:30px; font-weight:600;"><?php echo $this->agreement['client_namekh'];?></span>
														កើតនៅថ្ងៃទី  <strong><?php echo $dbparmeter->getNumberInkhmer(date("d-m-Y",strtotime($this->agreement['dob']))); ?></strong> 
														កាន់<?php echo $this->agreement['client_d_type'];?>លេខ <span class="value" style="min-width:30px; font-weight:600;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['client_nation_id']);?></span>	
														មានទីលំនៅភូមិ <span ><?php echo str_replace("ភូមិ", "", $this->agreement['client_village_kh']);?></span>
														 ឃុំ/សង្កាត់  <span ><?php echo $this->agreement['client_commune_kh'];?></span>
														 ស្រុក/ខណ្ឌ/ក្រុង  <span ><?php echo $this->agreement['client_districtkh'];?></span>
														 ខេត្ដ/រាជធានី  <span >&nbsp;<?php echo $this->agreement['client_province_kh'];?></span> 
														 លេខទូរស័ព្ទ <span class="value" style="min-width:30px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['client_phone']);?></span>
														<?php if(!empty($this->agreement['hname_kh'])){?>
														និង <?php echo getGenderTitle($this->agreement['gendertitle1']);//echo $titleWithClient;?> <span style="font-weight:600;"><?php echo $this->agreement['hname_kh'];?></span> 
														ភេទ <span class="value" style="min-width:30px;"><?php echo $this->agreement['partner_gender'];?></span> 
														កើតនៅថ្ងៃទី  <strong><?php echo $dbparmeter->getNumberInkhmer(date("d-m-Y",strtotime($this->agreement['dob_buywith']))); ?></strong> 
														កាន់<?php echo $this->agreement['joint_doc_type'];?>លេខ <span class="value" style="min-width:30px; font-weight:600;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['rid_no']);?></span>  
														មានទីលំនៅភូមិ <span class="value" style="min-width:30px;"><?php echo str_replace("ភូមិ", "",$this->agreement['w_client_village_kh']);?></span>
														ឃុំ/សង្កាត់ <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_commune_kh'];?></span> 
														ស្រុក/ខណ្ឌ/ក្រុង <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_districtkh'];?></span> 
														ខេត្ត/រាជធានី  <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_province_kh'];?></span> 
														 លេខទូរស័ព្ទ <span class="value" style="min-width:30px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['with_phone']);?></span>
														<?php }?> 
														តទៅនេះត្រូវបានហៅកាត់ថា <strong>ភាគី(ខ)</strong>។

													</span>
												</span>
												<div style=" text-align:justify;">
													<span class="margin-left">&nbsp;</span>ទឹកប្រាក់នេះជាប្រាក់កក់នៃការព្រមព្រៀងស្តីពីការទិញផ្ទះនៅក្នុងគម្រោង <strong><?php echo $projectName;?></strong>   ដែលមានអាសយដ្ឋានស្ថិតនៅ<?php echo $this->agreement['project_location'];?>។
													
													
												</div>
												
												
											</td>
										</tr>
										<tr>
											<td colspan="3" valign="top">
												<div style="  text-align: right;  margin-right: 40px;">
													សៀមរាប,  ថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['create_date'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['create_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['create_date'])));?>
												</div>
												<div>
													<div style="font-family:'Khmer OS Muol Light'; width:39%; text-align: center; display: inline-block;">
														<span class="value">អ្នកប្រគល់</span>
													</div>
													<div style="font-family:'Khmer OS Muol Light'; width:20%; text-align: center; display: inline-block;">
														<span class="value">សាក្សី</span>
													</div>
													
													<div style="font-family:'Khmer OS Muol Light'; white-space:nowrap; width:39%; text-align: center; display: inline-block;">
														<span class="value">អ្នកទទួល</span>
													</div>
													<div style="height: 110px;">
													</div>
													<div style="width:39%;text-align: center; display: inline-block;">
														<span class="border_bt  value" style="width:80%;" >&nbsp;<strong><?php echo $representName;?></strong></span>
													</div>
													
													<div style="width:20%; text-align: center; display: inline-block;">
														<span class="border_bt  value" style="width:80%;" ><strong><?php //echo $this->agreement['witness_ii'];?></strong></span>
													</div>
													<div style="width:39%; text-align: center; display: inline-block;">
														<span class="border_bt  value" style="width:80%; white-space: nowrap;text-align: center;" >&nbsp;&nbsp;<strong><?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"-".$this->agreement['hname_kh']:"";?></strong>&nbsp;</span>
													</div>
												</div>
											</td>
										 </tr>
								</table>
								
							  <div id="printfooter" style=" font-size: 8px;font-family:'Khmer OS Siemreap';width:100%;">
									<span style=" font-size: 10px;"></span>
							  </div> 
						</div>
					<?php }else{?>
					
					<div id="divPrint" style="position: relative;" >
							<style>		
								#padding-left-p-2{
									padding-left:105px !important;	
								}
								.padding-buttom{
									margin-top:-10px !important;
								}
								tr td,tr td h2,p,pre,span{ 
									font-size: 16px ; line-height:36px;
								}
								#padding-left{
									padding-left: 18px;
								}
								#bold-padding-right{
									margin-right:15px;
									font-family:'Times New Roman','Khmer OS Siemreap';
								}
								#padding-left-2{
								
									padding-left:15px;
								}
								#padding-left-p-2{
								   margin-top:-1px; 
								   padding-left: 85px;	
								}
								#padding-left-p{
									padding-left: 105px;
								}
								th{padding: 5px;}
								span.value{ line-height:10px;display: inline-block; text-align: center;}
								span.child {display:block; margin-left:25px; line-height: 22px;}
								.value_label{
									border-bottom: dashed 1px #000;
									line-height: 12px !important;
									min-width: 100%;
									display: inline-block;
								}
								body{
									position: relative;
								}
								#printfooter {
									position: absolute;
									bottom: 0;
									position: fixed;
									display: block ;
								}
								span.margin-left{
									margin-left:35px; display: inline-block;
								}
								ul.blogsub li{
									list-style-type: square;
									line-height: 24px;
								}
								ul.reference li{
									line-height: 24px;
									list-style: none;
								}
								ul.blogsub{
									padding:0;margin:0;
								}
								#printfooter {
									position: absolute;
									bottom:-5;
									position: fixed;
									display: block ;
								}
								body {
									margin:0.4cm 0.4cm 0cm 0.4cm;
								}
								ul.border-land {
									margin: 0;
									padding: 0;
									display: block;
									width: 100%;
									padding-left: 65px;
								}
								ul.border-land li {
									float: left;
									width: 50%;
									list-style: none;
								}
								span.property_note{
									white-space: pre-line; display: block; width: 100%; margin-left: 65px;
								}
								strong {
									font-weight:bold !important;
								}
								.noted{
									white-space: pre-wrap;
									word-wrap: break-word;
									word-break: break-all;
									line-height:14px;font-weight: normal !important;
									padding: 4px 2px !important;				 
								}
								@media print {
								  table.breakPage {page-break-after: always;}
									@page {
									  margin-bottom:0cm;
									}
								}
								
							</style>
								<table class="breakPage" width="100%" style="font-family:'Times New Roman','Khmer OS Siemreap'; padding:0; margin:0;border:0px;" >
										<tr>
											<td width="30%" valign="top" style="text-align: center;">
											<?php $imagelogo = $this->baseUrl()."/images/logo.jpg";
												if (!empty($this->agreement['project_logo'])){
													$imagelogo = $this->baseUrl()."/images/projects/".$this->agreement['project_logo'];
												}
												?>
												<img src="<?php echo $imagelogo;?>" style="max-width:100%; height: 80px; margin-top: 10px;">
											</td>
											<td width="40%" align="center" valign="top">
												<span style=" font-family:'Khmer OS Muol Light'; text-align:center; line-height:32px !important; font-size:18px; ">ព្រះរាជាណាចក្រកម្ពុជា</span>
												<span style=" font-family:'Khmer OS Muol Light'; text-align:center; line-height:32px !important; width: 100%; display: block; font-size:16px; "><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
												<span style=" text-align:center;line-height:55px !important;margin:5px 0px; width: 100%; display: block; font-size:15px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/style.png" height="12px"></span>
												<span style=" font-family:'Khmer OS Muol Light'; padding:2px 0; text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; "><?php echo $tr->translate("លិខិតប្រគល់-ទទួលប្រាក់");?></span>
											</td>
											<td width="30%"></td>
										 </tr>
										 
										 <tr>
											<td colspan="3" align="center">
												<span style="margin-top:35px; text-align:left; line-height:28px; width: 100%; display: block; ">
													<span style="font-family:'Khmer OS Muol Light';">យោង ៖ </span>  កិច្ចសន្យាលក់-ទិញផ្ទះ ចុះថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['agreement_date'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['agreement_date'])));?> 
													ផ្ទះលេខ <strong><?php echo $this->agreement['property_title'];?></strong>
												</span>
											</td>
										 </tr>
										 <tr>
											  <td colspan="3" align="center">
											  </td>
										 </tr>
										 
										 <tr>
											<td colspan="3" style="text-align: justify;">
												<?php 
													
													$sex="ប្រុស";
													$title="លោក";
													
													if($this->agreement['p_sex']==2){
														$sex="ស្រី";
														$title="លោកស្រី";
													}
													$sexWithManager="ប្រុស";
													$titleWithManager="លោក";
													if($this->agreement['w_sex']==2){
														$sexWithManager="ស្រី";
														$titleWithManager="លោកស្រី";
													}
													$project_location=$this->agreement['project_location'];
													$address=$tr->translate("ADDRESS_COMPANY");//"ផ្ទះលេខ ៥សេ ផ្លូវជាតិលេខ៤ ភូមិកន្ទោកជើង សង្កាត់កន្ទោក ខណ្ឌពោធិ៍សែនជ័យ រាជធានី ភ្នំពេញ";
													$wing_phone_getMoney="070 924 701";
												
													$projectName="អង្គរ សិរីមង្គល (Angkor Serey Mongkol )";
													$amountProperty=1;
													 if (!empty($this->agreement['old_land_id'])){
														$idse = explode(",", $this->agreement['old_land_id']);
														$amountProperty = count($idse);
													}
													
													
												?>
												<span style="margin:0 auto;font-family:'Times New Roman','Khmer OS Siemreap';text-align: justify; text-justify: inter-word;font-weight: normal !important;">
													<span style="text-align:left; min-width: 100%; display: inline-block;">
														<span class="margin-left">&nbsp;</span>
														<?php echo $titleRepresent;?> <span style=" font-weight:600;"><?php echo $representName;?></span>
														កើតនៅថ្ងៃទី  <strong><?php echo $dbparmeter->getNumberInkhmer(date("d-m-Y",strtotime($representDate))); ?></strong>
														 កាន់អត្តសញ្ញាណប័ណ្ណលេខ  <strong><?php echo $dbparmeter->getNumberInkhmer($representIDNo);?></strong> 
														
														<!--
														<?php if(!empty($this->agreement['w_manager_namekh'])){?>
														និង <?php echo $titleWithManager;?> <span style=" font-weight:600;"><?php echo $this->agreement['w_manager_namekh'];?></span>
														កើតនៅថ្ងៃទី <strong><?php echo $dbparmeter->getNumberInkhmer(date("d-m-Y",strtotime($this->agreement['w_dob']))); ?></strong> 
														កាន់អត្តសញ្ញាណប័ណ្ណលេខ  <strong><?php echo $dbparmeter->getNumberInkhmer($this->agreement['w_manager_nation_id']);?></strong> 
														<?php }?>
														-->
														មានទីលំនៅ<?php echo $representAddress;?> 
														លេខទូរស័ព្ទ <?php echo $dbparmeter->getNumberInkhmer($representPhone);?> 
														តទៅនេះត្រូវបានហៅថាជាអ្នកតំណាងឲ្យម្ចាស់គម្រោង <strong><?php echo $projectName;?> ឬភាគី(ក)</strong> ។<br />
														
														<?php echo $representPrefixWord;?>បានប្រគល់ប្រាក់ចំនួន <strong>USD <?php echo number_format($this->agreement['amountReturnBack'],2);?></strong> ជាអក្សរ (<strong><span id="lableAmountRefundKh" style="font-family:'Khmer OS Siemreap';"></span>ដុល្លារអាមេរិកគត់</strong> )
														
														<script>
															a_sold ='<?php echo ($this->agreement['amountReturnBack']) ?>';
															money_khmersold=read_money_in_khmer(a_sold);
															
															decimalmoney_khmersold='<?php echo substr(number_format($this->agreement['amountReturnBack'],2),-2);?>';
															str_centsold = 'សេន';
															if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
															last_number_sold='<?php echo substr(number_format($this->agreement['amountReturnBack'],2),-1);?>';
															
															if(last_number_sold<=0){last_number_sold='';}
															money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
															dojo.byId('lableAmountRefundKh').innerHTML=money_khmersold+" ";
													</script>
													</span>
													<span style="font-weight:600; text-align:center; min-width: 100%; display: inline-block;">ទៅឲ្យ</span>
													<span style="text-align:left; min-width: 100%; display: inline-block;">
													
													<?php 
														$sexClient="ប្រុស";
														$titleClient="លោក";
														if($this->agreement['sex']==2){
															$sexClient="ស្រី";
															$titleClient="លោកស្រី";
														}
														$sexWithClient="ប្រុស";
														$titleWithClient="លោក";
														if($this->agreement['ksex']==2){
															$sexWithClient="ស្រី";
															$titleWithClient="លោកស្រី";
														}
													?>
														<span class="margin-left">&nbsp;</span>
														<?php echo getGenderTitle($this->agreement['gendertitle']); //echo $titleClient;?> <span class="value" style="min-width:30px; font-weight:600;"><?php echo $this->agreement['client_namekh'];?></span>
														កើតនៅថ្ងៃទី  <strong><?php echo $dbparmeter->getNumberInkhmer(date("d-m-Y",strtotime($this->agreement['dob']))); ?></strong> 
														កាន់<?php echo $this->agreement['client_d_type'];?>លេខ <span class="value" style="min-width:30px; font-weight:600;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['client_nation_id']);?></span>	
														មានទីលំនៅភូមិ <span ><?php echo str_replace("ភូមិ", "", $this->agreement['client_village_kh']);?></span>
														 ឃុំ/សង្កាត់  <span ><?php echo $this->agreement['client_commune_kh'];?></span>
														 ស្រុក/ខណ្ឌ/ក្រុង  <span ><?php echo $this->agreement['client_districtkh'];?></span>
														 ខេត្ដ/រាជធានី  <span >&nbsp;<?php echo $this->agreement['client_province_kh'];?></span> 
														 លេខទូរស័ព្ទ <span class="value" style="min-width:30px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['client_phone']);?></span>
														<?php if(!empty($this->agreement['hname_kh'])){?>
														និង <?php echo getGenderTitle($this->agreement['gendertitle1']);//echo $titleWithClient;?> <span style="font-weight:600;"><?php echo $this->agreement['hname_kh'];?></span> 
														ភេទ <span class="value" style="min-width:30px;"><?php echo $this->agreement['partner_gender'];?></span> 
														កើតនៅថ្ងៃទី  <strong><?php echo $dbparmeter->getNumberInkhmer(date("d-m-Y",strtotime($this->agreement['dob_buywith']))); ?></strong> 
														កាន់<?php echo $this->agreement['joint_doc_type'];?>លេខ <span class="value" style="min-width:30px; font-weight:600;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['rid_no']);?></span>  
														មានទីលំនៅភូមិ <span class="value" style="min-width:30px;"><?php echo str_replace("ភូមិ", "",$this->agreement['w_client_village_kh']);?></span>
														ឃុំ/សង្កាត់ <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_commune_kh'];?></span> 
														ស្រុក/ខណ្ឌ/ក្រុង <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_districtkh'];?></span> 
														ខេត្ត/រាជធានី  <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_province_kh'];?></span> 
														 លេខទូរស័ព្ទ <span class="value" style="min-width:30px;"><?php echo $dbparmeter->getNumberInkhmer($this->agreement['with_phone']);?></span>
														<?php }?> 
														តទៅនេះត្រូវបានហៅកាត់ថា <strong>ភាគី(ខ)</strong>។

													</span>
												</span>
												<div style=" text-align:justify;">
													<span class="margin-left">&nbsp;</span>ទឹកប្រាក់នេះជាប្រាក់កក់នៃការព្រមព្រៀងស្តីពីការទិញផ្ទះនៅក្នុងគម្រោង <strong><?php echo $projectName;?></strong>   ដែលមានអាសយដ្ឋានស្ថិតនៅ<?php echo $this->agreement['project_location'];?>។
													
													
												</div>
												
												
											</td>
										</tr>
										<tr>
											<td colspan="3" valign="top">
												<div style="  text-align: right;  margin-right: 40px;">
													សៀមរាប,  ថ្ងៃទី <?php echo $dbparmeter->getNumberInkhmer(date("d",strtotime($this->agreement['create_date'])));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['create_date']))];?> ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer(date("Y",strtotime($this->agreement['create_date'])));?>
												</div>
												<div>
													<div style="font-family:'Khmer OS Muol Light'; width:39%; text-align: center; display: inline-block;">
														<span class="value">អ្នកប្រគល់</span>
													</div>
													<div style="font-family:'Khmer OS Muol Light'; width:20%; text-align: center; display: inline-block;">
														<span class="value">សាក្សី</span>
													</div>
													
													<div style="font-family:'Khmer OS Muol Light'; white-space:nowrap; width:39%; text-align: center; display: inline-block;">
														<span class="value">អ្នកទទួល</span>
													</div>
													<div style="height: 110px;">
													</div>
													<div style="width:39%;text-align: center; display: inline-block;">
														<span class="border_bt  value" style="width:80%;" >&nbsp;<strong><?php echo $representName;?></strong></span>
													</div>
													
													<div style="width:20%; text-align: center; display: inline-block;">
														<span class="border_bt  value" style="width:80%;" ><strong><?php //echo $this->agreement['witness_ii'];?></strong></span>
													</div>
													<div style="width:39%; text-align: center; display: inline-block;">
														<span class="border_bt  value" style="width:80%; white-space: nowrap;text-align: center;" >&nbsp;&nbsp;<strong><?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"-".$this->agreement['hname_kh']:"";?></strong>&nbsp;</span>
													</div>
												</div>
											</td>
										 </tr>
								</table>
								
							  <div id="printfooter" style=" font-size: 8px;font-family:'Khmer OS Siemreap';width:100%;">
									<span style=" font-size: 10px;"></span>
							  </div> 
						</div>
					
					<?php } ?>
			    </td>	
			</tr>
		</table>
	</div>
<script>
function doPrint1() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint1').innerHTML;
	window.frames["print_frame"].window.focus();
	window.frames["print_frame"].window.print();
}
function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
}
</script>