<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$db  = new Report_Model_DbTable_DbParamater();
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("របាយការណ៍ចំណូលចំណាយ");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('របាយការណ៍ចំណូលចំណាយ');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'paramater','action'=>'rpt-revenue-expense')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('branch_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('property_type');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('streetlist');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('start_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit">
		   		<?php echo $tr->translate("SEARCH");?></button>
				</div>
			</div>		
		</div>
	</form> 
	<div style="min-height:22cm; margin:0 auto;">
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
		<tr>
	    	<td align="center">
	    	 <div id="divPrint">
	    	 		<style>
						tr td.border_bottom{border-bottom: solid 1px #000;}
						tr td.border_double{border-bottom: double #000;}
						.style{
							line-height: 20px;font-size: 14px !important;
							font-family: 'Times New Roman','Khmer OS Battambang';
						}
						th{padding: 5px;}
					</style>
		        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
		        		<tr>
			                <td width="30%"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" style="height:80px;max-width: 100%;"></td>
			                <td width="40%" valign="top">
			                <ul style="list-style: none;">
				                <li style="white-space:nowrap;line-height:25px;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
				                <li style="line-height:20px;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("របាយការណ៍ចំណូលចំណាយ");?></li>
				                <li style="line-height:25px;text-align:center; font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php if (!empty($this->list_end_date['start_date'])){ echo  date("d-m-Y",strtotime($this->list_end_date['start_date']))." To ".date("d-m-Y",strtotime($this->list_end_date['end_date']));}?></li>
			                </ul>
			                </td>
			                <td width="30%"></td>
		             </tr> 
	             <?php $total_income = 0; $total_expense = 0; $net_income =0;?>
	             <tr>
	             	<td colspan="3">
	             		<table  width="100%" style="border-collapse:collapse; font-size: 14px; line-height: 18px;" >  
	             			<tr>
	             				<td colspan="3" style="font-size:14px;font-family:'Times New Roman','Khmer OS Muol Light'"> <?php echo $tr->translate("ចំណូលពីការលក់");?> </td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td align="right">&nbsp;<strong style="font-family: Helvetica;font-weight: bold;">&nbsp;</strong></td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			<tr height="21px">
	             				<td style="width: 20%;">&nbsp;</td>
	             				<td >&nbsp;កក់ប្រាក់&nbsp;</td>
	             				<td class="" align="right">&nbsp;<?php echo  number_format($this->money_deposit['recieve_amount'],2);?>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td >&nbsp;</td>
	             			</tr>
	             			<tr height="21px">
	             				<td style="width: 20%;">&nbsp;</td>
	             				<td >&nbsp;កក់បង្គ្រប់&nbsp;</td>
	             				<td class="" align="right">&nbsp;<?php echo number_format($this->money_schedule['recieve_amount'],2);?>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td >&nbsp;</td>
	             			</tr>
	             			<tr height="21px">
	             				<td style="width: 20%;">&nbsp;</td>
	             				<td >&nbsp;រំលស់ប្រចាំខែ&nbsp;</td>
	             				<td class="" align="right">&nbsp;<?php echo  number_format($this->money_install['recieve_amount'],2);?>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			
	             			<?php 
	             			$total_other_income=0;
	             			
	             			if (!empty($this->income_changehouse)){ foreach ($this->income_changehouse as $rs){//ចំណូលកែផ្ទះ
	             				$total_other_income=$total_other_income+$rs['total_amount'];
	             				?>
	             			<tr height="21px">
	             				<td style="width: 20%;">&nbsp;</td>
	             				<td >&nbsp;- <?php echo $rs['category_name'];?>&nbsp;</td>
	             				<td class="" align="right">&nbsp;<?php echo  number_format($rs['total_amount'],2);?>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			<?php
									}
								}?>
	             			<?php 
		             			$beginingbalance = 0;
		             			$parent=0;
	             			
	             			if (!empty($this->income)){ ?>
	             			<tr>
	             				<td colspan="3" style=" font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"> <?php echo $tr->translate("ចំណូលផ្សេងៗ");?> </td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td align="right">&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td >&nbsp;</td>
	             			</tr>
	             			<?php 
	             			
	             			foreach ($this->income as $income_cate){ 
		             				if($income_cate['is_beginning']==1){
		             					$beginingbalance = $beginingbalance+$income_cate['total_amount']; 
		             					continue;
		             				}
	             					$total_other_income = $total_other_income+$income_cate['total_amount'];
	             				?>
	             				<?php if ( $income_cate['parent']!=0 AND $parent != $income_cate['parent']){?>
	             					<tr height="21px">
			             				<td style="width: 20%;">&nbsp;</td>
			             				<td>&nbsp;<strong><?php echo $income_cate['parent_title'];?></strong>&nbsp;</td>
			             				<td class="" align="right">&nbsp;&nbsp;</td>
			             				<td style="width:10px;">&nbsp;</td>
			             				<td></td>
			             				<td style="width:10px;">&nbsp;</td>
			             				<td>&nbsp;</td>
			             				<?php $parent = $income_cate['parent'];?>
			             			</tr>
	             				<?php }?>
	             				<?php if ( $income_cate['parent']==0){?>
	             					<tr height="21px">
			             				<td style="width: 20%;">&nbsp;</td>
			             				<td >&nbsp;<?php echo $income_cate['category_name'];?>&nbsp;</td>
			             				<td class="" align="right">&nbsp;<?php echo  number_format($income_cate['total_amount'],2);?>&nbsp;</td>
			             				<td style="width:10px;">&nbsp;</td>
			             				<td>&nbsp;</td>
			             				<td style="width:10px;">&nbsp;</td>
			             				<td>&nbsp;</td>
			             			</tr>
	             				<?php }else{?>
			             			<tr height="21px">
			             				<td style="width: 20%;">&nbsp;</td>
			             				<td >&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $income_cate['category_name'];?>&nbsp;</td>
			             				<td class="" align="right">&nbsp;<?php echo  number_format($income_cate['total_amount'],2);?>&nbsp;</td>
			             				<td style="width:10px;">&nbsp;</td>
			             				<td>&nbsp;</td>
			             				<td style="width:10px;">&nbsp;</td>
			             				<td >&nbsp;</td>
			             			</tr>
	             				<?php }?>
	             			<?php } 
							}
	             			$total_income = $total_other_income+$this->saleicome['recieve_amount'];?>
	             			<tr>
	             				<td style="width: 20%;">&nbsp;</td>
	             				<td >&nbsp;</td>
	             				<td style="text-align:right ;font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"> <?php echo $tr->translate("ចំណូលសរុប");?>  </td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td class="border_bottom" align="right">&nbsp;<strong style="font-family: Helvetica;font-weight: bold;"><?php echo number_format($total_income,2);;?></strong>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td >&nbsp;</td>
	             			</tr>
	             			<tr>
	             				<td colspan="3" style=" font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"> <?php echo $tr->translate("ចំណាយផ្សេងៗ");?> </td>
	             				<td align="right">&nbsp;&nbsp;</td>
	             			</tr>
	             			<?php 
	             			$parent="";
	             			if (!empty($this->expense)) foreach ($this->expense as $expense_cate){ 
	             					$total_expense = $total_expense +$expense_cate['total_amount'];?>
	             			<?php if ( $expense_cate['parent']!=0 AND $parent != $expense_cate['parent']){?>
	             				<tr height="21px">
		             				<td style="width: 20%;">&nbsp;</td>
		             				<td>&nbsp;<strong><?php echo $expense_cate['parent_title'];?></strong>&nbsp;</td>
		             				<td class="" align="right"></td>
		             				<td style="width:10px;">&nbsp;</td>
		             				<td></td>
		             				<td style="width:10px;">&nbsp;</td>
		             				<td>&nbsp;</td>
		             				<?php $parent = $expense_cate['parent'];?>
		             			</tr>
		             		<?php }?>
		             		<?php if ( $expense_cate['parent']==0){?>
		             			<tr height="21px">
		             				<td style="width: 20%;">&nbsp;</td>
		             				<td>&nbsp;<?php echo $expense_cate['category_name'];?>&nbsp;</td>
		             				<td class="" align="right">&nbsp;<?php echo number_format($expense_cate['total_amount'],2);?>&nbsp;</td>
		             				<td style="width:10px;">&nbsp;</td>
		             				<td></td>
		             				<td style="width:10px;">&nbsp;</td>
		             				<td>&nbsp;</td>
		             			</tr>
		             		<?php }else{?>
		             			<tr height="21px">
		             				<td style="width: 20%;">&nbsp;</td>
		             				<td>&nbsp;&nbsp;&nbsp;&nbsp;<?php echo $expense_cate['category_name'];?>&nbsp;</td>
		             				<td class="" align="right">&nbsp;<?php echo number_format($expense_cate['total_amount'],2);?>&nbsp;</td>
		             				<td style="width:10px;">&nbsp;</td>
		             				<td></td>
		             				<td style="width:10px;">&nbsp;</td>
		             				<td>&nbsp;</td>
		             			</tr>
	             			<?php }?>
	             			<?php }?>	             			
	             			<!-- for expense from commission -->
	             			<?php if (!empty($this->expense_comission)) foreach ($this->expense_comission as $comission){ $total_expense = $total_expense + $comission['total_amount'];?>
	             			<tr height="21px">
	             				<td style="width: 20%;">&nbsp;</td>
	             				<td >&nbsp;<?php echo $comission['category_name'];?>&nbsp;</td>
	             				<td class="" align="right">&nbsp;<?php echo number_format($comission['total_amount'],2);?>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			<?php }?>
	             			<tr height="22px">
	             				<td style="width: 20%;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             				<td style="text-align:right;font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"> <?php echo $tr->translate("ចំណាយសរុប");?> </td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td class="border_bottom" align="right">&nbsp;<strong style="font-family: Helvetica;font-weight: bold;"><?php echo number_format($total_expense,2);?>&nbsp;</strong></td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             			</tr>
	             			<?php $net_income = $total_income-$total_expense;
	             			?>
	             			<tr style="padding-top: 100px;">
	             				<td style="width: 20%;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             				<td style="text-align:right ;font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("ប្រាក់ចំណេញសរុប");?> </td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td>&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td class="border_bottom" align="right"><strong style="font-family: Helvetica;font-weight: bold;">&nbsp;<?php if ($net_income<0){echo "(".number_format(abs($net_income),2).")";}else{ echo number_format($net_income,2);}?>&nbsp;</strong></td>
	             			</tr>
	             			<tr>
	             				<td colspan="3" style=" font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"> <?php echo $tr->translate("សមតុល្យដើមគ្រា")." (Beginning Balance)";?> </td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td align="right">&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td class="border_bottom" align="right">&nbsp;<strong style="font-family: Helvetica;font-weight: bold;"><?php echo number_format($beginingbalance,2);?></strong></td>
	             			</tr>
	             			<tr>
	             				<td colspan="3" style=" font-size:14px; font-family:'Times New Roman','Khmer OS Muol Light'"> <?php echo $tr->translate("សមតុល្យចុងក្រោយ")." (Ending Balance)"?> </td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<td align="right">&nbsp;</td>
	             				<td style="width:10px;">&nbsp;</td>
	             				<?php $ending_balance = $beginingbalance+$net_income;?>
	             				<td class="border_double" align="right">&nbsp;<strong style="font-family: Helvetica;font-weight: bold;"><?php if ($ending_balance<0){echo "(".number_format(abs($ending_balance),2).")";}else{ echo number_format($ending_balance,2);}?></strong></td>
	             			</tr>
	             		</table>
	             	</td>
	             </tr>
	            </table>
	            <br />
				   <?php echo $this->footerReport;?>
	            </div>
	    	</td>
	    </tr>
	</table>
	</div>
</div>
<style>

.select2-container, .select2-drop, .select2-search, .select2-search input {
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
input#e15 {
    display: none;
}
.select2-container {
    margin: 0;
    position: relative;
    display: inline-block;
    vertical-align: middle;
}
.select2-container-multi .select2-choices {
    min-height: 26px;
}
.select2-container-multi .select2-choices {
    height: auto !important;
    height: 1%;
    margin: 0;
    padding: 0 5px 0 0;
    position: relative;
    border: 1px solid #aaa;
    cursor: text;
    overflow: hidden;
    background-color: #fff;
    background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, color-stop(1%, #eee), color-stop(15%, #fff));
    background-image: -webkit-linear-gradient(top, #eee 1%, #fff 15%);
    background-image: -moz-linear-gradient(top, #eee 1%, #fff 15%);
    background-image: linear-gradient(to bottom, #eee 1%, #fff 15%);
}
.select2-container-multi .select2-choices .select2-search-choice {
    padding: 3px 5px 3px 18px;
    margin: 3px 0 3px 5px;
    position: relative;
    line-height: 13px;
    color: #333;
    cursor: default;
    border: 1px solid #aaaaaa;
    border-radius: 3px;
    -webkit-box-shadow: 0 0 2px #fff inset, 0 1px 0 rgba(0, 0, 0, 0.05);
    box-shadow: 0 0 2px #fff inset, 0 1px 0 rgba(0, 0, 0, 0.05);
    background-clip: padding-box;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-color: #e4e4e4;
    filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#eeeeee', endColorstr='#f4f4f4', GradientType=0);
    background-image: -webkit-gradient(linear, 0% 0%, 0% 100%, color-stop(20%, #f4f4f4), color-stop(50%, #f0f0f0), color-stop(52%, #e8e8e8), color-stop(100%, #eee));
    background-image: -webkit-linear-gradient(top, #f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eee 100%);
    background-image: -moz-linear-gradient(top, #f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eee 100%);
    background-image: linear-gradient(to bottom, #f4f4f4 20%, #f0f0f0 50%, #e8e8e8 52%, #eee 100%);
}
.select2-container-multi .select2-choices .select2-search-field {
    margin: 0;
    padding: 0;
    white-space: nowrap;
}
.select2-offscreen, .select2-offscreen:focus {
    clip: rect(0 0 0 0) !important;
    width: 1px !important;
    height: 1px !important;
    border: 0 !important;
    margin: 0 !important;
    padding: 0 !important;
    overflow: hidden !important;
    position: absolute !important;
    outline: 0 !important;
    left: 0px !important;
    top: 0px !important;
}
.select2-container-multi .select2-choices .select2-search-field input {
    margin: 1px 0;
    font-family: inherit;
    font-size: 100%;
    color: #666;
    outline: 0;
    border: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
    background: transparent !important;
}
.select2-container-multi .select2-choices li {
    float: left;
    list-style: none;
}
.select2-container-multi .select2-search-choice-close {
    left: 3px;
}
.select2-search-choice-close {
    display: block;
    width: 14px;
    height: 13px;
    position: absolute;
    right: 3px;
    top: 4px;
    font-size: 1px;
    outline: none;
    background: url(<?php echo $this->baseUrl()."/admin/3.5.0/"?>select2.png) right top no-repeat;
}	
.select2-drop.select2-drop-above.select2-drop-active {
    border-top: 1px solid #5897fb;
}
.select2-drop.select2-drop-above {
    margin-top: 1px;
    border-top: 1px solid #aaa;
    border-bottom: 0;
    border-radius: 4px 4px 0 0;
    -webkit-box-shadow: 0 -4px 5px rgba(0, 0, 0, .15);
    box-shadow: 0 -4px 5px rgba(0, 0, 0, .15);
}
.select2-display-none {
    display: none;
}
.select2-drop-active {
    border: 1px solid #5897fb;
    border-top: none;
}
.select2-drop {
    width: 100%;
    margin-top: -1px;
    position: absolute;
    z-index: 9999;
    top: 100%;
    background: #fff;
    color: #000;
    border: 1px solid #aaa;
    border-top: 0;
    border-radius: 0 0 4px 4px;
    -webkit-box-shadow: 0 4px 5px rgba(0, 0, 0, .15);
    box-shadow: 0 4px 5px rgba(0, 0, 0, .15);
}
.select2-results {
    max-height: 200px;
    padding: 0 0 0 4px;
    margin: 4px 4px 4px 0;
    position: relative;
    overflow-x: hidden;
    overflow-y: auto;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
.select2-results .select2-highlighted {
    background: #3875d7;
    color: #fff;
}
.select2-results li {
    list-style: none;
    display: list-item;
    background-image: none;
}
    .select2-results .select2-result-label {
    padding: 3px 7px 4px;
    margin: 0;
    cursor: pointer;
    min-height: 1em;
    -webkit-touch-callout: none;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
}
.select2-results .select2-selected {
    display: none;
}
</style>
 <link href="<?php echo $this->baseUrl()."/admin/"?>/3.5.0/select2.min.css" /> 
 <script src="<?php echo $this->baseUrl()."/admin/"?>/3.5.0/select2.min.js"></script>
 <?php 
	 $tags="";
	 if (!empty($this->street)) foreach ($this->street as $rs){
	 	if (empty($tags)){
	 		$tags = '"'.$rs['id'].'"';
	 	}else{
	 		if (!empty($rs['id'])){
	 		$tags=$tags.',"'.$rs['id'].'"';
	 		}
	 	}
	 } 	
?>
 <script>

require(["dojo/ready"], function(ready){
	ready(function(){
		 $("#e15").select2({tags:[<?php echo $tags;?>],placeholder: "<?php echo $tr->translate("CHOOSE_STREET");?>",allowClear: true});
	});
});
</script>