<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("INVESTOR"));
	$frm = $this->frm_search;
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="glyphicon glyphicon-user" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('INVESTOR');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<div class="card-box">
			<form  action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
	               <div class="col-md-2 col-sm-2 col-xs-12">
	                    <?php echo $frm->getElement('adv_search');?>
	                </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                    <?php echo $frm->getElement('start_date');?>
	                </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                    <?php echo $frm->getElement('end_date');?>
	                </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                    <?php echo $frm->getElement('status');?>
	                </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                    <button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	                </div>
	            </div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
