<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_receipt = $this->url(array('module'=>'report','controller'=>'invest','action'=>'receipt'),null, true)."/id/";

	$frm = $this->frm_search;
	$frmin = $this->frm;
?>
<title><?php echo $tr->translate("CLOSING_WITHDRAWAL");?></title>
<div class="reportblog">
	<div class="card-box">
	   	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CLOSING_WITHDRAWAL');?></h4>
	   		</div>
	   		<div class="col-sm-4 text-right">
	   		</div>
	   	</div>
	</div>
	<div class="card-box">
			<form  action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
	               <div class="col-md-2 col-sm-2 col-xs-12">
	                    <?php echo $frm->getElement('adv_search');?>
	                </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                    <?php echo $frmin->getElement('investor_id');?>
	                </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                    <?php echo $frm->getElement('start_date');?>
	                </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                    <?php echo $frm->getElement('end_date');?>
	                </div>
	                <div class="col-md-2 col-sm-2 col-xs-12">
	                    <button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	                </div>
	            </div>
			</form>
		</div>
	<style>
		.hideblog{display: block !important;;border: 1px solid #fff;border-bottom: 1px solid #000;}
		.hiddenblog{display: block !important;}
	</style>
	<div id="divPrint">
		<style type="text/css">
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		.hideblog{display: none;}
		.hiddenblog{display: block !important;}
		.style1:hover{ background: #ccc; }
		table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		  margin-top: 100px;
		}
		.hide{visibility: hidden;}
		@media print {
		  div.divFooter {
		    position: fixed;
		    top: 0;
		  	width: 100%;
		  	height: 100px;
		  	bottom:0px;
			margin:0;
		  }
			.hide{visibility: visible; height: 110px;}
		}
		</style>
		<form id="list" name="list" action="<?php echo $this->url(array('module'=>'report','controller'=>'invest','action'=>'submitentry')); ?>" dojoType="dijit.form.Form" method="post">
				<script type="dojo/method" event="onSubmit" >			
							id_selected = dijit.byId('id_selected').get('value');
							if(id_selected==''){
								alert('No record to close !!! ');
								return false;
							}
							return true;
					</script>
		<table width="100%">
			<tr>
		    	<td align="center" valign="top">
		        	<div class="divFooter">
			        	<table border="0" width="100%" style="font-family: 'Khmer OS Battambang';margin:0;padding:0;">
			            	<tr>
			                	<td width="20%" style="border:1px solid #fff;"></td>
			                	<td width="60%" valign="top">
			                		<ul>
			                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("BRAND_TITLE");?></li>
			                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("CLOSING_WITHDRAWAL");?></li>
			                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>;"><?php if($this->search['start_date']){echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));}?></li>
			                		</ul>
			                   </td>
			                    <td width="20%"></td>
			                </tr> 
			            </table>
		            </div>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		            <table width="100%" border="1" style="border-collapse:collapse; border:1px solid #000; " cellspacing="0">
			                <thead>
			                <tr class="hide" style="border:1px solid #000;">
			                	<td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
			                </tr>
			                <tr bgcolor="#c1d0f3" class="style" align="center" style="padding:0px 2px;white-space: nowrap;">
			                    <td rowspan="2"><input type="checkBox" onclick="checkAll('<?php echo count($this->historypayment);?>');" name="checkall" id="checkall" /><?php echo $tr->translate("NUM");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("INVEST_NO");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("INVESTOR");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("TYPE");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("AMOUNT_COLLECT");?></td>		
			                    <td colspan="3"><?php echo $tr->translate("TOTAL_PAYMENTED");?></td>    
			                    <td rowspan="2" style="white-space:nowrap; border-right:3px double black; "><?php echo $tr->translate("PAY_DATE");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("INPUT_DATE");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("RECIEPT_NO");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("PAYMENT_OPTION");?></td>
			                    <td rowspan="2" class=""><?php echo $tr->translate("BY_USER");?></td>
			                    <td rowspan="2" class=""><?php echo $tr->translate("STATUS");?></td>
			                </tr>
			                <tr bgcolor="#c1d0f3" class="style" style="white-space: nowrap;text-align: center;">
			                	<td><?php echo $tr->translate("AMOUNT_INVEST");?></td>                   
			                    <td><?php echo $tr->translate("AMOUNT_RETURN");?></td>
			                    <td><?php echo $tr->translate("TOTAL");?><input type="hidden" name="id_selected" id="id_selected" dojoType="dijit.form.TextBox" /></td>
			                </tr>
			            </thead>
		                <?php 
		                	$total_cash = 0;$total_cheque = 0;$total_bank = 0;                	 
		                	 $amt_d1 = 0;$amt_d2 = 0; 
		                	 $i=0;$oldloan_number='';
		                	 $total_d=0;$total_b=0;$total_r=0;
		                	 
		                ?>
		                <?php 
		                $is_set =0; if(!empty($this->historypayment)) foreach ($this->historypayment as $index => $rs){ ?>
		               <?php 
		              			$i++;
								$amt_d1 = $amt_d1+$rs['principle_paid'];
								$amt_d2 = $amt_d2+$rs['interest_paid'];
								$total_d=$amt_d1+$amt_d2;
								
								if($rs['payment_method']==1){
									$total_cash = $total_cash + $rs['principle_paid']+$rs['interest_paid'];
								}elseif($rs['payment_method']==2){
									$total_bank = $total_bank  + $rs['principle_paid']+$rs['interest_paid'];
								}else{
									$total_cheque = $total_cheque + $rs['principle_paid']+$rs['interest_paid'];
								}
		               ?>
		                <tr oncontextmenu="setrowdata(<?php echo $rs['id'];?>);return false;" class="style style1 context-menu-one" style="font-family: 'Khmer OS Content'; white-space:nowrap; ">
		               		<td style="text-align: center;">&nbsp;
		               		<input style="height: 15px;margin-top: 5px;" type="checkBox" onClick="checked_id(<?php echo $i;?>)" name="check_box<?php echo $i;?>" id="check_box<?php echo $i;?>" />
							<input type="hidden" id="id_<?php echo $i;?>" name="id_<?php echo $i;?>" value="<?php echo $rs['id'];?>" dojoType="dijit.form.TextBox" />
		               		<?php echo $i; ?>&nbsp;</td>
		               		<td align="center">&nbsp;<?php echo $rs["invest_no"];?>&nbsp;</td>
		               		<td>&nbsp;<?php echo $rs["investor_name"];?>&nbsp;</td>                 		
		               		<td>&nbsp;<?php echo $rs["payment_method_title"];?>&nbsp;</td>
		               		<td align="center">&nbsp;<?php echo $rs["times"];?>&nbsp;</td>
		               		<td align="right" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['principle_paid'],2);?>&nbsp;</td>               		
		               		<td align="right" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['interest_paid'],2);?>&nbsp;</td>
		               		<td align="right" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['total_payment'],2);?>&nbsp;</td>
		               		<td align="center" style="white-space:nowrap; border-right:3px double black; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["payment_date"]));?>&nbsp;</td>
		               		<td style="white-space:nowrap; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["paid_date"]));?>&nbsp;</td>
		               		<td align="center" style="color: red;">&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
		               		<td style="white-space: nowrap;font-site:9px; " align="center" >&nbsp;
							<?php echo $rs["option_pay_title"];?>
							</td>
		               		<td class="" style="font:bolder 11px 'Khmer OS Battambang',Arial;text-align: center;"><?php echo $rs['user_name']?></td>
		               		<td class="">&nbsp;<?php echo($rs['is_closed']==0)?"Unclose":"Closed";?>&nbsp;</td>
		                </tr>
		                <?php }?>
		            </table>
		            <br />
		             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
		                 <tr bgcolor="#c1d0f3" class="style" style="line-height: 24px; text-align: center; font-size:9px;font-family: 'Khmer OS Content';">
		                    <td><?php echo $tr->translate("AMOUNT_INVEST");?></td>                    
		                    <td><?php echo $tr->translate("TOTAL_AMOUNT_RETURN");?></td>
		                   
		                    <td><?php echo $tr->translate("TOTAL");?></td>
		                    <td rowspan="2">ចំណូលតាមប្រភេទ</td>
		                    <td><?php echo $tr->translate("សាច់ប្រាក់សរុប");?></td>
		                    <td><?php echo $tr->translate("តាមធនាគារ");?></td>
		                    <td><?php echo $tr->translate("សែកសរុប");?></td>
		                </tr>
		                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
		                    
		                    <td>&nbsp;&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($total_cash,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($total_bank,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($total_cheque,2);?>&nbsp;</td>
		                </tr>
		              </table>
		              <br />
				      <?php echo $this->footerReport;?>
		    	</td>
		    </tr>
		</table>
		<table width="100%">
				<tr>
			    	<td align="center">
			    		<br><button iconclass="dijitIconSave" dojoType="dijit.form.Button" showLabel="true" type="submit">Closing Entry</button>
			    	</td>
				</tr>	
			</table>
		</form>
		</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dijit.form.DateTextBox");
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="reciept"){
				url='<?php echo $url_receipt;?>';
			}else if(key=="edit"){
			}
			gotoAction();
		},
		items: {
			"reciept": {name: "<?php echo $tr->translate("RECEIPT");?>", icon: "fa-file-text", accesskey: "c"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}

function checkAll(array_length){
	dijit.byId('id_selected').attr('value','');
	if(dojo.byId('checkall').checked){
		for(var j=1;j<=array_length;j++){
			$('#check_box'+j).each(function() { 
				this.checked = true;  
			});
			checked_id(j);
		}
	}else{
		for(var j=1;j<=array_length;j++){
			$("#check_box"+j).removeAttr("checked");
			checked_id(j);
		}
	}
}

function checked_id(index){
	row_id = dijit.byId('id_'+index).get('value');
	if(dojo.byId('check_box'+index).checked){
		if($("#id_selected").val()!="") {
			var identity = $("#id_selected").val();
			$("#id_selected").val(identity+','+row_id);
		}else{
			$("#id_selected").val(row_id);
		}
	}else{
		var identity = $('#id_selected').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == row_id) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#id_selected').val(strings);
	}
}
 </script>