<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('RPT_BROKEN_STOCK'));
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$frm =  $this->form_search;
	$rows=$this->rows;
	//print_r($rows);
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
		   	<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_BROKEN_STOCK');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form action="" dojoType="dijit.form.Form" method="post">
		<div class="form-group">
			<label class="col-md-2 col-sm-2 col-xs-12" >
				<?php echo $frm->getElement('title');?>
			</label>
        	<label class="col-md-2 col-sm-2 col-xs-12" >
				<?php echo $frm->getElement('branch_id');?>
			</label>
			<label class="col-md-2 col-sm-2 col-xs-12" >
				<?php echo $frm->getElement("category_id");?>
			</label>
			<label class="col-md-2 col-sm-2 col-xs-12" >
				<input id="product" />>
			</label>
			<label class="col-md-2 col-sm-2 col-xs-12" >
				<?php echo $frm->getElement("product_type");?>
			</label>
			
			<label class="col-md-2 col-sm-2 col-xs-12" >
				<?php echo $frm->getElement('user');?>
			</label>

        	
		</div>
		<div class="form-group">
		<label class="col-md-2 col-sm-2 col-xs-12" >
				<<?php echo $frm->getElement('start_date');?>
			</label>
			<label class="col-md-2 col-sm-2 col-xs-12" >
				<?php echo $frm->getElement('end_date');?>
			</label>
			<label class="col-md-2 col-sm-2 col-xs-12" >
				<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			</label>
        </div>
	</form>
	<style>
	#footer{display: none;}
	</style>	
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<style>
				a{text-decoration: none;color: 000;}
			</style>
			<table width="100%" style="background:#fff; margin: 0 auto; width: 100%;font-family:'Times New Roman','Khmer OS Battambang' ">
				<tr>
					<td colspan="3"><?php echo $this->rsheader;?></td>
				</tr>
				<tr class="line"><td colspan="3"></td></tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<tr>
					<td width="15%" align="center">
					</td>
					<td align="center" width="70%">
						<span <?php echo TITLE_REPORT;?>><?php echo $tr->translate('RPT_BROKEN_STOCK');?></span><br>
						<span style="font-size: 12px; "><?php if(!empty($this->search['start_date'])){?><?php echo date("d-M-Y",strtotime($this->search['start_date']));?> &nbsp;<?php echo $tr->translate('TO');?>&nbsp; <?php echo date("d-M-Y",strtotime($this->search['end_date']));}?></span>
					</td>
					<td width="15%" align="center">
					</td>
				</tr>
				<tr>
					<td>&nbsp;</td>
				</tr>
				<style>
					table tr th{
						border: 1px solid #000;	
					}
					table {page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					}		
					thead tr td {
						font-weight: bold;
						padding: 6px 2px;
					}
					tr.line td{ border-bottom: 2px solid #000;padding-top: 5px; }					
				</style>
				<tr>
					<td colspan="3" id="exportExcel">
						<table cellpadding="4"​ style="font-family:'Khmer OS Battambang' ; margin:0 auto;width:100%;border:1px solid #000; border-collapse: collapse;white-space: nowrap;"  border="1" >
							<thead>
								<tr style="font-size:12px; height: 20px;background: #ccd9ff;" align="center" >
									<td scope="col"  rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
									<td scope="col"  rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH");?>&nbsp;</td>
									<td scope="col"  colspan="2">&nbsp;<?php echo $tr->translate("PRODUCT_INFO");?>&nbsp;</td>
									<td scope="col"  colspan="7">&nbsp;<?php echo $tr->translate("BROKEN_INFO");?>&nbsp;</td>
									<td scope="col"  rowspan="2">&nbsp;<?php echo $tr->translate("USER");?>&nbsp;</td>
									<td scope="col"  rowspan="2">&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
								</tr>
								
								<tr style="font-size:12px; height: 20px;background: #ccd9ff;" align="center" >
									<td scope="col" ><?php echo $tr->translate("CATEGORY");?></td>
									<td scope="col" ><?php echo $tr->translate("PRODUCT_NAME");?></td>
									<td scope="col" ><?php echo $tr->translate("BROKEN_NO");?></td>
									<td scope="col" ><?php echo $tr->translate("TITLE");?></td>
									<td scope="col" ><?php echo $tr->translate("QTY_BEFOR");?></td>
									<td scope="col" ><?php echo $tr->translate("QUANTITY_NEW");?></td>
									<td scope="col" ><?php echo $tr->translate("STOCK_SPACING");?></td>
									<td scope="col" ><?php echo $tr->translate("NOTE");?></td>
									<td scope="col" ><?php echo $tr->translate("CREATED_DATE");?></td>
								</tr>
							</thead>
							<?php 
							$gender=array(1=>"Male",2=>"Female");
							if(!empty($rows))foreach($rows As $key=> $rs_row){
							?>
							<tr style="font-size:12px; height: 23px;" class="hover" >
								<td data-label="<?php echo $tr->translate("NUM");?>" align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("BRANCH");?>">&nbsp;<?php echo $rs_row['branch_name']; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("CATEGORY");?>" >&nbsp;<?php echo $rs_row['category']; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("PRODUCT_NAME");?>" >&nbsp;<?php echo $rs_row['pro_name']; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("BROKEN_NO");?>" align="center">&nbsp;<strong><?php echo $rs_row['broken_no']; ?></strong>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("TITLE");?>" >&nbsp;<?php echo $rs_row['request_name']; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("QTY_BEFOR");?>" align="center">&nbsp;<?php if($rs_row['qty_before']!=0) echo $rs_row['qty_before']; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("QUANTITY_NEW");?>" align="center">&nbsp;<?php if($rs_row['qty_broken']!=0) echo $rs_row['qty_broken']; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("STOCK_SPACING");?>" align="center">&nbsp;<?php if($rs_row['qty_after']!=0) echo $rs_row['qty_after']; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("NOTE");?>" >&nbsp;<?php echo $rs_row['note']; ?></td>
								<td data-label="<?php echo $tr->translate("CREATED_DATE");?>" align="center">&nbsp;<?php echo date("d/m/Y",strtotime($rs_row['request_date'])); ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("USER");?>" align="center">&nbsp;<?php echo $rs_row['user_name']; ?>&nbsp;</td>
								<td data-label="<?php echo $tr->translate("STATUS");?>" align="center">&nbsp;<?php if ($rs_row['status']==1){ echo $tr->translate("ACTIVE"); }else{ echo $tr->translate("DEACTIVE");} ?>&nbsp;</td>
							</tr>
							<?php
							}
							?>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="3">
						<?php echo $this->rsfooteracc;?>
					</td>
				</tr>
			</table>
		</div>	
	</div>
</div>

<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
	
	require(["dojo/ready"], function(ready){
		ready(function(){
			getProductByCate();
		});
		new dijit.form.FilteringSelect({
			store: item_store,
			autoComplete: false,
			queryExpr: "*${0}*",                     
			id: "product",
			name: "product",   
			required:false,        
			class: 'fullside', 
		}, "product");
	});
	
	var item_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
	var url_dept = '<?php echo $this->url(array('module'=>'report','controller'=>'stock','action'=>'get-productbycate')); ?>';
	function getProductByCate(){
		cate_id = dijit.byId("category_id").get("value");
		//if(cate_id>0){
			dojo.xhrPost({
				url:url_dept,
				content:{
					'cate_id':cate_id,
					},
				handleAs:"json",
				load: function(data) {
					item_store  = getDataStorefromJSON('id','name', data);
					dijit.byId('product').set('store',item_store);  	
					dijit.byId('product').attr('value',"<?php echo $this->search['product']?>");
				},
				error: function(err) {
				}
			});
		//}
	}
</script>