<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	
	$frm = $this->frm_search;
	$frmProduct = $this->frmSearchProduct;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();

	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
	
	$branch_title = $tr->translate("BRAND_TITLE");
	$row = $this->rs;
?>
<title><?php echo $tr->translate("CONCRETED_STATEMENT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div class="reportblog">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('CONCRETED_STATEMENT');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		
		<div style="width:100%; margin:0 auto;">
		<div style="min-height:22cm; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
			</style>
			<div id="divPrint">
				<style type="text/css">
					
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.sideLeft,.sideRight{ float: left;}
					.sideLeft li,.sideRight li{text-align: left;}
					.eventStyle{background:#eee;}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table.content-data { page-break-inside:auto }
					tr.content-data{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
						.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						@page {size: portrait; margin-left: 0.3cm;margin-right:0.3cm;}
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #337ab7;
						color: white;
						font-weight:600;
					}
					.style td{
						padding: 0px 2px;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					.style:hover{background:#eee;}
					  
					  @media screen and (max-width: 600px) {
							  table {
							    border: 0;
							  }
								table.content-data {
								    border-collapse: collapse;
								    border: 1px solid #fff;
								    font-size: 13px;
								}
													
							  table thead {
							    border: none;
							    clip: rect(0 0 0 0);
							    height: 1px;
							    margin: -1px;
							    overflow: hidden;
							    padding: 0;
							    position: absolute;
							    width: 1px;
							  }
							  
							  table .content-data tr {
							    border-bottom: 3px solid #ddd;
							    border-right: 3px solid #ddd;
							    display: block;
							    margin-bottom: .625em;
							  }
							  
								table .content-data td {
							    /*border-bottom: 1px solid #ddd;*/
							    display: block;
							    font-size: .8em;
							    text-align: right;
							  }
							table .content-data td{
								border-bottom: 1px solid #ddd;	}
							  
							  table td::before {
							  
							    content: attr(data-label);
							    float: left;
							    font-weight: bold;
							    text-transform: uppercase;
							  }
							  
							  table td:last-child {
							    border-bottom: 0;
							  }
							}
							
					 		</style>
				<table width="100%">
					<tr>
				    	<td align="center" valign="top">
				        	<div class="divFooter">
					        	<?php echo $this->headerReport;?>
				            </div>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				            <table class="content-data" width="100%" border="1"  cellspacing="0" cellpadding="0">
				                <thead>
				                <tr class="hide" style="border:1px solid #000;">
				                	<td colspan="10" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
				                </tr>
								<tr>
									<td colspan="5" style="border:1px solid #fff;" >
										<ul class="sideLeft">
											<li>Supplier Name : <?php echo $row['supplierName']?></li>
											<li>Contact Name: </li>
											<li>Contact Number: </li>
										</ul>
									</td>
									<td colspan="5" style="border:1px solid #fff;" >
										<ul class="sideRight">
											<li>Reference: </li>
											<li>From Date: <?php echo $row['fromDate']?> </li>
											<li>To Date: <?php echo $row['toDate']?></li>
											<li>Create Date: <?php echo $row['createDate']?></li>
										</ul>
									</td>
								</tr>
				                <tr class="style" align="center">
									<td scope="col"  style="padding:1px;">ល.រ​ <br> No.</td>                   
									<td scope="col" style="padding:1px;">ឈ្មោះទំនិញ <br> Product Name</td>
									<td scope="col" style="padding:1px;">កាលបរិច្ឆេទ <br> Date</td>
									<td scope="col" style="padding:1px;">ប្រភេទការងារ <br> Work Type</td>
									<td scope="col" style="padding:1px;">លេខបេតុង <br> Strength</td>
									<td scope="col" style="padding:1px;">លេខ DN <br> DN Number</td>
									<td scope="col" style="padding:1px;">បរិមាណ <br>  QTY</td>	                    
									<td scope="col" style="padding:1px;">តម្លៃក្នុង​ ១ ឯកតា <br> Unit Price</td>
									<td scope="col" style="padding:1px;">សរុប <br> SubTotal</td>
									<td scope="col" style="padding:1px;">សម្គាល់ <br> Note</td>
									</tr>
					            </thead>
				                <?php 
				                $grandTotal = 0;
				                if(!empty($this->rows)) foreach ($this->rows as $index => $rs){
				                	$grandTotal = $grandTotal+$rs['subTotal'];
								?>
									<tr class="style <?php if($index%2!=0)echo "eventStyle";?>" align="left">
										<td data-label="ល.រ​ /N.o" class="padding" style="text-align: center;"><?php echo $index+1;?></td>
										<td data-label="ឈ្មោះទំនិញ/Product Name"><strong><?php echo $rs['proName']?> - <?php echo $rs['proCode']?></strong></td>
										<td data-label="កាលបរិច្ឆេទ/ Date"><?php echo $rs['stmentDate']?></td>
										<td data-label="ប្រភេទការងារ/Work Type"><?php echo $rs['workType']?></td>
										<td data-label="លេខបេតុង/Strength"><?php echo $rs['strength']?></td>
										<td data-label="លេខ DN/DN Number"><?php echo $rs['dnNumber']?></td>
										<td data-label="បរិមាណ/ QTY"><strong><?php echo number_format($rs['qtyPo'],2)?></strong><span style="float: right;">(<?php echo $rs['measureLabel'];?>)</span></td>
										<td data-label="តម្លៃ/Cost"><strong><?php echo number_format($rs['unitPrice'],2)?></strong></td>	  
										<td data-label="សរុប/SubTotal"><strong><span style="float: left; color:red;"><?php echo number_format($rs['subTotal'],2)?></span></strong></td>	                                      
										<td data-label="ផ្សេងៗ/Other" style="min-width: 200px;"><?php echo $rs['note']?></td>
									</tr>
				                <?php }?>
				                <tr>
				                	<td colspan="8" align="right" style="border-left:1px solid #fff;border-bottom:1px solid #fff;">សរុបរួម / Grand Total</td>
				                	<td colspan="2"  style="border:1px solid #fff;border-top:1px solid #000;">$ <strong><?php echo number_format($grandTotal,2);?></strong></td>
				                </tr>

				            </table>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	require(["dojo/ready"], function(ready){
		ready(function(){
			 getBranchInfo();
			 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			 document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("CONCRETED_STATEMENT");?>';
			 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date(DATE_FORMAT_FOR_PHP); }}?>';
		});
	});

function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->rows['projectId'])?0:$this->rows['projectId'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>