<?php	
	$frm = $this->frm;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<title><?php echo $tr->translate("CANCEL_STORE_RENTAL");?></title>
<style>
.fullside50{ width:48%;}
.agreement{
	border: 1px solid #92b0ea;
    background: #cbdcff;
    font-weight: bold;
    text-align: center;}
   textarea{font-size:10px;}
.not-display {
    display: none !important;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
        	<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CANCEL_STORE_RENTAL');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<form id='frm_add_tran' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
           			 branch_id = dijit.byId('branch_id').get('value');
           			 if (branch_id=='' || branch_id==-1){
						alert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH");?>!');
						dijit.byId('branch_id').focus();
						return false;
					}
					rent_id = dijit.byId('rent_id').get('value');
					if (rent_id=='' || rent_id==-1){
						alert('<?php echo $tr->translate("PLEASE_SELECT_RENT");?>!');
						dijit.byId('rent_id').focus();
						return false;
					}
              		loadingBlock();
			  	 return true;
				}else {
					return false;
				}
			</script>
		    <div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("RENT_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('branch_id');?>
	                    	<?php echo $frm->getElement('customer_id');?>
	                    	<?php echo $frm->getElement('property_id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("RENT_NO");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input id="rent_id" />
	                   </div>
	                </div>
	                
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-map-marker" aria-hidden="true"></i> <?php echo $tr->translate("CANCEL_STORE_RENTAL_INFO");?> 
	                   </label>
	                </div>
	                
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CANCEL_DATE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('cancel_date');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("REASON");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('reason');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('note');?>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
	            </div>
	        </div>
	        <div class="clearfix"></div>
			    <div class="card-box">
               		<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		    			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
						<input type="submit" label="<?php echo $tr->translate("SAVE_CLOSE")?>" id='saveclose' value='saveclose' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
						<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" id='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
	    		</div>
	    	</div>
		</form>
	</div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
<script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
</script>
<script type="text/javascript">	
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");
dojo.require("dojo.html");
var rent_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

require(["dojo/ready"], function(ready){
	 ready(function(){
	  });
	new dijit.form.FilteringSelect({
			store: rent_store,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,		           
			name: "rent_id",
			id: "rent_id",
			searchAttr: "name",
			class: 'fullside',
			required:true,
			onChange: function() {
				rent_id = dijit.byId('rent_id').get('value');
				if(rent_id==-1 || rent_id ==""){
				}else{
					getRentInfo();
				}
		}
	}, "rent_id");
});
var url_getsalenumber = "<?php echo $this->url(array('module'=>'rent','controller'=>'payment','action'=>'get-sale-number')); ?>";
function getAllRentNumber(){
	branch_id = dijit.byId('branch_id').get('value');
	dijit.byId('rent_id').reset();
	if(branch_id== 0 || branch_id==-1){
		var rent_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
		rent_store  = getDataStorefromJSON('id','name', data);
	    dijit.byId('rent_id').set('store',rent_store); 
		return false;
	}
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':branch_id,
		},		    
		handleAs:"json",
		load: function(data) {
			rent_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('rent_id').set('store',rent_store); 
		},
		error:  function(response, ioArgs) {
		}
	});
}
var url_rentinfo = "<?php echo $this->url(array('module'=>'rent','controller'=>'deposit','action'=>'getrentinfo')); ?>";
function getRentInfo(){
	rent_id = dijit.byId('rent_id').get('value');
	if(branch_id== 0 || branch_id==-1){
		return false;
	}
	dojo.xhrPost({
		url: url_rentinfo,	
		content:{ 
		    'rent_id':rent_id
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('customer_id').attr('value',data.client_id);
			dijit.byId('property_id').attr('value',data.house_id);
		},
		error:  function(response, ioArgs) {
		}
	});
}

</script>