<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('GENERAL_SETTING')); 
echo $this->headTitle();
$frm = $this->frm_general;

$defaultLogo = $this->baseUrl()."/images/logo.jpg";
if(!empty($this->row['logo']['keyValue'])){
	if (file_exists(PUBLIC_PATH."/images/photo/logo/".$this->row['logo']['keyValue'])){
		$defaultLogo = $this->baseUrl().'/images/photo/logo/'.$this->row['logo']['keyValue'];
	}
}

?>
<style>
div.cke_contents.cke_reset {
    height: 200px !important;
}
</style>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

<style>

img.image_view {
    width: 100%;
	height: 100px;
}
img#image_viewbg {
    height: 50px;
}
.button_browse{
	margin-top:0 !important;
}
.button_browse span {
    padding: 0 5px;
}
tr.header {
    background: #008;
    color: #fff;
}
tr.header td {
    padding: 5px;
}
</style>
<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" >
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				loadingBlock();
				return true;
			}
			return false;
	</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
	               	<div class="col-sm-12 border-botom">
			    		<div class="col-sm-8 pd-0">
			    			<h4 class="m-b-0"><i class="fa fa-cogs" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('GENERAL_SETTING');?></h4>
		    			</div>
		    			<div class="col-sm-4 text-right">
		    			</div>
		    		</div>
		    	</div>
				<div class="card-box">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<ul class="nav verticle-tab md-pills pills-primary nav-tab" role="tablist">
							<li class="nav-item active">
								<a class="nav-link " data-toggle="tab" href="#panelSetting1" role="tab"><i class="fa fa-exclamation-circle"></i> <?php echo $tr->translate("PROFILE");?></a>
							</li>
							<li class="nav-item">
								<a class="nav-link" data-toggle="tab" href="#panelSetting2" role="tab">
								<i class="fa fa-book ml-2"></i> <?php echo $tr->translate("DOCUMENT_SETTING");?>
								</a>
							</li>
							<li class="nav-item">
								<a class="nav-link" data-toggle="tab" href="#panelSetting3" role="tab">
								<i class="fa fa-cog ml-2"></i> <?php echo $tr->translate("SYSTEM_SETTING");?>
								</a>
							</li>
						</ul>
					</div>
					<div class="col-md-9 col-sm-9 col-xs-12">
						 <!-- Tab panels -->
						<div class="tab-content vertical">
							<!--Panel 1-->
							<div class="tab-pane fade in active" id="panelSetting1" role="tabpanel">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="form-group">
										<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Logo')?></div>
										<div class="col-md-4 col-sm-4 col-xs-12">
											<img class="image_view" id="image_view" src="<?php echo $defaultLogo;?>" alt=""  />
											<div class="button_browse">
												<span><?php echo $tr->translate('Change Logo')?><span><i class="fa fa-camera" aria-hidden="true"></i></span></span>
												<input class="btn_borwse_image"  type="file" id="photo" name="photo" onchange="loadImage()">
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Company Tel')?></div>
										<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('telClient')?></div>
									</div>
									<div class="form-group">
										<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Address')?></div>
										<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('footer_branch')?></div>
									</div>
									<div class="form-group">
										<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Email')?></div>
										<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('email_client')?></div>
									</div>
									<div class="form-group">
										<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Website')?></div>
										<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('website')?></div>
									</div>
								</div>
							</div>
							<!--Panel 1-->
							<!--Panel 2-->
							<div class="tab-pane fade in " id="panelSetting2" role="tabpanel">
								<div class="card-box">
									<div class="col-md-6 col-sm-6 col-xs-12">
										<div class="card-blogform">
											<div class="card-body"> 
												<div class="row"> 
													<div class="col-md-12 col-sm-12 col-xs-12"> 
														<div class="d-flex"> 
															<div class="settings-main-icon ">
																<i class="fa fa-university" aria-hidden="true"></i>
															</div> 
															<div class="col-md-10 col-sm-10 col-xs-12"> 
																<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("BANK")." 1";?></p>
															</div> 
														</div> 
														<div class="form-group">
															<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Bank Name')?></label>
															<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_account1');?></div>
														</div>
														<div class="form-group">
															<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Bank Acc Name')?></label>
															<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_account_name1');?></div>
														</div>
														<div class="form-group">
															<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Bank Number')?></label>
															<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_account1number');?></div>
														</div>
													</div> 
												</div> 
											</div> 
										</div>
									</div>
									<div class="col-md-6 col-sm-6 col-xs-12">
										<div class="card-blogform">
											<div class="card-body"> 
												<div class="row"> 
													<div class="col-md-12 col-sm-12 col-xs-12"> 
														<div class="d-flex"> 
															<div class="settings-main-icon ">
																<i class="fa fa-university" aria-hidden="true"></i>
															</div> 
															<div class="col-md-10 col-sm-10 col-xs-12"> 
																<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("BANK")." 2";?></p>
															</div> 
														</div> 
														<div class="form-group">
															<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Bank Name')?></label>
															<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_account2');?></div>
														</div>
														<div class="form-group">
															<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Bank Acc Name')?></label>
															<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_account_name2');?></div>
														</div>
														<div class="form-group">
															<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Bank Number')?></label>
															<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_account2number');?></div>
														</div>
													</div> 
												</div> 
											</div> 
										</div>
									</div>
								</div>
								<div class="card-box">
									<div class="col-md-6 col-sm-6 col-xs-12">
										<div class="card-blogform">
											<div class="card-body"> 
												<div class="row"> 
													<div class="col-md-12 col-sm-12 col-xs-12"> 
														<div class="d-flex"> 
															<div class="settings-main-icon ">
																<i class="fa fa-university" aria-hidden="true"></i>
															</div> 
															<div class="col-md-10 col-sm-10 col-xs-12"> 
																<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("BANK")." 3";?></p>
															</div> 
														</div> 
														<div class="form-group">
															<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Bank Name')?></label>
															<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_account3');?></div>
														</div>
														<div class="form-group">
															<label class="col-md-6 col-sm-6 col-xs-12"><?php echo $tr->translate('Bank Acc Name')?></label>
															<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_account_name3');?></div>
														</div>
														<div class="form-group">
															<label class="col-md-6 col-sm-6 col-xs-12"><?php echo $tr->translate('Bank Number')?></label>
															<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_account3number');?></div>
														</div>
													</div> 
												</div> 
											</div> 
										</div>
										
										<div class="card-blogform">
											<div class="card-body"> 
												<div class="row"> 
													<div class="col-md-12 col-sm-12 col-xs-12"> 
														<div class="d-flex"> 
															<div class="settings-main-icon ">
																<i class="fa fa-exclamation-circle" aria-hidden="true"></i>
															</div> 
															<div class="col-md-10 col-sm-10 col-xs-12"> 
																<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("OTHER");?></p>
																
															</div> 
														</div> 
														<div class="form-group">
															<label 	class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Cheque Receiver')?></label>
															<div	class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('cheque_receiver');?></div>
														</div>
														<div class="form-group">
															<label 	class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Sign Nature Agreement')?></label>
															<div 	class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('signatur_agree');?></div>
														</div>
													</div> 
												</div> 
											</div> 
										</div>
										
									</div>
									<div class="col-md-6 col-sm-6 col-xs-12">
										<div class="card-blogform">
											<div class="card-body"> 
												<div class="row"> 
													<div class="col-md-12 col-sm-12 col-xs-12"> 
														<div class="d-flex"> 
															<div class="settings-main-icon ">
																<i class="fa fa-credit-card" aria-hidden="true"></i>
															</div> 
															<div class="col-md-10 col-sm-10 col-xs-12">  
																<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("RECEIPT_INFO");?></p>
															</div> 
														</div> 
														<div class="form-group">
															<label 	class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Account Sign')?></label>
															<div 	class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('account_sign')?></div>
														</div>
														<div class="form-group">
															<label 	class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Teller Sign')?></label>
															<div 	class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('teller_sign')?></div>
														</div>
														<div class="form-group">
															<label 	class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Customer Sign')?></label>
															<div 	class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('customer_sign')?></div>
														</div>
														
														<div class="form-group">
															<label 	class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Bank Information')?></label>
															<div 	class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('bank_info')?></div>
														</div>
														<div class="form-group">
															<label 	class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Comment')?></label>
															<div 	class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('comment');?></div>
														</div>
														<div class="form-group">
															<label 	class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Comment');?>1</label>
															<div 	class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('comment1');?></div>
														</div>
													</div> 
												</div> 
											</div> 
										</div>
									
									</div>
								</div>
							</div>
							<!--Panel 2-->
							<!--Panel 3-->
							<div class="tab-pane fade in " id="panelSetting3" role="tabpanel">
								<div class="col-md-12 col-sm-12 col-xs-12">
									<div class="form-group">
										<label class="custom-switch  "> 
												<a href="javascript:void(0);" class="tx-14 mb-0 me-2"><?php echo $tr->translate('Show House Info');?></a> 
												<input type="checkbox" id="showhouseinfo" name="showhouseinfo" class="custom-switch-input"  <?php if(!empty($this->row['showhouseinfo']['keyValue'])){ echo "checked";} ?> > 
												<span class="custom-switch-indicator custom-radius"></span> 
										</label>
									</div>
									<div class="form-group">
										<label class="custom-switch  "> 
											
												<a href="javascript:void(0);" class="tx-14 mb-0 me-2"><?php echo $tr->translate('Show Property Price');?></a> 
											
												<input type="checkbox" id="show_propertyprice" name="show_propertyprice" class="custom-switch-input"  <?php if(!empty($this->row['show_propertyprice']['keyValue'])){ echo "checked";} ?> > 
												<span class="custom-switch-indicator custom-radius"></span> 
										
										</label>
									</div>
									<div class="form-group">
										<label class="custom-switch  "> 
												<a href="javascript:void(0);" class="tx-14 mb-0 me-2"><?php echo $tr->translate('AUTO_CALCULATE_PERIOD');?></a> 
												<input type="checkbox" id="autocalcualte_period" name="autocalcualte_period" class="custom-switch-input"  <?php if(!empty($this->row['autocalcualte_period']['keyValue'])){ echo "checked";} ?> > 
												<span class="custom-switch-indicator custom-radius"></span> 
										</label>
									</div>
			
									
									<div class="card-blogform">
										<div class="card-body"> 
											<div class="row"> 
												<div class="col-md-12 col-sm-12 col-xs-12"> 
													<div class="d-flex"> 
														<div class="settings-main-icon ">
															<i class="fa fa-quote-right" aria-hidden="true"></i>
														</div> 
														<div class="col-md-10 col-sm-10 col-xs-12"> 
															<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('Label Animation')?> </p>
														</div> 
													</div>
													<div class="form-group">
														<label class="col-md-3 col-sm-3 col-xs-12 "><?php echo $tr->translate('Label Animation')?></label>
														<div class="col-md-9 col-sm-9 col-xs-12"><?php echo $frm->getElement('label_animation');?></div>
													</div>													
												</div> 
											</div> 
										</div> 
									</div>
									
									<div class="card-blogform">
										<div class="card-body"> 
											<div class="row"> 
												<div class="col-md-12 col-sm-12 col-xs-12"> 
													<div class="d-flex"> 
														<div class="settings-main-icon ">
															<i class="fa fa-bell-o" aria-hidden="true"></i>
														</div> 
														<div class="col-md-10 col-sm-10 col-xs-12"> 
															<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('Alert Setting')?> </p>
															
														</div> 
													</div> 
													<div class="form-group">
														<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Agre Amount Day Alert')?></label>
														<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('agree_day_alert');?></div>
													</div>
													<div class="form-group">
														<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Payment Amount Day Alert')?></label>
														<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('payment_day_alert');?></div>
													</div>
												</div> 
											</div> 
										</div> 
									</div>
								
									<div class="card-blogform">
										<div class="card-body"> 
											<div class="row"> 
												<div class="col-md-12 col-sm-12 col-xs-12"> 
													<div class="d-flex"> 
														<div class="settings-main-icon ">
															<i class="fa fa-money" aria-hidden="true"></i>
														</div> 
														<div class="col-md-10 col-sm-10 col-xs-12"> 
															<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('Penalty Info')?>  </p>
															
														</div> 
													</div> 
													<div class="form-group">
														<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('Penalty Type')?></label>
														<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('penalty_type');?></div>
													</div>
													<div class="form-group">
														<label class="col-md-6 col-sm-6 col-xs-12 "><?php echo $tr->translate('PENALTY_RATE_PER_MONTH')?></label>
														<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('penalty_value');?></div>
													</div>
													<div class="form-group">
														<label class="col-md-6 col-sm-6 col-xs-12"><?php echo $tr->translate('GRACE_PERIOD_PAYMENT')?></label>
														<div class="col-md-6 col-sm-6 col-xs-12"><?php echo $frm->getElement('graice_pariod_late');?></div>
													</div>
												</div> 
											</div> 
										</div> 
									</div> 
									
									
						
								</div>
							</div>
							<!--Panel 3-->
						</div>
						<!-- Tab panels -->
					</div>
		    	</div>
		    	<div class="card-box">
		    		<table cellspacing="5" width="100%" style="padding:10px;">
						<?php $sss=0; if ($sss==1){?>
						<tr>
							<td class="bold" valign="top"><?php echo $tr->translate('Power By')?></td>
							<td valign="top"><?php echo $frm->getElement('power_by')?></td>
						</tr>
						<tr>
							<td class="bold" valign="top"><?php echo $tr->translate('Branch Tel')?></td>
							<td valign="top">
								<?php echo $frm->getElement('branchTel')?>
							</td>
						</tr>
						<tr>
							<td class="bold" valign="top"><?php echo $tr->translate('Branch Email')?></td>
							<td valign="top"><?php echo $frm->getElement('branch_email');?></td>
						</tr>
						<tr>
							<td class="bold" valign="top"><?php echo $tr->translate('Branch Address');?></td>
							<td><?php echo $frm->getElement('branch_add');?></td>
						</tr>
						<?php }?>
					</table>
	    		</div>
	    		<div class="card-box">
	    			<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
						<input class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" id="save_close" dojoType="dijit.form.Button"  /> 	
	    			</div>
	    		</div>
	  	 </div>
	</div>
</form>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.form.Textarea");
function loadImage(){
	 var output = document.getElementById('image_view');
  output.src = URL.createObjectURL(event.target.files[0]);
}

function CheckPenalty(){
	penalty_type = dijit.byId("penalty_type").get('value');
	if(penalty_type==1){
		penalty_value = dijit.byId("penalty_value").get('value');
		if(penalty_value>100){
			alert("<?php echo $tr->translate('ប្រាក់ពិន័យជាភាគរយមិនអាចលើសពី ១០០%ឡើយ');?>");
			dijit.byId('penalty_value').attr('value',100);
			return false;
		}
	}
}
</script>