<?php
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$this->headTitle($tr->translate('GENERAL_SETTING')); 
echo $this->headTitle();
$frm = $this->frm_general;

$defaultLogo = $this->baseUrl()."/images/logo.jpg";
if(!empty($this->row['logo']['keyValue'])){
	if (file_exists(PUBLIC_PATH."/images/photo/logo/".$this->row['logo']['keyValue'])){
		$defaultLogo = $this->baseUrl().'/images/photo/logo/'.$this->row['logo']['keyValue'];
	}
}

?>
<style>
div.cke_contents.cke_reset {
    height: 200px !important;
}
</style>
<script src="<?php echo $this->baseUrl();?>/ckeditor/ckeditor.js"></script>

<style>

img.image_view {
    width: 100%;
	height: 100px;
}
img#image_viewbg {
    height: 50px;
}
.button_browse{
	margin-top:0 !important;
}
.button_browse span {
    padding: 0 5px;
}
tr.header {
    background: #008;
    color: #fff;
}
tr.header td {
    padding: 5px;
}
</style>
<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data" >
	<script type="dojo/method" event="onSubmit">				
			if(this.validate()) {
				loadingBlock();
				return true;
			}
			return false;
	</script>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
	               	<div class="col-sm-12 border-botom">
			    		<div class="col-sm-8 pd-0">
			    			<h4 class="m-b-0"><i class="fa fa-user" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('GENERAL_SETTING');?></h4>
		    			</div>
		    			<div class="col-sm-4 text-right">
		    			</div>
		    		</div>
		    	</div>
		    	<div class="card-box">
		    		<div class="col-md-6">
		    			<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-user" aria-hidden="true"></i>Company Info 
		                   </label>
		                </div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Company Tel')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('telClient')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Address')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('footer_branch')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Email')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('email_client')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Website')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('website')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Logo')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12">
		    					<img class="image_view" id="image_view" src="<?php echo $defaultLogo;?>" alt=""  />
								<div class="button_browse">
									<span><?php echo $tr->translate('Change Logo')?><span><i class="fa fa-camera" aria-hidden="true"></i></span></span>
									<input class="btn_borwse_image"  type="file" id="photo" name="photo" onchange="loadImage()">
			    				</div>
			    			</div>
		    			</div>
		    			<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-hand-o-right" aria-hidden="true"></i>Bank Info 
		                   </label>
		                </div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate("Bank Name")." 1";?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_account1');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate("Bank Acc Name")." 1";?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_account_name1');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate("Bank Number")." 1";?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_account1number');?></div>
		    			</div>
		    			
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate("Bank Name")." 2";?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_account2');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate("Bank Acc Name")." 2";?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_account_name2');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate("Bank Number")." 2";?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_account2number');?></div>
		    			</div>
						
						<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate("Bank Name")." 3";?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_account3');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate("Bank Acc Name")." 3";?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_account_name3');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate("Bank Number")." 3";?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_account3number');?></div>
		    			</div>
						
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Cheque Receiver')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('cheque_receiver');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Sign Nature Agreement')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('signatur_agree');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Label Animation')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('label_animation')?></div>
		    			</div>
		    			
						<div class="form-group">
							<label class="custom-switch  "> 
								<div class="col-md-4 col-sm-4 col-xs-12 ">
									<a href="javascript:void(0);" class="tx-14 mb-0 me-2"><?php echo $tr->translate('Show House Info');?></a> 
								</div>
								<div class="col-md-8 col-sm-8 col-xs-12">
									<input type="checkbox" id="showhouseinfo" name="showhouseinfo" class="custom-switch-input"  <?php if(!empty($this->row['showhouseinfo']['keyValue'])){ echo "checked";} ?> > 
									<span class="custom-switch-indicator custom-radius"></span> 
								</div>
							</label>
		    			</div>
						<div class="form-group">
							<label class="custom-switch  "> 
								<div class="col-md-4 col-sm-4 col-xs-12 ">
									<a href="javascript:void(0);" class="tx-14 mb-0 me-2"><?php echo $tr->translate('Show Property Price');?></a> 
								</div>
								<div class="col-md-8 col-sm-8 col-xs-12">
									<input type="checkbox" id="show_propertyprice" name="show_propertyprice" class="custom-switch-input"  <?php if(!empty($this->row['show_propertyprice']['keyValue'])){ echo "checked";} ?> > 
									<span class="custom-switch-indicator custom-radius"></span> 
								</div>
							</label>
		    			</div>
		    			<div class="form-group">
							<label class="custom-switch  "> 
								<div class="col-md-4 col-sm-4 col-xs-12 ">
									<a href="javascript:void(0);" class="tx-14 mb-0 me-2"><?php echo $tr->translate('CALCULATE_PERIOD');?></a> 
								</div>
								<div class="col-md-8 col-sm-8 col-xs-12">
									<input type="checkbox" id="autocalcualte_period" name="autocalcualte_period" class="custom-switch-input"  <?php if(!empty($this->row['autocalcualte_period']['keyValue'])){ echo "checked";} ?> > 
									<span class="custom-switch-indicator custom-radius"></span> 
								</div>
							</label>
		    			</div>
		    			
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"></div>
		    			</div>
		    		</div>
		    		<div class="col-md-6">
		    			<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-user" aria-hidden="true"></i>Other Info 
		                   </label>
		                </div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Account Sign')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('account_sign')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Teller Sign')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('teller_sign')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Customer Sign')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('customer_sign')?></div>
		    			</div>
		    			
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Bank Information')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('bank_info')?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Comment')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('comment');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Comment');?>1</div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('comment1');?></div>
		    			</div>
		    			<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-money" aria-hidden="true"></i>
		                   <?php echo $tr->translate('Alert Setting')?> 
		                   </label>
		                </div>
		                <div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Agre Amount Day Alert')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('agree_day_alert');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Payment Amount Day Alert')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('payment_day_alert');?></div>
		    			</div>
		    			<div class="form-group">
		                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-money" aria-hidden="true"></i>
		                   <?php echo $tr->translate('Penalty Info')?> 
		                   </label>
		                </div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('Penalty Type')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('penalty_type');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('PENALTY_RATE_PER_MONTH')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('penalty_value');?></div>
		    			</div>
		    			<div class="form-group">
		    				<div class="col-md-4 col-sm-4 col-xs-12 "><?php echo $tr->translate('GRACE_PERIOD_PAYMENT')?></div>
		    				<div class="col-md-8 col-sm-8 col-xs-12"><?php echo $frm->getElement('graice_pariod_late');?></div>
		    			</div>
		    			
		    			<div class="form-group">
		    				<table cellspacing="5" width="100%" style="padding:10px;">
								<?php $sss=0; if ($sss==1){?>
								<tr>
									<td class="bold" valign="top"><?php echo $tr->translate('Power By')?></td>
									<td valign="top"><?php echo $frm->getElement('power_by')?></td>
								</tr>
								<tr>
									<td class="bold" valign="top"><?php echo $tr->translate('Branch Tel')?></td>
									<td valign="top">
										<?php echo $frm->getElement('branchTel')?>
									</td>
								</tr>
								<tr>
									<td class="bold" valign="top"><?php echo $tr->translate('Branch Email')?></td>
									<td valign="top"><?php echo $frm->getElement('branch_email');?></td>
								</tr>
								<tr>
									<td class="bold" valign="top"><?php echo $tr->translate('Branch Address');?></td>
									<td><?php echo $frm->getElement('branch_add');?></td>
								</tr>
								<?php }?>
							</table>
		    			</div>
		    		</div>
	    		</div>
	    		<div class="card-box">
	    			<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
						<input class="button_success" type="submit" value="save_close" name="save_close" label="<?php echo $tr->translate('GO_EDIT');?>" id="save_close" dojoType="dijit.form.Button"  iconClass="dijitEditorIcon dijitEditorIconSave"/> 	
	    			</div>
	    		</div>
	  	 </div>
	</div>
</form>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.form.Textarea");
function loadImage(){
	 var output = document.getElementById('image_view');
  output.src = URL.createObjectURL(event.target.files[0]);
}

function CheckPenalty(){
	penalty_type = dijit.byId("penalty_type").get('value');
	if(penalty_type==1){
		penalty_value = dijit.byId("penalty_value").get('value');
		if(penalty_value>100){
			alert("<?php echo $tr->translate('ប្រាក់ពិន័យជាភាគរយមិនអាចលើសពី ១០០%ឡើយ');?>");
			dijit.byId('penalty_value').attr('value',100);
			return false;
		}
	}
}
</script>