<?php	
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<title><?php echo $tr->translate("SALE_DEPOSIT");?></title>
<style>
.fullside50{ width:48%;}
.agreement{
	border: 1px solid #92b0ea;
    background: #cbdcff;
    font-weight: bold;
    text-align: center;}
   textarea{font-size:10px;}
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
<script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
</script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'deposit','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
           			 branch_id = dijit.byId('branch_id').get('value');
           			 if (branch_id=='' || branch_id==-1){
						alert('Please Select Branch!');
						dijit.byId('branch_id').focus();
						return false;
					}
					client = dijit.byId('member').get('value');
					if (client=='' || client==-1){
						alert('Please Select Client Name !');
						dijit.byId('member').focus();
						return false;
					}
            		payment_id =dijit.byId("schedule_opt").get("value");
              		date_agreement = dijit.byId("date_line").get("value");
            
              		if(payment_id==1 && date_agreement==null){ 
						alert("សូមបញ្ចូលថ្ងៃត្រូវមកធ្វើកិច្ចសន្យា");
						dijit.byId("date_line").focus();return false;
             		 }
					if(payment_id==2){//បង់ផ្តាច់
				  		sold_price = dijit.byId("sold_price").get("value");
  				  		deposit = dijit.byId("deposit").get("value");
					 	 if(sold_price!=deposit){
							alert("បង់ផ្តាច់ តម្លៃលក់ ត្រូវស្មើរ នឹងប្រាក់ដែលត្រូវទទួល!");
							dijit.byId("deposit").focus();
							return false;
				 		 }
					}
			  	 dijit.byId('savenew').set('disabled',true);
			  	 return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('SALE_DEPOSIT');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-hand-o-right" aria-hidden="true"></i> <?php echo $tr->translate("INFO_INDILOAN");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("BRANCH_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('branch_id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SALE_NO");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('sale_code');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CUSTOMER_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="member" /><input dojoType="dijit.form.TextBox" class="fullside" id="joint_with" name="joint_with"  type="hidden"><!-- ពេលបោះពុម្ពចេញអ្នកទិញជាមួយ -->
							<input type="hidden" name="identity_land" id="identity_land"  value="" >
							<input type="hidden" name="land_label" id="land_label" dojoType="dijit.form.TextBox" value="" >
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CLIENT_NUM");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		 <div class="col-md-7 col-sm-7 col-xs-12">
	                   		 	<input id="customer_code" /><input type="hidden" name="identity" id="identity"  value="" >
	                   		 </div>
	                   		  <div class="col-md-3 col-sm-3 col-xs-12">
	                   		  	<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="filterClient();"/>
	                   		 </div>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-user" aria-hidden="true"></i> <?php echo $tr->translate("SALE_AGENT_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("CO_NAME");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="staff_id" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("COMISSION_EXPECTED");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('full_commission');?>
	                   </div>
	                </div>
	                <!-- <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php //echo $tr->translate("COMISSION");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php //echo $frm->getElement('commission');?>
	                   </div>
	                </div> -->
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-map-marker" aria-hidden="true"></i> <?php echo $tr->translate("PROPERTY_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROPERTY_TYPE");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('property_type');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PROPERTY_CODE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		 <div class="col-md-6 col-sm-6 col-xs-12">
	                   		 	<?php echo $frm->getElement('typesale');?>
	                   		 </div>
	                   		  <div class="col-md-6 col-sm-6 col-xs-12">
	                   		  	<input id="land_code" /><input dojoType="dijit.form.TextBox"  id="propertype" name="propertype" type="hidden">
	                   		 </div>
	                   </div>
	                </div>
	                <?php $show=0; if ($show==1){?>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("LAND_PRICE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('land_price');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("HOUSE_PRICE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('house_price');?>
	                   </div>
	                </div>
	                <?php }?>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PRICE_BEFORE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('total_sold');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Discount");?>  :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('discount_percent');?><?php echo $frm->getElement('discount');?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("TOTAL_DISCOUNT");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('total_discount');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("SOLD_PRICE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('sold_price');?>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold  col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_TYPE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<select name="schedule_opt" id="schedule_opt" dojoType="dijit.form.FilteringSelect" class="fullside" onchange="checkScheduleOption();">
							    <option value="1" ><?php echo $tr->translate("DEPOSIT");?></option>
							    <option value="2" ><?php echo $tr->translate("DEPOSITE_PAYOFF");?></option>
							</select>
	                   </div>
	                </div>
	                 <div class="form-group">
	                   <div class="col-md-12 col-sm-12 col-xs-12" style="background:#fff;border:1px solid #aac4e6;font-size: 13px;color:#284db7;padding:2px;clear: both;height: auto;min-height: 100px;">
	                    	<label id="land_information" style="max-width:100%;"></label>
	                   </div>
	                </div>
	               
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate("AGREEMENT");?> 
	                   </label>
	                </div>
	                 <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DATE_BUY");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('date_buy');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("AGREEMENT_DATE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('agreement_date');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label id="lbl_dateline" class="control-label bold  col-md-5 col-sm-5 col-xs-12" for="first-name">
	                   <?php echo $tr->translate("DATE_MAKE_AGREEEMNT")?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('date_line');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label id="lbl_dateline" class="control-label   col-md-5 col-sm-5 col-xs-12" for="first-name">
	                   <?php echo $tr->translate("SECOND_DEPOSIT")?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('second_depostit');?>
	                   </div>
	                </div>
	                <?php if($this->data['note_agreement']==1){?>
	                <div class="form-group">
	                   <label id="lbl_dateline" class="control-label   col-md-5 col-sm-5 col-xs-12" for="first-name">
	                   <?php echo $tr->translate("AGREEMENT_NOTE")?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('note_agreement');?>
	                   </div>
	                </div>
	                <?php }?>
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" for="first-name"><i class="fa fa-money" aria-hidden="true"></i> <?php echo $tr->translate("PAYMENT_INFORMATION");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("DAY_PAYMENT");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input constraints="{datePattern:'dd/MM/yyyy'}" type="text" class="fullside" dojoType="dijit.form.DateTextBox" name="paid_date" id="paid_date"  value="<?php echo date("Y-m-d");?>" >
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_RECEIPT");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('receipt');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("PAYMENT_TYPE");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('payment_method');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NUMBER");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('cheque');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Paid");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('deposit');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("Balance");?> <span class="required">*</span> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('balance');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" for="first-name"><?php echo $tr->translate("NOTE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('note');?>
	                   </div>
	                </div>
	            </div>
	        </div>
	        <div class="clearfix"></div>
			    <div class="card-box">
               		<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		    			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" id='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
			<input type="button" onclick="printSave('','');displayNone();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
	    		</div>
	    	</div>
		</form>
	</div>
</div>

<div class="dijitHidden">
	<style>
	.print tr td{
		padding:5px 2px; 
	}
	</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់'" id="lbl_schedule" style="width: 25cm !important;">
		<div id="rpt_print" class="print" style="text-align: center;">
			<input style="text-align: center;" type="button" onclick="printSave('','');" label="<?php echo $tr->translate("បោះពុម្ភបង្កាន់ដៃ")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		</div>
	</div>
</div>
<div class="dijitHidden" style="width:24cm !important; height: 15cm ; padding: 0px; margin: 0px; padding-top: 40px;">
	<div data-dojo-type="dijit.Dialog" style="width:24cm !important;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="terms" >
		<button style="margin-bottom: 20px;" dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
			type="button" onclick="doPrint();">បោះពុម្ភ/Print</button>
		<div id="divPrint" style="height: 13cm ; padding: 0px; margin: 0px;font-family:'Khmer OS Battambang';">
			<?php 
				echo $this->officailreceipt;
			?>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
		
		<div id="divPrint1" style="width: 21cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<?php if($this->data['showreceipt']>1){?>
				<div style="border:2px dashed <?php echo $this->data['border_receiptcolor'];?>; vertical-align: middle;margin:20px 0px 40px 0px"></div>
			<?php }?>
			<div id="printblog2"></div>
		</div>
	</div>
</div>
<script type="text/javascript">	
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");					           
var staff_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->co_name));?> );
new dijit.form.FilteringSelect({
	store: staff_store,
	autoComplete: false,
	queryExpr: "*${0}*",                       
    id: "staff_id",
    name: "staff_id",  
    class: 'fullside',  
    required:false,
    placeHolder:"<?php echo $tr->translate("SELECT_SALE_AGENT");?>", 
    onChange: function() {        
    	branch_id = dijit.byId('branch_id').get('value');
    	staff_id = dijit.byId('staff_id').get('value');
    	if(branch_id==0){
    		if(staff_id==-1){
    			alert('Please select branch');
    			dijit.byId('branch_id').focus();
    			return false;
        	}
    	}else{
		    if(staff_id==-1){
		    	dijit.byId('branch_id_pop').attr('value',branch_id);
		   		dijit.byId("popup_staff").show();
		    }
    	}
    } 
}, "staff_id");
function enablePayment(){
	payment_method = dijit.byId('payment_method').get('value');
	dijit.byId("cheque").set("readOnly",false);
	dijit.byId("cheque").attr("value",'');
	if(payment_method==1){
		dijit.byId("cheque").attr("value",'N/A');
		dijit.byId("cheque").set("readOnly",true);
	}
}

function displayNone(){
	document.getElementById('divPrint1').style.display="none";
}
function checkScheduleOption(){
	payment_option = dijit.byId("schedule_opt").get("value");
	if(payment_option==2){
		sold_price = dijit.byId("sold_price").get("value");
		dijit.byId("deposit").attr("value",sold_price);
		dijit.byId("balance").attr("value",0);
	}
}
function resetSale(){
	dijit.byId('land_label').attr("value",'');
	$('#identity_land').val('');
	dojo.byId('land_information').innerHTML ="";
	//dijit.byId('land_price').attr("value",0);
	//dijit.byId('house_price').attr("value",0);
	dijit.byId('total_sold').attr("value",0);
	dijit.byId('sold_price').attr("value",0);
	land_id = dijit.byId("land_code").get("value");
	if(land_id!='' && land_id>0){
		getlandinfo();
	}
	
}
function calculateDiscount(){
	total_sold = dijit.byId('total_sold').get('value');
	discount = dijit.byId('discount').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	
	if(isNaN(discount)){
		discount=0;
	}
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	discount_percent = parseInt(total_sold*discount_percent/100);
	total_sold = total_sold - discount_percent-discount;
	total_discount = discount_percent+discount;
	dijit.byId('total_discount').attr('value',total_discount);
	dijit.byId('sold_price').attr('value',total_sold);
	Balance();
}
function Balance(){
	price = dijit.byId('sold_price').get('value');
	deposit =dijit.byId('deposit').get('value');
	if(isNaN(deposit)){
		deposit=0;
	}
	if(deposit > price){
		deposit = price;
		dijit.byId('deposit').attr('value',deposit);
	}
	dijit.byId('balance').attr('value',price-deposit);
}
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	getAllPropertyBranch(branch_id);
	getLoanByBranch('');
	getReceiptByBranch('');
	getAllClientByBranch(branch_id);
	getAllClientNumberByBranch(branch_id);
}
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	property_type = dijit.byId('property_type').get('value');
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,'property_type':property_type
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_code').set('store', property_store);
		},
		error: function(err) {
		}
	});
} 
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(condition){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
			if(condition==1){
				getReceiptByBranch(data);
			}
		},
		error: function(err) {
		}
	});
}
var url_getreceipt = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-receipt-number')); ?>';
function getReceiptByBranch(new_sale_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('receipt').attr('value',data);
			if(new_sale_id!=''){
				printSave(new_sale_id,data);
			}
		},
		error: function(err) {
		}
	});
}
    function calCulatorBalance(){
    	//price = dijit.byId('land_price').get('value');
    	price = dijit.byId('sold_price').get('value'); 
    	deposit =dijit.byId('deposit').get('value');
    	if(isNaN(deposit)){
    		deposit=0;
    	}
    	if(deposit>price){
    		alert("Deposit can not biger than price ");
    		dijit.byId('deposit').focus();
    		dijit.byId('deposit').attr('value',price)
    	}
        dijit.byId('balance').attr('value',price-deposit);
    }
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	function doPrint() {
		dojo.byId("printblog2").innerHTML = dojo.byId('divPrint').innerHTML;
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML<?php if($this->data['showreceipt']>1){ ?> + dojo.byId('divPrint1').innerHTML<?php }?>;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    printSubmit();
		hideDialog();
	}
	function printSubmit(){
		$('#frm_add_tran').submit();
	}
</script>
<script type="text/javascript">
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_name));?> );
var client_number_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_code));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );
var property_store  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	 ready(function(){
		 dijit.byId("date_line").set("readOnly",false);
		 enablePayment();
		 <?php if($this->data['enable_receipt']==1){?>
		 	dijit.byId("receipt").set("readOnly",false);
		 <?php }?>
	  });
	 
	new dijit.form.FilteringSelect({
			store: property_store,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,		           
			name: "land_code",
			id: "land_code",
			searchAttr: "name",
			class: 'fullside',
			required:true,
			onChange: function() {
				land_code = dijit.byId('land_code').get('value');
				if(land_code==-1){
				}else{
					getlandinfo();
				}
		}
			}, "land_code");
	 
	new dijit.form.FilteringSelect({
	store: client_store,
	autoComplete: false,
	queryExpr: "*${0}*",	           
	name: "member",
	id: "member",
	searchAttr: "name",
	required:true,
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			window.open('<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add'))?>');
		}else{
			dijit.byId('customer_code').attr('value',member);
			getcustomerinfo(member);
		}
   }
	}, "member");
	
	new dijit.form.FilteringSelect({
	store: client_number_store,
	autoComplete: true,
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			window.open('<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add'))?>');
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");
});
</script>
<script type="text/javascript">
var url_getcustomer = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclient')); ?>';
function getcustomerinfo(client_id){
	dojo.xhrPost({
		url:url_getcustomer,	
		content:{ 
		    'client_id':client_id
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('joint_with').attr('value',data.hname_kh);
		},
		error: function(err) {
			alert(err);
		}
	});
}
var url_getlandinfodetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfo(){
	var typesale =dijit.byId('typesale').get('value');
	var oldprice= dijit.byId('total_sold').get('value');
	//var land_price= dijit.byId('land_price').get('value');
	//var house_price= dijit.byId('house_price').get('value');
	land_id = dijit.byId('land_code').get('value');
	if(land_id==''){return false;}
	dojo.xhrPost({
		url:url_getlandinfodetail,	
		content:{ 
		    'land_id':land_id
		},		    
		handleAs:"json",
		load: function(data) {
			if(typesale==2){//multi
				var had = 0;
		 		var landcode= dijit.byId('land_code').get('value');
		 		var rowId = $('#identity_land').val();
			 	if($("#identity_land").val()!='') {
			 		var rowIDArray = rowId.split(',');
		 			for(var n = 0; n < rowIDArray.length; n++) {
		 				if(landcode == rowIDArray[n]){
			 				alert("លេខដី/ផ្ទះ នេះបានជ្រើសរើសរួចហើយ");
			 				had = 1;
		 				}
		 			}
				 	if(had==1){}else{
						var identity = $("#identity_land").val();
						var price = oldprice + parseFloat(data.price);
						
						oldland_code =  oldland_code+","+data.land_code;
						address = address+"&"+data.land_address+','+data.street;
						size = parseFloat(size)+parseFloat(data.land_size);
						height = height+" , "+data.height;
						width = width+" , "+data.width;
						$("#identity_land").val(identity+','+data.id);
						
						dijit.byId('total_sold').attr('value',price);
						dijit.byId('sold_price').attr('value',price);

						dojo.byId('land_information').innerHTML ="លេខដី/ផ្ទះ  "+address+", ទំហំ "+size+" ម៉ែត្រការ៉េ ";
						dijit.byId('land_label').attr('value',address);
						}
				}else {
						$("#identity_land").val(data.id);
						dijit.byId('total_sold').attr('value',data.price);
						dijit.byId('sold_price').attr('value',data.price);

						oldland_code = data.land_code;
						address = data.land_address+','+data.street;
						size = data.land_size;
						height = data.height;
						width = data.width;
						dijit.byId('land_label').attr('value',address);
						dojo.byId('land_information').innerHTML ="លេខដី/ផ្ទះ  "+address+","+" ទំហំ "+size+" ម៉ែត្រការ៉េ ";
				}
			}else{//normal
				var price = oldprice + parseFloat(data.price);			
				dijit.byId('total_sold').attr('value',data.price);
				dijit.byId('sold_price').attr('value',data.price);
				dojo.byId('land_information').innerHTML ="លេខសម្គាល់ "+data.land_code+", លេខផ្ទះ/ឡូតិ៏  "+data.land_address+", លេខផ្លូវ  "+data.street+", ប្រភេទ  "+data.property_type+", ទំហំ "+data.land_size+" ម៉ែត្រការ៉េ, បណ្តោយ "+data.height+" ម៉ែត្រ, ទទឹង  "+data.width+" ម៉ែត្រ";
				dijit.byId('propertype').attr('value',data.house_type);
			}
			Balance();
		},
		error: function(err) {
		}
	});
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
}
</script>
<script>
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==""){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img class="view" style="height:80px; max-width:100%" src="<?php echo $this->baseUrl()."/images/projects/"?>'+arr.logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;
		},
		error: function(e) {
		}
	});
}
function printSave(new_stu_id,new_receipt_no){
	<?php if($this->data['enable_receipt']==1){?>
		new_receipt_no = dijit.byId("receipt").get("value");
	<?php }?>
	getBranchInfo();
	schedule_opt = dijit.byId("schedule_opt").get("value");
	if(schedule_opt==2){//បង់ផ្តាច់
		  sold_price = dijit.byId("sold_price").get("value");
		  deposit = dijit.byId("deposit").get("value");
		  if(sold_price!=deposit){
			alert("បង់ផ្តាច់ តម្លៃលក់ ត្រូវស្មើរ នឹងប្រាក់ដែលត្រូវទទួល!");
			dijit.byId("deposit").focus();
			return false;
		  }
	}

    date_agreement = dijit.byId("date_line").get("value");
    if(schedule_opt==1 && date_agreement==null){ 
		alert("សូមបញ្ចូលថ្ងៃត្រូវមកធ្វើកិច្ចសន្យា");
		dijit.byId("date_line").focus();return false;
    }
    
	deposit = dijit.byId('deposit').get('value');
	if (deposit=='' || deposit==-1){
		alert('សូមបញ្ចូលប្រាក់ត្រូវបង់ ទើបបោះពុម្ភបង្កាន់ដៃបង់ប្រាក់បាន!');
		dijit.byId('deposit').focus();
		return false;
	}
	date_line = dijit.byId('date_line').get('value');
	if(date_line=="" || date_line==null){
		alert("<?php echo $tr->translate("ALERT_DEPOSIT_WARNING");?>");
		dijit.byId("date_line").focus();return false;
	}
	
	if(schedule_opt==1 && new_receipt_no!=''){
		var r = confirm("<?php //echo $tr->translate("ALERT_DEPOSIT_WARNING");?>"+"\n"+"<?php echo $tr->translate("ALERT_BEFORE_SAVE");?>");
		if (r == true) {
			
		} else {
		    return false;
		}
	}
	symbal=" $";
	if(new_stu_id=='' && new_receipt_no==''){
		getLoanByBranch(1);
		return false;
	}else{
		//dojo.byId("lb_sale_id").innerHTML = new_stu_id;
		dojo.byId("lb_receipt").innerHTML = new_receipt_no;
	}
	if(dijit.byId('frm_add_tran').validate()){
		
		dijit.byId("lbl_schedule").hide();
		dojo.byId("lbl_paidtimes").innerHTML = dijit.byId("schedule_opt").attr('displayedValue');
	
		date_payment = dijit.byId("paid_date").get('value');
		var a = new Date(date_payment);
		mm = a.getMonth()+1;
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		month = returnMOnth(mm);
		var y = a.getFullYear();
		var date_payment = dd +'-'+month+'-'+y ;
		var short_y = y.toString().substr(-2);
		var datepay1 = dd +'/'+mm+'/'+short_y ;
		
		dojo.byId("lb_buydate1").innerHTML = date_payment; 
		dojo.byId("lbl_paid_date1").innerHTML = date_payment;
		lbl_landaddress = dijit.byId("land_code").attr('displayedValue')+dijit.byId("propertype").attr('displayedValue');
		sale_type = dijit.byId("typesale").get('value');
		if(sale_type==2){
			lbl_landaddress =  dijit.byId("land_label").get('value');
		}
		dojo.byId("lb_hourseno").innerHTML = lbl_landaddress;
		dojo.byId("lb_saleprice").innerHTML = "$ "+dojo.number.format(dijit.byId("sold_price").get('value'),{places:2});
	
		total_sold = dijit.byId('total_sold').get('value');
		discount_percent = dijit.byId('discount_percent').get('value');
		if(isNaN(discount_percent)){
			discount_percent=0;
		}
		discount = dijit.byId('discount').get('value');
		if(isNaN(discount)){
			discount=0;
		}
		
		discount_percent = total_sold*discount_percent/100;
		total_discount = parseInt(discount_percent)+parseFloat(discount);
		dojo.byId("lbl_project").innerHTML = dijit.byId("branch_id").attr('displayedValue');
		
		dojo.byId("lbl_total_paid1").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
		dojo.byId("lb_amount").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
		dojo.byId("lbl_total_receive").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
		dojo.byId("lbl_totalpayment").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
		
		balance = dijit.byId("balance").get('value');
		if(isNaN(balance)){balance=0;}
		dojo.byId("lbl_balance").innerHTML = "$ "+dojo.number.format(balance,{places:2});
		dojo.byId("lb_noted").innerHTML =dijit.byId("note").get('value');
		joint_with = dijit.byId("joint_with").attr('displayedValue');
		
		
		if(joint_with!=''){joint_with = "/"+joint_with}
		dojo.byId("lbl_paymenttype").innerHTML = dijit.byId("payment_method").attr('displayedValue');
		document.getElementById('lbl_cheque').innerHTML = dijit.byId('cheque').get('value');
		
		dojo.byId("lbl_customer").innerHTML = dijit.byId("member").attr('displayedValue')+joint_with;
		dojo.byId("lb_customer").innerHTML = dijit.byId("member").attr('displayedValue');

		//for Five star Receipt
		dojo.byId("lb_customercode").innerHTML = dijit.byId("customer_code").attr('displayedValue');
		
		a =dojo.number.format(dijit.byId("deposit").get('value'),{places:2}).replace(",", "");
		money_khmer=read_money_in_english(a);
		decimalmoney_khmer=dojo.number.format(dijit.byId("deposit").get('value'),{places:2}).replace(",", "").substr(-2);
		str_cent = 'cent';
		if(decimalmoney_khmer>0){string='and';}else{string="";str_cent='';}
		
		last_number=dojo.number.format(dijit.byId("deposit").get('value'),{places:2}).replace(",", "").substr(-2);
		
		if(last_number<=0){last_number='';}
		money_khmer = money_khmer+" "+string+" "+read_in_english_from_10_to_99(decimalmoney_khmer)+''+read_in_english_from_0_to_9(last_number)+' '+str_cent;
		dojo.byId('lable_chartotalreceipt').innerHTML=money_khmer+" US Dollars Only";
		dojo.byId("lblpaid_date").innerHTML = datepay1;
		dojo.byId("lb_descriptionall").innerHTML = lbl_landaddress+" PMT No "+dijit.byId("schedule_opt").attr('displayedValue')+" Date "+datepay1+" "+dijit.byId("payment_method").attr('displayedValue')+" "+dijit.byId('cheque').get('value');
		
			
		dijit.byId("terms").show();	
  }
}
function hideDialog() {		
	dijit.byId("lbl_schedule").hide();
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
var url_add_staff = '<?php echo $this->url(array("module"=>"loan","controller"=>"index","action"=>"add-staff")); ?>';
function addStaff(){
	 if(dijit.byId('frm_staff').validate()){
		dijit.byId("save").attr("disabled",true);
		dojo.xhrPost({
			url:url_add_staff,
			form: dojo.byId("frm_staff"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = { 
		    	  	id: data,
			        name: dijit.byId('kh_name').get('value')
			    };
		 		addDataToSelectbox(dijit.byId('staff_id'), staff_store, Itemmake, data);
			    dijit.byId('frm_staff').reset();
			    dijit.byId("popup_staff").hide();
			},
			error: function(err) {
			
			}
		});
   }
}
function hideDialog1(){
	 dijit.byId("popup_staff").hide();
}
</script>
<style>
.hover:hover{background: #eee;}
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_staff" >
		<form style="background-color: buttonface; width:100%;" id='frm_staff' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_STAFF');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px; line-height: 32px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME_KH');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="kh_name" name="kh_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('SEX');?></td>
									<td><input type="hidden" name="branch_id_pop" id="branch_id_pop" dojoType="dijit.form.TextBox" />
										<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="sex" name="sex" value="" type="text">
											<option value="1"><?php echo $tr->translate("MALE");?></option>
											<option value="2"><?php echo $tr->translate("FEMALE");?></option>
										</select>
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('PHONE');?></td>
									<td>
										<input type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('NOTE');?></td>
									<td>
										<input type="text" name="note_pop" id="note_pop" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
								</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="<?php echo $tr->translate("CANCEL");?>" id="close" name="close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="<?php echo $tr->translate("GO_SAVE");?>" id="save" name="save" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addStaff();"/>
									</td>
								</tr>
							</table>
					</fieldset>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script>
function returnMOnth(monthnum){
	var month = new Array();
	month[1] = "Jan";
	month[2] = "Feb";
	month[3] = "Mar";
	month[4] = "Apr";
	month[5] = "May";
	month[6] = "Jun";
	month[7] = "Jul";
	month[8] = "Aug";
	month[9] = "Sep";
	month[10] = "Oct";
	month[11] = "Nov";
	month[12] = "Dec";
	return month[monthnum];
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function calculateDuration(type=null){
}
</script>