<?php	
	$this->headTitle('Add Sell'); 
	echo $this->headTitle();
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>
.fullside50{ width:48%;}
.agreement{
	border: 1px solid #92b0ea;
    background: #cbdcff;
    font-weight: bold;
    text-align: center;}
</style>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>	
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript"  src="<?php echo $this->baseUrl();?>/js/jquery-1.7.2.min.js"></script>
<script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
</script>
<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'deposit','action'=>'add')); ?>" 
	dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
<script type="dojo/method" event="onSubmit">			
		if(this.validate()) {
            branch_id = dijit.byId('branch_id').get('value');
            if (branch_id=='' || branch_id==-1){
				alert('Please Select Branch!');
				dijit.byId('branch_id').focus();
				return false;
			}
			client = dijit.byId('member').get('value');
			if (client=='' || client==-1){
				alert('Please Select Client Name !');
				dijit.byId('member').focus();
				return false;
			}
              payment_id =dijit.byId("schedule_opt").get("value");
              date_agreement = dijit.byId("date_line").get("value");
            
              if(payment_id==1 && date_agreement==null){ 
				alert("សូមបញ្ចូលថ្ងៃត្រូវមកធ្វើកិច្ចសន្យា");
				dijit.byId("date_line").focus();return false;
              }
			   dijit.byId('saveclose').set('disabled',true);	
			   dijit.byId('savenew').set('disabled',true);
			   return true;
			}else {
				return false;
			}
</script>
<table width="100%" style="margin-top:-5px;" cellspacing="10">
	<tr>
	    <td width="33%" valign="top">
	    	<fieldset>
				<legend><strong style="color:#284db7;"><?php echo $tr->translate("INFO_INDILOAN")?></strong></legend>
		    	<table width="100%" class="padding7" >
		    		<tr>
						<td width="10%"><?php echo $tr->translate("BRANCH_NAME")?></td>
						<td><?php echo $frm->getElement('branch_id');?></td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("SALE_NO")?></td>
						<td><?php echo $frm->getElement('sale_code');?></td>
					</tr>
					<tr>
						<td style="white-space: nowrap;font-weight: bold;"><?php echo $tr->translate("CUSTOMER_NAME")?></td>
						<td><input id="member" /><input dojoType="dijit.form.TextBox" class="fullside" id="joint_with" name="joint_with"  type="hidden"><!-- ពេលបោះពុម្ពចេញអ្នកទិញជាមួយ -->
							<input type="hidden" name="identity_land" id="identity_land"  value="" >
							<input type="hidden" name="land_label" id="land_label" dojoType="dijit.form.TextBox" value="" >
						</td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("CLIENT_NUM")?></td>
						<td>
							<table width="100%">
								<tr>
									<td><input id="customer_code" /><input type="hidden" name="identity" id="identity"  value="" ></td>
									<td width="30%">
										<input iconClass="dijitIconUndo" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="filterClient();"/>
									</td>
								</tr>
							</table>
						</td>
					</tr>
					<tr>
						<td><strong><?php echo $tr->translate("DATE_BUY")?></strong></td>
						<td><?php echo $frm->getElement('date_buy');?></td>
					</tr>
					<tr>
		    			<td style="white-space: nowrap;"><strong><?php echo $tr->translate("AGREEMENT_DATE")?></strong></td>
					    <td><?php echo $frm->getElement('agreement_date');?></td>
					</tr>
					<tr>
						<td style="white-space: nowrap;"><?php echo $tr->translate("CO_NAME")?></td>
						<td><input id="staff_id" /> </td>
					</tr>
					<tr>
						<td><?php echo $tr->translate("COMISSION")?></td>
						<td><?php echo $frm->getElement('commission');?></td>
					</tr>
		    	</table>
		    </fieldset>
	    </td>
	    <td width="33%" valign="top">
	    	<fieldset>
				<legend><strong style="color:#284db7;"><?php echo $tr->translate("PROPERTY_INFO")?></strong></legend>
			    	<table width="100%" class="padding7" >
						<tr height="40px">
							<td style="font-weight: bold;white-space: nowrap;"><?php echo $tr->translate("PROPERY_CODE")?></td>
							<td><?php echo $frm->getElement('typesale');?>
								<input id="land_code" /><input dojoType="dijit.form.TextBox"  id="propertype" name="propertype" type="hidden">
							</td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("DESCRIPTION")?></td>
							<td style="background:#fff;height:25px; border:1px solid #aac4e6; widht:100%; font-size: 13px; color:#284db7;padding:2px;" colspan="4"><label id="land_information" style="max-width:100%;"></label><?php //echo $tr->translate("Address")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("LAND_PRICE")?></td>
							<td><?php echo $frm->getElement('land_price');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("HOUSE_PRICE")?></td>
							<td><?php echo $frm->getElement('house_price');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("TOTAL_SOLD")?></td>
							<td><?php echo $frm->getElement('total_sold');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Discount")?></td>
							<td><?php echo $frm->getElement('discount_percent');?><?php echo $frm->getElement('discount');?></td>
						</tr>
						<tr style="font-weight: bold;">
							<td style="white-space: nowrap;"><?php echo $tr->translate("SOLD_PRICE")?></td>
							<td><?php echo $frm->getElement('sold_price');?></td>
						</tr>
						<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("PAYMENT_TYPE")?></td>
							<td><select name="schedule_opt" id="schedule_opt" dojoType="dijit.form.FilteringSelect" class="fullside" onchange="checkScheduleOption();">
								    <option value="1" ><?php echo $tr->translate("DEPOSIT");?></option>
								    <option value="2" ><?php echo $tr->translate("DEPOSITE_PAYOFF");?></option>
								</select>
							</td>
						</tr>
			    	</table>
			    </fieldset>
	    </td>
		<td valign="top">
			<fieldset>
				<legend><strong style="color:#284db7;"><?php echo $tr->translate("INSTALLMENT_INFO")?></strong></legend>
					<table  width="100%" class="padding7">
						<tr> 
							<td style="font-weight: bold;"><label id="lbl_dateline"><?php echo $tr->translate("DATE_MAKE_AGREEEMNT")?></label></td>
							<td><?php echo $frm->getElement('date_line');?></td>	
						</tr>
						<tr style="background: #edf7f8;">
							<td colspan="2" style="border-bottom:1px solid #aac4e6;"><strong style="color:#284db7;"><?php echo $tr->translate("PAYMENT_INFORMATION")?></strong></td>
						</tr>
							<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("DAY_PAYMENT")?></td>
							<td><input constraints="{datePattern:'dd/MM/yyyy'}" type="text" class="fullside" dojoType="dijit.form.DateTextBox" name="paid_date" id="paid_date"  value="<?php echo date("Y-m-d");?>" ></td>
						</tr>				
						<tr>
							<td style="white-space: nowrap;"><?php echo $tr->translate("PAYMENT_RECEIPT")?></td>
							<td><?php echo $frm->getElement('receipt');?></td>
						</tr>
						<tr>
							<td style="font-weight: bold;"><?php echo $tr->translate("Paid")?></td>
							<td><?php echo $frm->getElement('deposit');?></td>
						</tr>
						<tr>
							<td style="font-weight: bold;"><?php echo $tr->translate("Balance")?></td>
							<td><?php echo $frm->getElement('balance');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NOTE")?></td>
							<td><?php echo $frm->getElement('note')?></td>	
						</tr>
				</table>
			</fieldset>
		</td>
	</tr>
	<tr>
		<td align="center" colspan="3">
			<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
			<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" id='saveclose' name='saveclose' value='saveclose' dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
			<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" id='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
			<input type="button" onclick="printSave('','');displayNone();" label="<?php echo $tr->translate("PREVIEW")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		</td>
	</tr>	
</table>
<div class="dijitHidden">
	<style>
	.print tr td{
		padding:5px 2px; 
	}
	</style>
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'កាលវិភាគត្រូវបង់ប្រាក់'" id="lbl_schedule" style="width: 25cm !important;">
		<div id="rpt_print" class="print" style="text-align: center;">
			<input style="text-align: center;" type="button" onclick="printSave('','');" label="<?php echo $tr->translate("បោះពុម្ភបង្កាន់ដៃ")?>" name='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask" />
		</div>
	</div>
</div>
<div class="dijitHidden" style="width:25cm !important; height: 11cm ; padding: 0px; margin: 0px;">
	<div data-dojo-type="dijit.Dialog" style="width:24cm !important;" align="center" data-dojo-props="title:'<?php echo $tr->translate("PAYMENT_RECEIPT");?>'" id="terms" >
		<div id="divPrint" style="height: 13cm ; padding: 0px; margin: 0px;font-family:'Khmer OS Battambang';">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}
				.label{ font-size: 22px;}
				.value{ font:16px 'Khmer OS Battambang';border: 1px solid #000; height: 30px; padding: 0 2px;width: 100%;margin-right:5px; display: block;
						line-height: 30px;
					    text-align: center;
						}
				.values{ border: 1px solid #000; height: 30px; padding: 0 10px;display: block;
						line-height: 30px;}
				.h{}
				.print tr td{
					padding:2px 2px; 
				}
			   .khmerbold{font:14px 'Khmer OS Battambang';}
			   .khmer{font:14px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;}
			</style>	
			<table style="width:21cm !important; white-space: nowrap;font-size:14px;  padding:-10px 10px 0px 5px;margin-top: -10px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img style="height:75px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:18px 'Kh Muol';" valign="top" align="center"><u><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃទទួលប្រាក់</strong></u>
									<div style="line-height:35px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table style="width:22cm !important;white-space: nowrap;margin-top: -30px;font-family:'Khmer OS Battambang';font-size: 16px;" class="print" cellspacing="3px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="30%" ></td>
					<td width="15%" ></td>
					<td width="17%" ></td>
					<td width="10%" ></td>
					<td width="18%" ></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td colspan="5"></td>
					<td align="right"><strong><label id="lb_receipt" ></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td>លេខកូដលក់</td>
				    <td><strong><label id="lb_sale_id" class="value">3</label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;តម្លៃលក់</td>
                    <td colspan="3" ><strong><label id="lb_price" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td>ឈ្មោះ​អតិថិជន </td>
				    <td><strong><label id="lb_customer" class="value"></label></strong></td>
					<td>​&nbsp;&nbsp;&nbsp;បញ្ចុះតម្លៃ</td>
				    <td><strong><label id="lb_discount" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;តម្លៃផ្សេងៗ</td>
				    <td><strong><label id="lb_otherfee" class="value"></label></strong></td>
                </tr>
				<tr style="white-space: nowrap;">
					<td><?php echo $tr->translate("HOUSE_TITLE");?></td>
                    <td><strong><label id="lb_hourseno" class="value"></label></strong></td>
				    <td>&nbsp;&nbsp;&nbsp;ប្រាក់ត្រូវបង់</td>
                    <td colspan="3"><strong><label id="lb_amount" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td width="10%">ប្រភេទបង់</td>
				    <td width="40%"><strong><label id="lb_paymentid" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;ប្រាក់បានបង់</td>
				    <td colspan="3"><strong><label id="lb_paid" class="value" style="font-weight: bold; font-family:Arial;"></label></strong></td>
				</tr>
				<tr>
					<td>សែក</td>
					<td><strong><label id="lb_moneynote" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;ប្រាក់នៅសល់</td>
					<td colspan="3"><strong><label id="lb_balance" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td>សម្គាល់</td>
				    <td><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_noted" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;ថ្ងៃលក់</td>
				    <td colspan="3"><strong><label id="lb_buydate" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="60px;">
					<td colspan="6">
						<table width="100%" border="0" style="font-size:14px;line-height: 18px;">
							<tr>
								<td width="30%">&nbsp;
								</td>
								<td align="center" width="40%">
									<?php echo $this->data['customer_sign'];?>
								</td>
								<td align="center" width="30%">
									<?php echo $this->data['teller_sign'];?>
								</td>
							</tr>
							<tr>
								<td colspan="3">&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">&nbsp;
								</td>
							</tr>
							<tr>
								<td width="30%">&nbsp;
								</td>
								<td align="center" width="40%">
									<strong><label id="lbl_customer" ></label></strong>
								</td>
								<td align="center" width="30%">
									<strong>
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</strong>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr style="line-height: 20px;font-size: 11px;">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;">សំគាល់ ៖</span>
					</td>
					<td colspan="5">
						<span style="font-size: 13px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 13px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
					</td>
				</tr>
				<tr style="line-height: 15px;">
					<td colspan="6" >
						<table width="100%" style="font-family: 'Khmer OS Battambang'; font-size:13px;line-height: 15px;margin-top: -5px;margin-bottom:15px;white-space:nowrap;"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang'; "><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr style="white-space:nowrap;">
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?> </span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr>
					<td colspan="6" style="border-top:2px dashed #000;" >
					</td>
				</tr>
			</table>
		</div>
		<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
		<button dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconPrint"
			type="button" onclick="doPrint();">បោះពុម្ភ/Print</button>
		<div id="divPrint1" style="width: 21cm !important; height: 13cm ; padding: 0px; margin: 0px;">
			<table width="100%" style="white-space: nowrap;font-size:14px;  padding:-5px 10px 0px 5px;margin-top: 15px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img style="height:75px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:18px 'Kh Muol';" valign="top" align="center"><u><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃទទួលប្រាក់</strong></u>
									<div style="line-height:35px;"><strong style="font-size: 18px;">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table width="100%" style="white-space: nowrap;font-size:16px;margin-top:-30px;font-family: 'Khmer OS Battambang';" class="print" cellspacing="3px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="30%" ></td>
					<td width="15%" ></td>
					<td width="17%" ></td>
					<td width="10%" ></td>
					<td width="18%" ></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td colspan="5"></td>
					<td align="right"><strong><label id="lb_receipt1" ></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td>លេខកូដលក់</td>
				    <td><strong><label id="lb_sale_id1" class="value">3</label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;តម្លៃលក់</td>
                    <td colspan="3" ><strong><label id="lb_price1" class="value"></label></strong></td>
				</tr>				
				<tr style="white-space: nowrap;">
				    <td>ឈ្មោះ​អតិថិជន </td>
				    <td><strong><label id="lb_customer1" class="value"></label></strong></td>
					<td>​&nbsp;&nbsp;&nbsp;បញ្ចុះតម្លៃ</td>
				    <td><strong><label id="lb_discount1" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;តម្លៃផ្សេងៗ</td>
				    <td><strong><label id="lb_otherfee1" class="value"></label></strong></td>
                </tr>
				<tr style="white-space: nowrap;">
					<td><?php echo $tr->translate("HOUSE_TITLE");?></td>
                    <td><strong><label id="lb_hourseno1" class="value"></label></strong></td>
				    <td>&nbsp;&nbsp;&nbsp;ប្រាក់ត្រូវបង់</td>
                    <td colspan="3"><strong><label id="lb_amount1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td width="10%">ប្រភេទបង់</td>
				    <td width="40%"><strong><label id="lb_paymentid1" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;ប្រាក់បានបង់</td>
				    <td colspan="3"><strong><label id="lb_paid1" class="value" style="font-weight: bold; font-family:Arial;"></label></strong></td>
				</tr>
				<tr>
					<td>សែក</td>
					<td><strong><label id="lb_moneynote1" class="value"></label></strong></td>
					<td >&nbsp;&nbsp;&nbsp;ប្រាក់នៅសល់</td>
					<td colspan="3"><strong><label id="lb_balance1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td>សម្គាល់</td>
				    <td><strong style="white-space: nowrap;"><label style="white-space: nowrap;" id="lb_noted1" class="value"></label></strong></td>
					<td>&nbsp;&nbsp;&nbsp;ថ្ងៃលក់</td>
				    <td colspan="3"><strong><label id="lb_buydate1" class="value"></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="60px;">
					<td colspan="6">
						<table width="100%" border="0" style="font-size:14px;line-height: 18px;">
							<tr>
								<td width="30%">&nbsp;
								</td>
								<td align="center" width="40%">
									<?php echo $this->data['customer_sign'];?>
								</td>
								<td align="center" width="30%">
									<?php echo $this->data['teller_sign'];?>
								</td>
							</tr>
							<tr>
								<td colspan="3">&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">&nbsp;
								</td>
							</tr>
							<tr>
								<td width="30%">&nbsp;
								</td>								
								<td align="center" width="40%">
									<strong><label id="lbl_customer1"></label></strong>
								</td>
								<td align="center" width="30%">
									<strong>
										<?php 
										   $session_user=new Zend_Session_Namespace('auth');
										   $last_name=$session_user->last_name;
										   $username = $session_user->first_name;
										   echo $last_name." ".$username;
										?>
									</strong>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr style="line-height: 20px;font-size: 11px;">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;">សំគាល់ ៖</span>
					</td>
					<td colspan="5">
						<span style="font-size: 13px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 13px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" >
						<table width="100%" style="font-family: 'Khmer OS Battambang'; font-size:13px;line-height: 15px;margin-top: -5px;margin-bottom:15px;white-space:nowrap;"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang';"><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr style="white-space:nowrap;">
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
</form>
<script type="text/javascript">	
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.Textarea");					           
var staff_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode($this->co_name));?> );
new dijit.form.FilteringSelect({
	store: staff_store,
	autoComplete: false,
	queryExpr: "*${0}*",                       
    id: "staff_id",
    name: "staff_id",  
    class: 'fullside',  
    required:false,
    placeHolder:"Selected Agent", 
    onChange: function() {        
    	branch_id = dijit.byId('branch_id').get('value');
    	staff_id = dijit.byId('staff_id').get('value');
    	if(branch_id==0){
    		if(staff_id==-1){
    			alert('Please select branch');
    			dijit.byId('branch_id').focus();
    			return false;
        	}
    	}else{
		    if(staff_id==-1){
		    	dijit.byId('branch_id_pop').attr('value',branch_id);
		   		dijit.byId("popup_staff").show();
		    }
    	}
    } 
}, "staff_id");
function displayNone(){
	document.getElementById('divPrint1').style.display="none";
}
function checkScheduleOption(){
	payment_option = dijit.byId("schedule_opt").get("value");
	if(payment_option==2){
		sold_price = dijit.byId("sold_price").get("value");
		dijit.byId("deposit").attr("value",sold_price);
		dijit.byId("balance").attr("value",0);
	}
}
function resetSale(){
	dijit.byId('land_label').attr("value",'');
	$('#identity_land').val('');
	dojo.byId('land_information').innerHTML ="";
	dijit.byId('land_price').attr("value",0);
	dijit.byId('house_price').attr("value",0);
	dijit.byId('total_sold').attr("value",0);
	dijit.byId('sold_price').attr("value",0);
	land_id = dijit.byId("land_code").get("value");
	if(land_id!='' && land_id>0){
		getlandinfo();
	}
}
function calculateDiscount(){
	total_sold = dijit.byId('total_sold').get('value');
	discount = dijit.byId('discount').get('value');
	discount_percent = dijit.byId('discount_percent').get('value');
	
	if(isNaN(discount)){
		discount=0;
	}
	if(isNaN(discount_percent)){
		discount_percent=0;
	}
	discount_percent = parseInt(total_sold*discount_percent/100);
	total_sold = total_sold-discount_percent-discount;
	dijit.byId('sold_price').attr('value',total_sold);
	dijit.byId('remain_balance').attr('value',total_sold);
	Balance();
}
function Balance(){
	price = dijit.byId('sold_price').get('value');
	deposit =dijit.byId('deposit').get('value');
	if(isNaN(deposit)){
		deposit=0;
	}
	dijit.byId('balance').attr('value',price-deposit);
}
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	getAllPropertyBranch(branch_id);
	getLoanByBranch('');
	getReceiptByBranch('');
	getAllClientByBranch(branch_id);
	getAllClientNumberByBranch(branch_id);
}
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_code').set('store', property_store);
		},
		error: function(err) {
		}
	});
} 
var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('customer_code').set('store', client_number_store);
		},
		error: function(err) {
		}
	});
}
var url_getloan = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloannumber')); ?>';
function getLoanByBranch(condition){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getloan,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('sale_code').attr('value',data);
			if(condition==1){
				getReceiptByBranch(data);
			}
		},
		error: function(err) {
		}
	});
}
var url_getreceipt = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'get-receipt-number')); ?>';
function getReceiptByBranch(new_sale_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==''){
		alert('Please Select Branch');
		dijit.byId('branch_id').focus();
		return false;
	}
	dojo.xhrPost({
		url:url_getreceipt,	
		content:{ 
		    'branch_id':branch_id,
		    'is_group':0
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('receipt').attr('value',data);
			if(new_sale_id!=''){
				printSave(new_sale_id,data);
			}
		},
		error: function(err) {
		}
	});
}
    function calCulatorBalance(){
    	price = dijit.byId('land_price').get('value');
    	deposit =dijit.byId('deposit').get('value');
    	if(isNaN(deposit)){
    		deposit=0;
    	}
    	if(deposit>price){
    		alert("Deposit can not biger than price ");
    		dijit.byId('deposit').focus();
    		dijit.byId('deposit').attr('value',price)
    	}
        dijit.byId('balance').attr('value',price-deposit);
    }
	function hideDialog() {		
		dijit.byId("recript_dialog").hide();
		saveTrans(); 
	}
	function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML + dojo.byId('divPrint1').innerHTML;;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    printSubmit();
		hideDialog();
	}
	function printSubmit(){
		$('#frm_add_tran').submit();
	}
</script>
<script type="text/javascript">
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_name));?> );
var client_number_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_code));?> );
var co_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->co_name));?> );
var property_store  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	 ready(function(){
		 dijit.byId("date_line").set("readOnly",false);
	  });
	 
	new dijit.form.FilteringSelect({
			store: property_store,
			autoComplete: false,
			queryExpr: "*${0}*",
			required: false,		           
			name: "land_code",
			id: "land_code",
			searchAttr: "name",
			class: 'fullside fullside50',
			required:true,
			onChange: function() {
				land_code = dijit.byId('land_code').get('value');
				if(land_code==-1){
				}else{
					getlandinfo();
				}
		}
			}, "land_code");
	 
	new dijit.form.FilteringSelect({
	store: client_store,
	autoComplete: false,
	queryExpr: "*${0}*",	           
	name: "member",
	id: "member",
	searchAttr: "name",
	required:true,
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			window.open('<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add'))?>');
		}else{
			dijit.byId('customer_code').attr('value',member);
			getcustomerinfo(member);
		}
   }
	}, "member");
	
	new dijit.form.FilteringSelect({
	store: client_number_store,
	autoComplete: true,
	required: false,		           
	name: "customer_code",
	id: "customer_code",
	searchAttr: "name",
	class: 'fullside',
	onChange: function() {
		customer_code = dijit.byId('customer_code').get('value');
		if(customer_code==-1){
			window.open('<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'add'))?>');
		}else{
			dijit.byId('member').attr('value',customer_code);
		}
    }
	}, "customer_code");
});
</script>
<script type="text/javascript">
var url_getcustomer = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclient')); ?>';
function getcustomerinfo(client_id){
	dojo.xhrPost({
		url:url_getcustomer,	
		content:{ 
		    'client_id':client_id
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId('joint_with').attr('value',data.hname_kh);
		},
		error: function(err) {
			alert(err);
		}
	});
}
var url_getlandinfodetail = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'getlandinfo')); ?>';
function getlandinfo(){
	var typesale =dijit.byId('typesale').get('value');
	var oldprice= dijit.byId('total_sold').get('value');
	var land_price= dijit.byId('land_price').get('value');
	var house_price= dijit.byId('house_price').get('value');
	land_id = dijit.byId('land_code').get('value');
	if(land_id==''){return false;}
	dojo.xhrPost({
		url:url_getlandinfodetail,	
		content:{ 
		    'land_id':land_id
		},		    
		handleAs:"json",
		load: function(data) {
			if(typesale==2){//multi
				var had = 0;
		 		var landcode= dijit.byId('land_code').get('value');
		 		var rowId = $('#identity_land').val();
			 	if($("#identity_land").val()!='') {
			 		var rowIDArray = rowId.split(',');
		 			for(var n = 0; n < rowIDArray.length; n++) {
		 				if(landcode == rowIDArray[n]){
			 				alert("លេខដី/ផ្ទះ នេះបានជ្រើសរើសរួចហើយ");
			 				had = 1;
		 				}
		 			}
				 	if(had==1){}else{
						var identity = $("#identity_land").val();
						var price = oldprice + parseFloat(data.price);
						house_price = house_price+parseFloat(data.house_price);
						land_price = land_price+parseFloat(data.land_price);
						
						oldland_code =  oldland_code+","+data.land_code;
						address = address+"/"+data.land_address+','+data.street;
						size = parseFloat(size)+parseFloat(data.land_size);
						height = height+" , "+data.height;
						width = width+" , "+data.width;
						$("#identity_land").val(identity+','+data.id);
						
						dijit.byId('total_sold').attr('value',price);
						dijit.byId('sold_price').attr('value',price);

						dijit.byId('land_price').attr('value',land_price);
						dijit.byId('house_price').attr('value',house_price);
						
						dojo.byId('land_information').innerHTML ="លេខដី/ផ្ទះ  "+address+", ទំហំ "+size+" ម៉ែត្រការ៉េ ";
						dijit.byId('land_label').attr('value',address);
						}
				}else {
						$("#identity_land").val(data.id);
						dijit.byId('total_sold').attr('value',data.price);
						dijit.byId('sold_price').attr('value',data.price);

						dijit.byId('land_price').attr('value',data.land_price);
						dijit.byId('house_price').attr('value',data.house_price);

						oldland_code = data.land_code;
						address = data.land_address+','+data.street;
						size = data.land_size;
						height = data.height;
						width = data.width;
						dijit.byId('land_label').attr('value',address);
						dojo.byId('land_information').innerHTML ="លេខដី/ផ្ទះ  "+address+","+" ទំហំ "+size+" ម៉ែត្រការ៉េ ";
				}
			}else{//normal
				var price = oldprice + parseFloat(data.price);			
				dijit.byId('land_price').attr('value',data.land_price);
				dijit.byId('house_price').attr('value',data.house_price);
				dijit.byId('total_sold').attr('value',data.price);
				dijit.byId('sold_price').attr('value',data.price);
				dojo.byId('land_information').innerHTML ="លេខសម្គាល់ "+data.land_code+", លេខផ្ទះ/ឡូតិ៏  "+data.land_address+", លេខផ្លូវ  "+data.street+", ប្រភេទ  "+data.property_type+", ទំហំ "+data.land_size+" ម៉ែត្រការ៉េ, បណ្តោយ "+data.height+" ម៉ែត្រ, ទទឹង  "+data.width+" ម៉ែត្រ";
				dijit.byId('propertype').attr('value',data.house_type);
			}
		},
		error: function(err) {
		}
	});
}
function getClientInfo(type){
	if(type==1){
		customer_code= dijit.byId('customer_code').get('value');
		dijit.byId('member').attr('value',customer_code);
	}else{
		customer_code= dijit.byId('member').get('value');
		dijit.byId('customer_code').attr('value',customer_code);
	}
}
</script>
<script>
function printSave(new_stu_id,new_receipt_no){
	deposit = dijit.byId('deposit').get('value');
	if (deposit=='' || deposit==-1){
		alert('សូមបញ្ចូលប្រាក់ត្រូវបង់ ទើបបោះពុម្ភបង្កាន់ដៃបង់ប្រាក់បាន!');
		dijit.byId('deposit').focus();
		return false;
	}
	schedule_opt = dijit.byId("schedule_opt").get("value");
	if(schedule_opt==1 && new_receipt_no!=''){
		var r = confirm("<?php echo $tr->translate("ALERT_DEPOSIT_WARNING");?>"+"\n"+"<?php echo $tr->translate("ALERT_BEFORE_SAVE");?>");
		if (r == true) {
			
		} else {
		    return false;
		}
	}
	symbal=" $";
	if(new_stu_id=='' && new_receipt_no==''){
		getLoanByBranch(1);
		return false;
	}else{
		dojo.byId("lb_sale_id").innerHTML = new_stu_id;
		dojo.byId("lb_receipt").innerHTML = new_receipt_no;
		dojo.byId("lb_sale_id1").innerHTML = new_stu_id;
		dojo.byId("lb_receipt1").innerHTML = new_receipt_no;
	}
	if(dijit.byId('frm_add_tran').validate()){
		dijit.byId("lbl_schedule").hide();
		dojo.byId("lb_paymentid").innerHTML = dijit.byId("schedule_opt").attr('displayedValue');
	
		date_payment = dijit.byId("date_buy").get('value');
		var a = new Date(date_payment);
		mm = a.getMonth()+1;
		var dd = a.getDate();
		 if(dd<10){
			 dd = "0"+dd;
		}
		month = returnMOnth(mm);
		var y = a.getFullYear();
		var date_payment = dd +'-'+month+'-'+y ;
		
		dojo.byId("lb_buydate").innerHTML = date_payment; //dijit.byId("date_buy").attr('displayedValue');
		lbl_landaddress = dijit.byId("land_code").attr('displayedValue')+dijit.byId("propertype").attr('displayedValue');
		sale_type = dijit.byId("typesale").get('value');
		if(sale_type==2){
			lbl_landaddress =  dijit.byId("land_label").get('value');
		}
		dojo.byId("lb_hourseno").innerHTML = lbl_landaddress;
		dojo.byId("lb_price").innerHTML = "$ "+dojo.number.format(dijit.byId("total_sold").get('value'),{places:2});
	
		total_sold = dijit.byId('total_sold').get('value');
		discount_percent = dijit.byId('discount_percent').get('value');
		if(isNaN(discount_percent)){
			discount_percent=0;
		}
		discount = dijit.byId('discount').get('value');
		if(isNaN(discount)){
			discount=0;
		}
		
		discount_percent = total_sold*discount_percent/100;
		total_discount = parseInt(discount_percent)+parseFloat(discount);
		dojo.byId("lb_discount").innerHTML = symbal+" "+dojo.number.format(total_discount,2);
		dojo.byId("lb_amount").innerHTML = "$ "+dojo.number.format(dijit.byId("sold_price").get('value'),{places:2});
		dojo.byId("lb_paid").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
		balance = dijit.byId("balance").get('value');
		if(isNaN(balance)){balance=0;}
		dojo.byId("lb_balance").innerHTML = "$ "+dojo.number.format(balance,{places:2});
		dojo.byId("lb_noted").innerHTML =dijit.byId("note").get('value');
		dojo.byId("lb_paymentid1").innerHTML = dijit.byId("schedule_opt").attr('displayedValue');
		dojo.byId("lb_buydate1").innerHTML = date_payment;//dijit.byId("date_buy").attr('displayedValue');
		dojo.byId("lb_hourseno1").innerHTML = lbl_landaddress;//dijit.byId("land_code").attr('displayedValue')+dijit.byId("propertype").attr('displayedValue');
		dojo.byId("lb_price1").innerHTML = "$ "+dojo.number.format(dijit.byId("total_sold").get('value'),{places:2});
		dojo.byId("lb_discount1").innerHTML = symbal+" "+dojo.number.format(total_discount,2);//dis_percent+discount;//dijit.byId("discount").get('value');
		
		dojo.byId("lb_amount1").innerHTML = "$ "+dojo.number.format(dijit.byId("sold_price").get('value'),{places:2});
		dojo.byId("lb_paid1").innerHTML = "$ "+dojo.number.format(dijit.byId("deposit").get('value'),{places:2});
		dojo.byId("lb_balance1").innerHTML = "$ "+dojo.number.format(balance,{places:2});
		dojo.byId("lb_noted1").innerHTML =dijit.byId("note").get('value');
		joint_with = dijit.byId("joint_with").attr('displayedValue');
		if(joint_with!=''){joint_with = "/"+joint_with}
		
		dojo.byId("lbl_customer1").innerHTML = dijit.byId("member").attr('displayedValue')+joint_with;
		dojo.byId("lb_customer1").innerHTML = dijit.byId("member").attr('displayedValue');
		dojo.byId("lbl_customer").innerHTML = dijit.byId("member").attr('displayedValue')+joint_with;
		dojo.byId("lb_customer").innerHTML = dijit.byId("member").attr('displayedValue');	
		dijit.byId("terms").show();	
  }
}
function hideDialog() {		
	dijit.byId("lbl_schedule").hide();
}
function loading(){
    document.getElementsByClassName("overlay")[0].style.display="block";
}
var url_add_staff = '<?php echo $this->url(array("module"=>"loan","controller"=>"index","action"=>"add-staff")); ?>';
function addStaff(){
	 if(dijit.byId('frm_staff').validate()){
		dojo.xhrPost({
			url:url_add_staff,
			form: dojo.byId("frm_staff"),
			handleAs:"json",
			load: function(data) {
				var Itemmake = { 
		    	  	id: data,
			        name: dijit.byId('kh_name').get('value')
			    };
		 		addDataToSelectbox(dijit.byId('staff_id'), staff_store, Itemmake, data);
			    dijit.byId('frm_staff').reset();
			    dijit.byId("popup_staff").hide();
			},
			error: function(err) {
				alert("err"+err);
			}
		});
   }
}
function hideDialog1(){
	 dijit.byId("popup_staff").hide();
}
</script>
<style>
.hover:hover{background: #eee;}
.overlay {display: none;position: absolute;width: 100%;height: 100%;top: 0px;left: 0px;background: #FCFCFC;z-index: 1001;opacity: .95;}
.overlay-load {width: 350px;height: 100px;margin: auto;top: 0px;bottom: 0px;position: absolute;left: 0px;right: 0px;
           border: solid 1px #060522;text-align: center;
           background: #fff url("<?php echo $this->baseUrl()?>/images/loading.gif") 50% 25%;
           background-repeat: no-repeat;          
}
.overlay-msg{margin-bottom: 10px;bottom: 0px;position: absolute;font-style: italic;color: rgb(19, 19, 19);} 
</style>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" style="width:30%;" id="popup_staff" >
		<form style="background-color: buttonface; width:100%;" id='frm_staff' dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<table cellspacing="10" width="100%" style="margin: 0 auto;">
				<tr>
					<td>
						<fieldset style="background-color: buttonface;">
						<legend align="center" ><?php echo $tr->translate('ADD_STAFF');?></legend>
							<table style="margin: 0 auto; width: 100%;  padding:10px;" cellspacing="7" >
								<tr>
									<td><?php echo $tr->translate('NAME_KH');?></td>
									<td>
										<input dojoType="dijit.form.ValidationTextBox" required="1" class="fullside" id="kh_name" name="kh_name" value="" type="text">
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('SEX');?></td>
									<td><input type="hidden" name="branch_id_pop" id="branch_id_pop" dojoType="dijit.form.TextBox" />
										<select dojoType="dijit.form.FilteringSelect"  class="fullside" id="sex" name="sex" value="" type="text">
											<option value="1"><?php echo $tr->translate("MALE");?></option>
											<option value="2"><?php echo $tr->translate("FEMALE");?></option>
										</select>
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('PHONE');?></td>
									<td>
										<input type="text" name="phone" id="phone" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
								</tr>
								<tr>
									<td><?php echo $tr->translate('NOTE');?></td>
									<td>
										<input type="text" name="note_pop" id="note_pop" class="fullside" dojoType="dijit.form.TextBox" />
									</td>
								</tr>
								<tr>
									<td colspan="4" align="center">
										<input type="button" value="ចាកចេញ" label="<?php echo $tr->translate("CANCEL");?>" id="close" name="close" dojoType="dijit.form.Button" 
										​ ​​iconClass="dijitIconUndo" onclick="hideDialog1();"/>
										<input type="button" value="save" label="<?php echo $tr->translate("GO_SAVE");?>" id="save" name="save" dojoType="dijit.form.Button" 
										 iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addStaff();"/>
									</td>
								</tr>
							</table>
					</fieldset>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script>
function returnMOnth(monthnum){
	var month = new Array();
	month[1] = "Jan";
	month[2] = "Feb";
	month[3] = "Mar";
	month[4] = "Apr";
	month[5] = "May";
	month[6] = "Jun";
	month[7] = "Jul";
	month[8] = "Aug";
	month[9] = "Sep";
	month[10] = "Oct";
	month[11] = "Nov";
	month[12] = "Dec";
	return month[monthnum];
}
function getDayName(day){
	 var weekday = new Array(7);
	    weekday[0] = "អាទិត្យ";
	    weekday[1] = "ច័ន្ទ";
	    weekday[2] = "អង្គារ";
	    weekday[3] = "ពុធ";
	    weekday[4] = "ព្រហ";
	    weekday[5] = "សុក្រ";
	    weekday[6] = "សៅរ៍";
	    return weekday[day];
}
function calculateDuration(type=null){
}
</script>