<?php 
	$tr=Application_Form_FrmLanguages::getCurrentlanguage();
	$base_url = Application_Form_FrmMessage::getUrl("/");
	$request=Zend_Controller_Front::getInstance()->getRequest();
	$action=$request->getActionName();
	$controller=$request->getControllerName();
	$module=$request->getModuleName();
	
	$session_user=new Zend_Session_Namespace('authinstall');
	$username = $session_user->first_name;
	$user_id = $session_user->user_id;
	if(empty($user_id)){
			Application_Form_FrmMessage::redirectUrl("/");
	}
	$them_style = 'soria'; //$session_user->theme_style;
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
	<meta name="apple-mobile-web-app-capable" content="yes" />
	<link rel="stylesheet" href="<?php echo $base_url;?>css/font-awesome.min.css"/>

	<link rel="stylesheet" href="<?php echo $base_url;?>css/template.css"/>
	<link href="<?php echo $base_url;?>cssmenu/template.css" media="screen" rel="stylesheet" type="text/css">
	<!-- table  -->
	<?php //if($action=='index'){ ?>
	<?php if($module!='home'){?>
	    <link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>js/dojo-1.6.1/dijit/themes/<?php echo $them_style."/".$them_style?>.css" />
        <script src="<?php echo $this->baseUrl()."/contextMenu/1.11.3/"?>jquery.min.js"></script>
       <?php //if($action=='index'){?>
	<!-- 
	<script type="text/javascript" src="<?php //echo $this->baseUrl();?>/js/jquery.tablesorter.js"> </script>
	<script type="text/javascript" src="<?php //echo $this->baseUrl();?>/js/jquery.tablesorter.pager.js"> </script>
	 -->
       <?php  } ?>
	<?php //}?>
	<!-- export library -->
	<?php if($module=='report'){?>
	 <script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/tableExport.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jquery.base64.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/html2canvas.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/sprintf.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/jspdf.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl();?>/tableexport/jspdf/libs/base64.js"></script> 

	<?php } ?>	
	<?php if ($action=="index"){?>
	<link href="<?php echo $this->baseUrl()."/contextMenu/"?>jquery.contextMenu.css" rel="stylesheet" type="text/css" />
	<script src="<?php echo $this->baseUrl()."/contextMenu/"?>jquery.contextMenu.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl()."/contextMenu/"?>jquery.ui.position.min.js" type="text/javascript"></script>
	
	<link href="<?php echo $this->baseUrl()."/datatable/"?>datatables.min.css" rel="stylesheet" type="text/css" />
    <script src="<?php echo $this->baseUrl()."/datatable/"?>datatables.min.js" type="text/javascript"></script>
    
    <script>
	    $(document).ready(function() {
	        $('#datatable-responsive').DataTable( {
	       	 "dom": '<"top"i>rt<"bottom"flp><"clear">',
	        	searching: false,
	        } );
	    } );
    </script>
	<?php }?>
	
	<?php if($module!='home'){?>
	<script src="<?php echo $base_url;?>js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
	<script>dojoConfig = {parseOnLoad: true}</script>
	    <script>
			require(["dijit/form/Form","dijit/form/FilteringSelect","dijit/form/Button","dijit/Dialog"]);
      </script>
<?php }?>
	<!-- end -->
	<link rel="shortcut icon" href="<?php echo $base_url;?>images/icon.ico" type="image/x-icon"/>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
	<style type="text/css">
		*{ padding:0;margin:0;}
        html, body { width: 100%; height: 100%; margin: 0; }
		.btn{
			height: 40px;
			min-width: 100px;	
		}
		.soria .dijitButtonText {
		    line-height: 30px;
		}
		#menu ul {
		    margin: 0;
		}
		.add-link{  
        background-color: #0f2a5b;
	    /* width: 90px; */
	    /* margin-top: 2px; */
	    color: #fff;
	    text-align: center;
	    font-size: 13px;
	    font-weight: 600;
	    padding: 3px 15px;}
		.fullside{ width:98%; height: 28px;}
		.full{ width:100%;}
		body, html {font-size:98%; 
		background: linear-gradient(to right, #f7f7ff, #adc9ff);
		font-family: Helvetica,sans-serif,'Kh Battambang','Khmer Battambang';}
		.normal,.alternate{ font-size:90% !important;}
        
		fieldset{ font-family: inherit;}
		.border{ border: 1px solid #ccc; height: 100%; margin: 5px; padding: 5px;}
        .border1{ border: 1px solid #ccc; height: 100%; margin: 5px; margin-left:0px; padding: 5px;}
		.hover:hover{background: #eee;}
		.odd{background-color: #f9f9f9;
		}
	</style>	
	
</head>
    <body class="<?php echo $them_style;?>" >
            <table width="100%">
                <tr >
                	<td colspan="2" valign="top" style="position: fixed;width: 100%; z-index: 1;top: 0;" >
                		 <?php echo $this->render('header.phtml')?>
			                <p style="font-size:13px !important;background: #fff;">
				                <span style="padding-left: 3px;padding-right: 3px; display: inline-block; font-weight:600;"> <i class="fa fa-user" aria-hidden="true" style="line-height: 25px; font-size: 22px; color: #0f2a5b;"></i></span>
							    <span style="padding-left: 3px;padding-right: 3px; display: inline-block; font-weight:600;"> <?php //echo $tr->translate("USING_BY");?><a title="<?php echo $tr->translate("CHANGEPASSWORD");?>" style="color: #000098; text-transform: capitalize; font-size: 14px;" href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'changepassword')); ?>"><?php echo $username;?></a></span>  
								<span style="padding-left: 3px;padding-right: 3px; display: inline-block; font-weight:600;"> <a title="<?php echo $tr->translate("SIGN_OUT");?>" href="<?php echo $this->url(array('module'=>'','controller'=>'index','action'=>'logout','value'=>'1')); ?>" style="color: #000098; text-transform: capitalize;"> | <?php echo $tr->translate("SIGN_OUT");?></a></span>
				                <?php if($module!='home'){?>
				                <span style="padding-left: 3px;padding-right: 3px; display: inline-block; font-weight:600;"> <i class="fa fa-building" title="<?php echo $tr->translate("CALCULATOR");?>" aria-hidden="true" style="cursor:pointer; line-height: 25px; font-size: 22px; color: #0f2a5b;" onclick="dijit.byId('popupCalculator').show();" ></i></span>
				                <?php }?>
				                 <?php if($action=='index' AND $module!='report' AND $module!='home' AND $controller!='updateprice'){?>
				                	 <a class='add-link' style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'add'),null,true); ?>"><?php echo $tr->translate('ADD');?> <i class="fa fa-plus-circle" aria-hidden="true"></i></a>
								<?php }elseif($action=='add' OR $action=='edit' OR $module=='report'){?>
								 	<span style="padding-left: 3px;padding-right: 3px; float: right; font-weight:600;"><a class='add-link' style="float:right;" href="<?php echo $this->url(array('module'=>$module,'controller'=>$controller,'action'=>'index'),null,true); ?>"><i class="fa fa-arrow-circle-o-left" aria-hidden="true"></i> <?php echo $tr->translate('GO_BACK');?></a></span>
								<?php }?>
						</p>
                	</td>
                </tr>
                <tr style=" background: #fff;">
                	<td colspan="2" height="90px;"></td>
                </tr>
            	<tr>
            		<?php if($module!='home' AND $module!='report'){?>
            		<td valign="top" <?php if($module!='home') echo'width="40px"';  ?> >            			 
            			<?php echo $this->render('menuleft.phtml')?>            			
            		</td>
            		<?php }?>
            		<?php
            		$background='';
            		if($module=='report'){ $background='background:#fff;';}?>
            		<td valign="top" style="position: relative;<?php echo $background?>"  >
            			<?php 
            			if($module=='report' AND $action!='index'){?>
							<!-- 
							<div class="menureport">
								<ul>
									<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
									<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
									<li class="excel"><a href="#"  title="Export"  onclick="exportExcel();"></a></li>
								</ul>
							</div>
							 -->
							<div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
								<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
									<i class="fa fa-print"></i>
								</div>
								<div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
								<div class="ptss__settings">
									<div class="ptss__single-setting" id="ptss__layout">
										<div class="ptss__setting-control">
											<div class="ptss__layout-wrapper">
												<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
												<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
												<a class="qButton excel" href="#"  title="<?php echo $tr->translate("Export");?>"  onclick="exportExcel();"><i class="fa fa-file-excel-o" aria-hidden="true"></i></a>
											</div>
											
										</div>
									</div>
								</div>
							</div>
							<div style="clear:both;"></div>
							<?php }?>
            			<?php 
							$db = new Application_Model_DbTable_DbUsers();
	            			$rs = $db->getAccessUrl($module,$controller,$action);
	            			echo $this->layout()->content;
	            			if(!empty($rs) OR $action=='changepassword'){
	            				//echo $this->layout()->content;
	            			}else{
	            				//echo $this->render('pagenotfund.phtml');
	            			}
            			 ?>
            			<?php
			               	if($module=='report' AND $action!='rpt-paymentschedules'){
			            ?>
		                <?php }?>
            		</td>
            	</tr>
            </table>
           <?php  if( $module!='home') { echo $this->render('calculator.phtml'); }?>
    </body>

<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php if($module=='report' AND $action!='index'){?>
<script type="text/javascript">
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
function hideleft(){
	(dojo.style("leftmenu","display") == "none") ? 'show':'hide'();
}
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,fullscreen=yes, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function exportExcel(){
	$('#exportExcel').tableExport({type:'excel',escape:'false'});
}
jQuery(function () {
	'use strict';
	
	jQuery(".ptss__toggle-btn").click(function () {	
		jQuery('.js-ptss-frame').toggleClass('is-opened');
	});
	
	jQuery('.ptss__layout-wrapper > div').click(function(){
		
		jQuery(this).closest('.ptss__setting-control').find('.ptss__layout-wrapper').removeClass('is-selected');
		
		jQuery(this).parent().addClass('is-selected');
		
		if( jQuery(this).hasClass('ptss__layout-box--wide') ) {
			
			jQuery('body').removeClass('boxed');
			jQuery('#ptss__boxed-bg').hide();
			
			jQuery('body').removeClass('bg1').removeClass('bg2').removeClass('bg3').removeClass('bg4');
			
			jQuery('#ptss__boxed-backgrounds span').removeClass('is-selected');
			
		} else {
			
			jQuery('body').addClass('boxed');
			jQuery('#ptss__boxed-bg').show();
			
		}
		
	});
})
</script>
<?php }?>
</html>