  <?php 
  	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
  ?>
  <title><?php echo $tr->translate("REPORT");?></title>
  <div class="card">
	<div class="card-content collapse show">
		<div class="card-box report-list">
		  	<div class="row top_tiles">
			  	 <?php
			  	 	$db_user=new Application_Model_DbTable_DbUsers();
			  		$report_url =  $db_user->getArrAclReport(null);
			   	   if(!empty($report_url)){
			   	   foreach($report_url as $url){
			   	   if($url['action']=='index' OR $url['controller']=='incomeexpense' OR $url['controller']=='plongandhouse' OR $url['controller']=='stockreport' OR $url['action']=='receipt' 
			   	   		OR $url['action']=='rpt-updatepayment' OR $url['action']=='updatereceipt'
			   	   		OR $url['action']=='rpt-updatestatus' OR $url['action']=='bug' OR $url['action']=='submitentry' OR $url['action']=='commissionreceipt' 
			   	   			OR $url['action']=='paymenthistory' 
			   	   			OR $url['action']=='verifyagreement' 
			   	   			OR $url['action']=='issue-agreement'
			   	   			OR $url['action']=='rpt-saleprofile'
			   	   			OR $url['action']=='rpt-customer-contact' 
							OR $url['action']=='rpt-materialinlude-detail' 
							OR $url['action']=='submitentryunclosed' 
							OR $url['action']=='rpt-verification-detail' 
							OR $url['action']=='rpt-combine-payment-receipt'
			   	   		){continue;}
			   	   	?>
					<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a href="<?php echo $this->url(array('module'=>$url['module'],'controller'=>$url['controller'],'action'=>$url['action'])); ?>">
						<div title="<?php echo $tr->translate($url['label']);?>" class="tile-stats report-list">
							<div class="icon"><i class="fa fa-book"></i></div>
							<div class="count">&nbsp;</div>
			                 	<h3><?php echo $tr->translate($url['label']);?></h3>
						</div>
						</a>
			        </div> 
			        <?php }
				}?>
				<?php 
				$dbacc = new Application_Model_DbTable_DbUsers();
				$rs = $dbacc->getAccessUrl("report","loan",'bug');
				if(!empty($rs)){
				?>
					<div class="animated flipInY col-lg-3 col-md-3 col-sm-6 col-xs-12">
						<a style="color:red;" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'bug')); ?>">
						<div class="tile-stats report-list error">
							<div class="icon"><i class="fa fa-book"></i></div>
							<div class="count">&nbsp;</div>
			                 	<h3><?php echo $tr->translate("CHECK_MISTACK");?></h3>
						</div>
						</a>
			        </div> 
				<?php }?>
				
			   </div>
		  </div>
		</div>
	</div>
  <div style="clear: both;"></div>	