<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$day = array(
		"Mon" =>'ច័ន្ទ',
		"Tue" =>'អង្គារ',
		"Wed" =>'ពុធ',
		"Thu" =>'ព្រហស្បតិ៍',
		"Fri" =>'សុក្រ',
		"Sat" =>'សៅរ៍',
		"Sun" =>'អាទិត្យ',
		);
$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
?>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title><?php echo $tr->translate("AGREEMENT");?></title>
<style>
	.reff{ font-size: 20px !important; line-height:34px !important;}
#divPrint tr td h2,#divPrint p, #divPrint pre, #divPrint span{ font-size: 20px !important; line-height:34px !important;}
</style>
<div  id="exportword" style=" width:28cm;min-height:22cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.5cm">
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
	<tr>
    	<td align="center">
	    	<div id="divPrint">
	    	 	<style>
					th{padding: 5px;}
					span.value{ line-height:12px;display: inline-block; border-bottom: 1px #000 dotted;text-align: center;}
					span.child {display:block; margin-left:25px; line-height: 25px;}
					span{line-height: 26px;}
					.noted,.noted span{white-space: pre-wrap;     
						word-wrap: break-word;      
						word-break: break-all;
						white-space: pre;
					    font:12px Khmer OS Battambang;
                        line-height:10px !important;font-weight: normal !important;
					
					}
				</style>
	        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';" style="padding:0;margin:0;border:0px;" >
	        	<tr>
	                <td width="25%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" style="max-width:100%"></td>
	                <td width="50%" align="center">
	                <span style="text-align:center; line-height:28px; font-size:16px;font-family:'Khmer OS Muol Light';">ព្រះរាជាណាចក្រកម្ពុជា</span>
	                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:14px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
	                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:14px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/agreementsign.JPG" height="25px"></span>
	                <span style="text-align:center; line-height:28px; width: 100%; display: block; font-size:14px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("កិច្ចព្រមព្រៀងបន្ថែម និងការប្រគល់-ទទួលផ្ទះ");?></span>
	                <td width="25%"></td>
	             </tr> 
	             <tr>
	             	<td colspan="3">
	             		<p style="font-family: 'Times New Roman','Khmer OS Battambang'; text-align:justify; line-height:24px; font-size:14px; font-weight: normal !important;">
	             			<span style="display: block; width: 100%; line-height: inherit;">
	             			<span style="width: 100%; display: block;text-align: center;"> <span class="child" >កិច្ចព្រមព្រៀងនេះត្រូវបានធ្វើឡើងនៅថ្ងៃទី <?php echo date("d",strtotime($this->agreement['issue_date']));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['issue_date']))];?> ឆ្នាំ <?php echo date("Y",strtotime($this->agreement['issue_date']));?>ដោយ និង រវាង ៖</span></span>
	             			 លោក <span style="font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['project_manager_namekh'];?></span> កាន់អត្តសញ្ញាណប័ណ្ណសញ្ជាតិខ្មែរលេខ <span style="font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['project_manager_nation_id'];?></span> 
	             			មានអាសយដ្ឋាននៅ<?php echo $this->agreement['project_manager_p_current_address'];?>ម្ចាស់<span style="font-family:'Khmer OS Muol Light';font-weight:200;">(“អ្នកលក់”)</span>។
	             			</span>
	             			<span style="width:100%; display: block;text-align: center;font-style: italic;">និង</span>
	             			<span style="width:100%; display: block;">លោក-លោកស្រី <span class="value" style="min-width:50px;font-family:'Khmer OS Muol Light';font-weight:200;"><?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"/".$this->agreement['hname_kh']:"";?></span> ជាជនជាតិ <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_nationality'];?></span> កាន់អត្តសញ្ញាណប័ណ្ណលេខ <span class="value" style="min-width:80px;"><?php echo $this->agreement['client_nation_id'];?></span>
	             			មានអាស័យដ្ឋាន ផ្ទះលេខ: <span class="value" style="min-width:55px;"><?php echo $this->agreement['client_house_no'];?></span> ផ្លូវលេខ  <span class="value" style="min-width:55px;"><?php echo $this->agreement['client_street'];?></span> 
	             			សង្កាត់  <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_commune_kh'];?></span> 
	             			ខណ្ឌ <span class="value" style="min-width:50px;"><?php echo $this->agreement['client_districtkh'];?></span>
	             			ខេត្ត-រាជធានី <span class="value" style="min-width:50px;">&nbsp;<?php echo $this->agreement['client_province_kh'];?></span><span style=" font-family:'Khmer OS Muol Light';font-weight:200;">(“អ្នកទិញ”)</span>​។</span>
	             			<span style="width: 100%; display: block;"> <span class="child" >ដោយយោងលើកិច្ចព្រមព្រៀងទិញនិងលក់ផ្ទះចុះថ្ងៃទី<?php echo date("d",strtotime($this->agreement['agreement_date']));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo date("Y",strtotime($this->agreement['agreement_date']));?> ភាគីទាំងពីរព្រមព្រៀងគ្នាក្នុង លក្ខខ័ណ្ឌបន្ថែមដូចតទៅ ៖ </span></span>
	             			<span  style="width: 100%; display: block;"><span style=" font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ១ ៖ </span>អនុលោមតាមប្រការ ២.៧ នៃកិច្ចព្រមព្រៀងទិញនិងលក់ផ្ទះរវាងភាគីទាំងពីរ អ្នកលក់បានសម្រេចបញ្ចប់ការសាងសង់ ជាស្ថាពរមុនកាលកំណត់ ហើយភាគីអ្នកទិញព្រមព្រៀងគ្នាក្នុងការបង់ប្រាក់ដូចមានចែងក្នុងប្រការ ២ ខាងក្រោមនេះ។</span>
	             			<span  style="width: 100%; display: block;"><span style=" font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ២ ៖  </span>អ្នកលក់យល់ព្រមប្រគល់ផ្ទះ ឲ្យអ្នកទិញ ហើយអ្នកទិញយល់ព្រមទទួលផ្ទះពីអ្នកលក់នូវប្រភេទ
	             				ប្រភេទ  <span class="value" style="min-width:50px;"><?php echo $this->agreement['property_type_en'];?></span> ផ្ទះលេខ <span class="value" style="min-width:30px;font-weight: bold;"><?php echo $this->agreement['property_title'];?></span> 
	             				ផ្លូវលេខ: <span class="value" style="min-width:50px;"><?php echo $this->agreement['property_street'];?></span> នៅបុរីភ្នំពេញថ្មី (<?php echo $this->agreement['project_name'];?>) <?php echo $this->agreement['project_location'];?>
	             				<span style="">គិតចាប់ពីធ្វើកិច្ច ព្រមព្រៀងនេះតទៅ ប៉ុន្តែអ្នកទិញមានកាតព្វកិច្ចបន្តការបង់ប្រាក់ តាមតារាងបង់ប្រាក់ ក្នុង<?php echo $tr->translate("ARTICLE_1");?>
 								ដូចមានចែងក្នុងប្រការ៣ នៃកិច្ចព្រមព្រៀងទិញនិងលក់ផ្ទះចុះថ្ងៃទី<?php echo date("d",strtotime($this->agreement['agreement_date']));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo date("Y",strtotime($this->agreement['agreement_date']));?> ឲ្យបាន ទៀងទាត់និងគ្រប់ចំនួន ។ 
	             				</span>
	             			</span>
	             			<span  style="width: 100%; display: block;"><span style=" font-family:'Khmer OS Muol Light';font-weight:200;">ប្រការ៣ ៖  </span>
	             			អ្នកទិញត្រូវគោរពកាតព្វកិច្ចការបង់ប្រាក់តាមប្រការ៤នៃកិច្ចព្រមព្រៀងទិញនិងលក់ផ្ទះចុះថ្ងៃទី<?php echo date("d",strtotime($this->agreement['agreement_date']));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?>ឆ្នាំ<?php echo date("Y",strtotime($this->agreement['agreement_date']));?>។
	             			</span>
	             			<span  style="width: 100%; display: block;"><span style=" font-family:'Khmer OS Muol Light';font-weight:200;">*កំណត់សម្គាល់ :
	             			</span>
	             			</span>
	             			<span  style="width: 100%; display: block;">
	             			-ការធានាជួសជុលរយៈពេល៦ខែបន្ទាប់ពីទទួលផ្ទះគឺសំរាប់តែពាក់ព័ន្ធបញ្ហាបច្ចេកទេសទឹក ភ្លើង និងសំណង់សាងសង់
	             			</span>
	             			<span  style="width: 100%; display: block;">
							-អ្នកទិញយល់ព្រមទទួលផ្ទះដោយមានលេខកុងទ័រភ្លើងចុងក្រោយលេខ <strong><?php echo $this->agreement['electric_start'];?> </strong> កុងទ័រទឹកលេខ  <strong><?php echo $this->agreement['water_start'];?></strong>
	             			</span>
		             		<span style="width: 100%; display: block;line-height: 32px;">
			             		<span class="child">ដើម្បីជាសក្ខីភាពបញ្ជាក់ពីការព្រមព្រៀង របស់ភាគីទាំងពីរលើកិច្ចព្រមព្រៀង និងការប្រគល់ទទួលផ្ទះនេះ ភាគីទាំងពីរយល់ព្រមផ្តិតស្នាមមេដៃស្តាំ នៃកិច្ចព្រមព្រៀងនេះ ។</span>
		             		</span>
	             		</p>
	             	</td>
	             </tr>
	             <tr>
	             	<td colspan="3">
	             		<table align="center" width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';">
							   <tr style="font-size: 14px;">
							        <td class="reff" style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';font-weight:200;">អ្នកលក់</td>
							        <td>&nbsp;</td>
							        <td class="reff" style="width:20%;text-align:center; text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;"></td>
							        <td>&nbsp;</td>
							        <td class="reff" style="width:20%;text-align:center; text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;"></td>
							        <td>&nbsp;</td>
							        <td class="reff" style="width:20%;text-align:center; font-family:'Khmer OS Muol Light';font-weight:200;">អ្នកទិញ</td>
							   </tr>
							   <tr height="60px">
					             	<td>&nbsp;</td>
					           </tr>
					           <tr style="font-size: 14px;">
							        <td class="reff" style="width:20%;text-align:center;font-weight:200;"><?php echo $this->agreement['user_name'];?></td>
							        <td>&nbsp;</td>
							        <td class="reff" style="width:20%;text-align:center;text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;"></td>
							        <td>&nbsp;</td>
							        <td class="reff" style="width:20%;text-align:center;text-decoration:underline; font-family:'Khmer OS Muol Light';font-weight:200;"></td>
							        <td>&nbsp;</td>
							        <td class="reff" style="width:20%;text-align:center;font-weight:200;"><?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"/".$this->agreement['hname_kh']:"";?></td>
							   </tr>
						</table>
	             	</td>
	             </tr>
	             <tr>
	             	<td colspan="3">
	             		<span style="width:100%;display:block;line-height:32px;font-size:10px !important;" class="noted">
	             			<?php echo $this->agreement['contact_construction'];?>
	             		</span>
	             	</td>
	             </tr>
	            </table>
	           </div>
    	</td>
    </tr>
</table>
</div>