<meta charset="utf-8">
	<script>
		dojo.require("dijit.form.DateTextBox");
	</script>
<style>
	.hover:hover{background: #ccc;}
	img.view{height: 70px !important;}
</style>
<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<title><?php echo $tr->translate("RECEIPT");?></title>
 <style>
.five-startreceipt{
	background-image: url('<?php echo $this->baseUrl()."/images/fivestar-receipt.png";?>');background-size: 100%;
}
</style>
<div style="min-height:33cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div id="divPrint" style="width: 100%; padding-top: 30px;">
		<div id="divPrint1" style="width: 100%; height: 13cm ; padding: 0px; margin: 0px;">
			<?php 
			echo $this->officailreceipt;
			?>
		</div>
		<?php if($this->data['showreceipt']>1){?>
		<div id="divPrint2" style="width: 100%;height: 13cm ; padding: 0px; margin: 0px;">
			<div style="border:2px dashed <?php echo $this->data['border_receiptcolor'];?>; vertical-align: middle;margin:90px 0px 40px 0px"></div>
			<div id="printblog2"></div>
		</div>
		<?php }?>
	</div>
 </div>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<script>
require(["dojo/ready"], function(ready){
	 ready(function(){
		 loadingBlock();
		 getBranchInfo();
		 printSave();
		 setTimeout(function () {
			 <?php if($this->data['showreceipt']>1){?>
			 dojo.byId('printblog2').innerHTML = dojo.byId('divPrint1').innerHTML;
			 <?php }?>
	        HideloadingBlock();
	    }, 500);
		 
	 });
});	 
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->rs['branch_id'])?0:$this->rs['branch_id'];?>';
	if(branch_id==""){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img class="view" style="height:80px; max-width: 100%;" src="<?php echo $this->baseUrl()."/images/projects/"?>'+arr.logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;
		},
		error: function(e) {
		}
	});
}
function printSave(){
	symbal=" $";
	dojo.byId("lb_receipt").innerHTML = '<?php if ($this->rs['recieve_amount']==0){ echo "<span style='color:red'>VOID </span>"; }?><?php echo $this->rs['receipt_no'];?>';
	dojo.byId("lbl_project").innerHTML = '<?php echo $this->rs['project_name'];?>';
	dojo.byId("lb_customer").innerHTML = '<?php echo $this->rs['name_kh'];echo !empty($this->rs['hname_kh'])?" /".$this->rs['hname_kh']:"";?>';
	dojo.byId("lb_hourseno").innerHTML = '<?php echo $this->rs['land_address']; if(!empty($this->rs['street'])){echo ' , '.$this->rs['street']; } echo ' '.$this->rs['property_type'];?>';
	dojo.byId("lb_saleprice").innerHTML = '<?php echo "$ ".number_format($this->rs['selling_price'],2); //number_format($this->rs['price_sold'],2)." $";?>';
	dojo.byId("lbl_total_paid1").innerHTML ='<?php echo "$ ".number_format($this->rs['allpaid_before'],2);//number_format(($this->rs['price_sold']-(($this->rs['outstanding'])-($this->rs['recieve_amount']-$this->rs['penalize_amountpaid']-$this->rs['total_interest_permonthpaid']))),2)." $";?>';
	dojo.byId("lbl_balance").innerHTML ='<?php echo  "$ ".number_format($this->rs['selling_price']-$this->rs['allpaid_before'],2);//number_format(($this->rs['outstanding']-($this->rs['recieve_amount']-$this->rs['penalize_amountpaid']-$this->rs['total_interest_permonthpaid'])),2)." $";?>';
	dojo.byId("lb_noted").innerHTML ='<?php echo $this->rs['note'];?>';

	dojo.byId("lb_amount").innerHTML = '<?php echo  "$ ".number_format($this->rs['total_principal_permonth'],2);?>';
	dojo.byId("lbl_paidtimes").innerHTML = '<?php if($this->rs['field3']==1){ echo "កក់លើក ";} echo $this->rs['payment_times'];?>';
	dojo.byId("lb_interest").innerHTML ="<?php echo "$ ".number_format($this->rs['total_interest_permonthpaid'],2);?>";
	dojo.byId("lb_penalty").innerHTML ="<?php echo "$ ".number_format($this->rs['penalize_amountpaid'],2);?>";
	dojo.byId("lb_extrapayment").innerHTML ="<?php echo "$ ".number_format($this->rs['extra_payment'],2);?>";
	dojo.byId("lbl_totalpayment").innerHTML = '<?php echo  "$ ".number_format($this->rs['total_payment'],2);//total_principal_permonth?>';
	dojo.byId("lbl_total_receive").innerHTML = '<?php echo "$ ".number_format($this->rs['recieve_amount'],2);?>';
	dojo.byId("lb_buydate1").innerHTML = "<?php echo date("d-M-Y",strtotime($this->rs['date_payment']));?>";
	dojo.byId("lbl_paid_date1").innerHTML = "<?php echo date("d-M-Y",strtotime($this->rs['date_pay']));?>";
	dojo.byId("lbl_paymenttype").innerHTML = "<?php echo $this->rs['payment_method'];?>";
	dojo.byId("lbl_cheque").innerHTML = "<?php echo empty($this->rs['cheque'])?"N/A":$this->rs['cheque'];?>";

	dojo.byId("lbl_customer").innerHTML = '<?php echo $this->rs['name_kh'];echo (empty($this->rs['hname_kh'])?"":"/".$this->rs['hname_kh']); ?>';
	dojo.byId("lbl_usersale").innerHTML = "<?php echo $this->rs['by_user'];?>";

	a ='<?php echo ($this->rs['recieve_amount']) ?>';
	money_khmer=read_money_in_english(a);
	decimalmoney_khmer='<?php echo substr(number_format($this->rs['recieve_amount'],2),-2);?>';
	str_cent = 'cent';
	if(decimalmoney_khmer>0){string='and';}else{string="";str_cent='';}
	
	last_number='<?php echo substr(number_format($this->rs['recieve_amount'],2),-2);?>';
	
	if(last_number<=0){last_number='';}
	money_khmer = money_khmer+" "+string+" "+read_in_english_from_10_to_99(decimalmoney_khmer)+''+read_in_english_from_0_to_9(last_number)+' '+str_cent;
	dojo.byId('lable_chartotalreceipt').innerHTML=money_khmer;
	dojo.byId("lblpaid_date").innerHTML = "<?php echo date("d/m/y",strtotime($this->rs['date_pay']));?>";
	dojo.byId("lb_descriptionall").innerHTML = '<?php echo $this->rs['land_address']; if(!empty($this->rs['street'])){echo ' , '.$this->rs['street']; } echo ' '.$this->rs['property_type']; echo "PMT"; if($this->rs['field3']==1){ echo " កក់លើក ";} echo " ".$this->rs['payment_times']." ".date("d/m/y",strtotime($this->rs['date_payment']))." ".$this->rs['payment_method']; echo empty($this->rs['cheque'])?"":$this->rs['cheque'];?>';
	
}
</script>