<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<style>
.hover:hover{background: #ccc;}
img.view{height: 85px !important;}
</style>
<?php $tr = Application_Form_FrmLanguages::getCurrentlanguage();?>
<title><?php echo $tr->translate("RECEIPT");?></title>
 <div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div id="divPrint" style="width: 100%;">
			<?php 
				$dbGB = new Application_Model_DbTable_DbGlobal();
				$logo = $this->baseUrl()."/images/logo.jpg";
				$branch_title = $tr->translate("BRAND_TITLE");
			if ($this->rs['branch_id'] >0){
				$branch = $dbGB->getAllBranchInfoByID($this->rs['branch_id']);
				if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
					$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
				}
				$branch_title = $branch['project_name'];
			}
			$install_month = $this->data['install_by'];
		?>
			<style>
				.fontbig{
					font-size: 16px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}

				.label{ font-size: 22px;}
				.value{ font:16px 'Khmer OS Battambang';border: 1px solid #000; min-height: 29px; padding: 0 2px;width: 100%;margin-right:2px; display: block;
						line-height: 29px;
					    text-align: center;
						}
						
				.values{ border: 1px solid #000; height: 30px; padding: 0 10px;display: block;
						line-height: 30px;}
				.noted{white-space: pre-wrap;     
						word-wrap: break-word;      
						word-break: break-all;
						white-space: normal;
					    font:12px 'Khmer OS Battambang';
					    border: 1px solid #000;
                        line-height:20px;font-weight: normal !important;}
				.h{}
				.print tr td{
					padding:0px 2px 0px 2px; 
				}
			   .khmerbold{font:14px 'Khmer OS Battambang';}
			   .khmer{font:14px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;}
			</style>
			<?php for($i=0; $i<$this->data['showreceipt']; $i++){ ?>			
			<table width="100%" style="white-space: nowrap;font-size:14px; padding:0px;margin-top: -12px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img class="view" style="height:75px;" src="<?php echo $logo;?>">
								</td>					
								<td width="50%" style="font:18px 'Kh Muol';" valign="top" align="center"><u><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃទទួលប្រាក់</strong></u>
									<div style="line-height:10px;"><strong style="font-size: 18px;">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table style="width:100%;white-space: nowrap;font-size:16px;padding:-10px 10px 0px 5px; margin-top: -45px;margin-bottom:10px;font-family: 'Khmer OS Battambang';" class="print" cellspacing="3px"  cellpadding="0" >
				<tr height="1px">
					<td width="10%" ></td>
					<td width="30%" ></td>
					<td width="15%" ></td>
					<td width="17%" ></td>
					<td width="10%" ></td>
					<td width="18%" ></td>
				</tr>
				<tr style="white-space: nowrap;font-size: 14px;margin-top: -15px;" >
				    <td colspan="5"></td>
					<td align="right"><strong>
						<div style=" display: none;"><?php echo $this->rs['project_name'];?></div>
					<label><?php echo $this->rs['receipt_no'];?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
				    <td style="display: none;" >លេខកូដលក់</td>
				    <td style="display: none;" ><strong><label class="value"><?php echo $this->rs['sale_number'];?></label></strong></td>
				    <td  >គម្រោង</td>
				    <td  ><strong><label class="value"><?php echo $this->rs['project_name'];?></label></strong></td>
					<td  >&nbsp;&nbsp;ប្រាក់ដើមត្រូវបង់</td>
                    <td  ><strong><label  class="value"><?php echo  number_format($this->rs['total_principal_permonth'],2)." $";?></label></strong></td>
					<td>&nbsp;បង់លើកទី</td>
					<td><strong><label id="lbl_paid_date1" class="value"><?php echo $this->rs['payment_times'];?></label></strong></td>
				
				</tr>
				<tr style="white-space: nowrap;">
				    <td >ឈ្មោះ​អតិថិជន </td>
				    <td ><strong><label class="value"><?php echo $this->rs['name_kh'];echo !empty($this->rs['hname_kh'])?" /".$this->rs['hname_kh']:"";?></label></strong></td>
					<td  >&nbsp;&nbsp; ប្រាក់ការ</td>
                    <td  ><strong><label  class="value"><?php echo  number_format($this->rs['total_interest_permonthpaid'],2)." $";?></label></strong></td>
					<td>&nbsp; ប្រាក់ពិន័យ</td>
					<td><strong><label id="lbl_paid_date1" class="value"><?php echo number_format($this->rs['penalize_amountpaid'],2);?></label></strong></td>
                </tr>
				<tr style="white-space: nowrap;">
					<td ><?php echo $tr->translate("PROPERTY_CODE");?></td>
                    <td><strong><label class="value"><?php echo $this->rs['land_address']; if(!empty($this->rs['street'])){echo ' , '.$this->rs['street']; } echo ' '.$this->rs['property_type'];?></label></strong></td>
				   <td >&nbsp;&nbsp;ប្រាក់បង់បន្ថែម</td>
					<td colspan="3"><strong><label  class="value"><?php echo number_format($this->rs['extra_payment'],2)." $";?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td  width="10%"><?php echo $tr->translate("HOUSE_PRICE");?></td>
				    <td width="40%"><strong><label id="lblpropertyprice1" class="value"><?php echo  number_format($this->rs['price_sold'],2)." $";?></label></strong></td>
					<td >&nbsp;&nbsp;ប្រាក់ត្រូវបង់</td>
                    <td colspan="3"><strong><label id="lbl_total_payment1" class="value"><?php echo  number_format($this->rs['total_payment'],2)." $";//total_principal_permonth?></label></strong></td>
				</tr>
				<tr>
					<td >ប្រាក់បានបង់សរុប</td>
					<td >
						<table width="100%" cellpadding="0" cellspacing="0">
							<tr>
								<td width="33.5%" style="white-space: nowrap;"><strong><label style="margin-left: -4px;" id="lbl_total_paid1" class="value"><?php echo  number_format(($this->rs['price_sold']-(($this->rs['outstanding'])-($this->rs['recieve_amount']-$this->rs['penalize_amountpaid']-$this->rs['total_interest_permonthpaid']))),2)." $";?></label></strong></td>
								<td width="33%" style="white-space: nowrap;">ប្រាក់នៅសល់</td>
								<td width="33.5%"><strong style="white-space: nowrap;"><label style="white-space: nowrap;margin-right: -4px;" class="value"><?php echo  number_format(($this->rs['outstanding']-($this->rs['recieve_amount']-$this->rs['penalize_amountpaid']-$this->rs['total_interest_permonthpaid'])),2)." $";?></label></strong></td>
							</tr>
						</table>
					</td>
					<td>&nbsp;&nbsp;ប្រាក់ទទួលបាន</td>
				    <td colspan="3"><strong><label  class="value" style="font-weight:700; font-family: Arial,Helvetica,sans-serif;"><?php echo number_format($this->rs['recieve_amount'],2)." $";?></label></strong></td>
				</tr>
				<tr style="">
					<td rowspan="2">សម្គាល់</td>
				    <td rowspan="2" class="noted" valign="top"><?php echo $this->rs['note'];?></td>
					<td >&nbsp;&nbsp;ថ្ងៃត្រូវបង់</td>
				    <td><strong><label id="lb_buydate1" class="value"><?php echo date("d-M-Y",strtotime($this->rs['date_payment']));?></label></strong></td>
					<td>&nbsp;ថ្ងៃទទួល</td>
					<td><strong><label id="lbl_paid_date1" class="value"><?php echo date("d-M-Y",strtotime($this->rs['date_pay']));?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td>&nbsp;បង់ជា</td>
					<td><strong><label id="lbl_paid_date1" class="value"><?php echo $this->rs['payment_method'];?></label></strong></td>
					<td>&nbsp;&nbsp;លេខ</td>
					<td><strong><label id="lb_cheque1" class="value"><?php echo $this->rs['cheque'];?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="35px;">
					<td colspan="6" valign="top">
						<table width="100%" border="0" style="font-size:14px;line-height: 18px;">
							<tr>
								<td width="30%">&nbsp;
								</td>
								<td align="center" width="40%">
									<?php echo $this->data['customer_sign'];?>
								</td>
								<td align="center" width="30%">
									<?php echo $this->data['teller_sign'];?>
								</td>
							</tr>
							<tr height="60px">
								<td colspan="3">&nbsp;
								</td>
							</tr>
							<tr>
								<td colspan="3">&nbsp;
								</td>
							</tr>
							<tr>
								<td width="30%">&nbsp;
								</td>
								<td align="center" width="40%">
									<strong><label id="lbl_customer1"><?php echo $this->rs['name_kh'];echo (empty($this->rs['hname_kh'])?"":"/".$this->rs['hname_kh']); ?></label></strong>
								</td>
								<td align="center" width="30%">
									<strong>
										<?php 
											echo $this->rs['by_user'];
										?>
									</strong>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<tr style="line-height: 20px;font-size: 11px;">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px; margin-top: -5px;">សំគាល់ ៖</span>
					</td>
					<td colspan="5">
						<span style="font-size: 11px;margin-top: -5px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 11px;margin-top: -5px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 10px;">
					<td colspan="6" >
						<table width="100%" style="font-family: 'Khmer OS Battambang'; font-size:10px;line-height: 10px;margin-top: -7px; margin-bottom:10px;white-space:nowrap;"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang';"><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr style="white-space:nowrap;">
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<?php if($i==0 AND $this->data['showreceipt']>1){?>
				<tr height="55px">
					<td colspan="6" style="border-top:2px dashed #000;" ></td>
				</tr>
				<?php }?>
			</table>
			<?php } ?>
	</div>
</div>