<?php $rs = $this->rsincome;?>
<div style=" width:29cm;min-height:23cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm;background: #fff;">
<div id="divPrint" style="width: 21cm !important; padding: 0px; margin: 0px auto;">
			<style>
				.fontbig{
					font-size: 15px;	
				}
				.fonttel{
					font-size: 18px;	
				}
				.pleft{
					width: 110px;	
				}

				.label{ font-size: 22px;}
				.value{ font: 14px 'Khmer OS Battambang';border: 1px solid #000; height: 27px; width: 100%;margin-right:5px; display: block;
						line-height: 25px;
					    text-align: center;
						}
				.print tr td{
					padding:2px 2px; 
				}
			   .khmerbold{font:14px 'Khmer OS Battambang';}
			   .khmer{font:12px 'Khmer OS Battambang';}
			   .one{white-space:nowrap;}
			   .h{ margin-top: -10px;/*margin-left:4px;*/}
			</style>	
			<?php for($i=1;$i<=2;$i++){?>
			<table width="100%" style="white-space: nowrap;font-size:14px;margin-top: 0px;" class="print" cellspacing="0"  cellpadding="0" >
				<tr>
					<td colspan="6">
						<table width="100%" style="font-family:'Khmer MEF2';white-space:nowrap;">
							<tr>
								<td width="25%">
									<img style="width:100%;height:61px;" src="<?php echo $this->baseUrl().'/images/bppt_logo.png'?>">
								</td>					
								<td width="50%" style="font:bold 18px 'Kh Muol';" valign="top" align="center"><u><b><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';">បង្កាន់ដៃទទួលប្រាក់</strong></b></u>
									<div style="line-height:10px;"><strong style="font-size: 18px;font-weight:bold">OFFICIAL RECEIPT</strong></div>
								</td>
								<td width="25%">
								</td>
							</tr>
						</table>
					</td>
				</tr>
			</table>
			<table width="100%" style="white-space: nowrap;font-size:14px;margin-top: -5px;" class="print" cellspacing="2px"  cellpadding="0">
				<tr>
					<td width="10%" ></td>
					<td width="30%" ></td>
					<td width="15%" ></td>
					<td width="17%" ></td>
					<td width="10%" ></td>
					<td width="18%" ></td>
				</tr>
				
				<tr style="white-space: nowrap;">
				
					<td class="one khmerbold">គម្រោង</td>
                    <td><strong><label class="value"><?php echo $rs['branch_name'];?></label></strong></td>
				    <td class="one khmerbold">&nbsp;&nbsp;&nbsp;វិក័យប័ត្រលេខ</td>
                    <td colspan="3"><strong><label class="value"><?php echo $rs['invoice'];?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold" width="10%">អតិថិជន</td>
				    <td width="40%"><strong><label class="value"><?php echo $rs['client_name'].' ('.$rs['house_name'].')';?></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;&nbsp;ប្រភេទចំនូល</td>
				    <td colspan="3"><strong><label class="value"><?php echo $rs['category_name'];?></label></strong></td>
				</tr>

				<tr>
					<td class="one khmerbold">ពណ៌នាចំនូល</td>
					<td ><strong><label class="value"><?php echo $rs['title'];?></label></strong></td>
					<td class="one khmerbold">&nbsp;&nbsp;ចំនូលសរុប</td>
					<td colspan="3"><strong><label class="value">$ <?php echo number_format($rs['total_amount'],2);?></label></strong></td>
				</tr>
				<tr style="white-space: nowrap;">
					<td class="one khmerbold">សែក</td>
				    <td ><strong style="white-space: nowrap;"><label style="white-space: nowrap;" class="value"><?php echo $rs['cheque'];?></label></strong></td>
					
					<td class="one khmerbold">&nbsp;&nbsp;ថ្ងៃទទួល</td>
				    <td colspan="3"><strong><label class="value"><?php echo date("d/m/Y",strtotime($rs['date']));?></label></strong></td>
				</tr>
				
				<tr style="white-space:normal;">
					<td class="one khmerbold">សម្គាល់</td>
				    <td colspan="1"><strong><label style="height:max-content;word-wrap: break-word;max-width:300px;text-align: center;" class="value">&nbsp;<?php echo $rs['description'];?></label></strong></td>
				</tr>
				
				<tr style="white-space: nowrap;">
				    <td class="khmerbold" style="line-height: 14px;"colspan="4"  align="center" >&nbsp;&nbsp;<strong style=" font-family: Arial Black;font-family:'Khmer MEF2';"><?php echo $this->data['customer_sign'];?></strong></td>
				    <td colspan="2" class="khmerbold" style="line-height: 14px;" align="center" ><strong style=" font-family: Arial Black;font-family:'Khmer MEF2';"><?php echo $this->data['teller_sign'];?></strong></td>
				</tr>
				<tr style="white-space: nowrap;" height="60px;">
					<td class="one khmerbold" colspan="4" align="center" valign="bottom">
						<h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
							<lable id="lb_customer_name"><?php echo $rs['client_name'];?></lable>
						</h4>
					</td>
				    <td class="one khmerbold" colspan="2" align="center" valign="bottom">&nbsp;
				  	  <h4 style="padding-right: 5px ! important;margin-bottom: -10px  !important;">
		              <?php echo $rs['user_name'];?></h4>  
					</td>
				</tr>
				
				<tr style="line-height: 15px;font-size: 12px;">
					<td colspan="6" valign="top" >
						
					</td>
				</tr>
				<tr style="line-height: 20px;font-size: 11px;font-family:'Khmer OS Battambang'">
					<td valign="top" >
						<span style="text-decoration:underline;font-size: 14px;">សំគាល់ ៖</span>
					</td>
					<td colspan="5">
						<span style="font-size: 12px;"><?php echo $this->data['comment'];?></span><br />
						<span style="white-space: pre-line;font-size: 12px;"><?php echo $this->data['comment1'];?></span><br />
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 12px;">
					<td colspan="6" style="border-top: 2px solid rgba(255, 235, 59, 0.88)">
						
					</td>
				</tr>
				<tr style="line-height: 15px;font-size: 12px;">
					<td colspan="6" >
						<table width="100%" style="font-size:11px;line-height: 12px;margin-top: -5px;font-family: 'Khmer OS Battambang';"> 
							<tr>
								<td width="22%">
									<img style="width:70%;height: 25px;" src="<?php echo $this->baseUrl().'/images/bppt_letter.png'?>">
								</td>
								<td width="40%">
									<span style=""><?php echo $this->data['website'];?></span>
								</td>
								<td width="40%" align="right">
									<span style="font-family: 'Khmer OS Battambang';"><?php echo $this->data['email_client'];?></span>
								</td>
							</tr>
							<tr>
								<td colspan="2">
									<?php echo $this->data['footer_branch'];?>
								</td>
								<td width="40%" align="right">
									<span style=""><?php echo $this->data['tel-client'];?></span>
								</td>
							</tr>
						</table>
					</td>
				</tr>
				<?php if($i==1){?>
				<tr style="">
					<td colspan="6" style="border-bottom:2px dashed #000;" >
						&nbsp;<div style="margin-top: 40px;"></div>
					</td>
				</tr>
				<?php }?>
			</table>
			<?php }?>
		</div>
		<div style="clear: both;"></div>
	</div>