<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("REPORT_LOAN_PAYOFF"));
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->list_end_date['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->list_end_date['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('REPORT_LOAN_PAYOFF');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement("adv_search");?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('branch_id');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<input id="land_id" />
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('client_name');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('start_date');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('end_date');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
				</div>
			</div>
		</div>
	</form>
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<style>
			.style{
				line-height: 20px;font-size: 12px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
				text-align: center;
			}
			.style1:hover{ background: #ccc;}
			table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
			 table { page-break-inside:auto }
			  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			.hide{visibility: hidden;}
				@media print {
				  div.divFooter {
				    position: fixed;
				    top: 0;
				  	width: 100%;
				  	height: 100px;
				  	bottom:0px;
					margin:0;
				  }
					.hide{visibility: visible; height: 110px;}
				}
				th{text-align: center;}
				table.content-data{
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:13px;
					font-family: 'Times New Roman','Khmer OS Battambang';
					white-space: nowrap;
				}
				table.content-data thead tr.style {
				   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #c1d0f3;
				}
				table.tb-footer{
					border-collapse:collapse;
					border:1px solid #000; 
					font-family: 'Times New Roman','Khmer OS Battambang';
					font-size:11px;
				}
				table.tb-footer tr{
				 line-height: 14px;  padding:2px 0px; height: 25px;
				}
				table tr td{
					padding:0 2px;
				}
			</style>
			<table width="100%">
				<tr>
			    	<td align="center">
			    		<div class="divFooter">
			        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;">
			            	<tr>
			                	<td width="30%"><img src="<?php echo $logo;?>" height="85px" style="max-width: 100%;"></td>
			                	<td width="40%" valign="top">
			                	   <ul>
			                			<li style="white-space:nowrap;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $branch_title;?></li>
			                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_LOAN_PAYOFF");?></li>
			                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){ echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
			                		</ul>
			                	</td>
			                    <td width="30%"></td>
			                </tr> 
			            </table>
			            </div>
			        </td>
			    </tr>
			    <tr>
			    	<td>
			            <table id="exportExcel" class="content-data" width="100%" border="1" cellspacing="0">
			                 <thead>
			                 	<tr class="hide" style="border:1px solid #000;">
						             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						        </tr>
				                <tr class="style" align="center" >
				                    <td rowspan="2"><?php echo $tr->translate("NUM");?></td>
				                    <td rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></td>
				                    <td rowspan="2"><?php echo $tr->translate("PROPERTY_CODE");?></td> 
				                    <td rowspan="2"><?php echo $tr->translate("STREET");?></td> 
				                    <td rowspan="2" ><?php echo $tr->translate("SOLD_PRICE");?></td>
				                    <td rowspan="2" ><?php echo $tr->translate("CUSTOMER_NAME");?></td>
				                    <td rowspan="2"><?php echo $tr->translate("RELEASED_DATE");?></td>
				                    <td rowspan="2"><?php echo $tr->translate("LIFE_LOAN");?></td>
				                    <td rowspan="2" ><?php echo $tr->translate("RECEIPT_NO");?></td>
				                    <td colspan="4" ><?php echo $tr->translate("TOTAL_PAYMENTED");?></td>
				                    <td rowspan="2"><?php echo $tr->translate("PAID");?></td>
				                    <td rowspan="2"><?php echo $tr->translate("DAY_PAYMENT");?></td>
				                    <td rowspan="2"><?php echo $tr->translate("BY_USER");?></td>
				                </tr>
				                <tr class="style"  >
				                	<td><?php echo $tr->translate("PRINCIPAL");?></td>                    
				                    <td><?php echo $tr->translate("INTEREST");?></td>
				                    <td><?php echo $tr->translate("PENALIZE AMOUNT");?></td>  
				                    <td><?php echo $tr->translate("EXTRA_PAYMENT");?></td>                    
				                </tr>
			                </thead>
			                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$amt_r6 = 0;$amt_r7 = 0;
			                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$amt_d6 = 0;$amt_d7 = 0;
			                	  $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$amn_b6 = 0;$amn_b7 = 0;
			                ?>
			                <?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
			                <?php 
								$amt_d1 = $amt_d1+$rs['total_principal_permonthpaid'];
								$amt_d2 = $amt_d2+$rs['total_interest_permonthpaid'];
								$amt_d3 = $amt_d3+$rs['penalize_amountpaid'];
								$amt_d5 = $amt_d5+$rs['extra_payment'];
								$amt_d4 = $amt_d4+$rs['total_payment'];
			               ?>
			                <tr class="style style1" >
			               		<td align="center"><?php echo $key+1; ?></td>
			               		<td ><?php echo $rs["branch_name"];?></td>
			               		<td ><?php echo $rs["land_address"];?></td>
			               		<td ><?php echo $rs["street"];?></td>
			               		<td ><?php echo $rs["price_sold"];?></td>
			               		<td ><?php echo $rs["customer_name"];?></td>
			               		<td align="center"><?php echo date("d-m-Y",strtotime($rs["buy_date"]));?></td>
			               		<td align="center"><?php echo date("d-m-Y",strtotime($rs["end_line"]));?></td>
			               		<td align="center"><?php echo $rs["receipt_no"];?></td>
			               		<td align="right"><?php echo number_format( $rs["total_principal_permonthpaid"],2);?></td>               		
			               		<td align="right"><?php echo number_format($rs["total_interest_permonthpaid"],2);?></td>
			               		<td align="right"><?php echo number_format($rs["penalize_amountpaid"],2);?></td>               		
			               		<td align="right"><?php echo number_format($rs["extra_payment"],2);?></td>               		
			               		<td align="right"><?php echo number_format($rs["total_payment"],2);?></td>
			               		<td align="center"><?php echo date("d-m-Y",strtotime($rs["date_payment"]));?></td>
			               		<td align="center"><?php echo $rs['user_name'];?></td>
			                </tr>
			                <?php }?>
			                <tr style="font-weight:bold; text-align: center;background:#87acff;">
								<td colspan="9" align="right"></td>
								<td align="right"><?php echo number_format($amt_d1,2);?></td>
								<td align="right"><?php echo number_format($amt_d2,2);?></td>
								<td align="right"><?php echo number_format($amt_d3,2);?></td>
								<td align="right"><?php echo number_format($amt_d5,2);?></td>
								<td align="right"><?php echo number_format($amt_d1+$amt_d2+$amt_d3+$amt_d5,2);?></td>
								<td colspan="3">
								</td>
							</tr>
			            </table>
			             
			              <br />
			             <?php echo $this->footerReport;?>
			    	</td>
			    </tr>
			</table>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
		}, "land_id");
});
land_id = '<?php echo $this->list_end_date['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
} 
</script>