<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("PAY_OFF"));
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->list_end_date['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->list_end_date['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<form method="post">
		<script>
			dojo.require("dijit.form.DateTextBox");
		</script>
		<table style="font-family: 'Khmer OS Content';margin: 0 auto;" >
			   <tr>
		   			<td><?php echo $frm->getElement("adv_search");?></td>
		   			<td><?php echo $frm->getElement('branch_id');?></td>
		   			<td><input id="land_id" /></td>
		   			<td><?php echo $frm->getElement('client_name');?></td>
		   			<td><?php echo $frm->getElement('start_date');?></td>
		   			<td><?php echo $frm->getElement('end_date');?></td>
		   			<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
		   		</tr>
		</table>
	</form>
	<div style="min-height:22cm; margin:0 auto;">
		<div id="divPrint">
			<style>
			.style{
				line-height: 20px;font-size: 12px !important;
				font-family: 'Khmer OS Battambang';
				text-align: center;
			}
			.style1:hover{ background: #ccc;}
			table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
			 table { page-break-inside:auto }
			  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			.hide{visibility: hidden;}
				@media print {
				  div.divFooter {
				    position: fixed;
				    top: 0;
				  	width: 100%;
				  	height: 100px;
				  	bottom:0px;
					margin:0;
				  }
					.hide{visibility: visible; height: 110px;}
				}
				th{text-align: center;}
				table.content-data{
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:13px;
					font-family: 'Times New Roman','Khmer OS Battambang';
					white-space: nowrap;
				}
				table.content-data thead tr.style {
				   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #c1d0f3;
				}
				table.tb-footer{
					border-collapse:collapse;
					border:1px solid #000; 
					font-family: 'Times New Roman','Khmer OS Battambang';
					font-size:11px;
				}
				table.tb-footer tr{
				 line-height: 14px;  padding:2px 0px; height: 25px;
				}
			</style>
			<table width="100%">
				<tr>
			    	<td align="center">
			    		<div class="divFooter">
			        	<table width="100%" style="font-family: 'Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
			            	<tr>
			                	<td width="20%"><img src="<?php echo $logo;?>" height="85px"></td>
			                	<td width="60%" valign="top">
			                	   <ul>
			                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $branch_title;?></li>
			                			<li style="text-align:center; font-size:14px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_LOAN_PAYOFF");?></li>
			                			<li style="text-align:center; font-size:13px;"><?php if(!empty($this->list_end_date['start_date'])){ echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
			                		</ul>
			                	</td>
			                    <td width="20%"></td>
			                </tr> 
			            </table>
			            </div>
			        </td>
			    </tr>
			    <tr>
			    	<td>
			            <table id="exportExcel" class="content-data" width="100%" border="1" cellspacing="0">
			                 <thead>
			                 	<tr class="hide" style="border:1px solid #000;">
						             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						        </tr>
				                <tr class="style" align="center" >
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PROPERTY_CODE");?>&nbsp;</td> 
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("STREET");?>&nbsp;</td> 
				                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("SOLD_PRICE");?>&nbsp;</td>
				                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("RELEASED_DATE");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("LIFE_LOAN");?>&nbsp;</td>
				                    <td rowspan="2" >&nbsp;<?php echo $tr->translate("RECEIPT_NO");?>&nbsp;</td>
				                    <td colspan="4" >&nbsp;<?php echo $tr->translate("TOTAL_PAYMENTED");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("PAID");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("DAY_PAYMENT");?>&nbsp;</td>
				                    <td rowspan="2">&nbsp;<?php echo $tr->translate("BY_USER");?>&nbsp;</td>
				                </tr>
				                <tr class="style"  >
				                	<td>&nbsp;<?php echo $tr->translate("PRINCIPAL");?>&nbsp;</td>                    
				                    <td>&nbsp;<?php echo $tr->translate("INTEREST");?>&nbsp;</td>
				                    <td>&nbsp;<?php echo $tr->translate("PENALIZE AMOUNT");?>&nbsp;</td>  
				                    <td>&nbsp;<?php echo $tr->translate("EXTRA_PAYMENT");?>&nbsp;</td>                    
				                </tr>
			                </thead>
			                <?php $amt_r1 = 0;$amt_r2 = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$amt_r6 = 0;$amt_r7 = 0;
			                	  $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$amt_d6 = 0;$amt_d7 = 0;
			                	  $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$amn_b6 = 0;$amn_b7 = 0;
			                ?>
			                <?php if(!empty($this->LoanCollectionco_list)) foreach ($this->LoanCollectionco_list as $key => $rs){ ?>
			                <?php 
								$amt_d1 = $amt_d1+$rs['total_principal_permonthpaid'];
								$amt_d2 = $amt_d2+$rs['total_interest_permonthpaid'];
								$amt_d3 = $amt_d3+$rs['penalize_amountpaid'];
								$amt_d5 = $amt_d5+$rs['extra_payment'];
								$amt_d4 = $amt_d4+$rs['total_payment'];
			               ?>
			                <tr class="style style1" >
			               		<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
			               		<td >&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
			               		<td >&nbsp;<?php echo $rs["land_address"];?>&nbsp;</td>
			               		<td >&nbsp;<?php echo $rs["street"];?>&nbsp;</td>
			               		<td >&nbsp;<?php echo $rs["price_sold"];?>&nbsp;</td>
			               		<td >&nbsp;<?php echo $rs["customer_name"];?>&nbsp;</td>
			               		<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["buy_date"]));?>&nbsp;</td>
			               		<td align="center">&nbsp;<?php echo date("d-m-Y",strtotime($rs["end_line"]));?>&nbsp;</td>
			               		<td align="center">&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
			               		<td align="right">&nbsp;<?php echo number_format( $rs["total_principal_permonthpaid"],2);?>&nbsp;</td>               		
			               		<td align="right">&nbsp;<?php echo number_format($rs["total_interest_permonthpaid"],2);?>&nbsp;</td>
			               		<td align="right">&nbsp;<?php echo number_format($rs["penalize_amountpaid"],2);?>&nbsp;</td>               		
			               		<td align="right">&nbsp;<?php echo number_format($rs["extra_payment"],2);?>&nbsp;</td>               		
			               		<td align="right">&nbsp;<?php echo number_format($rs["total_payment"],2);?>&nbsp;</td>
			               		<td align="center">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_payment"]));?>&nbsp;</td>
			               		<td align="center">&nbsp;<?php echo $rs['user_name'];?>&nbsp;</td>
			                </tr>
			                <?php }?>
			            </table>
			            <br /><br />
			             <table class="tb-footer" width="100%"  border="1"​ class="tb-footer" cellspacing="0">
			                 <tr bgcolor="#c1d0f3" align="center">
			                    <td><?php echo $tr->translate("TOTAL_PRINCEPLE");?></td>
			                    <td><?php echo $tr->translate("EXTRA_PAYMENT");?></td>                    
			                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
			                    <td><?php echo $tr->translate("TOTAL_PENELIZE");?></td>
			                    <td><?php echo $tr->translate("TOTAL_PAYMENTED");?></td>
			                </tr>
			                 <tr>
			                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
			                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
			                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
			                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
			                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1+$amt_d2+$amt_d3+$amt_d5,2);?>&nbsp;</td>
			                 </tr>
			              </table>
			               <br />
			               <table align="center" width="100%">
							   <tr>
							        <td style="width:20%;font-size:14px;text-align:center;  font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
							        <td></td>
							        <td style="width:20%;font-size:14px;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
							        <td></td>
							        <td style="width:20%;font-size:14px;text-align:center;font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
							   </tr>
						</table>
			    	</td>
			    </tr>
			</table>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
		}, "land_id");
});
land_id = '<?php echo $this->list_end_date['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
} 
</script>