<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលោះប្រាក់ដើម",4=>"បង់ផ្តាច់");
	$url_receipt = $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt'));
	$url_receiptupdate = $this->url(array('module'=>'report','controller'=>'loan','action'=>'updatereceipt'));
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->rssearch['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>
<title><?php echo $tr->translate("RPT_CHANGEPROPERTY");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div class="reportblog">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_CHANGEPROPERTY');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<form method="post">
			<div class="card-box">
		    	<div class="form-group"> 
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('client_name');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('status');?>
					</div>
				</div>
				<div class="form-group"> 
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
					</div>
				</div>
			</div>
		</form>
		<div style="width:100%; margin:0 auto;">
		<div style="min-height:22cm; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
			</style>
			<div id="divPrint">
			<style type="text/css">
				.style{
					line-height: 20px;font-size: 11px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				.hideblog{display: none;}
				.hiddenblog{display: block !important;}
				.style1:hover{ background: #ccc; }
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				  margin-top: 100px;
				}
				.hide{visibility: hidden;}
				@media print {
				  div.divFooter {
				    position: fixed;
				    top: 0;
				  	width: 100%;
				  	height: 100px;
				  	bottom:0px;
					margin:0;
				  }
				  .hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
				}
					table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:13px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
							width: 100%;
						}
						table.content-data thead tr.style {
						   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
							background: #c1d0f3;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
			</style>
				<table width="100%">
					<tr>
				    	<td align="center" valign="top">
				        	<div class="divFooter">
					        	<?php echo $this->headerReport;?>
				            </div>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				            <table width="100%" class="content-data" border="1"  cellspacing="0">
					                <thead>
						                <tr class="hide" style="border:1px solid #000;">
						                	<td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						                </tr>
						                <tr bgcolor="#c1d0f3" class="style" align="center" >
						                    <td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?></td>
						                   	<td scope="col" colspan="6"><?php echo $tr->translate("FROM_HOUSE");?></td>
						                    <td scope="col" colspan="7"><?php echo $tr->translate("TO_HOUSE");?></td>
						                    <td scope="col" rowspan="2"><?php echo $tr->translate("CHANGE_DATE");?></td>
						                    <td scope="col" rowspan="2"><?php echo $tr->translate("BY_USER");?></td>
						                </tr>
						                <tr class="style" align="center">
						                	<td scope="col" ><?php echo $tr->translate("BRANCH_NAME");?></td>
						                    <td scope="col"><?php echo $tr->translate("CUSTOMER_NAME");?></td>                  
						                    <td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
						                    <td scope="col"><?php echo $tr->translate("SOLD_PRICE");?></td>
						                    <td scope="col"><?php echo $tr->translate("PAID");?></td>  
						                    <td	scope="col" ><?php echo $tr->translate("BALANCE");?></td>   
						                    <td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td> 
						                    <td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
						                    <td scope="col"><?php echo $tr->translate("PRICE_BEFORE");?></td>
						                    <td scope="col"><?php echo $tr->translate("DISCOUNT_PERCENT");?></td>
						                    <td scope="col"><?php echo $tr->translate("Discount");?></td>
						                    <td scope="col"><?php echo $tr->translate("SOLD_PRICE");?></td>
						                    <td scope="col"><?php echo $tr->translate("BALANCE");?></td>
						                </tr>
						            </thead>
				                <?php 
				                $i=1;
				                $is_set =0; if(!empty($this->row)) foreach ($this->row as $index => $rs){ ?>
				                <tr class="style style1" style="white-space:nowrap; ">
				               		<td data-label="<?php echo $tr->translate("NUM");?>" style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>">&nbsp;<?php echo $rs["from_branch"];?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("CUSTOMER_NAME");?>">&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>">&nbsp;<?php echo $rs["from_property"];?>&nbsp;</td>                 		
				               		<td data-label="<?php echo $tr->translate("SOLD_PRICE");?>" align="center">&nbsp;<?php echo number_format($rs["soldprice_before"],2);?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("PAID");?>" align="right">&nbsp;<?php echo number_format($rs["paid_before"],2);?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("BALANCE");?>" align="right" >&nbsp;<?php echo number_format($rs['balance_before'],2);?>&nbsp;</td>               		
				               		<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>" align="right" >&nbsp;<?php echo $rs['to_branch'];?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>">&nbsp;<?php echo $rs['to_propertype'];?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("PRICE_BEFORE");?>" style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["house_priceafter"],2);?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("DISCOUNT_PERCENT");?>" style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["discount_percentafter"],2);?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("Discount");?>" style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["discount_amountafter"],2);?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("SOLD_PRICE");?>" style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["sold_priceafter"],2);?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("BALANCE");?>" style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["balance_after"],2);?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("CHANGE_DATE");?>" align="center" style="white-space:nowrap; ">&nbsp;<?php echo date("d-m-Y",strtotime($rs["change_date"]));?>&nbsp;</td>
				               		<td data-label="<?php echo $tr->translate("BY_USER");?>" class="" style="font:11px 'Khmer OS Battambang',Arial;text-align: center;"><?php echo $rs['user_name']?></td>
				                </tr>
				                <?php }?>
				            </table>
				              <br />
				               <?php echo $this->footerReport;?>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
	require(["dojo/ready"], function(ready){
		ready(function(){
			 getBranchInfo();
			 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
			 document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("RPT_CHANGEPROPERTY");?>';
			 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
		
		});
		
	});
	
	function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>