<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("REPORT_EXPECT_INCOME"));
	$frm = $this->frm_search;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPORT_EXPECT_INCOME');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>	
	<form method="post">
		<div class="card-box">
			<div class="form-group">
	            <div class="col-md-2 col-sm-2 col-xs-12">
	            	<?php echo $frm->getElement("adv_search");?>
	            </div>
	            <div class="col-md-2 col-sm-2 col-xs-12">
	            	<?php echo $frm->getElement("branch_id");?>
	            </div>
	            <div class="col-md-2 col-sm-2 col-xs-12">
	            	<?php echo $frm->getElement("client_name");?>
	            </div>
	            <div class="col-md-2 col-sm-2 col-xs-12">
	            	<?php echo $frm->getElement('schedule_opt');?>
	            </div>
	            <div class="col-md-2 col-sm-2 col-xs-12">
	            	<select class="fullside" id="stepoption" name="stepoption" dojoType="dijit.form.FilteringSelect">
						<option value="-1" <?php if ($this->search['stepoption']==-1){ echo 'selected=selected';}?>><?php  echo $tr->translate("ALL");?></option>
						<option value="0" <?php if ($this->search['stepoption']==0){ echo 'selected=selected';}?>><?php  echo $tr->translate("DATE_PAYMENT");?></option>
						<?php if (!empty($this->stepoption)) foreach ($this->stepoption as $rs){?>
						<option value="<?php echo $rs['key_code']?>" <?php if ($this->search['stepoption']==$rs['key_code']){ echo 'selected=selected';}?>><?php echo $rs['name_en']?></option>
						<?php }?>
					</select>
	            </div>
	            <div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $frm->getElement('co_id');?>
				</div>
	        </div>
	        <div class="form-group">
	            <div class="col-md-2 col-sm-2 col-xs-12">
	            	<select class="fullside" id="is_completed" name="is_completed" dojoType="dijit.form.FilteringSelect">
						<option value="-1" <?php if ($this->search['is_completed']==-1){ echo 'selected=selected';}?>><?php  echo $tr->translate("ALL");?></option>
						<option value="0" <?php if ($this->search['is_completed']==0){ echo 'selected=selected';}?>><?php  echo $tr->translate("UNPAID");?></option>
						<option value="1" <?php if ($this->search['is_completed']==1){ echo 'selected=selected';}?>><?php  echo $tr->translate("COMPLETED");?></option>
					</select>
	            </div>
	            <div class="col-md-2 col-sm-2 col-xs-12">
	            	<?php echo $frm->getElement('start_date');?>
	            </div>
	            <div class="col-md-2 col-sm-2 col-xs-12">
	            	<?php echo $frm->getElement('end_date');?>
	            </div>
	            <div class="col-md-2 col-sm-2 col-xs-12">
	            	<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	            </div>
	        </div>
	    </div>
	</form>
	<div style="min-height:28cm; margin:0 auto;">
		<div id="divPrint">
			<style type="text/css">
				.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px;}
				th{padding: 5px;}
				table { page-break-inside:auto }
				  tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
				.hide{visibility: hidden;}
				@media print {
				  div.divFooter {
				    position: fixed;
				    top: 0;
				  	width: 100%;
				  	height: 100px;
				  	bottom:0px;
					margin:0;
				  }
				.hide{visibility: visible; height: 110px;}
				}
				.hover:hover{background:#ccc;}
				table.content-data{
					border-collapse:collapse;
					border:1px solid #000; 
					font-size:13px;
					font-family: 'Times New Roman','Khmer OS Battambang';
					white-space: nowrap;
					line-height: 22px;
					width: 100%;
				}
				table.content-data thead tr.style {
				   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
					background: #c1d0f3;
				}
				table.tb-footer{
					border-collapse:collapse;
					border:1px solid #000; 
					font-family: 'Times New Roman','Khmer OS Battambang';
					font-size:11px;
				}
				table.tb-footer tr{
				 line-height: 14px;  padding:2px 0px; height: 25px;
				}
			</style>
			<table width="100%">
				<tr>
			    	<td align="center">
			        	<div class="divFooter">
				        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;">
				            	<tr>
				                	<td width="30%"><img src="<?php echo $logo;?>" style="height:80px;max-width:100%;"></td>
				                	<td width="40%" valign="top" align="center">
				                		<ul>
				                			<li style="white-space:nowrap;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $branch_title;//$tr->translate("BRAND_TITLE");?></li>
				                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_EXPECT_INCOME");?></li>
				                			<li style="text-align:center; font-size:14px;"><?php if (!empty($this->search['start_date'])) { echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';}echo date("D-d-M-Y",strtotime($this->search['end_date']));?></li>
				                		</ul>
				                	</td>
				                    <td width="30%"></td>
				                </tr> 
				            </table>
			           </div>
			        </td>
			    </tr>
			    <tr>
			    	<td id="exportExcel">
			            <table class="content-data" width="100%" border="1"  cellspacing="0">
			                 <thead>
			                 <tr class="hide" style="border:1px solid #000;">
				                <td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
				             </tr>
			                <tr class="style" align="center" style="font-weight: bold;background: #ccd9ff" >
			                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
			                    <td rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("TEL");?></td>
			                    <td rowspan="2"><?php echo $tr->translate("PROPERTY_CODE");?></td>
			                    <td colspan="5" style="text-align: center;"><?php echo $tr->translate("PAID_INFO");?></td>
			                    <td colspan="3" style="text-align: center;"><?php echo $tr->translate("SCHEDULE_PAYMENTUNPAID");?></td>
			                </tr>
			                <tr  class="style" align="center"  style="font-weight: bold;background: #ccd9ff">
			                    <td><?php echo $tr->translate("DAY_PAYMENT");?></td>
			                    <td><?php echo $tr->translate("AMOUNT_COLLECT");?></td>
			                    <td><?php echo $tr->translate("PRINCIPAL");?></td> 
			                    <td><?php echo $tr->translate("INTEREST");?></td>
			                    <td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
			                    <td><?php echo $tr->translate("PRINCIPAL");?></td> 
			                    <td><?php echo $tr->translate("INTEREST");?></td>
			                    <td><?php echo $tr->translate("TOTAL_PAYMENT");?></td>
			                </tr>
			                </thead>
			                <?php 
			                	 $amt_d1 = 0;
			                	 $amn_b1 = 0; 
			                	 $p_d = 0;
			                	 $p_b = 0;
			                	 $principal=0;
			                	 $interest=0;
			                	 $i=0;
			                	 $paid=0;
			                ?>
			                <?php if(!empty($this->LoanCollectionco_list))foreach ($this->LoanCollectionco_list as $key => $rs){ $i++; ?>
			                <?php 
			                	if($rs['is_completed']==1){
			                		$rs['principal_permonthafter']=0;
			                		$rs['total_interest_after']=0;
			                	}
					             $p_d = $p_d+$rs['principal_permonthafter'];
								 $amt_d1 = $amt_d1+$rs['total_interest_after'];
								 
								 $principal = $principal+$rs['principal_permonth'];
								 $interest = $interest+$rs['total_interest'];
								 $total_paid= $rs["principal_permonthafter"]+$rs["total_interest_after"];
								 
								 if($total_paid<=0){
								 	$paid++;
								 }
			               ?>
			                <tr class="style hover" style="font-size: 12px; font-family: 'Times New Roman','Khmer OS Battambang';<?php if($total_paid>0){echo 'background:#fdf1f4;';}?>">
			               		<td style="font-size: 12px; text-align: center;">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
			               		<td >&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
			               		<td >&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>
			               		<td style="font-size: 12px; line-height: 18px;white-space: normal !important;max-width: 100px;width: 100px;padding: 5px;overflow-wrap: break-word;"><?php echo $rs["phone"];?></td>
			               		<td >&nbsp;<?php echo $rs["land_address"].','.$rs["street"];?>&nbsp;</td>
			               		<td align="center">&nbsp;
			               		<?php if($rs['ispay_bank']==0){
		                    			$date= new DateTime($rs['date_payment']);
		                    			echo $date->format("d-m-Y");
		                    		}else{
		                    			echo $rs['payment_type'];
		                    		}?>&nbsp;
			               		</td>
								<td align="center">&nbsp;<?php echo $rs["no_installment"];?>&nbsp;</td>
			               		<td align="right">&nbsp;<?php echo number_format($rs["principal_permonth"],2);?>&nbsp;</td>
			               		<td align="right">&nbsp;<?php echo number_format($rs["total_interest"],2);?>&nbsp;</td>
			               		<td align="right">&nbsp;<?php echo number_format($rs["principal_permonth"]+$rs["total_interest"],2);?>&nbsp;</td>
			               		<td align="right">&nbsp;<?php echo number_format($rs["principal_permonthafter"],2);?>&nbsp;</td>
			               		<td align="right">&nbsp;<?php echo number_format($rs["total_interest_after"],2);?>&nbsp;</td>
			               		<td align="right">&nbsp;<?php echo number_format($rs["principal_permonthafter"]+$rs["total_interest_after"],2);?>&nbsp;</td>
			                </tr>
			                <?php }?>
			                <tr style="height: 30px; font-weight:bold; text-align: center;font-size: 14px; background:#87acff;">
			                	<td colspan="7"><?php echo $tr->translate("PAID");?>&nbsp;<?php echo $paid;?>&nbsp;&nbsp;<?php echo $tr->translate("NOT_PAID");?>&nbsp;&nbsp;<?php echo $i-$paid;?>&nbsp;</td>
			                	<td>&nbsp;$&nbsp;<?php echo number_format($principal,2);?>&nbsp;</td>
			                    <td>&nbsp;$&nbsp;<?php echo number_format($interest,2);?>&nbsp;</td>
			                    <td style="background:#688de0;">&nbsp;$&nbsp;<?php echo number_format($principal+$interest,2);?>&nbsp;</td>
			                    <td>&nbsp;$&nbsp;<?php echo number_format($p_d,2);?>&nbsp;</td>
			                    <td>&nbsp;$&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
			                    <td style="background:#f9a3a3;">&nbsp;$&nbsp;<?php echo number_format($amt_d1+$p_d,2);?>&nbsp;</td>
			                </tr>
			            </table>
			            	<br />
			              <?php echo $this->footerReport;?>
			    	</td>
			    </tr>
			</table>
		</div>
	</div>
</div>