<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលោះប្រាក់ដើម",4=>"បង់ផ្តាច់");
	$url_receipt = $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt'));
	$url_receiptupdate = $this->url(array('module'=>'report','controller'=>'loan','action'=>'updatereceipt'));
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->rssearch['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->rssearch['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<title><?php echo $tr->translate("RPT_CHANGE_OWNER");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
		<form method="post">
			<table style="font-family: 'Khmer OS Content'; margin: 0 auto;width:100%;" >
				<tr>
			   		<td><?php echo $frm->getElement("adv_search");?></td>
			   		<td><?php echo $frm->getElement('branch_id');?></td>
			   		<td><?php echo $frm->getElement('client_name');?></td>
			   		<td><?php echo $frm->getElement('status');?></td>
			   		<td><?php echo $frm->getElement('start_date');?></td>
			   		<td><?php echo $frm->getElement('end_date');?></td>
			   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			   	</tr>
			</table>
		</form>
		<div style="width:100%; margin:0 auto;">
		<div style="min-height:22cm; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
			</style>
			<div id="divPrint">
			<style type="text/css">
				.style{
					line-height: 20px;font-size: 11px !important;
					font-family: 'Times New Roman','Khmer OS Battambang';
				}
				.hideblog{display: none;}
				.hiddenblog{display: block !important;}
				.style1:hover{ background: #ccc; }
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				  margin-top: 100px;
				}
				.hide{visibility: hidden;}
				@media print {
				  div.divFooter {
				    position: fixed;
				    top: 0;
				  	width: 100%;
				  	height: 100px;
				  	bottom:0px;
					margin:0;
				  }
				  .hide{visibility: visible; height: 110px;}
				}
					table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:13px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
							width: 100%;
						}
						table.content-data thead tr.style {
						   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
							background: #c1d0f3;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
			</style>
				<table width="100%">
					<tr>
				    	<td align="center" valign="top">
				        	<div class="divFooter">
					        	<table border="0" width="100%" style="font-family: 'Khmer OS Battambang';margin:0;padding:0;">
					            	<tr>
					                	<td width="30%" style="border:1px solid #fff;"><img src="<?php echo $logo;?>" style="height:80px;max-width: 100%;"></td>
					                	<td width="40%" valign="top" align="center">
					                		<ul>
					                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $branch_title;?></li>
					                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("RPT_CHANGEPROPERTY");?></li>
					                			<li style="text-align:center; font-size:16px;"><?php if($this->list_end_date['start_date']){echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
					                		</ul>
					                   </td>
					                    <td width="30%"></td>
					                </tr> 
					            </table>
				            </div>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				            <table width="100%" class="content-data" border="1"  cellspacing="0">
					                <thead>
						                <tr class="hide" style="border:1px solid #000;">
						                	<td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						                </tr>
						                <tr bgcolor="#c1d0f3" class="style" align="center" >
						                    <td rowspan="2"><?php echo $tr->translate("NUM");?></td>
						                   	<td colspan="6"><?php echo $tr->translate("FROM_HOUSE");?></td>
						                    <td colspan="7"><?php echo $tr->translate("TO_HOUSE");?></td>
						                    <td rowspan="2"><?php echo $tr->translate("CHANGE_DATE");?></td>
						                    <td rowspan="2"><?php echo $tr->translate("BY_USER");?></td>
						                </tr>
						                <tr class="style" align="center">
						                	<td ><?php echo $tr->translate("BRANCH_NAME");?></td>
						                    <td ><?php echo $tr->translate("CUSTOMER_NAME");?></td>                  
						                    <td ><?php echo $tr->translate("PROPERTY_CODE");?></td>
						                    <td ><?php echo $tr->translate("SOLD_PRICE");?></td>
						                    <td ><?php echo $tr->translate("PAID");?></td>  
						                    <td ><?php echo $tr->translate("BALANCE");?></td>   
						                    <td ><?php echo $tr->translate("BRANCH_NAME");?></td> 
						                    <td ><?php echo $tr->translate("PROPERTY_CODE");?></td>
						                    <td ><?php echo $tr->translate("PRICE_BEFORE");?></td>
						                    <td ><?php echo $tr->translate("DISCOUNT_PERCENT");?></td>
						                    <td ><?php echo $tr->translate("Discount");?></td>
						                    <td ><?php echo $tr->translate("SOLD_PRICE");?></td>
						                    <td ><?php echo $tr->translate("BALANCE");?></td>
						                </tr>
						            </thead>
				                <?php 
				                $i=0;
				                $is_set =0; if(!empty($this->row)) foreach ($this->row as $index => $rs){ ?>
				                <tr class="style style1" style="white-space:nowrap; ">
				               		<td style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["from_branch"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["from_property"];?>&nbsp;</td>                 		
				               		<td align="center">&nbsp;<?php echo number_format($rs["soldprice_before"],2);?>&nbsp;</td>
				               		<td align="right">&nbsp;<?php echo number_format($rs["paid_before"],2);?>&nbsp;</td>
				               		<td align="right" >&nbsp;<?php echo number_format($rs['balance_before'],2);?>&nbsp;</td>               		
				               		<td align="right" >&nbsp;<?php echo $rs['to_branch'];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs['to_propertype'];?>&nbsp;</td>
				               		<td style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["house_priceafter"],2);?>&nbsp;</td>
				               		<td style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["discount_percentafter"],2);?>&nbsp;</td>
				               		<td style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["discount_amountafter"],2);?>&nbsp;</td>
				               		<td style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["sold_priceafter"],2);?>&nbsp;</td>
				               		<td style="white-space:nowrap; ">&nbsp;<?php echo number_format($rs["balance_after"],2);?>&nbsp;</td>
				               		<td align="center" style="white-space:nowrap; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["change_date"]));?>&nbsp;</td>
				               		<td class="" style="font:11px 'Khmer OS Battambang',Arial;text-align: center;"><?php echo $rs['user_name']?></td>
				                </tr>
				                <?php }?>
				            </table>
				              <br />
				               <table align="center" width="100%">
								   <tr style="font-size: 14px;">
								        <td style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
								        <td></td>
								        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
								        <td></td>
								        <td style="width:20%;text-align:center;font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
								   </tr>
							</table>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
	require(["dojo/ready"], function(ready){
		ready(function(){
		});
		
	});
</script>