<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$url_receipt = $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt'));
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$dbReport = new Report_Model_DbTable_DbLandreport();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->rssearch['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->rssearch['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	
	$montFomat="d-m-Y";
	if(MONTH_FORMATE_DATE_RECEIPT==1){
		$montFomat="d-M-Y";
	}
	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
	$pages=0;
	$limitNumberRow=7000;
	
	$arrayResultData = $this->summaryData;
	
?>
<title><?php echo $tr->translate("RPT_SUMMARY_DIALY");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div class="reportblog">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('RPT_SUMMARY_DIALY');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<form method="post">
			<div class="card-box">
		    	
				<div class="form-group"> 
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('branch_id');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</div>
		</form>
		<div style="min-height:22cm;width:100%; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
				a.attachFile {
					color: #008;
					padding: 0 5px;
				}
				a.attachFile.whiteColor {
					color: transparent;
				}
			</style>
			<div id="divPrint">
				<style type="text/css">
					.style{
  						line-height: 20px;font-size: 11px !important;
           				font-family: "Times New Roman","Khmer OS Battambang";
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover td{ background: #ccc !important; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table.content-data { page-break-inside:auto }
					table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					display: table-header-group;
						page-break-inside:avoid; page-break-after:auto;
						margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
						div.divFooter {
							position: fixed;
							top: 0;
							width: 100%;
							height: 100px;
							bottom:0px;
							margin:0;
						}
						.hide{visibility: visible; height: <?php echo $classHideHeight; ?>;}
						.attachFile{
							display : none;
						}
						
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:11px;
					}
					table.content-data thead tr.style {
					line-height: 25px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
						font-weight:600;
					}
					table.content-data tr.style {
					white-space: nowrap;
					
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:11px;
						font-family: "Times New Roman","Khmer OS Battambang";
					}
					table.tb-footer tr{
					line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:0 2px;
					}
					tr.voidclass {
						background: #fff7f7;
					}
					td.centerText{
						text-align: center;
					}
					.bold {
						font-weight: 600;
					}
					.redText {
						color: #f80000;
					}
					
					tr.odd {
						background: #f5f5f5;
					}

					td.moneyAlign {
						text-align: center;
					}
					.income {
						background: #f6fff7;
					}

					.expense {
						background: #fff8f6;
					}
					table.summaryTotal {
						font-family: "Times New Roman","Khmer OS Battambang";
						border-collapse: collapse;
						font-size: 11px;
						border-top: solid 1px #637fc0;
					}
					
				</style>
		   <table width="100%">
				<tr>
					<td align="center" valign="top">
					<div class="divFooter">
						<?php echo $this->headerReport; ?>
					</div>
					</td>
				</tr>
				<tr>
					<td id="exportExcel"> 	
					   <table class="content-data" width="100%" border="1"  cellspacing="0" cellpadding="0">
							<thead>
								<tr class="hide" style="border:1px solid #000;">
									<td colspan="20" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
								</tr>
								<tr class="style" align="center" >
									<td rowspan="3" class="center"><?php echo $tr->translate("NUM"); ?></td>
									<td rowspan="3" class="center"><?php echo $tr->translate("DATE"); ?></td>
									<td colspan="6" class="center"><?php echo $tr->translate("INCOME_INFO"); ?></td>
									<td colspan="3" class="center"><?php echo $tr->translate("EXPENSE_INFO"); ?></td>
									<td rowspan="3" class="center"><?php echo $tr->translate("TOTAL"); ?></td>
								</tr>
								<tr class="style" align="center" >
									<td colspan="4" class="center"><?php echo $tr->translate("INCOME_CUSTOMER_PAYMENT"); ?></td>
									<td rowspan="2" class="center"><?php echo $tr->translate("INCOME_OTHER"); ?></td>
									<td rowspan="2" class="center"><?php echo $tr->translate("INCOME_REPAIR_HOUSE"); ?></td>
									
									<td rowspan="2" class="center"><?php echo $tr->translate("OTHER_EXPENSE"); ?></td>
									<td rowspan="2" class="center"><?php echo $tr->translate("EXPENSE_REPAIR_HOUSE"); ?></td>
									<td rowspan="2" class="center"><?php echo $tr->translate("COMISSION"); ?></td>
								</tr>
								<tr class="style" align="center" >
									<td scope="col"><?php echo $tr->translate("PAID_PRINCIPAL");?></td>
									<td scope="col"><?php echo $tr->translate("EXTRA_PAYMENT");?></td>
									<td scope="col"><?php echo $tr->translate("INTEREST");?></td>
									<td scope="col"><?php echo $tr->translate("PENALIZE AMOUNT");?></td>
								</tr>
							</thead>
							<?php 
								$i=1;
								$dateValue="";
								
								$gTotalPinciple=0; $gTotalExtraPayment=0; $gTotalInterest=0; $gTotalPenalize=0;
								$gTotalIncomeOther=0; $gTotalIncomeRepairHouse=0;
								
								$gTotalOtherExpense=0;
								$gTotalExpenseRepairHouse=0;
								$gTotalCommission=0;
								
								$theGrandTotal=0;
								if(!empty($arrayResultData)) {
							?>
								<?php foreach ($arrayResultData as $index => $rs){ 
									if($dateValue!=$rs["recordDate"]){
										$comparing = $dbReport->getResulArrayBySpecificDate($rs["recordDate"],$arrayResultData);
										$filter = $comparing;
										if(count($comparing) == 0){
											$filter = $rs;
										}
										$totalPinciple			=$filter["totalPinciple"];
										$totalExtraPayment		=$filter["totalExtraPayment"];
										$totalInterest			=$filter["totalInterest"];
										$totalPenalize			=$filter["totalPenalize"];
										
										$totalIncomeOther		=$filter["totalIncomeOther"];
										$totalIncomeRepairHouse	=$filter["totalIncomeRepairHouse"];
										
										$totalOtherExpense		=$filter["totalOtherExpense"];
										$totalExpenseRepairHouse=abs($filter["totalExpenseRepairHouse"]);
										$totalExpenseComission	=empty($filter["totalExpenseComission"]) ? 0 : $filter["totalExpenseComission"];
										$totalExpenseComissionPayment=empty($filter["totalExpenseComissionPayment"]) ? 0 :$filter["totalExpenseComissionPayment"];
									
										$commission = $totalExpenseComission+$totalExpenseComissionPayment;
										
										$totalIncome = ($totalPinciple+$totalExtraPayment+$totalInterest+$totalPenalize+$totalIncomeOther+$totalIncomeRepairHouse);
										$totalExpense = ($totalOtherExpense+$totalExpenseRepairHouse+$commission);
										$rowTotal = $totalIncome - $totalExpense;
										
										$rowTotalLabel = number_format($rowTotal,2);
										$classTotal = "income";
										if($rowTotal<0){
											$rowTotalLabel = "(".number_format(abs($rowTotal),2).")";
											$classTotal = "expense";
										}
										$gTotalPinciple		= $gTotalPinciple+$totalPinciple;
										$gTotalExtraPayment	= $gTotalExtraPayment+$totalExtraPayment;
										$gTotalInterest		= $gTotalInterest+$totalInterest;
										$gTotalPenalize		= $gTotalPenalize+$totalPenalize;
										
										$gTotalIncomeOther			= $gTotalIncomeOther+$totalIncomeOther;
										$gTotalIncomeRepairHouse	= $gTotalIncomeRepairHouse+$totalIncomeRepairHouse;
										
										$gTotalOtherExpense			= $gTotalOtherExpense+$totalOtherExpense;
										$gTotalExpenseRepairHouse	= $gTotalExpenseRepairHouse+$totalExpenseRepairHouse;
										$gTotalCommission			= $gTotalCommission+$commission;
										
										$theGrandTotal= $theGrandTotal+$rowTotal;
										
										
										
								?>
								<tr class="style style1" >
									<td data-label="<?php echo $tr->translate("N_O");?>" style="text-align: center;"><?php echo $i++; ?></td>
									<td data-label="<?php echo $tr->translate("DATE");?>" class="center bold" ><?php echo date($montFomat,strtotime($rs["recordDate"]));?></td>
									<td class="moneyAlign income" data-label="<?php echo $tr->translate("PAID_PRINCIPAL");?>"  ><?php echo number_format($totalPinciple,2);?></td>
									<td class="moneyAlign income" data-label="<?php echo $tr->translate("EXTRA_PAYMENT");?>" ><?php echo number_format($totalExtraPayment,2);?></td>
									<td class="moneyAlign income" data-label="<?php echo $tr->translate("INTEREST");?>" ><?php echo number_format($totalInterest,2);?></td>
									<td class="moneyAlign income" data-label="<?php echo $tr->translate("PENALIZE AMOUNT");?>" ><?php echo number_format($totalPenalize,2);?></td>
									
									<td class="moneyAlign income" data-label="<?php echo $tr->translate("INCOME_OTHER");?>" ><?php echo number_format($totalIncomeOther,2);?></td>
									<td class="moneyAlign income" data-label="<?php echo $tr->translate("INCOME_REPAIR_HOUSE");?>" ><?php echo number_format($totalIncomeRepairHouse,2);?></td>
									
									<td class="moneyAlign expense" data-label="<?php echo $tr->translate("OTHER_EXPENSE");?>" ><?php echo number_format($totalOtherExpense,2);?></td>
									<td class="moneyAlign expense" data-label="<?php echo $tr->translate("EXPENSE_REPAIR_HOUSE");?>" ><?php echo number_format($totalExpenseRepairHouse,2);?></td>
									<td class="moneyAlign expense" data-label="<?php echo $tr->translate("COMISSION");?>" ><?php echo number_format($commission,2);?></td>
									<td class="moneyAlign <?php echo $classTotal;?> bold" data-label="<?php echo $tr->translate("TOTAL");?>" ><?php echo $rowTotalLabel;?></td>
								</tr>                     
								<?php }
									$dateValue = $rs["recordDate"]; 
								 } ?>
								 
								 <?PHP 
									$gTotalIncome = $gTotalPinciple+$gTotalExtraPayment+$gTotalInterest+$gTotalPenalize+$gTotalIncomeOther+$gTotalIncomeRepairHouse;
									$gTotalExpense = $gTotalOtherExpense+$gTotalExpenseRepairHouse+$gTotalCommission;
									
									$theGrandTotalLabel = number_format($theGrandTotal,2);
									$classGTotal = "";
									if($theGrandTotal<0){
										$theGrandTotalLabel = "(".number_format(abs($theGrandTotal),2).")";
										$classGTotal = "expense";
									}
									
								 ?>
								 <tr class="style " style="font-weight: 600; background: #c1d0f3;" >
									<td colspan="2" rowspan="2" ></td>
									<td class="moneyAlign bold"><?php echo number_format($gTotalPinciple,2);?></td>
									<td class="moneyAlign bold"><?php echo number_format($gTotalExtraPayment,2);?></td>
									<td class="moneyAlign bold"><?php echo number_format($gTotalInterest,2);?></td>
									<td class="moneyAlign bold"><?php echo number_format($gTotalPenalize,2);?></td>
									<td class="moneyAlign bold"><?php echo number_format($gTotalIncomeOther,2);?></td>
									<td class="moneyAlign bold"><?php echo number_format($gTotalIncomeRepairHouse,2);?></td>
									
									<td class="moneyAlign bold"><?php echo number_format($gTotalOtherExpense,2);?></td>
									<td class="moneyAlign bold"><?php echo number_format($gTotalExpenseRepairHouse,2);?></td>
									<td class="moneyAlign bold"><?php echo number_format($gTotalCommission,2);?></td>
									
									<td rowspan="2" class="moneyAlign bold <?php echo $classGTotal;?>"><?php echo $theGrandTotalLabel;?></td>
								 </tr>
								 <tr class="style " style="font-weight: 600; background: #c1d0f3;" >
									
									<td class="moneyAlign bold"><?php echo $tr->translate("TOTAL_INCOME");?></td>
									<td class="moneyAlign income bold" colspan="5"><?php echo number_format($gTotalIncome,2);?></td>
									<td class="moneyAlign  bold"><?php echo $tr->translate("TOTAL_EXPENSE");?></td>
									<td class="moneyAlign  expense bold" colspan="2"><?php echo number_format($gTotalExpense,2);?></td>
								 </tr>
							<?php } ?>
						</table>
						<br />
						  <?php echo $this->footerReport;?>
					</td>
				</tr>
			</table>
		</div>
	</div>
</div>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 

require(["dojo/ready"], function(ready){
	ready(function(){
		  getBranchInfo();
		 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
		 document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("RPT_SUMMARY_DIALY");?>';
		 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
	});
});

function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
		url: url_submit,	
		content:{ 
			'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>

