<?php  

	$filter = $this->frm_search;
	$dayin_khmer = $this->day_inkhmer;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();	
	$db = new Report_Model_DbTable_DbLandreport();

	$tran = $this->tran_schedule;
	$end_dat=$this->date_show;
	$db_keycode = new Application_Model_DbTable_DbKeycode();
	$key_code= $db_keycode->getSystemSetting(9);
	$free_day=$key_code['value'];
	$intest_rate = 2;
	
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
	
// 	$db_keycode = new Application_Model_DbTable_DbKeycode();
// 	$key_code= $db_keycode->getSystemSetting(22);
// 	$free_day=$key_code['value'];	
?>
<style>
.hover:hover{background: #ccc;}
</style>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><?php  echo $tr->translate("REPORT_LOAN_COLLECT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
 	<form method="post">
		<table style="width:100%;margin: 0 auto;">
			<tr>
				<td><?php echo $filter->getElement('adv_search');?></td>
				<td><?php echo $filter->getElement('branch_id');?></td>
				<td><?php echo $filter->getElement('client_name');?></td>
				<td>
					<select class="fullside" id="last_optiontype" name="last_optiontype" dojoType="dijit.form.FilteringSelect">
						<option value="-1">ទាំងអស់</option>
						<option value="1">យកតាមកាលបរិច្ឆេទបង់</option>
						<option value="0">បង់បញ្ចាប់ពេលប្រគល់ផ្ទះ</option>
					</select>
				</td>
				<td><?php echo $filter->getElement('start_date');?></td>
				<td><?php echo $filter->getElement('end_date');?></td>
				<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			</tr>
		</table>
	</form>
<div style="min-height:25cm; margin:0 auto;">
	<div id="divPrint">
	<style>
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		  table { page-break-inside:auto }
		  tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover td{padding: 1px;}
		.hide{visibility: hidden;}
		@media print {
		  div.divFooter {
		    position: fixed;
		    top: 0;
		  	width: 100%;
		  	height: 100px;
		  	bottom:0px;
			margin:0;
		  }
		.hide{visibility: visible; height: 110px;}
		}
</style>
	<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	<div class="divFooter">
	        	<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
	            	<tr>
	                	<td width="20%"><img src="<?php echo $logo;?>" height="70px"></td>
	                	<td width="60%" valign="top">
	                	<ul>
                			<li style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><?php echo $branch_title;?></li>
                			<li style="text-align:center; font-size:15px; font-family:'Khmer MEF2'"><?php echo $tr->translate("REPORT_LOAN_COLLECT");?></li>
                			<li style="text-align:center; font-size:15px;"><?php if(!empty($this->search['start_date'])){ echo date("D-d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));}?></li>
                		</ul>
                    </td>
	                    <td width="20%"></td>
	                </tr>
	            </table>
	            </div>
	        </td>
	    </tr>
	    <tr>
	    	<td id="exportExcel">
	            <table  border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%">
	                <thead>
		                 <tr class="hide" style="border:1px solid #000;">
			                <td colspan="16" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
			             </tr>
		                 <tr class="style" align="center" bgcolor="#c1d0f3" style="white-space: nowrap;font-weight: bold;">
		                    <th rowspan="2" style="padding:0px 1px;"><?php echo $tr->translate("NUM");?></th>
		                    <th rowspan="2" style="padding:0px 1px;"><?php echo $tr->translate("BRANCH_NAME");?></th>
		                    <th colspan="2" style="padding:0px 1px;"><?php echo $tr->translate("CLIENT_INFO");?></th>
		                    <th colspan="3" style="padding:0px 1px;"><?php echo $tr->translate("PROPERTY_INFO");?></th>
		                    <th colspan="4" style="padding:0px 1px;"><?php echo $tr->translate("PAYMENT");?></th>
		                    <th rowspan="2" style="padding:0px 1px;"><?php echo $tr->translate("AMOUNT_COLLECT");?></th>
		                    <th rowspan="2" style="padding:0px 1px;"><?php echo $tr->translate("DAY_PAYMENT");?></th>
		                </tr>
		                <tr class="style" bgcolor="#c1d0f3" style="white-space: nowrap; text-align: center;font-weight: bold;">
	                        <th><?php echo $tr->translate("CUSTOMER_NAME");?></th>
	                        <th><?php echo $tr->translate("TEL");?></th>
		                    <th style="padding:0px 1px;"><?php echo $tr->translate("PROPERTY_CODE");?></th>
		                    <th style="padding:0px 1px;"><?php echo $tr->translate("STREET");?></th>
	                        <th style="padding:0px 1px;"><?php echo $tr->translate("SOLD_PRICE");?></th>
		                    <th style="text-align:center ;padding:0px 1px;"><?php echo $tr->translate("PRINCIPAL");?></th>
		                    <th style="text-align:center ;padding:0px 1px;"><?php echo $tr->translate("INTEREST");?></th>
		                    <th style="text-align:center ;padding:0px 1px;"><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
		                 	<th style="text-align:center ;padding:0px 1px;"><?php echo $tr->translate("TOTAL_PAYMENT");?></th>
		                </tr>
	                </thead>
	                <?php 
		                 $amt_r1 = 0;$tir = 0;$amt_r3 = 0;$amt_r4 = 0;$amt_r5 = 0;$total_r=0;
	                	 $amt_d1 = 0;$amt_d2 = 0;$amt_d3 = 0;$amt_d4 = 0;$amt_d5 = 0;$total_b=0;
	                	 $amn_b1 = 0; $amn_b2 = 0; $amn_b3 = 0; $amn_b4 = 0;$amn_b5 = 0;$total_d=0;
	                	 $penelize=0;$total_payment=0;
	                	 $key=0;
		             ?>
	               <?php if(!empty($tran)){foreach($tran as $key =>$row){
	               	?>
	               	<tr align="center" style="font-size:9px; height: 20px; white-space:nowrap;" class="style hover">
	                    <td ><?php echo ($key+1<10)?"0":"";echo $key+1;?></td>
	                    <td align="left">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
						<td>&nbsp;<a style="color:#000; text-decoration: none;" ><?php echo $row['client_name'];?>&nbsp;</a></td>
						<td align="left" style="white-space: nowrap;">&nbsp;<?php echo $row['phone_number'];?>&nbsp;</td>
						<td>&nbsp;&nbsp;<?php echo $row['land_address']; ?>&nbsp;</td>	
						<td>&nbsp;<?php echo $row['street'];?>&nbsp;</td>
	                    <td align="left">&nbsp;<?php echo $row['price_sold'];?>&nbsp;</td>
	                    <td align="left" style="white-space: nowrap;">&nbsp;<?php echo number_format($row['principal_permonthafter'],2) ;?>&nbsp;</td>
	                    <?php $str_day = date('D',strtotime($row['date_payment']));
	                    	$day_as_khmer = $dayin_khmer[$str_day];
	                    ?>
	                    <td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($row['total_interest_after'],2));?>&nbsp;</td>
	                    <td align="center">&nbsp;<?php 
		                    $penelize = $row['penelize'];
							echo number_format($row['penelize'],2);
		                    $total_payment = $row['principal_permonthafter']+$row['total_interest_after']+$penelize+$row['service_charge'];
	                    ?>&nbsp;
	                    </td>
	                   	<td align="center">&nbsp;<?php echo str_replace('.00', '', number_format($total_payment,2));?>&nbsp;</td>
	                    <td><?php echo $row['no_installment'];?></td>
	                   <td align="center" style="white-space: nowrap;"><?php echo ($row['last_optiontype']==1)?date('d-m-Y',strtotime($row['date_payment'])):"បង់ពេលប្រគល់ផ្ទះ";?>&nbsp;</td>
	                 </tr>
		               <?php 
							$amt_d1 = $amt_d1+$row['principal_permonthafter'];
							$amt_d2 = $amt_d2+$row['total_interest_after'];
							$amt_d3 = $amt_d3+$penelize;
							$amt_d4 = $amt_d4+$total_payment;
							$amt_d5 = $amt_d5+$row['service_charge'];
							$total_d=$amt_d4;
		               ?>
	                <?php }}?>
                <?php $i=1;?>
                </table>
              <br />
		             <table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:9px;" width="100%" cellspacing="0">
		                 <tr bgcolor="#c1d0f3" class="style" style="font-weight:bold; line-height: 15px; text-align: center; font-size:9px;font-family: 'Khmer OS Content';">
		                    <td><?php echo $tr->translate('CURRENT_TYPE');?></td>                  
		                    <th><?php echo $tr->translate("TOTAL_PRINCIPLE");?></th>
		                    <th><?php echo $tr->translate("TOTAL_INTEREST");?></th>
		                    <th><?php echo $tr->translate("PENALIZE AMOUNT");?></th>
		                    <th><?php echo $tr->translate("TOTAL_PAYMENT");?></th>
		                </tr>
		                 <tr class="style" style=" line-height: 24px; font-size:9px; font-family: 'Khmer OS Content';">
		                    <td>&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($penelize,2);?>&nbsp;</td>
		                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1+$amt_d2+$penelize,2);?>&nbsp;</td>
		                </tr>
		              </table>
		               <table align="center" width="100%">
						   <tr style="font-size: 12px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'"><?php echo $tr->translate('APPROVED BY');?></th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'"><?php echo $tr->translate('VERIFYED BY');?></th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'"><?php echo $tr->translate('PREPARE BY');?></th>
						   </tr>
						</table>
					</td>
				</tr>
		</table>
	</div>
</div>
</div>