<?php $tran = $this->tran_schedule;
	$client = $this->client;
	$filter = $this->form_filter;
	$dayin_khmer = $this->day_inkhmer;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$key = new Application_Model_DbTable_DbKeycode();
	$dataterm = $key->getKeyCodeMiniInv(TRUE);
	
	$dbparmeter = new Report_Model_DbTable_DbParamater();
	$paymentCondiction = PAYMENT_CONDICTION_SCHEDULE;
	$waterMarkSetting = WATERMARK_SETTING;
?>
<title><?php echo $tr->translate('Payment Schedule');?></title>
<style>
	td p{ margin-top:0px !important;}
	#printfooter{display: none !important;}
	h2{line-height: 14px !important;}
</style>
<div style="margin:0 auto; padding: 0 40px;">
	<div id="divPrint">
	<style type="text/css">
	.style{
		line-height: 20px;font-size: 12px;
		font-family: 'Times New Roman','Khmer OS Battambang';
	}
	.font_bold{
		font-family:'Khmer OS Muol Light Light';
		font-size: 14px;
	}
	td p{ margin-top:-12px;    margin: 0;}
	table#exportExcel { page-break-inside:auto }
	tr{ page-break-inside:avoid; page-break-after:auto; }
	#header {
	  display: table-header-group;
	  page-break-inside:avoid; page-break-after:auto;
	  margin-top:10px;
	}
	.hover:hover{background: #ccc;}
	
	h2{line-height: 10px;}
	p.lblhousecode{
	 overflow-wrap: break-word;
    white-space: normal;
    width: 250px;
    display: block;
    line-height: 24px;
	}
	.hide{visibility: hidden;}
	@media print {
	 div#divFooter {
		position: fixed;
		top: 0;
		width: 100%;
		height: 100px;
		bottom:0px;
		margin:0;
	  }
		
	}
	#printfooter {
		    position: absolute;
		    bottom: 0;
		    position: fixed;
		    display: block ;
			width:100%;
		}
	.capitalWord{font-weight: bold;font-variant:  text-transform: uppercase;text-decoration: underline;}
</style>
<table style="font-family: 'Khmer OS Content'; width:100%;"  >
		<tr>
	    	<td align="center">
	        	
				<table width="100%" style="font-family:khmer;margin:0 auto;padding:0px; border:none;">
	            	<tr>
	                	<td width="25%" style="">
	                		<?php $imagelogo = $this->baseUrl()."/images/logo.jpg";
			                	if (!empty($client['project_logo'])){
			                		$imagelogo = $this->baseUrl()."/images/projects/".$client['project_logo'];
			                	}
			                	?>
	                	</td>
	                	<td width="50%" valign="top">
		                	<h2 style="text-align:center;"><img src="<?php echo $imagelogo;?>"  style="height:80px; max-width:100%;"></h2>
		                	<h2 style="text-align:center; font-weight:normal; font-size:18px; font-family:cambria"><?php echo $tr->translate("Payment Reminder");?></h2>
		                	<h2 style="text-align:center;  font-weight:normal; font-size:13px; font-family:'Khmer OS Muol Light'"> <?php echo $tr->translate('Payment Reminder CN');?></h2>
	                	</td>
	                    <td width="25%" ></td>
	                </tr>
	                <?php 
	                	$db = new Application_Model_DbTable_DbGlobal();
	                	$row = $db->getClientByType(null,$client['client_id'],1);
	                ?> 
	                <tr>
	                	<td colspan="3">
	                		<h3 style="font-size:12px;">Dear <span class="capitalWord"><?php echo $client['client_name_kh'];?></span><?php if(!empty($client['hname_kh'])){?> And <span class="capitalWord"><?php  echo $client['hname_kh'];?></span><?php }?>,</h3>
	                		<p>
	                			Pursuant to the Sales and Purchase Agreement signed for <?php echo $client['land_address'].",".$client['stree'];?>, the amount of USD 1640.00 will be due on 10 Dec 2022(Date). Please disregard this letter if you have already made the payment, otherwise, please arrange to make the due payment at your full attention. Thank you in advance for your cooperation in this matter. Wish all the best!
	                		</p>
	                	</td>
	                </tr>
	                <tr>
	                	<td colspan="3">
	                		<h3 style="font-size:12px;">尊敬的业主 <span class="capitalWord"><?php echo $client['client_name_kh'];?></span><?php if(!empty($client['hname_kh'])){?>/<span class="capitalWord"><?php  echo $client['hname_kh'];?></span><?php }?>先生和女士 :</h3>
	                		<p>
								根据您所签订的 Vue Aston 公寓<?php echo $client['land_address'].",".$client['stree'];?> （房号） 买卖协议，您有一笔金额为1640.00
								美元的付款应于2022 年12 月10 日（日期）支付。敬请提前安排以免延误付
								款时间。如您已经支付则请忽略此提醒。谢谢您的配合！祝顺利！
								附： 付款进度/Reference Payment Schedule
	                		</p>
	                	</td>
	                </tr>
	                <tr>
	                	<td colspan="3">
							<table width="100%" style="margin-top:10px; display: none;">
			                	<tr class='style'>
				                   <td width="35%" valign="top">
				                	    <p><?php echo $tr->translate('CUSTOMER_NAME');?>: <?php echo $client['client_name_kh'];echo !empty($client['hname_kh'])?"/".$client['hname_kh']:"";?> </p>
				                		<p><?php echo $tr->translate("ADDRESS");?>:<?php echo $row['village_name'];?> ,<?php echo $row['commune_name'];?> <br /><?php echo $row['district_name'];?> ,  <?php echo $row['province_en_name'];?>
				                		
				                		<p><?php echo $tr->translate("TEL");?>  : <?php echo $client['tel'];?></p>  
				                	</td>
				                    <td valign="top" style="" width="33%">
				                      <p class="lblhousecode"><?php echo $tr->translate("PROPERTY_CODE");?> : <?php echo $client['land_address'].",".$client['stree'];?></p>
				                      <p><?php echo $tr->translate("SOLD_PRICE");?>  : $ <strong><?php echo number_format($client['price_sold'],2);?></strong></p>
									  <?php if($client['payment_id']==4){?>				                	 
									  <p><?php echo $tr->translate("INSTALLMENT_AMOUNT");?>  : $ <?php echo number_format($client['for_installamount'],2);//echo number_format($client['price_sold']-$client['total_installamount'],2);?></p>
									  				                     
									  <p><?php echo $tr->translate("INTEREST_RATE");?> : <?php if ($client['interest_policy']>0){ echo $client['interest_policy_title'];}else{ echo $client['interest_rate']."&nbsp;%";}?></p>
									  <?php }?>
									  <p><?php echo $tr->translate("TERM_BORROWINYEAR");?> : <?php echo number_format($client['total_duration'],0);?>&nbsp;
										<?php if($client['payment_id']!=4){
											echo $tr->translate("MONTH");
										}else{
											echo ($dataterm['install_by']==12)?$tr->translate("YEAR"):$tr->translate("MONTH");
										}?>
									  </p>
				                    </td>
				                    <td width="30%" valign="top">
				                      <p><?php echo $tr->translate("RELEASED_DATE");?> : <?php echo date('d-m-Y',strtotime($client['buy_date']));?> </p>
				                      <p><?php echo $tr->translate("FIRST_PAYMENT");?> : <?php echo date('d-m-Y',strtotime($client['first_payment'])); ?></p>
				                      <p><?php echo $tr->translate("LIFE_LOAN");?> : 
				                      <span id="life_date">
				                      <?php 
				                      	$date= new DateTime($client['end_line']);
				                      	echo $LIFE_LOAN = $date->format("d-m-Y");
				                       ?>
				                       </span>
				                       </p>
				                    </td>
				                </tr>
			                </table>
			              </td>
			           </tr>   
	            </table>
				
	        </td>
	    </tr>
	    <tr>
	    	<td>
				<?php if($waterMarkSetting==1){?>
	            <div id="watermark" style="top:-50;opacity:0.150;position:fixed;z-index:-1;display: block;background:url('<?php echo $this->baseUrl()?>/images/watermark/scheduleWatermark.jpg') no-repeat center;background-size: 80%;z-index: -1; width:100%;height:100%;left:15;" ></div>
				<?php }?>
	            <table id="exportExcel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%">
	                 <thead>
						 <tr class="hide" style="border:1px solid #000;">
							<td colspan="8" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
						</tr>
		                 <tr class="style" align="center" style=" line-height: 20px;">
		                    <td rowspan="2">No./编号</td>
		                    <td rowspan="2">Date/日期</td>
		                    <td rowspan="2">Amount/金额</td>
		                    <td rowspan="2">Note/笔记</td>
		                </tr>
	                </thead>
	               <?php $set=1; 
	               $i=0;
	               if(!empty($tran)) foreach($tran as $key =>$row){ ?>
	               	<?php if($row['status']==0 AND $row['collect_by']==2){?>
	               	<tr align="center" style=" height: 20px;" class="style">
	               		<td colspan="10" style="background: #d3d3ff;"><span style="font-family:'Khmer OS Muol Light'"><?php if(!empty($row['note'])){echo $row['note']; }else{?>បានរំលស់ប្រាក់ដើម ចំនួន<?php }?></span><span style="font-family:Arail;font-size:16px;"> $ <?php echo str_replace('.00', '', number_format($row['total_payment'],2)); ?></span><span style="font-family:'Khmer OS Muol Light'"> នៅថ្ងៃទី  <?php echo date('d-m-Y',strtotime($row['date_payment']));?></span></td>
	               	</tr>
	               	<?php continue;}
	               	$i++; ?>
	               	<tr align="center" style=" height: 20px;" class="style hover" >
	                    <td><?php echo sprintf("%02d", $i); //($i<10)?"0":"";echo $i;?></td>
		                    <?php $str_day = date('D',strtotime($row['date_payment']));
		                    	$day_as_khmer = $dayin_khmer[$str_day];
		                    ?>
	                    <td align="center">
	                    	<?php 
		                    	if($row['last_optiontype']==1){//by date
		                    		if($row['ispay_bank']==0){
		                    			$date= new DateTime($row['date_payment']);
		                    			$LIFE_LOAN =  $date->format("d-m-Y");
		                    			echo $LIFE_LOAN;
		                    		}else{
		                    			$LIFE_LOAN = $row['payment_type'];
		                    			echo $LIFE_LOAN;
		                    		}
		                    	}else{//by last payment
		                    		if($row['ispay_bank']==0){
		                    			$LIFE_LOAN = $tr->translate("RECEIVED_PROPERTY");
		                    			echo $LIFE_LOAN;
		                    		}else{
		                    			$LIFE_LOAN = $row['payment_type'];
		                    			echo $LIFE_LOAN;
		                    		}
		                    	}
	                    		
	                    	?>
	                    </td>
	                    <td ><?php echo str_replace('.00', '', number_format($row['total_payment'],2)); ?></td>
	                    <?php 
	                   		$remain = $row['ending_balance'];
	                    ?>
	                    <td><?php echo ($row['is_completed']==1)?'Paid/有薪酬的':""; ?></td>
	                    	<?php  
// 		                    if($row['is_completed']==1){
// 			                    if($row['received_date']!=0){
// 			                    	$date = new DateTime($row['received_date']);
// 			                   	 	$receive_date =  $date->format("d-m-Y");
// 			                    }else{$receive_date='';}
// 		                    	//echo ($row['received_date']==0)?"":$receive_date;
// 		                    }
	                    	?>
	                </tr>
	               <?php }
	               ?>
	            </table>
	            <?php if ($paymentCondiction==1){?>
					<table width="100%" cellpadding="3" style="font-family:'Khmer OS Muol Light'">
			            <?php 
			            	$yearSplit = str_split(date("Y"), 2);
			            ?>
		            	<tr class="font_bold" style="height:25px; font-family:'Times New Roman','Khmer OS Battambang'">
		            		<td align="center" width="50%"></td>
		            		<td align="center" valign="bottom" style="font-style: italic;">
		            		The Peninsula Capital Co., Ltd.<br />  <span style="display: inline-block; width: 30px; border-bottom: dashed 1px #000;"></span> 
		            		ខែ <span style="display: inline-block; width: 60px; border-bottom: dashed 1px #000;"></span>
		            		ឆ្នាំ <?php echo $dbparmeter->getNumberInkhmer($yearSplit[0]);?><span style="display: inline-block; width: 60px; border-bottom: dashed 1px #000;"></span>
		            		</td>
		            	</tr>
	            	</table>
	            <?php }?>
	            <table width="100%" cellpadding="3" style="font-family:'Khmer OS Muol Light'">
	            	<tr class="font_bold" style="height:25px;">
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('ACCOUNTING_SIGN');?></td>
	            		<td align="center" valign="bottom"></td> 
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('BORROWER');?></td>
	            	</tr>
	            	<tr class="font_bold">
	            		<td align="center" height="120px" valign="bottom" style="font-family:'Khmer OS Muol Light'"><?php echo $client['user_name'];?></td>
	            		<td align="center"  valign="bottom"></td>
	            		<td align="center" valign="bottom" style="font-family:'Khmer OS Muol Light'"><?php echo $client['client_name_kh'];echo !empty($client['hname_kh'])?"/".$client['hname_kh']:"";?></td>
	            	</tr>
	            </table>
	    	</td>
	    </tr>
	    <tfoot>
        <tr height="30px">
		    <td >
		    <div id="printfooter">
        		<table width="99%" style="background: #fff;border-top: 2px solid #000;font-family: 'Times New Roman','Khmer OS Battambang'; font-size:10px;line-height: 15px;white-space:nowrap;"> 
				<tbody>
					<tr style="white-space:nowrap;line-height: 15px;">
						<td width="40%"><?php echo $this->data['website'];?></td>
						<td width="40%" align="right"><?php echo $this->data['email_client'];?></td>
					</tr>
					<tr style="white-space:nowrap;line-height: 15px;">
						<td><?php echo $this->data['footer_branch'];?></td>
						<td width="40%" align="right"><?php echo $this->data['tel-client'];?></td>
						</tr>
					</tbody>
				</table>
        	</div>
        	</td>
		</tr>
	     </tfoot>
           
	</table>
	</div>
</div>
<script>
require(["dojo/ready"], function(ready){
	 ready(function(){
		 printSave();
		 
	 });
});	 

function printSave(){
	symbal=" $";
	dojo.byId("life_date").innerHTML = '<?php echo preg_replace( "/\r|\n/", "", strip_tags(htmlspecialchars($LIFE_LOAN)));?>';
}
</script>