<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_search;
$opt = array(1=>"បង់ធម្មតា",2=>"បង់មុន",3=>"បង់រំលោះប្រាក់ដើម",4=>"បង់ផ្តាច់");

	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("REPORT_OTHERINCOME_DETAIL");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">	
	<form method="post">
		<div class="form-group">
	   		<div class="col-md-3 col-sm-3 col-xs-12">
	   			<?php echo $frm->getElement("adv_search");?>
	   		</div>
	   		<div class="col-md-3 col-sm-3 col-xs-12">
	   			<?php echo $frm->getElement('branch_id');?>
	   		</div>
	   		<div class="col-md-2 col-sm-2 col-xs-12">
	   			<?php echo $frm->getElement('client_name');?>
	   		</div>
	   		<div class="col-md-2 col-sm-2 col-xs-12">
	   			<?php echo $frm->getElement('category_id');?>
	   		</div>
	   		<div class="col-md-2 col-sm-2 col-xs-12">
	   			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
	   		</div>
	   	</div>
	   	<div class="form-group">
	   		<div class="col-md-3 col-sm-3 col-xs-12">
	   			<?php echo $frm->getElement('payment_process');?>
	   		</div>
	   		<div class="col-md-3 col-sm-3 col-xs-12">
	   			<?php echo $frm->getElement('start_date');?>
	   		</div>
	   		<div class="col-md-2 col-sm-2 col-xs-12">
	   			<?php echo $frm->getElement('end_date');?>
	   		</div>
	   		
	   		<div class="col-md-2 col-sm-2 col-xs-12">
	   		</div>
	   	</div>
	</form>
	<div style="min-height:22cm; margin:0 auto;">
			<div id="divPrint">
			<style>
				.style{
   				 	line-height: 20px;font-size: 11px !important;
           			 font-family: 'Times New Roman','Khmer OS Battambang';
        }
        .hideblog{display: none;}
        .hiddenblog{display: block !important;}
        .style1:hover{ background: #ccc; }
        table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
        table.content-data { page-break-inside:auto }
		table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
        #header {
        display: table-header-group;
        page-break-inside:avoid; page-break-after:auto;
        margin-top: 100px;
        }
        
        .center{text-align: center !important;}
        table.content-data{
            border-collapse:collapse;
            border:1px solid #000; 
            font-size:8px;
        }
        table.content-data thead tr.style {
        line-height: 25px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
            background: #c1d0f3;
            font-weight:600;
        }
        table.content-data tr.style {
         white-space: nowrap;
        
        }
        table.tb-footer{
            border-collapse:collapse;
            border:1px solid #000; 
            font-size:11px;
            font-family: 'Times New Roman','Khmer OS Battambang';
        }
        table.tb-footer tr{
        line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
        }
        table tr td{
            padding:0 2px;
        }
        tr.voidclass {
            background: #fff7f7;
        }
        td.centerText{
            text-align: center;
        }
        .redBold {
            font-weight: 600;
            color: #f80000;
        }

			
			</style>
			<?php $client_id = null; $sale_id = null;?>
			<?php 
                $i=1;
			?>
			<table width="100%">
				<tr>
			    	<td align="center">
			    	<div class="divFooter">
			        	<table width="100%" style="font-family: 'Khmer OS Battambang';margin:0; padding:0;border:none;">
			            	<tr>
			                	<td width="30%"><img src="<?php echo $logo;?>" style="height:85px;max-width: 100%;"></td>
			                	<td width="40%" valign="top" align="center">
			                         <ul>
			                			<li style="white-space:nowrap;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $branch_title;?></li>
			                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_OTHERINCOME_DETAIL");?></li>
			                			<li style="text-align:center; font-size:14px;"><?php if(!empty($this->search['start_date'])){ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));}?></li>
			                		</ul>
			                 </td>
			                 <td width="30%"></td>
			               </tr> 
			            </table>
		            </div>
			        </td>
			    </tr>
			    <tr><td id="exportExcel" class="mymy">
			    		<table width="100%" class="content-data" cellspacing="0">
			            	<?php 
			            	$grtotalprice =0; 
			            	$totalcustomer=0;
			            	if(!empty($this->loantotalcollect_list)) {
				              	foreach ($this->loantotalcollect_list as $index => $rs){?>
			              			<?php if ($client_id!=$rs["client_id"]) { ?>
			              			<?php if ($index>0){?>
			              			<tr class="style stylehover" style=" line-height: 20px; text-align: center;" >
				                		<td colspan="8" style="border-left: solid #fff 1px;  border-bottom : solid #fff 1px;">&nbsp;</td>
					                    <td style="background:#eaeaea;padding:2px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
					                    <td align="right" style="padding:5px 0px; border-bottom: double #000 2px;padding:2px 0px;">&nbsp;<?php echo number_format($totalcustomer,2);?>&nbsp;</td>
					                </tr>
	               					<tr>
					                	<td colspan="16" style="border-left:1px solid #fff;border-right:1px solid #fff;">&nbsp;</td>
					                </tr>
			              			<?php }?>
		              				<tr style="background:#f6f6f6;border: 1px solid #fff;border-bottom: 1px solid #000;" >
		              					<td colspan="18"  style=";font-size: 14px;font-family: 'Times New Roman','Khmer OS Battambang';">&nbsp;&nbsp;
					              			<?php 
					              				 echo $tr->translate("CUSTOMER_NAME").':'.$rs["name_kh"].',';
					              				 echo $tr->translate("SEX").':';
					              					if (!empty($rs['sex']) AND $rs['sex']==1){
					              					echo "M";
					              				}
					              				else {
					              					echo "F";
					              				}
					              				$totalcustomer=0;
					              			?>
			              				</td>
					              	</tr>
			               <thead>
									<tr  class="style" align="center" >
									<td scope="col"><?php echo $tr->translate("NUM");?></td>
									<td scope="col"><?php echo $tr->translate("BRANCH_NAME");?></td>
									<td scope="col"><?php echo $tr->translate("DATE");?></td>
									<td scope="col"><?php echo $tr->translate("RECEIPT_NO");?></td>
									<td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>  
									<td scope="col"><?php echo $tr->translate("STREET");?></td>
									<td scope="col"><?php echo $tr->translate("CATEGORY");?></td>	
									<td scope="col"><?php echo $tr->translate("DESCRIPTION");?></td>   
									<td scope="col"><?php echo $tr->translate("PRICE");?></td>
									<td scope="col"><?php echo $tr->translate("QUANTITY");?></td>
									<td scope="col"><?php echo $tr->translate("TOTAL");?></td>
									</tr>
						   </thead>
				              <?php }?>
				            <?php 
				            $grtotalprice = $grtotalprice+$rs["total"];
				            $totalcustomer = $totalcustomer+$rs["total"];
				            ?>
			                <tr class="style stylehover <?php if($index%2==1){echo"even";}?>" style="border:1px solid #ccc;font-family: 'Times New Roman','Khmer OS Battambang';white-space: nowrap;" width="100%">
			               		<td data-label="<?php echo $tr->translate("NUM");?>" style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
			               		<td data-label="<?php echo $tr->translate("BRANCH_NAME");?>" align="center">&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
			               		<td data-label="<?php echo $tr->translate("DATE");?>" align="center">&nbsp;<?php echo date("d/m/Y",strtotime($rs["date"]));?>&nbsp;</td>
			               		<td data-label="<?php echo $tr->translate("RECEIPT_NO");?>" align="center">&nbsp;<?php echo $rs["invoice"];?>&nbsp;</td>
			               		<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="center">&nbsp;<?php echo $rs["land_address"];?>&nbsp;</td>
			               		<td data-label="<?php echo $tr->translate("STREET");?>" align="center">&nbsp;<?php echo $rs["street"];?>&nbsp;</td>
			               		<td  data-label="<?php echo $tr->translate("CATEGORY");?>" valign="top">&nbsp;<?php echo $rs["category"];?>&nbsp;</td>
			               		<td data-label="<?php echo $tr->translate("DESCRIPTION");?>" >&nbsp;<?php echo $rs["description"];?>&nbsp;</td>
			               		<td data-label="<?php echo $tr->translate("PRICE");?>" align="right">&nbsp;&nbsp;<?php echo number_format($rs["price"],2);?>&nbsp;</td>
			               		<td data-label="<?php echo $tr->translate("QUANTITY");?>" align="center">&nbsp;&nbsp;<?php echo $rs["qty"];?></td>               		
			               		<td data-label="<?php echo $tr->translate("TOTAL");?>" align="right">&nbsp;<?php echo number_format($rs["total"],2);?>&nbsp;</td>
			                </tr>
			                <?php if ($client_id!=$rs["client_id"]) {
			                	$client_id=$rs["client_id"];
			                } ?>
			                <?php }?>
			                 <tr  class="style stylehover" style=" line-height: 20px; text-align: center;" >
		                		<td colspan="8" style="border-left: solid #fff 1px;  border-bottom : solid #fff 1px;">&nbsp;</td>
			                    <td style="background:#eaeaea;padding:2px 0px;" colspan="2">&nbsp;​<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
			                    <td align="right" style="padding:5px 0px; border-bottom: solid #000 2px;padding:2px 0px;">&nbsp;<?php echo number_format($totalcustomer,2);?>&nbsp;</td>
			                </tr>
			                <tr>
			                	<td colspan="16" style="border-left:1px solid #fff; border-bottom : solid #fff 1px; border-right:1px solid #fff;">&nbsp;</td>
			                </tr>
			                <tr  class="style stylehover" style=" line-height: 20px; text-align: center;" >
			                		<td colspan="8" style="border-left: solid #fff 1px;  border-bottom : solid #fff 1px;">&nbsp;</td>
				                    <td style="background:#eaeaea;padding:5px 0px; border-bottom: double #000 4px;" colspan="2">&nbsp;​<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
				                    <td align="right" style="background:#eaeaea;padding:5px 0px; border-bottom: double #000 4px;">&nbsp;<?php echo number_format($grtotalprice,2);?>&nbsp;</td>
				                </tr>
			                <?php }?>
			            </table>
			              <br />
			               <table align="center" width="100%">
							   <tr style="font-size: 14px;">
							        <td style="width:20%;text-align:center;  font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
							        <td></td>
							        <td style="width:20%;text-align:center; font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
							        <td></td>
							        <td style="width:20%;text-align:center;font-family:'Times New Roman','Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
							   </tr>
						</table>
			    	</td>
			    </tr>
			</table>
		</div>
	</div>
</div>
