<?php 
	$filter = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
	$showOtherDis = OTHER_DIS_OPTION;
	$showEditSchedule = SHOW_EDIT_SCHEDULE;
?>
<meta charset="utf-8">
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("LOAN_DISBURSE");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i> <?php echo $tr->translate('LOAN_DISBURSE');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
    <form method="post">
	    <div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('adv_search');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('branch_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<input id="land_id" />
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('client_name');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('schedule_opt');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('co_id');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('sale_status');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('buy_type');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('property_type');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('start_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('end_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('queryOrdering');?>
				</div>
			</div>
		</div>
	</form>
	<div id="divPrint" style="margin: 0 auto;">
	<style>
		.hover:hover{ background: #ccc;}
		.style{
			line-height: 20px;font-size: 14px !important;
			font-family:'Times New Roman','Khmer OS Battambang';
		}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
		th{padding: 5px;}
		.hover td{padding: 1px;}
		.hide{visibility: hidden;}
		@media print {
		  div.divFooter {
		    position: fixed;
		    top: 0;
		  	width: 100%;
		  	height: 100px;
		  	bottom:0px;
			margin:0;
		  }
		.hide{visibility: visible; height: 110px;}
		}
		.divFooter table{
			font-family: 'Times New Roman','Khmer OS Battambang';
			margin:0; 
			padding:0; 
			border:none;
		}
		table.content-data{
			border-collapse:collapse;
			border:1px solid #000; 
			font-size:13px;
		}
		table.content-data thead tr.style {
		   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
		}
		table.tb-footer{
		border-collapse:collapse;
		border:1px solid #000; 
		font-size:13px;
		}
		table.tb-footer tr{
		 line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;
		}
		.border_bottom {
			border-bottom: 2px solid #000;
		}
		table tr td{
			padding:0 2px;
		}
	</style>
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;">
		<tr>
	    	<td align="center">
	        	<div class="divFooter">
		        	<table width="100%">
		            	<tr>
		                	<td width="30%"><img src="<?php echo $logo;?>" height="85px" ></td>
		                	<td width="40%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $branch_title;?></li>
		                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("LOAN_DISBURSE");?></li>
		                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>;"><?php if(!empty($this->list_end_date['start_date'])){echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
		                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>;"><?php if($this->branch_id>0){ echo $tr->translate("BRANCH_NAME").' '.@$this->loanrelease_list[0]['branch_name']; }?></li>
		                		</ul>
		                	</td>
		                    <td width="30%"></td>
		                </tr> 
		            </table>
	            </div>
	        </td>
	    </tr>
	    <tr>
	    	<td id="exportExcel">
	    		<?php 
	    		$colspanDIS=3;
	    		?>
	            <table class="content-data" border="1"​ width="100%" cellspacing="0">
	               <thead>
	                 <tr class="hide" style="border:1px solid #000;">
		                <td colspan="18" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
		             </tr>
	                 <tr bgcolor="#c1d0f3" class="style" align="center" >
	                    <td rowspan="2"><span><?php echo $tr->translate("NUM");?></span></td>
	                    <td rowspan="2"><span><?php echo $tr->translate("CUSTOMER_NAME");?></span></td>
	                    <td colspan="4"><span><?php echo $tr->translate("PROPERTY_INFO");?></span></td>
	                    <td colspan="<?php echo $colspanDIS;?>"><span><?php echo $tr->translate("INFO_INDILOAN");?></span></td>
	                    <td colspan="8"><span><?php echo $tr->translate("PAYMENT_INFO");?></span></td>
	                    <td rowspan="2"><span><?php echo $tr->translate("BY_USER");?></span></td>
	                </tr>
	                <tr bgcolor="#c1d0f3" class="style" align="center" >
	                    <td><?php echo $tr->translate("TYPE");?></td>
	                    <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
	                    <td><?php echo $tr->translate("STREET");?></td>
	                    <td><?php echo $tr->translate("AMOUNT_PROPERTY");?></td>
	                    <td><?php echo $tr->translate("PRICE_BEFORE");?></td>
	                    <td><?php echo $tr->translate("DISCOUNT");?>%</td>
	                    <td><?php echo $tr->translate("DISCOUNT");?></td>
	                    <td><?php echo $tr->translate("SOLD_PRICE");?></td>
	                    <td><?php echo $tr->translate("PAID");?></td>
	                    <td><?php echo $tr->translate("BALANCE");?></td>
	                    <td><?php echo $tr->translate("PERIIOD");?></td>
	                    <td ><?php echo $tr->translate("INTEREST");?>(%<?php echo $tr->translate("YEAR");?>)</td>
	                    <td><?php echo $tr->translate("BUY_DATE");?></td>
	                    <td><?php echo $tr->translate("FIRST_PAYMENT");?></td>
	                    <td><?php echo $tr->translate("END_DATE");?></td>
	                </tr>
	              </thead>
	               <?php 
	               $amount_property=0;
	               $link="#";
	               $total_paid = 0;$total=0;$balance=0;$set_cancel=0;
	               $payment_0=0;$sold_price0=0;$paid_price0=0;$balace_price0=0;
	               $payment_1=0;$payment_2=0;$payment_3=0;$payment_4=0;$payment_5=0;$payment_6=0;
	               $sold_price1=0;$sold_price2=0;$sold_price3=0;$sold_price4=0;$sold_price5=0;$sold_price6=0;
	               $paid_price1=0;$paid_price2=0;$paid_price3=0;$paid_price4=0;$paid_price5=0;$paid_price6=0;
	               $balace_price1=0;$balace_price2=0;$balace_price3=0;$balace_price4=0;$balace_price5=0;$balace_price6=0;
	               $payment_id='';
	               
	               $amount_property=0;
	               $amt_pro_payment_cancel=0;
	               $amt_pro_payment_1=0;
	               $amt_pro_payment_2=0;
	               $amt_pro_payment_3=0;
	               $amt_pro_payment_4=0;
	               $amt_pro_payment_5=0;
	               $amt_pro_payment_6=0;
	               
	               $db  = new Report_Model_DbTable_DbParamater();
	               if(!empty($this->loanrelease_list)) foreach($this->loanrelease_list as $key =>$row){?>
	               <?php 
	               $row['totalAmountCreadit'] = empty($row['totalAmountCreadit'])?0:$row['totalAmountCreadit'];
	               if(!empty($row['old_land_id'])){
	               	$idse = explode(",", $row['old_land_id']);
	               	$countland = count($idse);
	               	$amount_property = $amount_property+$countland;
	               	if($row['is_cancel']==0){
	               		if($row['payment_id']==1){
	               			$amt_pro_payment_1 = $amt_pro_payment_1 + $countland;
	               		}elseif($row['payment_id']==2){
	               			$amt_pro_payment_2 = $amt_pro_payment_2 + $countland;
	               		}elseif($row['payment_id']==3){
	               			$amt_pro_payment_3 = $amt_pro_payment_3 + $countland;
	               		}elseif($row['payment_id']==4){
	               			$amt_pro_payment_4 = $amt_pro_payment_4 + $countland;
	               		}elseif($row['payment_id']==5){
	               			$amt_pro_payment_5 = $amt_pro_payment_5 + $countland;
	               		}elseif($row['payment_id']==6){
	               			$amt_pro_payment_6 = $amt_pro_payment_6 + $countland;
	               		}
	               	}else{
	               		$amt_pro_payment_cancel = $amt_pro_payment_cancel + $countland;
	               	}
	               }else{
	               	$countland = 1;
	               	$amount_property = $amount_property+$countland;
	               	if($row['is_cancel']==0){
	               		if($row['payment_id']==1){
	               			$amt_pro_payment_1 = $amt_pro_payment_1 + $countland;
	               		}elseif($row['payment_id']==2){
	               			$amt_pro_payment_2 = $amt_pro_payment_2 + $countland;
	               		}elseif($row['payment_id']==3){
	               			$amt_pro_payment_3 = $amt_pro_payment_3 + $countland;
	               		}elseif($row['payment_id']==4){
	               			$amt_pro_payment_4 = $amt_pro_payment_4 + $countland;
	               		}elseif($row['payment_id']==5){
	               			$amt_pro_payment_5 = $amt_pro_payment_5 + $countland;
	               		}elseif($row['payment_id']==6){
	               			$amt_pro_payment_6 = $amt_pro_payment_6 + $countland;
	               		}
	               	}else{
	               		$amt_pro_payment_cancel = $amt_pro_payment_cancel + $countland;
	               	}
	               }
	               
	             if($row['is_cancel']==0){
// 	             	if (!empty($row['old_land_id'])){
// 	             		$idse = explode(",", $row['old_land_id']);
// 	             		$countland = count($idse);
// 	             		$amount_property = $amount_property+$countland;
// 	             	}else{
// 	             		$amount_property = $amount_property+1;
// 	             	}
	             	
	               if($row['payment_id']==1){
	               	 $payment_1=$payment_1+1;
	               	 $sold_price1=$sold_price1+$row['price_sold'];
// 	               	 $paid_price1=$paid_price1+$row['paid_amount'];
// 	               	 $balace_price1=$balace_price1+($row['price_sold']-$row['paid_amount']);
	               	 
	               	 $paid_price1=$paid_price1+$row['paid_amount']+$row['totalAmountCreadit'];
	               	 $balace_price1=$balace_price1+($row['price_sold']-($row['paid_amount']+$row['totalAmountCreadit']));
	               }elseif($row['payment_id']==2){
	               	 $payment_2=$payment_2+1;
	               	 $sold_price2=$sold_price2+$row['price_sold'];
// 	               	 $paid_price2=$paid_price2+$row['paid_amount'];
// 	               	 $balace_price2=$balace_price2+($row['price_sold']-$row['paid_amount']);
	               	 
	               	 $paid_price2=$paid_price2+$row['paid_amount']+$row['totalAmountCreadit'];
	               	 $balace_price2=$balace_price2+($row['price_sold']-($row['paid_amount']+$row['totalAmountCreadit']));
	               }elseif($row['payment_id']==3){
	               	 $payment_3=$payment_3+1;
	               	 $sold_price3=$sold_price3+$row['price_sold'];
// 	               	 $paid_price3=$paid_price3+$row['paid_amount'];
// 	               	 $balace_price3=$balace_price3+($row['price_sold']-$row['paid_amount']);

	               	 $paid_price3=$paid_price3+$row['paid_amount']+$row['totalAmountCreadit'];
	               	 $balace_price3=$balace_price3+($row['price_sold']-($row['paid_amount']+$row['totalAmountCreadit']));
	               }elseif($row['payment_id']==4){
	               	 $payment_4=$payment_4+1;
	               	 $sold_price4=$sold_price4+$row['price_sold'];
// 	               	 $paid_price4=$paid_price4+$row['paid_amount'];
// 	               	 $balace_price4=$balace_price4+($row['price_sold']-$row['paid_amount']);
	               	 
	               	 $paid_price4=$paid_price4+$row['paid_amount']+$row['totalAmountCreadit'];
	               	 $balace_price4=$balace_price4+($row['price_sold']-($row['paid_amount']+$row['totalAmountCreadit']));
	               }elseif($row['payment_id']==5){
	               	 $payment_5=$payment_5+1;
	               	 $sold_price5=$sold_price5+$row['price_sold'];
// 	               	 $paid_price5=$paid_price5+$row['paid_amount'];
// 	               	 $balace_price5=$balace_price5+($row['price_sold']-$row['paid_amount']);

	               	 $paid_price5=$paid_price5+$row['paid_amount']+$row['totalAmountCreadit'];
	               	 $balace_price5=$balace_price5+($row['price_sold']-($row['paid_amount']+$row['totalAmountCreadit']));
	               }
	               elseif($row['payment_id']==6){
	               	$payment_6=$payment_6+1;
	               	$sold_price6=$sold_price6+$row['price_sold'];
// 	               	$paid_price6=$paid_price6+$row['paid_amount'];
// 	               	$balace_price6=$balace_price6+($row['price_sold']-$row['paid_amount']);
	               	
	               	$paid_price6=$paid_price6+$row['paid_amount']+$row['totalAmountCreadit'];
	               	$balace_price6=$balace_price6+($row['price_sold']-($row['paid_amount']+$row['totalAmountCreadit']) );
	               }
// 	              	$total=$total+$row['paid_amount'];
// 	              	$total_paid=$total_paid+$row['paid_amount'];
// 	              	$balance=$balance+($row['price_sold']-$row['paid_amount']);
	              	
	              	$total=$total+$row['paid_amount']+$row['totalAmountCreadit'];
	              	$total_paid=$total_paid+$row['paid_amount']+$row['totalAmountCreadit'];
	              	$balance=$balance+($row['price_sold']-($row['paid_amount']+$row['totalAmountCreadit']) );
	              
	              if($row['payment_id']!=$payment_id){?>
	              	<tr>
	              		<td colspan="18" style="text-align:center; font-size:14px; font-family:'Khmer OS Muol Light'"><?php echo $row['paymenttype']; ?></td>
	              	</tr>
	              <?php } 
	             }else{
	             	$payment_0=$payment_0+1;
// 	             	$paid_price0=$paid_price0+$row['paid_amount'];
	             	$paid_price0=$paid_price0+$row['paid_amount']+$row['totalAmountCreadit'];
	             	if($set_cancel==0){$set_cancel=1;
	             	?>
	             	<tr>
	              		<td colspan="18" style="text-align:center; font-size:14px; font-family:'Khmer OS Muol Light'">បោះបង់<?php //echo $row['paymenttype']; ?></td>
	              	</tr>
	             <?php }}
	              	$payment_id = $row['payment_id']?>
	              	<tr oncontextmenu="setrowdata(<?php echo $row['id'];?>);return false;" style="line-height: 20px; white-space: nowrap;" class="hover context-menu-one">
						<td align="center"><?php echo $key+1; ?></td>
						<!-- <td ><a target="_blank" style="color:#000; text-decoration: none;" href="<?php //echo $link;?>"><?php //echo $row['branch_name']; ?></a></td> -->
						<!--<td ><a target="_blank" style="color:#000; text-decoration: none;" href="<?php //echo $link;?>"><?php //echo $row['client_number']; ?></a></td> -->
						<td width="100px"><?php echo $row['name_kh'];?></td>
						<td><?php echo $row['propertype']; ?></td>
						<!--<td><a target="_blank" style="color:#000; text-decoration: none;" href="<?php echo $link;?>"><?php echo $row['land_code']; ?></a></td> -->	
						<td align="left"><span style="max-width: 330px; display: block; white-space: pre-line; line-height: 16px; overflow-wrap: break-word;padding: 0 1px;" ><?php echo $row['land_address']; ?></span></td>
						<td><?php echo $row['street'];?></td>
						<td align="center"><?php echo $countland; ?></td>
						
						<td align="right"><span style="line-height:15px;"><?php echo number_format($row['price_before'],2); ?></span></td>
						<td align="center"><?php echo number_format($row['discount_percent'],2); ?></td>	
						<td align="right" style="white-space:nowrap;"><?php 
						$other_discount = empty($row['other_discount'])?0:$row['other_discount'];
						echo number_format($row['discount_amount']+$other_discount,2); ?></td>
						<td align="right" style="white-space:nowrap;"><?php echo number_format($row['price_sold'],2); ?></td>	
						<!-- <td align="left"><span style="line-height:15px;"><?php //echo $row['other_fee']; ?></span></td>-->
						<?php 
// 							$percent = $db->getFirstDepositBySaleID($row['id'],$row['payment_id']);
// 							$percent =$percent['percent'];
						?>
						<td style="white-space:nowrap; text-align: right;">
						<?php 
							if($row['payment_id']==4){
// 								echo number_format($row['paid_amount'],2);
								$paidAmoutn = $row['paid_amount']+$row['totalAmountCreadit'];
								echo number_format($paidAmoutn,2);
							}elseif($row['payment_id']==1){
// 								echo number_format($row['paid_amount'],2);
								$paidAmoutn = $row['paid_amount']+$row['totalAmountCreadit'];
								echo number_format($paidAmoutn,2);
							}else{
// 								echo number_format($row['paid_amount'],2);
								$paidAmoutn = $row['paid_amount']+$row['totalAmountCreadit'];
								echo number_format($paidAmoutn,2);
							}
						?></td>
						<td align="right" style="white-space:nowrap;"><?php echo number_format($row['price_sold']-$paidAmoutn,2);//echo number_format($row['price_sold']-$row['paid_amount'],2); ?></td>
						<!-- <td style="white-space:nowrap; font-size:10px;text-align: left;"><?php //echo $row['paymenttype']; ?></td> -->
						<td align="center"><?php if($row['payment_id']==3 OR $row['payment_id']==4){ echo $row['total_duration']; } if($row['payment_id']==6){ echo $row['times']."ដង";}?></td>
						<td align="center"><?php if($row['payment_id']==3 OR $row['payment_id']==4){ echo $row['interest_rate']; }?></td>
						<td align="center" style="white-space:nowrap;"><?php echo date("d-m-Y",strtotime($row['buy_date'])); ?></td>
						<!--<td><?php //if($row['payment_id']==3 OR $row['payment_id']==4){echo date("d-m-Y",strtotime($row['startcal_date']));}?></td> -->
						<td style="max-width:120px;white-space: normal;"><?php if($row['payment_id']==1){echo "<span style='font-size:10px;line-height:15px;'>".$row['note']."</span>"; } if($row['payment_id']==3 OR $row['payment_id']==4){echo date("d-m-Y",strtotime($row['first_payment'])); }?></td>
						<td align="center" style="white-space:nowrap;" ><?php 	$date= new DateTime($row['end_line']);	echo $date->format("d-m-Y");?></td>
						<td align="center" style="white-space:nowrap;" ><?php echo $row['user_name'];?></td>
						</tr>
					<?php }?>
	            		<tr>
	            			<td colspan="18" style=" border: #fff solid 1px;    border-top: solid 1px #000;">
				             <br />
				             <table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
			                 	<td></td>
			                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TYPE");?></span></td>
			                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("SALE_AMOUNT");?></span></td>
			                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL_INCASH");?></span></td>
			                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("TOTAL_PAYMENTED");?></span></td>
			                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("LOANOUTSTADING");?></span></td>
			                    <td align="center"><span class="border_bottom"><?php echo $tr->translate("ចំនួនអចលនទ្រព្យ");?></span></td>
			                    <td></td>
			                 </tr>
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
			                 	<td></td>
			                    <td align="right"><?php echo $tr->translate("SALE_CANCEL");?></td>
			                    <td align="center"><?php echo $payment_0;?></td>
			                    <td align="right">$<?php echo number_format(0,2);//number_format($paid_price0,2);?></td>
			                    <td align="right">$<?php echo number_format($paid_price0,2);?></td>
			                    <td align="right">$<?php echo number_format(0,2);?></td>
			                    <td align="right"><?php echo number_format($amt_pro_payment_cancel,0);?></td>
			                    <td></td>
			                 </tr>
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
			                 	<td></td>
			                    <td align="right"><?php echo $tr->translate("DEPOSIT");?></td>
			                    <td align="center"><?php echo $payment_1;?></td>
			                    <td align="right">$<?php echo number_format($sold_price1,2);?></td>
			                    <td align="right">$<?php echo number_format($paid_price1,2);?></td>
			                    <td align="right">$<?php echo number_format($balace_price1,2);?></td>
			                    <td align="right"><?php echo number_format($amt_pro_payment_1,0);?></td>
			                    <td></td>
			                 </tr>
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
			                 	<td></td>
			                    <td align="right"><?php echo $tr->translate("PAYOFF_PAID");?></td>
			                    <td align="center"><?php echo $payment_2;?></td>
			                    <td align="right">$<?php echo number_format($sold_price2,2);?></td>
			                    <td align="right">$<?php echo number_format($paid_price2,2);?></td>
			                    <td align="right">$<?php echo number_format($balace_price2,2);?></td>
			                    <td align="right"><?php echo number_format($amt_pro_payment_2,0);?></td>
			                    <td></td>
			                 </tr>
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
			                 	<td></td>
			                    <td align="right"><?php echo $tr->translate("FIXED_PAYMENT");?></td>
			                    <td align="center"><?php echo $payment_3;?></td>
			                    <td align="right">$<?php echo number_format($sold_price3,2);?></td>
			                    <td align="right">$<?php echo number_format($paid_price3,2);?></td>
			                    <td align="right">$<?php echo number_format($balace_price3,2);?></td>
			                    <td align="right"><?php echo number_format($amt_pro_payment_3,0);?></td>
			                    <td></td>
			                 </tr>
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
			                 	<td></td>
			                    <td align="right"><?php echo $tr->translate("FIXIBLE");?></td>
			                    <td align="center"><?php echo $payment_6;?></td>
			                    <td align="right">$<?php echo number_format($sold_price6,2);?></td>
			                    <td align="right">$<?php echo number_format($paid_price6,2);?></td>
			                    <td align="right">$<?php echo number_format($balace_price6,2);?></td>
			                    <td align="right"><?php echo number_format($amt_pro_payment_6,0);?></td>
			                    <td></td>
			                 </tr>
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
			                	<td></td>
			                    <td align="right"><?php echo $tr->translate("INSTALLMENT");?></td>
			                    <td align="center"><?php echo $payment_4;?></td>
			                    <td align="right">$<?php echo number_format($sold_price4,2);?></td>
			                    <td align="right">$<?php echo number_format($paid_price4,2);?></td>
			                    <td align="right">$<?php echo number_format($balace_price4,2);?></td>
			                    <td align="right"><?php echo number_format($amt_pro_payment_4,0);?></td>
			                    <td></td>
			                 </tr>
			                 <tr bgcolor="#a0baf5" class="style" style="border-bottom: 4px double #000; line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
			                 	<td></td>
			                    <td align="right"><?php echo $tr->translate("BANK_SCHEDULE");?></td>
			                    <td align="center"><?php echo $payment_5;?></td>
			                    <td align="right">$<?php echo number_format($sold_price5,2);?></td>
			                    <td align="right">$<?php echo number_format($paid_price5,2);?></td>
			                    <td align="right">$<?php echo number_format($balace_price5,2);?></td>
			                    <td align="right"><?php echo number_format($amt_pro_payment_5,0);?></td>
			                    <td></td>
			                 </tr>
			                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px;  font-weight: bold; font-size:14px; padding:2px 0px; height: 25px;">
			                    <td align="right"><?php echo $tr->translate("ALL_TOTAL");?></td>
			                    <td></td>
			                    <td align="center" ><?php echo $payment_0+$payment_1+$payment_2+$payment_3+$payment_4+$payment_5+$payment_6;?></td>
			                    <td align="right" >$<?php echo number_format($paid_price0+$sold_price1+$sold_price2+$sold_price3+$sold_price4+$sold_price5+$sold_price6,2);?></td>
			                    <td align="right" >$<?php echo number_format($paid_price0+$paid_price1+$paid_price2+$paid_price3+$paid_price4+$paid_price5+$paid_price6,2);?></td>
			                    <td align="right" >$<?php echo number_format($balace_price1+$balace_price2+$balace_price3+$balace_price4+$balace_price5+$balace_price6,2);?></td>
			                 	 <td align="right"><?php echo number_format($amount_property,0);?></td>
			                 	<td></td>
			                 </tr>
			              </table>
			             </td>
			           </tr>
	              </table>
	              <br />
	              <?php echo $this->footerReport;?>
	    	</td>
	    </tr>
	</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
	}, "land_id");		 
});
land_id = '<?php echo $this->search['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
} 
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="agreement"){
				url='<?php echo $this->baseUrl()."/report/paramater/rpt-agreement/id/";?>';
			}else if(key=="reschedule"){
				url='<?php echo $this->baseUrl()."/report/loan/rpt-paymentschedules/id/";?>';
			}else if(key=="edit"){
				url='<?php echo $this->baseUrl()."/loan/index/rpt-updatepayment/id/";?>';
			}
			else if(key=="editstatus"){
				url='<?php echo $this->baseUrl()."/report/loan/rpt-updatestatus/id/";?>';
			}
			else if(key=="payment"){
				url='<?php echo $this->baseUrl()."/report/loan/paymenthistory/id/";?>';
			}
			gotoAction();
		},
		items: {
			"agreement": {name: "<?php echo $tr->translate("AGREEMENT");?>", icon: "fa-file-text", accesskey: "c"},
			"reschedule": {name: "<?php echo $tr->translate("SCHEDULE_PAYMENT");?>", icon: "fa-calendar"},
			<?php if($showEditSchedule==1){?>
			"edit": {name: "<?php echo $tr->translate("EDIT_SCHEDULE");?>", icon: "fa-money", accesskey: "c o p y"},
			<?php }?>
			//"editstatus": {name: "<?php echo $tr->translate("EDIT_SCHEDULE_STATUS");?>", icon: "fa-money", accesskey: "c o p y"},
			"payment": {name: "<?php echo $tr->translate("REPORT_LOAN_PAYMENT");?>", icon: "fa-money", accesskey: "c o p y"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>