<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$url_receipt = $this->url(array('module'=>'report','controller'=>'loan','action'=>'receipt'));
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->rssearch['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->rssearch['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<title><?php echo $tr->translate("RPT_CLIENT_PAYMENT");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div style="min-height:26cm; margin:0 auto; padding:0.5cm 0.5cm 0cm 0.5cm">
		<form method="post">
			<table style="font-family: 'Khmer OS Content'; margin: 0 auto;width:100%;" >
				<tr>
			   		<td><?php echo $frm->getElement("adv_search");?></td>
			   		<td><?php echo $frm->getElement('branch_id');?></td>
			   		<td><input id="land_id" /></td>
			   		<td><?php echo $frm->getElement('client_name');?></td>
			   	</tr>
			   	<tr>
			   		<td><?php echo $frm->getElement('payment_method');?></td>
			   		<td><?php echo $frm->getElement('user_id');?></td>
			   		<td><?php echo $frm->getElement('start_date');?></td>
			   		<td><?php echo $frm->getElement('end_date');?></td>
			   		<td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			   	</tr>
			</table>
		</form>
		<div style="width:100%; margin:0 auto;">
		<div style="min-height:22cm; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
			</style>
			<div id="divPrint">
				<style type="text/css">
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table { page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
					 .hide{visibility: visible; height: 110px;}
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
						font-family: 'Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
				</style>
				<table width="100%">
					<tr>
				    	<td align="center" valign="top">
				        	<div class="divFooter">
					        	<table border="0" width="100%" style="font-family: 'Khmer OS Battambang';"style="margin:0;padding:0;">
					            	<tr>
					                	<td width="30%" style="border:1px solid #fff;"><img src="<?php echo $logo;?>" height="80px"></td>
					                	<td width="40%" valign="top">
					                		<ul>
					                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light';"><?php echo $branch_title;?></li>
					                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light';"><?php echo $tr->translate("RPT_CLIENT_PAYMENT");?></li>
					                			<li style="text-align:center; font-size:16px;"><?php if($this->list_end_date['start_date']){echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></li>
					                		</ul>
					                   </td>
					                    <td width="30%"></td>
					                </tr> 
					            </table>
				            </div>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				            <table class="content-data" width="100%" border="1"  cellspacing="0" cellpadding="0">
					                <thead>
					                <tr class="hide" style="border:1px solid #000;">
					                	<td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
					                </tr>
					                <tr class="style" align="center" >
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("BRANCH_NAME");?>&nbsp;</td>
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("CUSTOMER_NAME");?>&nbsp;</td>
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("PROPERTY_CODE");?>&nbsp;</td>  
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("PAYMENT_TYPE");?>&nbsp;</td>
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("AMOUNT_COLLECT");?>&nbsp;</td>		
					                    <td colspan="5" class="center">&nbsp;<?php echo $tr->translate("TOTAL_PAYMENTED");?>&nbsp;</td>    
					                    <td rowspan="2" class="center" style="white-space:nowrap; border-right:3px double black; ">&nbsp;<?php echo $tr->translate("PAY_DATE");?>&nbsp;</td>
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("INPUT_DATE");?>&nbsp;</td>
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("RECIEPT_NO");?>&nbsp;</td>
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("PAYMENT_OPTION");?>&nbsp;</td>
					                    <td rowspan="2" class="center">&nbsp;<?php echo $tr->translate("BY_USER");?>&nbsp;</td>
					                </tr>
					                <tr class="style" align="center">
					                	<td style="padding:1px;">&nbsp;<?php echo $tr->translate("PRINCIPAL");?>&nbsp;</td>                   
					                    <td style="padding:1px;">&nbsp;<?php echo $tr->translate("INTEREST");?>&nbsp;</td>
					                    <td style="padding:1px;">&nbsp;<?php echo $tr->translate("PENALIZE AMOUNT");?>&nbsp;</td>
					                    <td style="padding:1px;">&nbsp;<?php echo $tr->translate("EXTRA_PAYMENT");?>&nbsp;</td>	                    
					                    <td style="padding:1px;">&nbsp;<?php echo $tr->translate("TOTAL");?>&nbsp;</td>
					                </tr>
					            </thead>
				                <?php 
				                	$total_cash = 0;$total_cheque = 0;$total_bank = 0;
				                	$amt_d1 = 0;
				                	$amt_d2 = 0;
				                	$amt_d3 = 0;
				                	$amt_d4 = 0;
				                	$amt_d5 = 0;
				                	$total_d=0;
				                	$i=1;
				                ?>
				                <?php 
				                if(!empty($this->loantotalcollect_list)) foreach ($this->loantotalcollect_list as $index => $rs){ ?>
				               <?php 
									$amt_d1 = $amt_d1+$rs['total_principal_permonthpaid'];
									$amt_d2 = $amt_d2+$rs['total_interest_permonthpaid'];
									$amt_d3 = $amt_d3+$rs['penalize_amountpaid'];
									$amt_d5 = $amt_d5+$rs['extra_payment'];
									$total_d=$amt_d1+$amt_d2+$amt_d3+$amt_d5;
									if($rs['payment_methodid']==1){
										$total_cash = $total_cash + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
									}elseif($rs['payment_methodid']==2){
										$total_bank = $total_bank  + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
									}else{
										$total_cheque = $total_cheque + $rs['total_principal_permonthpaid']+$rs['total_interest_permonthpaid']+$rs['penalize_amountpaid']+$rs['extra_payment'];
									}
				               ?>
				                <tr class="style style1" style="font-family: 'Khmer OS Content'; white-space:nowrap; ">
				               		<td style="text-align: center;">&nbsp;<?php echo $i++; ?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["branch_name"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["name_kh"];?>&nbsp;</td>                 		
				               		<td style="max-width:170px;white-space: pre-wrap;word-wrap: break-word;white-space: normal;">&nbsp;<?php echo $rs["land_address"].",".$rs["street"];?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["payment_method"];?>&nbsp;</td>
				               		<td align="center">&nbsp;<?php echo $rs["payment_times"];?>&nbsp;</td>
				               		<td align="right" style="font:bolder 11px Arial;padding:0px 1px;">&nbsp;<?php echo number_format($rs['total_principal_permonthpaid'],2);?>&nbsp;</td>               		
				               		<td align="right" style="font:bolder 11px Arial;padding:0px 1px;">&nbsp;<?php echo number_format($rs['total_interest_permonthpaid'],2);?>&nbsp;</td>
				               		<td align="right" style="font:bolder 11px Arial;padding:0px 1px;">&nbsp;<?php echo number_format($rs['penalize_amountpaid'],2);?>&nbsp;</td>
				               		<td align="right" style="font:bolder 11px Arial;padding:0px 1px;">&nbsp;<?php echo number_format($rs['extra_payment'],2);?>&nbsp;</td>
				               		<td align="right" style="font:bolder 11px Arial;">&nbsp;<?php echo number_format($rs['amount_payment'],2);?>&nbsp;</td>
				               		<td align="center" style="white-space:nowrap; border-right:3px double black; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_payment"]));?>&nbsp;</td>
				               		<td align="center" style="white-space:nowrap; ">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_pay"]));?>&nbsp;</td>
				               		<td>&nbsp;<?php echo $rs["receipt_no"];?>&nbsp;</td>
				               		<td style="white-space: nowrap;font-site:9px; <?php if($rs["payment_option"]==4){echo " background:#ccc";} ?>" align="center" >&nbsp;
									<a target="_blank" style="color:#000; text-decoration: none;" href="<?php echo $url_receipt.'/id/'.$rs["id"];?>">
									<?php echo $rs["paymentoption"];?></a>
									</td>
				               		<td align="center">&nbsp;<?php echo $rs['user_name']?>&nbsp;</td>
				                </tr>
				                <?php }?>
				            </table>
				            <br />
				             <table class="tb-footer" border="1"​ width="100%" cellspacing="0">
				                 <tr align="center" bgcolor="#c1d0f3" >
				                    <td><?php echo $tr->translate("PRINCIPAL");?></td>                    
				                    <td><?php echo $tr->translate("TOTAL_INTEREST");?></td>
				                    <td><?php echo $tr->translate("TOTAL_PENILIZE_AMOUNT");?></td>
				                    <td><?php echo $tr->translate("EXTRA_PAYMENT");?></td>
				                    <td><?php echo $tr->translate("TOTAL");?></td>
				                    <td rowspan="2">ចំណូលតាមប្រភេទ</td>
				                    <td><?php echo $tr->translate("CASH");?></td>
				                    <td><?php echo $tr->translate("PAYWITH_BANK");?></td>
				                    <td><?php echo $tr->translate("CHEQUE");?></td>
				                </tr>
				                 <tr >
				                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d1,2);?>&nbsp;</td>
				                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d2,2);?>&nbsp;</td>
				                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d3,2);?>&nbsp;</td>
				                    <td>&nbsp;&nbsp;<?php echo number_format($amt_d5,2);?>&nbsp;</td>
				                    <td>&nbsp;&nbsp;<?php echo number_format($total_d,2);?>&nbsp;</td>
				                    <td>&nbsp;&nbsp;<?php echo number_format($total_cash,2);?>&nbsp;</td>
				                    <td>&nbsp;&nbsp;<?php echo number_format($total_bank,2);?>&nbsp;</td>
				                    <td>&nbsp;&nbsp;<?php echo number_format($total_cheque,2);?>&nbsp;</td>
				                </tr>
				              </table>
				              <br />
				               <table align="center" width="100%">
								   <tr style="font-size: 14px;">
								        <td style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
								        <td></td>
								        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
								        <td></td>
								        <td style="width:20%;text-align:center;font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
								   </tr>
							</table>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
	var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
	require(["dojo/ready"], function(ready){
		ready(function(){
			 getAllPropertyBranch();
		});
		new dijit.form.FilteringSelect({
			store: property_store,
			required: false,
			autoComplete: false,
			queryExpr: "*${0}*",
			name: "land_id",
			id: "land_id",
			value:-1,
			searchAttr: "name",
			class: 'fullside fullside50',
			onChange: function() {
				land_id=-1;
		}
			}, "land_id");
	});
	land_id = '<?php echo $this->rssearch['land_id']?>';
	var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
	function getAllPropertyBranch(branch_id){
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id<0){
			return false;
		}
		dojo.xhrPost({
			url:url_getland,	
			content:{ 
			    'branch_id':branch_id,
			    'action':1
			},		    
			handleAs:"json",
			load: function(data) {
				property_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('land_id').set('store', property_store);
			    if(land_id>0){
			    	dijit.byId('land_id').attr('value',land_id);
				 }
			},
			error: function(err) {
			}
		});
	}
</script>