<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$frm = $this->frm_property;

$dbGB = new Application_Model_DbTable_DbGlobal();
$logo = $this->baseUrl()."/images/logo.jpg";
$branch_title = $tr->translate("BRAND_TITLE");
if ($this->list_end_date['branch_id'] >0 ){
	$branch = $dbGB->getAllBranchInfoByID($this->list_end_date['branch_id']);
	if(file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
		$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
	}
	$branch_title = $branch['project_name'];
}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("REPORT_PROPERTY_PRICE");?></title>
<div class="reportblog">
<form name="frm_rptstaff" action="" dojoType="dijit.form.Form" method="post">
	<table style="margin: 0 auto;width: 100%;">
		 <tr> 
			  <td><?php echo $frm->getElement("adv_search");?></td>
			  <td><?php echo $frm->getElement("branch_id");?></td>
			  <td><?php echo $frm->getElement("streetlist");?></td>
			  <td><?php echo $frm->getElement("property_type");?></td>
	   	  </tr>
	   	  <tr>
	   	  	  <td><?php echo $frm->getElement("type_property_sale");?></td>
		   	  <td><?php echo $frm->getElement('start_date');?></td>
		      <td><?php echo $frm->getElement('end_date');?></td>
		      <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button"  type="submit" name="btn_search" ><?php echo $tr->translate("SEARCH");?></button>
			  </td>
		   </tr>
	</table>
 </form> 
<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
	<tr>
    	<td align="center">
    	 <div id="divPrint">
    	 	<style>
			.style{
				line-height: 20px;font-size: 11px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
				}
				th{padding: 5px;}
				.hover:hover{background: #ccc;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
				table.content-data { page-break-inside:auto }
				table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
			table.content-data{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:13px;
				font-family: 'Times New Roman','Khmer OS Battambang';
				white-space: nowrap;
				line-height: 22px;
				width: 100%;
			}
			table.content-data thead tr.style {
			   line-height: 25px; font-size:13px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #c1d0f3;
			}
			table.tb-footer{
				border-collapse:collapse;
				border:1px solid #000; 
				font-family: 'Times New Roman','Khmer OS Battambang';
				font-size:11px;
			}
			table.tb-footer tr{
			 line-height: 14px;  padding:2px 0px; height: 25px;
			}			
.border_bottom {
    border-bottom: 1px solid #000;
}
 		</style>
	<div class="divFooter">
	    <table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;" >
	        <tr>
	          	<td width="30%"><img src="<?php echo $logo;?>" style="height:80px;max-width: 100%;"></td>
	              <td width="40%" valign="top">
	                <ul>
	                	<li style="white-space:nowrap;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $branch_title;?></li>
	                	<li style="white-space:nowrap;text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("REPORT_PROPERTY_PRICE");?></li>
	                	<li style="text-align:center; font-size:14px;"><?php if(!empty($this->list_end_date['start_date'])){ echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';}echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));?></li>
		            </ul>
		           </td>
	               <td width="30%"></td>
	         </tr> 
	   </table>
	</div>
     <table id="exportExcel" class="content-data" width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0; padding:0; border:1px solid #000; border-collapse: collapse;" >
		<?php
		   $all_totalland = 0;$all_totalhouse =0;$all_total=0;$all_propertype=0;
	       $total_land_pric=0; $total_house_price = 0; $property_type=0; $i=0; $total=0;
	       $is_lock=0; 
	       if(!empty($this->row))foreach($this->row as $key =>$row){?>
	     <?php  
	      	$all_totalhouse=$all_totalhouse+$row['house_price'];
	      	$all_total=$all_total+$row['price'];
	      	$all_propertype = $key+1;
			if($row['property_type']!=$property_type){	
				if($key>0 ){
			?>
			<tr >
				<td colspan="10" style="border: solid 1px #000;background: #c1d0f3;padding: 0 10px;">
					<span class="border_bottom"><?php echo $tr->translate("TOTAL_PROPERTY");?></span>&nbsp;&nbsp;: <?php echo $i;?>
				</td>
			</tr>
				<?php $i=0; $total_land_pric=0;$total_house_price=0;$total_house_price=0;$total=0;}?>
		     <thead>
		     	<tr bgcolor="#c1d0f3" class="style hover" align="center"  >
					<td style="border:1px solid #000;"><?php echo $tr->translate("NUM");?></td>
					<td  style="border:1px solid #000;"><?php echo $tr->translate("BRANCH_NAME");?></td>
					<td style="border:1px solid #000;"><?php echo $tr->translate("PROPERTY_CODE");?></td>
					<td style="border:1px solid #000;"><?php echo $tr->translate("STREET_NO");?></td>
					<td style="border:1px solid #000;"><?php echo $tr->translate("PROPERTY_TYPE");?></td>
					<td style="border:1px solid #000;"><?php echo $tr->translate("OLD_PRICE");?></td>
					<td style="border:1px solid #000;"><?php echo $tr->translate("NEW_PRICE");?></td>
					<td style="border:1px solid #000;"><?php echo $tr->translate("NOTE");?></td>
					<td style="border:1px solid #000;"><?php echo $tr->translate("UPDATE_DATE");?></td>
					<td style="border:1px solid #000;"><?php echo $tr->translate("BY_USER");?></td>
				</tr>
			</thead>
			<?php }  $i++;?>
			   <tr class="hover" style="font-size: 12px;border:1px solid #000; white-space: nowrap;line-height: 25px;" align="left">
			     <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $i; ?></td>
			     <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
			     <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $row['land_address'];?>&nbsp;</td>
				 <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $row['street'];?>&nbsp;</td>
				 <td style="border:1px solid #000;">&nbsp;<?php echo $row['pro_type'];?></td>
				 <td align="center" style="border:1px solid #000;">&nbsp;<?php echo number_format($row['old_price'],2);?>&nbsp;</td>
				 <td align="center" style="border:1px solid #000;">&nbsp;<?php echo number_format($row['price'],2);?>&nbsp;</td>
				 <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $row['note'];?>&nbsp;</td>
				 <td align="center" style="border:1px solid #000;">&nbsp;<?php echo date("d-m-Y",strtotime($row['update_date']));?>&nbsp;</td>
				 <td align="center" style="border:1px solid #000;">&nbsp;<?php echo $row['user_name'];?>&nbsp;</td>
			 </tr>
				<?php $total = $total + $row['price'];
				$total_land_pric= $total_land_pric +$row['land_price'];
				$total_house_price= $total_house_price +$row['house_price'];
				$property_type = $row['property_type'];
				$all_totalland = $all_totalland+$row['land_price'];
				?>
			<?php }?>
	    </table>
	 </div>
	</td>
  </tr>
</table>
</div>