<?php 
	$filter = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
?>
<meta charset="utf-8">
	<script>
	dojo.require("dijit.form.DateTextBox");
	</script>
<title><?php echo $tr->translate("LOAN_DISBURSE");?></title>
<div style="min-height:26cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">
	<form method="post">
		<table width="100%">
			<tr>
				<td><?php echo $filter->getElement('adv_search');?></td>
				<td><?php echo $filter->getElement('branch_id');?></td>
				<td><input id="land_id" /></td>
				<td><?php echo $filter->getElement('client_name');?></td>
			</tr>
			<tr>
				<td><?php echo $filter->getElement('co_id');?></td>
				<td><?php echo $filter->getElement('property_type');?></td>
				<td><?php echo $filter->getElement('start_date');?></td>
				<td><?php echo $filter->getElement('end_date');?></td>
				<td align="left"><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button></td>
			</tr>
		</table>
	</form>
	<div id="divPrint" style="margin: 0 auto;">
	<style>
		.hover:hover{ background: #ccc;}
		.style{
			line-height: 20px;font-size: 14px !important;
			font-family:Arial,'Khmer OS Battambang';
		}
		table { page-break-inside:auto }
		tr{ page-break-inside:avoid; page-break-after:auto; }
		#header {
		  display: table-header-group;
		  page-break-inside:avoid; page-break-after:auto;
		}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
		th{padding: 5px;}
		.hover td{padding: 1px;}
		.hide{visibility: hidden;}
		@media print {
		  div.divFooter {
		    position: fixed;
		    top: 0;
		  	width: 100%;
		  	height: 100px;
		  	bottom:0px;
			margin:0;
		  }
		.hide{visibility: visible; height: 110px;}
		}
	</style>
	<table style="font-family: 'Khmer OS Content'; width:100%;">
		<tr>
	    	<td align="center">
	        	<div class="divFooter">
		        	<table width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';" style="margin:0; padding:0;border:none;">
		            	<tr>
		                	<td width="30%"><img src="<?php echo $logo;?>" height="85px"></td>
		                	<td width="40%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:18px; font-family:'Khmer OS Muol Light'"><?php echo $branch_title;?></li>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("MAKE_AGREEMENTLIST");?></li>
		                			<li style="text-align:center; font-size:16px;"><strong><?php if(!empty($this->list_end_date['start_date'])){echo date("d-M-Y",strtotime($this->list_end_date['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->list_end_date['end_date']));}?></strong></li>
		                			<li style="text-align:center; font-size:16px;"><?php if($this->branch_id>0){ echo $tr->translate("BRANCH_NAME").' '.@$this->loanrelease_list[0]['branch_name']; }?></li>
		                		</ul>
		                	</td>
		                    <td width="30%"></td>
		                </tr> 
		            </table>
	            </div>
	        </td>
	    </tr>
	    <tr>
	    	<td id="exportExcel">
	            <table border="1"​ style="font-family:'Times New Roman','Khmer OS Battambang'; border-collapse:collapse;border:1px solid #000; font-size:13px;" width="100%" cellspacing="0">
	               <thead>
	                 <tr class="hide" style="border:1px solid #000;">
		                <td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
		             </tr>
	                 <tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; ">
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
	                    <td rowspan="2"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
	                    <td rowspan="2"><?php echo $tr->translate("TEL");?></td>
	                    <td colspan="2"><?php echo $tr->translate("PROPERTY_INFO");?></td>
	                    <td colspan="5"><?php echo $tr->translate("INFO_INDILOAN");?></td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("LATE_DAY");?>&nbsp;</td>
	                    <td rowspan="2">&nbsp;<?php echo $tr->translate("BY_USER");?>&nbsp;</td>
	                </tr>
	                <tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold; line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; ">
	                    <td><?php echo $tr->translate("TYPE");?></td>
	                    <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
	                    <td><?php echo $tr->translate("SOLD_PRICE");?></td>
	                    <td><?php echo $tr->translate("PAID");?></td>
	                    <td><?php echo $tr->translate("BALANCE");?></td>
	                    <td><?php echo $tr->translate("BUY_DATE");?></td>
	                    <td><?php echo $tr->translate("DATE_MAKE_AGREEEMNT");?></td>
	                </tr>
	              </thead>
	               <?php 
	               $link="#";
	               $total_paid = 0;$total=0;$balance=0;$set_cancel=0;
	               $payment_0=0;$sold_price0=0;$paid_price0=0;$balace_price0=0;
	               $payment_1=0;
	               $sold_price1=0;
	               $paid_price1=0;
	               $balace_price1=0;
	               $payment_id='';
	               $db  = new Report_Model_DbTable_DbParamater();
	               if(!empty($this->loanrelease_list)) foreach($this->loanrelease_list as $key =>$row){?>
	               <?php 
	             if($row['is_cancel']==0){
	               if($row['payment_id']==1){
	               	 $payment_1=$payment_1+1;
	               	 $sold_price1=$sold_price1+$row['price_sold'];
	               	 $paid_price1=$paid_price1+$row['paid_amount'];
	               	 $balace_price1=$balace_price1+($row['price_sold']-$row['paid_amount']);
	               }
	              	$total=$total+$row['paid_amount'];
	              	$total_paid=$total_paid+$row['paid_amount'];
	              	$balance=$balance+($row['price_sold']-$row['paid_amount']);
	             } 
	             ?>
	             <?php 
	              	$payment_id = $row['payment_id']?>
	              	<tr <?php //if($row['payment_id']!=1){?>oncontextmenu="setrowdata(<?php echo $row['id'];?>);return false;" <?php //}?> style="line-height: 20px; white-space: nowrap;" class="hover context-menu-one">
						<td align="center">&nbsp;<?php echo $key+1; ?>&nbsp;</td>
						<td style="width: 100px; !important">&nbsp;<?php echo $row['name_kh'];?></td>
						<td style="line-height: 12px;white-space: normal !important;max-width: 100px;width: 120px;padding: 5px;overflow-wrap: break-word;"><?php echo $row['phone'];?></td>
						<td>&nbsp;<?php echo $row['propertype']; ?>&nbsp;</td>
						<td align="left">&nbsp;<?php echo $row['land_address']."(".$row['street'].")"; ?>&nbsp;</td>
						<td align="right" style="white-space:nowrap;">&nbsp;<?php echo number_format($row['price_sold']-$row['other_fee'],2); ?>&nbsp;</td>	
						<?php 
							$percent = $db->getFirstDepositBySaleID($row['id'],$row['payment_id']);
							$percent =$percent['percent'];
						?>
						<td style="white-space:nowrap; text-align: right;"><?php 
							if($row['payment_id']==4){
								$percent_paid =  number_format($row['paid_amount']/$row['price_sold']*100,2); 
								if($percent_paid>$percent)
								{
									echo"រំលស់";
								}else{
									echo"កក់បង្គ្រប់";
								}
							}elseif($row['payment_id']==1){
								echo number_format($row['paid_amount'],2);
							}
							$end_dat=date("Y-m-d");
							$total_day=strtotime($end_dat)-strtotime($row['end_line']);
							$total_late_day=$total_day/(60*60*24);
							
						?>&nbsp;</td>
						<td align="right" style="white-space:nowrap;">&nbsp;<?php echo number_format($row['price_sold']-$row['paid_amount'],2); ?>&nbsp;</td>
						<td align="center" style="white-space:nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($row['buy_date'])); ?>&nbsp;</td>
						<td align="center" style="white-space:nowrap;">&nbsp;<?php echo date("d-m-Y",strtotime($row['end_line']));?>&nbsp;</td>
						<td align="center" style="white-space:nowrap;">&nbsp;<?php echo $total_late_day;?>&nbsp;</td>
						<td style="white-space:nowrap;">&nbsp;<?php echo $row['user_name'];?>&nbsp;</td>
						</tr>
					<?php }?>
	            		<tr>
            				<td colspan="17" style=" border: #fff solid 1px; border-top: solid 1px #000;">
				             <br />
				             <table style="font-family: 'Times New Roman','Khmer OS Battambang'; border-collapse:collapse; font-size:14px;" width="100%" cellspacing="0">
				                <tr style=" line-height: 24px; ">
				                    <td>
				                    <div><span style="display: inline-block; min-width: 120px"><?php echo $tr->translate("SALE_AMOUNT");?></span>&nbsp;:&nbsp;<strong><?php echo $payment_1;?></strong></div>
				                    <div><span style="display: inline-block; min-width: 120px"><?php echo $tr->translate("TOTAL_INCASH");?></span>&nbsp;:&nbsp;<strong><?php echo number_format($sold_price1,2);?></strong></div>
				                    <div><span style="display: inline-block; min-width: 120px"><?php echo $tr->translate("TOTAL_PAYMENTED");?></span>&nbsp;:&nbsp;<strong><?php echo number_format($paid_price1,2);?></strong></div>
				                    <div><span style="display: inline-block; min-width: 120px"><?php echo $tr->translate("LOANOUTSTADING");?></span>&nbsp;:&nbsp;<strong><?php echo number_format($balace_price1,2);?></strong></div>
				                    </td>
				                </tr>
				              </table>
				             </td>
			            </tr>
	              </table>
	              <br />
	              <table align="center" width="100%">
					   <tr style="font-size: 14px;">
					        <td style="width:20%;text-align:center;  font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('APPROVED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('VERIFYED BY');?></td>
					        <td></td>
					        <td style="width:20%;text-align:center;font-family:'Khmer OS Muol Light'"><?php echo $tr->translate('PREPARE BY');?></td>
					   </tr>
				</table>	
	    	</td>
	    </tr>
	</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
	}, "land_id");		 
});
land_id = '<?php echo $this->rssearch['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
} 
</script>