<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$frmMaterial = $this->frmMaterial;
	$urlDetail = $this->baseUrl()."/report/loan/rpt-materialinlude-detail/id/";
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
	
	$montFomat="d-m-Y";
	if(MONTH_FORMATE_DATE_RECEIPT==1){
		$montFomat="d-M-Y";
	}
?>
<title><?php echo $tr->translate("RPT_MATERIAL_INCLUDE");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div class="reportblog">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_MATERIAL_INCLUDE');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<form method="post">
			<div class="card-box">
		    	<div class="form-group">
			   		<div class="col-md-3 col-sm-3 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-3 col-sm-3 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-3 col-sm-3 col-xs-12">
			   			<input id="land_id" />
			   		</div>
			   		<div class="col-md-3 col-sm-3 col-xs-12">
			   			<?php echo $frm->getElement('client_name');?>
			   		</div>
			   		<!-- <div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php //echo $frm->getElement('category_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php //echo $frm->getElement('payment_method');?>
			   		</div> -->
			   	</div>
			   	<div class="form-group">
					<div class="col-md-3 col-sm-3 col-xs-12">
			   			<?php echo $frmMaterial->getElement('items_id');?>
			   		</div>
			   		<div class="col-md-3 col-sm-3 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-3 col-sm-3 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-3 col-sm-3 col-xs-12">
			   			<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			   		</div>
			   	</div>
			</div>
		</form>
		<div style="width:100%; margin:0 auto;">
		<div style="min-height:22cm; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
			</style>
			<div id="divPrint">
				<style type="text/css">
					.style{
						line-height: 20px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table { page-break-inside:auto }
					tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
					 .hide{visibility: visible; height: 110px;}
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
					}
					table.content-data thead tr.style {
					   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
						background: #c1d0f3;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:13px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
				</style>
				<table width="100%">
					<tr>
				    	<td align="center" valign="top">
				        	<div class="divFooter">
					        	<table border="0" width="100%" style="font-family: 'Times New Roman','Khmer OS Battambang';"style="margin:0;padding:0;">
					            	<tr>
					                	<td width="30%" style="border:1px solid #fff;"><img src="<?php echo $logo;?>" height="80px"></td>
					                	<td width="40%" valign="top">
					                		<ul>
					                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $branch_title;?></li>
					                			<li style="text-align:center; font-size:<?php echo FONTSIZE_REPORT;?>; font-family:'Times New Roman','Khmer OS Muol Light';"><?php echo $tr->translate("RPT_MATERIAL_INCLUDE");?></li>
					                			<li style="text-align:center; font-size:16px;"><?php if($this->search['start_date']){echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));}?></li>
											</ul>
					                   </td>
					                    <td width="30%"></td>
					                </tr> 
					            </table>
				            </div>
				        </td>
				    </tr>
				    <tr>
				    	<td id="exportExcel">
				              <?php if(!empty($this->row)){?>
					            <table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
					            	<tr>	
					            	<td colspan="3" id="exportExcel">
					            		<table  class="content-data" border="1" width="100%"  >  
									    	<thead>
									    	<tr class="hide" style="border:1px solid #000;">
									             <td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
									        </tr>
									    	<tr class="style" align="center"  >
												<td><?php echo $tr->translate("NUM");?></td>
											    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
											    <td><?php echo $tr->translate("CLIENT_NAME");?></td>
											    <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
											    <td><?php echo $tr->translate("ITEMS");?></td>
											    <td><?php echo $tr->translate("NOTE");?></td>
											    <td><?php echo $tr->translate("DATE");?></td>
											    <td><?php echo $tr->translate("BY_USER");?></td>
											</tr>
											</thead>
									       <?php $branch_id=''; $n=0; $i=0; $total=0; if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
											<tr class="context-menu-one" oncontextmenu="setrowdata('<?php echo $row['id'];?>');return false;" align="left">
											   <td align="center">&nbsp;<?php echo $i; ?>&nbsp;</td>
											   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
											   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['client_name'];?>&nbsp;</td>
											   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $row['house_no'];?>&nbsp;</td>
											   <td align="center">&nbsp;<?php echo $row['itmesTitle'];?>&nbsp;</td>
											   <td>&nbsp;<?php echo $row['description'];?>&nbsp;</td>
											   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo date($montFomat,strtotime($row['for_date']));?>&nbsp;</td>
											    <td align="center">&nbsp;<?php echo $row['user_name'];?>&nbsp;</td>
											</tr>
											<?php }?>
									    </table>
					            	</td>
					            </tr>
				            </table>
							<br />
				            <?php }?>
				             <?php echo $this->footerReport;?>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
		}, "land_id");
});
land_id = '<?php echo $this->rssearch['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
}
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="detail"){
				url='<?php echo $urlDetail;?>';
			}  
			gotoAction();
		},
		items: {
			"detail": {name: "<?php echo $tr->translate("DETAIL");?>", icon: "edit", accesskey: "e"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row+'?rightclick=true', '_blank');
}
</script>