<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_search;
	$frmMaterial = $this->frmMaterial;
	$urlDetail = $this->baseUrl()."/report/loan/rpt-materialinlude-detail/id/";
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		$branch_title = $branch['project_name'];
	}
	
	$montFomat="d-m-Y";
	if(MONTH_FORMATE_DATE_RECEIPT==1){
		$montFomat="d-M-Y";
	}
	
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>
<title><?php echo $tr->translate("RPT_MATERIAL_INCLUDE");?></title>
<script>
     dojo.require("dijit.form.DateTextBox");
</script>
	<div class="reportblog">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RPT_MATERIAL_INCLUDE');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<form method="post">
			<div class="card-box">
		    	<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<input id="land_id" />
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('client_name');?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frmMaterial->getElement('items_id');?>
			   		</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frmMaterial->getElement('is_gived');?>
			   		</div>
			   	</div>
			   	<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			   		</div>
			   	</div>
			</div>
		</form>
		<div style="width:100%; margin:0 auto;">
		<div style="min-height:22cm; margin:0 auto;">
			<style>
				.hideblog{display: block !important;;border: 1px solid #fff; border-bottom: 1px solid #000;}
				.hiddenblog{display: block !important;}
			</style>
			<div id="divPrint">
				<style type="text/css">
					.style{
						line-height: 14px;font-size: 11px !important;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					.hideblog{display: none;}
					.hiddenblog{display: block !important;}
					.style1:hover{ background: #ccc; }
					table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
					table.content-data { page-break-inside:auto }
					table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
					#header {
					  display: table-header-group;
					  page-break-inside:avoid; page-break-after:auto;
					  margin-top: 100px;
					}
					.hide{visibility: hidden;}
					@media print {
					 div.divFooter {
					    position: fixed;
					    top: 0;
					  	width: 100%;
					  	height: 100px;
					  	bottom:0px;
						margin:0;
					  }
					 .hide{visibility: visible; height: 110px;}
					}
					.center{text-align: center !important;}
					table.content-data{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:11px;
					}
					table.content-data thead tr.style {
					   line-height: 14px; 
					   font-size:11px !important; 
					   padding:1px 0px; white-space: nowrap; 
						background: #c1d0f3;
					}
					table.tb-footer{
						border-collapse:collapse;
						border:1px solid #000; 
						font-size:11px;
						font-family: 'Times New Roman','Khmer OS Battambang';
					}
					table.tb-footer tr{
					 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
					}
					table tr td{
						padding:2px 2px;
					}
					tr.odd {
						background: #ededed;
					}
					span.noteValue{
						line-height: 12px;
						white-space: pre-wrap !important;
						max-width: 100px;
						width: 100px;
						padding: 1px;
						display: block;
						font-size: 90%;
						overflow-wrap: break-word;
						text-align: left;
						vertical-align: top;
					}
					span.smallClass{
						display: block; 
						line-height: 12px; 
						font-size:80%;
					}
						
				</style>
				<table width="100%">
					<tr>
						<td align="center">
							<div class="divFooter">
								<?php echo $this->headerReport;?>
							</div>
						</td>
					</tr>
				    <tr>
				    	<td id="exportExcel">
				              <?php if(!empty($this->row)){?>
					            <table width="100%" style="font-family:'Khmer OS Battambang';" style="margin:0; padding:0;border:none;" >
					            	<tr>	
					            	<td colspan="3" id="exportExcel">
					            		<table  class="content-data" border="1" width="100%"  >  
									    	<thead>
									    	<tr class="hide" style="border:1px solid #000;">
												<td colspan="12" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
											 </tr>
											 <tr class="style" align="center" >
												<td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?></td>
												<td scope="col" rowspan="2"><?php echo $tr->translate("BRANCH_NAME");?></td>
												  
												<td scope="col" colspan="2"><?php echo $tr->translate("SALE_INFO");?></td>   
												<td scope="col" colspan="4"><?php echo $tr->translate("materialIncludeInfo");?></td>   
												<td scope="col" rowspan="2"><?php echo $tr->translate("BY_USER");?></td>
											</tr>
									    	<tr class="style" align="center"  >
											    <td  scope="col"><?php echo $tr->translate("Customers");?></td>
											    <td  scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
												
											    <td  scope="col"><?php echo $tr->translate("material");?></td>
											    <td  scope="col"><?php echo $tr->translate("DATE");?></td>
											    <td  scope="col"><?php echo $tr->translate("NOTE");?></td>
											    <td  scope="col"><?php echo $tr->translate("STATUS");?></td>
											</tr>
											</thead>
									       <?php $branch_id=''; $n=0; $i=0; $total=0; if(!empty($this->row)) foreach($this->row as $key =>$row){ 
											   $i++;
											   $classRow = "";
												if(($i%2)==0){
													$classRow = "odd";
												}
										   ?>
											<tr class="context-menu-one <?php echo $classRow;?>" oncontextmenu="setrowdata('<?php echo $row['id'];?>');return false;" align="left">
											   <td data-label="<?php echo $tr->translate("NUM");?>" align="center"><?php echo $i; ?></td>
											   <td data-label="<?php echo $tr->translate("BRANCH_NAME");?>" style="white-space: nowrap;"><?php echo $row['branch_name'];?></td>
											   <td data-label="<?php echo $tr->translate("Customers");?>" style="white-space: nowrap;">
											   <?php echo $row['client_name'];?>
											   <?php 
												if(!empty($row['tel'])){ echo "<span class='smallClass' >".$row['tel']."</span>";}
												?>
											   </td>
											   <td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="left" style="white-space: nowrap;"><?php echo $row['house_no'];?></td>
											   <td data-label="<?php echo $tr->translate("material");?>" ><?php echo $row['itmesTitle'];?></td>
											   
												<td data-label="<?php echo $tr->translate("DATE");?>" align="center"  style="white-space: nowrap;"><?php echo date($montFomat,strtotime($row['for_date']));?></td>
											    <td data-label="<?php echo $tr->translate("NOTE");?>"><span class="noteValue" ><?php echo $row['description'];?></span></td>
												<td data-label="<?php echo $tr->translate("STATUS");?>" ><?php echo $row['isGiveLabel'];?></td>
											    <td data-label="<?php echo $tr->translate("BY_USER");?>" align="center"><?php echo $row['user_name'];?></td>
											</tr>
											<?php }?>
									    </table>
					            	</td>
					            </tr>
				            </table>
							<br />
				            <?php }?>
				             <?php echo $this->footerReport;?>
				    	</td>
				    </tr>
				</table>
			</div>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
		 
		getBranchInfo();
		document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
		document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("RPT_MATERIAL_INCLUDE");?>';
		document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
	
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
		}, "land_id");
});
land_id = '<?php echo $this->rssearch['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
}
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			if(key=="detail"){
				url='<?php echo $urlDetail;?>';
			}  
			gotoAction();
		},
		items: {
			"detail": {name: "<?php echo $tr->translate("MATERIAL_INCLUDE");?>", icon: "edit", accesskey: "e"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row+'?rightclick=true', '_blank');
}

function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>