<?php 
	$filter = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url = $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-groupmember'));
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>
<meta charset="utf-8">
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<title><?php echo $tr->translate("MAKE_AGREEMENTLIST");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i> <?php echo $tr->translate('MAKE_AGREEMENTLIST');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('adv_search');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('branch_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<input id="land_id" />
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('client_name');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('co_id');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('property_type');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('start_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<?php echo $filter->getElement('end_date');?>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
					<button class="button-class button-primary" iconClass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
				<div class="col-md-2 col-sm-2 col-xs-12">
				</div>
			</div>
		</div>
	</form>
	<div id="divPrint" style="margin: 0 auto;">
		<style>
			.style{
				line-height: 20px;font-size: 11px !important;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			.hideblog{display: none;}
			.hiddenblog{display: block !important;}
			.style1:hover{ background: #ccc; }
			table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
			table.content-data { page-break-inside:auto }
			table.content-data tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			  margin-top: 100px;
			}
			.hide{visibility: hidden;}
			@media print {
			 div.divFooter {
				position: fixed;
				top: 0;
				width: 100%;
				height: 100px;
				bottom:0px;
				margin:0;
			  }
				.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
				
			}
			.center{text-align: center !important;}
			table.content-data{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:8px;
			}
			table.content-data thead tr.style {
			   line-height: 25px; font-size:10px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
				background: #c1d0f3;
				font-weight:600;
			}
			table.tb-footer{
				border-collapse:collapse;
				border:1px solid #000; 
				font-size:11px;
				font-family: 'Times New Roman','Khmer OS Battambang';
			}
			table.tb-footer tr{
			 line-height: 14px; font-size:11px; padding:2px 0px; height: 25px;
			}
			table tr td{
				padding:0 2px;
			}
			tr.voidclass {
				background: #fff7f7;
			}
			td.centerText{
				text-align: center;
			}
			.redBold {
				font-weight: 600;
				color: #f80000;
			}
			table.content-data tr td{
				padding: 2px;
			}
		</style>
	<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;">
		<tr>
	    	<td align="center">
	        	<div class="divFooter">
		        	<?php echo $this->headerReport;?>
	            </div>
	        </td>
	    </tr>
	    <tr>
	    	<td id="exportExcel">
	            <table class="content-data" cellpadding="5" border="1" width="100%">
	               <thead>
	                 <tr class="hide" style="border:1px solid #000;">
		                <td colspan="17" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
		             </tr>
	                 <tr class="style" align="center" >
	                    <td scope="col" rowspan="2"><?php echo $tr->translate("NUM");?></td>
	                    <td scope="col" rowspan="2"><?php echo $tr->translate("CUSTOMER");?></td>
	                    <td scope="col" rowspan="2"><?php echo $tr->translate("TEL");?></td>
	                    <td scope="col" colspan="2"><?php echo $tr->translate("PROPERTY_INFO");?></td>
	                    <td scope="col" colspan="5"><?php echo $tr->translate("INFO_INDILOAN");?></td>
	                    <td scope="col" rowspan="2"><?php echo $tr->translate("LATE_DAY");?></td>
	                    <td scope="col" rowspan="2"><?php echo $tr->translate("BY_USER");?></td>
	                </tr>
	                <tr  class="style" align="center" >
	                    <td scope="col"><?php echo $tr->translate("TYPE");?></td>
	                    <td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
	                    <td scope="col"><?php echo $tr->translate("SOLD_PRICE");?></td>
	                    <td scope="col"><?php echo $tr->translate("PAID");?></td>
	                    <td scope="col"><?php echo $tr->translate("BALANCE");?></td>
	                    <td scope="col"><?php echo $tr->translate("BUY_DATE");?></td>
	                    <td scope="col"><?php echo $tr->translate("DATE_MAKE_AGREEEMNT");?></td>
	                </tr>
	              </thead>
	               <?php 
	               $amount_property=0;
	               $link="#";
	               $total_paid = 0;$total=0;$balance=0;$set_cancel=0;
	               $payment_0=0;$sold_price0=0;$paid_price0=0;$balace_price0=0;
	               $payment_1=0;
	               $sold_price1=0;
	               $paid_price1=0;
	               $balace_price1=0;
	               $payment_id='';
	               $db  = new Report_Model_DbTable_DbParamater();
	               if(!empty($this->loanrelease_list)) foreach($this->loanrelease_list as $key =>$row){?>
	               <?php 
	             if($row['is_cancel']==0){
	             	
	               if($row['payment_id']==1){
	               	 $payment_1=$payment_1+1;
	               	 $sold_price1=$sold_price1+$row['price_sold'];
	               	 $paid_price1=$paid_price1+$row['paid_amount'];
	               	 $balace_price1=$balace_price1+($row['price_sold']-$row['paid_amount']);
	               }
	              	$total=$total+$row['paid_amount'];
	              	$total_paid=$total_paid+$row['paid_amount'];
	              	$balance=$balance+($row['price_sold']-$row['paid_amount']);
	             } 
	             
	             if (!empty($row['old_land_id'])){
	             	$idse = explode(",", $row['old_land_id']);
	             	$countland = count($idse);
	             	$amount_property = $amount_property+$countland;
	             }else{
	             	$amount_property = $amount_property+1;
	             }
	             ?>
	             <?php 
	              	$payment_id = $row['payment_id']?>
	              	<tr oncontextmenu="setrowdata(<?php echo $row['id'];?>);return false;" class="hover style context-menu-one">
						<td data-label="<?php echo $tr->translate("NUM");?>" align="center"><?php echo $key+1; ?></td>
						<td  data-label="<?php echo $tr->translate("CUSTOMER_NAME");?>"><?php echo $row['name_kh'];?></td>
						<td data-label="<?php echo $tr->translate("TEL");?>" style="line-height: 16px; white-space: normal !important;max-width: 100px;width: 120px;padding: 5px;overflow-wrap: break-word;"><?php echo $row['phone'];?></td>
						<td data-label="<?php echo $tr->translate("TYPE");?>" align="center"><?php echo $row['propertype']; ?></td>
						<td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="left"><?php echo $row['land_address']."(".$row['street'].")"; ?></td>
						<td data-label="<?php echo $tr->translate("SOLD_PRICE");?>" align="right" style="white-space:nowrap;"><?php echo number_format($row['price_sold'],2); ?></td>	
						<?php 
							$percent = $db->getFirstDepositBySaleID($row['id'],$row['payment_id']);
							$percent =$percent['percent'];
						?>
						<td data-label="<?php echo $tr->translate("PAID");?>" style="white-space:nowrap; text-align: right;"><?php 
						
							if($row['payment_id']==4){
								$percent_paid =  number_format($row['paid_amount']/$row['price_sold']*100,2);
							}elseif($row['payment_id']==1){
								echo number_format($row['paid_amount'],2);
							}else{
								echo number_format($row['paid_amount'],2);
							}
						
							$end_dat=date("Y-m-d");
							$total_day=strtotime($end_dat)-strtotime($row['end_line']);
							$total_late_day=$total_day/(60*60*24);
							
						?></td>
						<td data-label="<?php echo $tr->translate("BALANCE");?>" align="right" style="white-space:nowrap;"><?php echo number_format($row['price_sold']-$row['paid_amount'],2); ?></td>
						<td data-label="<?php echo $tr->translate("BUY_DATE");?>" align="center" style="white-space:nowrap;"><?php echo date("d-m-Y",strtotime($row['buy_date'])); ?></td>
						<td data-label="<?php echo $tr->translate("DATE_MAKE_AGREEEMNT");?>" align="center" style="white-space:nowrap;"><?php echo date("d-m-Y",strtotime($row['end_line']));?></td>
						<td data-label="<?php echo $tr->translate("LATE_DAY");?>" align="center" style="white-space:nowrap;"><?php echo $total_late_day;?></td>
						<td data-label="<?php echo $tr->translate("BY_USER");?>" style="white-space:nowrap;"><?php echo $row['user_name'];?></td>
						</tr>
					<?php }?>
	            		<tr>
            				<td colspan="17" style=" border: #fff solid 1px; border-top: solid 1px #000;">
				             <br />
				             <table style=" font-size:11px;width:70%;margin:0 auto;" cellspacing="0">
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
				                    <td align="right"><?php echo $tr->translate("PROPERTY");?></td>
				                    <td><?php echo $amount_property;?></td>
				                    <td align="right"></td>
				                    <td></td>
				                    <td></td>
				                    <td></td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
				                    <td align="right"><?php echo $tr->translate("SALE_AMOUNT");?></td>
				                    <td><?php echo $payment_1;?></td>
				                    <td align="right"></td>
				                    <td></td>
				                    <td></td>
				                    <td></td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
				                    <td align="right"><?php echo $tr->translate("TOTAL_INCASH");?>$</td>
				                    <td><?php echo number_format($sold_price1,2);?></td>
				                    <td align="right"></td>
				                    <td></td>
				                    <td></td>
				                    <td></td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
				                    <td align="right"><?php echo $tr->translate("TOTAL_PAYMENTED");?>$</td>
				                    <td><?php echo number_format($paid_price1,2);?></td>
				                    <td align="right"><?php //echo $tr->translate("រំលស់");?></td>
				                    <td><?php //echo $payment_3;?></td>
				                    <td><?php //echo $payment_3_completed;?></td>
				                    <td><?php //echo $payment_3-$payment_3_completed;?></td>
				                 </tr>
				                 <tr bgcolor="#a0baf5" class="style" style="line-height: 14px; font-size:14px; padding:2px 0px; height: 25px;">
				                    <td align="right"><?php echo $tr->translate("LOANOUTSTADING");?>$</td>
				                    <td><?php echo number_format($balace_price1,2);?></td>
				                    <td align="right"><?php //echo $tr->translate("រំលស់");?></td>
				                    <td><?php //echo $payment_3;?></td>
				                    <td><?php //echo $payment_3_completed;?></td>
				                    <td><?php //echo $payment_3-$payment_3_completed;?></td>
				                 </tr>
			                 </table>
			                <!-- 
			                 <br />
				             <table style="font-family: 'Times New Roman','Khmer OS Battambang'; border-collapse:collapse; font-size:14px;" width="100%" cellspacing="0">
				                <tr style=" line-height: 24px; ">
				                    <td>
				                    <div><span style="display: inline-block; min-width: 120px"><?php //echo $tr->translate("PROPERTY");?></span>:<strong><?php //echo $amount_property;?></strong></div>
				                    <div><span style="display: inline-block; min-width: 120px"><?php //echo $tr->translate("SALE_AMOUNT");?></span>:<strong><?php //echo $payment_1;?></strong></div>
				                    <div><span style="display: inline-block; min-width: 120px"><?php //echo $tr->translate("TOTAL_INCASH");?></span>:<strong><?php //echo number_format($sold_price1,2);?></strong></div>
				                    <div><span style="display: inline-block; min-width: 120px"><?php //echo $tr->translate("TOTAL_PAYMENTED");?></span>:<strong><?php //echo number_format($paid_price1,2);?></strong></div>
				                    <div><span style="display: inline-block; min-width: 120px"><?php //echo $tr->translate("LOANOUTSTADING");?></span>:<strong><?php //echo number_format($balace_price1,2);?></strong></div>
				                    </td>
				                </tr>
				              </table>
			                 -->
				             </td>
			            </tr>
	              </table>
	              <br />
	              <?php echo $this->footerReport;?>
	    	</td>
	    </tr>
	</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		 getAllPropertyBranch();
		 <?php if(!empty($this->search['end_date'])){?>
		 dijit.byId('end_date').attr('value','<?php echo date('Y-m-d',strtotime($this->search['end_date'])); ?>');
		 <?php }?>
		 
		  getBranchInfo();
		 document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
		 document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("MAKE_AGREEMENTLIST");?>';
		 document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['start_date'])){ if( date("Y-m-d",strtotime($this->search['start_date']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['start_date'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['end_date']));} }else{ echo date("d-M-Y",strtotime($this->search['end_date'])); }?>';
	
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
	}, "land_id");		 
});
land_id = '<?php echo $this->rssearch['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
}
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>