<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_cancel;
	
	$dbGB = new Application_Model_DbTable_DbGlobal();
	$logo = $this->baseUrl()."/images/logo.jpg";
	$branch_title = $tr->translate("BRAND_TITLE");
	if ($this->search['branch_id'] >0 ){
		$branch = $dbGB->getAllBranchInfoByID($this->search['branch_id']);
		if (file_exists(PUBLIC_PATH."/images/projects/".$branch["logo"])){
			$logo = $this->baseUrl()."/images/projects/".$branch["logo"];
		}
		//$branch_title = $branch['project_name'];
	}
	$headerReportType = REPORT_LETER_HEAD;
	$classHideHeight="110px";
	if($headerReportType==2){
		$classHideHeight="125px";
	}
?>
<script>
	dojo.require("dijit.form.DateTextBox");
</script>
<meta charset="utf-8">
<title><?php echo $tr->translate("RECEIVED_TITLE_REPORT");?></title>
<div class="reportblog">
	<div class="card-box">
       	<div class="col-sm-12 border-botom">
	   		<div class="col-sm-8 pd-0">
	    		<h4 class="m-b-0"><i class="fa fa-file" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('RECEIVED_TITLE_REPORT');?></h4>
    		</div>
    		<div class="col-sm-4 text-right">
    		</div>
    	</div>
    </div>
	<form name="frm_rptstaff" action="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-receiveplong')); ?>" dojoType="dijit.form.Form" method="post">
		<div class="card-box">
	    	<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('adv_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('branch_id');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<input id="land_id" />
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('client_name');?>
				</div>
			</div>
			<div class="form-group"> 
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('plong_type');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('from_date_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<?php echo $frm->getElement('to_date_search');?>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
				</div>
			</div>
		</div>
	</form> 
	<div style="min-height:22cm; margin:0 auto;">
		<table style="font-family: 'Times New Roman','Khmer OS Battambang'; width:100%;"  >
			<tr>
		    	<td align="center">
		    	 <div id="divPrint">
		    	 	<style>
						.style{
							line-height: 20px;font-size: 12px !important;
							font-family: 'Times New Roman','Khmer OS Battambang';
						}
						th{padding: 5px;}
						table.content-data{
							border-collapse:collapse;
							border:1px solid #000; 
							font-size:12px;
							font-family: 'Times New Roman','Khmer OS Battambang';
							white-space: nowrap;
							line-height: 22px;
							width: 100%;
						}
						table.content-data thead tr.style {
						   line-height: 25px; font-size:12px !important; padding:1px 0px; white-space: nowrap;height: 22px; 
							background: #c1d0f3;
							
						}
						table.content-data thead tr.style td {
							height: 20px;
						}
						table.tb-footer{
							border-collapse:collapse;
							border:1px solid #000; 
							font-family: 'Times New Roman','Khmer OS Battambang';
							font-size:11px;
						}
						table.tb-footer tr{
						 line-height: 14px;  padding:2px 0px; height: 25px;
						}
						.hide{visibility: hidden;}
						@media print {
						 div.divFooter {
							position: fixed;
							top: 0;
							width: 100%;
							height: 100px;
							bottom:0px;
							margin:0;
						  }
							.hide{visibility: visible; height: <?php echo $classHideHeight;?>;}
						}
					
					</style>
					<div class="divFooter">
						<?php echo $this->headerReport;?>
					</div>
		        	<table width="100%" style="font-family:'Times New Roman','Khmer OS Battambang';margin:0; padding:0;border:none;" >
			        	
			            <tr>
			            	<td colspan="3">
			            		<table id="exportExcel" class="content-data" width="100%" border="1" >  
							      	<thead>
										<tr class="hide" style="border:1px solid #000;">
											<td colspan="10" style="border:1px solid #fff;border-bottom:1px solid #000;"></td>
										</tr>
							      		<tr bgcolor="#a0baf5" class="style" align="center"  >
											<td scope="col"><?php echo $tr->translate("NUM");?></td>
											<td scope="col"><?php echo $tr->translate("PROJECT_NAME");?></td>
											<td scope="col"><?php echo $tr->translate("CUSTOMER_NAME");?></td>
											<td scope="col"><?php echo $tr->translate("PROPERTY_TYPE");?></td>
											<td scope="col"><?php echo $tr->translate("PROPERTY_CODE");?></td>
							                <td scope="col"><?php echo $tr->translate("STREET");?></td>
							                <td scope="col"><?php echo $tr->translate("HEAD_TITLE_NO");?></td>
							                <td scope="col"><?php echo $tr->translate("LAYOUT_TYPE");?></td>
											<td scope="col"><?php echo $tr->translate("RECEIVED_DATE");?></td>
							                <td scope="col"><?php echo $tr->translate("NOTE");?></td>
										</tr>
							      	</thead>
							       <?php $property_type=''; $i=0;
							       if(!empty($this->row))foreach($this->row as $key =>$row){ $i++;?>
									<?php 
										$property_type= $row['property_type'];
									?>
									   <tr  align="left">
									     <td data-label="<?php echo $tr->translate("NUM");?>" align="center">&nbsp;<?php echo $i; ?></td>
									     <td data-label="<?php echo $tr->translate("PROJECT_NAME");?>">&nbsp;<?php echo $row['branch_name'];?></td>
									     <td data-label="<?php echo $tr->translate("CUSTOMER_NAME");?>" align="center">&nbsp;<?php echo $row['client_name'];?></td>
										 <td data-label="<?php echo $tr->translate("PROPERTY_TYPE");?>" align="center">&nbsp;<?php echo $row['property_type'];?></td>
										 <td data-label="<?php echo $tr->translate("PROPERTY_CODE");?>" align="center">&nbsp;<?php echo $row['land_address'];?></td>
										 <td data-label="<?php echo $tr->translate("STREET");?>" align="center">&nbsp;<?php echo $row['street'];?></td>
										 <td data-label="<?php echo $tr->translate("HEAD_TITLE_NO");?>" align="center">&nbsp;<?php echo $row['hardtitle'];?></td>
										 <td data-label="<?php echo $tr->translate("LAYOUT_TYPE");?>" align="center">&nbsp;<a style=" text-decoration: none;" target="_blank" href="<?php echo $this->url(array('module'=>'report','controller'=>'loan','action'=>'rpt-printplong','id'=>$row['id']));?>"><?php echo $row['layout_type'];?></a></td>
										 <td data-label="<?php echo $tr->translate("RECEIVED_DATE");?>" align="left" style="font-size: 12px;">&nbsp;<?php echo date("d-m-Y",strtotime($row['date']));?></td>
										 <td data-label="<?php echo $tr->translate("NOTE");?>" align="center">&nbsp;<?php echo $row['note'];?> </td>
									  </tr>
									<?php 
							       }?>
							    </table>
							    <br />
							   <?php echo $this->footerReport;?>
			            	</td>
			            </tr>
		            </table>
		            </div>
		    	</td>
		    </tr>
		</table>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
require(["dojo/ready"], function(ready){
	ready(function(){
		getSaleClie();
		getBranchInfo();
		document.getElementById('companyTitle').innerHTML = '<?php echo $branch_title; ?>';
		document.getElementById('reportTitle').innerHTML = '<?php echo $tr->translate("RECEIVED_TITLE_REPORT");?>';
		document.getElementById('dateReport').innerHTML = '<?php if(!empty($this->search['from_date_search'])){ if( date("Y-m-d",strtotime($this->search['from_date_search']))==date("Y-m-d") ){ echo date("d-M-Y"); }else{ echo date("d-M-Y",strtotime($this->search['from_date_search'])).' '.$tr->translate('TO').' ';echo date("D-d-M-Y",strtotime($this->search['to_date_search']));} }else{ echo date("d-M-Y",strtotime($this->search['to_date_search'])); }?>';
		 
	});
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
		}, "land_id");
});
land_id = '<?php echo $this->search['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getSaleClie(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
} 
function getSaleNo(){
}
function getBranchInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = '<?php echo empty($this->search['branch_id'])?0:$this->search['branch_id'];?>';
	if(branch_id=="" || branch_id<=0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			var arr = JSON.parse(data);
			var imagesUrl = '<img  style="height:85px; max-width: 100%;" src="'+arr.url_logo+'" />';
			document.getElementById('projectlogo').innerHTML = imagesUrl;	
			
			<?php if($headerReportType==2){?>
			document.getElementById('projectName').innerHTML = '('+arr.project_name+')';
			<?php }else{?>
			document.getElementById('projectName').innerHTML = arr.project_name;
			<?php }?>
		},
		error: function(e) {
		}
	});
}
</script>