<?php 
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
     $frm = $this->frm;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<title><?php echo $this->tr->translate("APPROVED_REQUEST_PO")?></title>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('APPROVED_REQUEST_PO');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id=='' || branch_id<=0){
						alert('<?php echo $tr->translate('PLEASE_SELECT_BRANCH');?>');
						dijit.byId('branch_id').focus();
						return false;
					}
					var rowId = $('#identity').val();
					if(rowId==''){ 
						alert("<?php echo $tr->translate("PLEASE_ADD_RECORD");?>");
						return false;
					}
					loadingBlock();
					return true;
	  			 }else {
					return false;
	   			}
			</script>
			<div class="card-box">
				
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div class="form-group">
							<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("FEEDBACK");?> </label>
							<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $frm->getElement("approveNote");?>
							</div>
						 </div>
						 <div class="form-group">
							<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DATE");?> </label>
							<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $frm->getElement("approveDate");?>
							</div>
						 </div>	
						<div class="form-group">
							<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
							<div class="col-md-7 col-sm-7 col-xs-12">
								<?php echo $frm->getElement("approveStatus");?>
								<?php echo $frm->getElement("id");?>
							</div>
						 </div>	
					</div>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div id="request-info">
							<div class="form-group" style=" padding: 10px; ">
								<span class="note_score"><i class="fa fa-file-text-o" aria-hidden="true"></i> ព័ត៌មានសំណើបញ្ជាទិញទំនិញ</span>
								<ul>
									<li><span class="lbl-tt"><?php echo $tr->translate("BRANCH_NAME");?></span>: <span class="red"><?php echo $this->row['branch_name'];?></span></li>
									<li><span class="lbl-tt"><?php echo $tr->translate("REQUEST_NO");?></span>: <span class="red"><?php echo $this->row['requestNo'];?></span></li>
									<li><span class="lbl-tt"><?php echo $tr->translate("REQUEST_NO_FROM");?></span>: <span class="red"><?php echo $this->row['requestNoLetter'];?></span></li>
									<li><span class="lbl-tt"><?php echo $tr->translate("REQUEST_DATE");?></span>: <span class="red"><?php echo date("d-M-Y",strtotime($this->row['date']));?></span></li>
									<li><span class="lbl-tt"><?php echo $tr->translate("PURPOSE");?></span>: <span class="red"><?php echo $this->row['purpose'];?></span></li>
									<li><span class="lbl-tt"><?php echo $tr->translate("NOTE");?></span>: <span class="red"><?php echo $this->row['note'];?></span></li>
								</ul>
							</div>
						</div>
					</div>
					
					<table class="collape tablesorter" id="table_row" style="width:100%; white-space: nowrap;border:1px solid #ddd;">
				    	<tr id="head-title" class="head-td" align="center"></tr>
					</table>
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
					
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
				
               	</div>
             </div>
		</form>
    </div>
</div>
<?php if (!empty($this->rowdetail)) foreach ($this->rowdetail as $key=> $rs){?>
	<div id="proCode<?php echo $key?>" style="display: none;"><?php echo $rs['proCode'];?></div>
	<div id="productName<?php echo $key?>" style="display: none;"><?php echo $rs['proName'];?></div>
	<div id="measureTitle<?php echo $key?>" style="display: none;"><?php echo $rs['measureTitle'];?></div>
	<div id="itemsNote<?php echo $key?>" style="display: none;"><?php echo $rs['note'];?></div>
<?php } ?>
<style>
#table tr td{
	border:1px solid #cccccc;
	text-align: center;
}
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
}
table#table_row td.productName {
    font-size: 12px;
    line-height: 14px;
    font-weight: 600;
}
table#table_row td.currentQty {
    text-align: center;
    color: #f74545;
    font-weight: 600;
}
tr.rowData {
    border-bottom: solid 2px #02014a;
}
tr.rowData td {
    padding: 5px 0;
}
div#request-info .form-group {
	display: block;
	font-size: 12px;
	background: #fdfbbd;
	border: solid 2px #dc0303;
	border-radius: 5px;
}
div#request-info .form-group ul li span.lbl-tt {
	color: #02014a;
}
span.red {
	color: #f00;
	font-weight: bold;
}
div#request-info .form-group ul {
    margin: 0;
    padding: 0px 5px;
}
div#request-info .form-group ul li {
	display: inline-block;
	width: 45%;
	vertical-align: top;	
}
</style>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
    dojo.require("dijit.form.Textarea");
    dojo.require("dijit.form.NumberTextBox");
    dojo.require("dijit.form.DateTextBox");
	
	var productStore  = getDataStorefromJSON('id','name', null );
    require(["dojo/ready"], function(ready){
		ready(function(){
			initailize();
			onChageFunctionByBranch();
		});

	 });
    
	function onChageFunctionByBranch(){
		//getAllProduct();
		//getRequestNoByBranch();
	}
	
	
	var col= 0; var no=0;
	var title = 0;
	var urlGetProductInfo = '<?php echo $this->url(array('module'=>'stockmg','controller'=>'request','action'=>'productinfo')); ?>';
	function addRowProductRequest(){
		
		
	}
	

	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
	function initailize() {
		<?php if (!empty($this->rowdetail)) foreach ($this->rowdetail as $rs){?>
		col++;no++;
		template='';
		temp = "";
		if(title!=1){
			temp+='<td><?php echo $tr->translate("N_O");?></td>';
			temp+='<td width="20%"><?php echo $tr->translate("PRODUCT_NAME");?></td>';
			temp+='<td class="currentQty"><?php echo $tr->translate("STOCK_REMAIN");?></td>';
			temp+='<td width="10%"><?php echo $tr->translate("QTY_REQUEST");?></td>';
			temp+='<td width="10%"><?php echo $tr->translate("QTY_APPROVED");?></td>';
			temp+='<td width="20%"><?php echo $tr->translate("DATE_ENTRY");?></td>';
			temp+='<td width="20%"><?php echo $tr->translate("NOTE");?></td>';
			temp+='<td width="15%"><?php echo $tr->translate("STATUS");?></td>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
		
		var proCodeString = $( '#proCode'+'<?php echo $key;?>').html();
		var productNameString = $( '#productName'+'<?php echo $key;?>').html();
		var measureTitleString = $( '#measureTitle'+'<?php echo $key;?>').html();
		var itemsNoteString = $( '#itemsNote'+'<?php echo $key;?>').html();
		
		template+='<td align="center" width="2%">'+no+'<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="detailId'+col+'" name="detailId'+col+'" value="<?php echo $rs['id'];?>" type="text"  ></td>';
		template+='<td class="productName" >'+proCodeString+'<br />'+productNameString+'<input type="hidden" dojoType="dijit.form.TextBox" class="fullside" id="proId'+col+'" name="proId'+col+'" value="<?php echo $rs['proId'];?>" type="text"  ></td>';	
		template+='<td class="currentQty"  width="10%"><?php echo $rs['currentQty'];?> ('+measureTitleString+')</td>';	
		template+='<td><input readOnly dojoType="dijit.form.NumberTextBox" class="fullside" id="qtyAdjust'+col+'" name="qtyAdjust'+col+'" placeholder="'+'<?php echo $tr->translate("QTY_REQUEST");?> " value="<?php echo $rs['qtyAdjust'];?>" type="text"  ></td>';	
		template+='<td><input required dojoType="dijit.form.NumberTextBox" data-dojo-props="constraints:{min:1},rangeMessage:'+"'<?php echo $tr->translate("MINIMUM_VALUE_IS_ONE");?>'"+'" class="fullside" id="qtyApproved'+col+'" name="qtyApproved'+col+'" placeholder="'+'<?php echo $tr->translate("QTY_APPROVED");?> " value="<?php echo $rs['qtyApproved'];?>" type="text"  ></td>';	
		
		template+='<td><input readOnly dojoType="dijit.form.DateTextBox" class="fullside" constraints="{datePattern:'+"'dd/MM/yyyy'"+'}" id="dateReqStockIn'+col+'" name="dateReqStockIn'+col+'" placeholder="'+'<?php echo $tr->translate("DATE_ENTRY");?> " value="<?php echo date("Y-m-d",strtotime($rs['dateReqStockIn']));?>" type="text"  ></td>';	
		template+='<td><input dojoType="dijit.form.TextBox" class="fullside" id="note'+col+'" name="note'+col+'" placeholder="'+'<?php echo $tr->translate("NOTE");?> " value="'+itemsNoteString+'" type="text"  ></td>';	
		template+='<td><select class="fullside" name="approvedStatus'+col+'" id="approvedStatus'+col+'" dojoType="dijit.form.FilteringSelect" ><option value="1"><?php echo $tr->translate("APPROVED");?></option><option value="2"><?php echo $tr->translate("REJECTED");?></option></select></td>';
					

		tmp='<tr class="rowData" id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
		<?php }?>
	}
</script>