
<?php	
	$frm = $this->frm_loan;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
?>
<style>
	fieldset {
		border:1px solid #518aff !important;
	}
</style>
<title><?php echo $tr->translate('TRANSFER_CASH');?></title>
<div class="overlay">
	<div class="overlay-load">
		<div class="overlay-msg">
	    </div>
	</div>
</div>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script>
	require(["dijit/form/DateTextBox","dijit/form/NumberTextBox"]);
</script>
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action="<?php echo $this->url(array('module'=>'loan','controller'=>'transfercash','action'=>'add')); ?>" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				branch_id = dijit.byId('branch_id').get('value');
				if (branch_id=='' || branch_id==-1){
					alert('Please Select Branch!');
					dijit.byId('branch_id').focus();
					return false;
				}
				client = dijit.byId('member').get('value');
				if (client=='' || client==-1){
					alert('Please Select Client Name !');
					dijit.byId('member').focus();
					return false;
				}
				loan_number = dijit.byId('loan_number').get('value');
				toloan_number = dijit.byId('toloan_number').get('value');
				if(loan_number == toloan_number){
					alert("ដី/ផ្ទះដែលត្រូវផ្ទេរមិនអាចដូចគ្នាបានទេ !");
					dijit.byId('toloan_number').focus();
					return false;
				}
				loadingBlock();
				dijit.byId('savenew').set('disabled',true);
				dijit.byId('saveclose').set('disabled',true);
				return true;
			}else {
				return false;
			}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('TRANSFER_CASH');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-money" aria-hidden="true"></i> <?php echo $tr->translate("INFO_INDILOAN");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('branch_id')?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_CODE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id='loan_number' />
							<input type="hidden" name="identity" id="identity"  value="" >
							<input type="hidden" dojoType="dijit.form.TextBox" name="total_installamount" id="total_installamount"  value="" >
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DATE_BUY");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('date_buy')?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CUSTOMER_NAME");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="member" />
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-map" aria-hidden="true"></i> <?php echo $tr->translate("PROPERTY_INFO");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_CODE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="land_code" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SOLD_PRICE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('total_sold');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PAID");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('paid_before');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("INTEREST_PAID");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('from_interest_rate');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("Balance");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('balance_before');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DESCRIPTION");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<textarea name="transfer_note" class="fullside" style="min-height:80px;"></textarea>
	                   </div>
	                </div>
	            </div>
	            <div class="col-md-4 col-sm-4 col-xs-12">
	    			<div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-map-marker" aria-hidden="true"></i> <?php echo $tr->translate("TRANSFER_PROPERTY_INFORMATION");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('to_branch_id');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TO_LAND_CODE");?>(1) :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<input id="toloan_number" />
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SOLD_PRICE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('land_price');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PAID");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('house_price');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("Balance");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php echo $frm->getElement('to_total_sold');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-12 col-sm-12 col-xs-12 title-blog bold" ><i class="fa fa-info-circle" aria-hidden="true"></i> <?php echo $tr->translate("NOTE");?> 
	                   </label>
	                </div>
	                <div class="form-group">
	                	<div class="col-md-12 col-sm-12 col-xs-12" style="min-height: 75px;background: #f3feff;border: solid 1px #000096;padding: 10px 5px;color: #c00;font-size: 14px;">
	                		<span>&nbsp;រាល់ទិ​ន្នន័យប្រាក់បានបង់ ទាំងអស់នឹងត្រូវបានផ្ទេរមក ភាគីថ្មី <strong>(1)</strong></span>
	                	</div>
	                </div>
	            </div>
	        </div>
	        <div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-sm-12 border-top mt-20 ptb-10 text-center">
               		<input type="reset" label="<?php echo $tr->translate("CLEAR")?>" dojoType="dijit.form.Button" iconClass="dijitIconClear"/>
					<input type="submit" label="<?php echo $tr->translate("SAVECLOSE");?>" name='saveclose' id='saveclose' value='saveclose' dojoType="dijit.form.Button" iconClass="dijitIconDelete"/>
					<input type="submit" label="<?php echo $tr->translate("SAVENEW")?>" name='savenew' id='savenew' value='savenew' dojoType="dijit.form.Button" iconClass="dijitIconNewTask"/>
    			</div>
    		</div>
		</form>
	</div>
</div>
<script type="text/javascript">	
function setBranchID(){
	dijit.byId('to_branch_id').attr('value',dijit.byId('branch_id').get('value'));	
}
function filterClient(){
	branch_id = dijit.byId('branch_id').get('value');
	getAllPropertyBranch(branch_id);
	getAllClientByBranch(branch_id);
	getAllClientNumberByBranch(branch_id);
	getAllSaleNumber(branch_id);
}
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'transferproject','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){//used
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_code').set('store', property_store);
		},
		error: function(err) {
		}
	});
} 
var url_getland_transfer = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranchTransfer(){//used
	to_branch_id = dijit.byId('to_branch_id').get('value');
	if(to_branch_id=='' || to_branch_id==-1){return false;}
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':to_branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			sale_number_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('toloan_number').set('store',sale_number_store); 
		},
		error: function(err) {
		}
	});
} 

var url_getclient = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientbybranch')); ?>';
function getAllClientByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclient,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('member').set('store', client_store);
		},
		error: function(err) {
		}
	});
}
var url_getclientnum = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'getclientnumberbybranch')); ?>';
function getAllClientNumberByBranch(branch_id){
	dojo.xhrPost({
		url:url_getclientnum,	
		content:{ 
		    'branch_id':branch_id
		},		    
		handleAs:"json",
		load: function(data) {
			client_number_store  = getDataStorefromJSON('id','name', data);		
		},
		error: function(err) {
		}
	});
}

</script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore"); 
dojo.require("dojo.html");

var client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_name));?> );
var client_number_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->client_code));?> );
var property_store  = getDataStorefromJSON('id','name', null );

require(["dojo/ready"], function(ready){
	new dijit.form.FilteringSelect({
			store: property_store,
			autoComplete: true,
			required: false,		           
			name: "land_code",
			id: "land_code",
			searchAttr: "name",
			class: 'fullside',
			required:true,
			onChange: function() {
				land_code = dijit.byId('land_code').get('value');
				if(land_code==-1){
				}else{
					//getlandinfo();
				}
		}
	}, "land_code");
	 
	new dijit.form.FilteringSelect({
	store: client_store,
	autoComplete: true,
	required: false,		           
	name: "member",
	id: "member",
	searchAttr: "name",
	required:true,
	class: 'fullside',
	onChange: function() {
		member = dijit.byId('member').get('value');
		if(member==-1){
			showPopupclient();
		}else{
		}
}
	}, "member");

	new dijit.form.FilteringSelect({
		autoComplete: false, 
		queryExpr: "*${0}*",
		required: true,		           
		name: "loan_number",
		id: "loan_number",
		searchAttr: "name",
		class: 'fullside',
		onChange: function(){
			getInfoByLoanNumber();
	    }
		}, "loan_number");

	new dijit.form.FilteringSelect({
		autoComplete: false,  
		queryExpr: "*${0}*",
		required: true,		           
		name: "toloan_number",
		id: "toloan_number",
		searchAttr: "name",
		class: 'fullside',
		onChange: function(){
			getInfoBytoLoanNumber();
	    }
		}, "toloan_number");
	 
	});
</script>
<script type="text/javascript">
var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getInfoByLoanNumber(){
	loan_id = dijit.byId('loan_number').get('value');
	if(loan_id=="" || loan_id==null){
		dijit.byId('paid_before').attr('value',"");
		dijit.byId("member").attr('value',"");
		dijit.byId('land_code').attr('value',"");
		dijit.byId('from_interest_rate').attr('value',"");
		return false;
	}
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'sale_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {
			total_principal= data.total_principal;
			if(isNaN(total_principal) || total_principal==null){total_principal=0;}
		    paid_amount = data.total_principal;
			if(isNaN(paid_amount) || paid_amount==null){paid_amount=0;}
			total_principal = parseFloat(total_principal);
			dijit.byId('paid_before').attr('value',total_principal);
			dijit.byId("member").attr('value',data.client_id);
			dijit.byId('land_code').attr('value',data.house_id)
			
			dijit.byId('from_interest_rate').attr('value',data.total_interest_paid);
			dijit.byId('from_interest_rate').set('readOnly',true);
			
			dijit.byId('member').set('readOnly',true);

			dijit.byId('land_code').set('readOnly',true);
			dijit.byId("total_sold").attr('value',data.price_sold);
			dijit.byId("paid_before").attr('value',data.total_principal);
			dijit.byId('paid_before').set('readOnly',true);
			dijit.byId("balance_before").attr('value', parseFloat(data.price_sold)- parseFloat(data.total_principal));
			dijit.byId('balance_before').set('readOnly',true);
		},
		error: function(err) {
			alert(err);
		}
	});
}

var url_submiinfo = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getloan-bymemberid')); ?>';
function getInfoBytoLoanNumber(){
	loan_id = dijit.byId('toloan_number').get('value');
	if(loan_id==''){
		return false;
	}
	dojo.xhrPost({
	    url: url_submiinfo,	
	    content : { 
		    'sale_id':loan_id ,
		},	
		handleAs:"json",
		load: function(data) {
			total_principal= data.total_principal;
			if(isNaN(total_principal) || total_principal==null){total_principal=0;}

		    paid_amount = data.paid_amount;
			if(isNaN(paid_amount) || paid_amount==null){paid_amount=0;}

			price_sold = data.price_sold;
			if(isNaN(price_sold) || price_sold==null){price_sold=0;}
			
			total_principal = parseFloat(total_principal);
			dijit.byId('house_price').attr('value',total_principal);//paid
			dijit.byId('land_price').attr('value',price_sold);
			dijit.byId('to_total_sold').attr('value',price_sold - total_principal);//balance
		},
		error: function(err) {
			alert(err);
		}
	});
}

var sale_number_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_getsalenumber = "<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'get-sale-number')); ?>";
function getAllSaleNumber(branch_id){//used
	dojo.xhrPost({
		url:url_getsalenumber,	
		content:{ 
		    'branch_id':dijit.byId('branch_id').get('value')
		},		    
		handleAs:"json",
		load: function(data) {
			sale_number_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('loan_number').set('store',sale_number_store); 
		},
		error: function(err) {
		}
	});
}
</script>