<?php 
	$frm = $this->frm_search;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm_searchloantype = $this->frm_searchloantype;
	$urlprint = $this->baseUrl()."/report/incomeexpense/receipt-otherincome/id/";
	$urledit = $this->baseUrl()."/incexp/incomeotherpayment/edit/id/";
?>
<title><?php echo $tr->translate('REPAIRE_HOUSE_PAYMENT');?></title>
<script>
	dojo.require('dijit.form.Button');
	dojo.require("dijit.form.DateTextBox");
</script>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
	       	<div class="col-sm-12 border-botom">
		   		<div class="col-sm-8 pd-0">
		    		<h4 class="m-b-0"><i class="fa fa-money" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('REPAIRE_HOUSE_PAYMENT');?></h4>
	    		</div>
	    		<div class="col-sm-4 text-right">
	    		</div>
	    	</div>
	    </div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement("adv_search");?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('branch_id');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<input id="land_id" />
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('client_name');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm_searchloantype->getElement('type');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<input id="category_id" />
			   		</div>
			   	</div>
			   	<div class="form-group">
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('payment_method');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('start_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<?php echo $frm->getElement('end_date');?>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   			<button class="button-class button-primary" iconclass="glyphicon glyphicon-search" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
			   		</div>
			   		<div class="col-md-2 col-sm-2 col-xs-12">
			   		</div>
			   	</div>
			</form>
		</div>
		<div class="card-box">
			 <?php echo $this->list;?>
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore"); 
var property_store  = getDataStorefromJSON('id','name',[{"id":-1,"name":"<?php echo $tr->translate("SELECT_PROPERTY");?>"}]);
var income_category_store  = getDataStorefromJSON('id','name',<?php print_r(Zend_Json::encode(array()));?> );
require(["dojo/ready"], function(ready){
	
	new dijit.form.FilteringSelect({
		store: property_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "land_id",
		id: "land_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside fullside50',
		onChange: function() {
			land_id=-1;
	}
	}, "land_id");

	new dijit.form.FilteringSelect({
		store: income_category_store,
		required: false,
		autoComplete: false,
		queryExpr: "*${0}*",
		name: "category_id",
		id: "category_id",
		value:-1,
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			land_id=-1;
	}
		}, "category_id");

	 ready(function(){
		 getAllPropertyBranch();
		 getCategoryByType();
		 var catetype = dijit.byId('type');
		 catetype.on('change', function(evt) {
			 getCategoryByType();
	    });
	});
	 
});
land_id = '<?php echo $this->rssearch['land_id']?>';
var url_getland = '<?php echo $this->url(array('module'=>'loan','controller'=>'index','action'=>'getallland')); ?>';
function getAllPropertyBranch(branch_id){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id<0){
		return false;
	}
	dojo.xhrPost({
		url:url_getland,	
		content:{ 
		    'branch_id':branch_id,
		    'action':1
		},		    
		handleAs:"json",
		load: function(data) {
			property_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('land_id').set('store', property_store);
		    
		    if(land_id>0){
		    	dijit.byId('land_id').attr('value',land_id);
			 }
		},
		error: function(err) {
		}
	});
}
oldtype = '<?php echo $this->rssearch['type']?>';
var url_getcatebytype = '<?php echo $this->url(array('module'=>'loan','controller'=>'incomeotherpayment','action'=>'get-categorybytype')); ?>';
function getCategoryByType(){
	cate_type = dijit.byId('type').get('value');
	dijit.byId('category_id').reset(); 
	if(cate_type=="" || cate_type ==-1){
		income_category_store  = getDataStorefromJSON('id','name', <?php print_r(array())?>);
	    dijit.byId('category_id').set('store',income_category_store);   
		return false;
	}
	dojo.xhrPost({
		url: url_getcatebytype,
		content:{
			'cate_type':cate_type
			},
		handleAs:"json",
		load: function(data) {
			income_category_store  = getDataStorefromJSON('id','name', data);
		    dijit.byId('category_id').set('store',income_category_store);
		    if(oldtype==cate_type){
		    	dijit.byId('category_id').set('value','<?php echo $this->rssearch['category_id']?>');
		    }   
		},
		error: function(err) {
		}
	});
}

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
			var m = "clicked: " + key;
			var newPageTitle="";
			var actionType=1;
			
			if(key=="print"){
				url='<?php echo $urlprint;?>';
				newPageTitle="<?php echo $tr->translate("PRINT");?>";
			}
			else if(key=="edit"){
				url='<?php echo $urledit;?>';
				actionType=2;
			}
			if(actionType==1){
				addTab(newPageTitle,url+row+'?inFrame=true');
			}else{
				gotoAction();
			}
		},
		items: {
			"print": {name: "<?php echo $tr->translate("PRINT");?>", icon: "fa-print", accesskey: "c o p y"},
			"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "fa-edit", accesskey: "c o p y"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_self');
}
</script>