<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$frm = $this->frm_incomeother;
?>
<title><?php echo $tr->translate('ADD_MATERIAL_INCLUDE');?></title>
<style>	
.fullside {
	width: 100%;
	height: 30px;
}
.btn-reset{
	background: #c00;
    color: #fff;
}
.addfile{
	background: #0077c5 !important;
    color: #fff !important;
}
.head-td th {
    padding: 5px;
}

.custom-switch a.switchButton {
    width: initial;
    min-width: initial;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
 <script>
		require(["dijit/form/DateTextBox","dijit/form/NumberTextBox","dojo/number","dijit/Dialog"]);
 </script>
 <div class="card">
	<div class="card-content collapse show">
		<form id='frm_add_tran' action=""	dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					branch_id = dijit.byId('branch_id').get('value');
					if(branch_id=='' || branch_id==-1){
						infoMessageAlert('<?php echo $tr->translate("PLEASE_SELECT_BRANCH")?>!');
						dijit.byId('branch_id').focus();
						return false;
					}
				
					var identity = $('#identity').val();
					if(identity==''){
						infoMessageAlert("<?php echo $tr->translate("PLEASE_SET_MATERAIL");?>");
						dijit.byId("loan_number").focus();
						return false;
					}

					loadingBlock();
				
					dijit.byId('saveclose').set('disabled',true);	
					dijit.byId('savenew').set('disabled',true);
					return true;
				}else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_MATERIAL_INCLUDE');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-screenshot" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('PROJECT_INFO')?> </p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branch_id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_CODE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="sale_client" />
										<input type="hidden" id="land_address" name="land_address" dojoType="dijit.form.TextBox"/>
										<input type="hidden" id=street name="street" dojoType="dijit.form.TextBox"/>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("CUSTOMER_NAME");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="customer" />
											<input type="hidden" id="house_id" name="house_id" dojoType="dijit.form.TextBox"/>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	             </div>
	             <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('OTHER_INFO')?> </p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DATE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('Date');?>
									   </div>
									</div>
								  
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('Description');?>
									   </div>
									</div>
								 </div>
							 </div>
						 </div>
					 </div>
				 </div>

	        </div>
	        <div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-tasks" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate('ITEMS')?> </p>
										</div> 
									</div>
									
									<div class="form-group" style="background: #d8e0e2;padding: 5px 15px;margin: 0;border: solid 1px #697996;border-radius: 2px;margin-top: 10px;">
										<div class="form-group">
										   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("ITEMS");?> :
										   </label>
										   <div class="col-md-5 col-sm-5 col-xs-12">
												<?php echo $frm->getElement('items_id');?>
										   </div>
										   <div class="col-md-2 col-sm-2 col-xs-12">
												<input class="button-class button-primary" iconClass="glyphicon glyphicon glyphicon-refresh" type="button" label="<?php echo $tr->translate('REFRESH');?>" dojoType="dijit.form.Button" onclick="getRefreshItems();"/>
											</div>
										</div>
									</div>
									<div class="card-box mb-20">
										<table id="table_row" class="collape responsiveTable">
											<tr id="head-title1" class="head-td" align="right"></tr>
										</table>
										<input type="hidden" name="identity" id="identity"  value="" >
									</div>
								</div>
							</div>
						</div>
					</div>
       			  </div>
           	  </div>
		     <div class="clearfix"></div>
			 <div class="card-box">
             	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove" label="<?php echo $tr->translate("SAVECLOSE");?>" id='saveclose' name='saveclose' value='saveclose' dojoType="dijit.form.Button" />
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" label="<?php echo $tr->translate("SAVENEW")?>" id='savenew' name='savenew' value='savenew' dojoType="dijit.form.Button" />
					
    			</div>
    		</div>
	   	</form>
	 </div>
</div>
<script type="text/javascript">
dojo.require("dijit.form.Textarea");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.NodeList-manipulate");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
function displayNone(){
	document.getElementById('divPrint1').style.display="none";
}
require(["dojo/ready"], function(ready){
	new dijit.form.FilteringSelect({
		name: "items_id",
		id: "items_id",
		autoComplete: false,
		queryExpr: "*${0}*", 
		required: false,
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			items_id = dijit.byId('items_id').get('value');
			if(items_id==-1){
				window.open('<?php echo Zend_Controller_Front::getInstance()->getBaseUrl()."/loan/itemsmeterial/add?rightclick=true";?>','_blank');
				return false;
			}
			setValueToRow();
	    }
		}, "items_id");
});
var sale_client_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
dojo.ready(function(){
	
	new dijit.form.FilteringSelect({
	    autoComplete: true,                        
	    id: "customer",
	    name: "customer",  
	    readOnly: "readOnly",
	    tabindex: "16",  
	    class: 'fullside',  
	    placeHolder:"<?php echo $tr->translate("CHOOSE_CUSTOEMR")?>",          
	    onChange: function() {  
	    }
	}, "customer");
	
});
dojo.ready(function(){
	<?php if(!empty($this->rsresult)){?>
		dijit.byId('branch_id').attr('value','<?php echo $this->rsresult['branch_id'];?>');
		getallCustomer();
		getSaleClie();
	<?php }?>
});


var customer_store  = getDataStorefromJSON('id','name', <?php print_r(array())?> );
var url_customer = '<?php echo $this->url(array('module'=>'incexp','controller'=>'income','action'=>'get-all-customer')); ?>';
	function getallCustomer(){
		getBranchinfo();
		branch_id = dijit.byId('branch_id').get('value');
		if(branch_id=='' || branch_id==0){
			return 0;
		}
		dojo.xhrPost({
			url:url_customer,
			content:{
				'branch_id':branch_id
				},
			handleAs:"json",
			load: function(data) {
				customer_store  = getDataStorefromJSON('id','name', data);
			    dijit.byId('customer').set('store',customer_store);   
			},
			error: function(err) {
			}
		});
	}

function getInvoiceNo(condition){
	
}
var template = '';
var service = '';
var col = 0;
var noo = 0;
var title = 0;
tmp = '';
temp='';
function setValueToRow(){
	items_id = dijit.byId('items_id').get('value');
	if(items_id=='' || items_id==-1){
		dijit.byId('items_id').focus();
		return false;
	}
	
    itemslabel = dijit.byId("items_id").attr('displayedValue');
	
	col++;noo++;
		template='';
		if(title!=1){  
			temp+='<th scope="col" width="47px"><?php echo $tr->translate("DEL");?></th>';
			temp+='<th scope="col" width="50px"><?php echo $tr->translate("NUM");?></th>';
			temp+='<th scope="col" width="25%"><?php echo $tr->translate("ITEMS");?></th>';
			temp+='<th scope="col"><?php echo $tr->translate("DESCRIPTION");?></th>';
			temp+='<th scope="col" width="70px"><?php echo $tr->translate("STATUS");?></th>';
			dojo.query("#head-title1").append(temp);
			title=1;
	    }
		template+='<td data-label="<?php echo $tr->translate("DEL");?>"  align="center"><span title="<?php echo $tr->translate("REMOVE_RECORD");?>" class="removeRow" onclick="deleteRecords('+col+');calculateTotal('+col+');"><i class="glyphicon glyphicon-trash" aria-hidden="true"></i></span></td>';
		template+='<td data-label="<?php echo $tr->translate("NUM");?>"  align="center">'+noo+'</td>';
		template+='<td data-label="<?php echo $tr->translate("ITEMS");?>" >'+itemslabel+'<input dojoType="dijit.form.TextBox" class="fullside" required="required" id="items_id'+col+'" name="items_id'+col+'" value="'+items_id+'" type="hidden" ></td>';	
		template+='<td data-label="<?php echo $tr->translate("DESCRIPTION");?>"><input type="text" name="description_'+col+'" id="description_'+col+'" dojoType="dijit.form.Textarea" placeholder="<?php echo $tr->translate("NOTE");?>" class="fullside" /></td>';
		template+='<td data-label="<?php echo $tr->translate("STATUS");?>">';
	    		
		template+='<label class="control-label custom-switch ">';
			template+='<a href="javascript:void(0);" class="switchButton "><?php echo $tr->translate("GIVED_TO_CUSTOMER");?></a>'; 
			template+='<input type="checkbox" id="is_gived_'+col+'" name="is_gived_'+col+'" class="custom-switch-input" > ';
			template+='<span class="custom-switch-indicator custom-radius "></span>'; 
		template+='</label>';
		template+='</td>';
		tmp='<tr class="rowData" id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
}
function typethisamename(index,type){
	description = dijit.byId('description_'+index).get('value');
	dijit.byId('remark_'+index).set('value',description);
}
function deleteRecords(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
}	



new dijit.form.FilteringSelect({
	store: sale_client_store,
	autoComplete: false,
	queryExpr: "*${0}*",
	required: false,		           
	name: "sale_client",
	id: "sale_client",
	placeholder:"<?php echo $tr->translate('SELECT_PROPERTY');?>", 
	searchAttr: "name",
	class: 'fullside',
		onChange: function() {
			getLandAndClientDetail();
		}
	}, "sale_client");
	
 
var	url_getSaleClien = '<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'get-saleclie'));?>';
function getSaleClie(){
	dijit.byId('sale_client').reset();
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getSaleClien,	
		content:{ 
			'branch_id': branch_id, 'sale_id':'',
			'is_completed':0
		},
		handleAs:"json",
		load: function(data) {	
			sale_client_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('sale_client').set('store', sale_client_store);
			<?php if(!empty($this->rsresult)){?>
		    	dijit.byId('sale_client').attr('value','<?php echo $this->rsresult['id'];?>');
		    <?php }?>
		},
		error: function(err) {
		}
	});
}


var url_land= '<?php echo $this->url(array('module'=>'loan','controller'=>'cancel','action'=>'get-info'));?>';
function getLandAndClientDetail(){
		sale_id = dijit.byId('sale_client').get('value');
		if(sale_id=='' || sale_id==0){
			return false;
		}
	dojo.xhrPost({
		url:url_land,	
		content:{ 
		    'sale_id':sale_id
		},		    
		handleAs:"json",
		load: function(data) {
			dijit.byId("customer").attr("value",data.client_id);
			dijit.byId("house_id").attr("value",data.house_id);
			dijit.byId("land_address").attr("value",data.land_address);
			dijit.byId("street").attr("value",data.street);
			
		},
		error: function(err) {
		}
	});
}


function printSubmit(){
		$('#frm_add_tran').submit();
}
function getBranchinfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'loan','controller'=>'ilpayment','action'=>'getbranch')); ?>';
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==""){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'branch_id':branch_id
		},	
		load: function(data) {
			//var arr = JSON.parse(data);
			//var imagesUrl = '<img class="view" style="height:80px; max-width: 100%;" src="<?php echo $this->baseUrl()."/images/projects/"?>'+arr.logo+'" />';
			//document.getElementById('projectlogo').innerHTML = imagesUrl;
		},
		error: function(e) {
		}
	});
}
function returnMOnth(monthnum){
	var month = new Array();
	month[1] = "Jan";
	month[2] = "Feb";
	month[3] = "Mar";
	month[4] = "Apr";
	month[5] = "May";
	month[6] = "Jun";
	month[7] = "Jul";
	month[8] = "Aug";
	month[9] = "Sep";
	month[10] = "Oct";
	month[11] = "Nov";
	month[12] = "Dec";
	return month[monthnum];
}

var urlGetItems = '<?php echo $this->url(array('module'=>'loan','controller'=>'itemsmeterial','action'=>'getitems')); ?>';
function getRefreshItems(){
	loadingBlock();
	dojo.xhrPost({
		url: urlGetItems,	
		content:{ 
		    'addNew':1
		},		    
		handleAs:"json",
		load: function(data) {
			itemesStore  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('items_id').set('store', itemesStore);
		    HideloadingBlock();
		},
		error: function(err) {
		}
	});
}
</script>
