<?php

	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('ADD'));
	
?>	
<div class="card">
	<div class="card-content collapse show">
		<form id='frm_add' action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					return true;
				}else{
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-folder-open" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD');?></h4>
	    			</div>
	    		</div>
	    	</div>
		    <div class="col-md-12">
	        	<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="form-group">
	                   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("MEASURE_TITLE");?>
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                   		<input type="text" name="title" class="fullside" id="title" dojoType="dijit.form.ValidationTextBox" required="required" />
	                   </div>
	                </div>
	            </div>
	        </div>
			<div class="clearfix"></div>
			  <div class="card-box">
               	<div class="col-sm-4 border-top mt-20 ptb-10 text-center">
               		<div class="col-md-4 col-sm-4 col-xs-12"></div>
               		<div class="col-md-7 col-sm-7 col-xs-12">
						<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
						 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
					</div>
    			</div>
	    	</div>
		</form>
	</div>
</div>