<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Land Information'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'add')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong><?php echo $tr->translate("Add Property");?></strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("Property Code")?></td>
							<td><?php echo $frm->getElement('landcode');?></td>
							<td><?php echo $tr->translate("TITLE")?>*</td>
							<td><?php  echo $frm->getElement('land_address');?></td>
							<td><?php echo $tr->translate("Price")?>*</td>
							<td><?php  echo $frm->getElement('price');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Size")?></td>
							<td><?php  echo $frm->getElement('size');?></td>
							<td><?php echo $tr->translate("Width")?></td>
							<td><?php  echo $frm->getElement('width');?></td>
							<td>Height</td>
							<td><?php  echo $frm->getElement('height');?></td>
						</tr>
						<tr>
						    <td valign="top"><?php echo $tr->translate("Head Title No.")?></td>
							<td valign="top"><?php  echo $frm->getElement('hardtitle');?></td>
							<td valign="top"><?php echo $tr->translate("NOTE")?></td>
							<td><?php  echo $frm->getElement('desc');?></td>
							<td valign="top"><?php echo $tr->translate("STATUS")?></td>
							<td valign="top"><?php  echo $frm->getElement('status');?></td>
						</tr>
						<tr>
						    <td valign="top"><?php echo $tr->translate("Property Type")?></td>
							<td valign="top"><?php  echo $frm->getElement('property_type');?></td>
							<td valign="top"><?php echo $tr->translate("Floor")?></td>
							<td><?php  echo $frm->getElement('floor');?></td>
							<td valign="top"><?php echo $tr->translate("Bedroom")?></td>
							<td valign="top"><?php  echo $frm->getElement('bedroom');?></td>
						</tr>
						<tr>
						    <td valign="top"><?php echo $tr->translate("Living")?></td>
							<td valign="top"><?php  echo $frm->getElement('living');?></td>
							<td valign="top"><?php echo $tr->translate("Dinner Room")?></td>
							<td><?php  echo $frm->getElement('dinnerroom');?></td>
							<td valign="top"><?php echo $tr->translate("Buiding Year")?></td>
							<td valign="top"><?php  echo $frm->getElement('buidingyear');?></td>
						</tr>
						<tr>
						    <td valign="top"><?php echo $tr->translate("Parking Space")?></td>
							<td valign="top"><?php echo $frm->getElement('parkingspace');?></td>
							<td valign="top"><?php echo $tr->translate("Photo")?></td>
							<td><?php echo $frm->getElement('photo');?></td>
							<td valign="top"><?php //echo $tr->translate("bedroom")?></td>
							<td valign="top"><?php  //echo $frm->getElement('bedroom');?></td>
						</tr>
						<tr>
							<td colspan="6" align="center">
							<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							 <input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
							<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
								 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>
<script type="text/javascript">

dojo.ready(function(){
	
	try{
	
	}catch(e){
	}
});
</script>