<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Land Information'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.Dialog");
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'copy')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				dijit.byId('save_close').set('disabled',true);	
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr>
		<td>
			<fieldset>
				<legend ><strong><?php echo $tr->translate("ADD_PROPERTY");?></strong></legend>
				<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td valign="top" width="33%">
									<table width="100%">
										<tr>
											<td><?php echo $tr->translate("BRANCH_NAME")?></td>
											<td><?php echo $frm->getElement('branch_id');?></td>
										</tr>
										<tr>
											<td><?php echo $tr->translate("LOAN_NO")?></td>
											<td><?php echo $frm->getElement('landcode');?></td>
										</tr>
										<tr>
											<td valign="top"><strong><?php echo $tr->translate("HEAD_TITLE_NO")?></strong></td>
											<td valign="top"><?php  echo $frm->getElement('hardtitle');?></td>
										</tr>
										<tr>
											<td><strong><?php echo $tr->translate("HOUSE_TITLE")?>*</strong></td>
											<td><label id="message" style="color: red;"></label>
											<?php  echo $frm->getElement('land_address');?></td>
										</tr>
										<tr>
											<td><strong><?php echo $tr->translate("STREET")?></strong></td>
											<td><?php  echo $frm->getElement('street');?></td>
										</tr>
										<tr>
											<td valign="top"><?php echo $tr->translate("PROPERTY_TYPE")?></td>
											<td valign="top"><input id="property_type" /><?php  //echo $frm->getElement('property_type');?></td>
										</tr>
										<tr>
											<td><strong><?php echo $tr->translate("LAND_PRICE")?>*</strong></td>
											<td><?php  echo $frm->getElement('land_price');?></td>
										</tr>
										<tr>
											<td><strong><?php echo $tr->translate("HOUSE_PRICE")?>*</strong></td>
											<td><?php  echo $frm->getElement('house_price');?></td>
										</tr>
										<tr>
											<td><strong><?php echo $tr->translate("PRICE")?>*</strong></td>
											<td><?php  echo $frm->getElement('price');?></td>
										</tr>
									</table>
							</td>
							<td valign="top" width="33%">
								<table width="100%">
									<tr>
										<td><strong><?php echo $tr->translate("WIDTH")?></strong></td>
										<td><?php  echo $frm->getElement('width');?></td>
									</tr>
									<tr>
										<td><strong><?php echo $tr->translate("HEIGHT")?></strong></td>
										<td><?php  echo $frm->getElement('height');?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("SIZE")?></td>
										<td><?php  echo $frm->getElement('size');?></td>
									</tr>
									<!-- <tr>
										<td><?php //echo $tr->translate("WIDTH_LAND")?></td>
										<td><?php  //echo $frm->getElement('width_land');?></td>
									</tr>
									<tr>
										<td><?php //echo $tr->translate("HEIGHT_LAND")?></td>
										<td><?php  //echo $frm->getElement('height_land');?></td>
									</tr> -->
									<tr>
										<td><?php echo $tr->translate("SOUTH")?></td>
										<td><?php echo $frm->getElement('south');?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("NORTH")?></td>
										<td><?php echo $frm->getElement('north');?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("WEST")?></td>
										<td><?php echo $frm->getElement('west');?></td>
									</tr>
									<tr>
										<td><?php echo $tr->translate("EAST")?></td>
										<td><?php echo $frm->getElement('east');?></td>
									</tr>
									<tr>
										<td valign="top"><strong><?php echo $tr->translate("STATUS_BUY")?></strong></td>
										<td valign="top"><?php  echo $frm->getElement('buy_status');?></td>
									</tr>
									<tr>
										<td valign="top"><?php echo $tr->translate("STATUS")?></td>
										<td valign="top"><?php  echo $frm->getElement('status');?></td>
									</tr>
								</table>
							</td>
							<td valign="top" width="33%">
									<table width="100%">
								<?php $is_show =$this->data['showhouseinfo']; 
									if($is_show==1){?>
										<tr>
											<td valign="top"><?php echo $tr->translate("FLOOR")?></td>
											<td><?php  echo $frm->getElement('floor');?></td>
										</tr>
										<tr>
											<td valign="top"><?php echo $tr->translate("BEDROOM")?></td>
											<td valign="top"><?php  echo $frm->getElement('bedroom');?></td>
										</tr>
										<tr>
											<td valign="top"><?php echo $tr->translate("LIVING")?></td>
											<td valign="top"><?php  echo $frm->getElement('living');?></td>
										</tr>
										<tr>
											<td valign="top"><?php echo $tr->translate("DINNER_ROOM")?></td>
											<td><?php  echo $frm->getElement('dinnerroom');?></td>
										</tr>
										<tr>
											<td valign="top"><?php echo $tr->translate("BUIDING_YEAR")?></td>
											<td valign="top"><?php  echo $frm->getElement('buidingyear');?></td>
										</tr>
										<tr>
											<td valign="top"><?php echo $tr->translate("PARKING_SPACE")?></td>
											<td valign="top"><?php echo $frm->getElement('parkingspace');?></td>
										</tr>
								<?php }?>
										<tr>
											<td valign="top"><?php echo $tr->translate("NOTE")?></td>
											<td><?php  echo $frm->getElement('desc');?></td>
										</tr>
								</table>
							</td>
						</tr>
						<tr>
							<td colspan="3" align="center">
								<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
									 iconClass="dijitIconClear" /> 
								<input type="submit" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new"
									 iconClass="dijitEditorIcon dijitEditorIconSave"/> 
							</td>
						</tr>
					</table>			
			</fieldset>		
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>
<?php echo $this->frmPopupPropertyType;?>
<script type="text/javascript">
var propertyType_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->pro_type));?> );
dojo.ready(function(){
	
	try{
		new dijit.form.FilteringSelect({
			store: propertyType_store,
			autoComplete: true,
			required: true,		           
			name: "property_type",
			id: "property_type",
			value: "<?php echo $this->row['property_type'];?>",
			searchAttr: "name",
			class: 'fullside',
				onChange: function() {
					//district = dijit.byId('property_type').get('value');
					showPopupForm();
				}  
			}, "property_type");
		getPropertyNo();
	}catch(e){
	}
});
function showPopupForm(){
	property_type = dijit.byId('property_type').get('value');
	if(property_type==''){
		alert('Please Select Property Type');
		dijit.byId('property_type').focus();
		return false;
	}else if(property_type==-1){
		dijit.byId('frm_propertytype').show();
	}
}
url_property = '<?php echo $this->url(array('module'=>'group','controller'=>'propertiestype','action'=>'add-propertytype'));?>';
function addNewPropertytype(){
	if(dijit.byId('frm_propertytype').validate()) {
		dojo.xhrPost({
			url:url_property,	
			form:dojo.byId('form_propertytype'),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('type_nameen').get('value')
				};		
				addDataToSelectbox(dijit.byId('property_type'), propertyType_store, Itemmake, data);	
				dijit.byId('property_type').attr('value',data);
				dijit.byId('frm_propertytype').reset();
				dijit.byId('frm_propertytype').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
url_getPropertyNo = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'get-property-no'));?>';
function getPropertyNo(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getPropertyNo,	
		content:{ 
			'branch_id': branch_id
		},
		handleAs:"json",
		load: function(data) {	
		    dijit.byId('landcode').attr('value',data);
		},
		error: function(err) {
			alert(err);
		}
	});
}
function CalculatePrice(){
	house_price = dijit.byId('house_price').get('value');
	land_price = dijit.byId('land_price').get('value');
	var price = Number(house_price + land_price);
	dijit.byId('price').attr('value',price);
}
function calCulateSize(){
	width = dijit.byId("width").get('value');
	height = dijit.byId("height").get('value');
	totalsize = width*height;
	dijit.byId("size").attr('value',totalsize);
}

var old_title = '<?php echo $this->row['land_address'];?>';
url_CheckTitle = '<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'check-title'));?>';
function checkTitle(){
	title = dijit.byId('land_address').get('value');
	branch_id = dijit.byId('branch_id').get('value');
	street = dijit.byId('street').get('value');
	if(title=='' || street==''){ document.getElementById('message').innerHTML ='';return false;}
	dojo.xhrPost({
		url:url_CheckTitle,	
		content:{ 
			'branch_id': branch_id , 'land_address': title,'street': street
		},
		handleAs:"json",
		load: function(data) {	
			if(data !== false ){
		   		document.getElementById('message').innerHTML ='លេខផ្ទះ/ឡូតិ៍នេះមានរួចរាល់ហើយ';
		   		dijit.byId('land_address').focus();
		   		return false;
			}else{
				document.getElementById('message').innerHTML ='';
				return true;
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>