<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('Land Information'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.NumberTextBox");
</script>
<form id='add_client' action="<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'edit')); ?>" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				return true;
			} else {
				return false;
			}
</script>
<table  width="100%" style="margin-top:-5px;">
	<tr>
		<td>
		<fieldset>
					<legend ><strong><?php echo $tr->translate("Edit Property");?></strong></legend>
					<table style="margin: 0 auto; width:100%;" cellspacing="10">
						<tr>
							<td><?php echo $tr->translate("Land Code")?></td>
							<td><?php echo $frm->getElement('landcode'); echo $frm->getElement('id'); ?></td>
							<td><?php echo $tr->translate("Land Address")?>*</td>
							<td><?php  echo $frm->getElement('land_address');?></td>
							<td><?php echo $tr->translate("Price")?>*</td>
							<td><?php  echo $frm->getElement('price');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("Size")?></td>
							<td><?php  echo $frm->getElement('size');?></td>
							<td><?php echo $tr->translate("Width")?></td>
							<td><?php  echo $frm->getElement('width');?></td>
							<td>Height</td>
							<td><?php  echo $frm->getElement('height');?></td>
						</tr>
						<tr>
							<td valign="top"><?php echo $tr->translate("Head Title No.")?></td>
							<td valign="top"><?php  echo $frm->getElement('hardtitle');?></td>
							<td valign="top"><?php echo $tr->translate("NOTE")?></td>
							<td><?php  echo $frm->getElement('desc');?></td>
							<td valign="top"><?php echo $tr->translate("STATUS")?></td>
							<td valign="top"><?php  echo $frm->getElement('status');?></td>
						</tr>
						<tr>
						    <td valign="top"><?php echo $tr->translate("property_type")?></td>
							<td valign="top"><?php  echo $frm->getElement('property_type');?></td>
							<td valign="top"><?php echo $tr->translate("floor")?></td>
							<td><?php  echo $frm->getElement('floor');?></td>
							<td valign="top"><?php echo $tr->translate("bedroom")?></td>
							<td valign="top"><?php  echo $frm->getElement('bedroom');?></td>
						</tr>
						<tr>
						    <td valign="top"><?php echo $tr->translate("living")?></td>
							<td valign="top"><?php  echo $frm->getElement('living');?></td>
							<td valign="top"><?php echo $tr->translate("dinnerroom")?></td>
							<td><?php  echo $frm->getElement('dinnerroom');?></td>
							<td valign="top"><?php echo $tr->translate("buidingyear")?></td>
							<td valign="top"><?php  echo $frm->getElement('buidingyear');?></td>
						</tr>
						<tr>
						    <td valign="top"><?php echo $tr->translate("parkingspace")?></td>
							<td valign="top"><?php echo $frm->getElement('parkingspace');?></td>
							<td valign="top"><?php echo $tr->translate("Photo")?></td>
							<td><?php echo $frm->getElement('photo');?></td>
							<td valign="top"><?php //echo $tr->translate("bedroom")?></td>
							<td valign="top"><?php  //echo $frm->getElement('bedroom');?></td>
						</tr>
						<tr>
							<td colspan="6" align="center">
							<input type="reset" label="<?php echo $tr->translate('CLEAR');?>" dojoType="dijit.form.Button" 
								 iconClass="dijitIconClear" /> 
							 <input type="submit" value="SAVE_CLOSE" tabindex="2" label="<?php echo $tr->translate('GO_EDIT');?>" id="save_close" dojoType="dijit.form.Button" name="save_close"
								 iconClass="dijitEditorIcon dijitEditorIconSave" /> 
							</td>
						</tr>
					</table>	
		</fieldset>		
		</td>
	</tr>
</table>	
</form>
<table>
<tr>
</tr>
</table>

<script type="text/javascript">

dojo.ready(function(){
	
	try{
	
	}catch(e){
	}
});

var document_type_url = '<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'insert-document-type'));?>';
function addNewDocumentType(){
	dojo.xhrPost({
		url:document_type_url,	
		content:{ 
		    'title_en':dijit.byId('clienttype_nameen').get('value'),
		    'title_kh':dijit.byId('clienttype_namekh').get('value'),
		    'type':23,
		},
		handleAs:"json",
		load: function(data) {	
			clienttypeen = dijit.byId('clienttype_nameen').get('value');
			clienttypekh = dijit.byId('clienttype_namekh').get('value');
			if(doc_type==1){
				document_type = dijit.byId('client_d_type');
				
			}else if(doc_type==2){
				document_type = dijit.byId('join_d_type');
			}else{
				document_type = dijit.byId('guarantor_d_type');
			}

			 var myNewItem1 = {					
						id: data,
						name: clienttypekh+'-'+clienttypeen
				};			
				addDataToSelectbox(document_type, d_datastore, myNewItem1, data);		
				 
			dijit.byId('frm_clienttype').reset();
			dijit.byId('frm_clienttype').hide();
	
		},
		error: function(err) {
			alert(err);
		}
	});	
}
function showPopupclientdtype(){
	dijit.byId('frm_clienttype').show();
}
</script>