<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("Land Information"));
$frm = $this->frm_search;
$frms=$this->frm_client;
?>
<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'land','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
<table>
   <tr>  
      <td><?php echo $frm->getElement("adv_search");?></td>
      <td><?php echo $frm->getElement('status');?></td>
       <td><?php echo $frm->getElement('start_date');?></td>
      <td><?php echo $frm->getElement('end_date');?></td>
      <td><button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
   </tr>
</table>  
<?php echo $this->list;?> 
</form>
<script type="text/javascript">
dojo.require("dojo.data.ObjectStore");
dojo.require("dijit.form.DateTextBox");

dojo.ready(function(){
	
});

</script>