<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('EDIT_PROPERTY_TYPE'));
	
	$serviceFee = SEVICEFEE_INPROPERTY_TYPE;
	$classFee = "";
	if($serviceFee==0){
		$classFee = "hideClass";
	}
	$property = $this->frm_property_type;
?>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-map" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_PROPERTY_TYPE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="card-box">
	    	<form  id='add_techer' action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
				<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="form-group">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_TYPE");?><span>*</span>   :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php  echo $property->getElement('type_nameen');?>
	                   </div>
	                </div>
					<div class="form-group <?php echo $classFee;?>">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12 " ><?php echo $tr->translate("BOREY_FEE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php  echo $property->getElement('serviceFee');?>
	                   </div>
	                </div>
					<div class="form-group <?php echo $classFee;?>">
	                   <label class="control-label bold col-md-5 col-sm-5 col-xs-12 " ><?php echo $tr->translate("BOREY_FEE");?> <?php echo $tr->translate("YEAR");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php  echo $property->getElement('serviceFeeYear');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php  echo $property->getElement('note');?>
	                   </div>
	                </div>
	                <div class="form-group">
	                   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?> :
	                   </label>
	                   <div class="col-md-7 col-sm-7 col-xs-12">
	                    	<?php  echo $property->getElement('status');?>
	                   </div>
	                </div>
	                <div class="col-sm-12 border-top mt-20 ptb-10 text-center">
		    			<input type="hidden" name="exchangefrom" value="2" />
						<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVECLOSE");?>" dojoType="dijit.form.Button" 
							iconClass="dijitEditorIcon dijitEditorIconSave" />
		    		</div>
				</div>
				<div class="col-md-3 col-sm-3 col-xs-12">
					<div class="form-group">
		                   <div class="col-md-12 col-sm-12 col-xs-12">
		                    	<?php 
								$imageFeature = $this->baseUrl()."/images/photo/property/default-property-img.jpg";
								if (!empty($this->row['image_feature'])){
									if (file_exists(PUBLIC_PATH."/images/photo/property/".$this->row['image_feature'])){
										$imageFeature = $this->baseUrl()."/images/photo/property/".$this->row['image_feature'];
									}
								}
								?>
								<input name="old_photo"  value="<?php echo $this->row['image_feature'];?>" type="hidden" />
								<div class="account-image" >
									<div class="image-box">
										<img id="logo_wiew" src="<?php echo $imageFeature;?>" alt=""  />
									</div>
									<div class="button_browse">
									<div id='preview'></div>	
											<span>
												<?php echo $tr->translate('Change IMAGE')?> 
												<span ><i class="fa fa-camera" aria-hidden="true"></i></span><br />
												(950px x 478px)
											</span>
											<input class="btn_borwse_image" type="file" id="logo" name="logo" />
									</div>
								</div>
		                   </div>
		                 </div>
				</div>
				
			</form>
		</div>
	</div>
</div>
<style>
.image-box {
    text-align: center;
}
.image-box img {
    width: 100%;
    height: 150px;
    border: solid 1px #eee;
}
.button_browse {
    /*margin-top: 10px; */
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 45px;
    cursor: pointer;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 45px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 100%;
}
.hideClass{
   display:none !important;
  
}
</style>
<script>
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.NumberTextbox");
	
	function readURL(input) {
		if (input.files && input.files[0]) {
			var reader = new FileReader();
			
			reader.onload = function (e) {
				$('#logo_wiew').attr('src', e.target.result);
			}
			reader.readAsDataURL(input.files[0]);
		}
	}
	$("#logo").change(function(){
		readURL(this);
	});
</script>