<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("PROPERTY_TYPE"));
$frm = $this->frm_property_type;
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-map" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('PROPERTY_TYPE');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
			   <table width="100%">
			   	<tr>
				   <td ><?php echo $frm->getElement("adv_search");?></td>
				   <td ><?php echo $frm->getElement('status_search');?></td>
				   <td><input type="submit" value="search" name="search" label="Search" dojoType="dijit.form.Button" 
													iconClass="dijitIconSearch" /></td>
				</tr>
			   </table>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
