<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('BUY_LAND'));
?>	
<?php  $frm = $this->frm_buy;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"
	type="text/javascript"></script>
<script>
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.Textarea");
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
require(["dijit/form/CheckBox","dijit/Dialog","dijit/layout/TabContainer"]);
</script>
<form id='buy_land'	action="<?php echo $this->url(array('module'=>'property','controller'=>'index','action'=>'edit')); ?>"
	enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
	<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(dijit.byId('province').get('value')==0){
					alert('Province required');
					dijit.byId('province').focus();
					return false;
			    }
				return true;
			} else {
				return false;
			}
</script>
	<table width="100%" style="margin-top: -5px;">
		<tr>
			<td>
				<div id="mainTabContainer" style=" position:relative; width:1200px; display:block; height: 530px;" dojoType="dijit.layout.TabContainer" region="center" >
				<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("LAND_INFO");?>" selected="true">
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td colspan="6" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("LAND_INFO")?></td>
						</tr>
					<tr>
                        <td width="33%">
                            <table width="100%">      
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("BUY_NO")?></td>          
                                  <td width="66%"><?php echo $frm->getElement('buy_no');?></td>
                                </tr>
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("TITLE")?>* </td>          
                                    <td width="66%"><?php echo $frm->getElement('title');?></td>
                                </tr>
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("LAND_BLOG")?>*</td>          
                                    <td width="66%"><input id="land_blog"></td>
                                </tr>
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("WIDTH")."(".$tr->translate("HEAD").")";?></td>        
                                    <td width="66%"><?php  echo $frm->getElement('width');?></td>
                                </tr>
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("HEIGHT")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('height');?></td>
                                </tr>
                            </table>
                        </td>
                        <td width="33%">
                          <table width="100%">
                                 <tr>
                                    <td width="33%"><?php echo $tr->translate("SIZE")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('size');?></td>
                                </tr>
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("PRICE")?>*</td>          
                                    <td width="66%"><?php echo $frm->getElement('land_price');?></td>
                                </tr>				
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("THE_CREDENTAIL_NO")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('credentail_no');?></td>
                                </tr>
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("ISSUE_DATE")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('issue_date');?></td>
                                </tr>
                                <tr>			
                                    <td width="33%"><?php echo $tr->translate("BUY_DATE")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('buy_date');?></td>
                                </tr>
                            </table>
                        </td>
                        <td width="33%">
                          <table width="100%">			
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("BORDER_NORTH")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('border_north');?></td>
                                </tr>
                                <tr>		
                                    <td width="33%"><?php echo $tr->translate("BORDER_SOUTH")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('border_south');?></td>
                                </tr>
                                <tr>				
                                    <td width="33%"><?php echo $tr->translate("BORDER_WEST")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('border_west');?></td>
                                </tr>
                                <tr>			
                                    <td width="33%"><?php echo $tr->translate("BORDER_EAST")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('border_east');?></td>
                                </tr>				
                                <tr>
                                    <td width="33%"><?php echo $tr->translate("STATUS")?></td>          
                                    <td width="66%"><?php  echo $frm->getElement('status');?></td>
                                </tr>
                            </table>	
                        </td>
                    </tr>	
                        <tr>
							<td colspan="6"><?php echo $tr->translate("LOCATION")?></td>
                       </tr>
						<tr>							
							<td colspan="6"><?php  echo $frm->getElement('location');?></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("NOTE")?></td>
						</tr>
						<tr>
							<td colspan="6"><?php  	echo $frm->getElement('note');?></td>
						</tr>
						<tr>
							<td colspan="6"><?php echo $frm->getElement('land_img1').$frm->getElement('land_img2');?></td>
							
						</tr>
					</table>
				</div><!-- end tab 1 -->
				<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("SELLER_INFO");?>" selected="false">
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td colspan="6" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("SELLER_INFO")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH")?>*</td>
							<td><?php  echo $frm->getElement('sale_name_kh');?></td>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $frm->getElement('sale_sex');?></td>
							<td><?php echo $tr->translate("AGE")?></td>
							<td><?php  echo $frm->getElement('sale_age');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONALITY")?></td>
							<td><?php  echo $frm->getElement('sale_nationality');?></td>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php  echo $frm->getElement('sale_nation_id');?></td>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><?php  echo $frm->getElement('sale_phone');?></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("RELEVANT_STAKEHOLDER")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH")?></td>
							<td><?php  echo $frm->getElement('sale_relevent_name');?></td>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $frm->getElement('sale_relevent_sex');?></td>
							<td><?php echo $tr->translate("AGE")?></td>
							<td><?php  echo $frm->getElement('sale_relevent_age');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONALITY")?></td>
							<td><?php  echo $frm->getElement('sale_relevent_nationlity');?></td>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php  echo $frm->getElement('sale_relevent_nationid');?></td>
							<td><?php echo $tr->translate("IS")?></td>
							<td><?php  echo $frm->getElement('sale_relevent_is');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CURRENT_ADDRESS")?></td>
							<td colspan="5"><?php  echo $frm->getElement('sale_address');?></td>
						</tr>
						<tr>
							<td colspan="6">
							<?php if (!empty($this->rs['sale_photo1'])){?><img height="60px" src="<?php echo $this->baseUrl().'/images/'.$this->rs['sale_photo1'];?>" /><?php }?>
							<?php echo $frm->getElement('sale_img1').$frm->getElement('old_sale_img1');?>
							<?php if (!empty($this->rs['sale_photo2'])){?><img height="60px" src="<?php echo $this->baseUrl().'/images/'.$this->rs['sale_photo2'];?>" /><?php }?>
							<?php echo $frm->getElement('sale_img2').$frm->getElement('old_sale_img2');?></td>
						</tr>
					</table>
				</div><!-- end tab 2 -->
				<div class="tabContentSection" dojoType="dijit.layout.ContentPane" title="<?php echo $tr->translate("BUYER_INFO");?>" selected="false">
					<table style="margin: 0 auto; width: 100%;" cellspacing="10">
						<tr>
							<td colspan="6" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("BUYER_INFO")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH")?>*</td>
							<td><?php  echo $frm->getElement('buy_name_kh');?></td>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $frm->getElement('buy_sex');?></td>
							<td><?php echo $tr->translate("AGE")?></td>
							<td><?php  echo $frm->getElement('buy_age');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONALITY")?></td>
							<td><?php  echo $frm->getElement('buy_nationality');?></td>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php  echo $frm->getElement('buy_nation_id');?></td>
							<td><?php echo $tr->translate("PHONE")?></td>
							<td><?php  echo $frm->getElement('buy_phone');?></td>
						</tr>
						<tr>
							<td colspan="6" style="border-bottom: solid 1px #ccc;"><?php echo $tr->translate("RELEVANT_STAKEHOLDER")?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NAME_KH")?></td>
							<td><?php  echo $frm->getElement('buyer_relevent_name');?></td>
							<td><?php echo $tr->translate("SEX")?></td>
							<td><?php  echo $frm->getElement('buyer_relevent_sex');?></td>
							<td><?php echo $tr->translate("AGE")?></td>
							<td><?php  echo $frm->getElement('buyer_relevent_age');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("NATIONALITY")?></td>
							<td><?php  echo $frm->getElement('buyer_relevent_nationality');?></td>
							<td><?php echo $tr->translate("NATIONAL_ID")?></td>
							<td><?php  echo $frm->getElement('buyer_relevent_nationid');?></td>
							<td><?php echo $tr->translate("IS")?></td>
							<td><?php  echo $frm->getElement('buyer_relevent_is');?></td>
						</tr>
						<tr>
							<td><?php echo $tr->translate("CURRENT_ADDRESS")?></td>
							<td colspan="5"><?php  echo $frm->getElement('buy_address');?></td>
						</tr>
					</table>
				</div><!-- end tab 3 -->
			</div>
			<table style="margin: 0 auto; width: 100%;" cellspacing="10">
					<tr>
						<td colspan="6" align="center"><input type="reset"
							label="<?php echo $tr->translate('CLEAR');?>"
							dojoType="dijit.form.Button" iconClass="dijitIconClear" /> <input
							type="submit" value="SAVE_CLOSE" tabindex="2"
							label="<?php echo $tr->translate('SAVECLOSE');?>"
							id="save_close" dojoType="dijit.form.Button" name="save_close"
							iconClass="dijitEditorIcon dijitEditorIconSave" />
					</tr>
				</table>
			</td>
		</tr>
	</table>
</form>
<table>
	<tr>
	</tr>
</table>
<?php echo $this->frmPopupPropertyType;
echo $this->frmPopuplandblog;
?>
<script type="text/javascript">
var propertyType_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->pro_type));?> );
var landblog_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->land_blog));?> );

dojo.ready(function(){
	
	try{
		new dijit.form.FilteringSelect({
			store: propertyType_store,
			autoComplete: true,
			required: true,		           
			name: "property_type",
			id: "property_type",
			value:'<?php echo $this->rs['land_type']?>',
			searchAttr: "name",
			class: 'fullside',
				onChange: function() {
					//district = dijit.byId('property_type').get('value');
					showPopupForm();
				}  
			}, "property_type");

		new dijit.form.FilteringSelect({
			store: landblog_store,
			autoComplete: true,
			required: true,		           
			name: "land_blog",
			id: "land_blog",
			searchAttr: "name",
			value:'<?php echo $this->rs['land_blog']?>',
			class: 'fullside',
				onChange: function() {
					//district = dijit.byId('property_type').get('value');
					showLandBlogPopupForm();
				}  
			}, "land_blog");
	}catch(e){
		alert(e);
	}
});

function showLandBlogPopupForm(){
	land_blog = dijit.byId('land_blog').get('value');
	if(land_blog==''){
		alert('សូមជ្រើសរើសប្លុកទីតាំងដី');
		dijit.byId('land_blog').focus();
		return false;
	}else if(land_blog==-1){
		dijit.byId('frm_landblog').show();
	}
}
url_landblog = '<?php echo $this->url(array('module'=>'property','controller'=>'blog','action'=>'addlandblog'));?>';
function addNewLandBlog(){
	if(dijit.byId('frm_landblog').validate()) {
		dojo.xhrPost({
			url:url_landblog,	
			form:dojo.byId('form_landblog'),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('title_kh').get('value')
				};		
				addDataToSelectbox(dijit.byId('land_blog'), landblog_store, Itemmake, data);	
				dijit.byId('land_blog').attr('value',data);
				dijit.byId('frm_landblog').reset();
				dijit.byId('frm_landblog').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function showPopupForm(){
	property_type = dijit.byId('property_type').get('value');
	if(property_type==''){
		alert('Please Select Property Type');
		dijit.byId('property_type').focus();
		return false;
	}else if(property_type==-1){
		dijit.byId('frm_propertytype').show();
	}
}
url_property = '<?php echo $this->url(array('module'=>'group','controller'=>'propertiestype','action'=>'add-propertytype'));?>';
function addNewPropertytype(){
	if(dijit.byId('frm_propertytype').validate()) {
		dojo.xhrPost({
			url:url_property,	
			form:dojo.byId('form_propertytype'),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('type_nameen').get('value')
				};		
				addDataToSelectbox(dijit.byId('property_type'), propertyType_store, Itemmake, data);	
				dijit.byId('property_type').attr('value',data);
				dijit.byId('frm_propertytype').reset();
				dijit.byId('frm_propertytype').hide();
			},
			error: function(err) {
				alert(err);
			}
		});
	}
}
function calculateSize(){
	width = dijit.byId('width').get('value');
	height = dijit.byId('height').get('value');
	if(width==0){
		width="1";
		dijit.byId('width').attr('value','1')
	}
	if(height==0){
		height="1";
		dijit.byId('height').attr('value','1')
	}
	//alert(height);
	var size = Number(width * height);
	dijit.byId('size').attr('value',size);
}
</script>