<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("ADD_PRODUCT_CATEGORY"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
 	$frm_degree= $this->frm_degree;
?>
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
	dojo.require("dijit.form.Textarea");
	dojo.require("dijit.form.NumberTextBox");
</script>
<style>
.dijitTextArea[cols].dijitTextArea[cols]{
	width: 99%;
}
ul.opt-school {
    list-style-type: none;
}
 input[type=checkbox],  input[type=radio]{
	height: 15px;
    display: initial;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-server " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('ADD_PRODUCT_CATEGORY');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form  id='frm_degree' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					loadingBlock();
					return true;
				}else {
					return false;
				}
			</script>
	    	<div class="card-box">
				<div class="col-md-5 col-sm-4 col-xs-12">
		    		<div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TITLE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_degree->getElement("title");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TITLE_EN");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_degree->getElement("title_en");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("SHORTCUT");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_degree->getElement("shortcut");?>
		                </div>
		             </div>
					 <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ORDERING");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_degree->getElement("ordering");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm_degree->getElement("note");?>
		                </div>
		             </div>
		         </div>
		         <div class="clearfix"></div>
		         <div class="card-box mt-20">
	               	<div class="col-md-5 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
	               		<input type="submit"  label="<?php echo $tr->translate("SAVE_CLOSE");?>" id="save_close" name="save_close" value="save_close"
							dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
						<input type="submit"  label="<?php echo $tr->translate("SAVE_NEW");?>" id="save_new" name="save_new" 
							dojoType="dijit.form.Button" iconClass="dijitEditorIcon dijitEditorIconSave" />
	               	</div>
	             </div>
	    	</div>
    	</form>
    </div>
</div>
<script type="text/javascript">

</script>