<?php 
     $this->tr=Application_Form_FrmLanguages::getCurrentlanguage();
     $tr = Application_Form_FrmLanguages::getCurrentlanguage();
     $frm = $this->frm;
?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<style>
#table tr td{
	border:1px solid #cccccc;
	text-align: center;
}
#table tr th{
	background: #cccccc;
	border:1px solid #ddd;
}
</style>
<title><?php echo $this->tr->translate("POLICY_INTEREST_SETTING")?></title>
 <div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-tasks" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('POLICY_INTEREST_SETTING');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form action="" dojoType="dijit.form.Form" method="post" enctype="multipart/form-data">
			<script type="dojo/method" event="onSubmit">   
	  			 if(this.validate()) {
					var rowId = $('#identity').val();
					if(rowId==''){ 
						alert("<?php echo $tr->translate("PLEASE_ADD_RECORD_SETTING");?>");
						return false;
					}
					loadingBlock();
					return true;
	  			 }else {
					return false;
	   			}
			</script>
			<div class="card-box">
				<div class="col-md-4 col-sm-4 col-xs-12">
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TITLE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("title");?>
		                </div>
		             </div>
		             <div class="form-group">
		                <label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
		                <div class="col-md-7 col-sm-7 col-xs-12">
		                	<?php echo $frm->getElement("note");?>
		                </div>
		             </div>
				</div>
				<div class="col-md-8 col-sm-8 col-xs-12">
					<table class="collape tablesorter" id="table_row" style="width:100%; white-space: nowrap;border:1px solid #ddd;">
				    	<tr id="head-title" class="head-td" align="center"></tr>
					</table>
					<input type="hidden" name="identity" id="identity" dojoType="dijit.form.TextBox" value="" >
					<input type="button" label="<?php echo $tr->translate('ADD_ROW');?>" dojoType="dijit.form.Button" 
						iconClass="dijitIconEditProperty" onclick="addRow();" />
				</div>
				<div class="clearfix"></div>
			</div>
			<div class="clearfix"></div>
	       	<div class="card-box mt-20">
               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
               		<input type="submit" value="save_close" id="save_close" name="save_close" label="<?php echo $tr->translate("SAVE_CLOSE");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
					<input type="submit" value="save_close" id="save_new" name="save_new" label="<?php echo $tr->translate("SAVE_NEW");?>" dojoType="dijit.form.Button" 
						iconClass="dijitEditorIcon dijitEditorIconSave" />
               	</div>
             </div>
		</form>
    </div>
</div>
<script type="text/javascript">
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dojo.NodeList-manipulate");
    dojo.require("dijit.form.Textarea");
    dojo.require("dijit.form.NumberTextBox");
    
    var dept_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
	dojo.ready(function(){ 
		addRow();
	});
	
	var col= 0; var no=0;
	var title = 0;
	function addRow() {
		col++;no++;
		template='';
		temp = "";
	
		if(title!=1){
			temp+='<td><?php echo $tr->translate("DEL");?></td>';
			temp+='<td><?php echo $tr->translate("N_O");?></td>';
			temp+='<td><?php echo $tr->translate("AMOUNT_MONTH");?></td>';
			temp+='<td><?php echo $tr->translate("INTEREST_VALUE");?></td>';
			temp+='<td><?php echo $tr->translate("NOTE");?></td>';
			dojo.query("#head-title").append(temp);
			title=1;
		}
			
		template+='<td width="2%" align="center"><img onclick="deleteRecord('+col+');" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
		template+='<td align="center" width="2%">'+no+'</td>';
		template+='<td width="10%"><input required="required" dojoType="dijit.form.NumberTextBox" class="fullside" id="max_month'+col+'" name="max_month'+col+'" placeholder="'+'<?php echo $tr->translate("AMOUNT_MONTH");?>" value="" type="text"  ></td>';	
		template+='<td width="10%"><input dojoType="dijit.form.TextBox" class="fullside" id="percent_value'+col+'" name="percent_value'+col+'" placeholder="'+'<?php echo $tr->translate("INTEREST_VALUE");?> " value="" type="text"  ></td>';	
		template+='<td width="10%"><input dojoType="dijit.form.TextBox" class="fullside" id="note'+col+'" name="note'+col+'" placeholder="'+'<?php echo $tr->translate("NOTE");?> " value="" type="text"  ></td>';	
		
		tmp='<tr id="row'+col+'">';
		tmp+="</tr>";
		dojo.query("#table_row").append(tmp);
		if($("#identity").val()!="") {
			var identity = $("#identity").val();
			$("#identity").val(identity+','+col);
		} else {$("#identity").val(col);}
		dojo.html.set(dojo.byId("row"+col),template , {
		     parseContent: true,
		});
	}
	function deleteRecord(index) {
		var identity = $('#identity').val();
		var arrays = identity.split(',');
		for(var i=0;i<arrays.length;i++) {
			if(arrays[i] == index) arrays.splice(i,1);
		}
		var strings = arrays.join(',');
		$('#identity').val(strings);
		dojo.query("#row"+index).remove();
	}
	
</script>