<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('COPY_PROPERTY'));
?>	
<?php  $frm = $this->frm_client;?>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script>
	dojo.require("dojo.data.ItemFileWriteStore");  
	dojo.require("dijit.form.DateTextBox");
	dojo.require("dijit.form.NumberTextBox");
	dojo.require("dijit.Dialog");
	dojo.require("dijit.form.Textarea");
</script>
<div class="card">
	<div class="card-content collapse show">
		<form id='add_client' action=" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
			<script type="dojo/method" event="onSubmit">			
			if(this.validate()) {
				if(checkhouse_title==1){
					alert("<?php echo $tr->translate('DUPLICATE_PROPERTY_MSG')?>");
					dijit.byId('land_address').focus();
					return false;
				}
				if(checkAmountHouse==1){
						alert("<?php echo $tr->translate('PROPERTY_IS_LIMIT_BY_BRANCH');?>");
						dijit.byId('branch_id').focus();
						return false;
					}
				loadingBlock();
				return true;
			} else {
				return false;
			}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="glyphicon glyphicon-copy" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('COPY_PROPERTY');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-money" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("PRICE_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BRANCH_NAME");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('branch_id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("LOAN_NO");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('landcode');?>
									   </div>
									</div>
														
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("HEAD_TITLE_NO");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('hardtitle');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_CODE");?>
									   <span id="message" style="color: red; display: block;"></span>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('land_address');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STREET");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('street');?>
											<?php echo $frm->getElement('streetCode');?>
									   </div>
									</div>
									
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PROPERTY_TYPE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<input id="property_type" />
									   </div>
									</div>
									
									 <div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("TYPE_STORE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('type_tob');?>
									   </div>
									</div>
									
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("LAND_PRICE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('land_price');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("HOUSE_PRICE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('house_price');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PRICE");?>
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('price');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	                
			    </div>  
			    <div class="col-md-4 col-sm-4 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-map" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INFO_OF_LAND");?></p>
										</div> 
									</div>
									 <div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("WIDTH");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('width');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("HEIGHT");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('height');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SIZE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('size');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SOUTH");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('south');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NORTH");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('north');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("WEST");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('west');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("EAST");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('east');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('desc');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS_BUY");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('buy_status');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STATUS");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('status');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
			    </div>
			    <div class="col-md-4 col-sm-4 col-xs-12">
					 <?php $is_show =$this->data['showhouseinfo']; 
					if($is_show==1){?>
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-home" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("HOUSE_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
										<div class="col-md-6 col-sm-6 col-xs-12">
											<label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("WIDTH");?> :
											</label>
											<div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement('width_land');?>
											</div>
										</div>
										<div class="col-md-6 col-sm-6 col-xs-12">
											<label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("HEIGHT");?> :
											</label>
											<div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement('height_land');?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<div class="col-md-6 col-sm-6 col-xs-12">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("SIZE");?> :
											</label>
											<div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement('full_size');?>
											</div>
										</div>
										<div class="col-md-6 col-sm-6 col-xs-12">
											<label class="control-label  col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("FLOOR");?> :
											</label>
											<div class="col-md-7 col-sm-7 col-xs-12">
													<?php echo $frm->getElement('floor');?>
											</div>
										</div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BEDROOM");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('bedroom');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("LIVING");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('living');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DINNER_ROOM");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('dinnerroom');?>
									   </div>
									</div>
									
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("PARKING_SPACE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('parkingspace');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BUIDING_YEAR");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('buidingyear');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	                <?php }?>
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-building" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("BUILD_INFO");?></p>
										</div> 
									</div> 
									
									<div class="form-group">
									   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BUILD_PERCENTAGE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('buildPercentage');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BUILD_PERCENTAGE_NOTE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('buildPercentageNote');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
			    </div>      
	    	</div>
	    	<div class="clearfix"></div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_close" dojoType="dijit.form.Button" name="save_new" /> 
				</div>
	    	</div>
		</form>
	</div>
</div>
<?php echo $this->frmPopupPropertyType;?>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("STREET")?>'"  id="frm_street" >
		<form id="form_propertytype" >
			<div class="card-box">
				<div class="form-group">
				   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STREET_CODE");?>
				   </label>
				   <div class="col-md-7 col-sm-7 col-xs-12">
						<input dojoType="dijit.form.TextBox" placeholder="<?php echo $tr->translate("STREET_CODE")?>" class="fullside" id="streetNewCode" name="streetNewCode" value="" type="text">
				   </div>
				</div>
				<div class="form-group">
				   <label class="control-label bold col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("STREET_NAME");?>
				   </label>
				   <div class="col-md-7 col-sm-7 col-xs-12">
						<input dojoType="dijit.form.ValidationTextBox" placeholder="<?php echo $tr->translate("STREET_NAME")?>" required="true" class="fullside" id="newStreet" name="newStreet" value="" type="text">
				   </div>
				</div>
			</div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					<input type="button"  id="save_street" value="Save" label="<?php echo $tr->translate('GO_SAVE');?>" dojoType="dijit.form.Button" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk" onclick="addNewStreet();"/>
	    		</div>
	    	</div>
		</form>
	</div>
</div>
<div class="dijitHidden">
	<div data-dojo-type="dijit.Dialog" data-dojo-props="title:'<?php echo $tr->translate("TYPE_STORE")?>'"  id="frm_cheque" >
		<form id="form_cheque" dojoType="dijit.form.Form" >
			<table style="margin: 0 auto; width: 100%;" cellspacing="7">
				<tr>
					<td>
						<input dojoType="dijit.form.ValidationTextBox" required="true" class="fullside" id="addchequename" name="addchequename" value="" type="text">
					</td>
				</tr>
				<tr>
					<td colspan="2" align="center">
						<input type="button" id="save_cheque" value="Save" label="<?php echo $tr->translate('GO_SAVE');?>" dojoType="dijit.form.Button"
							iconClass="dijitEditorIcon dijitEditorIconSave" onclick="addNewCheque();"/>
					</td>
				</tr>
			</table>
		</form>
	</div>
</div>
<script type="text/javascript">
require(["dojo/ready"], function(ready){
	new dijit.form.FilteringSelect({
		name: "type_tob",
		id: "type_tob",
		autoComplete: false,
		required: false,
		queryExpr: "*${0}*",     
		searchAttr: "name",
		class: 'fullside',
		onChange: function() {
			popupIssuer();
	    }
	}, "type_tob");
});
function popupIssuer(){
	cheque_issuer = dijit.byId('type_tob').get('value');
	if(cheque_issuer==-1){
		dijit.byId('save_cheque').set('disabled',false);
		dijit.byId('frm_cheque').show();
	}
}
var chequeStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->alltobtype));?> );
function addNewCheque(){
	if(dijit.byId('form_cheque').validate()){
		var Itemmake = {					
			id: dijit.byId('addchequename').get('value'),
		    name: dijit.byId('addchequename').get('value')
		};		
		addDataToSelectbox(dijit.byId('type_tob'),chequeStore , Itemmake, dijit.byId('addchequename').get('value'));
		dijit.byId('form_cheque').reset();
		dijit.byId('frm_cheque').hide();
		dijit.byId('save_cheque').set('disabled',true);
	}
}
function showStreet(){
	dijit.byId('save_street').set('disabled',false);
	street = dijit.byId('street').get('value');
	if(street==''){
		alert("<?php echo $tr->translate("PLEASE_SELECT_STREET")?>");
		dijit.byId('street').focus();
		return false;
	}else if(street==-1){
		dijit.byId('frm_street').show();
	}
	checkTitle();
}
var StreetStore  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->street));?> );
function addNewStreet(){
	if(dijit.byId('frm_street').validate()) {
		var Itemmake = {					
				id: dijit.byId('newStreet').get('value'),
			    name: dijit.byId('newStreet').get('value')
		};		
		addDataToSelectbox(dijit.byId('street'), StreetStore, Itemmake, dijit.byId('newStreet').get('value'));	
		dijit.byId('newStreet').attr('value',dijit.byId('newStreet').get('value'));
		dijit.byId('streetCode').attr('value',dijit.byId('streetNewCode').get('value'));
		
		dijit.byId('frm_street').reset();
		dijit.byId('frm_street').hide();
		dijit.byId('save_street').set('disabled',true);

		
	}
}
var propertyType_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode($this->pro_type));?> );
dojo.ready(function(){	
		new dijit.form.FilteringSelect({
			store: propertyType_store,
			autoComplete: true,
			required: true,		           
			name: "property_type",
			id: "property_type",
			value: "<?php echo $this->row['property_type'];?>",
			searchAttr: "name",
			class: 'fullside',
				onChange: function() {
					showPopupForm();
				}  
			}, "property_type");
		getPropertyNo();
		checkTitle();
		dijit.byId('land_address').set('readOnly',false);
		dijit.byId('street').set('readOnly',false);
		dijit.byId('land_price').set('readOnly',false);
		dijit.byId('house_price').set('readOnly',false);
		dijit.byId('buy_status').set('value',0);
		
		var branch_id = dijit.byId('branch_id');
		 branch_id.on('change', function(evt) {
			 getAllAmountPrpertyByBranch();
		});
		getAllAmountPrpertyByBranch();
});
function showPopupForm(){
	dijit.byId('save_property').set('disabled',false);
	property_type = dijit.byId('property_type').get('value');
	if(property_type==''){
		alert('Please Select Property Type');
		dijit.byId('property_type').focus();
		return false;
	}else if(property_type==-1){
		dijit.byId('frm_propertytype').show();
	}
}
url_property = '<?php echo $this->url(array('module'=>'project','controller'=>'propertiestype','action'=>'add-propertytype'));?>';
function addNewPropertytype(){
	if(dijit.byId('frm_propertytype').validate()) {
		dijit.byId('save_property').set('disabled',true);
		dojo.xhrPost({
			url:url_property,	
			form:dojo.byId('form_propertytype'),
			handleAs:"json",
			load: function(data) {
				var Itemmake = {					
						id: data,
					    name: dijit.byId('type_nameen').get('value')
				};		
				addDataToSelectbox(dijit.byId('property_type'), propertyType_store, Itemmake, data);	
				dijit.byId('property_type').attr('value',data);
				dijit.byId('frm_propertytype').reset();
				dijit.byId('frm_propertytype').hide();
				dijit.byId('save_property').set('disabled',false);
			},
			error: function(err) {
			
			}
		});
	}
}
url_getPropertyNo = '<?php echo $this->url(array('module'=>'project','controller'=>'land','action'=>'get-property-no'));?>';
function getPropertyNo(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getPropertyNo,	
		content:{ 
			'branch_id': branch_id
		},
		handleAs:"json",
		load: function(data) {	
		    dijit.byId('landcode').attr('value',data);
		},
		error: function(err) {
		}
	});
}
function CalculatePrice(){
	house_price = dijit.byId('house_price').get('value');
	land_price = dijit.byId('land_price').get('value');
	var price = Number(house_price + land_price);
	dijit.byId('price').attr('value',price);
}
function calCulateSize(){
	width = dijit.byId("width").get('value');
	height = dijit.byId("height").get('value');
	totalsize = width*height;
	dijit.byId("size").attr('value',totalsize);
}
function calCulateFullSize(){
	width = dijit.byId("width_land").get('value');
	height = dijit.byId("height_land").get('value');
	totalsize = width*height;
	dijit.byId("full_size").attr('value',totalsize);
}
var checkhouse_title=0;
var old_title = '<?php echo $this->row['land_address'];?>';
url_CheckTitle = '<?php echo $this->url(array('module'=>'project','controller'=>'land','action'=>'check-title'));?>';
function checkTitle(){
	title = dijit.byId('land_address').get('value');
	branch_id = dijit.byId('branch_id').get('value');
	street = dijit.byId('street').get('value');
	property_type = dijit.byId('property_type').get('value');
	if(title=='' || street==''){ document.getElementById('message').innerHTML ='';return false;}
	dojo.xhrPost({
		url:url_CheckTitle,	
		content:{ 
			'branch_id': branch_id , 'land_address': title,'street': street,'property_type': property_type
		},
		handleAs:"json",
		load: function(data) {	
			if(data !== false ){
				checkhouse_title=1;
		   		document.getElementById('message').innerHTML ='<?php echo $tr->translate('DUPLICATE_PROPERTY_MSG')?>';
		   		dijit.byId('land_address').focus();
		   		return false;
			}else{
				checkhouse_title=0;
				document.getElementById('message').innerHTML ='';
				return true;
			}
		},
		error: function(err) {
			alert(err);
		}
	});
}

var checkAmountHouse=0;
url_getPropertyByBranch = '<?php echo $this->url(array('module'=>'project','controller'=>'land','action'=>'getpropertyamount'));?>';
function getAllAmountPrpertyByBranch(){
	branch_id = dijit.byId('branch_id').get('value');
	if(branch_id==0 || branch_id==-1){
		return false;
	}
	dojo.xhrPost({
		url:url_getPropertyByBranch,	
		content:{ 
			'branch_id': branch_id
		},
		handleAs:"json",
		load: function(data) {	
			
		   if(data==1){
			   checkAmountHouse=0;
		   }else{
			   checkAmountHouse=1;
		   }
		},
		error: function(err) {
			alert(err);
		}
	});
}
</script>