<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("CUSTOMER_LIST"));
	$frm = $this->frm_search;
	$frms=$this->frm_client;
	$urlEdit = $this->baseUrl()."/group/index/edit/id/";
	$urlProfile = $this->baseUrl()."/group/index/view/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-map" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CUSTOMER_LIST');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="<?php echo $this->url(array('module'=>'group','controller'=>'index','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frms->getElement('customer_id');?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement('status');?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement('start_date');?>
                   </div>
                  <div class="col-md-2 col-sm-2 col-xs-12">
                   		<?php echo $frm->getElement('end_date');?>
                   </div>
                   <div class="col-md-2 col-sm-2 col-xs-12">
                   </div>
                </div>
                <div class="form-group">
					<div class="col-md-2 col-sm-2 col-xs-12">
						<?php echo $frms->getElement('province');?>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<input id="district" >
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<input id="commune" >
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<input id="village" >
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
					</div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?> 
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");

var district_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var commune_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );
var village_store  = getDataStorefromJSON('id','name', <?php print_r(Zend_Json::encode(array()));?> );

dojo.ready(function(){
	new dijit.form.FilteringSelect({
		store: district_store,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "district",
		id: "district",
		searchAttr: "name",
		class: 'fullside',
		placeholder:'<?php echo $tr->translate("DISTRICT");?>',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះ ស្រុក/ខ័ណ្ឌ!",	
			onChange: function() {
				district = dijit.byId('district').get('value');
				if(district==-1){
					showPopupdistrict();
					}
					filterCommune();
			}  
		}, "district");
		 
		new dijit.form.FilteringSelect({
		store: commune,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "commune",
		id: "commune",
		searchAttr: "name",
		placeholder:'<?php echo $tr->translate("COMMUNE");?>',
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឃុំ/សង្កាត់",	
			onChange: function() {
				commune = dijit.byId('commune').get('value');
				if(commune==-1){
					showPopupCommune();
				}
				else{
					filterVillage();
				}
	  }
		}, "commune");
		 
		new dijit.form.FilteringSelect({
		store: village_store,
		autoComplete:false,
		queryExpr:'*${0}*',
		required: false,		           
		name: "village",
		id: "village",
		placeholder:'<?php echo $tr->translate("VILLAGE");?>',
		searchAttr: "name",
		class: 'fullside',
		missingMessage:"អ្នក​ភ្លេច​បំពេញ​ ឈ្មោះភូមិ!",	
			onChange: function() {
				vill = dijit.byId('village').get('value');
				if(vill==-1){
					showPopupVillage();
				}
			}
		}, "village");
});
url_getdistrict = '<?php echo $this->url(array('module'=>'other','controller'=>'district','action'=>'get-district'));?>';
function filterDistrict(){
	pro_id = dijit.byId('province').get('value');
	if(pro_id==0){
		return false;}
		dojo.xhrPost({
			url:url_getdistrict,	
			content:{ 
				'pro_id': pro_id,'no_addnew':1
			},
			handleAs:"json",
			load: function(data) {	
				district_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('district').set('store', district_store);
			},
			error: function(err) {
			}
		});	
}
url_getcommune = '<?php echo $this->url(array('module'=>'other','controller'=>'commune','action'=>'get-commune'));?>';
function filterCommune(){
	distict_id = dijit.byId('district').get('value');
	if(distict_id==0){
		return false;}
	dojo.xhrPost({
		url:url_getcommune,	
		content:{ 
			'district_id': distict_id,'no_addnew':1
		},
		handleAs:"json",
		load: function(data) {	
			commune_store  = getDataStorefromJSON('id','name', data);		
		    dijit.byId('commune').set('store', commune_store);
		},
		error: function(err) {
		}
	});
}
url_getvillage = '<?php echo $this->url(array('module'=>'other','controller'=>'village','action'=>'get-allvillage'));?>';
function filterVillage(){
	commune_id = dijit.byId('commune').get('value');
	if(commune_id==0){
		return false;}
		dojo.xhrPost({
			url:url_getvillage,	
			content:{ 
				'commune_id': commune_id,'no_addnew':1
			},
			handleAs:"json",
			load: function(data) {	
				village_store  = getDataStorefromJSON('id','name', data);		
			    dijit.byId('village').set('store', village_store);
			},
			error: function(err) {
				alert(err);
			}
		});
}
var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="edit"){
				url='<?php echo $urlEdit;?>';
			}else if(key=="profile"){
				url='<?php echo $urlProfile;?>';
			}
			gotoAction();
		},
		items: {
			"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
			"profile": {name: "<?php echo $tr->translate("CUSTOMER_PROFILE");?>", icon: "fa-user"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>
