<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('CUSTOMER_PROFILE'));
	$rs = $this->client_list;
	$base_url = Application_Form_FrmMessage::getUrl("/");
	
	$photo='no-profile.png';
	if(!empty($rs['photo_name'])){
		$photo=$rs['photo_name'];
	}
	
	$key = new Application_Model_DbTable_DbKeycode();
	$data =$key->getKeyCodeMiniInv(TRUE);
	$montFomat="d-m-Y";
	if(MONTH_FORMATE_DATE_RECEIPT==1){
		$montFomat="d-M-Y";
	}
?>	
<style>
.border-cover {
  border: 1px solid #ccc;
  padding: 0px 4px;
  background: #E5F2F5;
}
.menureport ul li {
    display: inline-block;
    float: none;
}
</style>
<div class="menureport">
	<ul>
		<li class="preview"><a title="Preview" href="#" onclick="preview();"></a></li>
		<li class="print"><a href="#" title="Print" onclick="doPrint();" ></a></li>
	</ul>
</div>
<style>
tr.head td h2 {
    font-size: 16px !important;
    line-height: 27px !important;
}
.b{ font-weight: bold; }

p.padding-left {
    line-height: 24px !important;
}

table#exportExcel tr td {
    font-size: 14px !important;
}
label.title {
    font-size: 14px !important;
    min-width: 100px !important;
}
label.value {
    font-size: 14px !important;
    min-width: 100px !important;
}
</style>
<div class="ptss-frame  js-ptss-frame "><!-- is-opened -->
	<div class="ptss__toggle-btn  js-ptss-toggle-btn ">
		<i class="fa fa-print"></i>
	</div>
    <div class="ptss__header"><?php echo $tr->translate("PRINT");?></div>
		<div class="ptss__settings">
			<div class="ptss__single-setting" id="ptss__layout">
				<div class="ptss__setting-control">
					<div class="ptss__layout-wrapper">
						<a class="qButton" title="<?php echo $tr->translate("Preview");?>" href="#" onclick="preview();"><i class="fa fa-search" aria-hidden="true"></i></a>
						<a class="qButton print" href="#" title="<?php echo $tr->translate("PRINT");?>" onclick="doPrint();" ><i class="fa fa-print" aria-hidden="true"></i></a>
					</div>
				</div>
		</div>
	 </div>
</div>
<div style="background: #fff;width: 31cm;margin: 0 auto;min-height: 27cm; padding: 0.5cm;">
			<div id="divPrint">
				<style>
		   			label.value{
		   				font-weight: initial;
		   				min-width: 100px;
		   				font-size: 14px;
		   				display: inline-block;
					}
					p.padding-left {
					    padding-left: 10px;
						    line-height: 20px;
					}
					label.title {
					    font-size: 14px;
					    min-width: 80px;
					    display: inline-block;
					}
					.border {
					        border: none;
					    display: block;
					    width: 100%;
					    height: 1px;
					    margin-bottom: 10px;
					}
					
						table.content-data{
									border-collapse:collapse;
									width:100%;
									border:1px solid #000; 
									font-family:'Times New Roman','Khmer OS Battambang';
									font-size:12px !important;
									white-space: nowrap;
									margin:0 auto;
								}
								table.content-data tr.style-head {
								   line-height: 25px; padding:1px 0px; white-space: nowrap;height: 22px; 
									background: #ccd9ff;
									text-align: center;
								}
								table.content-data tr.style-rowdata {
									font-size:12px; 
									height: 23px;
								}
								table.content-data td {
									padding: 2px;
								}
								.border_bottom{
									border-bottom:2px solid #000;
								}
								tr.style-rowdata.hover.context-menu-one.completedCss {
									background: #00e01c0d;
								}
								table tr td{
									padding:0 2px;
								}
		  		 </style>
				<table width="100%" style="font-size:12px; font-family:Tahoma,'Khmer OS Battambang';"> 
					<tr class="head">
						<td colspan="2"  valign="middle">
							<img alt="" src="<?php echo $this->baseUrl()."/images/logo.jpg"?>" style="max-height: 130px;display: inline-block;margin-right: 10px;">
							<div style=" display: inline-block;    vertical-align: top;">
							<h2 style="font-size:14px;     line-height: 14px; font-weight: initial; font-family:'Khmer OS Muol Light';" ><?php //echo empty($data['client_company_name'])?"":$data['client_company_name'];//$tr->translate("BRAND_TITLE");?></h2>
						</div>
					   </td>
					   <td width="30%" align="center">
					   		<h2 style="font-size:16px;line-height: 14px; font-weight: initial; font-family:'Khmer OS Muol Light';" >ព្រះរាជាណាចក្រកម្ពុជា</h2>
					   		<h2 style="font-size:14px;line-height: 14px; font-weight: initial; font-family:'Khmer OS Muol Light';">ជាតិ សាសនា ព្រះមហាក្សត្រ</h2>
					   		<img alt="" src="<?php echo $this->baseUrl()."/images/sign.PNG"?>" style=" width: 120px;">
					   </td>
					</tr>
					<tr class="head">
					   <td colspan="3" align="center">
					   		<h2 style="font-size:16px;font-weight: initial;font-family:'Khmer OS Muol Light';text-decoration: underline;" >ប្រវត្តិរូបសង្ខេប</h2>
					   </td>
					</tr>
					<tr>
					   <td colspan="3">
					   		<table style="font-family:'Khmer OS Battambang'; border-collapse:collapse;  font-size:14px; white-space: nowrap;" width="100%" cellspacing="0">
						    	<tr>
						    		<td align="center" style="font-size:14px; font-weight: initial; font-family:'Khmer OS Muol Light';">
						    			<img src="<?php echo $this->baseUrl();?>/images/<?php echo $photo;?>" style="width: 120px;/* max-height: 120px; */border: solid 1px #a29f9f;height: 130px;"/>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight: initial; font-family:'Khmer OS Muol Light';">
						    			I. ព័ត៌មានអតិថិជន
						    			<div class="border"></div>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-family:'Khmer OS Battambang';">
						    			<p class="padding-left">
						    			<label class="title">នាមត្រកូល-ខ្លួន</label> : <label class="value"><?php echo $rs['name_kh'];?></label> <label class="title">ភេទ</label> : <label class="value"><?php echo $rs['sex'];?></label> <label class="title">សញ្ជាតិ</label> : <label class="value"><?php  echo $rs['nationality'];?></label> 
						    			</p>
						    			<p class="padding-left">
						    			 <label class="title">អត្តលេខ</label> : <label class="value"><?php echo $rs['client_number'];?></label> <label class="title">ថ្ងៃ ខែ ឆ្នាំកំណើត</label> : <label class="value"><?php echo date("d M Y",strtotime($rs['dob']));?></label>  <label class="title">មុខរបរ</label> : <label class="value"><?php //echo $rs['job'];?></label>
						    			</p>
						    			<p class="padding-left">
						    			<label class="title">ប្រភេទឯកសារ</label> : <label class="value"><?php echo $rs['doc_name'];?></label> <label class="title">លេខសម្គាល់</label> : <label class="value"><?php echo $rs['nation_id'];?></label> <label class="title">លេខទូរសព្ទ</label> : <label class="value"><?php echo $rs['phone'];?></label>
						    			</p>
						    					
						    			<p class="padding-left">
						    			<label class="title">អាសយដ្ឋាន</label> : <label class="value"><?php echo empty($rs['house'])?"":"ផ្ទះលេខ ".$rs['house']; echo empty($rs['street'])?"":" ផ្លូវលេខ ".$rs['street']; echo empty($rs['village_name'])?"":" ភូមិ ".$rs['village_name']; echo empty($rs['commune_name'])?"":" ឃុំ/សង្កាត់ ".$rs['commune_name']; echo empty($rs['district_name'])?"":" ស្រុក/ខណ្ឌ ".$rs['district_name']; echo empty($rs['province_en_name'])?"":" រាជធានី/ខេត្ត ".$rs['province_en_name'];?></label> 
						    			</p>
						    		</td>
						    	</tr>
						    	<tr><td>&nbsp;</td></tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight: initial; font-family:'Khmer OS Muol Light';">
						    			II. ព័ត៌មានអ្នកទិញជាមួយ
						    			<div class="border"></div>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-family:'Khmer OS Battambang';">
						    			<p class="padding-left">
						    			<label class="title">ឈ្មោះ </label> : <label class="value"><?php echo $rs['hname_kh'];?></label> <label class="title">ភេទ</label> : <label class="value"><?php if(!empty($rs['hname_kh'])) echo $rs['ksex'];?></label> <label class="title">សញ្ជាតិ</label> : <label class="value"><?php if(!empty($rs['hname_kh'])) echo $rs['p_nationality'];?></label>
						    			</p>
						    			<p class="padding-left">
						    			<label class="title">ត្រូវជា</label> : <label class="value"><?php if(!empty($rs['hname_kh'])) echo $rs['join_type'];?></label> <label class="title">ថ្ងៃ ខែ ឆ្នាំកំណើត</label> : <label class="value"><?php if(!empty($rs['hname_kh'])) echo date("d M Y",strtotime($rs['dob_buywith']));?></label> <label class="title">លេខទូរសព្ទ </label> : <label class="value"><?php if(!empty($rs['hname_kh'])) echo $rs['lphone'];?></label>
						    			</p>
						    			<p class="padding-left">
						    			<label class="title">ប្រភេទឯកសារ</label> : <label class="value"><?php if(!empty($rs['hname_kh'])) echo $rs['doc_name'];?></label> <label class="title">លេខសម្គាល់</label> : <label class="value"><?php if(!empty($rs['hname_kh'])) echo $rs['rid_no'];?></label>
						    			</p>
						    			<p class="padding-left">
						    			<label class="title">អាសយដ្ឋាន</label> : <label class="value"><?php if(!empty($rs['hname_kh'])) echo empty($rs['ghouse'])?"":"ផ្ទះលេខ ".$rs['ghouse']; echo empty($rs['dstreet'])?"":" ផ្លូវលេខ ".$rs['dstreet']; echo empty($rs['p_village_name'])?"":" ភូមិ ".$rs['p_village_name']; echo empty($rs['p_commune_name'])?"":" ឃុំ/សង្កាត់ ".$rs['p_commune_name']; echo empty($rs['p_district_name'])?"":" ស្រុក/ខណ្ឌ ".$rs['p_district_name']; echo empty($rs['p_province_en_name'])?"":" រាជធានី/ខេត្ត ".$rs['p_province_en_name'];?></label> 
						    			</p>
						    		</td>
						    	</tr>
						    	<tr><td>&nbsp;</td></tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight: initial; font-family:'Khmer OS Muol Light';">
						    			III. ព័ត៌មានអ្នកធានា
						    			<div class="border"></div>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-family:'Khmer OS Battambang';">
						    			<p class="padding-left">
						    				<label class="title">ឈ្មោះ </label> : <label class="value"><?php echo $rs['arid_no']; ?></label> <label class="title">លេខអត្តសញ្ញាណប័ណ្ណ</label> : <label class="value"><?php echo $rs['refe_nation_id'];?></label> 
						    			</p>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td style="font-size:14px; font-weight: initial; font-family:'Khmer OS Muol Light';">
						    			IV. ព័ត៌មានការលក់
						    			<div class="border"></div>
						    		</td>
						    	</tr>
						    	<tr>
						    		<td >
						    			<table class="content-data" border="1"​ cellspacing="0" style="font-size:12px !important; font-family:'Khmer OS Battambang';">
						    				<tr class="style-head">
											  <?php 
											 ?>
												<td rowspan="2"><?php echo $tr->translate("NUM");?></td>
												<td colspan="10"><?php echo $tr->translate("SALE_INFO");?></td>
												<td colspan="2"><?php echo $tr->translate("PAYMENT_INFO");?></td>
												<td rowspan="2"><?php echo $tr->translate("AGENTCY");?></td>
												<td rowspan="2"><?php echo $tr->translate("STATUS");?></td> 
											 </tr>
							                 <tr class="style-head">
							                    <td><?php echo $tr->translate("BRANCH_NAME");?></td>
							                    <td><?php echo $tr->translate("PROPERTY_CODE");?></td>
							                    <td><?php echo $tr->translate("AMOUNT_PROPERTY");?></td>
							                    <td><?php echo $tr->translate("BUY_DATE");?></td>
							                    <td><?php echo $tr->translate("END_DATE");?></td>
							                    <td><?php echo $tr->translate("TYPE");?></td>
							                    <td><?php echo $tr->translate("PRICE_BEFORE");?></td>
							                    <td><?php echo $tr->translate("DISCOUNT");?>$</td>
							                    <td><?php echo $tr->translate("DISCOUNT_PERCENT");?></td>
							                    <td><?php echo $tr->translate("SOLD_PRICE");?></td>
							                    <td><?php echo $tr->translate("PAID_PRINCIPAL");?></td>
							                    <td><?php echo $tr->translate("REMAIN");?></td>
							                </tr>
							                <?php 
							                $totalSale = 0;
							                $paid=0;
							                $paidAmount=0;
							                if(!empty($this->saleList)) foreach($this->saleList as $key=> $row){
							                	if(!empty($row['old_land_id'])){
							                		$idse = explode(",", $row['old_land_id']);
							                		$countland = count($idse);
							                	}else{
							                		$countland = 1;
							                	}
							                	if($row['is_cancel']!=1){
								                	$paidAmount = $row['totalpaid_amount']+$row['totalAmountCreadit'];
								                	$paid = $paid+$paidAmount;
								                	$totalSale = $totalSale+$row['price_sold'];
							                	}
							                	?>
							                	<tr class="style-rowdata hover context-menu-one" oncontextmenu="setrowdata(<?php echo $row['id'];?>);return false;" >
														<td align="center"><?php echo $key+1; ?></td>
														<td><span style="line-height: 18px;white-space: pre-wrap !important;max-width: 150px;width: 150px;display: block;font-size: 11px;overflow-wrap: break-word;text-align: left;vertical-align: top; font-weight: 600;" ><?php echo $row['branch_name']; ?></span></td>
														<td><span style="line-height: 18px;white-space: pre-wrap !important;max-width: 150px;width: 150px;display: block;font-size: 11px;overflow-wrap: break-word;text-align: left;vertical-align: top; font-weight: 600;" ><?php echo $row['land_address']." ".$row['street']; ?></span></td>
														<td align="center"><?php echo $countland ?></td>
														<td style="white-space:nowrap;"><?php echo date($montFomat,strtotime($row['buy_date'])); ?></td>
														<td style="white-space:nowrap;" ><?php $date= new DateTime($row['end_line']); echo $date->format($montFomat); ?></td>
														<td><?php echo $row['paymenttype']; ?></td>
														<td align="right"><span style="line-height:15px;"><?php echo number_format($row['price_before'],2); ?></span></td>
														<td align="right" style="white-space:nowrap;">
														<?php 
															$other_discount = empty($row['other_discount'])?0:$row['other_discount'];
															echo number_format($row['discount_amount']+$other_discount,2);
															
														?></td>	
														<td align="center" style="white-space:nowrap;"><?php echo number_format($row['discount_percent'],2); ?></td>
														<td align="right" style="white-space:nowrap;"><?php echo number_format($row['price_sold'],2); ?></td>	
														<td align="right" style="white-space:nowrap; text-align: right;"><?php echo number_format($paidAmount,2);//echo number_format($row['paid_amount'],2);?></td>
														<td align="right" style="white-space:nowrap;"><?php echo number_format($row['price_sold']-$paidAmount,2); //echo number_format($row['price_sold']-$row['paid_amount'],2); ?></td>
														<td><?php echo $row['staff_name']; ?></td>
														<td><?php echo $row['isCancel']; ?></td>
													</tr>
							                <?php }?>
							                <tr style="border: 1px solid #fff;border-top: 1px solid #000;font-weight: bold;">
							                	<td colspan="11" align="right"><?php echo number_format($totalSale,2); ?></td>
							                	<td align="right"><?php echo number_format($paid,2); ?></td>
							                	<td align="right"><?php echo number_format($totalSale-$paid,2); ?></td>
							                	<td colspan=" 2"></td>
							                </tr>
						    			</table>
						    		</td>
						    	</tr>
						    </table>
					   </td>
					</tr>
	  		 	</table>
	   		</div>
		 </div>	
<iframe style="font-size: 10px; !important;" name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function preview()
{ 
  var disp_setting="toolbar=no,status=no,resizable=no,location=no,directories=yes,menubar=no,"; 
      disp_setting+="scrollbars=no,width=1100, height=700, left=100, top=25"; 
  var content_vlue = document.getElementById("divPrint").innerHTML; 
  
  var docprint=window.open("","",disp_setting); 
   docprint.document.open(); 
   docprint.document.write('<html><head>'); 
   docprint.document.write('</head><div style=" font-size:16px !important; margin:0px; font-family:Verdana;"><style>table th {font-size:14px !important;} table td{font-size:12px !important;}</style><center>');          
   docprint.document.write(content_vlue);          
   docprint.document.write('</center></div></html>'); 
   docprint.document.close(); 
   docprint.focus(); 
}
function doPrint() {
	window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
    window.frames["print_frame"].window.focus();
    window.frames["print_frame"].window.print();
    hideDialog();
}
</script>