<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate("EDIT_PRODUCT_CATEGORY"));
	$baseurl =  Zend_Controller_Front::getInstance()->getBaseUrl();
 	$frm_degree= $this->frm_degree;
 	
?>	
<script src="<?php echo $baseurl;?>/js/help.js"></script>
<script type="text/javascript">
    dojo.require("dojo.NodeList-manipulate");
    dojo.require("dojo.parser");
    dojo.require("dijit.form.Textarea");
</script>
<style>
.dijitTextArea[cols].dijitTextArea[cols]{
	width: 99%;
}
ul.opt-school {
    list-style-type: none;
}
 input[type=checkbox],  input[type=radio]{
	height: 15px;
    display: initial;
}
</style>
<div class="card">
	<div class="card-content collapse show">
		<div class="card-box">
       		<div class="col-sm-12 border-botom">
		    	<div class="col-sm-8 pd-0">
	    			<h4 class="m-b-0"><i class="fa fa-edit " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('EDIT_PRODUCT_CATEGORY');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<form  id='edit-dept' action="" dojoType="dijit.form.Form" method="post" enctype="application/x-www-form-urlencoded">
			<script type="dojo/method" event="onSubmit">   
  				 if(this.validate()) {
					 loadingBlock();
    				return true;
   				}else {
    				return false;
  				 }
			</script>
			<div class="card-box">
				<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-sitemap" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("PRODUCT_CATEGORY");?></p>
										</div> 
									</div>
									<div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("TITLE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_degree->getElement("title");?>
											<?php echo $frm_degree->getElement("id");?>
										</div>
									 </div>
									
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("NOTE");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_degree->getElement("note");?>
										</div>
									 </div>
									 <div class="form-group">
										<label class="control-label bold col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?> </label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm_degree->getElement("status");?>
										</div>
									 </div>
								 </div>
							 </div>
						 </div>
					 </div>
		         </div>
		         <div class="col-md-4 col-sm-4 col-xs-12">
		       
		         </div>
		         <div class="clearfix"></div>
		         <div class="card-box mt-20">
	               	<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
						<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk"  label="<?php echo $tr->translate("GO_EDIT");?>" id="submitButton"  dojoType="dijit.form.Button" />
	               	</div>
	             </div>
	    	</div>
		</form>
    </div>
</div>

<script type="text/javascript">
dojo.require("dojo.date.locale");
dojo.require("dojo.data.ObjectStore");
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dojo.store.Memory");
//dojo.require('dojox.form.BusyButton');
dojo.require("dojo.html");
dojo.ready(function(){
	/*getValue();*/
});


/*function getValue(){
	var par='';
	if(dojo.byId('is_parent').checked){
		par = 1;
		dijit.byId('parent').attr('value','');
		dijit.byId("parent").set('readOnly',true);
		 dijit.byId('parent').set('required',false);  
	}else{
		par=0;
		dijit.byId("parent").set('readOnly',false);
		 dijit.byId('parent').set('required',true);  
	}
	$('#par').val(par);
}*/
function CheckAllTotal(index){
	if(index==0){
			if($('#check_all').is(":checked")){
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = true;  
				});
			}else{
				$('.checkbox').each(function() { //loop through each checkbox
		            this.checked = false;  
				});
			}
	}else{
		var a = $("input:checked").val();
		 var identity = [];
	     $(':checkbox:checked').each(function(i){
	    	 identity[i] = $(this).val();
	     });
	     var allidentity = $("#identityCheck").val();
		if(identity == allidentity ){
			$('#check_all').prop('checked', true); // checks it
		}else{
			$('#check_all').prop('checked', false); // Unchecks it
		}
	}
}
</script>
