<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$day = array(
		"Mon" =>'ច័ន្ទ',
		"Tue" =>'អង្គារ',
		"Wed" =>'ពុធ',
		"Thu" =>'ព្រហស្បតិ៍',
		"Fri" =>'សុក្រ',
		"Sat" =>'សៅរ៍',
		"Sun" =>'អាទិត្យ',
	);
	$month = array("01"=>"មករា","02"=>"កុម្ភៈ","03"=>"មីនា","04"=>"មេសា","05"=>"ឧសភា","06"=>"មិថុនា","07"=>"កក្កដា","08"=>"សីហា","09"=>"កញ្ញា","10"=>"តុលា","11"=>"វិច្ឆិកា","12"=>"ធ្នូ",);
	$dbparmeter = new Report_Model_DbTable_DbParamater();
	$key = new Application_Model_DbTable_DbKeycode();
	$dataterm = $key->getKeyCodeMiniInv(TRUE);
	$arrgender = array(1=>"ប្រុស",2=>"ស្រី");
?>
<script>
dojo.require("dijit.form.DateTextBox");
</script>
<script src="<?php echo $this->baseUrl();?>/js/pdbs_js.js"  type="text/javascript"></script>
<meta charset="utf-8">
<title style="color:#fff;"><?php echo $tr->translate("AGREEMENT");?></title>
<style>
	#divPrint .reff{ font-size: 20px !important; line-height:34px !important;}
	#divPrint tr td h2,#divPrint p, #divPrint pre, #divPrint span,#divPrint tr td{
		font-size: 20px !important; line-height:35px !important;
    }
	#divPrint #padding-left-p-2{
	 	padding-left: 105px !important;	
	}
	#divPrint .padding-buttom{
		margin-top: -5px !important;
	}
	#mainbody{
		display: block !important;
	    position: relative !important;
	}
	#watermark{
		display: none !important;	
	}
	ul.blogsub li{
		line-height:34px !important;
	}
	#printfooter{display: none !important;}
	body{
		margin:0 !important;
	}
</style>
	<div  id="exportword" style="min-height:22cm; margin:0 auto;padding:0px 0.5cm">
		<table style="font-family: 'Khmer OS Content'; width:100%;"  >
			<tr>
			    <td align="center">
						<div id="divPrint" style="position: relative;" >
					    	 	<style>		
									#padding-left-p-2{
										padding-left:105px !important;	
									}
									.padding-buttom{
										margin-top:-10px !important;
									}
									tr td,tr td h2,p,pre,span{ 
										font-size: 16px ; line-height:30px !important;
									}
									#padding-left{
										padding-left: 18px;
									}
									#bold-padding-right{
										margin-right:15px;
										font-family:'Times New Roman','Khmer OS Siemreap';
									}
									#padding-left-2{
									
										padding-left:15px;
									}
									#padding-left-p-2{
									   margin-top:-1px; 
									   padding-left: 85px;	
									}
									#padding-left-p{
										padding-left: 105px;
									}
									th{padding: 5px;}
									span.value{ line-height:10px;display: inline-block; text-align: center;}
									span.child {display:block; margin-left:25px; line-height: 22px;}
									.value_label{
								        border-bottom: dashed 1px #000;
									    line-height: 12px !important;
									    min-width: 100%;
									    display: inline-block;
									}
									body{
									    position: relative;
									}
									#printfooter {
									    position: absolute;
									    bottom: 0;
									    position: fixed;
									    display: block ;
									}
									span.margin-left{
										margin-left:35px; display: inline-block;
									}
									ul.blogsub li{
										list-style-type: square;
										line-height: 24px;
									}
									ul.reference li{
										line-height: 24px;
										list-style: none;
									}
									ul.blogsub{
										padding:0;margin:0;
									}
									#printfooter {
									    position: absolute;
									    bottom:-5;
									    position: fixed;
									    display: block ;
									}
									body {
										margin:0.4cm 0.4cm 0cm 0.4cm;
									}
									ul.border-land {
										margin: 0;
										padding: 0;
										display: block;
										width: 100%;
										padding-left: 65px;
									}
									ul.border-land li {
										float: left;
										width: 50%;
										list-style: none;
									}
									span.property_note{
										white-space: pre-line; display: block; width: 100%; margin-left: 65px;
									}
									strong {
										font-weight:bold !important;
									}
									@media print {
									  table.breakPage {page-break-after: always;}
										@page {
										  margin-bottom:0cm;
										}
									}
									
								</style>
							       	<table class="breakPage" width="100%" style="font-family:'Times New Roman','Khmer OS Siemreap'; padding:0; margin:0;border:0px;" >
								        	<tr>
								                <td width="30%" valign="top" style="text-align: center;">
												<?php $imagelogo = $this->baseUrl()."/images/logo.jpg";
													if (!empty($this->agreement['project_logo'])){
														$imagelogo = $this->baseUrl()."/images/projects/".$this->agreement['project_logo'];
													}
													?>
													<img src="<?php echo $imagelogo;?>" style="max-width:100%; height: 80px; margin-top: 10px;">
												</td>
								                <td width="40%" align="center" valign="top">
								                	<span style=" font-family:'Khmer OS Muol Light'; text-align:center; line-height:40px !important; font-size:18px; ">ព្រះរាជាណាចក្រកម្ពុជា</span>
									                <span style=" font-family:'Khmer OS Muol Light'; text-align:center; line-height:40px !important; width: 100%; display: block; font-size:16px; "><?php echo $tr->translate("ជាតិ សាសនា ព្រះមហាក្សត្រ");?></span>
									                <span style=" text-align:center;line-height:55px !important;margin:30px 0px; width: 100%; display: block; font-size:15px; font-family: 'Tacteing';"><img src="<?php echo $this->baseUrl();?>/images/style.png" height="12px"></span>
									                <span style=" font-family:'Khmer OS Muol Light'; padding:2px 0; text-align:center; line-height:28px; width: 100%; display: block; font-size:16px; "><?php echo $tr->translate("កិច្ចសន្យាលក់-ទិញផ្ទះ");?></span>
						              			</td>
								                <td width="30%"></td>
								             </tr>
											 
											 <tr>
												<td colspan="3" align="center">
								                	<span style="text-align:center; line-height:28px; width: 100%; display: block; ">កិច្ចសន្យានេះធ្វើនៅ	សៀមរាប   ថ្ងៃទី  <?php echo date("d",strtotime($this->agreement['agreement_date']));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo date("Y",strtotime($this->agreement['agreement_date']));?> <br />
								                	<span style="font-family:'Khmer OS Muol Light';">រវាង</span></span>
								             	</td>
								             </tr>
											 <tr>
												  <td colspan="3" align="center">
												  </td>
											 </tr>
											 
											 <tr>
								             	<td colspan="3" style="text-align: justify;">
													<?php 
														$sex="ប្រុស";
														$title="លោក";
														if($this->agreement['p_sex']==2){
															$sex="ស្រី";
															$title="លោកស្រី";
														}
														$sexWithManager="ប្រុស";
														$titleWithManager="លោក";
														if($this->agreement['w_sex']==2){
															$sexWithManager="ស្រី";
															$titleWithManager="លោកស្រី";
														}
														$project_location=$this->agreement['project_location'];
														$address=$tr->translate("ADDRESS_COMPANY");//"ផ្ទះលេខ ៥សេ ផ្លូវជាតិលេខ៤ ភូមិកន្ទោកជើង សង្កាត់កន្ទោក ខណ្ឌពោធិ៍សែនជ័យ រាជធានី ភ្នំពេញ";
														$wing_phone_getMoney="070 924 701";
													?>
													
								             		<span style="margin:0 auto;font-family:'Times New Roman','Khmer OS Siemreap';text-align: justify; text-justify: inter-word;font-weight: normal !important;">
														<span style="text-align:left; min-width: 100%; display: inline-block;">
															<span class="margin-left">&nbsp;</span>
															<?php echo $title;?> <span style=" font-weight:600;"><?php echo $this->agreement['project_manager_namekh'];?></span>
															ភេទ <span class="value" ><?php echo empty($arrgender[$this->agreement['p_sex']])?"":$arrgender[$this->agreement['p_sex']];?></span> 
															អាយុ  
																<strong>
																<?php 
																	if (!empty($this->agreement['manager_dob'])){ 
																		$from = new DateTime($this->agreement['manager_dob']);
																		$to   = new DateTime($this->agreement['buy_date']);
																		echo $dbparmeter->getNumberInkhmer($from->diff($to)->y);
																	}
																	?>
																</strong>
															ឆ្នាំ  
															សញ្ជាតិ<?php echo $this->agreement['project_manager_nationality'];?>
															 កាន់អត្តសញ្ញាណប័ណ្ណលេខ  <span class="value" style="min-width:30px; font-weight:600;"><?php echo $this->agreement['project_manager_nation_id'];?></span> 
															
															<?php if(!empty($this->agreement['w_manager_namekh'])){?>
															<strong>និង</strong> <?php echo $titleWithManager;?> <span style=" font-weight:600;"><?php echo $this->agreement['w_manager_namekh'];?></span>
															ភេទ <span class="value" ><?php echo empty($arrgender[$this->agreement['w_sex']])?"":$arrgender[$this->agreement['w_sex']];?></span> 
															អាយុ  
																<strong>
																	<?php 
																	if (!empty($this->agreement['w_dob'])){ 
																		$from = new DateTime($this->agreement['w_dob']);
																		$to   = new DateTime($this->agreement['buy_date']);
																		echo $dbparmeter->getNumberInkhmer($from->diff($to)->y);
																	}
																	?>
																</strong>
															ឆ្នាំ  
															សញ្ជាតិ<?php echo $this->agreement['w_manager_nationality'];?> 
															កាន់អត្តសញ្ញាណប័ណ្ណលេខ  <span class="value" style="min-width:30px; font-weight:600;"><?php echo $this->agreement['w_manager_nation_id'];?></span> 
															<?php }?>
															មានទីលំនៅ<?php echo $this->agreement['project_manager_p_current_address'];?> 
															ត្រូវបានហៅថាជា(ម្ចាស់គម្រោង) ឬ<strong>ភាគី(ក)</strong> ។
														</span>
														<span style="font-family:'Khmer OS Muol Light'; text-align:center; min-width: 100%; display: inline-block;">និង</span>
														<span style="text-align:left; min-width: 100%; display: inline-block;">
														
														<?php 
															$sexClient="ប្រុស";
															$titleClient="លោក";
															if($this->agreement['sex']==2){
																$sexClient="ស្រី";
																$titleClient="លោកស្រី";
															}
															$sexWithClient="ប្រុស";
															$titleWithClient="លោក";
															if($this->agreement['ksex']==2){
																$sexWithClient="ស្រី";
																$titleWithClient="លោកស្រី";
															}
														?>
															<span class="margin-left">&nbsp;</span>
															<?php echo $titleClient;?> <span class="value" style="min-width:30px; font-weight:600;"><?php echo $this->agreement['client_namekh'];?></span>
															ភេទ <span class="value" style="min-width:30px;"><?php echo $this->agreement['sexKh'];?></span> 
															អាយុ  
																<?php 
																	if (!empty($this->agreement['dob'])){ 
																		$from = new DateTime($this->agreement['dob']);
																		$to   = new DateTime($this->agreement['buy_date']);
																		echo $dbparmeter->getNumberInkhmer($from->diff($to)->y);
																	}
																	?>
															ឆ្នាំ  
															សញ្ជាតិ<?php echo $this->agreement['client_nationality'];?> 
															កាន់<?php echo $this->agreement['client_d_type'];?>លេខ <span class="value" style="min-width:30px; font-weight:600;"><?php echo $this->agreement['client_nation_id'];?></span>	
															មានទីលំនៅភូមិ <span ><?php echo str_replace("ភូមិ", "", $this->agreement['client_village_kh']);?></span>
															 ឃុំ/សង្កាត់  <span ><?php echo $this->agreement['client_commune_kh'];?></span>
															 ស្រុក/ខណ្ឌ/ក្រុង  <span ><?php echo $this->agreement['client_districtkh'];?></span>
															 ខេត្ដ/រាជធានី  <span >&nbsp;<?php echo $this->agreement['client_province_kh'];?></span> 
															 ដែលមានលេខទូរស័ព្ទ <span class="value" style="min-width:30px;"><?php echo $this->agreement['client_phone'];?></span>
															<?php if(!empty($this->agreement['hname_kh'])){?>
															<strong>និង</strong> <?php echo $titleWithClient;?> <span style="font-weight:600;"><?php echo $this->agreement['hname_kh'];?></span> 
															ភេទ <span class="value" style="min-width:30px;"><?php echo $this->agreement['partner_gender'];?></span> 
															អាយុ  
																<?php 
																	if (!empty($this->agreement['dob_buywith'])){ 
																		$from = new DateTime($this->agreement['dob_buywith']);
																		$to   = new DateTime($this->agreement['buy_date']);
																		echo $dbparmeter->getNumberInkhmer($from->diff($to)->y);
																	}
																	?>
															ឆ្នាំ  
															សញ្ជាតិ<?php echo $this->agreement['with_client_nationlity'];?> 
															កាន់<?php echo $this->agreement['joint_doc_type'];?>លេខ <span class="value" style="min-width:30px; font-weight:600;"><?php echo $this->agreement['rid_no'];?></span>  
															មានទីលំនៅភូមិ <span class="value" style="min-width:30px;"><?php echo str_replace("ភូមិ", "",$this->agreement['w_client_village_kh']);?></span>
															ឃុំ/សង្កាត់ <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_commune_kh'];?></span> 
															ស្រុក/ខណ្ឌ/ក្រុង <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_districtkh'];?></span> 
															ខេត្ត/រាជធានី  <span class="value" style="min-width:30px;"><?php echo $this->agreement['w_client_province_kh'];?></span> 
															 ដែលមានលេខទូរស័ព្ទ <span class="value" style="min-width:30px;"><?php echo $this->agreement['with_phone'];?></span>
															<?php }?> 
															ត្រូវបានហៅថា(អ្នកទិញផ្ទះ) ឬ<strong>ភាគី(ខ)</strong>។

														</span>
													</span>
													<span style="padding:10px 0; text-align:center; width: 100%; display: block; font-weight:200;font-family:'Khmer OS Muol Light';">គោលបំណងនៃកិច្ចសន្យា</span>
													<div style=" text-align:justify;">
														<?php 
															$projectName="អង្គរ អ៊ីកូ រ៉េស៊ីដេន (Angkor Eco Residence)";
															$amountProperty=1;
															 if (!empty($this->agreement['old_land_id'])){
																$idse = explode(",", $this->agreement['old_land_id']);
																$amountProperty = count($idse);
															}
														?>
														ដោយហេតុថាភាគី (ក) បានព្រមព្រៀងលក់ ផ្ទះចំនួន <strong><?php echo $dbparmeter->getNumberInkhmer($amountProperty);?></strong> ល្វែង ដែលមានលេខផ្ទះ <span class="value" style="min-width:70px; font-weight:600;"><?php echo $this->agreement['property_title'];?></span> 
														ដែលផ្ទះមាន
														<br />
														ទំហំៈ <strong><?php echo number_format($this->agreement['full_size'],2);?> m<sup>2</sup> (<span class="houseSizeKhmer"></span>ម៉ែត្រការ៉េ) </strong>  
														<span class="property_note"><?php echo $this->agreement['propertyTypeNote'];?></span> 
														
														<span class="margin-left">&nbsp;</span>ផ្ទះនេះស្ថិតនៅក្នុងគម្រោង <strong><?php echo $projectName; ?></strong>  ដែលមានទីតាំងនៅ<?php echo $this->agreement['project_location'];?>  
														សាងសង់នៅលើដីមានផ្ទៃក្រឡាសរុប <strong><?php echo number_format($this->agreement['property_land_size'],2);?> m<sup>2</sup> (<span class="landSizeKhmer"></span>ម៉ែត្រការ៉េ)</strong>
														បណ្តោយ <strong><?php echo $this->agreement['property_height'];?></strong> ម៉ែត្រ 
														ទទឹង <strong><?php echo $this->agreement['property_width'];?></strong> ម៉ែត្រ ដែលមានព្រំប្រទល់ៈ
														<ul class="border-land">
															<li>
																- ខាងជើងទល់នឹងៈ <?php echo $this->agreement['border_north'];?>
															</li>
															<li>
																- ខាងត្បូងទល់នឹងៈ <?php echo $this->agreement['border_south'];?>
															</li>
															<li>
																- ខាងលិចទល់នឹងៈ   <?php echo $this->agreement['border_west'];?>
															</li>
															<li>
																- ខាងកើតទល់នឹងៈ  <?php echo $this->agreement['border_east'];?>
															</li>
														</ul>
														<span class="margin-left">&nbsp;</span>
														អោយទៅភាគី (ខ)  ក្នុងការលក់-ទិញ នេះភាគីទាំងពីរបានព្រមព្រៀងគ្នានៅក្នុងតម្លៃជាក់លាក់ទៅលើទំហំទាំងមូល គឺចំនួន <strong>$<?php echo number_format($this->agreement['price_sold'],2);?></strong> ជាអក្សរ (<strong><span id="lable_pricekhmer" style="font-family:'Khmer OS Siemreap';"></span>ដុល្លារអាមេរិក</strong> )
														
														<script>
																
																fullSize ='<?php echo ($this->agreement['full_size']) ?>';
																fullSizeLabel=read_money_in_khmer(fullSize);
																
																
																decimalmoney_fullSizeLabel='<?php echo substr(number_format($this->agreement['full_size'],2),-2);?>';
																if(decimalmoney_fullSizeLabel>0){stringSplit='ចុច';}else{stringSplit="";}
																
																lastFullSizeLabel='<?php echo substr(number_format($this->agreement['full_size'],2),-1);?>';
																if(lastFullSizeLabel<=0){lastFullSizeLabel='';}
																fullSizeLabel = fullSizeLabel+""+stringSplit+""+read_in_khmer_from_10_to_99(decimalmoney_fullSizeLabel)+''+read_in_khmer_from_0_to_9(lastFullSizeLabel);
																$( ".houseSizeKhmer" ).html( fullSizeLabel );
																
																landfullSize ='<?php echo ($this->agreement['property_land_size']) ?>';
																landfullSizeLabel=read_money_in_khmer(landfullSize);
																
																decimalmoney_landfullSizeLabel='<?php echo substr(number_format($this->agreement['property_land_size'],2),-2);?>';
																if(decimalmoney_landfullSizeLabel>0){stringSplit='ចុច';}else{stringSplit="";}
																
																lastlandfullSize='<?php echo substr(number_format($this->agreement['property_land_size'],2),-1);?>';
																if(lastlandfullSize<=0){lastlandfullSize='';}
																landfullSizeLabel = landfullSizeLabel+""+stringSplit+""+read_in_khmer_from_10_to_99(decimalmoney_landfullSizeLabel)+''+read_in_khmer_from_0_to_9(lastlandfullSize);
																$( ".landSizeKhmer" ).html( landfullSizeLabel );
																
																
																a_sold ='<?php echo ($this->agreement['price_sold']) ?>';
																money_khmersold=read_money_in_khmer(a_sold);
																
																decimalmoney_khmersold='<?php echo substr(number_format($this->agreement['price_sold'],2),-2);?>';
																str_centsold = 'សេន';
																if(decimalmoney_khmersold>0){string_sold='និង';}else{string_sold="";str_cent_sold='';}
																last_number_sold='<?php echo substr(number_format($this->agreement['price_sold'],2),-1);?>';
																
																if(last_number_sold<=0){last_number_sold='';}
																money_khmersold = money_khmersold+" "+string_sold+" "+read_in_khmer_from_10_to_99(decimalmoney_khmersold)+''+read_in_khmer_from_0_to_9(last_number_sold)+''+str_cent_sold;
																dojo.byId('lable_pricekhmer').innerHTML=money_khmersold+" ";
														</script>
													</div>
													
													<span style="padding:10px 0; text-align:center; width: 100%; display: block; font-weight:200;font-family:'Khmer OS Muol Light';">
													លក្ខខណ្ឌនៃកិច្ចសន្យា<br />ការទូទាត់ប្រាក់ៈ
													</span>
													<div style=" text-align:justify;">
													<span class="margin-left">&nbsp;</span>
													- ភាគីទាំងពីរបានឯកភាពទូទាត់ប្រាក់ក្នុងការទិញ-លក់ផ្ទះនេះតាមគោលការណ៍តារាងបង់ប្រាក់ក្នុង <strong>ឧបសម្ព័ន្ធទី១</strong> ជាប្រាក់សុទ្ធ ឫតាមគណនីធនាគារ។
													</div>
												</td>
											</tr>
									</table>
									<table class="breakPage" width="100%" style="font-family:'Times New Roman','Khmer OS Siemreap'; padding:0; margin:0;border:0px;" >
								         <tr>
								             <td colspan="3" style="text-align: justify;">
									             <div style=" text-align:justify;">
													<span style="padding:25px 0; text-align:center; width: 100%; display: block; font-weight:200;font-family:'Khmer OS Muol Light';">
													ការទទួលខុសត្រូវចំពោះមុខច្បាប់
													</span>
													<span class="margin-left">&nbsp;</span>
													- <strong>ភាគី(ក) </strong>ជាអ្នករ៉ាប់រងរត់ការផ្លូវច្បាប់ដើម្បី កាត់ឈ្មោះ ផ្ទេរសិទ្ធិកាន់កាប់អចលនទ្រព្យ <strong>(ប្លង់រឹង) </strong>ជូនទៅ <strong>ភាគី(ខ)</strong> ។
													<br />
													<span class="margin-left">&nbsp;</span>- រាល់ការចំណាយក្នុងការផ្ទេរសិទ្ធិ ជាបន្ទុករបស់ <strong>ភាគី (ក)</strong>។
													<br />
													<span class="margin-left">&nbsp;</span>- <strong>ភាគី (ក)</strong> ជាអ្នកទទួលខុសត្រូវរាល់បញ្ហាផ្លូវច្បាប់ ក្នុងករណីមានផលប៉ះពាល់ដែលកើតឡើងពីការប្តឹងជំទាស់ ឬតវ៉ាក្នុងកំឡុងពេល និងក្រោយពេល លក់-ទិញផ្ទះ ប្រសិនបើមានការតវ៉ាពីអ្នកពាក់ព័ន្ធផលប្រយោជន៍ជាមួយ <strong>ភាគី(ក)</strong> ឬ សមាជិកគ្រួសារ ទាយាទ និងម្ចាស់បំណុលផ្សេងៗ ។
													<br />
													<span class="margin-left">&nbsp;</span>- បើមានការកែប្រែតម្លៃ ឬសម្រេចចិត្តឈប់លក់ពី <strong>ភាគី(ក)</strong> ត្រូវសងប្រាក់ទៅ <strong>ភាគី(ខ)</strong> ចំនួនពីរដង នៃប្រាក់ដែល <strong>ភាគី(ខ)</strong> បានទូទាត់រួច។
													<br />
													<span class="margin-left">&nbsp;</span>- បើ <strong>ភាគី(ខ)</strong> កែប្រែឈប់ទិញ  ឬប្រព្រឹត្តផ្ទុយពីលក្ខខណ្ឌខាងលើនេះ  ប្រាក់ដែលបានបង់ត្រូវចាត់ទុកជាអសារបង់។
													<br />
													<span class="margin-left">&nbsp;</span>- <strong>ភាគី(ក)</strong> ធានាក្នុងការជួសជុល ផ្ទះរយៈពេល 1ឆ្នាំ ជូន <strong>ភាគី(ខ)</strong> បន្ទាប់ពី <strong>ភាគី(ក)</strong> ប្រគល់ផ្ទះជូន ។ ករណីបើមានប្រធានសក្តិ និង គ្រោះធម្មជាតិមិនមែនជាការទទួលខុសត្រូវរបស់<strong>ភាគី(ក)</strong> ទេ។
													<br />
													<span class="margin-left">&nbsp;</span>- រាល់ការចំណាយក្នុងការតបណ្តាញ ទឹក-ភ្លើង ជាបន្ទុករបស់<strong>ភាគី(ក)</strong>។
													<br />
													<span class="margin-left">&nbsp;</span>- <strong>ភាគី(ក)</strong> ធានាសាងសង់ និងប្រគល់ផ្ទះជូន<strong>ភាគី(ខ)</strong> មិនលើសពី <?php echo empty($this->agreement['amount_build'])?" ...........":$dbparmeter->getNumberInkhmer(number_format($this->agreement['amount_build'],0));?> ខែបន្ទាប់ពីចុះកិច្ចសន្យា  លក់-ទិញ។ករណីបើមានប្រធានសក្តិ កើតឡើង    ភាគី  (ក)    សូមពន្យារពេលការសាងសង់ និង ប្រគល់ផ្ទះ   រយៈពេល៦ខែ បន្ថែមលើការកំណត់ខាងលើ។
													<br />
													<br />
													ភាគីទាំងពីរមិនអាចកែប្រែអ្វីទាំងអស់ បន្ទាប់ពីភាគីទាំងសងខាងបានផ្តិតមេដៃប្រគល់ និងទទួលប្រាក់កក់ ហើយភាគីទាំងសងខាង ត្រូវទុកពេលវេលាជូនគ្នាទៅវិញទៅមក អោយបានសមស្រប ដើម្បីបំពេញកាតព្វកិច្ចតបស្នង ទៅតាមលក្ខខណ្ឌនៃកិច្ចសន្យាខាងលើ។
													<br />
													<span class="margin-left">&nbsp;</span>កិច្ចសន្យានេះចូលជាធរមានចាប់ពីថ្ងៃដែលភាគីទាំងពីរ   បានផ្តិតមេដៃទុកជាភស្តុតាងខាងក្រោមនេះតទៅ។
													<br />
													<span class="margin-left">&nbsp;</span>បើភាគីណាមួយមិនគោរពតាមកិច្ចសន្យា ឬមានចេតនាធ្វើអោយខូចខាត ឬប្រព្រឹត្តផ្ទុយពីលក្ខខណ្ឌ នៃកិច្ចសន្យាខាងលើ ភាគីនោះនឹងត្រូវទទួលខុសត្រូវចំពោះមុខច្បាប់ជាធរមាន។
													<br />
													<span class="margin-left">&nbsp;</span>កិច្ចសន្យានេះធ្វើឡើងជាភាសាខ្មែរ និងមានចំនួន02ច្បាប់ ត្រូវបានរក្សាទុកនៅភាគីទាំងសងខាង ចំនួនមួយច្បាប់ម្នាក់។
												</div>								
											</td>
										</tr>
										<tr>
												<td colspan="3" valign="top">
													<div style="  text-align: right;  margin-right: 40px;">
														ថ្ងៃទី <?php echo date("d",strtotime($this->agreement['agreement_date']));?> ខែ <?php echo $month[date("m",strtotime($this->agreement['agreement_date']))];?> ឆ្នាំ <?php echo date("Y",strtotime($this->agreement['agreement_date']));?>
													</div>
													<div>
														<div style="font-family:'Khmer OS Muol Light'; width:28%; text-align: center; display: inline-block;">
															<span class="value">ស្នាមមេដៃភាគី (ក)</span>
														</div>
														<div style="font-family:'Khmer OS Muol Light'; width:20%; text-align: center; display: inline-block;">
															<span class="value">សាក្សីទី១</span>
														</div>
														<div style="font-family:'Khmer OS Muol Light'; width:20%; text-align: center; display: inline-block;">
															<span class="value">សាក្សីទី២</span>
														</div>
														<div style="font-family:'Khmer OS Muol Light'; white-space:nowrap; width:28%; text-align: center; display: inline-block;">
															<span class="value">ស្នាមមេដៃភាគី (ខ)</span>
														</div>
														<div style="height: 110px;">
														</div>
														<div style="width:28%;text-align: center; display: inline-block;">
															<span class="border_bt  value" style="width:80%;" >&nbsp;<strong><?php echo $this->agreement['project_manager_namekh']; echo empty($this->agreement['w_manager_namekh'])?"":"-".$this->agreement['w_manager_namekh'];?></strong></span>
														</div>
														<div style="width:20%; text-align: center; display: inline-block;">
															<span class="border_bt  value" style="width:80%;" ><strong><?php echo $this->agreement['witness_i'];?></strong></span>
														</div>
														<div style="width:20%; text-align: center; display: inline-block;">
															<span class="border_bt  value" style="width:80%;" ><strong><?php echo $this->agreement['witness_ii'];?></strong></span>
														</div>
														<div style="width:28%; text-align: center; display: inline-block;">
															<span class="border_bt  value" style="width:80%; white-space: nowrap;text-align: center;" >&nbsp;&nbsp;<strong><?php echo $this->agreement['client_namekh'];echo (!empty($this->agreement['hname_kh']))?"-".$this->agreement['hname_kh']:"";?></strong>&nbsp;</span>
														</div>
													</div>
												</td>
											 </tr>
									</table>
								  <div id="printfooter" style=" font-size: 8px;font-family:'Khmer OS Siemreap';width:100%;">
										<span style=" font-size: 10px;"></span>
								  </div> 
							</div>
					
			    </td>	
			</tr>
		</table>
	</div>
<script>
function doPrint() {
		window.frames["print_frame"].document.body.innerHTML=dojo.byId('divPrint').innerHTML;
	    window.frames["print_frame"].window.focus();
	    window.frames["print_frame"].window.print();
	    hideDialog();
}
</script>