<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	echo $this->headTitle($tr->translate('CREATE_INVESTMENT'));
	$frm = $this->frm;
?>
<div class="card">
	<div class="card-content collapse show">
		<form  action="" enctype="multipart/form-data" dojoType="dijit.form.Form" method="post">
			<script type="dojo/method" event="onSubmit">			
				if(this.validate()) {
					investor_id = dijit.byId('investor_id').get('value');
					if(investor_id==0 || investor_id==""){
						infoMessageAlert("<?php echo $tr->translate("PLEASE_SELECT_INVESTOR");?>");
						dijit.byId('investor_id').focus();
						return false;
					}

					amount = dijit.byId('amount').get('value');
					if(amount==0 || amount==""){
						infoMessageAlert("<?php echo $tr->translate("PLEASE_ENTER_AMOUNT_INVEST");?>");
						dijit.byId('amount').focus();
						return false;
					}
					period = dijit.byId('duration').get('value');
					if(period==0){
						infoMessageAlert("<?php echo $tr->translate("PLEASE_ENTER_DURATION_INVEST");?>");
						dijit.byId('duration').focus();return false;
					}
					identity= $("#identity").val();
					if(identity=='' || identity==null){
						infoMessageAlert("<?php echo $tr->translate("PLEASE_ADD_RECORD_INVESTOR_SCHEDULE");?>");
						addRow();
						return false;
					}
					
					broker_id = dijit.byId('broker_id').get('value');
					if(broker_id>0){
						broker_amount = dijit.byId('broker_amount').get('value');
						if(broker_amount==0 || broker_amount==""){
							infoMessageAlert("<?php echo $tr->translate("PLEASE_ENTER_BROKER_AMOUNT");?>");
							dijit.byId('broker_amount').focus();
							return false;
						}
						period = dijit.byId('broker_duration').get('value');
						if(period==0){
								infoMessageAlert("<?php echo $tr->translate("PLEASE_ENTER_DURATION_BROKER");?>");
								dijit.byId('broker_duration').focus();
								return false;
						}
						identity_broker= $("#identity_broker").val();
						if(identity_broker=='' || identity_broker==null){
							infoMessageAlert("<?php echo $tr->translate("PLEASE_ADD_RECORD_BROKER_SCHEDULE");?>");
							addRowBroker();
							return false;
						}
						amount_payment=0;
						var arrays = identity_broker.split(',');
						for(var i=0;i<arrays.length;i++) {
							row_amount = dijit.byId('total_payment_broker'+arrays[i]).get('value');
							row_amount=isNaN(row_amount)?0:row_amount;
							amount_payment = amount_payment + row_amount;
						}
						if(broker_amount>amount_payment){
							infoMessageAlert("<?php echo $tr->translate("TOTAL_AMOUNT_BROKER_SCHEDULE_NOT_ENOUGHT");?>");
							return false;
						}else if(broker_amount<amount_payment){
							infoMessageAlert("<?php echo $tr->translate("TOTAL_AMOUNT_BROKER_SCHEDULE_IS_OVER_BROKER_AMOUNT");?>");
							return false;
						}
					}

					loadingBlock();
					return true;
				} else {
					return false;
				}
			</script>
			<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-recycle " aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('CREATE_INVESTMENT');?></h4>
	    			</div>
	    			<div class="col-sm-4 text-right">
	    			</div>
	    		</div>
	    	</div>
	    	<div class="card-box">
	    		<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="fa fa-recycle" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("INVESTMENT");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("INVEST_NO");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('invest_no');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("INVESTOR");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('investor_id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("INVEST_DATE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('date');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("AMOUNT_INVEST");?> ($) :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('amount');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DURATION_INVEST").$tr->translate("YEAR");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('duration');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("NOTE");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('note');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	    		</div>
	    		<div class="col-md-6 col-sm-6 col-xs-12">
					<div class="card-blogform">
						<div class="card-body"> 
							<div class="row"> 
								<div class="col-md-12 col-sm-12 col-xs-12"> 
									<div class="d-flex"> 
										<div class="settings-main-icon ">
											<i class="glyphicon glyphicon-user" aria-hidden="true"></i>
										</div> 
										<div class="col-md-10 col-sm-10 col-xs-12"> 
											<p class="tx-20 font-weight-semibold d-flex "><?php echo $tr->translate("BROKER_INFO");?></p>
										</div> 
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BROKER");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('broker_id');?>
									   </div>
									</div>
									<div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BROKER_PROFIT");?> (%) :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('broker_percent');?>
									   </div>
									</div>
									 <div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("BROKER_AMOUNT");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('broker_amount');?>
									   </div>
									</div>
									 <div class="form-group">
									   <label class="control-label col-md-5 col-sm-5 col-xs-12" ><?php echo $tr->translate("DURATION");?> :
									   </label>
									   <div class="col-md-7 col-sm-7 col-xs-12">
											<?php echo $frm->getElement('broker_duration');?>
									   </div>
									</div>
								</div>
							</div>
						</div>
					</div>
	            </div>
	           
	    	</div>
	    	
	    	<div class="card-box">
		         <div class="col-md-12 col-sm-12 col-xs-12">
		          	 <div class="form-group">
                		 <div class="col-md-12 col-sm-12 col-xs-12 blog-left-content">
                		 	<div class="card-box">
					    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
							            <li class="nav-item active">
							                <a class="nav-link " data-toggle="tab" href="#panel211" role="tab">
							                <i class="fa fa-calendar ml-2"></i> <?php echo $tr->translate("INVESTOR_SCHEDULE");?></a>
							            </li>
						            <li class="nav-item">
						                <a class="nav-link" data-toggle="tab" href="#panel212" role="tab">
						                <i class="fa fa-calendar ml-2"></i> <?php echo $tr->translate("BROKER_SCHEDULE");?>
						                </a>
							        </li>
						        </ul>
						    </div>
						     <div class="col-md-12" style=" max-height: 400px; min-height;400px;   overflow-y: auto;">
						        <!-- Tab panels -->
						        <div class="tab-content vertical">
							        <!--Schedule Panel 1-->
							        <div class="tab-pane fade in active" id="panel211" role="tabpanel">
							        	<div  id="showrecord">
							        		<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;"><tbody><tr id="head-title" class="head-td" style="color:#000 !important;background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" align="center"></tr></tbody></table>
							        	</div>
							        	<input type="hidden" name="identity" id="identity"  value="" >
										<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-sort-by-attributes" label="<?php echo $tr->translate('ADD_INSTALLMENT');?>" dojoType="dijit.form.Button" onclick="addRow();" />
							        </div>
							        <!--/.Schedule Panel 1-->
							        <!--Schedule Panel 2-->
							        <div class="tab-pane fade in " id="panel212" role="tabpanel">
							        	<div  id="showrecord_broker"></div>
							        	<input type="hidden" name="identity_broker" id="identity_broker"  value="" >
										<input type="button" class="button-class button-primary" iconClass="glyphicon glyphicon-sort-by-attributes" label="<?php echo $tr->translate('ADD_INSTALLMENT');?>" dojoType="dijit.form.Button" onclick="addRowBroker();" />
							        </div>
							        <!--/.Schedule Panel 2-->
							     </div>
							 </div>
						</div>
					</div>
				</div>
			</div>
									    
	    	<div class="clearfix"></div>
			<div class="card-box">
				<div class="col-md-12 col-sm-12 col-xs-12 border-top mt-20 ptb-10 text-center">
					 <input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-remove"  value="save_close" tabindex="2" label="<?php echo $tr->translate('SAVECLOSE');?>" id="save_close" dojoType="dijit.form.Button" name="save_close" iconClass="dijitEditorIcon dijitEditorIconSave" /> 
					<input type="submit" class="button-class button-primary" iconClass="glyphicon glyphicon-floppy-disk"  value="SAVE_NEW" tabindex="1" label="<?php echo $tr->translate('SAVENEW');?>" id="save_new" dojoType="dijit.form.Button" name="save_new" iconClass="dijitEditorIcon dijitEditorIconSave"/> 
	    		</div>
	    	</div>
		</form>
	</div>
</div>
<style>	
.blog-left-content {
    min-height: 250px;
    border: 1px solid #eee;
    margin: 0 !important;
    padding: 10px !important;
    background: #f9f7f7;
}
table.collape {
    width: 99%;
}

table tr td input {
    height: auto;
    margin: 0 !important;
    vertical-align: top;
}
th.tdheader{
	background: #607D8B;
    color: #fff;
	border:#bfc6ca 1px solid;
	line-height: 20px;
}
table.collape th.tdheader{padding:5px 0px;}

.image-box {
    text-align: center;
}
.image-box img {
    width: 170px;
    height: 180px;
    border: solid 1px #eee;
}
.account-image {
    border: solid 1px #eee;
    width: 170px;
}
.button_browse {
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 45px;
    cursor: pointer;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 33px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 45px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
</style>
<script src="<?php echo $this->baseUrl();?>/js/help.js"></script>
<script type="text/javascript">
dojo.require("dijit.form.NumberTextBox");
dojo.require("dijit.form.DateTextBox");
dojo.require("dijit.form.TextArea");
dojo.require("dijit.Dialog");
dojo.require("dojo.NodeList-manipulate");
dojo.require("dojo.html");

dojo.ready(function(){
});
col=0;no=0;title=0;temp='';tempbroker="";
function addRow(){
	investor_id = dijit.byId('investor_id').get('value');
	if(investor_id==0 || investor_id==""){
			infoMessageAlert("<?php echo $tr->translate("PLEASE_SELECT_INVESTOR");?>");
			dijit.byId('investor_id').focus();
			return false;
	}

	amount = dijit.byId('amount').get('value');
	if(amount==0 || amount==""){
			infoMessageAlert("<?php echo $tr->translate("PLEASE_ENTER_AMOUNT_INVEST");?>");
			dijit.byId('amount').focus();
			return false;
	}
	
	period = dijit.byId('duration').get('value');
	if(period==0){infoMessageAlert("<?php echo $tr->translate("PLEASE_ENTER_DURATION_INVEST");?>");dijit.byId('duration').focus();return false;}

	no=0;title=0;temp=''; tempbroker=""; $('#identity').val('');
	dojo.byId("showrecord").innerHTML = '';
	tmp='<table id="table_row" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title" class="head-td" style="color:#000 !important;background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord").append(tmp);

	for(i=1;i<=period;i++){
			col++;no++;
			template='';
			template_broker="";
			if(title!=1){    
				temp+='<th><?php echo $tr->translate("DEL");?></th>';
				temp+='<th><?php echo $tr->translate("NUM");?></th>';
				temp+='<th><?php echo $tr->translate("DATE");?></th>';
				temp+='<th id="lbl_titlemetion" width="50px"><?php echo $tr->translate("PERCENT_RETURN");?></th>';
				temp+='<th id="lbl_titlemetion" width="130px"><?php echo $tr->translate("AMOUNT_RETURN");?></th>';
				temp+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title").append(temp);

				title=1;
				epx_date = dijit.byId("date").get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+1;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear()+1;
				var epx_date = y+'-'+ mm + '-'+dd ;
			}else{
				indexs = col-1;
				epx_date = dijit.byId("date_payment"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+1;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear()+1;
				var epx_date = y+'-'+ mm + '-'+dd ;
			}

				template+='<td width="47px"align="center"><img onclick="deleteRecord('+col+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
				template+='<td width="2%" align="center">'+no+'</td>';
				template+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment"+col+"' name='date_payment"+col+"' /></td>";
				template+='<td><input type="text" onkeyup="calCulateAmount('+col+')" class="fullside" required="true" data-dojo-type="dijit.form.NumberTextBox"  id="percent'+col+'" name="percent'+col+'" /></td>';			
				template+='<td><input class="fullside" onkeyup="calCulateAmount('+col+',2)" type="text" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment'+col+'" name="total_payment'+col+'" /></td>';			
				template+='<td> <input class="fullside" type="text"  name="remark'+col+'" id="remark'+col+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/><label id="subsub"></label></td>';

				
				tmp='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row'+col+'">';
				tmp+="</tr>";
				dojo.query("#table_row").append(tmp);
				
				
			if($("#identity").val()!="") {
				var identity = $("#identity").val();
				$("#identity").val(identity+','+col);
			} else {$("#identity").val(col);}
			dojo.html.set(dojo.byId("row"+col),template , {
			     parseContent: true,
			});
	}
}

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	dojo.query("#row"+index).remove();
	
	period = dijit.byId('duration').get('value');
	dijit.byId('duration').attr('value',period-1);
}

function calCulateAmount(index,revers=1){
	balance = dijit.byId('amount').get('value');
	if(revers==1){//% to value
	    percent = dijit.byId('percent'+index).get('value');
	    amount_payment = parseInt(balance*percent/100);
	    dijit.byId('total_payment'+index).attr('value',amount_payment);
   }else{//value to %
	   amount_payment =  dijit.byId('total_payment'+index).get('value');
	   percent = amount_payment*100/balance;
	   dijit.byId('percent'+index).attr('value',percent);
   }
	if(dijit.byId('percent'+index).get('value')>100){
		 infoMessageAlert("តម្លៃត្រូវបង់មិនអាចធំជាង ១០០ ភាគរយបានទេ !");
		 dijit.byId('percent'+index).attr('value',"");
		 dijit.byId('total_payment'+index).attr('value',"");
		 dijit.byId('percent'+index).focus();
     }
}


function getBrokerInfo(){
	var url_submit = '<?php echo $this->url(array('module'=>'invest','controller'=>'broker','action'=>'getbrokerinfo')); ?>';
	broker_id = dijit.byId('broker_id').get('value');
	if(broker_id=="" || broker_id==0){
		return false;
	}
	dojo.xhrPost({
	    url: url_submit,	
	    content:{ 
		    'broker_id':broker_id
		},
		handleAs:"json",	
		load: function(data) {
			 dijit.byId('broker_percent').set('value',data.percent_income);
			 calculateBrokerAmount(1);
		},
		error: function(e) {
		}
	});
}
function calculateBrokerAmount(revers=1){
	amount = dijit.byId('amount').get('value');
	if(amount==0 || amount==""){
		infoMessageAlert("<?php echo $tr->translate("PLEASE_ENTER_AMOUNT_INVEST");?>");
		dijit.byId('amount').focus();
		return false;
	}
	broker_id = dijit.byId('broker_id').get('value');
	if(broker_id=="" || broker_id==0){
		return false;
	}
	if(revers==1){//% to value
		broker_percent = dijit.byId('broker_percent').get('value');
	    amount_payment = parseInt(amount*broker_percent/100);
	    dijit.byId('broker_amount').attr('value',amount_payment);
	    
   }else{//value to %
	   amount_payment =  dijit.byId('broker_amount').get('value');
	   broker_percent = amount_payment*100/amount;
	   dijit.byId('broker_percent').attr('value',broker_percent);
   }
	if(dijit.byId('broker_percent').get('value')>100){
		 infoMessageAlert("តម្លៃត្រូវបង់មិនអាចធំជាង ១០០ ភាគរយបានទេ !");
		 dijit.byId('broker_percent').attr('value',0);
		 dijit.byId('broker_amount').attr('value',0);
		 dijit.byId('broker_percent').focus();
   }
}

col_broker=0;no_broker=0;title_broker=0;temp_broker='';
function addRowBroker(){
	broker_id = dijit.byId('broker_id').get('value');
	if(broker_id==0 || broker_id==""){
			infoMessageAlert("<?php echo $tr->translate("PLEASE_SELECT_BROKER");?>");
			dijit.byId('broker_id').focus();
			return false;
	}

	broker_amount = dijit.byId('broker_amount').get('value');
	if(broker_amount==0 || broker_amount==""){
			infoMessageAlert("<?php echo $tr->translate("PLEASE_ENTER_BROKER_AMOUNT");?>");
			dijit.byId('broker_amount').focus();
			return false;
	}
	
	period = dijit.byId('broker_duration').get('value');
	if(period==0){infoMessageAlert("<?php echo $tr->translate("PLEASE_ENTER_DURATION_BROKER");?>");dijit.byId('broker_duration').focus();return false;}

	no_broker=0;title_broker=0;temp_broker=''; $('#identity_broker').val('');
	dojo.byId("showrecord_broker").innerHTML = '';
	tmp='<table id="table_row_broker" width="100%" style="border-collapse: collapse; border:1px solid #ccc !important;">';
	tmp+='<tr id="head-title_broker" class="head-td" style="color:#000 !important;background:#eee; font-size: 12px; height: 30px;margin-bottom: 10px;" id="head_title" class="head-title" align="center"></tr>';
	tmp+='</table>';
	dojo.query("#showrecord_broker").append(tmp);

	for(i=1;i<=period;i++){
		col_broker++;no_broker++;
			template_broker="";
			if(title_broker!=1){    
				temp_broker+='<th><?php echo $tr->translate("DEL");?></th>';
				temp_broker+='<th><?php echo $tr->translate("NUM");?></th>';
				temp_broker+='<th><?php echo $tr->translate("DATE");?></th>';
				temp_broker+='<th width="130px"><?php echo $tr->translate("AMOUNT_RETURN");?></th>';
				temp_broker+='<th><?php echo $tr->translate("NOTE");?></th>';
				dojo.query("#head-title_broker").append(temp_broker);

				title_broker=1;
				
				epx_date = dijit.byId("date").get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+1;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;
			}else{
				indexs = col_broker-1;
				epx_date = dijit.byId("date_payment_broker"+indexs).get("value");
				var a = new Date(epx_date);
				mm = a.getMonth()+2;
				var dd = a.getDate();
				 if(dd<10){
					 dd = "0"+dd;
				}
				if(mm<10){
					 mm = "0"+mm;
				}
				var y = a.getFullYear();
				var epx_date = y+'-'+ mm + '-'+dd ;
			}

			template_broker+='<td width="47px"align="center"><img onclick="deleteRecordBroker('+col_broker+')" src="<?php echo $this->baseUrl();?>/images/Delete_16.png"></td>';
			template_broker+='<td width="2%" align="center">'+no_broker+'</td>';
			template_broker+="<td><input class='fullside' type='text' constraints="+"{datePattern:'dd/MM/yyyy'}"+" dojoType='dijit.form.DateTextBox' value='"+epx_date+"' id='date_payment_broker"+col_broker+"' name='date_payment_broker"+col_broker+"' /></td>";
			template_broker+='<td><input class="fullside" onkeyup="calCulateAmountBroker('+col_broker+',2)" type="text" required="true"  dojoType="dijit.form.NumberTextBox" id="total_payment_broker'+col_broker+'" name="total_payment_broker'+col_broker+'" /></td>';			
			template_broker+='<td> <input class="fullside" type="text"  name="remark_broker'+col_broker+'" id="remark_broker'+col_broker+'" dojoType="dijit.form.TextBox" placeholder="ផ្សេងៗ"/></td>';

				
				tmp_broker='<tr class="hover" style="border-bottom:1px solid #ccc;" id="row_broker'+col_broker+'">';
				tmp_broker+="</tr>";
				dojo.query("#table_row_broker").append(tmp_broker);
				
				
			if($("#identity_broker").val()!="") {
				var identity = $("#identity_broker").val();
				$("#identity_broker").val(identity+','+col_broker);
			} else {$("#identity_broker").val(col_broker);}
			dojo.html.set(dojo.byId("row_broker"+col_broker),template_broker , {
			     parseContent: true,
			});
	}
}
function calCulateAmountBroker(index,revers=1){
	broker_amount = dijit.byId('broker_amount').get('value');
	amount_payment =  dijit.byId('total_payment_broker'+index).get('value');
	if(amount_payment>broker_amount){
		infoMessageAlert("<?php echo $tr->translate("TOTAL_AMOUNT_BROKER_SCHEDULE_IS_OVER_BROKER_AMOUNT");?>");
		dijit.byId('total_payment_broker'+index).attr('value',broker_amount);
		return false;
	}
	/*
	
	if(revers==1){//% to value
	    percent = dijit.byId('percent_broker'+index).get('value');
	    amount_payment = parseInt(broker_amount*percent/100);
	    dijit.byId('total_payment_broker'+index).attr('value',amount_payment);
   }else{//value to %
	   amount_payment =  dijit.byId('total_payment_broker'+index).get('value');
	   percent = amount_payment*100/broker_amount;
	   dijit.byId('percent_broker'+index).attr('value',percent);
   }
	if(dijit.byId('percent_broker'+index).get('value')>100){
		 infoMessageAlert("តម្លៃត្រូវបង់មិនអាចធំជាង ១០០ ភាគរយបានទេ !");
		 dijit.byId('percent_broker'+index).attr('value',"");
		 dijit.byId('total_payment_broker'+index).attr('value',"");
		 dijit.byId('percent_broker'+index).focus();
     }
	*/
}
function deleteRecordBroker(index) {
	var identity = $('#identity_broker').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
	if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity_broker').val(strings);
	dojo.query("#row_broker"+index).remove();
	
	period = dijit.byId('broker_duration').get('value');
	dijit.byId('broker_duration').attr('value',period-1);
}
</script>